<?php
$this->headTitle($article->getCode());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Артикулы производителей'=>$this->url('producer', ['action' => 'article']),
            $article->getCode()=>$this->url('producer', ['action'=>'article-view', 'id'=>$article->getId()])
            ]);

?>
<h1>
    <?= $this->escapeHtml($article->getFullCode()); ?>    
</h1>
<table class="table table-striped">
    <tr>
        <td colspan="3">            
            <?php if ($prev):?>
                <a href="/producer/article-view/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getFullCode()?></a>
            <?php endif;?>            
        </td>
        <td colspan="3" align="right">
            <?php if ($next):?>
                <a href="/producer/article-view/<?= $next[0]->getId()?>"><?= $next[0]->getFullCode()?>&rarr;</a>
            <?php endif;?>                            
        </td>
    </tr>
    <?php $totalRawpriceCount = 0; ?>
    <?php $articleId = 0?>
    <?php    foreach ($rawpriceCountBySupplier as $row):?>
        <?php if ($articleId != $row['articleId']): ?>
            <?php $articleId = $row['articleId']?>
            <tr>
                <th>
                </th>
                <td colspan="4" align="right">
                    <b><?= number_format($articleManager->meanPrice($articleId), 2, '.', '') ?></b>
                    (<?= number_format($articleManager->dispersionPrice($articleId), 2, '.', '') ?>)
                </td>
                <td align="right">
                </td>
            </tr>
        <?php endif; ?>    
        <tr>
            <td colspan="6">
                <b><?= $row['supplierName'];?></b>
            </td>
        </tr>
        <?php $randRawprices = $articleManager->randRawpriceBy(['article' => $row['articleId'], 'supplier' => $row['supplierId']]);?>
            <?php foreach($randRawprices as $randRawprice):?>
                <tr>
                    <td>
                        <?= $randRawprice->getArticle();?>
                    </td>
                    <td>
                        <a href="<?= $this->url('producer', ['action' => 'unknown-view', 'id' => $randRawprice->getUnknownProducer()->getId()]);?>">
                            <?= $randRawprice->getUnknownProducer()->getName();?>
                        </a>   
                    </td>
                    <td>
                        <a href="<?= $this->url('rawprice', ['action' => 'view', 'id' => $randRawprice->getId()]);?>">
                            <?= $randRawprice->getGoodname();?>
                        </a>    
                    </td>
                    <td>
                        <?php foreach($randRawprice->getOemRaw() as $oemRaw): ?>
                        <span style="font-size: xx-small"><?= $oemRaw->getCode()?></span>
                        <?php endforeach;?>
                    </td>
                    <td align="right">
                        <?= number_format($randRawprice->getRealPrice(), 2, '.', '');?>
                    </td>
                    <td align="right">
                        <?= $randRawprice->getRealRest();?>
                    </td>
                </tr>
            <?php endforeach;?>                    
        <?php $totalRawpriceCount += $row['rawpriceCount']; ?>
    <?php endforeach;?>        
    <tr>
        <th colspan="4">
            Всего
        </th>
        <td align="right">
        </td>
        <td align="right">
            <b><?= $totalRawpriceCount ?></b>
        </td>
    </tr>
</table>

<?php print_r($vacabulary)?>
