<?php
$this->headTitle('Артикулы производителей');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Производители'=>$this->url('producer'),
            'Артикулы производителей'=>$this->url('producer', ['action'=>'article'])
            ]);

$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
?>

<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск по артикулу (не менее 3-х символов)">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/producer/article-content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric">ID</th>
                     <th data-field="code" data-formatter="linkFormatter">Код</th>
                     <th data-field="fullcode">Артикул</th>             
                     <th data-field="unknownProducer" data-formatter="unknownProducerFormatter">Производитель</th>             
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Строки прайсов
                    </div>
                    <div class="panel-body">
                        <?php foreach($stages as $stage):?>
                            <?php if ($stage['stage']):?>
                                <div>
                                     <?= $stage['rowCount']?> - привязаны
                                </div>     
                            <?php else:?>
                                <div>
                                    <?= $stage['rowCount']?> - не привязаны
                                </div>
                            <?php endif;?>
                        <?php endforeach;?>
                    </div>
                </div>    
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Всего артикулов
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?= $total?>
                        </div>
                        <div class="pull-right">
                            <button value="/producer/delete-empty-article/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Удаление пустых">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Заполнить ДН
                        </div>
                        <div class="pull-right">
                            <button value="/name/fill-fp-tree/" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить дерево наименований">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Пересчет ДН
                        </div>
                        <div class="pull-right">
                            <button value="/name/count-fp-tree/" class="btn btn-info btn-xs refresh-table-button"
                                    title="Пересчет поддержки">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Удалить пустые ДН
                        </div>
                        <div class="pull-right">
                            <button value="/name/delete-empty-fp-tree/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Удалить пустые узлы">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var $table = $('#table'),
        $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams() {
        var params = {offset: 0, limit: 10};
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function linkFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/producer/article-view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function unknownProducerFormatter(value){
        return [
            '<div class="pull-left">',
            '<a href="/producer/unknown-view/' + value.id + '" target="_blank">' + value.name + '</a>',
            '</div>'
        ].join('');         
    }
    
    function responseHandler(res) {
        return res;
    }    
</script>
