<?php
$this->headTitle($article->getCode());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Артикулы производителей'=>$this->url('producer', ['action' => 'article']),
            $article->getCode()=>$this->url('producer', ['action'=>'article-view', 'id'=>$article->getId()])
            ]);

?>
<h1>
    <?= $this->escapeHtml($article->getFullCode()); ?>    
</h1>
<table class="table table-striped">
    <tr>
        <td colspan="3">            
            <?php if ($prev):?>
                <a href="/producer/article-view/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getFullCode()?></a>
            <?php endif;?>            
        </td>
        <td colspan="3" align="right">
            <?php if ($next):?>
                <a href="/producer/article-view/<?= $next[0]->getId()?>"><?= $next[0]->getFullCode()?>&rarr;</a>
            <?php endif;?>                            
        </td>
    </tr>
    <tr>
        <td colspan="6" align="right">
            <?php if (count($articles) == 2):?>
                <?php $tokenIntersect = $articleManager->articleTokenIntersect($articles[0], $articles[1]);?>
                <?php if(count($tokenIntersect)):?>
                    <span class="label label-success"><?= implode(',', $tokenIntersect)?></span>
                <?php else:?>
                    <span class="label label-default">Нет одинаковых токенов</span>
                <?php endif;?>
            <?php endif;?>
            <?php $articleMeanPrice = $articleManager->articlesMeanPrice($articles);?>
            <?php $articleDispersion = $articleManager->articlesDeviation($articles);?>
            <b><?= number_format($articleMeanPrice, 2, '.', '') ?></b>
            (<?= number_format($articleDispersion, 2, '.', '') ?>)
            <?php if ($articleMeanPrice):?>
                (<?= number_format($articleDispersion/$articleMeanPrice, 2, '.', '') ?>)
            <?php endif; ?>                
        </td>
    </tr>
    <?php $totalRawpriceCount = 0; ?>
    <?php $articleId = $meanPrice = $dispersion = 0?>
    <?php    foreach ($rawpriceCountBySupplier as $row):?>
        <?php $randRawprices = $articleManager->randRawpriceBy(['article' => $row['articleId'], 'supplier' => $row['supplierId']]);?>
        <?php if ($articleId != $row['articleId']): ?>
            <?php $articleId = $row['articleId']?>
            <tr>
                <th>
                    
                </th>
                <th>
                    <?= $randRawprices[0]->getUnknownProducer()->getName()?>
                </th>
                <td colspan="4" align="right">
                    <?php $meanPrice = $articleManager->meanPrice($articleId);?>
                    <?php $dispersion = $articleManager->dispersionPrice($articleId);?>
                    <b><?= number_format($meanPrice, 2, '.', '') ?></b>
                    (<?= number_format($dispersion, 2, '.', '') ?>)
                    <?php if ($meanPrice):?>
                        (<?= number_format($dispersion/$meanPrice, 2, '.', '') ?>)
                    <?php endif; ?>    
                </td>
            </tr>
        <?php endif; ?>    
        <tr>
            <td colspan="6">
                <b><?= $row['supplierName'];?></b>
            </td>
        </tr>
        <?php foreach($randRawprices as $randRawprice):?>
            <tr>
                <td>
                    <?= $randRawprice->getArticle();?>
                    <?php if ($randRawprice->getStatusToken() == $randRawprice::TOKEN_PARSED):?>
                        <button value="/goods/assembly/<?= $randRawprice->getId() ?>" class="btn btn-info btn-xs refresh-button"
                                title="Создать">
                                Товар
                        </button>
                    <?php endif;?>
                    <div style="font-size: xx-small">
                        <?php if ($randRawprice->getGood()):?>
                            <a href="/goods/view/<?= $randRawprice->getGood()->getId()?>">
                                <?= $randRawprice->getGood()->getCode()?>
                            </a>
                            <a href="/producer/view/<?= $randRawprice->getGood()->getProducer()->getId()?>">
                                <?= $randRawprice->getGood()->getProducer()->getName()?>
                            </a>
                        <?php else:?>
                        <span color=''>
                            <?= $randRawprice->getStatusGoodName();?>                            
                        </span>
                        <?php endif;?>
                    </div>                         
                </td>
                <td>
                    <a href="<?= $this->url('producer', ['action' => 'unknown-view', 'id' => $randRawprice->getUnknownProducer()->getId()]);?>">
                        <?= $randRawprice->getUnknownProducer()->getName();?>
                    </a>   
                </td>
                <td>
                    <a href="<?= $this->url('rawprice', ['action' => 'view', 'id' => $randRawprice->getId()]);?>">
                        <?= $randRawprice->getGoodname();?>
                    </a>    
                    <?php $tokens = $randRawprice->getTokens(); ?>
                    <?php if(count($tokens)):?>  
                        <div>    
                            <?php foreach($tokens as $token):?>
                                <span style="font-size: xx-small; font-weight: <?= ($token->getStatus() == $token::IS_DICT) ? 'bold':'normal' ?>">
                                    <a href="/name/view-token/<?= $token->getId() ?>"><?= $token->getLemma() ?></a>
                                </span>
                            <?php endforeach;?>
                        </div>        
                    <?php endif;?>                                                
                </td>
                <td>
                    <?php $oemIntersect = $articleManager->oemIntersect($articleId, $randRawprice); ?>
                    <?php foreach($randRawprice->getOemRaw() as $oemRaw): ?>
                        <a href="<?= $this->url('oem', ['action' => 'view-on-code'], ['query' => ['code' => $oemRaw->getCode()]]);?>">
                            <span style="font-size: xx-small; color: <?= (in_array($oemRaw->getCode(), $oemIntersect)) ? 'green':'inherit' ?>"><?= $oemRaw->getCode()?></span>
                        </a>    
                    <?php endforeach;?>
                </td>
                <td align="right">
                    <span style="color: <?= ($this->articleManager->inSigma3($randRawprice->getRealPrice(), $articleMeanPrice, $articleDispersion)) ? 'inherit':'red'?>">
                        <?= number_format($randRawprice->getRealPrice(), 2, '.', '');?>
                    </span>
                </td>
                <td align="right">
                    <?= $randRawprice->getRealRest();?>
                </td>
            </tr>
        <?php endforeach;?>                    
        <?php $totalRawpriceCount += $row['rawpriceCount']; ?>
    <?php endforeach;?>        
    <tr>
        <th colspan="4">
            Всего
        </th>
        <td align="right">
        </td>
        <td align="right">
            <b><?= $totalRawpriceCount ?></b>
        </td>
    </tr>
</table>
