<?php
    use Application\Entity\Producer;

    $this->headTitle('Производители');

    $this->mainMenu()->setActiveItemId('rb');

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Производители'=>$this->url('producer'),
                ]);

?>


<h1>Производители</h1>
<!--<p>
<a class="btn btn-default" href="
    <?= $this->url('producer', ['action'=>'add']); ?>">
    Новый производитель
</a>
</p>-->

<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/producer/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                     <th data-field="aplId" data-type="numeric" data-sortable="true">AplId</th>
                     <th data-field="name" data-formatter="linkFormatter" data-sortable="true">Наименование</th>
                     <th data-field='goodCount' data-sortable="true">Товаров</th>
                     <th data-field='unknownProducerCount' data-sortable="true">НП</th>
                     <th data-field='supplierCount' data-sortable="true">Постащиков</th>
                     <th data-field='rawpriceCount' data-sortable="true">Строк прайсов</th>
                     <th data-field="status" data-formatter="statusFormatter">
                         <span data-toggle="tooltip" data-original-title="Загружать товары производителя">Б</span>
                     </th>             
                     <th data-field="" data-formatter="activeFormatter"></th>
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Всего наименований
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?= $total?>
                        </div>
                        <div class="pull-right">
                            <button value="/producer/assembly-producers/" class="btn btn-default btn-xs refresh-table-button"
                                    title="Генерация производителей">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                            <button value="/producer/delete-empty-producer/" class="btn btn-danger btn-xs refresh-table-button"
                                    title="Удаление пустых">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button> 
                        </div>
                    </div>
                </div>    
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Обработка и обновления
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Наименования
                        </div>
                        <div class="pull-right">
                            <button value="/producer/best-names" class="btn btn-default btn-xs refresh-table-button"
                                    title="Обновление наименований">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Количество товаров
                        </div>
                        <div class="pull-right">
                            <button value="/producer/update-producers-good-count" class="btn btn-default btn-xs refresh-table-button"
                                    title="Обновление количество товаров">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Обновление AplId
                        </div>
                        <div class="pull-right">
                            <button value="/apl/update-producer-apl-id/" class="btn btn-default btn-xs refresh-table-button"
                                    title="Обновление AplId">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table').bootstrapTable({
        onLoadSuccess: function(res){
//            $('#totalRow').html($('#table').bootstrapTable('getOptions').totalRows);
            $("[data-toggle='tooltip']").tooltip();
            $('.editableCheckBox').change(function() {
                $.ajax({
                    type: "POST",
                    url: $(this).attr('data-url'),
                    data: "pk="+$(this).attr('data-pk'),
                    success: function(msg){
//                      alert( "Прибыли данные: " + msg );
                    }
                });
            })        
        }
    });

    ok = $('#ok');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function activeFormatter(value, row){
        var url = '/producer/delete-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function statusFormatter(value, row){
        var checked = 'checked';
        if (value == <?= Producer::STATUS_RETIRED?>){
            checked = '';
        }
        return [
            '<input data-toggle="tooltip" class="editableCheckBox" \n\
                data-pk="'+row.id+'" data-url="/producer/producer-status-edit" type="checkbox" '+checked+'/>'
        ].join(''); 
    }     
    
    function responseHandler(res) {
        return res;
    }    
</script>

