<?php
use Application\Entity\UnknownProducer;

$this->headTitle($unknownProducer->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Неизвестные производители'=>$this->url('producer', ['action' => 'unknown']),
            $unknownProducer->getName()=>$this->url('producer', ['action'=>'unknown-view', 'id'=>$unknownProducer->getId()])
            ]);

?>
<div class="row">
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-10">
                <h1>
                    <?= $this->escapeHtml($unknownProducer->getName()); ?>    
                </h1>
                <?php if ($unknownProducer->getProducer()): ?>
                    <p>
                        Наименование в ТекДок: 
                        <a href="#" 
                            class="bootstrapEdit" data-type="text" 
                            data-pk="<?= $unknownProducer->getId()?>" 
                            data-name="nameTd" data-emptytext="<?= $unknownProducer->getName() ?>"
                            data-url="/producer/edit-unknown-producer-name-td">
                            <?= $unknownProducer->getNameTd() ?>    
                        </a>
                    </p>
                <?php endif; ?>    
                <input id="editableCheckBox" data-pk="<?= $unknownProducer->getId()?>" 
                       data-url="/producer/unknown-producer-status-edit" type="checkbox"
                       <?= ($unknownProducer->getStatus() == UnknownProducer::STATUS_ACTIVE) ? 'checked':''?>/>
                <label for="editableCheckBox">Загружать товары производителя</label>            
            </div>    
            <div class="col-md-2">
                <?php if ($unknownProducer->getRawpriceCount() == 0 && $unknownProducer->getSupplierCount() == 0):?>
                    <a style="font-size: calc" href="<?= $this->url('producer', ['action'=>'delete-unknown', 'id'=>$unknownProducer->getId()]); ?>">
                        Удалить
                    </a>
                <?php endif;?>
            </div>    
        </div>    
        <div class="row">
            <div class="col-md-12">
                <?php foreach($intersects as $intrsect):?>
                    <? 
                        $diff = 0;
                        if ($unknownProducer->getRawpriceCount()){
                            $diff = $intrsect['countCode']/($unknownProducer->getRawpriceCount());
                        } else {
                            continue;
                        }            
                    ?>
                    <span>
                        <a href="<?= $this->url('producer', ['action' => 'unknown-view', 'id' => $intrsect['unknown_producer_id']])?>">
                            <?= $intrsect['unknown_producer_name']?>
                        </a>
                    </span>    
                    <span>
                        (<?= $intrsect['countCode']?>/<?= round($diff, 2)?>)
                    </span>
                <?php endforeach;?>    
            </div>
            <table class="table table-striped">
                <tr>
                    <td  colspan="4">
                        <span><?= $unknownProducer->getDateCreated() ?></span>,
                        <span>Поставщиков: <?= $unknownProducer->getSupplierCount() ?></span>,
                        <span>cтрок прайсов: <?= $unknownProducer->getRawpriceCount() ?></span>
                        
                    </td>
                </tr>
                <tr>
                    <td colspan="2">            
                        <?php if ($prev):?>
                            <a href="/producer/unknown-view/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getName()?></a>
                        <?php endif;?>            
                    </td>
                    <td colspan="2" align="right">
                        <?php if ($next):?>
                            <a href="/producer/unknown-view/<?= $next[0]->getId()?>"><?= $next[0]->getName()?>&rarr;</a>
                        <?php endif;?>                            
                    </td>
                </tr>
            </table>    
            <ul class="nav nav-tabs" id="featureTab" role="tablist">
                <li role="presentation"><a href="#price" role="tab" id="price-tab" data-toggle="tab" aria-controls="price" aria-expanded="true">Прайсы <span id="priceBadge" class="badge"><?= $unknownProducer->getRawpriceCount() ?></span></a></li>
                <li role="presentation"><a href="#intersect" role="tab" id="intersect-tab" data-toggle="tab" aria-controls="intersect" aria-expanded="true">Пересечения <span class="badge"><?= count($intersects)?></span><span id="intersectBadge" class="badge"></span></a></li>
            </ul>

            <div class="tab-content" id="featureTabContent">
                <div class="tab-pane fade" role="tabpanel" id="price" aria-labelledby="price-tab">
                    <div id="priceToolbar">
                        <div class="form-inline" role="form">
                            <select style="width: 200px" class="form-control" id='priceStatusSelect'>
                                <?php foreach ($priceStatuses as $key => $value):?>
                                    <option value="<?= $key?>" <?= ($key == 2) ? 'selected':'' ?>><?= $value?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <table id="priceTable" 
                        data-toggle="table" 
                        data-url="/rawprice/content/<?= $unknownProducer->getId()?>"
                        data-side-pagination="server"
                        data-pagination="true" 
                        data-page-list="[5, 10, 20, 50]"
                        data-toolbar="#priceToolbar"
                        data-show-refresh="true"
                        data-show-toggle="true"
                        data-query-params="priceQueryParams"
                        data-response-handler="responseHandler"
                        >
                        <thead>
                            <tr>
                                 <!--<th data-field="id" data-type="numeric">ID</th>-->
                                 <!--<th data-field="supplier" data-formatter="supplierFormatter">Поставщик</th>-->
                                 <th data-field="code" data-formatter="codeFormatter">Артикул</th>
                                 <th data-field="goodname" data-formatter="goodnameFormatter">Описание</th>
                                 <th data-field="rest" data-align='right'>Наличие</th>
                                 <th data-field="price" data-align='right'>Цена</th>
                             </tr>                
                        </thead>
                    </table>
                </div>    
                <div class="tab-pane fade" role="tabpanel" id="intersect" aria-labelledby="intersect-tab">
                    <div id="intersectToolbar">
                        <div class="form-inline" role="form">
                            <select style="width: 400px" class="form-control" id='intersectSelect'>
                                <?php foreach ($intersects as $key => $value):?>
                                <? 
                                    $diff = 0;
                                    if ($unknownProducer->getRawpriceCount()){
                                        $diff = $value['countCode']/($unknownProducer->getRawpriceCount());
                                    } else {
                                        continue;
                                    }            
                                ?>
                                <option value="<?= $value['unknown_producer_id']?>" <?= ($key === 0) ? 'selected':''?>><?= $value['unknown_producer_name'].' ('.$value['countCode'].'/'.round($diff, 2).')' ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <table id="intersectTable" 
                        data-toggle="table" 
                        data-url="/rawprice/intersect-content/<?= $unknownProducer->getId()?>"
                        data-side-pagination="server"
                        data-pagination="true" 
                        data-page-list="[5, 10, 20, 50]"
                        data-toolbar="#intersectToolbar"
                        data-show-refresh="true"
                        data-show-toggle="true"
                        data-query-params="intersectQueryParams"
                        data-response-handler="responseHandler"
                        >
                        <thead>
                            <tr>
                                 <th data-field="code" data-formatter="intersectCodeFormatter">Артикул</th>
                             </tr>                
                        </thead>
                    </table>
                </div>    
            </div>
        </div>    
    </div>    
    <div class="col-md-3" id="side-nav">
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Производитель
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?php if ($unknownProducer->getProducer()):?>
                                <a style="font-size: calc" href="<?= $this->url('producer', ['action'=>'view', 'id'=>$unknownProducer->getProducer()->getId()]); ?>" target="_balnk">
                                    <?= ($unknownProducer->getProducer()->getName()) ?$unknownProducer->getProducer()->getName():'---' ?>
                                </a>
                            <?php else:?>
                                <i>Не создан</i>
                            <?php endif;?>        
                        </div>
                        <div class="pull-right">
                            <button value="/producer/assembly-producer/<?= $unknownProducer->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                                    title="Создать производителя">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>

<script type="text/javascript">
    $.fn.editable.defaults.mode = 'inline';
    
    $(window).on('load', function() {
        $('.nav-tabs a:first').tab('show');
        $('.bootstrapEdit').editable();
        $('#editableCheckBox').change(function() {
            $.ajax({
                type: "POST",
                url: $(this).attr('data-url'),
                data: "pk="+$(this).attr('data-pk'),
                success: function(msg){
//                      alert( "Прибыли данные: " + msg );
                }
            });
        })        
    });
    
    $(function () {
        $('#priceStatusSelect').change(function (){
            $('#priceTable').bootstrapTable('refresh');
        })
        $('#intersectSelect').change(function (){
            $('#intersectTable').bootstrapTable('refresh');
        })
    });    
    
    function refreshPriceTable(){
        $('#priceTable').bootstrapTable('refresh');
    }

    function refreshIntersectTable(){
        $('#intersectTable').bootstrapTable('refresh');
    }

    var priceTable = $('#priceTable').bootstrapTable({
        onLoadSuccess: function(res){
            $('#priceBadge').html($('#priceTable').bootstrapTable('getOptions').totalRows)
        }
    });
    
    var intersectTable = $('#intersectTable').bootstrapTable({
        onLoadSuccess: function(res){
            $('#intersectBadge').html($('#intersectTable').bootstrapTable('getOptions').totalRows)
        }
    });
    
    function tabQueryParams(tab, params) {
        $(tab +'Toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $(tab + ' .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $(tab + ' li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function priceQueryParams(params) {
        params.status = $('#priceStatusSelect').val();
        return tabQueryParams('#price', params);
    }
    
    function intersectQueryParams(params) {
        params.intersect = $('#intersectSelect').val();
        return tabQueryParams('#intersect', params);
    }
    
    function responseHandler(res) {
        return res;
    }       
    
    function goodnameFormatter(value, row) {
        return '<a href="/rawprice/view/'+row.id+'" target="_blank">'+value+'</a>';
    }    
    
    function producerFormatter(value, row) {
        return '<a href="/producer/unknown-view/'+row.producerId+'" target="_blank">'+value+'</a>';
    }    
    
    function codeFormatter(value, row) {
        if (row.codeId){
            return '<a href="/producer/article-view/'+row.codeId+'" target="_blank">'+value+'</a>';
        } else {
            return row.article;
        }    
    }    
    
    function supplierFormatter(value, row) {
        var priceDate = new Date(row.dateCreated);
        var priceDateStr = priceDate.getDate()+'-'+ (priceDate.getMonth()+1) + ' ' + priceDate.getHours() + ':' + priceDate.getMinutes();
        return '<a href="/supplier/view/'+row.supplierId+'" target="_blank">'+value+'</a>' + '<br/>' + priceDateStr ;
    }    
        
    function intersectCodeFormatter(value, row) {
        return '<a href="/producer/article-view?code='+value+'&unknownProducerIntersect=<?= $unknownProducer->getId()?>&unknownProducer='+row.unknownProducer+'" target="_blank">'+value+'</a>';
    }    
    
</script>
