<?php
$this->headTitle('Неизвестные производители');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Неизвестные производители'=>$this->url('producer', ['action'=>'unknown'])
            ]);
  
?>

<div class="row">
    <div class="col-md-10">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/producer/unknown-content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                     <th data-field="dateCreated" data-formatter="dateFormatter" data-sortable="true">Дата</th>
                     <th data-field="name" data-formatter="linkFormatter" data-sortable="true">Неизвестный</th>
                     <th data-field="nameTd" data-formatter="nameTdFormatter" data-sortable="true">Имя для ТД</th>
                     <th data-field="producer" data-formatter="producerFormatter">Известный</th>             
                     <th data-field="rawpriceCount" data-align='right' data-sortable="true">Строк в прайсах</th>             
                     <th data-field="supplierCount" data-align='right' data-sortable="true">Поставщиков</th>             
                     <th data-field="id" data-formatter="intersectFormatter" data-align='right' data-sortable="false">Пересечений</th>             
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-2" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Строки прайсов
                    </div>
                    <div class="panel-body">
                        <?php foreach($stages as $stage):?>
                            <?php if ($stage['stage']):?>
                                <div>
                                     <?= $stage['rowCount']?> - привязаны
                                </div>     
                            <?php else:?>
                                <div>
                                    <?= $stage['rowCount']?> - не привязаны
                                </div>
                            <?php endif;?>
                        <?php endforeach;?>
                    </div>    
                    <div class="panel-body">
                    </div>
                </div>    
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Всего наименований
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?= $total?>
                        </div>
                        <div class="pull-right">
                            <button value="/producer/delete-empty-unknown-producer/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Удаление пустых">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button> 
                        </div>
                    </div>
                </div>    
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Пересчет количества
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <span>товаров</span>
                        </div>
                        <div class="pull-right">
                            <button value="/producer/rawprice-count-unknown-producer/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Обновить количество товара">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <span>поставщиков</span>
                        </div>
                        <div class="pull-right">
                            <button value="/producer/supplier-count-unknown-producer/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Обновить количество поставщиков">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <span>пересечений</span>
                        </div>
                        <div class="pull-right">
                            <button value="/producer/unknown-producer-intersect/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Обновить пересечения поставщиков">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">

    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table').bootstrapTable({
        onLoadSuccess: function(res){
            $('.bootstrapEdit').editable();
        }
    });

    var ok = $('#ok');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function linkFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/producer/unknown-view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function nameTdFormatter(value, row){
        if (row.producer){
            return [
                '<a href="#"',
                ' class="bootstrapEdit" data-type="text"',
                ' data-pk="'+row.id+'"',
                ' data-name="nameTd"',
                ' data-url="/producer/edit-unknown-producer-name-td">'+value,
                '</a>',
            ].join(''); 
        }
        
        return;
    }    
    
    function producerFormatter(value, row){
        if (value){
            return [
                '<div class="pull-left">',
                '<a href="/producer/view/' + value.id + '" target="_blank">' + value.name + '</a>',
                '</div>'
            ].join(''); 
        }
        return;
    }    
    
    function dateFormatter(value){
        var date = new Date(value);
        return date.getDate() + '-' + (date.getMonth() + 1) + '-' +  date.getFullYear();
    }
    
    function intersectCount(data){
        if (data.intersectCount){
            $('#unknownProducer'+data.id).html(data.intersectCount);
        }    
    }
    
    function intersectFormatter(value){
        $.post(
            '/producer/intersect-count-content/'+value,
            null,
            intersectCount                
        );
        return [
            '<span id="unknownProducer'+value+'"></span>',
        ].join(''); 
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>
