<?php
$this->headTitle('Неизвестные производители');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Производители'=>$this->url('producer'),
            'Неизвестные производители'=>$this->url('producer', ['action'=>'unknown'])
            ]);

?>

<h1>Неизвестные производители</h1>
<div class="row">
  <div class="col-lg-12">
    <a class="btn btn-default <?= ($ua ? 'active':'')?>" href="
        <?= $this->url('producer', ['action'=>'unknown'], ['query' => ['ua' => 1]]); ?>">
        Не привязанные
    </a>
    <a class="btn btn-default <?= ($ua ? '':'active')?>" href="
        <?= $this->url('producer', ['action'=>'unknown']); ?>">
        Все
    </a>
    <div class="input-group">
        <input type="text" class="form-control" aria-label="...">
        <div class="input-group-btn">
            <!-- Buttons -->
        </div>
    </div>
  </div>  
</div>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Известный</th>
        <th>Неизвестный</th>
        <th>Действие</th>
    </tr>
    
    <?php foreach ($producer as $row): ?>
    <tr>
        <td><?= $this->escapeHtml($row->getId()); ?></td>
        <td>
            <?php if ($row->getProducer()): ?>    
                <a href="<?= $this->url('producer', ['action'=>'view', 'id'=>$row->getProducer()->getId()]); ?>">
                    <?= $this->escapeHtml($row->getProducer()->getName()); ?>
                </a> 
            <?php endif; ?>
        </td>
        <td><?= $row->getName(); ?></td>        
        <td>
            <?php if ($row->getProducer()): ?>
            <?php else: ?>
                <a class="btn btn-info" href="<?= $this->url('producer', 
                        ['action'=>'from-unknown', 'id'=>$row->getId()], ['query' => ['page' => $page]]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span>Добавить
                </a>
            <?php endif; ?>
            <a class="btn btn-danger" href="<?= $this->url('producer',
                    ['action'=>'delete-unknown', 'id'=>$row->getId()], ['query' => ['page' => $page]]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Удалить
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>
<?= $this->paginationControl($producer,
            'Sliding',
            'application/partial/paginator', 
            ['route' => array('route' => 'producer', 'action' => 'unknown', 'query' => $ua)]); ?>

