<?php
$this->headTitle($unknownProducer->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Неизвестные производители'=>$this->url('producer', ['action' => 'unknown']),
            $unknownProducer->getName()=>$this->url('producer', ['action'=>'unknown-view', 'id'=>$unknownProducer->getId()])
            ]);

?>
<h1>
    <?= $this->escapeHtml($unknownProducer->getName()); ?>    
</h1>
<table class="table table-striped">
    <tr>
        <th colspan="2">
            Всего
        </th>
        <td  colspan="2" align="right">
            <b><?= $unknownProducer->getRawpriceCount() ?></b>
            /
            <?= $unknownProducer->getSupplierCount() ?>
        </td>
    </tr>
    <tr>
        <td colspan="2">            
            <?php if ($prev):?>
                <a href="/producer/unknown-view/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getName()?></a>
            <?php endif;?>            
        </td>
        <td colspan="2" align="right">
            <?php if ($next):?>
                <a href="/producer/unknown-view/<?= $next[0]->getId()?>"><?= $next[0]->getName()?>&rarr;</a>
            <?php endif;?>                            
        </td>
    </tr>
    <?php    foreach ($rawpriceCountBySupplier as $row):?>
        <tr>
            <td colspan="3">
                <b><?= $row[0]->getSupplier()->getName();?></b>
            </td>
            <td align="right">
                <?= $row['rawpriceCount']?>
            </td>
        </tr>
        <?php $randRawprices = $producerManager->randRawpriceBy(['unknownProducer' => $unknownProducer->getId(), 'raw' => $row[0]->getId()]);?>
        <?php foreach($randRawprices as $randRawprice):?>
            <tr style="font-size: x-small">
                <td>
                    <?php if ($randRawprice->getCode()):?>
                        <?php if ($randRawprice->getCode()->getId()):?>
                            <a href="<?= $this->url('producer', ['action' => 'article-view', 'id' => $randRawprice->getCode()->getId()]);?>">
                                <?= $randRawprice->getCode()->getCode();?>
                            </a>    
                        <?php else:?>
                            <?= $randRawprice->getArticle();?>
                        <?php endif; ?>
                    <?php else:?>
                        <?= $randRawprice->getArticle();?>
                    <?php endif; ?>
                </td>
                <td>
                    <a href="<?= $this->url('rawprice', ['action' => 'view', 'id' => $randRawprice->getId()]);?>">
                        <?= $randRawprice->getGoodname();?>
                    </a>    
                </td>
                <td align="right">
                    <?= $randRawprice->getPrice();?>
                </td>
                <td align="right">
                    <?= $randRawprice->getRest();?>
                </td>
            </tr>
        <?php endforeach;?>                    
    <?php endforeach;?>        
</table>
