<?php
$this->headTitle($unknownProducer->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Неизвестные производители'=>$this->url('producer', ['action' => 'unknown']),
            $unknownProducer->getName()=>$this->url('producer', ['action'=>'unknown-view', 'id'=>$unknownProducer->getId()])
            ]);

?>
<h1>
    <?= $this->escapeHtml($unknownProducer->getName()); ?>    
</h1>
<div>
    <span>
        <?php if ($prev):?>
        <a href="/producer/unknown-view/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getName()?></a>
        <?php endif;?>            
    </span>
    <span>
        <?php if ($next):?>
            <a href="/producer/unknown-view/<?= $next[0]->getId()?>"><?= $next[0]->getName()?>&rarr;</a>
        <?php endif;?>                
    </span>    
</div>
<table class="table table-striped">
    <tr>
        <th>
            Поставщик
        </th>
        <th>
            Количество записей
        </th>
    </tr>
    <?php $totalRawpriceCount = 0; ?>
    <?php    foreach ($rawpriceCountBySupplier as $row):?>
        <tr>
            <td>
                <?= $row['supplierName'];?>
            </td>
            <td align="right">
                <?= $row['rawpriceCount']?>            
            </td>
        </tr>
        <?php $totalRawpriceCount += $row['rawpriceCount']; ?>
    <?php endforeach;?>        
    <tr>
        <th>
            Всего
        </th>
        <td align="right">
            <b><?= $totalRawpriceCount ?></b>
        </td>
    </tr>
</table>
