<?php
$this->headTitle('Неизвестные производители');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Производители'=>$this->url('producer'),
            'Неизвестные производители'=>$this->url('producer', ['action'=>'unknown'])
            ]);

$this->headLink()
    ->appendStylesheet($this->basePath('js/x-editable/bootstrap3-editable/css/bootstrap-editable.css'))        
    ->appendStylesheet($this->basePath('js/x-editable/inputs-ext/typeaheadjs/lib/typeahead.js-bootstrap.css'))        
        ;

$this->headScript()
    ->appendFile($this->basePath('js/x-editable/bootstrap3-editable/js/bootstrap-editable.js'))
    ->appendFile($this->basePath('js/x-editable/inputs-ext/typeaheadjs/lib/typeahead.js'))
    ->appendFile($this->basePath('js/x-editable/inputs-ext/typeaheadjs/typeaheadjs.js'))
            ;
        
?>

<h1>Неизвестные производители</h1>
<form method="GET">
    <div class="row">
        <div class="col-lg-7">
            <div class="input-group">
                <span class="input-group-btn">
                    <a class="btn btn-default <?= ($ua ? 'active':'')?>" href="
                        <?= $this->url('producer', ['action'=>'unknown'], ['query' => ['ua' => 1]]); ?>">
                        Не привязанные
                    </a>
                    <a class="btn btn-default <?= ($ua ? '':'active')?>" href="
                        <?= $this->url('producer', ['action'=>'unknown']); ?>">
                        Все
                    </a>
                </span>    
                <input type="text" class="form-control" aria-label="..." name="q" value="<?= $q ?>">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Найти</button>
                </span>
            </div>    
        </div>  
    </div>
</form>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Известный</th>
        <th>Неизвестный</th>
        <th>Действие</th>
    </tr>
    
    <?php foreach ($producer as $row): ?>
    <tr>
        <td><?= $this->escapeHtml($row->getId()); ?></td>
        <td>
            <?php if ($row->getProducer()): ?>    
                <a href="#" class="editable" data-type="typeaheadjs" data-pk="<?= $row->getId() ?>" data-url="<?= $this->url('producer', ['action' => 'editable-unknown'])?>"><?= $row->getProducer()->getName(); ?></a>
            <?php else: ?>    
                <a href="#" class="editable" data-type="typeaheadjs" data-pk="<?= $row->getId() ?>" data-url="<?= $this->url('producer', ['action' => 'editable-unknown'])?>"></a>
            <?php endif; ?>
        </td>
        <td><?= $row->getName(); ?></td>        
        <td>
            <?php if ($row->getProducer()): ?>
            <?php else: ?>
                <a class="btn btn-info" href="<?= $this->url('producer', 
                        ['action'=>'from-unknown', 'id'=>$row->getId()], ['query' => ['page' => $page, 'ua' => $ua, 'q' => $q]]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span>Добавить
                </a>
            <?php endif; ?>
            <a class="btn btn-danger" href="<?= $this->url('producer',
                    ['action'=>'delete-unknown', 'id'=>$row->getId()], ['query' => ['page' => $page, 'ua' => $ua, 'q' => $q]]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Удалить
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>
<?= $this->paginationControl($producer,
            'Sliding',
            'application/partial/paginator', 
            ['route' => array('route' => 'producer', 'action' => 'unknown', 'query' => $q)]); ?>

<script type="text/javascript">
    $(function(){
        $('.editable').editable({
            title: 'Выбрать производителя',
            emptytext: 'Не привязан',
            typeahead: {
                remote: {
                    url: '/producer/search-assistant/?q=%QUERY'
                },
                template: function(item) {                        
                    return item.value + ' (' + item.text + ')'; 
                }             
            }    
        });        
    });
</script>
