<?php
$this->headTitle('Производитель - ' . $producer->getName());
//$this->mainMenu()->setActiveItemId('home');
//$this->pageBreadcrumbs()->setItems([
//            'Home'=>$this->url('home')
//            ]);
        
?>

<a href="
    <?= $this->url('producer', []); ?>">
    &lt;&lt; Назад в список производителей
</a>

<h1>
    <?= $this->escapeHtml($producer->getName()); ?>    
</h1>


<p>    
    Страна 
    <?php if ($producer->getCountry()):?>
        <?= $this->escapeHtml($producer->getCountry()->getName()); ?>
    <?php else: ?>
        неуказана
    <?php endif;?>
</p>