<?php
$this->headTitle($producer->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Производители'=>$this->url('producer'),
            $producer->getName()=>$this->url('producer', ['action'=>'view', 'id'=>$producer->getId()])
            ]);

$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ; 

$unknownProducerQueryId = null;
if ($unknownProducerQuery){
    $unknownProducerQueryId = $unknownProducerQuery->getId();
}    

?>
<div class="row">
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-12">
                <h1>
                    <button value="/producer/best-name/<?= $producer->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                            title="Обновить наименование">
                        <span class="glyphicon glyphicon-refresh" ></span>
                    </button> 
                    <span><?= $this->escapeHtml($producer->getName()); ?></span>
                    <sup style="font-size: xx-small">
                        <?php foreach($producer->getUnknownProducer() as $unknownProducer):?>    
                            <span>
                                <a href="<?= $this->url('producer', ['action'=>'unknown-view', 'id'=>$unknownProducer->getId()]) ?>" target="_blank">
                                    <?= $unknownProducer->getName();?>
                                </a>
                            </span>
                        <?php endforeach; ?>            
                    </sup>
                </h1>                
                <!--<p>    
                    Страна 
                    <?php if ($producer->getCountry()):?>
                        <?= $this->escapeHtml($producer->getCountry()->getName()); ?>
                    <?php else: ?>
                        неуказана
                    <?php endif;?>
                </p>-->
                <table class="table table-striped">
                    <tr>
                        <td colspan="2">            
                            <?php if ($prev):?>
                                <a href="/producer/view/<?= $prev[0]['id']?>">&larr;<?= $prev[0]['name']?></a>
                            <?php endif;?>            
                        </td>
                        <td  colspan="3" align="right">
                            <?php if ($next):?>
                                <a href="/producer/view/<?= $next[0]['id']?>"><?= $next[0]['name']?>&rarr;</a>
                            <?php endif;?>                            
                        </td>
                    </tr>
                </table>    
                <div id="goodsToolbar">
                    <div class="form-inline" role="form">
                        <div class="form-group">
                            <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                        </div>
                        <button id="goodsOk" type="submit" class="btn btn-default">OK</button>                        
                    </div>
                </div>
                <table id="goodsTable" 
                    data-toggle="table" 
                    data-url="/goods/content"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#goodsToolbar"
                    data-show-refresh="true"
                    data-show-toggle="true"
                    data-query-params="goodsQueryParams"
                    data-response-handler="responseHandler"
                    >
                    <thead>
                        <tr>
                             <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                             <th data-field="aplId" data-type="numeric" data-formatter="aplFormatter" data-sortable="true">AplId</th>
                             <th data-field="code" data-formatter="linkFormatter" data-sortable="true">Артикул</th>
                             <th data-field="producer" data-formatter="producerFormatter">Производитель</th>             
                             <th data-field="" data-formatter="activeFormatter"></th>
                         </tr>                
                    </thead>
                </table>
            </div>    
        </div>
    </div>    
    <div class="col-md-3" id="side-nav">
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Обновления
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            AplId: <?= $producer->getAplId()?>
                        </div>
                        <div class="pull-right">
                            <button value="/apl/producer-apl-id/<?= $producer->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить АПЛ Ид">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                </div>
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Расценка
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Min Цена
                        </div>
                        <div class="pull-right">
                            <?= $minPrice?>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Max Цена
                        </div>
                        <div class="pull-right">
                            <?= $maxPrice?>
                        </div>
                    </div>
                    <?php if ($rate):?>
                        <div class="panel-body">
                            <div class="pull-left">
                                <a href="<?= $this->url('rate', ['action' => 'view', 'id' => $rate->getId()])?>">
                                    <?= $rate->getName()?>
                                </a>
                            </div>
                            <div class="pull-right">
                                <button value="/rate/add/?producer=<?= $producer->getId()?>&prompt=Расценка для <?= $producer->getName()?>" class="btn btn-info btn-xs refresh-button"
                                        title="Создать специальную расценку">
                                    <span class="glyphicon glyphicon-plus" ></span>
                                </button> 
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>    
</div>

<script type="text/javascript">
    function refreshTable(){
        $('#goods').bootstrapTable('refresh');
    }

    var goodsTable = $('#goods'),
        goodsOk = $('#goodsOk');

    $(function () {
        goodsOk.click(function () {
            goodsTable.bootstrapTable('refresh');
        });
    });
    
    function tabQueryParams(tab, params) {
        $(tab +'Toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $(tab + ' .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $(tab + ' li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        params.producer = <?= $producer->getId();?>;
        
        return params;
    }
    
    function goodsQueryParams(params) {
        return tabQueryParams('#goods', params);
    }    
    
    function linkFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/goods/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function aplFormatter(value, row){
        if (value != '0'){
            return [
                '<div class="pull-left">',
                '<a href="https://autopartslist.ru/goods/view/id/' + value + '" target="_blank">' + value + '</a>',
                '</div>'
            ].join(''); 
        } else {
            return '-';
        }    
    }    
    
    function producerFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + value.id + '" target="_blank">' + value.name + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function activeFormatter(value, row){
        var url = '/goods/delete-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>
