<?php
$this->headTitle($producer->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Производители'=>$this->url('producer'),
            $producer->getName()=>$this->url('producer', ['action'=>'view', 'id'=>$producer->getId()])
            ]);

?>
<h1>
    <?= $this->escapeHtml($producer->getName()); ?>    
</h1>


<p>    
    Страна 
    <?php if ($producer->getCountry()):?>
        <?= $this->escapeHtml($producer->getCountry()->getName()); ?>
    <?php else: ?>
        неуказана
    <?php endif;?>
</p>

<?php foreach($producer->getUnknownProducer() as $unknownProducer):?>    
    <span>
        <?php if ($unknownProducer == $unknownProducerQuery):?>
            <a style="font-weight: bold" href="<?= $this->url('producer', ['action'=>'view', 'id'=>$producer->getId()]) ?>">
                <?= $unknownProducer->getName();?>
            </a>
        <?php else:?>
            <a href="<?= $this->url('producer', ['action'=>'view', 'id'=>$producer->getId()], ['query' => ['unknownProducer' => $unknownProducerQuery->getId()]])?>">
                <?= $unknownProducer->getName();?>
            </a>
        <?php endif; ?>
    </span>
<?php endforeach; ?>
<table class="table table-striped">
    <tr>
        <td colspan="2">            
            <?php if ($prev):?>
                <a href="/producer/view/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getName()?></a>
            <?php endif;?>            
        </td>
        <td  colspan="3" align="right">
            <?php if ($next):?>
                <a href="/name/view/<?= $next[0]->getId()?>"><?= $next[0]->getName()?>&rarr;</a>
            <?php endif;?>                            
        </td>
    </tr>
    <tr>
        <td colspan="4">
            <?= $this->paginationControl($goods,
                        'Sliding',
                        'application/partial/paginator', 
                        ['route' => ['route' => 'producer', 'action' => 'view', 'id' => $producer->getId(), 'query' => ['unknownProducer' => $unknownProducerQuery->getId()]]]); ?>
            
        </td>
        <td align="right" valign="center">
            <b><?= $totalGoodsCount?></b>
        </td>
    </tr>
    <?php    foreach ($goods as $good):?>
        <tr>
            <td>
                <a href="<?= $this->url('goods', ['action' => 'view', 'id' => $good->getId()]);?>">
                    <?= $good->getCode();?>
                </a>   
            </td>
            <td>
                <a href="<?= $this->url('producer', ['action' => 'view', 'id' => $good->getProducer()->getId()]);?>">
                    <?= $good->getProducer()->getName();?>
                </a>   
            </td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    <?php endforeach;?>        
    <tr>
        <td colspan="5">
            <?= $this->paginationControl($goods,
                        'Sliding',
                        'application/partial/paginator', 
                        ['route' => ['route' => 'producer', 'action' => 'view', 'id' => $producer->getId(), 'query' => ['unknownProducer' => $unknownProducer->getId()]]]); ?>
            
        </td>
    </tr>
</table>
