<?php
$this->headTitle('Обмен с autopartslist.ru');

$this->mainMenu()->setActiveItemId('apl');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Администрирование'=>$this->url('admin'),
            'Обновление с/на autopartslist.ru' => $this->url('apl')
            ]);  

?>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Клиенты и сотрудники</h3>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <p>
                    Обновление списка клиентов и сотрудников
                </p>
                <button class="btn btn-default refresh-button" value="/apl/get-clients">
                    <span class="glyphicon glyphicon-refresh" ></span>Обновить
                </button>
                
            </div>
            <div class="panel-body">
                <div class="pull-left">
                    Очистка дублей с кодом Апл
                </div>
                <div class="pull-right">
                    <button value="/client/clear-double-apl" class="btn btn-default btn-xs refresh-button"
                            title="Очистка дублей с кодом Апл">
                        <span class="glyphicon glyphicon-refresh" ></span>
                    </button> 
                </div>
            </div>
            <div class="panel-body">
                <div class="pull-left">
                    ОУдаление пустых контактов
                </div>
                <div class="pull-right">
                    <button value="/contact/delete-empty-contacts/" class="btn btn-danger btn-xs refresh-table-button"
                            title="Удаление пустых контактов">
                        <span class="glyphicon glyphicon-remove" ></span>
                    </button> 
                </div>
            </div>
            <div class="panel-body">
                <div class="pull-left">
                    Удаление пустых клиентов
                </div>
                <div class="pull-right">
                    <button value="/client/delete-empty-clients/" class="btn btn-danger btn-xs refresh-table-button"
                            title="Удаление пустых клиентов">
                        <span class="glyphicon glyphicon-remove" ></span>
                    </button> 
                </div>
            </div>
        </div>
    </div>    

    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Поставщики</h3>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <p>
                    Обновление списка <a href="/supplier">поставщиков</a>
                </p>
                <button class="btn btn-default refresh-button" value="/apl/get-suppliers">
                    <span class="glyphicon glyphicon-refresh" ></span>Обновить
                </button>
                
            </div>
            <div class="panel-body">
                <div class="pull-left">
                    Импорт из АПЛ
                </div>
                <div class="pull-right">
                    <button value="/apl/unload-doc?doc=ptu" class="btn btn-default btn-xs refresh-button"
                            title="Импорт одного поступления из АПЛ">
                        <span class="glyphicon glyphicon-refresh" ></span>
                    </button> 
                    <button value="/apl/unload-docs?doc=ptu" class="btn btn-default btn-xs refresh-button"
                            title="Импорт поступлений из АПЛ">
                        <span class="glyphicon glyphicon-refresh" ></span>
                    </button> 
                </div>
            </div>
            <div class="panel-body">
                <div class="pull-left">
                    Перепровести все
                </div>
                <div class="pull-right">
                    <button value="/ptu/repost-all-ptu/" class="btn btn-default btn-xs refresh-button"
                            title="Поступления товаров">ПТУ
<!--                        <span class="glyphicon glyphicon-refresh" ></span>-->
                    </button> 
                    <button value="/st/repost-all-st/" class="btn btn-default btn-xs refresh-button"
                            title="Списания товаров">СТ
<!--                        <span class="glyphicon glyphicon-refresh" ></span>-->
                    </button> 
                </div>
            </div>
        </div>
    </div>    
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Отправка выписки банка</h3>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <button class="btn btn-default refresh-button" value="/apl/trans-bank">
                    <span class="glyphicon glyphicon-refresh" ></span>Отправить
                </button>
                
            </div>
        </div>
    </div>    

    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Обновление прайсов</h3>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <button class="btn btn-default refresh-button" value="/apl/update-good-rawprice">
                    <span class="glyphicon glyphicon-refresh" ></span>Обновить
                </button>
                
            </div>
        </div>
    </div>    

</div>