<?php
$this->headTitle('Обмен с autopartslist.ru');

$this->mainMenu()->setActiveItemId('apl');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Администрирование'=>$this->url('admin'),
            'Обновление с/на autopartslist.ru' => $this->url('apl')
            ]);  

?>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Сотрудники</h3>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <p>
                    Обновление списка <a href="/users">сотрудников</a>
                </p>
                <button class="btn btn-default refresh-button" value="/apl/get-staffs">
                    <span class="glyphicon glyphicon-refresh" ></span>Обновить
                </button>
                
            </div>
        </div>
    </div>    

    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Поставщики</h3>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <p>
                    Обновление списка <a href="/supplier">поставщиков</a>
                </p>
                <button class="btn btn-default refresh-button" value="/apl/get-suppliers">
                    <span class="glyphicon glyphicon-refresh" ></span>Обновить
                </button>
                
            </div>
        </div>
    </div>    
</div>


<script async="true">
    $('.refresh-button').on('click', function(e) {
        var url = e.currentTarget.value;
        
        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    if (data == 'ok'){
                        bootbox.alert("Данные успешно обновлены.");
                    }    
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })
</script>