<?php
$this->headTitle('Машины');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Машины'=>$this->url('make'),
            ]);

$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
?>
<!--<button value="/make/make-form" class="btn btn-default btn-xs"
        data-toggle="modal" data-target="#modal-dialog" title="Добавить">
    <span class="glyphicon glyphicon-plus" ></span>
</button>                                                                        -->

<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/make/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                     <th data-field="tdId" data-sortable="true">TD</th>
                     <th data-field="aplId" data-sortable="true">АПЛ</th>
                     <th data-field="name" data-formatter="linkFormatter" data-sortable="true">Наименование</th>             
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Обновить из внешних баз
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Марки машин<sup><?= $totalMake?></sup> 
                        </div>
                        <div class="pull-right">
                            <button value="/make/fill-makes" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить производителей">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                            <button value="/make/update-all-make-status" class="btn btn-default btn-xs refresh-table-button"
                                    title="Обновить статус марок машин">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Модели<sup><?= $totalModel?></sup> 
                        </div>
                        <div class="pull-right">
                            <button value="/make/fill-all-models" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить модели">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                            <button value="/make/update-all-model-status" class="btn btn-default btn-xs refresh-table-button"
                                    title="Обновить статус моделей машин">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Модификации<sup><?= $totalCar?></sup> 
                        </div>
                        <div class="pull-right">
                            <button value="/car/update-all-status" class="btn btn-default btn-xs refresh-table-button"
                                    title="Обновить статус машин">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Товары<sup><?= $totalGoods?></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/goods/update-car-count" class="btn btn-default btn-xs refresh-table-button"
                                    title="Обновить количество машин в товарах">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                           АПЛ Ид
                        </div>
                        <div class="pull-right">
                            <button value="/apl/update-make-apl-id" class="btn btn-default btn-xs refresh-table-button"
                                    title="Заполнить AplId производителей">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                            <button value="/apl/update-model-apl-id" class="btn btn-default btn-xs refresh-table-button"
                                    title="Заполнить AplId моделей">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>
                <div class="panel panel-info">
                    <div class="panel-body">
                        <a href="<?= $this->url('car', ['action' => 'attribute-types'])?>">Атрибуты</a>                                            
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var $table = $('#table'),
        $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }

        
        return params;
    }
    
    function linkFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/make/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function statusFormatter(value, row){
        switch (value){
            case '1': return 'RU Словарь'; 
            case '2': return 'RU'; 
            case '3': return 'RU 1'; 
            case '4': return 'RU Аббревиатура'; 
            case '11': return 'EN Словарь'; 
            case '12': return 'EN'; 
            case '13': return 'EN 1'; 
            case '14': return 'EN Аббревиатура'; 
            case '21': return 'Число'; 
            default: return 'Неизвестно';    
        }
    }
    
    function flagFormatter(value, row){
        switch (value){
            case '1': return 'Белый'; 
            case '8': return 'Серый'; 
            case '9': return 'Черный'; 
            default: return 'Неизвестно';    
        }
    }
    
    function responseHandler(res) {
        return res;
    }    
</script>
