<?php
use Application\Entity\Make;

$this->headTitle($make->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Машины'=>$this->url('make'),
            $make->getName()=>$this->url('make', ['action'=>'view', 'id'=>$make->getId()])
            ]);

$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js')
            ;    

?>

<h1>
    <?= $make->getName();?>
    <sup>
        <?= $make->getTdId();?>
    </sup>
</h1>
<p>
    <?= $make->getStatusAsString();?>.
    <?php if ($make->getStatus() == Make::STATUS_ACTIVE): ?>
        Наименование выводимое: 
         <a href="#" 
            class="bootstrapEdit" data-type="text" 
            data-pk="<?= $make->getId()?>" 
            data-mode="inline"
            data-name="fullName" data-emptytext="<?= $make->getName() ?>"
            data-url="/make/edit-full-name">
            <?= $make->getFullName() ?>    
        </a>
    <?php endif; ?>    
</p>

<div class="row">
    <div class="col-md-9">

        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/make/model-content/<?= $make->getId()?>"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                     <th data-field="tdId" data-sortable="true">TD</th>
                     <th data-field="aplId" data-sortable="true">АПЛ</th>
                     <th data-field="name" data-formatter="linkFormatter" data-sortable="true">Наименование</th>             
                     <th data-field="fullName" data-formatter="fullNameFormatter" data-sortable="true">Выводимое</th>
                     <th data-field="interval" data-sortable="true">Период</th>             
                     <th data-field="goodCount" data-sortable="true">Товаров</th>             
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Обновления и внешние данные
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            AplId: 
                                <?= $make->getAplId()?>
                        </div>
                        <div class="pull-right">
                            <button value="/apl/make-apl-id/<?= $make->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить АПЛ Ид">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Модели<sup><?= $totalModel?></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/make/fill-models/<?= $make->getId();?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить модели">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Модификации<sup><?= $totalCar?></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/car/fill-make-cars/<?= $make->getId();?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить модификации">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Товары<sup><?= $totalGoods?></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/make/update-available-make/<?= $make->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить доступность">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    //$.fn.editable.defaults.mode = 'inline';
    
    $(window).on('load', function() {
        $('.bootstrapEdit').editable();
    });

    var table = $('#table').bootstrapTable({
        onLoadSuccess: function(res){
            $('.bootstrapTableEdit').editable();
        }
    });

    $('.show-button').on('click', function(e) {
        var url = e.currentTarget.value;

        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    dialog = bootbox.dialog({
                        message: '<div><i class="fa fa-spin fa-spinner"></i>'+objectToHtml(data.message)+'</div>',
                        closeButton: true,
                        size: 'large'
                    });
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })        

function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var $table = $('#table'),
        $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }

        
        return params;
    }
    
    function linkFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/make/view-model/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function fullNameFormatter(value, row){
        return [
            '<a href="#"',
            ' class="bootstrapTableEdit" data-type="text"',
            ' data-pk="'+row.id+'"',
            ' data-name="fullName"',
            ' data-emptyText="'+row.name+'"',
            ' data-url="/make/edit-model-full-name">'+value,
            '</a>',
        ].join(''); 
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>

