<?php
$this->headTitle($make->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Машины'=>$this->url('make'),
            $make->getName()=>$this->url('make', ['action'=>'view', 'id'=>$make->getId()])
            ]);

?>

<h1>
    <?= $make->getName();?>
    <sup>
        <?= $make->getTdId();?>
    </sup>
</h1>

<div class="row">
    <div class="col-md-9">

        <table class="table table-striped">
            <tr>
                <td colspan="3">            
                    <?php if ($prev):?>
                        <a href="/make/view/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getName()?></a>
                    <?php endif;?>            
                </td>
                <td colspan="3" align="right">
                    <?php if ($next):?>
                        <a href="/make/view/<?= $next[0]->getId()?>"><?= $next[0]->getName()?>&rarr;</a>
                    <?php endif;?>                            
                </td>
            </tr>
            <?php foreach($make->getModels() as $model):?>
            <tr>
                <td>
                    <?= $model->getId()?>
                </td>
                <td>
                    <?= $model->getTdId()?>
                </td>
                <td>
                    <?= $model->getAplId()?>
                </td>
                <td>
                    <a href="/make/view-model/<?= $model->getId()?>">
                        <?= $model->getName()?>
                    </a>   
                </td>
                <td>
                    <?= $model->getInterval()?>
                </td>
                <td>
                    
                </td>
            </tr>
            <?php endforeach;?>
        </table>
        
        <h5>Товары<sup><?= $totalCars?></sup></h5>
        <table class="table table-striped">
            <tr>
                <td colspan="6">
                    <?= $this->paginationControl($goods,
                                'Sliding',
                                'application/partial/paginator', 
                                ['route' => array('route' => 'car', 'action' => 'view', 'id' => $car->getId())]); ?>

                </td>
            </tr>
            <?php    foreach ($goods as $good):?>
                <tr>
                    <td colspan="6">
                        <a href="<?= $this->url('goods', ['action' => 'view', 'id' => $good->getId()]);?>">
                            <?= $good->getCode();?> <?= $good->getProducer()->getName();?>
                        </a>   
                    </td>
                </tr>
            <?php endforeach;?>        
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Обновления и внешние данные
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            AplId: 
                                <?= $make->getAplId()?>
                        </div>
                        <div class="pull-right">
                            <button value="/apl/make-apl-id/<?= $make->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить АПЛ Ид">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Модели<sup><?= $totalModel?></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/make/fill-models/<?= $make->getId();?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить модели">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Модификации<sup><?= $totalCar?></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/car/fill-make-cars/<?= $make->getId();?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить модификации">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.show-button').on('click', function(e) {
        var url = e.currentTarget.value;

        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    dialog = bootbox.dialog({
                        message: '<div><i class="fa fa-spin fa-spinner"></i>'+objectToHtml(data.message)+'</div>',
                        closeButton: true,
                        size: 'large'
                    });
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })        
</script>
