<?php
$this->headTitle($model->getMake()->getName().' '.$model->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Машины'=>$this->url('make'),
            $model->getMake()->getName() => $this->url('make', ['action' => 'view', 'id' => $model->getMake()->getId()]),
            $model->getMake()->getName().' '.$model->getName()=>$this->url('make', ['action'=>'view-model', 'id'=>$model->getId()])
            ]);

?>

<h1>
    <?= $model->getMake()->getName().' '.$model->getName();?>
    <sup>
        <?= $model->getTdId();?>
    </sup>
</h1>
<p>
    <small>
        <span><?= $model->getInterval()?></span>
        <span><?= $model->getStatusAsString();?></span>
    </small>
</p>
<div class="row">
    <div class="col-md-9">

        <table class="table table-striped">
            <tr>
                <td colspan="3">            
                    <?php if ($prev):?>
                        <a href="/make/view-model/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getMake()->getName().' '.$prev[0]->getName()?></a>
                    <?php endif;?>            
                </td>
                <td colspan="3" align="right">
                    <?php if ($next):?>
                        <a href="/make/view-model/<?= $next[0]->getId()?>"><?= $next[0]->getMake()->getName().' '.$next[0]->getName()?>&rarr;</a>
                    <?php endif;?>                            
                </td>
            </tr>
            <?php foreach($model->getCars() as $car):?>
                <?php if ($car->getStatus() == $car::STATUS_ACTIVE):?>
                    <tr>
                        <td>
                            <?= $car->getId()?>
                        </td>
                        <td>
                            <?= $car->getTdId()?>
                        </td>
                        <td>
                            <?= $car->getAplId()?>
                        </td>
                        <td colspan="3">
                            <span>
                                <a href="/car/view/<?= $car->getId()?>">
                                    <?= $car->getName()?>
                                </a>                               
                            </span>
                            <small>
                                <?//= $car->getStatusAsString()?>
                            </small>
                        </td>
                        <td>
                            <?= $car->getGoodCount()?>
                        </td>
                    </tr>    
                    <tr>
                        <td colspan="7">
                            <div>
                                <small>
                                   <?php foreach ($car->getVehicleDetailsCar() as $vehicleDetailCar):?>
                                        <?php if ($vehicleDetailCar->getVehicleDetailValue()->getVehicleDetail()->getNameApl()):?>
                                            <span><?= $vehicleDetailCar->getVehicleDetailValue()->getVehicleDetail()->getNameApl(); ?></span>: 
                                            <span><?= $vehicleDetailCar->getVehicleDetailValue()->getNameApl(); ?></span>; 
                                        <?php endif;?>
                                    <?php endforeach;?>
                                </small>                                
                            </div>
                        </td>                    
                    </tr>
                <?php endif;?>    
            <?php endforeach;?>    
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Обновления и внешние данные
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            AplId: 
                                <?= $model->getAplId()?>
                        </div>
                        <div class="pull-right">
                            <button value="/apl/model-apl-id/<?= $model->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить АПЛ Ид">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Модификации<sup><?= $totalCar?></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/car/fill-cars/<?= $model->getId();?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить модификации">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Товары<sup><?= $totalGoods?></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/make/update-available-model/<?= $model->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить доступность">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.show-button').on('click', function(e) {
        var url = e.currentTarget.value;

        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    dialog = bootbox.dialog({
                        message: '<div><i class="fa fa-spin fa-spinner"></i>'+objectToHtml(data.message)+'</div>',
                        closeButton: true,
                        size: 'large'
                    });
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })        
</script>
