<?php
use Stock\Entity\St;

$form = $this->form;

$form->get('office_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('company')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('user')->setAttributes([
    'class'=>'form-control selectpicker', 
    ]);

$form->get('cost')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('doc_date')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('doc_no')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('writeOff')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'st-submit']);

$form->prepare();

$docName = 'Новый';
if ($st){
    $docName = '№ '.$st->getDocNo().' от  '.date('d.m.Y', strtotime($st->getDocDate()));
}

?>



            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title" id="stModalLabel">Списание товаров <?= $docName?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('doc_no')); ?>
                            <?= $this->formElement($form->get('doc_no')); ?>
                            <?= $this->formElementErrors($form->get('doc_no')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('office_id')); ?>
                            <?= $this->formElement($form->get('office_id')); ?>
                            <?= $this->formElementErrors($form->get('office_id')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('status')); ?>
                            <?= $this->formElement($form->get('status')); ?>
                            <?= $this->formElementErrors($form->get('status')); ?>                  
                        </div>
                    </div>
                    <div class="col-xs-2 text-right">
                    </div>    
                    <div class="col-xs-2 text-right">
                        <h1 class="display-4" id="stQuantity"></h1>
                    </div>    
                    <div class="col-xs-1 text-right">
                        <h1 class="display-4" id="stAmount"><?= ($st) ? round($st->getAmount(), 2):"" ?></h1>                        
                    </div>    
                </div>    
                <div class="row">
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('doc_date')); ?>
                            <?= $this->formElement($form->get('doc_date')); ?>
                            <?= $this->formElementErrors($form->get('doc_date')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('company')); ?>
                            <?= $this->formElement($form->get('company')); ?>
                            <?= $this->formElementErrors($form->get('company')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('writeOff')); ?>
                            <?= $this->formElement($form->get('writeOff')); ?>
                            <?= $this->formElementErrors($form->get('writeOff')); ?>                  
                        </div>
                    </div>
                    <div class="col-xs-3">                        
                        <div class="form-group" id="userGroup">
                            <?= $this->formLabel($form->get('user')); ?>
                            <?= $this->formElement($form->get('user')); ?>
                            <?= $this->formElementErrors($form->get('user')); ?>                  
                        </div>
                        <div class="form-group" id="costGroup">
                            <?= $this->formLabel($form->get('cost')); ?>
                            <?= $this->formElement($form->get('cost')); ?>
                            <?= $this->formElementErrors($form->get('cost')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-3">                        
                    </div>    
                </div>        
                <div class="row">
                    <div class="col-xs-12">
                        <div id="stgoodtoolbar">
                            <div class="form-inline" role="form">
                                <button type="button" class="btn btn-default st-good-modal-show" modal-url="/st/good-edit-form">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                </button>
                            </div>
                        </div>
                        <table id="stgoodtable" 
                            data-toggle="stgoodtable" 
                            data-url="/st/good-content/<?= ($st) ? $st->getId():"" ?>"
                            data-side-pagination="client"
                            data-pagination="true"
                            data-page-size = "5"
                            data-page-list="[5, 10, 20, 50]"
                            data-toolbar="#stgoodtoolbar"
                            data-show-refresh="true"
                            data-show-toggle="true"
                            data-query-params="stgoodQueryParams"
                            data-response-handler="stgoodResponseHandler"
                            data-unique-id = "rowNo"
                            >
                            <thead>
                                <tr>
                                     <th data-field="rowNo" data-type="numeric" data-align="right">N</th>
                                     <th data-field="good.code" data-type="numeric">Артикул</th>
                                     <th data-field="good.producer.name" data-type="numeric">Производитель</th>
                                     <th data-field="good.name" data-type="numeric">Наименование</th>
                                     <th data-field='amount' data-formatter="pgPriceFormatter" data-align="right">Цена</th>
                                     <th data-field='quantity' data-align="right">Количество</th>
                                     <th data-field='amount' data-align="right">Сумма</th>
                                     <th data-field="rowNo" data-formatter="pgActiveFormatter" data-width="80"></th>
                                 </tr>                
                            </thead>
                        </table>
                    </div>
                </div>    
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('comment')); ?>
                            <?= $this->formElement($form->get('comment')); ?>
                            <?= $this->formElementErrors($form->get('comment')); ?>                  
                        </div>                        
                    </div>                                            
                </div>        




                <?= $this->formElement($form->get('csrf')); ?>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="submit" class="btn btn-primary" id="st-submit">Сохранить</button>
            </div>

            <?= $this->form()->closeTag(); ?>
            
<script>
    function submitForm(){
        var data = serializeForm('#st-form');
        data.stGood = getFormatedStGood();
        $.ajax({
            type: 'POST',
            url: '/st/edit-form/<?= ($st) ? $st->getId():"" ?>',
            data: $.param(data)
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#stModal').modal('hide');
                    $('#table').bootstrapTable('refresh');
                } else {
                    $('#stModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };
    
    function getFormatedStGood(){
        var data = $('#stgoodtable').bootstrapTable('getData');
        var result = [];
        $.each( data, function( index, row ) {
            var newRow = {
                good_id: row.good.id,
                quantity: row.quantity,
                amount: row.amount,
            };
            result.push(newRow);
        });   
        return result;
    }
    
    
    $('#office').on('change', function(){
        $.getJSON( '/offices/legals/'+$('#office').val(), function( data ) {
            $('#company').empty();
            $.each( data.rows, function( key, value ) {
                $('#company').append('<option value="' + key + '">' + value.name + '</option>');
            });
        });    
    });
        
    function stUpdateTotal(){
        var data = $('#stgoodtable').bootstrapTable('getData');
        var amount = 0; var quantity = 0;
        $.each(data, function( index, value ) {
            amount += Math.round(value.amount*100)/100;
            quantity += Math.round(value.quantity*100)/100; 
        });
        $('#stAmount').html(Math.round(amount*100)/100);
        $('#stQuantity').html(Math.round(quantity*100)/100);
    }
    
    //удаление строки из таблицы
    function removeTableRowByUniqueId(index){
        $('#stgoodtable').bootstrapTable('removeByUniqueId', index);
        stUpdateTotal();
    }
    
    function hideUserGroup()
    {
        $('#userGroup').hide();
        $('#user').attr('required', false);
        if ($("#writeOff").val() == <?= St::WRITE_PAY?>){
            $('#userGroup').show();
            $('#user').attr('required', true);
        }
        
        $('#costGroup').hide();
        $('#cost').attr('required', false);
        if ($("#writeOff").val() == <?= St::WRITE_COST?>){
            $('#costGroup').show();
            $('#cost').attr('required', true);
        }
    }
    
    $( document ).ready(function() {
        
        hideUserGroup();
        
        $('#stgoodtable').bootstrapTable({
            onLoadSuccess: function(res){
                stUpdateTotal();
            }            
        }); 
        
        var forms = $('#st-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('st-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });
        
        $('#writeOff').on('change', function(){
            hideUserGroup();
        });

        $('#user').selectpicker({
                liveSearch: true,
            })
            .ajaxSelectPicker({
                ajax: {
                    url: '/users/live-search',
                    data: function () {
                        var params = {
                            search: '{{{q}}}',
                            limit: 10
                        };
//                        if(gModel.selectedGroup().hasOwnProperty('ContactGroupID')){
//                            params.GroupID = gModel.selectedGroup().ContactGroupID;
//                        }
                        return params;
                    }
                },
                locale: {
                    emptyTitle: 'Поиск по телефону...'
                },
                preprocessData: function(data){
                    var users = [];
                    if(data.hasOwnProperty('rows')){
                        var len = data.rows.length;
                        for(var i = 0; i < len; i++){
                            var curr = data.rows[i];
                            users.push(
                                {
                                    'value': curr.id,
                                    'text': '('+ curr.phone+ ') ' + curr.fullName,
//                                    'data': {
//                                        'icon': 'icon-person',
//                                        'subtext': 'Internal'
//                                    },
                                    'disabled': false
                                }
                            );
                        }
                    }
                    return users;
                },
                preserveSelected: false
            });  
    });    
    
    function stGoodRefreshTable(){
        $('#stgoodtable').bootstrapTable('refresh');
    }
    
    function stgoodQueryParams(params) {
        $('#stgoodtoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#stgoodtable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#stgoodtable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function pgActiveFormatter(value, row){
        var url = '/st/good-edit-form/';
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs st-good-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' unique-id="'+value+'"';
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';

        btn += ' <button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs table-row-remove"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="removeTableRowByUniqueId('+value+')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function pgPriceFormatter(value, row){
        return Math.round(value*100/row.quantity)/100;
    }        
    
    function stgoodResponseHandler(res) {
        return res;
    }     
</script>