<?php
    use Stock\Entity\St;
    
    $this->headTitle('Списание товаров');

    $this->mainMenu()->setActiveItemId('stock');
    $this->mainMenu()->setActiveUrl($this->url('st'));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Склад'=>$this->url('stock'),
                'Списание товаров'=>$this->url('st'),
                ]);


?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button class="btn btn-default st-modal-show" type="button" modal-url="/st/edit-form">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
                <div class="form-group">
                    <div class="btn-group">
                        <input id="searchinput" name="search" style="width: 150px" class="form-control" type="text" placeholder="Артикул">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>
                    <button id="ok" type="submit" class="btn btn-default" title="Поиск">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
                <div class="form-group">
                    <select id="officeSelect" style="width: 100px" class="form-control">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <input id="monthSelect" class="form-control" type="month" placeholder="Период" value="<?= date('Y-m');?>">
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/st/content"
            data-cookie-id-table="stSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="rowStyle"
            >
            <thead>
                <tr>
                     <th data-field="docDate" data-sortable="true" data-width="100">Дата</th>
                     <th data-field="id" data-sortable="false" data-formatter="docNumFormatter" data-width="80" data-align="right">Ид</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-formatter="amountFormatter">Сумма</th>
                     <th data-field='office.name' data-sortable="false">Склад</th>
                     <th data-field='comment' data-sortable="false">Примечание</th>
                     <th data-field='cost.name' data-sortable="false" data-formatter="writeOffFormatter">Списано</th>
                     <th data-field="" data-formatter="activeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    var table = $('#table'),
        ok = $('#ok');
    
    function refreshTable(){
        table.bootstrapTable('refresh');
    }

    $(function () {
        $(".inputclear").click(function(){
            $("#searchinput").val('');
            table.bootstrapTable('refresh');
        });

        ok.click(function () {
            table.bootstrapTable('refresh');
        });
        $(document).on('click', '.st-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'stModal',
                url: url,
                width: '1440px'
            });
        });  
        $(document).on('click', '.st-good-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            var uniqueId = $(e.currentTarget).attr('unique-id');
            if (uniqueId){
                var row = $('#stgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'stGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('change', '#officeSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#yearSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#monthSelect', function (e) {
            refreshTable();
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.office = $('#officeSelect').val();
        params.month = $('#monthSelect').val();
        
        return params;
    }
    
    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status == '<?= St::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        return {classes: retired};
    }
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    

    function docNumFormatter(value, row){
        if (row.aplId > 0){
            return row.aplId;
        }
        return value;
    }    

function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function activeFormatter(value, row){
        var url = '/st/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs st-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function writeOffFormatter(value, row){
        if (row.writeOff == <?= St::WRITE_PAY?>){
            if (row.user){
                return row.user.fullName
            }    
        }
        if (row.writeOff == <?= St::WRITE_INVENTORY?>){
            return 'Инв';
        }
        return value;
    }    

    function responseHandler(res) {
        return res;
    }    
</script>

