<?php
    use Stock\Entity\St;
    
    $this->headTitle('Списание товаров');

    $this->mainMenu()->setActiveItemId('stock');
    $this->mainMenu()->setActiveUrl($this->url('st'));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Склад'=>$this->url('stock'),
                'Списание товаров'=>$this->url('st'),
                ]);


?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button class="btn btn-default st-modal-show" type="button" modal-url="/st/edit-form">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
                <div class="form-group">
                    <div class="btn-group">
                        <input id="searchinput" name="search" style="width: 150px" class="form-control enter-search" type="text" placeholder="Артикул">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>
                    <button id="ok" type="submit" class="btn btn-default" title="Поиск">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
                <div class="form-group">
                    <select id="officeSelect" style="width: 100px" class="form-control">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <input id="monthSelect" class="form-control" type="month" placeholder="Период" value="<?= date('Y-m');?>">
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/st/content"
            data-cookie="true"
            data-cookie-id-table="stSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="stQueryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="rowStyle"
            data-unique-id="id"
            >
            <thead>
                <tr>
                     <th data-field="docDate" data-sortable="true" data-width="100" data-formatter="dateFormatter">Дата</th>
                     <th data-field="id" data-sortable="false" data-formatter="docNumFormatter" data-width="100" data-align="right">Номер</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-width="100" data-formatter="amountFormatter">Сумма</th>
                     <th data-field='office.name' data-sortable="false">Склад</th>
                     <th data-field='comment' data-sortable="false">Примечание</th>
                     <th data-field='cost.name' data-sortable="false" data-formatter="writeOffFormatter">Списано</th>
                     <th data-field="" data-formatter="activeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');
    
    var curentRowIndex = -1;
    
    function setCurrentIndex(index){
        curentRowIndex = index;
    }
    
    function getCurrentIndex(){
        return curentRowIndex;
    }
        
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }

    function stQueryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.office = $('#officeSelect').val();
        params.month = $('#monthSelect').val();
        
        return params;
    }
    
    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status === <?= St::STATUS_RETIRED?>){
           retired += ' retired';
        }
        if (row.writeOff === <?= St::WRITE_COMMISSION?>){
           retired += ' info';
        }
        if (row.statusAccount === <?= St::STATUS_TAKE_NO?>){
           retired += ' warning';
        }
        if (row.statusAccount === <?= St::STATUS_ACCOUNT_NO?>){
           retired += ' status-account-no';
        }
        return {classes: retired};
    }
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    

    function docNumFormatter(value, row){
        if (row.aplId > 0){
            return '<nobr>'+value+' ('+row.aplId+')</nobr>';
        }
        return value;
    }    

    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function activeFormatter(value, row){
        var url = '/st/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs st-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function writeOffFormatter(value, row){
        if (row.writeOff === <?= St::WRITE_PAY?>){
            if (row.user){
                return row.user.fullName;
            }    
        }
        if (row.writeOff === <?= St::WRITE_INVENTORY?>){
            return 'Инв';
        }
        if (row.writeOff === <?= St::WRITE_COMMISSION?>){
            return 'Возврат с комиссии';
        }
        return value;
    }    

    function changeStatus(docId, status){
        $.get( "/st/status/"+docId+'?status='+status, function(data){
            $table.bootstrapTable('updateByUniqueId', {id: docId, row: data});
        });        
    } 
    
    var menu = new BootstrapMenu('.tablerow', {
        fetchElementData: function(rowElem) {
            setCurrentIndex($(rowElem).attr('data-index'));
            return $table.bootstrapTable('getData')[getCurrentIndex()];
        },
        actionsGroups: [
           ['statusActiv', 'statusRetired'], 
           ['history']
        ],      
        actions: {
            statusActiv: {
                name: 'Сделать активным',
                iconClass: 'glyphicon glyphicon-ok',
                onClick: function(row) {
                    changeStatus(row.id, <?= St::STATUS_ACTIVE?>);
                },
                isShown: function(row) {
                    return row.status === <?= St::STATUS_RETIRED?>;
                },
                isEnabled: function(row) {
                    return row.status === <?= St::STATUS_RETIRED?>;
                }                
            }, 
            statusRetired: {
                name: 'Сделать не активным',
                iconClass: 'glyphicon glyphicon-remove',
//                classNames: 'bg-danger',
                onClick: function(row) {
                    changeStatus(row.id, <?= St::STATUS_RETIRED?>);
                },
                isShown: function(row) {
                    return row.status === <?= St::STATUS_ACTIVE?>;
                },
                isEnabled: function(row) {
                    return row.status === <?= St::STATUS_ACTIVE?>;
                }                
            },
            history: {
                name: 'История',
                iconClass: 'glyphicon glyphicon-list-alt',
//                classNames: 'bg-danger',
                onClick: function(row) {
                    $.ajax({
                        type: "GET",
                        url: "/log/history/"+row.id+"?docType=vt",
                        success: function (result) {
                            bootbox.alert({
                                size: "large",
                                message: result
                            });
                        }
                    });                    
                }
            }
        }
    });        

    function responseHandler(res) {
        return res;
    }    
</script>

