<?php

$form = $this->form;

$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Для документов, доставки и т.п.'    
    ]);

$form->get('address')->setAttributes([
    'class'=>'form-control', 
    'label' => 'Адрес'
    ]);

$form->get('addressSms')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'address-submit']);

$form->prepare();

?>

            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title">Адреса</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-10">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('name')); ?>
                            <?= $this->formElement($form->get('name')); ?>
                            <?= $this->formElementErrors($form->get('name')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('address')); ?>
                            <?= $this->formElement($form->get('address')); ?>
                            <?= $this->formElementErrors($form->get('address')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('addressSms')); ?>
                            <?= $this->formElement($form->get('addressSms')); ?>
                            <?= $this->formElementErrors($form->get('addressSms')); ?>                  
                        </div>

                    </div>        
                </div>
            </div>    
                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="address-submit">Сохранить</button>
            </div>
                
            <?= $this->form()->closeTag(); ?>
            
<script>
    $('#address-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/contact/address-form/<?= $contact->getId() ?>?address=<?= ($address ? $address->getId():'') ?>',
            data: $('#address-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
                    window.location.reload();
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");

            });
    })    
</script>