<?php

$form = $this->legalForm;

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('inn')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('kpp')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('ogrn')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('okpo')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('ogrn')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('head')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('chiefAccount')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('address')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('info')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('dateStart')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить']);

$form->prepare();

?>


            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Организация</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('name')); ?>
                            <?= $this->formElement($form->get('name')); ?>
                            <?= $this->formElementErrors($form->get('name')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('inn')); ?>
                            <?= $this->formElement($form->get('inn')); ?>
                            <?= $this->formElementErrors($form->get('inn')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('kpp')); ?>
                            <?= $this->formElement($form->get('kpp')); ?>
                            <?= $this->formElementErrors($form->get('kpp')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('ogrn')); ?>
                            <?= $this->formElement($form->get('ogrn')); ?>
                            <?= $this->formElementErrors($form->get('ogrn')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('okpo')); ?>
                            <?= $this->formElement($form->get('okpo')); ?>
                            <?= $this->formElementErrors($form->get('okpo')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('dateStart')); ?>
                            <?= $this->formElement($form->get('dateStart')); ?>
                            <?= $this->formElementErrors($form->get('dateStart')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('status')); ?>
                            <?= $this->formElement($form->get('status')); ?>
                            <?= $this->formElementErrors($form->get('status')); ?>                  
                        </div>
                    </div>                

                    <div class="col-md-6">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('address')); ?>
                            <?= $this->formElement($form->get('address')); ?>
                            <?= $this->formElementErrors($form->get('address')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('head')); ?>
                            <?= $this->formElement($form->get('head')); ?>
                            <?= $this->formElementErrors($form->get('head')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('chiefAccount')); ?>
                            <?= $this->formElement($form->get('chiefAccount')); ?>
                            <?= $this->formElementErrors($form->get('chiefAccount')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('info')); ?>
                            <?= $this->formElement($form->get('info')); ?>
                            <?= $this->formElementErrors($form->get('info')); ?>                  
                        </div>

                        <?= $this->formElement($form->get('csrf')); ?>

                    </div>
                </div>
            </div>    
                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="legal-submit">Сохранить</button>
            </div>
            
            <?= $this->form()->closeTag(); ?>
            
<script>
    $('#legal-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/contact/legal-form/<?= $contact->getId() ?>',
            data: $('#legal-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#legal-modal').modal('hide');
                    window.location.reload();
                } else {
                    $('#legal-modal-content').html(data);
                }    
            })
            .fail(function () {
                alert("Posting failed.");

            });
    })
    
    $('#inn').on('blur', function() {
        var inn = $('#inn').val();
        if (inn){
            $.ajax({
                type: 'GET',
                url: '/contact/find-legal/'+inn,
            })
                .done(function (data) {
                    if (data.inn){
                        if (confirm('Есть юр. лицо с таким ИНН. Заполнить поля?')){
                            $.each( data, function( key, value ) {
                                if ($('#'+key).length) {
                                    $('#'+key).val(value);
                                }
                            });                            
                        }        
                    }    
                })
                .fail(function (error) {
                    console.log(error);
                });
            }        
    })
    
</script>