<?php

$form = $this->form;

$form->get('phone')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'8 (000) 000-0000',
    'aria-describedby' => "basic-addon2",
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Добавочный, комментарий',
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'phone-submit']);

$form->prepare();

?>

            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title">Добавить контактный телефон</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-10">
                        <div class="form-group">
                            <?//= $this->formLabel($form->get('name')); ?>
                            <?= $this->formElement($form->get('phone')); ?>
                            <?= $this->formElementErrors($form->get('phone')); ?>                  
                        </div>

                        <div class="form-group">
                            <?//= $this->formLabel($form->get('description')); ?>
                            <?= $this->formElement($form->get('comment')); ?>
                            <?= $this->formElementErrors($form->get('comment')); ?>                  
                        </div>

                    </div>        
                </div>
            </div>    
                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="phone-submit">Сохранить</button>
            </div>
                
            <?= $this->form()->closeTag(); ?>
            
<script>
    $('#phone_name').mask('8 (000) 000-0000', {selectOnFocus: false});
    
    $('#phone-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/contact/phone-form/<?= $contact->getId() ?>?phone=<?= ($phone ? $phone->getId():'') ?>',
            data: $('#phone-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
                    window.location.reload();
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");

            });
    })    
</script>