<?php
$this->headTitle('Биграмы');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Биграмы'=>$this->url('name', ['action' => 'index-bigram'])
            ]);

$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
?>

<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
                <select id="statusSelect" style="width: 170px" class="form-control">
                    <?php foreach ($statuses as $key => $value):?>
                        <option value="<?= $key?>"><?= $value?></option>
                    <?php endforeach;?>
                </select>
                <select id="flagSelect" style="width: 170px" class="form-control">
                    <?php foreach ($flags as $key => $value):?>
                        <option value="<?= $key?>"><?= $value?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/name/content-bigram"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-sort-name="frequency"
            data-sort-order="desc"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                     <th data-field="bilemma" data-formatter="bigramFormatter" data-sortable="true">Билемма</th>
                     <th data-field="status" data-formatter="statusFormatter" data-sortable="true">Статус</th>             
                     <th data-field="flag" data-formatter="flagFormatter" data-sortable="true">Список</th>             
                     <th data-field="idf" data-sortable="true">IDF</th>             
                     <th data-field="frequency" data-sortable="true">Частота</th>             
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Всего биграм
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?= $total?>
                        </div>
                        <div class="pull-right">
                            <button value="/name/delete-empty-bigram/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Удаление пустых">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <?php foreach($statusBigramCount as $row):?>
                            <span onclick="$('#statusSelect').val(<?= $row['status']?>); refreshTable()"><?= $statuses[$row['status']].': '.$row['bigramCount'] ?></span><br/>
                        <?php endforeach;?>
                    </div>
                </div>    
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Пересчет количества
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <span>артикулов</span>
                        </div>
                        <div class="pull-right">
                            <button value="/name/article-count-bigram/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Обновить количество артикулов">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var $table = $('#table'),
        $ok = $('#ok'), 
        $statusSelect = $('#statusSelect');
        $flagSelect = $('#flagSelect');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
        $statusSelect.change(function () {
            $table.bootstrapTable('refresh');
        });
        $flagSelect.change(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }
        
        params.status = $statusSelect.val();
        params.flag = $flagSelect.val();
        
        return params;
    }
    
    function bigramFormatter(value, row){
        var str = '<div class="pull-left">';
        str += '<a href="/name/view-bigram/' + row.id + '" target="_blank">' + value + '</a>';
        str += '</div>';

        return str; 
    }    
    
    function statusFormatter(value, row){
        switch (value){
            <?php foreach ($statuses as $key => $value):?>
                case '<?= $key?>': return '<?= $value?>';
            <?php endforeach;?>
            default: return 'Неизвестно';    
        }
    }
    
    function flagFormatter(value, row){
        switch (value){
            <?php foreach ($flags as $key => $value):?>
                case '<?= $key?>': return '<?= $value?>';
            <?php endforeach;?>
            default: return 'Неизвестно';    
        }
    }
    
    function responseHandler(res) {
        return res;
    }    
</script>
