<?php
$this->headTitle('Токены');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Токены'=>$this->url('name', ['action' => 'index-token'])
            ]);

$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
?>

<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/name/content-token"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric">ID</th>
                     <th data-field="lemma" data-formatter="tokenFormatter">Токен</th>
                     <th data-field="status" data-formatter="statusFormatter">Статус</th>             
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Строки прайсов
                    </div>
                    <div class="panel-body">
                        <div>
                             <?= $bind ?> - обработано
                        </div>     
                        <div>
                            <?= $noBind?> - не обработано
                        </div>
                    </div>
                </div>    
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Всего токенов
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?= $total?>
                        </div>
                        <div class="pull-right">
                            <button value="/oem/delete-empty/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Удаление пустых">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var $table = $('#table'),
        $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams() {
        var params = {offset: 0, limit: 10};
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function tokenFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/name/view-token/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function statusFormatter(value, row){
        switch (value){
            case '1': return 'RU Словарь'; 
            case '2': return 'RU'; 
            case '3': return 'RU 1'; 
            case '4': return 'RU Аббревиатура'; 
            case '11': return 'EN Словарь'; 
            case '12': return 'EN'; 
            case '13': return 'EN 1'; 
            case '14': return 'EN Аббревиатура'; 
            case '21': return 'Число'; 
            default: return 'Неизвестно';    
        }
    }
    
    function responseHandler(res) {
        return res;
    }    
</script>
