<?php
use Application\Entity\GroupSite;

$this->headTitle('Группы наименований');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Группы наименований'=>$this->url('name', ['action' => 'token-group'])
            ]);

?>

<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <div class="btn-group">
                        <input name="search" style="width: 300px" class="form-control enter-search" 
                               type="text" onfocus="this.select();" placeholder="Поиск">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>    
                    <button id="ok" type="submit" class="btn btn-default">OK</button>
                </div>
                
                <div class="form-group">
                    <select type="select" class="form-control" id="goodCountLevel">
                        <option value="0_-1">Товаров больше 0</option>
                        <option value="2_0">Товаров больше 1</option>
                        <option value="5_0">Товаров больше 5</option>
                        <option value="10_0" selected>Товаров больше 10</option>
                        <option value="100_0">Товаров больше 100</option>
                        <option value="500_0">Товаров больше 500</option>
                        <option value="1000_0">Товаров больше 1000</option>
                        <option value="0_0">Товаров =0</option>
                        <option value="1_1">Товаров =1</option>
                        <option value="2_2">Товаров =2</option>
                        <option value="5_5">Товаров =5</option>
                        <option value="10_10">Товаров =10</option>
                    </select>
                    <select type="select" class="form-control" id="withoutName">
                        <option value="0">Все</option>
                        <option value="1">Без названия</option>
                        <option value="2">С названием</option>
                    </select>
                    <select type="select" class="form-control" id="withGenericGroup">
                        <option value="0">Все</option>
                        <option value="1">с группами ТД</option>
                        <!--<option value="2">без групп ТД</option>-->
                    </select>
                    <select type="select" class="form-control" id="withGroupSite">
                        <option value="0">Все</option>
                        <option value="2">без категорий</option>
                        <option value="1">с категориями</option>
                    </select>
                </div>    
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/name/token-group-content"
            data-side-pagination="server"
            data-cookie="true"
            data-cookie-id-table="tokenGroupSaveId"
            data-cookie-expire="1m"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-sort-name="goodCount"
            data-sort-order="desc"
            data-id-field="id"
            data-unique-id="id"
            data-classes = "table table-bordered table-hover table-condensed"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true" data-width="10">ID</th>
                     <th data-field="lemms" data-formatter="nameFormatter" data-sortable="true">Наименование</th>
                     <th data-field="groupSite" data-formatter="groupSiteFormatter" data-sortable="true">Категория</th>
<!--                     <th data-field="lemms" data-sortable="true">Токены</th>             -->
                     <th data-field="goodCount" data-align='right' data-sortable="true" data-width="10">Товаров</th>             
                     <th data-field="movement" data-align='right' data-sortable="true" data-width="10">Движений</th>             
                     <th data-field="" data-formatter="activeFormatter" data-align="center" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Всего групп наименований
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?= $total?>
                        </div>
                        <div class="pull-right">
                            <button value="/name/delete-empty-token-group/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Удаление пустых">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>                             
<!--                            <button value="/name/fill-token-group-token/" class="btn btn-default btn-xs refresh-table-button"
                                    title="Заполнить токены группы">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                            <button value="/name/fill-token-group-bigram/" class="btn btn-default btn-xs refresh-table-button"
                                    title="Заполнить биграмы группы">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             -->
                            <button value="/name/support-title-tokens/" class="btn btn-info btn-xs refresh-table-button"
                                    title="Поддержка токенов наименований">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                            <button value="/name/support-title-bigrams/" class="btn btn-info btn-xs refresh-table-button"
                                    title="Поддержка биграм наименований">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
<!--                            <button value="/ml/token-groups-to-csv/" class="btn btn-default btn-xs refresh-table-button"
                                    title="Выгрузить в CSV">
                                <span class="glyphicon glyphicon-download-alt" ></span>
                            </button>                             -->
                        </div>
                    </div>
                </div>    
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Пересчет количества
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <span>товаров</span>
                        </div>
                        <div class="pull-right">
                            <button value="/name/good-count-token-group/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Обновить количество товара">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <span>движений</span>
                        </div>
                        <div class="pull-right">
                            <button value="/name/movement-token-group/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Обновить количество движений">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
<!--                    <div class="panel-body">                    
                        <div class="pull-left">
                            С группами <span id="goodsWithTokenGroup" class="badge">0</span>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Без групп <span id="goodsWithoutTokenGroup" class="badge">0</span>
                        </div>
                    </div>-->
                </div>    
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Охват
                    </div>
                    <div class="panel-body">
                        <div>
                            <span><?= $totalGoods.'/'.$goodCoverage.'/'.$nameCoverage.'/'.$goodWithBestName ?></span>
                        </div>
                        <div>
                            <span><?= '('.round($goodCoverage*100/$totalGoods).'/'.round($nameCoverage*100/$totalGoods).'/'.round($goodWithBestName*100/$totalGoods).' %%)' ?></span>
                        </div>
                        <div class="pull-right">
<!--                            <button value="/name/good-count-token-group/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Обновить количество товара">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> -->
                        </div>
                    </div>
                </div>    
            </div>
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');

    function totalFeatures(){
        $(".badge").each(function( index ) {
            var node = $(this).attr('id');
            $.getJSON('/name/token-group-total-feature/?feature=' + node, function(data){
                $('#'+node).text(data['total']);
            });
        });        
    }

    function setGroupSiteCookie(selectedValue){
        let expires = 30;
        Cookies.set('selectedGroupSite', selectedValue, { expires: expires});        
    }
    
    function getGroupSiteCookie(){
        return Cookies.get('selectedGroupSite');
    }    
    
    $(window).on('load', function() {
        totalFeatures();
    });
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }

    function updateTokenGroupGroupSite(tokenGroupId, groupSiteId){
        $.getJSON('/name/update-token-group-category/'+tokenGroupId+'?groupSite='+groupSiteId, function( data ) {
            if (data.row && data.id){
                $table.bootstrapTable('updateByUniqueId', {id: data.id, row: data.row});
            }
        });                            
    }    

    function operType(rowId, rowName, rowGroupSite){        

        $.getJSON( '/group-site/content?hasChild=<?= GroupSite::HAS_NO_CHILD?>&sort=code', function( data ) {
            var inputOptions = [{text: 'без категории', value: -1}];
            $.each(data.rows, function( index, value ) {
                inputOptions.push({text: value.fullName, value: value.id});
            });
            bootbox.prompt({
                title: 'Укажите категорию',
                message: '<p>Выберете категорию для <b>'+rowName+'</b>:</p>',
                inputType: 'select',
                value: (rowGroupSite > 0) ? rowGroupSite:getGroupSiteCookie(),        
                inputOptions: inputOptions,
                callback: function (result) {
//                    console.log(result); return;               
                    if (result){
                        setGroupSiteCookie(result);
                        updateTokenGroupGroupSite(rowId, result);
                    }    
                }
            });
        }); 
        return;
    }
    
    $(function () {
    
        $(".inputclear").click(function(){
            var val = $(".enter-search").val();
            $(".enter-search").val('');
            if (val){
                refreshTable();
            }    
        });
    
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
        $('#goodCountLevel').change(function (){
            $table.bootstrapTable('refresh');
        });
        $('#withoutName').change(function (){
            $table.bootstrapTable('refresh');
        });
        $('#withGenericGroup').change(function (){
            $table.bootstrapTable('refresh');
        });
        $('#withGroupSite').change(function (){
            $table.bootstrapTable('refresh');
        });
        $(document).on('click', '.category-select', function (e) {
            operType($(this).attr('data-id'), $(this).attr('data-name'), $(this).attr('data-group-site'));
        });
        
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.goodCountLevel = $("#goodCountLevel").val();
        params.withoutName = $("#withoutName").val();
        params.withGenericGroup = $("#withGenericGroup").val();
        params.withGroupSite = $("#withGroupSite").val();
        
        return params;
    }
    
    function nameFormatter(value, row){
        var str = row.name;
        if (!str){
            str = '---';
        }
        var link = '<a href="/name/view-token-group/'+row.id+'" target="_blank">';
        link += str;
        link += '</a>';
        
        var tokens = '<div style="font-size: xx-small; color: gray">';
        tokens += value;
        tokens += '</div>';
        return link + tokens;        
    }
    
    function groupSiteFormatter(value, row){
        var groupSiteName = 'Не назаначена';
        var groupSiteId = -1;
        
        if (row.groupSite){
            groupSiteName = row.groupSite.fullName;
            groupSiteId = row.groupSite.id;
        }
        
        var result =  '<p><a href="#" class="category-select"';
        result += ' data-id="'+row.id+'" data-name="'+row.name+'"';
        result += ' data-group-site="'+groupSiteId+'">';
        result +=   groupSiteName +'</a></p>'; 
    
        return result;
    }
        
    function activeFormatter(value, row){
        var urlEdit = '/name/token-group-name-form/'+row.id;
        var btnEdit = '<nobr><button';
        btnEdit += ' type="button"';
        btnEdit += ' class="btn btn-default btn-xs"';
        btnEdit += ' aria-label="Left Align"'; 
        btnEdit += ' title="Изменить наименование группы"'; 
        btnEdit += ' onclick="promptDialog(\''+urlEdit+'\', \''+row.name+'\')">';
        btnEdit += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btnEdit += '</button>';

        var url = '/name/delete-token-group-form/'+row.id;
        var btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button></nobr>';
        return btnEdit + ' ' + btn;
    }    

    function responseHandler(res) {
        return res;
    }    
    
    
    
    /**
    * Промпт диалог
    * @param {string} url
    * @param {string} initValue
    */
    function promptDialog(url, initValue) {
        if (url){            
            var dialog = bootbox.prompt({ 
                size: "medium",
                value: initValue,
                title: 'Наименование группы', 
                callback: function(result){
                    /* result = String containing user input if OK clicked or null if Cancel clicked */
                    if (result){
                        $.ajax({
                            type: 'GET',
                            url: url+'?prompt='+result
                        })
                            .done(function (data) {
                                if (data === 'ok'){
                                    $('#table').bootstrapTable('refresh');
                                }    
                            })
                            .fail(function (e) {
                                bootbox.alert("Произошла ошибка при выполнении операции.");
                            });
                    }        
                }
            });
        }        
    }    
</script>
