<?php
$this->headTitle('Группы наименований');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Группы наименований'=>$this->url('name', ['action' => 'token-group'])
            ]);

$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
?>

<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/name/token-group-content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                     <th data-field="name" data-formatter="nameFormatter" data-sortable="true">Наименование</th>
<!--                     <th data-field="lemms" data-sortable="true">Токены</th>             -->
                     <th data-field="goodCount" data-align='right' data-sortable="true">Товаров</th>             
                     <th data-field="" data-formatter="activeFormatter" data-align="center"></th>
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Всего групп наименований
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?= $total?>
                        </div>
                        <div class="pull-right">
                            <button value="/name/delete-empty-token-group/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Удаление пустых">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>                             
<!--                            <button value="/name/delete-all-token-group/" class="btn btn-danger btn-xs refresh-table-button"
                                    title="Удаление всех">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>                             -->
                        </div>
                    </div>
                </div>    
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Пересчет количества
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <span>товаров</span>
                        </div>
                        <div class="pull-right">
                            <button value="/name/good-count-token-group/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Обновить количество товара">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                </div>    
            </div>
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var $table = $('#table'),
        $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function nameFormatter(value, row){
        var str = value;
        if (!str){
            str = '---';
        }
        var link = '<a href="/name/view-token-group/'+row.id+'" target="_blank">';
        link += str;
        link += '</a>';
        
        var tokens = '<div style="font-size: xx-small; color: gray">';
        tokens += row.lemms;
        tokens += '</div>';
        return link + tokens;        
    }
        
    function activeFormatter(value, row){
        var urlEdit = '/name/token-group-name-form/'+row.id;
        var btnEdit = '<button';
        btnEdit += ' type="button"';
        btnEdit += ' class="btn btn-default btn-xs"';
        btnEdit += ' aria-label="Left Align"'; 
        btnEdit += ' title="Изменить наименование группы"'; 
        btnEdit += ' onclick="promptDialog(\''+urlEdit+'\', \''+row.name+'\')">';
        btnEdit += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btnEdit += '</button>';

        var url = '/name/delete-token-group-form/'+row.id;
        var btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btnEdit + ' ' + btn;
    }    

    function responseHandler(res) {
        return res;
    }    
    
    /**
    * Промпт диалог
    *
    */
    function promptDialog(url, initValue) {
        if (url){            
            var dialog = bootbox.prompt({ 
                size: "medium",
                value: initValue,
                title: 'Наименование группы', 
                callback: function(result){
                    /* result = String containing user input if OK clicked or null if Cancel clicked */
                    if (result){
                        $.ajax({
                            type: 'GET',
                            url: url+'?prompt='+result,
                        })
                            .done(function (data) {
                                if (data == 'ok'){
                                    $('#table').bootstrapTable('refresh');
                                }    
                            })
                            .fail(function (e) {
                                bootbox.alert("Произошла ошибка при выполнении операции.");
                            });
                    }        
                }
            });
        }        
    }    
</script>
