<?php

$form = $this->form;

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'token-submit']);

$form->prepare();

?>

            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title">Лемма</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-10">
                        <div class="input-group">
                            <?= $this->formElement($form->get('name')); ?>
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary" id="token-submit">Сохранить</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                            </div>    
                        </div>    
                        <div class="input-group">
                            <?= $this->formElementErrors($form->get('name')); ?>                  
                        </div>    
                    </div>        
                </div>
            </div>    
                
            <?= $this->form()->closeTag(); ?>
            
<script>
    $('#token-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/name/update-token-form/<?= $token->getId() ?>',
            data: $('#token-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
                    window.location.reload();
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");

            });
    })    
</script>