<?php
$this->headTitle($token->getLemma());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Токены'=>$this->url('name', ['action' => 'index-token']),
            $token->getLemma()=>$this->url('name', ['action'=>'view-token', 'id'=>$token->getId()])
            ]);

?>
<h1>
    <?= $this->escapeHtml($token->getLemma()); ?>    
    <sup>
        <small>
            <?= $token->getStatusAsString();?>
        </small>
    </sup>
</h1>
<p>
    <small class="text-success">
        <?= $token->getCorrect();?>
    </small>
</p>
<p>
    <?php if ($token->getStatus() != $token::IS_RU_ABBR && $token->getStatus() != $token::IS_EN_ABBR):?>
        <span>
            <small>
                <button value="/name/update-token-form/<?= $token->getId() ?>"" class="btn btn-info btn-xs"
                        data-toggle="modal" data-target="#modal-dialog" title="Добавить в свой словарь">
                    <span class="glyphicon glyphicon-plus-sign" ></span>
                </button> 
            </small>
        </span>
    <?php endif; ?>    
    <?php if ($token->getCorrect() && ($token->getStatus() == $token::IS_DICT || $token->getStatus() == $token::IS_EN_DICT)):?>
        <span>
            <small>
                <button value="/name/delete-token-from-my-dict/<?= $token->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                        title="Удалить из словаря">
                    <span class="glyphicon glyphicon glyphicon-minus-sign" ></span>
                </button> 
            </small>
        </span>
    <?php endif; ?>    
    <?php if (in_array($token->getStatus(), [$token::IS_EN, $token::IS_EN_ABBR])):?>
        <span>
            <small>
                <button value="/name/abbr/<?= $token->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                        title="Установить/Снять пометрку аббревиатуры">
                    <span class="">ABBR</span>
                </button> 
            </small>
        </span>
    <?php endif; ?>    
    <?php if ($token->inBlackList()):?>
        <span>
            <small>
                <button value="/name/token-flag/<?= $token->getId()?>?flag=<?= $token::WHITE_LIST?>" class="btn btn-danger btn-xs refresh-table-button"
                        title="Удалить из черного списка">
                    <span class="glyphicon glyphicon glyphicon-ok-circle" ></span>
                </button> 
            </small>
        </span>
    <?php else: ?>
        <?php if (!$token->inGrayList()):?>
            <span>
                <small>
                    <button value="/name/token-flag/<?= $token->getId()?>?flag=<?= $token::BLACK_LIST?>" class="btn btn-default btn-xs refresh-table-button"
                            title="Добавить в черный список">
                        <span class="glyphicon glyphicon glyphicon-ban-circle" ></span>
                    </button> 
                </small>
            </span>
        <?php endif; ?>    
    <?php endif; ?>    
    <?php if ($token->inGrayList()):?>
        <span>
            <small>
                <button value="/name/token-flag/<?= $token->getId()?>?flag=<?= $token::WHITE_LIST?>" class="btn btn-warning btn-xs refresh-table-button"
                        title="Удалить из серого списка">
                    <span class="glyphicon glyphicon glyphicon-ok-circle" ></span>
                </button> 
            </small>
        </span>
    <?php else: ?>
        <?php if (!$token->inBlackList()):?>
            <span>
                <small>
                    <button value="/name/token-flag/<?= $token->getId()?>?flag=<?= $token::GRAY_LIST?>" class="btn btn-info btn-xs refresh-table-button"
                            title="Добавить в серый список">
                        <span class="glyphicon glyphicon glyphicon-ban-circle" ></span>
                    </button> 
                </small>
            </span>
        <?php endif; ?>    
    <?php endif; ?>    
</p>
<table class="table table-striped">
    <tr>
        <td colspan="2">            
            <?php if ($prev):?>
                <a href="/name/view-token/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getLemma()?></a>
            <?php endif;?>            
        </td>
        <td  colspan="3" align="right">
            <?php if ($next):?>
                <a href="/name/view-token/<?= $next[0]->getId()?>"><?= $next[0]->getLemma()?>&rarr;</a>
            <?php endif;?>                            
        </td>
    </tr>
    <tr>
        <td colspan="3">
            <?= $this->paginationControl($rawprices,
                        'Sliding',
                        'application/partial/paginator', 
                        ['route' => array('route' => 'name', 'action' => 'view-token', 'id' => $token->getId())]); ?>
            
        </td>
        <td align="right" valign="center" colspan="2">
            <b><?= $token->getFrequency()?></b>
             <?= round($token->getIdf(), 2)?>
            <button value="/name/update-article-count-token/<?= $token->getId()?>" class="btn btn-warning btn-xs refresh-table-button"
                    title="Обновить количество товара">
                <span class="glyphicon glyphicon-refresh" ></span>
            </button>
        </td>
    </tr>
    <?php    foreach ($articles as $article):?>
        <?php $rawprices = $articleManager->articleRawprices($article, 1);?>
        <?php    foreach ($rawprices as $rawprice):?>
            <tr>
                <td>
                    <a href="<?= $this->url('producer', ['action' => 'article-view', 'id' => $article->getId()]);?>">
                        <?= $article->getCode();?>
                    </a>   
                </td>
                <td>
                    <a href="<?= $this->url('producer', ['action' => 'unknown-view', 'id' => $rawprice->getUnknownProducer()->getId()]);?>">
                        <?= $rawprice->getUnknownProducer()->getName();?>
                    </a>   
                </td>
                <td>
                    <a href="<?= $this->url('rawprice', ['action' => 'view', 'id' => $rawprice->getId()]);?>">
                        <?= $rawprice->getGoodname();?>
                    </a>    
                    <?php $tokens = $rawprice->getTokens(); ?>
                    <?php if(count($tokens)):?>  
                        <div>    
                            <?php foreach($tokens as $tokenraw):?>
                                <span style="font-size: xx-small; font-weight: <?= ($tokenraw->getStatus() == $tokenraw::IS_DICT) ? 'bold':'normal' ?>">
                                    <a href="/name/view-token/<?= $tokenraw->getId() ?>"><?= $tokenraw->getLemma() ?></a>
                                </span>
                            <?php endforeach;?>
                        </div>        
                    <?php endif;?>                                                
                </td>
                <td align="right">
                    <?= $rawprice->getPrice();?>
                </td>
                <td align="right">
                    <?= $rawprice->getRest();?>
                </td>
            </tr>
        <?php endforeach;?>        
    <?php endforeach;?>        
    <tr>
        <td colspan="5">
            <?= $this->paginationControl($rawprices,
                        'Sliding',
                        'application/partial/paginator', 
                        ['route' => array('route' => 'name', 'action' => 'view-token', 'id' => $token->getId())]); ?>
            
        </td>
    </tr>
</table>
