<?php
$this->headTitle($tokenGroup->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Группы наименований'=>$this->url('name', ['action' => 'token-group']),
            $tokenGroup->getName()=>$this->url('name', ['action'=>'view-token-group', 'id'=>$tokenGroup->getId()])
            ]);

$this->headLink()
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js')
            ; 

?>
<h1>
    <?= $this->escapeHtml(($tokenGroup->getName()) ? $tokenGroup->getName():'---'); ?>    
    <button onclick="promptDialog('/name/token-group-name-form/<?= $tokenGroup->getId()?>', '<?= $this->escapeHtml($tokenGroup->getName()); ?>')" 
            class="btn btn-default btn-xs" 
            title="Изменить наименование группы">
        <span class="glyphicon glyphicon-pencil" ></span>
    </button> 

</h1>
<div>
    <?= $tokenGroup->getLemms()?> (<?= $meanFrequency['mean']; ?>)
</div>
<div>
    <?php foreach ($aplGroups as $aplGroup):?>
        <span><?= $aplGroup['groupApl']?></span> 
        <span>(<?= $aplGroup['goodCount']?>)</span>
    <?php endforeach;?>     
</div>
<div class="row">
    <div class="col-md-9">
        <ul class="nav nav-tabs" id="featureTab" role="tablist">
            <li role="presentation"><a href="#goods" role="tab" id="goods-tab" data-toggle="tab" aria-controls="price" aria-expanded="true">Товары <span id="goodBadge" class="badge">0</span></a></li>
            <li role="presentation"><a href="#tokens" role="tab" id="tokens-tab" data-toggle="tab" aria-controls="tokens" aria-expanded="true">Токены <span id="tokenBadge" class="badge">0</span></a></li>
            <li role="presentation"><a href="#bigrams" role="tab" id="bigrams-tab" data-toggle="tab" aria-controls="bigrams" aria-expanded="true">Биграмы <span id="bigramBadge" class="badge">0</span></a></li>
        </ul>
        <div class="tab-content" id="featureTabContent">
            <div class="tab-pane fade" role="tabpanel" id="goods" aria-labelledby="goods-tab">
                <table id="goodTable" 
                    data-toggle="table" 
                    data-url="/name/token-group-good-content/<?= $tokenGroup->getId()?>"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#goodsToolbar"
                    data-show-refresh="true"
                    data-show-toggle="true"
                    data-query-params="goodQueryParams"
                    data-response-handler="responseHandler"
                    >
                    <thead>
                        <tr>
                             <th data-field="goodId" data-sortable="true">Id</th>
                             <th data-field="goodCode" data-sortable="true">Артикул</th>
                             <th data-field="producerName" data-sortable="true">Производитель</th>
                             <th data-field="goodNames" data-sortable="true">Наименования</th>
                         </tr>                
                    </thead>
                </table>
            </div>
            <div class="tab-pane fade" role="tabpanel" id="tokens" aria-labelledby="tokens-tab">
                <div id="tokensToolbar">
                    <div class="form-inline" role="form">
<!--                        <div class="form-group">
                            <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                        </div>
                        <button id="ok" type="submit" class="btn btn-default">OK</button>-->
                        <select id="tokenStatusSelect" style="width: 170px" class="form-control">
                            <?php foreach ($tokenStatuses as $key => $value):?>
                                <option value="<?= $key?>"><?= $value?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                </div>
                <table id="tokenTable" 
                    data-toggle="table" 
                    data-url="/name/token-group-token-content/<?= $tokenGroup->getId()?>"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#tokensToolbar"
                    data-show-refresh="true"
                    data-show-toggle="true"
                    data-query-params="tokenQueryParams"
                    data-response-handler="responseHandler"
                    >
                    <thead>
                        <tr>
                             <th data-field="tokenCount">Частота</th>
                             <th data-field="lemma" data-formatter="tokenFormatter">Токен</th>
                             <th data-field="lemma" data-formatter="dispalyTokenFormatter">Выводить</th>
                         </tr>                
                    </thead>
                </table>
            </div>
            <div class="tab-pane fade" role="tabpanel" id="bigrams" aria-labelledby="bigrams-tab">
                <div id="bigramsToolbar">
                    <div class="form-inline" role="form">
<!--                        <div class="form-group">
                            <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                        </div>
                        <button id="ok" type="submit" class="btn btn-default">OK</button>-->
                        <select id="bigramStatusSelect" style="width: 170px" class="form-control">
                            <?php foreach ($bigramStatuses as $key => $value):?>
                                <option value="<?= $key?>"><?= $value?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                </div>
                <table id="bigramTable" 
                    data-toggle="table" 
                    data-url="/name/token-group-bigram-content/<?= $tokenGroup->getId()?>"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#bigramsToolbar"
                    data-show-refresh="true"
                    data-show-toggle="true"
                    data-query-params="bigramQueryParams"
                    data-response-handler="responseHandler"
                    >
                    <thead>
                        <tr>
                             <th data-field="bigramCount">Частота</th>
                             <th data-field="bilemma" data-formatter="bigramFormatter">Билема</th>
                             <th data-field="bilemma" data-formatter="dispalyBigramFormatter">Выводить</th>
                         </tr>                
                    </thead>
                </table>
            </div>
        </div>    
    </div>    
    <div class="col-md-3">
        <ul class="list-group">
            <?php if ($tdGroups):?>
                <?php foreach ($tdGroups as $tdGroup):?>
                    <li class="list-group-item <?= ($tdGroupActive == $tdGroup[0]->getId()) ? 'active':''?>">
                        <span class="badge"><?= $tdGroup['goodCount']?></span>
                        <a href='<?= $this->url('name', ['action'=>'view-token-group', 'id'=>$tokenGroup->getId()], ['query' => ['tdGroup' => $tdGroup[0]->getId()]])?>'>
                            <?= $tdGroup[0]->getName()?>
                        </a>                    
                    </li>
                <?php endforeach;?>
            <?php endif;?>        
        </ul>
        <?php if ($this->access('rate.manage')):?>
            <div class="panel panel-info">
                <?php if ($rate):?>
                    <div class="panel-heading">
                        Расценка
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Мин. цена
                        </div>
                        <div class="pull-right">
                            <?= $rate->getMinPrice()?>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                           Макс. цена
                        </div>
                        <div class="pull-right">
                            <?= $rate->getMaxPrice()?>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <a href="<?= $this->url('rate', ['action' => 'view', 'id' => $rate->getId()])?>">
                                <?= $rate->getName()?>
                            </a>
                        </div>
                        <?php if (!$rate->getTokenGroup()):?>
                            <div class="pull-right">
                                <button value="/rate/add/?tokenGroup=<?= $tokenGroup->getId()?>&prompt=Расценка для <?= ($tokenGroup->getName()) ? $tokenGroup->getName():$tokenGroup->getLemms()?>" class="btn btn-info btn-xs refresh-button"
                                        title="Создать специальную расценку">
                                    <span class="glyphicon glyphicon-plus" ></span>
                                </button> 
                            </div>
                        <?php else:?>
                        <?php endif;?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>    
</div>

<script type="text/javascript">
    $(window).on('load', function() {
        $('.nav-tabs a:first').tab('show');
        $('.editable').editable();
        $('#tokenStatusSelect').change(function () {
            $('#tokenTable').bootstrapTable('refresh');
        });
        $('#bigramStatusSelect').change(function () {
            $('#bigramTable').bootstrapTable('refresh');
        });
    });

    var goodTable = $('#goodTable').bootstrapTable({
        onLoadSuccess: function(res){
            $('#goodBadge').html($('#goodTable').bootstrapTable('getOptions').totalRows)
        }
    });

    var tokenTable = $('#tokenTable').bootstrapTable({
        onLoadSuccess: function(res){
            $('#tokenBadge').html($('#tokenTable').bootstrapTable('getOptions').totalRows)
        }
    });

    var bigramTable = $('#bigramTable').bootstrapTable({
        onLoadSuccess: function(res){
            $('#bigramBadge').html($('#bigramTable').bootstrapTable('getOptions').totalRows)
        }
    });
    
    function tabQueryParams(tab, params) {
        $(tab +'Toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $(tab + ' .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $(tab + ' li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function goodQueryParams(params) {
        return tabQueryParams('#goods', params);
    }

    function tokenQueryParams(params) {
        params.status = $('#tokenStatusSelect').val();
        return tabQueryParams('#tokens', params);
    }

    function bigramQueryParams(params) {
        params.status = $('#bigramStatusSelect').val();
        return tabQueryParams('#bigrams', params);
    }
    
    function responseHandler(res) {
        return res;
    }       
    
    function tokenFormatter(value, row){
        var str = '<div class="pull-left">';
        str += '<a href="/name/view-token/?lemma=' + value + '" target="_blank">' + value + '</a>';
        str += '</div>';

        return str; 
    }    
    
    function bigramFormatter(value, row){
        var str = '<div class="pull-left">';
        str += '<a href="/name/view-bigram/' + row.bigramId + '" target="_blank">' + value + '</a>';
        str += '</div>';
        
        return str; 
    }    
        
    function displayTokenFormatter(value, row){
        if (row.producer){
            return [
                '<a href="#"',
                ' class="editable" data-type="text"',
                ' data-pk="<?= $tokenGroup->getId()?>"',
                ' data-name="'+row.lemma+'"',
                ' data-url="">',
                '</a>',
            ].join(''); 
        }
        
        return;
    } 

    function displayBigramFormatter(value, row){
        if (row.producer){
            return [
                '<a href="#"',
                ' class="editable" data-type="text"',
                ' data-pk="<?= $tokenGroup->getId()?>"',
                ' data-name="'+row.bigramId+'"',
                ' data-url="">',
                '</a>',
            ].join(''); 
        }
        
        return;
    } 
    /**
    * Промпт диалог
    *
    */
    function promptDialog(url, initValue) {
        if (url){            
            var dialog = bootbox.prompt({ 
                size: "medium",
                value: initValue,
                title: 'Наименование группы', 
                callback: function(result){
                    /* result = String containing user input if OK clicked or null if Cancel clicked */
                    if (result != null){
                        $.ajax({
                            type: 'GET',
                            url: url+'?prompt='+result,
                        })
                            .done(function (data) {
                                if (data == 'ok'){
                                    window.location.reload();
                                }    
                            })
                            .fail(function (e) {
                                bootbox.alert("Произошла ошибка при выполнении операции.");
                            });
                    }        
                }
            });
        }        
    }    
</script>