<?php
$this->headTitle($tokenGroup->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Группы наименований'=>$this->url('name', ['action' => 'token-group']),
            $tokenGroup->getName()=>$this->url('name', ['action'=>'view-token-group', 'id'=>$tokenGroup->getId()])
            ]);

$this->headLink()
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js')
            ; 

?>
<h1>
    <?= $this->escapeHtml(($tokenGroup->getName()) ? $tokenGroup->getName():'---'); ?>    
    <button onclick="promptDialog('/name/token-group-name-form/<?= $tokenGroup->getId()?>', '<?= $this->escapeHtml($tokenGroup->getName()); ?>')" 
            class="btn btn-default btn-xs" 
            title="Изменить наименование группы">
        <span class="glyphicon glyphicon-pencil" ></span>
    </button> 

</h1>
<div>
    <?= $tokenGroup->getLemms()?> (<?= $meanFrequency['mean']; ?>)
</div>
<div>
    <?php foreach ($aplGroups as $aplGroup):?>
        <span><?= $aplGroup['groupApl']?></span> 
        <span>(<?= $aplGroup['goodCount']?>)</span>
    <?php endforeach;?>     
</div>
<div class="row">
    <div class="col-md-9">
        <ul class="nav nav-tabs" id="featureTab" role="tablist">
            <li role="presentation"><a href="#goods" role="tab" id="price-tab" data-toggle="tab" aria-controls="price" aria-expanded="true">Товары <span id="goodBadge" class="badge">0</span></a></li>
            <li role="presentation"><a href="#tokens" role="tab" id="home-tab" data-toggle="tab" aria-controls="tokens" aria-expanded="true">Токены <span id="tokenBadge" class="badge">0</span></a></li>
            <li role="presentation"><a href="#bigrams" role="tab" id="oem-tab" data-toggle="tab" aria-controls="bigrams" aria-expanded="true">Биграмы <span id="bigramBadge" class="badge">0</span></a></li>
        </ul>
        <div class="tab-pane fade" role="tabpanel" id="tokens" aria-labelledby="tokens-tab">
            <table id="linkedTable" 
                data-toggle="table" 
                data-url="/name/token-group-token-content/<?= $tokenGroup->getId()?>"
                data-side-pagination="server"
                data-pagination="true" 
                data-page-list="[5, 10, 20, 50]"
                data-toolbar="#tokensToolbar"
                data-show-refresh="true"
                data-show-toggle="true"
                data-query-params="tokenQueryParams"
                data-response-handler="responseHandler"
                >
                <thead>
                    <tr>
                         <th data-field="lemma" data-sortable="true">Токен</th>
                         <th data-field="tokenCount" data-sortable="true">Количество</th>
                     </tr>                
                </thead>
            </table>
        </div>
    </div>    
    <div class="col-md-9">
        <table class="table table-striped">
            <tr>
                <td colspan="2"  style="font-size: x-small">            
                    <?php if ($prev):?>
                        <a href="/name/view-token-group/<?= $prev[0]->getId()?>">&larr;<?= ($prev[0]->getName()) ? $prev[0]->getName():$prev[0]->getLemms() ?></a>
                    <?php endif;?>            
                </td>
                <td  colspan="3" align="right"  style="font-size: x-small">
                    <?php if ($next):?>
                        <a href="/name/view-token-group/<?= $next[0]->getId()?>"><?= ($next[0]->getName()) ? $next[0]->getName():$next[0]->getLemms()?>&rarr;</a>
                    <?php endif;?>                            
                </td>
            </tr>
            <tr>
                <td colspan="5" align="right" valign="center">
                    <b><?= $tokenGroup->getGoodCount()?></b>
                    <button value="/name/update-good-count-token-group/<?= $tokenGroup->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                            title="Обновить количество товара">
                        <span class="glyphicon glyphicon-refresh" ></span>
                    </button> 
                    <button value="/name/token-group-token/<?= $tokenGroup->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                            title="Обновить токены группы">
                        <span class="glyphicon glyphicon-refresh" ></span>
                    </button> 
                </td>
            </tr>            
            <tr>
                <td colspan="5">
                    <?= $this->paginationControl($goods,
                                'Sliding',
                                'application/partial/paginator', 
                                ['route' => array('route' => 'name', 'action' => 'view-token-group', 'id' => $tokenGroup->getId())]); ?>

                </td>
            </tr>
            <?php    foreach ($goods as $good):?>
                <tr>
                    <td colspan="5">
                        <a href="<?= $this->url('goods', ['action' => 'view', 'id' => $good->getId()]);?>">
                            <?= $good->getCode();?> <?= $good->getProducer()->getName();?>
                        </a>   
                        <div>
                            <?php foreach($good->getArticles() as $article):?>
                                <?php foreach ($article->getRawprice() as $rawprice):?>
                                    <?php if ($rawprice->getStatus() == $rawprice::STATUS_PARSED):?>
                                        <span>
                                            <?= $rawprice->getGoodname();?>
                                        </span>
                                    <? endif; ?>        
                                <?php endforeach;?>                            
                            <?php endforeach;?>                            
                        </div>
                    </td>
                </tr>
            <?php endforeach;?>        
            <tr>
                <td colspan="5">
                    <?= $this->paginationControl($goods,
                                'Sliding',
                                'application/partial/paginator', 
                                ['route' => array('route' => 'name', 'action' => 'view-token-group', 'id' => $tokenGroup->getId())]); ?>

                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-3">
        <ul class="list-group">
            <?php if ($tdGroups):?>
                <?php foreach ($tdGroups as $tdGroup):?>
                    <li class="list-group-item <?= ($tdGroupActive == $tdGroup[0]->getId()) ? 'active':''?>">
                        <span class="badge"><?= $tdGroup['goodCount']?></span>
                        <a href='<?= $this->url('name', ['action'=>'view-token-group', 'id'=>$tokenGroup->getId()], ['query' => ['tdGroup' => $tdGroup[0]->getId()]])?>'>
                            <?= $tdGroup[0]->getName()?>
                        </a>                    
                    </li>
                <?php endforeach;?>
            <?php endif;?>        
        </ul>
        <?php if ($this->access('rate.manage')):?>
            <div class="panel panel-info">
                <?php if ($rate):?>
                    <div class="panel-heading">
                        Расценка
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Мин. цена
                        </div>
                        <div class="pull-right">
                            <?= $rate->getMinPrice()?>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                           Макс. цена
                        </div>
                        <div class="pull-right">
                            <?= $rate->getMaxPrice()?>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <a href="<?= $this->url('rate', ['action' => 'view', 'id' => $rate->getId()])?>">
                                <?= $rate->getName()?>
                            </a>
                        </div>
                        <?php if (!$rate->getTokenGroup()):?>
                            <div class="pull-right">
                                <button value="/rate/add/?tokenGroup=<?= $tokenGroup->getId()?>&prompt=Расценка для <?= ($tokenGroup->getName()) ? $tokenGroup->getName():$tokenGroup->getLemms()?>" class="btn btn-info btn-xs refresh-button"
                                        title="Создать специальную расценку">
                                    <span class="glyphicon glyphicon-plus" ></span>
                                </button> 
                            </div>
                        <?php else:?>
                        <?php endif;?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>    
</div>

<script type="text/javascript">
    function tabQueryParams(tab, params) {
        $(tab +'Toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $(tab + ' .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $(tab + ' li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function tokenQueryParams(params) {
        return tabQueryParams('#tokens', params);
    }

    
    
    
    /**
    * Промпт диалог
    *
    */
    function promptDialog(url, initValue) {
        if (url){            
            var dialog = bootbox.prompt({ 
                size: "medium",
                value: initValue,
                title: 'Наименование группы', 
                callback: function(result){
                    /* result = String containing user input if OK clicked or null if Cancel clicked */
                    if (result != null){
                        $.ajax({
                            type: 'GET',
                            url: url+'?prompt='+result,
                        })
                            .done(function (data) {
                                if (data == 'ok'){
                                    window.location.reload();
                                }    
                            })
                            .fail(function (e) {
                                bootbox.alert("Произошла ошибка при выполнении операции.");
                            });
                    }        
                }
            });
        }        
    }    
</script>