<?php
    use Admin\Entity\Log;

    $this->headTitle('Лог записей '.$id);

    $logs = $entityManager->getRepository(Log::class)
            ->logDescription($rows, false);
?>


<?= $this->partial('/admin/log/log-partial.phtml', ['logs' => $logs, 'id' => $id]) ?>        

<?= $this->paginationControl($rows,
            'Sliding',
            'application/partial/paginator', 
            ['route' => ['route' => 'log', 'action' => 'index', 'query' => ['ident' => $ident, 'id' => $id]]]); ?>

