<?php // partial.phtml 
    $qstr = '';
    if (isset($this->ident)){
        $qstr = "?ident={$this->ident}";
        if (isset($this->id)){
            $qstr .= "&id={$this->id}";            
        }
    }
?>
<div class="row">
    <div class="col-xs-12">
        <h4>
            <?php if($qstr):?>
                <a class="btn btn-default btn-xs" href="/log<?= $qstr?>" 
                   title="Все записи в отдельном окне" target="_blank">
                    <span class="glyphicon glyphicon-new-window"></span>
                </a>
            <?php endif;?>
            История изменений <?= $this->id?>:
        </h4>
    </div>
</div>

<?= $this->partialLoop('/admin/log/log-partial-loop.phtml', $this->logs) ?>
