<?php
use Admin\Entity\Setting;

$statuses = Setting::getStatusList();

$this->headTitle('Регламентные процессы');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            ]);

$this->headLink()
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js')
            ; 

?>

<style>
    .modal-body {
        height: 400px;
        overflow-y: scroll;
    }    
</style>


<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
<!--                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>-->
                <select style="width: 200px" class="form-control" id='statusSelect'>
                    <?php foreach ($statuses as $key => $value):?>
                        <option value="<?= $key?>" <?= ($key == Setting::STATUS_ACTIVE) ? 'selected':'' ?>><?= $value?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/log/setting-content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-sortable="true" data-type="numeric">ID</th>
                     <th data-field="lastMod" data-sortable="true">Дата</th>
                     <th data-field="action" data-sortable="true">Процесс</th>
                     <th data-field="name" data-formatter="nameFormatter" data-sortable="true">Наименование</th>
                     <th data-field="status" data-sortable="true" data-formatter="statusFormatter">Статус</th>
                     <th data-field="errCode">Код ошибки</th>
                     <th data-field="errText" data-formatter="errTextFormatter"></th>
                </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav">
    </div>
</div>

<script type="text/javascript">

    $(window).on('load', function() {
        $('.editable').editable();
    });
    
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }
    
    var table = $('#table').bootstrapTable({
        onLoadSuccess: function(res){
            $('.editable').editable();
            $('#show-button').on('click', function(e) {
                var text = e.currentTarget.value;
                if (text){
                    dialog = bootbox.dialog({
                        message: '<div><i class="fa fa-spin fa-spinner"></i>'+text+'</div>',
                        closeButton: true,
                        size: 'large'
                    });
                }        
            })        
            $('.status').editable({
//                value: $('#status').val(),
                source: [
                    <?php foreach ($statuses as $key => $value):?>
                        {value:"<?= $key?>", text:"<?= $value?>"},      
                    <?php endforeach;?>            
                ]
            });  
        }
    });

    var ok = $('#ok');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
        $('#statusSelect').change(function (){
            $('#table').bootstrapTable('refresh');
        })
    });    
    
    function tabQueryParams(tab, params) {
        $(tab +'Toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $(tab + ' .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $(tab + ' li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function queryParams(params) {
        params.status = $('#statusSelect').val();
        return tabQueryParams('#table', params);
    }
    
    function responseHandler(res) {
        return res;
    }       
    
    function statusName(value){
        switch(value){
            <?php foreach ($statuses as $key => $value):?>
                case "<?= $key?>": result="<?= $value?>"; break;      
            <?php endforeach;?>            
            default: result = 'Неизвестно'; break;
        }
        
        return result;
    }    
    
    function statusFormatter(value, row){
        return [
            '<a href="#"',
            ' class="status" data-type="select"',
            ' data-pk="'+row.id+'"',
            ' data-value="'+value+'"',
            ' data-name="status"',
            ' data-url="/log/edit-setting-status">'+statusName(value),
            '</a>',
        ].join(''); 
    }    
    
    function nameFormatter(value, row){
        if (!value){
            value = row.action;
        }
        return [
            '<a href="#"',
            ' class="editable" data-type="text"',
            ' data-pk="'+row.id+'"',
            ' data-name="name"',
            ' data-url="/log/edit-setting-name">'+value,
            '</a>',
        ].join(''); 
        
        return;
    }    
    
    function errTextFormatter(value, row){
        //if (row.errText && row.status == <?= Setting::STATUS_ERROR?>){
            return [
                '<button id="show-button" class="btn btn-default btn-xs"',
                ' title="Описание ошибки" value="'+value+'">',
                ' <span class="glyphicon glyphicon-menu-hamburger" ></span>',
                '</button>',
            ].join(''); 
        //}    
        
        return;
    }    
        
</script>
