<div class="modal-header">
    <h5 class="modal-title" id="ptuModalLabel">Описание ошибки</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<?php
    preg_match_all('/<pre>(.*?)<\/pre>/s', $this->text, $matches);
    var_dump($matches[0]);
?>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
</div>

