<?php
use Admin\Entity\Setting;

$statuses = Setting::getStatusList();

$this->headTitle('Регламентные процессы');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            ]);

?>

<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
<!--                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>-->
                <select style="width: 200px" class="form-control" id='statusSelect'>
                    <?php foreach ($statuses as $key => $value):?>
                        <option value="<?= $key?>" <?= ($key == Setting::STATUS_ACTIVE) ? 'selected':'' ?>><?= $value?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/log/setting-content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-sortable="true" data-type="numeric">ID</th>
                     <th data-field="lastMod" data-sortable="true">Дата</th>
                     <th data-field="action" data-sortable="true">Процесс</th>
                     <th data-field="name" data-formatter="nameFormatter" data-sortable="true">Наименование</th>
                     <th data-field="status" data-sortable="true" data-formatter="statusFormatter">Статус</th>
                     <th data-field="errorCode">Код ошибки</th>
                     <th data-field="errorText" data-formatter="errTextFormatter"></th>
                </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav">
    </div>
</div>

<script type="text/javascript">

    $(window).on('load', function() {
        $('.editable').editable();
    });
    
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }
    
    var table = $('#table').bootstrapTable({
        onLoadSuccess: function(res){
            $('.editable').editable();
            $('.show-button').on('click', function(e) {
                var rowId = e.currentTarget.value;
                if (rowId){
                    $.ajax({
                        type: 'POST',
                        url: '/log/setting-error-text/'+rowId
                    })
                    .done(function (data) {
                        bootbox.alert(data.text);
                    })
                    .fail(function () {
                        bootbox.alert("Произошла ошибка при выполнении операции.");
                    }); 
                }        
            })        
            $('.status').editable({
                source: [
                    <?php foreach ($statuses as $key => $value):?>
                        {value:"<?= $key?>", text:"<?= $value?>"},      
                    <?php endforeach;?>            
                ]
            });  
        }
    });

    var ok = $('#ok');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
        $('#statusSelect').change(function (){
            $('#table').bootstrapTable('refresh');
        })
        $(document).on('click', '.error-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'errorModal',
                url: url,
                width: '1440px'
            });
        });  
    });    
    
    function tabQueryParams(tab, params) {
        $(tab +'Toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $(tab + ' .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $(tab + ' li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function queryParams(params) {
        params.status = $('#statusSelect').val();
        return tabQueryParams('#table', params);
    }
    
    function responseHandler(res) {
        return res;
    }       
    
    function statusName(value){
        switch(value){
            <?php foreach ($statuses as $key => $value):?>
                case "<?= $key?>": result="<?= $value?>"; break;      
            <?php endforeach;?>            
            default: result = 'Неизвестно'; break;
        }
        
        return result;
    }    
    
    function statusFormatter(value, row){
        return [
            '<a href="#"',
            ' class="status" data-type="select"',
            ' data-pk="'+row.id+'"',
            ' data-value="'+value+'"',
            ' data-name="status"',
            ' data-url="/log/edit-setting-status">'+statusName(value),
            '</a>',
        ].join(''); 
    }    
    
    function nameFormatter(value, row){
        if (!value){
            value = row.action;
        }
        return [
            '<a href="#"',
            ' class="editable" data-type="text"',
            ' data-pk="'+row.id+'"',
            ' data-name="name"',
            ' data-url="/log/edit-setting-name">'+value,
            '</a>',
        ].join(''); 
        
        return;
    }    
    
    function errTextFormatter(value, row){
        if (row.errorText && row.status == <?= Setting::STATUS_ERROR?>){
            return [
                '<button class="btn btn-default btn-xs error-modal-show"',
                ' title="Описание ошибки" modal-url="/log/setting-error-text/'+row.id+'">',
                ' <span class="glyphicon glyphicon-menu-hamburger" ></span>',
                '</button>',
            ].join(''); 
        }    
        
        return;
    }    
        
</script>
