<?php
use Admin\Entity\Setting;

$statuses = Setting::getStatusList();

$this->headTitle('Регламентные процессы');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            ]);

$editableSourse = [];
foreach ($statuses as $key => $value){
    $editableSourse[] = '{value:"'.$key.'", text:"'.$value.'"}';      
}     
$sourceString = '['.implode(',', $editableSourse).']';
?>

<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
          <div class="panel-body var-info">
              Метка последовательности: <?= ($variable) ? $variable->getDateVar():'' ?> <?= ($variable) ? $variable->getDoc():''?>; следующий <?= ($register) ? $register->getDateVar():'' ?> <?= ($register) ? $register->getDoc():''?>
          </div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="panel panel-default">
          <div class="panel-body syslog-info">
          </div>
        </div>
    </div>
    <div class="col-md-1">
        <button value="/admin/varact" class="btn btn-warning btn-lg refresh-button"
                title="Восстановление последовательности">ВП
        </button> 
    </div>
</div>    

<div class="row">
    <div class="col-md-12">
        <div id="tableToolbar">
            <div class="form-inline" role="form">
<!--                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>-->
                <select style="width: 200px" class="form-control" id='statusSelect'>
                    <?php foreach ($statuses as $key => $value):?>
                        <option value="<?= $key?>" <?= ($key == Setting::STATUS_ACTIVE_AND_ERROR) ? 'selected':'' ?>><?= $value?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/log/setting-content"
            data-cookie="true"
            data-cookie-id-table="logSettingSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#tableToolbar"
            data-show-refresh="true"
            data-auto-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="rowStyle"
            >
            <thead>
                <tr>
                     <th data-field="id" data-sortable="true" data-type="numeric">ID</th>
                     <th data-field="lastMod" data-sortable="true">Дата</th>
                     <th data-field="action" data-sortable="true">Процесс</th>
                     <th data-field="name" data-formatter="nameFormatter" data-sortable="true">Наименование</th>
                     <th data-field="status" data-sortable="true" data-formatter="statusFormatter">Статус</th>
                     <th data-field="errorCode">Код ошибки</th>
                     <th data-field="errorText" data-formatter="errTextFormatter"></th>
                </tr>                
            </thead>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <p id="error-log"></p>;
    </div>
</div>    
<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    var $editableSource = <?= $sourceString ?>;
    
    var $table = $('#table');

    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status === <?= Setting::STATUS_ERROR?>){
           retired += ' warning';
        }        
        if (row.status === <?= Setting::STATUS_RETIRED?>){
           retired += ' success';
        }        
        return {classes: retired};
    }

    function refreshTable(){
        $table.bootstrapTable('refresh');
    }    
    
    function updateVariable(){
        $.get( "/log/variable/", function( data ) {
            $('.var-info').html('Метка последовательности: '+data.varDate+' '+data.varDoc+'; следующий '+data.actDate+' '+data.actDoc);
        });
    }
    
    function updateSyslog(){
        $.get( "/admin/syslog", function( data ) {
            $('.syslog-info').html('Нагрузка: '+data[0]+' '+data[1]+' '+data[2]);
        });
    }

    function updateErrorLog(){
        $.get( "/log/error-log/", function( data ) {
//            console.log(data);            
            $( ".stripe-line" ).remove();
            $.each(data.rows, function( index, value ) {
                $('#error-log').append('<div class="stripe-line">'+value+'</div>')
            });
        });
    }

    $(function () {        
        $table.bootstrapTable('refreshOptions', {
            onLoadSuccess: function(res){
                updateVariable();
                updateSyslog();
                updateErrorLog();
                $('.editable').editable();
                $('.status').editable({
                    source: $editableSource               
                });  
            }        
        });   

        $('#statusSelect').change(function (){
            refreshTable();
        });
        
        $(document).on('click', '.error-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'errorModal',
                url: url,
                width: '1440px'
            });
        });        
    });    
    
    function tabQueryParams(tab, params) {
        $(tab +'Toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $(tab + ' .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $(tab + ' li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function queryParams(params) {
        params.status = $('#statusSelect').val();
        return tabQueryParams('#table', params);
    }
    
    function responseHandler(res) {
        return res;
    }       
    
    function statusName(value){
        switch(value){
            <?php foreach ($statuses as $key => $value):?>
                case <?= $key?>: result="<?= $value?>"; break;      
            <?php endforeach;?>            
            default: result = 'Неизвестно'; break;
        }
        
        return result;
    }    
    
    function statusFormatter(value, row){
        return [
            '<a href="#"',
            ' class="status" data-type="select"',
            ' data-pk="'+row.id+'"',
            ' data-value="'+value+'"',
            ' data-name="status"',
            ' data-url="/log/edit-setting-status">'+statusName(value),
            '</a>',
        ].join(''); 
    }    
    
    function nameFormatter(value, row){
        if (!value){
            value = row.action;
        }
        return [
            '<a href="#"',
            ' class="editable" data-type="text"',
            ' data-pk="'+row.id+'"',
            ' data-name="name"',
            ' data-url="/log/edit-setting-name">'+value,
            '</a>',
        ].join(''); 
        
        return;
    }    
    
    function errTextFormatter(value, row){
        if (row.errorText){
            return [
                '<button class="btn btn-default btn-xs error-modal-show"',
                ' title="Описание ошибки" modal-url="/log/setting-error-text/'+row.id+'">',
                ' <span class="glyphicon glyphicon-menu-hamburger" ></span>',
                '</button>',
            ].join(''); 
        }    
        
        return;
    }    
        
</script>
