<?php
use Zp\Entity\Personal;
use Laminas\Json\Encoder;

$this->headTitle('Плановые начисления');

$this->mainMenu()->setActiveItemId('zp');
$this->mainMenu()->setActiveUrl($this->url('personal'));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Плановые начисления' => $this->url('personal')
            ]);  

?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <button class="btn btn-default personal-modal-show" type="button" modal-url="/personal/edit-form">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </button>
                </div>    
                <div class="form-group">
                    <select id="companySelect" name="company" style="width: 200px" class="form-control cookie-control">
                        <!--<option selected>все компании</option>-->
                        <?php foreach ($companies as $value):?>
                            <option value="<?= $value->getId()?>"><?= $value->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="userSelect" name="user" style="width: 200px" class="form-control cookie-control">
                        <!--<option selected>все компании</option>-->
                        <option>все сотрудники</option>
                        <?php foreach ($users as $value):?>
                            <option value="<?= $value->getId()?>"><?= $value->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="statusSelect" name="status" style="width: 200px" class="form-control cookie-control">
                        <?php foreach (Personal::getStatusList() as $key => $value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
            </div>
        </div>    
        <table id="table" 
            data-toggle="table" 
            data-url="/personal/content"
            data-side-pagination="server"
            data-pagination="false" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-show-footer="false"
            data-row-style="rowStyle"
            data-classes = "table table-bordered table-hover table-condensed"
            data-sort-name="docDate"
            data-sort-order="desc"  
            data-unique-id="id"
            >
            <thead>
                <tr>
                     <th data-field="id" data-sortable="true" data-align="right" data-width="10">Id</th>
                     <th data-field="docDate" data-sortable="true" data-width="10" data-formatter="dateFormatter">Дата</th>
                     <th data-field="user.fullName">Сотрудник</th>
                     <th data-field="position.name">Должность</th>
                     <th data-field="positionNum" data-sortable="false" data-width="10">Ставка</th>
                     <th data-field="status" data-sortable="false" data-width="10" data-formatter="statusFormatter">Статус</th>
                     <th data-field="comment" data-sortable="false">Комментарий</th>
                     <th data-field="active" data-formatter="activeFormatter" data-width="5"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<?php echo $this->partial('/zp/index/zp-partial', []); ?>

<script type="text/javascript">
    var $table = $('#table');
        $ok = $('#ok');
    
    var curentRowIndex = -1;
    
    function setCurrentIndex(index){
        curentRowIndex = index;
    }
    
    function getCurrentIndex(){
        return curentRowIndex;
    }
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }
    

    $(function () {
        $ok.click(function () {
            refreshTable();
        });
        $table.on('load-success.bs.table', function (e, res) {
        });                
        $(document).on('change', '#companySelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#userSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#statusSelect', function (e) {
            refreshTable();
        });
    });    
    
    function rowStyle(row){
        var retired = 'tablerow';

        if (row.status === '<?= Personal::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        
        return {classes: retired};
    }
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }    
    
    function statusFormatter(value, row){
        var statuses = <?= Encoder::encode(Personal::getStatusList())?>;
        return statuses[value];
    }    
    
    function activeFormatter(value, row){
        var url = '/personal/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs personal-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
        
    function responseHandler(res) {
        return res;
    }    
    
    var menu = new BootstrapMenu('.tablerow', {
        fetchElementData: function(rowElem) {
            setCurrentIndex($(rowElem).attr('data-index'));
            return $table.bootstrapTable('getData')[getCurrentIndex()];
        },
        actionsGroups: [
           ['statusActiv', 'statusRetired'], 
           ['duplicate'],
           ['history']
        ],      
        actions: {
            statusActiv: {
                name: 'Сделать активным',
                iconClass: 'glyphicon glyphicon-ok',
                onClick: function(row) {
                },
                isShown: function(row) {
                },
                isEnabled: function(row) {
                }                
            }, 
            statusRetired: {
                name: 'Сделать не активным',
                iconClass: 'glyphicon glyphicon-remove',
//                classNames: 'bg-danger',
                onClick: function(row) {
                },
                isShown: function(row) {
                },
                isEnabled: function(row) {
                }                
            },
            duplicate: {
                name: 'Скопировать',
                iconClass: 'glyphicon glyphicon-duplicate',
//                classNames: 'bg-danger',
                onClick: function(row) {
                    var url = '/personal/edit-form/'+row.id+'?copy=1';
                    showFormDialog({
                        id: 'ptuModal',
                        url: url,
                        width: '1440px'
                    });
                },
                isShown: function(row) {
                  return true;
                },
                isEnabled: function(row) {
                    return true;
                }                
            }
        }
    });        
    
</script>
