<?php
    use Cash\Entity\CashDoc;

    $this->headTitle('Касса');

    $this->mainMenu()->setActiveItemId('company');
    $this->mainMenu()->setActiveUrl($this->url('till'));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Подотчет'=>$this->url('accountant'),
                'Касса'=>$this->url('till'),
                ]);


?>
<div class="row">
    <div class="col-md-10">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button class="btn btn-default cash-in-modal-show" type="button" modal-url="/till/edit-cash-in">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
                <button class="btn btn-default cash-out-modal-show" type="button" modal-url="/till/edit-cash-out">
                    <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                </button>                
                <div class="form-group">
                    <select id="periodSelect" class="form-control" name="period">
                        <option value="date">Дата</option>
                        <option value="week">Неделя</option>                        
                        <option value="month">Месяц</option>                        
                        <option value="number">Год</option>                        
                    </select>
                    <input name="dateStart" id="dateStart" style="width: 200px" class="form-control refresh-table" type="date" value="<?= date('Y-m-d')?>">
                    <!--<input name="dateEnd" id="dateEnd" style="width: 150px" class="form-control refresh-table" type="date" value="<?= date('Y-m-d')?>">-->
                </div>
                <div class="form-group">
                    <select id="kindSelect" style="width: 200px" class="form-control refresh-table" name="kind">
                        <option>Все операции</option>
                        <?php foreach (CashDoc::getKindList() as $kind=>$value):?>
                            <option value="<?= $kind?>"><?= ($kind>10) ? '-':'+' ?><?= $value?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="tillOfficeSelect" style="width: 100px" class="form-control" name="office">
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>" <?= ($office->getId() == $currentUser->getOffice()->getId()) ? 'selected':'' ?>><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="cashSelect" style="width: 200px" class="form-control refresh-table" name="cash">
                        <option value="0">все</option>
                        <?php foreach ($cashes as $cash):?>
                            <option value="<?= $cash->getId()?>"><?= $cash->getName()?></option>
                        <?php endforeach;?>
                    </select>
                </div>    
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/till/content"
            data-cookie="true"
            data-cookie-id-table="tillSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-undefined-text=''
            data-query-params="queryParams"
            data-sort-name="docStamp"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-row-style="rowStyle"
            data-classes = "table table-bordered table-hover table-condensed"
            data-show-footer="true"
            data-auto-refresh="true"
            >
            <thead>
                <tr>
                     <!--<th data-field="id" data-type="numeric" data-sortable="true" data-align="right">ID</th>-->
                     <th data-field="docStamp" data-sortable="true" data-formatter="dateFormatter" data-width="80">Дата</th>
                     <th data-field="cashDoc.id" data-sortable="false" data-width="50" data-align="right" data-formatter="cashIdFormatter">Номер</th>
                     <th data-field='cashDoc.kind' data-sortable="false" data-formatter="kindFormatter" data-width="200">Операция</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-footer-formatter="footerDebitFormatter" data-formatter="inFormatter" data-width="100">Приход</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-footer-formatter="footerCreditFormatter" data-formatter="outFormatter" data-width="100">Расход</th>
                     <th data-field='cash.name' data-sortable="false" data-width="150">Касса</th>
                     <!--<th data-field="aplId" data-type="numeric"data-align="right">AplId</th>-->
                     <th data-field='cashDoc.kind' data-sortable="false" data-formatter="operFormatter">Кому/от кого</th>
                     <th data-field='cashDoc.comment' data-sortable="false">Комментарий</th>
                     <th data-field='cashDoc.userCreator.fullName' data-sortable="false" data-width="50">Отв.</th>
                     <th data-field="amount" data-formatter="tillActiveFormatter" data-width="50"></th>
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-2" id="side-nav" >
        <!--<div class="nav nav-stacked nav-list affix">-->
            <div id="balancetoolbar">
                <div class="form-inline" role="form">
                    <button value="/till/update-balances/" class="btn btn-default btn-xs refresh-table-button"
                            title="Пересчитать остатки">
                        <span class="glyphicon glyphicon-rub" ></span>
                    </button>                         
                </div>
            </div>
            <table id="balancetable" 
                data-toggle="balancetable" 
                data-url="/till/balances"
                data-side-pagination="server"
                data-pagination="false" 
                data-page-list="[5, 10, 20, 50]"
                data-toolbar="#balancetoolbar"
                data-show-refresh="true"
                data-show-toggle="false"
                data-undefined-text=''
                data-query-params="queryParams"
                data-response-handler="responseHandler"
                data-row-style="balanceRowStyle"
                data-classes = "table table-bordered table-hover table-condensed"
                data-show-footer="true"
                data-auto-refresh="true"
                data-show-refresh="false"
                data-buttons-class='xs'
            >
                <thead>
                    <tr>
                         <th data-field="name" data-footer-formatter="totalFooterFormatter" data-sortable="false">Касса</th>
                         <th data-field="balance" data-footer-formatter="footerFormatter" data-sortable="false" data-align="right" data-formatter="amountFormatter">Остаток</th>
                     </tr>                
                </thead>
            </table>
        
            <table id="userbalancetable" 
                data-toggle="userbalancetable" 
                data-url="/till/user-balances"
                data-side-pagination="client"
                data-pagination="true" 
                data-page-list="[5, 10]"
                data-pagination-parts="['pageList']"
                data-toolbar="#userbalancetoolbar"
                data-show-refresh="true"
                data-show-toggle="false"
                data-undefined-text=''
                data-query-params="queryParams"
                data-response-handler="responseHandler"
                data-row-style="balanceRowStyle"
                data-classes = "table table-bordered table-hover table-condensed"
                data-show-footer="true"
                data-auto-refresh="true"
                data-show-refresh="false"
                data-buttons-class='xs'
            >
                <thead>
                    <tr>
                         <th data-field="name" data-footer-formatter="totalFooterFormatter" data-sortable="false">Подотчет</th>
                         <th data-field="balance" data-footer-formatter="footerFormatter" data-sortable="false" data-align="right" data-formatter="amountFormatter">Остаток</th>
                     </tr>                
                </thead>
            </table>
        <!--</div>-->
    </div>    
</div>    

<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    var $balanceTable = $('#balancetable');
    var $userBalanceTable = $('#userbalancetable');
    var $table = $('#table');
    
    function updateBalance(){
        var current = $.format.date(new Date(), "yyyy-MM-dd");
        $.getJSON( '/till/cash-balance/'+$('#cashSelect').val()+'?dateEnd='+current, function( data ) {
            $('#cashBalance').html((data.balance*100/100).toFixed(2));
        });    
    }
    
    function refreshTable(){
        $table.bootstrapTable('selectPage', 1);
    }

    function officeChange(){
        $.getJSON( '/till/office-cashes/'+$('#tillOfficeSelect').val(), function( data ) {
            $('#cashSelect').empty();
            $('#cashBalance').empty();
            $('#cashSelect').append('<option value="0">все</option>');
            $.each( data.rows, function( key, value ) {
                $('#cashSelect').append('<option value="' + key + '">' + value.name + '</option>');
            });            
            refreshTable();
        });    
    }

    $(function () {   
        $balanceTable.bootstrapTable();
        $userBalanceTable.bootstrapTable();
        //$table.bootstrapTable();

        $('#ok').click(function () {
            refreshTable();
        });        
        $table.on('load-success.bs.table', function (e, res) {
            tableRowClick();        
            var inTotal = (res.inTotal) ? res.inTotal:0;
            var outTotal = (res.outTotal) ? -res.outTotal:0;
//            var endTotal = (res.turnover.endTotal) ? res.turnover.endTotal:0;
            $('#inTotalFooter').html((Math.round(inTotal*100)/100).toFixed(2));
            $('#outTotalFooter').html((Math.round(outTotal*100)/100).toFixed(2));
//            $('#startTotalFooter').html((Math.round((inTotal-outTotal-endTotal)*100)/100).toFixed(2));
        });
        $(document).on('change', '.refresh-table', function (e) {
            refreshTable();
        });
        $(document).on('change', '#tillOfficeSelect', function (e) {
            officeChange();
            $balanceTable.bootstrapTable('refresh');
            $userBalanceTable.bootstrapTable('refresh');
        });
        $(document).on('change', '#cashSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#periodSelect', function (e) {
            $('#dateStart').attr('type', $(this).val());
        });
        $(document).on('click', '.send-cash-doc', function (e) {
            var url = $(this).attr('modal-url');
//            console.log(url);
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: true
            });
            $.get( url, function(data){
//                console.log(data);
//                $table.bootstrapTable('updateByUniqueId', {id: id, row: data.data});
                dialog.modal('hide');
            });
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        return params;
    }
    
    function cashIdFormatter(value, row){
        if (row.cashDoc.aplId){
            return '<nobr>' + value + ' (' + row.cashDoc.aplId + ')</nobr>';
        }
        return value;
    }    
    
    function dateFormatter(value, row){
        var date = new Date(row.dateOper);
        return $.format.date(date, "dd.MM.yyyy");
    }    
    
    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }
    
    function inFormatter(value){
        if (value>0){
            return (Math.round(value*100)/100).toFixed(2);
        }
        return;
    }    
    
    function outFormatter(value){
        if (value<0){
            return (-Math.round(value*100)/100).toFixed(2);
        }
        return;
    }    
    
    function footerDebitFormatter(data){
        return '<span id="inTotalFooter"></span>';
    }

    function footerCreditFormatter(data){
        return '<span id="outTotalFooter"></span>';
    }
    
    function totalFooterFormatter() {
        return 'Всего:';
    }

    function footerFormatter(data){
        var field = this.field;
        return (data.map(function (row) {
            return +row[field];
        }).reduce(function (sum, i) {
            var total = sum + i;
            return (Math.round((total)*100)/100);
        }, 0)).toFixed(2);
    }
    
    function kindFormatter(value){
        var kinds = <?= CashDoc::getKindListAsJavascriptArray() ?>;
        return kinds[value];
    }    
    
    function operFormatter(value, row){
        var cashRefill = null;
        var cashName = null;
        switch(value){
            case '<?= CashDoc::KIND_IN_PAYMENT_CLIENT ?>': 
            case '<?= CashDoc::KIND_OUT_RETURN_CLIENT ?>': 
                        var orderId = (row.cashDoc.order) ? "<a href='#' class='order-view-show' modal-url='/order/view/"+row.cashDoc.order.id+"'>Заказ №"+row.cashDoc.order.aplId+"</a>":'Пополнение ЛС';
                        var contactName = '<span class="text-warning">!Контакт не указан!</span>';
                        if (row.cashDoc.contact){
                            var contactName = (row.cashDoc.contact.client) ? "<a href='/client/view/"+row.cashDoc.contact.client.id+"' target=_blank>"+row.cashDoc.contact.client.name+"</a>":'NaN';
                        }    
                        return contactName+' '+orderId;
            case '<?= CashDoc::KIND_IN_REFILL ?>': 
                        cashRefill = (row.cashDoc.cashRefill) ? row.cashDoc.cashRefill.name:row.cashDoc.userRefill.fullName;
                        cashName = (row.cashDoc.cash) ? row.cashDoc.cash.name:'<span class="text-warning">!Касса не указана!</span>';
                        return (row.amount < 0) ? cashName:cashRefill;
            case '<?= CashDoc::KIND_OUT_REFILL ?>': 
                        cashRefill = (row.cashDoc.cashRefill) ? row.cashDoc.cashRefill.name:row.cashDoc.userRefill.fullName;
                        cashName = (row.cashDoc.cash) ? row.cashDoc.cash.name:'<span class="text-warning">!Касса не указана!</span>';
                        return (row.amount > 0) ? cashName:cashRefill;
            case '<?= CashDoc::KIND_IN_RETURN_USER ?>': 
            case '<?= CashDoc::KIND_OUT_COURIER ?>': 
            case '<?= CashDoc::KIND_OUT_SALARY ?>': 
            case '<?= CashDoc::KIND_OUT_USER ?>': 
                        return (row.cashDoc.userRefill) ? row.cashDoc.userRefill.fullName:null;
            case '<?= CashDoc::KIND_OUT_COST ?>': 
                        return row.cashDoc.cost.name;
            case '<?= CashDoc::KIND_IN_RETURN_SUPPLIER ?>': 
            case '<?= CashDoc::KIND_OUT_SUPPLIER ?>': 
                if (row.cashDoc.legal){
                    return row.cashDoc.legal.name;
                }                
                return '<span class="text-warning">!Поставщик не указан!</span>';
        }
        return;
    }    
    
    function tillActiveFormatter(value, row){
        var btn = '<nobr>';
        if (row.cashDoc.cash && row.statusEx != <?= CashDoc::STATUS_EX_RECD?>){
            if (row.cashDoc.kind<10){
                var url = '/till/edit-cash-in/'+row.cashDoc.id;
                btn += '<button';
                btn += ' type="button"';
                btn += ' class="btn btn-default btn-xs cash-in-modal-show"';
                btn += ' aria-label="Left Align"'; 
                btn += ' modal-url="'+url+'">';
                btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
                btn += '</button>';
            }    
            if (row.cashDoc.kind>10){
                var url = '/till/edit-cash-out/'+row.cashDoc.id;
                btn += '<button';
                btn += ' type="button"';
                btn += ' class="btn btn-default btn-xs cash-out-modal-show"';
                btn += ' aria-label="Left Align"'; 
                btn += ' modal-url="'+url+'">';
                btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
                btn += '</button>';
            }    
            
            var url = '/apl/send-cash-doc/'+row.cashDoc.id;
            btn += ' <button';
            btn += ' type="button"';
            btn += ' class="btn btn-info btn-xs send-cash-doc"';
            btn += ' aria-label="Left Align"'; 
            btn += ' modal-url="'+url+'">';
            btn += '<span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>';
            btn += '</button>';
        }    
        btn += '</nobr>';
        return btn;
    }    
    
    function rowStyle(row, index) {
        var retired = 'tablerow';
        if (row.cashDoc){
            if (row.cashDoc.status == '<?= CashDoc::STATUS_RETIRED?>'){
               retired += ' retired';
            }        
            if (row.cashDoc.status == '<?= CashDoc::STATUS_CORRECT?>'){
               retired += ' retired-muted';
            }        
        }    
        return {classes: retired};    
    }
    
    function responseHandler(res) {
        return res;
    }    
</script>

