<?php
    $this->headTitle('Проверка АПИ поставщиков');
    $this->mainMenu()->setActiveItemId('sapi');
    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Проверка АПИ поставщиков'=>$this->url('sapi'),
                ]);
    
?>    
<strong>Module:</strong>        Application &raquo;
<strong>Controller:</strong>    Sapi &raquo;
<strong>Action:</strong>        index

