<?php
use Stock\Entity\Revise;

$form = $this->form;

$form->get('docDate')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('amount')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('phone')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'8 (000) 000-0000',
    'aria-describedby' => "basic-addon2",
    ]);

$form->get('office')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('company')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('supplier')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('legal')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('contract')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'cash-submit']);

$form->prepare();

?>
<?= $this->form()->openTag($form); ?>

<div class="modal-header">
    <h5 class="modal-title" id="reviseModalLabel">Корректировка долга</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <div class="row">
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('docDate')); ?>
                <?= $this->formElement($form->get('docDate')); ?>
                <?= $this->formElementErrors($form->get('docDate')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('amount')); ?>
                <?= $this->formElement($form->get('amount')); ?>
                <?= $this->formElementErrors($form->get('amount')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('office')); ?>
                <?= $this->formElement($form->get('office')); ?>
                <?= $this->formElementErrors($form->get('office')); ?>                  
            </div>
        </div>
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('company')); ?>
                <?= $this->formElement($form->get('company')); ?>
                <?= $this->formElementErrors($form->get('company')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>                  
            </div>
        </div>    
    </div>
    <div class="row" id="supplierRevise">
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('supplier')); ?>
                <?= $this->formElement($form->get('supplier')); ?>
                <?= $this->formElementErrors($form->get('supplier')); ?>                  
            </div>
        </div>    
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('legal')); ?>
                <?= $this->formElement($form->get('legal')); ?>
                <?= $this->formElementErrors($form->get('legal')); ?>                  
            </div>
        </div>    
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('contract')); ?>
                <?= $this->formElement($form->get('contract')); ?>
                <?= $this->formElementErrors($form->get('contract')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row" id="clientRevise">
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('phone')); ?>
                <span id="contactName"><?= $contactName?></span>
                <?= $this->formElement($form->get('phone')); ?>
                <?= $this->formElementErrors($form->get('phone')); ?>                  
            </div>
        </div>    
        <div class="col-xs-3">                        
            <div class="form-group">
            </div>
        </div>    
    </div>    
    <div class="row">    
        <div class="col-xs-12">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('comment')); ?>
                <?= $this->formElement($form->get('comment')); ?>
                <?= $this->formElementErrors($form->get('comment')); ?>                  
            </div>
        </div>    
    </div>    
</div>    

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary" id="revise-submit">Сохранить</button>
</div>
<?= $this->form()->closeTag(); ?>
            
<script>         
    $('#phone').mask('8 (000) 000-0000', {selectOnFocus: false});
    
    function submitForm(){
        var data = serializeForm('#revise-form');
         $('#revise-submit').prop('disabled', true);
        //console.log(data);
        $.ajax({
            type: 'POST',
            url: '/revise/edit-form/<?= ($revise) ? $revise->getId():"" ?>?kind=<?= $kind?>',
            data: $.param(data)
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#reviseModal').modal('hide');
                    $('#table').bootstrapTable('refresh');
                } else {
                    $('#reviseModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };
    
    function showGroup()
    {
        $('#supplierRevise').hide();
        $('#clientRevise').hide();
        $('#phone').attr('required', false);
        $('#supplier').attr('required', false);
        $('#legal').attr('required', false);
        $('#contract').attr('required', false);
        <?php if ($kind == Revise::KIND_REVISE_SUPPLIER): ?>
            $('#supplierRevise').show();
            $('#supplier').attr('required', true);
            $('#legal').attr('required', true);
            $('#contract').attr('required', true);
        <?php endif; ?>
        <?php if ($kind == Revise::KIND_REVISE_CLIENT): ?>
            $('#clientRevise').show();
            $('#phone').attr('required', true);
        <?php endif; ?>        
    }
    
    function contactName(){
        if ($('#phone').val()){
            $.getJSON( '/till/phone-contact?phone='+$('#phone').val(), function( data ) {
                $('#contactName').html(data.name);

            });            
        }    
    }    
    
    function contractList(){
        //alert(11);
        $.getJSON( '/contracts/select/?company='+$('#company').val()+'&legal='+$('#legal').val(), function( data ) {
            $('#contract').empty();
            $.each( data.rows, function( key, value ) {
                $('#contract').append('<option value="' + key + '">' + value.name + '</option>');
            });
        });    
    }
    
    $('#office').on('change', function(){
        $.getJSON( '/offices/legals/'+$('#office').val(), function( data ) {
            $('#company').empty();
            $.each( data.rows, function( key, value ) {
                $('#company').append('<option value="' + key + '">' + value.name + '</option>');
            });
            contractList();
        });    
    });
    
    $('#company').on('change', function(){
        contractList();
    });    
    
    $('#supplier').on('change', function(){
        $.getJSON( '/supplier/legals/'+$('#supplier').val(), function( data ) {
            $('#legal').empty();
            $.each( data.rows, function( key, value ) {
                $('#legal').append('<option value="' + key + '">' + value.name + '</option>');
            });
            contractList();            
        });    
    });
    
    $('#legal').on('change', function(){
        contractList();
    });
    
    $('#phone').on('change', function(){
        contactName();
    });

$( document ).ready(function() {
                
        showGroup();
        
        var forms = $('#revise-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('revise-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });
    });            
</script>