<?php
    use Stock\Entity\Revise;
    
    $this->headTitle('Корректировка долга');    

    $this->mainMenu()->setActiveItemId('raw');
    if ($kind == Revise::KIND_REVISE_CLIENT){
        $this->mainMenu()->setActiveItemId('client');
    }

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Корректировка долга'=>$this->url('revise', ['action' => 'index'], ['query' => ['kind' => $kind]]),
                ]);
?>


<h1>Корректировка долга</h1>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button class="btn btn-default revise-modal-show" type="button" modal-url="/revise/edit-form?kind=<?= $kind?>">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
                <?php if ($kind == Revise::KIND_REVISE_CLIENT):?>
                    <div class="form-group">
                        <input name="search" style="width: 150px" class="form-control" type="text" placeholder="Поиск">
                        <button id="ok" type="submit" class="btn btn-default">OK</button>
                    </div>
                <?php endif; ?>                
                <?php if ($kind == Revise::KIND_REVISE_SUPPLIER):?>
                    <div class="form-group">
                        <select id="supplierSelect" style="width: 250px" class="form-control">
                            <option selected>поставщик</option>
                            <?php foreach ($suppliers as $supplier):?>
                                <option value="<?= $supplier->getId()?>"><?= $supplier->getName()?></option>
                            <?php endforeach;?>
                        </select>

                    </div>    
                <?php endif; ?>
                <div class="form-group">
                    <select id="officeSelect" style="width: 100px" class="form-control">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <select id="yearSelect" style="width: 80px" class="form-control">
                        <option>год</option>
                        <?php foreach ($years as $year):?>
                            <option value="<?= $year?>" <?= ($year == date('Y'))? 'selected':''?>><?= $year?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="monthSelect" style="width: 70px" class="form-control">
                        <option>мес</option>
                        <?php foreach ($monthes as $month):?>
                            <option value="<?= $month?>" <?= ($month == date('m'))? 'selected':''?>><?= $month?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/revise/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true" data-align="right">ID</th>
                     <th data-field="aplId" data-type="numeric"data-align="right">AplId</th>
                     <th data-field="docDate" data-sortable="true">Дата</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-formatter="amountFormatter">Сумма</th>
                     <?php if ($kind == Revise::KIND_REVISE_SUPPLIER):?>
                        <th data-field='legal.name' data-sortable="false">Поставщик</th>
                        <th data-field='contract.name' data-sortable="false">Договор</th>
                     <?php endif;?>   
                     <?php if ($kind == Revise::KIND_REVISE_CLIENT):?>
                        <th data-field='contact.name' data-sortable="false">Покупатель</th>
                     <?php endif;?>   
                     <th data-field='office.name' data-sortable="false">Офис</th>
                     <th data-field='comment' data-sortable="false">Примечание</th>
                     <th data-field='status' data-sortable="false">П</th>
                     <th data-field='statusDoc' data-sortable="false">Т</th>
                     <th data-field='statusEx' data-sortable="false">О</th>
                     <th data-field="" data-formatter="activeFormatter"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table'),
        ok = $('#ok');
    
    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
        $(document).on('click', '.revise-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'reviseModal',
                url: url,
                width: '1440px'
            });
        });  
        
        $(document).on('change', '#supplierSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#officeSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#yearSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#monthSelect', function (e) {
            refreshTable();
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.supplier = $('#supplierSelect').val();
        params.office = $('#officeSelect').val();
        params.year = $('#yearSelect').val();
        params.month = $('#monthSelect').val();
        params.kind = <?= $kind?>
        
        return params;
    }
    
    function amountFormatter(value){
        return Math.round(value*100)/100;
    }    
    
    function activeFormatter(value, row){
        var url = '/revise/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs revise-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>

