<?php
    use Cash\Entity\CashDoc;

    $this->headTitle('Касса');

    $this->mainMenu()->setActiveItemId('company');

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Касса'=>$this->url('till'),
                'Подотчет'=>$this->url('accountant'),
                ]);


?>
<style>
    .retired {
        text-decoration: line-through;
    }
</style>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button class="btn btn-default user-in-modal-show" type="button" modal-url="/accountant/edit-user-in">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
                <button class="btn btn-default user-out-modal-show" type="button" modal-url="/accountant/edit-user-out">
                    <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                </button>                
                <div class="form-group">
                    <input name="dateOper" id="dateOper" style="width: 150px" class="form-control refresh-table" type="date" value="<?= date('Y-m-d')?>">
                </div>
                <div class="form-group">
                    <select id="kindSelect" style="width: 200px" class="form-control refresh-table" name="cashId">
                        <option>Все операции</option>
                        <?php foreach (CashDoc::getKindList() as $kind=>$value):?>
                            <option value="<?= $kind?>"><?= ($kind>10) ? '-':'+' ?><?= $value?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="officeSelect" style="width: 100px" class="form-control" name="officeId">
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="userSelect" style="width: 200px" class="form-control refresh-table" name="cashId">
                        <?php foreach ($users as $user):?>
                            <option value="<?= $user->getId()?>"><?= $user->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    <label for="userSelect" id="userBalance">0</label>
                </div>    
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/accountant/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-row-style="rowStyle"
            >
            <thead>
                <tr>
                     <!--<th data-field="id" data-type="numeric" data-sortable="true" data-align="right">ID</th>-->
                     <th data-field="dateCreated" data-sortable="false" data-width="150">Дата</th>
                     <th data-field="cashDoc.id" data-sortable="false" data-width="50" data-align="right">Номер</th>
                     <!--<th data-field="aplId" data-type="numeric"data-align="right">AplId</th>-->
                     <th data-field='cashDoc.kind' data-sortable="false" data-formatter="kindFormatter" data-width="200">Операция</th>
                     <th data-field='cashDoc.kind' data-sortable="false" data-formatter="operFormatter" data-width="200">Кому/от кого</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-formatter="inFormatter" data-width="100">Приход</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-formatter="outFormatter" data-width="100">Расход</th>
                     <th data-field='cashDoc.comment' data-sortable="false">Комментарий</th>
                     <!--<th data-field='status' data-sortable="false"></th>-->
                     <th data-field='cashDoc.userCreator.fullName' data-sortable="false" data-width="50">Отв.</th>
                     <th data-field="amount" data-formatter="activeFormatter" data-width="50"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    var table = $('#table').bootstrapTable({
        onLoadSuccess: function() {
            updateBalance();
        }, 
    });
    
    function updateBalance(){
        $.getJSON( '/accountant/user-balance/'+$('#userSelect').val()+'?dateOper='+$('#dateOper').val(), function( data ) {
            $('#userBalance').html((data.balance*100/100).toFixed(2));
        });    
    }
    
    function refreshTable(){
        table.bootstrapTable('refresh');
    }

    function officeChange(){
        $.getJSON( '/accountant/office-cashes/'+$('#officeSelect').val(), function( data ) {
            $('#userSelect').empty();
            $('#userBalance').empty()
            $.each( data.rows, function( key, value ) {
                $('#userSelect').append('<option value="' + key + '">' + value.name + '</option>');
            });            
            refreshTable();
        });    
    }

    $(function () {
        $('#ok').click(function () {
            refreshTable()
        });
        $(document).on('click', '.user-in-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'userInModal',
                url: url,
                width: '1440px'
            });
        });  
        $(document).on('click', '.user-out-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'userOutModal',
                url: url,
                width: '1440px'
            });
        });  
        $(document).on('change', '.refresh-table', function (e) {
            refreshTable();
        });
        $(document).on('change', '#officeSelect', function (e) {
            officeChange();
        });
        $(document).on('change', '#cashSelect', function (e) {
            table.bootstrapTable('selectPage', 1);
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.office = $('#officeSelect').val();
        params.user = $('#userSelect').val();
        params.kind = $('#kindSelect').val();
        return params;
    }
    
    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function amountFormatter(value){
        return Math.round(value*100)/100;
    }
    
    function inFormatter(value){
        if (value>0){
            return Math.round(value*100)/100;
        }
        return;
    }    
    
    function outFormatter(value){
        if (value<0){
            return -Math.round(value*100)/100;
        }
        return;
    }    
    
    function kindFormatter(value){
        var kinds = <?= CashDoc::getKindListAsJavascriptArray() ?>;
        return kinds[value];
    }    
    
    function operFormatter(value, row){
        var cashName = (row.cashDoc.cash) ? row.cashDoc.cash.name:row.cashDoc.user.fullName;
        switch(value){
            case '<?= CashDoc::KIND_IN_REFILL ?>': 
                        return (row.amount < 0) ? cashName:row.cashDoc.cashRefill.name;
            case '<?= CashDoc::KIND_OUT_REFILL ?>': 
                        return (row.amount > 0) ? cashName:row.cashDoc.cashRefill.name;
            case '<?= CashDoc::KIND_IN_RETURN_USER ?>':
                    if (row.cashDoc.cash){
                        return row.cashDoc.cash.name;
                    }    
            case '<?= CashDoc::KIND_OUT_COURIER ?>': 
            case '<?= CashDoc::KIND_OUT_SALARY ?>': 
            case '<?= CashDoc::KIND_OUT_USER ?>': 
                        return (row.cashDoc.userRefill) ? row.cashDoc.userRefill.fullName:null;
            case '<?= CashDoc::KIND_OUT_COST ?>': 
                        return row.cashDoc.cost.name;
            case '<?= CashDoc::KIND_IN_RETURN_SUPPLIER ?>': 
            case '<?= CashDoc::KIND_OUT_SUPPLIER ?>': 
                        return row.cashDoc.legal.name;
        }
        return;
    }    
    
    function activeFormatter(value, row){
        var btn = '';
        if (row.cashDoc.user){
            if (row.cashDoc.kind<10){
                var url = '/accountant/edit-user-in/'+row.cashDoc.id;
                btn = '<button';
                btn += ' type="button"';
                btn += ' class="btn btn-default btn-xs user-in-modal-show"';
                btn += ' aria-label="Left Align"'; 
                btn += ' modal-url="'+url+'">';
                btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
                btn += '</button>';
            }    
            if (row.cashDoc.kind>10){
                var url = '/accountant/edit-user-out/'+row.cashDoc.id;
                btn = '<button';
                btn += ' type="button"';
                btn += ' class="btn btn-default btn-xs user-out-modal-show"';
                btn += ' aria-label="Left Align"'; 
                btn += ' modal-url="'+url+'">';
                btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
                btn += '</button>';
            }    
        }    
        return btn;
    }    
    
    function rowStyle(row, index) {
        if (row.cashDoc.status == <?= CashDoc::STATUS_RETIRED?>) {
            return {               
                classes: 'retired'
            }   
        }
        return {
          css: {
//            color: 'blue'
          }
        }   
    }
    
    function responseHandler(res) {
        return res;
    }    
</script>

