<?php
use Application\Entity\Cross;

$this->headTitle('Кроссы');

$this->mainMenu()->setActiveItemId('raw');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Кроссы'=>$this->url('cross', ['action' => 'index'])
            ]);  

?>

<div class="row">
    <div class="col-md-9">
        <div class="panel-group">
            <?php if (count($files)): ?>
                <?php foreach($files as $fileInfo):?>
                    <?php if (file_exists($fileInfo->getPathname())):?>
                        <div class="caption panel-body small">
                            <div class="pull-left">
                                <?= $fileInfo->getFileName() ?>
                            </div>
                            <div class="pull-right">
                                <button value="/cross/upload-tmp-file/?file=<?= rawurlencode($fileInfo->getPathname()) ?>" class="btn btn-default btn-xs refresh-button"
                                        title="Загрузить">
                                    <span class="glyphicon glyphicon-import" ></span>
                                </button>
                                <?php if ($crossManager->isCompressFile($fileInfo->getPathName())): ?>
                                    <button value="/cross/decompress-tmp-file/?file=<?= rawurlencode($fileInfo->getPathname()) ?>" class="btn btn-default btn-xs refresh-button"
                                            title="Распаковать">
                                        <span class="glyphicon glyphicon-compressed" ></span>
                                    </button>                             
                                <?php endif;?>
                                <button value="/cross/delete-tmp-file/?file=<?= rawurlencode($fileInfo->getPathname()) ?>" class="btn btn-warning btn-xs this-delete"
                                        title="Удалить">
                                    <span class="glyphicon glyphicon-remove" ></span>
                                </button>                             
                            </div>                                                                            
                        </div>                    
                    <?php endif;?>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select id="statusSelect" style="width: 200px" class="form-control refresh-table cookie-control" name="status">
                        <option>все</option>
                        <?php foreach (Cross::getStatusList() as $key=>$value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                    </select>
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/cross/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-cookie="true"
            data-cookie-id-table="crossSaveId"
            data-cookie-expire="1m"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-auto-refresh ="true"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric">ID</th>
                     <th data-field="supplier" data-formatter="supplierFormatter">Поставщик</th>
                     <th data-field="filename"  data-formatter="filenameFormatter">Файл</th>
                     <th data-field="rowCount">Строк</th>
                     <th data-field="status" data-formatter="statusFormatter">Состояние</th>
                     <th data-field="dateCreated" data-formatter="dateCreatedFormatter">Дата</th>
                     <th data-field="" data-formatter="activeFormatter"></th>
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Загрузить
                    </div>
                    <div class="panel-body">
                        <button value="/cross/check-mail" class="btn btn-default btn-xs refresh-button"
                                title="Проверить ящик для кроссов">
                            <span class="glyphicon glyphicon-envelope" ></span>
                        </button>                             
<!--                        <button value="/cross/upload-tmp-cross-form" class="btn btn-default btn-xs"
                                data-toggle="modal" data-target="#modal-dialog" title="Загрузить файл">
                            <span class="glyphicon glyphicon-export" ></span>
                        </button>                            
                        <button value="/cross/upload-tmp-files" class="btn btn-default btn-xs refresh-button"
                                title="Добавить кроссы к товарам">
                            <span class="glyphicon glyphicon-import" ></span>
                        </button>                             -->
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');

    function refreshTable(){
//        $table.bootstrapTable('selectPage', 1);
        $table.bootstrapTable('refresh');
    }

    $(function () {
        $ok.click(function () {
            refreshTable();
        });

        $(document).on('change', '.refresh-table', function (e) {
            refreshTable();
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.status = $('#statusSelect').val();
        return params;
    }
    
    function activeFormatter(value, row){
        var url = '/cross/delete-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }
    
    function supplierFormatter(value) {
        if (value){
            return '<a href="/supplier/view/'+value.id+'">'+value.name+'</a>';
        }
        return;
    }
    
    function filenameFormatter(value, row) {
        return '<a href="/cross/view/'+row.id+'" target="_blank">'+value+'</a>';
    }
    
    function statusFormatter(value, row) {
        switch (value){
            case 2: return 'Удален'; 
            case 3: return 'Разобран'; 
            case 4: return 'Загружается'; 
            case 5: return 'Разбирается'; 
            case 6: return 'Не удалось загрузить<br/><small style="color:red">'+row.name+'</small>'; 
            case 7: return 'Устарел'; 
            case 8: return 'Исследован'; 
            case 9: return 'Привязан'; 
            default: return 'Новый';    
        }
    }
    
    function statusStageFormatter(value, row) {
        var status = statusFormatter(value, row);
        var stage = '';
        if (value === 3){
            switch (row.parseStage){
                case 1: stage = '<br/> Производители не разобраны'; break;
                case 2: stage =  '<br/> Производители разобраны'; break;
                case 3: stage =  '<br/> Артикулы разобраны'; break;
                case 4: stage =  '<br/> Номера разобраны'; break;
                case 5: stage =  '<br/> Наименования разобраны'; break;
                case 6: stage =  '<br/> Производители собраны'; break;
                case 7: stage =  '<br/> Товары собраны'; break;
                case 8: stage =  '<br/> Цены пересчитаны'; break;
                case 10: stage =  '<br/> Группы наименований разобраны'; break;
                default: stage =  '<br/> Неизвестно';                  
            }
        }    
        return status+stage;
    }
    
    function dateCreatedFormatter(value, row) {
        return value;
    }    
    
    
    function responseHandler(res) {
        return res;
    }
</script>
