<?php
$this->headTitle('Кросс '.$cross->getBasename());

$this->mainMenu()->setActiveItemId('raw');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Кроссы'=>$this->url('cross'),
            $cross->getBasename() => $this->url('cross', ['action'=>'view', 'id' => $cross->getId()])
            ]);  

$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    

?>

<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Данные из файла</h3>
            </div>
        </div> 
        <table id="table" 
            data-toggle="table" 
            data-url="/cross/list-content/<?= $cross->getId()?>"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric">ID</th>
                     <th data-field="rawdata">Данные</th>
                     <th data-field="" data-formatter="activeFormatter"></th>
                 </tr>                
            </thead>
        </table>
    </div>    
    <div class="col-md-3" id="side-nav">
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12">
                            </div>    
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="pull-left">
                                    <?= $this->escapeHtml($cross->getBasename()); ?>
                                    <br/>
                                    <?= $this->escapeHtml($cross->getStatusAsString()); ?>
                                </div>    
                            </div>
                        </div>    
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="pull-left">
                                    <button value="/cross/explore/<?= $cross->getId()?>" class="btn btn-default btn-xs refresh-button"
                                            title="Исследовать">
                                        <span class="glyphicon glyphicon-education"></span>
                                    </button>                             
                                </div>    
                            </div>    
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <?php if (is_array($cross->getDescription())): ?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12">
                                    <table>
                                        <?php foreach($cross->getDescription() as $key => $value):?>
                                            <tr>
                                                <td>
                                                    <?= $key?>
                                                </td>
                                                <td align="right">
                                                    <?= $value?>
                                                </td>
                                            </tr>
                                        <?php endforeach;?>                                        
                                    </table>
                                </div>    
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>    
</div>    

<script type="text/javascript">
    var table = $('#table'),
        ok = $('#ok');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
    });
    
    function queryParams() {
        var params = {offset: 0, limit: 10};
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        return params;
    }
    function responseHandler(res) {
        return res;
    }
    
    function activeFormatter(value, row){
        var url = '/cross/delete-line/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }
    
    function supplierFormatter(value) {
        if (value){
            return '<a href="/supplier/view/'+value.id+'">'+value.name+'</a>';
        }
        return;
    }
    
    function filenameFormatter(value, row) {
        return '<a href="/cross/view/'+row.id+'">'+value+'</a>';
    }
    
    function statusFormatter(value, row) {
        switch (value){
            case '2': return 'Удален'; 
            case '3': return 'Разобран'; 
            case '4': return 'Загружается'; 
            case '5': return 'Разбирается'; 
            case '6': return 'Не удалось загрузить<br/><small style="color:red">'+row.name+'</small>'; 
            case '7': return 'Устарел'; 
            default: return 'Новый';    
        }
    }
    function statusStageFormatter(value, row) {
        var status = statusFormatter(value, row);
        var stage = '';
        if (value == '3'){
            switch (row.parseStage){
                case '1': stage = '<br/> Производители не разобраны'; break;
                case '2': stage =  '<br/> Производители разобраны'; break;
                case '3': stage =  '<br/> Артикулы разобраны'; break;
                case '4': stage =  '<br/> Номера разобраны'; break;
                case '5': stage =  '<br/> Наименования разобраны'; break;
                case '6': stage =  '<br/> Производители собраны'; break;
                case '7': stage =  '<br/> Товары собраны'; break;
                case '8': stage =  '<br/> Цены пересчитаны'; break;
                case '10': stage =  '<br/> Группы наименований разобраны'; break;
                default: stage =  '<br/> Неизвестно';                  
            }
        }    
        return status+stage;
    }
    
    function dateCreatedFormatter(value, row) {
        return value;
    }    
    
</script>
