<?php
$this->headTitle('Статьи');

$this->mainMenu()->setActiveItemId('cost');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Статьи'=>$this->url('cost'),
            ]);
?>

<h1>Статьи затрат</h1>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
<a class="btn btn-default" href="
    <?= $this->url('cost', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Новая статья
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Апл Id</th>
        <th>Наименование</th>
        <th>Статус</th>
        <th>Действие</th>        
    </tr>
    
    <?php foreach ($costs as $cost): ?>
    
    <tr>
        <td><?= $this->escapeHtml($cost->getId()); ?></td>
        <td><?= $this->escapeHtml($cost->getAplId()); ?>
        </td>
        <td>
            <a href="<?= $this->url('cost', ['action'=>'view', 'id'=>$cost->getId()]); ?>">
                <?= $this->escapeHtml($cost->getName()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($cost->getStatusAsString()); ?> 
        </td>
        <td>
            </nobr>
            <a class="btn btn-info" href="<?= $this->url('cost', 
                    ['action'=>'edit', 'id'=>$cost->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Изменить
            </a>
            <a class="btn btn-danger" href="<?= $this->url('cost',
                    ['action'=>'delete', 'id'=>$cost->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Удалить
            </a>
            </nobr>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>




