<?php
$this->headTitle('Регион');

$this->mainMenu()->setActiveItemId('regions');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Регионы'=>$this->url('regions'),
            'Регион'=>$this->url('regions', ['action'=>'view', 'id'=>$region->getId()])
            ]);
?>


<h1>Регион</h1>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
<a class="btn btn-default" href="<?= $this->url('regions', 
                    ['action'=>'edit', 'id'=>$region->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Изменить
</a>
</p>
    
<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($region->getId()) ?></th>
            </tr>
            <tr>
                <th>Сокращение:</th>
                <td><?= $this->escapeHtml($region->getName()) ?></th>
            </tr>
            <tr>
                <th>Полное наименование:</th>
                <td><?= $this->escapeHtml($region->getFullName()) ?></th>
            </tr>
        </table>
    </div>
</div>