<?php
$this->headTitle('Торговые площадки');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Администрирование'=>$this->url('admin'),
            'Торговые площадки' => $this->url('market-place')
            ]);  

?>
<p>
    <button class="btn btn-default marketplace-modal-show" type="button" modal-url="/market-place/edit-form">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"> Добавить</span>
    </button>                
    <button class="btn btn-default btn-default marketplace-realization" type="button" modal-url="/market-place/realization-reports/">
        <span class="glyphicon glyphicon-list" ></span> Загрузить отчеты
    </button>
</p>

<table class="table table-striped">

   <tr>
        <th>Id</th>
        <th>Наименование</th>
        <th>ID Личного кабинета</th>  
        <th>Клиент</th>  
        <th>Договор</th>  
        <th>Тип</th>  
        <th>Статус</th>  
        <th></th>
    </tr>
    
    <?php foreach ($marketplaces as $marketplace): ?>    
        <tr>
            <td><?= $this->escapeHtml($marketplace->getId()); ?></td>
            <td>
                <?= $marketplace->getTagName(); ?>
            </td>
            <td>
                <?= $this->escapeHtml($marketplace->getMerchantId()); ?>
            </td>
            <td>
                <?= $marketplace->getContactPresent(); ?>
            </td>
            <td>
                <?= $marketplace->getContractPresent(); ?>
            </td>
            <td>
                <?= $this->escapeHtml($marketplace->getMarketTypeAsString()); ?>
            </td>
            <td>
                <?= $this->escapeHtml($marketplace->getStatusAsString()); ?>
            </td>
            <td>
                <nobr>
                    <button class="btn btn-xs btn-info marketplace-modal-show" type="button" modal-url="/market-place/edit-form/<?= $marketplace->getId()?>">
                        <span class="glyphicon glyphicon-pencil" ></span>
                    </button>
                </nobr>    
            </td>    
        </tr> 
    <?php endforeach; ?>       
</table>

<script type="text/javascript">
    $(function () {
        $(document).on('click', '.marketplace-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'marketplaceModal',
                url: url,
                width: '1440px'
            });
        });          
        
        $(document).on('click', '.marketplace-realization', function (e) {
            var url = $(this).attr('modal-url');
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока идет загрузка ...</p>',
                closeButton: false
            });
                        
            $.ajax({
                url: url,
                success: function (data) {
                    dialog.modal('hide');
//                    console.log(data);
                },
                error: function(data){
                    dialog.modal('hide');
                    alert('Отчет не создан');
                }
            });            
        });          
    });    
</script>