<?php
$this->headTitle('Торговые площадки');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Администрирование'=>$this->url('admin'),
            'Торговые площадки' => $this->url('market-place')
            ]);  

?>
<p>
    <button class="btn btn-default marketplace-modal-show" type="button" modal-url="/market-place/edit-form">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"> Добавить</span>
    </button>                
</p>

<table class="table table-striped">

   <tr>
        <th>Id</th>
        <th>Наименование</th>
        <th>ID Личного кабинета</th>  
        <th>Статус</th>  
        <th></th>
    </tr>
    
    <?php foreach ($marketplaces as $marketplace): ?>    
        <tr>
            <td><?= $this->escapeHtml($marketplace->getId()); ?></td>
            <td>
                <?= $marketplace->getTagName(); ?>
            </td>
            <td>
                <?= $this->escapeHtml($marketplace->getMerchantId()); ?>
            </td>
            <td>
                <?= $this->escapeHtml($marketplace->getStatusAsString()); ?>
            </td>
            <td>
                <nobr>
                    <button class="btn btn-xs btn-info marketplace-modal-show" type="button" modal-url="/market-place/edit-form/<?= $marketplace->getId()?>">
                        <span class="glyphicon glyphicon-pencil" ></span>
                    </button>
                </nobr>    
            </td>    
        </tr> 
    <?php endforeach; ?>       
</table>

<script type="text/javascript">
    $(function () {
        $(document).on('click', '.marketplace-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'marketplaceModal',
                url: url,
                width: '1440px'
            });
        });          
    });    
</script>