<?php
use ApiMarketPlace\Entity\Marketplace;

$this->headTitle('Торговая площадка');

$this->mainMenu()->setActiveItemId('');

?>


<h1><?= $marketplace->getName()?></h1>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
    <button class="btn btn-xs btn-info marketplace-modal-show" type="button" modal-url="/market-place/edit-form/<?= $marketplace->getId()?>">
        <span class="glyphicon glyphicon-pencil" ></span> Изменить
    </button>
    <?php if ($marketplace->getMarketType() == Marketplace::TYPE_OZON):?>
        <button class="btn btn-xs btn-default marketplace-realization" type="button" modal-url="/market-place/ozon-realization/<?= $marketplace->getId()?>">
            <span class="glyphicon glyphicon-list" ></span> Отчет о реализации
        </button>
    <?php endif;?>
</p>
    
<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($marketplace->getId()) ?></td>
            </tr>
            <tr>
                <th>Наименование:</th>
                <td><?= $this->escapeHtml($marketplace->getName()) ?></td>
            </tr>
            <tr>
                <th>Номер в магазина в торговой площадке:</th>
                <td><?= $this->escapeHtml($marketplace->getMerchantId()) ?></td>
            </tr>
            <tr>
                <th>Сайт:</th>
                <td>
                    <?php if ($marketplace->getSite()):?>
                        <a href="<?= $marketplace->getSite() ?>" target="_blank"><?= $this->escapeHtml($marketplace->getSite()) ?></a>
                    <?php endif; ?>    
                </td>    
            </tr>
            <tr>
                <th>Ip торговой площадки:</th>
                <td><?= $this->escapeHtml($marketplace->getRemoteAddr()) ?></td>
            </tr>
            <tr>
                <th>Клиент:</th>
                <td><?= $marketplace->getContactPresent() ?></td>
            </tr>
            <tr>
                <th>Договор:</th>
                <td><?= $marketplace->getContractPresent() ?></td>
            </tr>
            <tr>
                <th>Тип:</th>
                <td><?= $this->escapeHtml($marketplace->getMarketTypeAsString()) ?></td>
            </tr>
            <tr>
                <th>Статус:</th>
                <td><?= $this->escapeHtml($marketplace->getStatusAsString()) ?></td>
            </tr>
            <tr>
                <th>Комментарий:</th>
                <td><?= $this->escapeHtml($marketplace->getComment()) ?></td>
            </tr>
            <tr>
                <th>Дата создания:</th>
                <td><?= $this->escapeHtml($marketplace->getDateCreated()) ?></td>
            </tr>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $(document).on('click', '.marketplace-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'marketplaceModal',
                url: url,
                width: '1440px'
            });
        });   
        
        $(document).on('click', '.marketplace-realization', function (e) {
            var url = $(this).attr('modal-url');
            bootbox.prompt({
                title: 'Месяц отчета',
                inputType: 'date',
                size: 'small',
                min: '<?= $allowDate?>',
                value: $.format.date(new Date(), "yyyy-MM-dd"),
                callback: function (result) {
                    if (result){
                        var dialog = bootbox.dialog({
                            message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока идет загрузка ...</p>',
                            closeButton: false
                        });
                        
                        $.ajax({
                            url: url+'?date='+result,
                            success: function (data) {
                                dialog.modal('hide');
            //                    console.log(data);
                            },
                            error: function(data){
                                dialog.modal('hide');
                                alert('Отчет не создан');
                            }
                        });            
                    }    
                }
            });                                            
        });          
    });    
</script>