<?php

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('position')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Сохранить');

$form->prepare();
?>

        <?= $this->form()->openTag($form); ?>

        <div class="modal-header">
            <h5 class="modal-title">Член коммисии</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
            
        <div class="modal-body">
            <div class="row">
                <div class="col-md-10">
        
                    <div class="form-group">
                        <?= $this->formLabel($form->get('name')); ?>
                        <?= $this->formElement($form->get('name')); ?>
                        <?= $this->formElementErrors($form->get('name')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('position')); ?>
                        <?= $this->formElement($form->get('position')); ?>
                        <?= $this->formElementErrors($form->get('position')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('status')); ?>
                        <?= $this->formElement($form->get('status')); ?>
                        <?= $this->formElementErrors($form->get('status')); ?>                  
                    </div>        
                </div>
            </div>
        </div>    
        
        <?= $this->form()->closeTag(); ?>
        
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            <button type="button" class="btn btn-primary" id="commission-submit">Сохранить</button>
        </div>
        

<script>
    $('#commission-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/offices/edit-commission/<?= ($commission) ? $commission->getId():'' ?>?office=<?= $office->getId()?>',
            data: $('#commission-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
                    window.location.reload();
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");

            });
    })    
</script>