<?php

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Наименование'
    ]);

$form->get('aplId')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'apl ID'
    ]);

$form->get('shippingLimit1')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('shippingLimit2')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('region')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Регион'
    ]);

$form->get('sbCard')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('sbOwner')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('sbpMerchantId')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Статус'
    ]);

$form->get('parent')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('linkReview')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Сохранить');

$form->prepare();
?>

<?= $this->form()->openTag($form); ?>

<div class="modal-header">
    <h5 class="modal-title">Изменить данные офиса</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
            
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('name')); ?>
                        <?= $this->formElement($form->get('name')); ?>
                        <?= $this->formElementErrors($form->get('name')); ?>                  
                    </div>
                </div>
            </div>    
            <div clalss="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('aplId')); ?>
                        <?= $this->formElement($form->get('aplId')); ?>
                        <?= $this->formElementErrors($form->get('aplId')); ?>                  
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('parent')); ?>
                        <?= $this->formElement($form->get('parent')); ?>
                        <?= $this->formElementErrors($form->get('parent')); ?>                  
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('shippingLimit1')); ?>
                        <?= $this->formElement($form->get('shippingLimit1')); ?>
                        <?= $this->formElementErrors($form->get('shippingLimit1')); ?>                  
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('sbCard')); ?>
                        <?= $this->formElement($form->get('sbCard')); ?>
                        <?= $this->formElementErrors($form->get('sbCard')); ?>                  
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('sbpMerchantId')); ?>
                        <?= $this->formElement($form->get('sbpMerchantId')); ?>
                        <?= $this->formElementErrors($form->get('sbpMerchantId')); ?>                  
                    </div>
                </div>
                <div class="col-md-6">                
                    <div class="form-group">
                        <?= $this->formLabel($form->get('status')); ?>
                        <?= $this->formElement($form->get('status')); ?>
                        <?= $this->formElementErrors($form->get('status')); ?>                  
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('region')); ?>
                        <?= $this->formElement($form->get('region')); ?>
                        <?= $this->formElementErrors($form->get('region')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('shippingLimit2')); ?>
                        <?= $this->formElement($form->get('shippingLimit2')); ?>
                        <?= $this->formElementErrors($form->get('shippingLimit2')); ?>                  
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('sbOwner')); ?>
                        <?= $this->formElement($form->get('sbOwner')); ?>
                        <?= $this->formElementErrors($form->get('sbOwner')); ?>                  
                    </div>
                </div>    
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('linkReview')); ?>
                        <?= $this->formElement($form->get('linkReview')); ?>
                        <?= $this->formElementErrors($form->get('linkReview')); ?>                  
                    </div>
                </div>
            </div>    
        </div>    
    </div>
</div>    
        
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="button" class="btn btn-primary" id="office-submit">Сохранить</button>
</div>
        
<?= $this->formElement($form->get('csrf')); ?>
<?= $this->form()->closeTag(); ?>
        
<script>
    $('#office-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/offices/edit-form/<?= $office->getId() ?>',
            data: $('#office-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
                    window.location.reload();
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");

            });
    })    
</script>