<?php
$this->headTitle('Офис '.$office->getName());

$this->mainMenu()->setActiveItemId('offices');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Офисы'=>$this->url('offices'),
            $office->getName()=>$this->url('offices', ['action'=>'view', 'id'=>$office->getId()])
            ]);

$this->headScript()
            ->appendFile($this->basePath('js/jquery.mask.min.js'))
        ;                     

?>


<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="row">
    <div class="col-sm-9">
        <div id="section1">
            <h2>Офис <?= $office->getName() ?></h2>
            <div>
                <button value="/offices/edit-form/<?= $office->getId() ?>" class="btn btn-default btn-xs"
                        data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                    <span class="glyphicon glyphicon-edit" ></span>
                    Изменить
                </button>                    

            </div>
            <table class="table table-striped table-bordered">
                 <tr>
                    <th>ID:</th>
                    <td><?= $this->escapeHtml($office->getId()) ?></th>
                </tr>
                <tr>
                    <th>Наименование:</th>
                    <td><?= $this->escapeHtml($office->getName()) ?></th>
                </tr>
                <tr>
                    <th>Регион:</th>
                    <td><?= $this->escapeHtml($office->getRegion()->getFullName()) ?></th>
                </tr>
                <tr>
                    <th>Статус:</th>
                    <td><?= $this->escapeHtml($office->getStatusAsString()) ?></th>
                </tr>
            </table>
        </div>

        <div id="section2">
            <h2>Контактные телефоны</h2>
            <?php foreach ($office->getLegalContacts() as $contact):?>
                <div>
                    <button value="/contact/phone-form/<?= $contact->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Добавить телефон">
                        <span class="glyphicon glyphicon-plus" ></span>
                        телефон
                    </button>                    

                </div>
                <table class="table table-striped table-bordered">
                    <?php foreach ($contact->getPhones() as $phone): ?>
                        <tr>
                           <th class="phone_name">
                                <div class="pull-left">
                                    <?= $phone->getName()?>
                                    <span><?= $phone->getComment()?></span>
                                </div>
                                <div class="pull-right">
                                    <button value="/contact/phone-form/<?= $contact->getId() ?>?phone=<?= ($phone ? $phone->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                        <span class="glyphicon glyphicon-edit" ></span>
                                    </button>                                                            
                                    <button value="/contact/delete-phone-form/<?= $phone->getId() ?>" class="btn btn-default btn-xs this-delete"
                                            title="Удалить">
                                        <span class="glyphicon glyphicon-remove" ></span>
                                    </button>                                                            
                                </div>                                        
                           </th>
                       </tr>
                    <?php endforeach; ?>
                </table>
            <?php endforeach; ?>
        </div>
        <div id="section3">
            <h2>Электронная почта</h2>
            <?php foreach ($office->getLegalContacts() as $contact):?>
                <div>
                    <button value="/contact/email-form/<?= $contact->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Добавить email">
                        <span class="glyphicon glyphicon-plus" ></span>
                        email
                    </button>                                            
                </div>     
                <table class="table table-striped table-bordered">
                    <?php foreach ($contact->getEmails() as $email): ?>
                        <tr>
                           <th class="email_name">
                                <div class="pull-left">
                                    <?= $email->getName()?>
                                </div>
                                <div class="pull-right">
                                    <button value="/contact/email-form/<?= $contact->getId() ?>?email=<?= ($email ? $email->getId():'') ?>" class="btn btn-default btn-xs email-edit"
                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                        <span class="glyphicon glyphicon-edit" ></span>
                                    </button>                                                            
                                    <button value="/contact/delete-email-form/<?= $email->getId() ?>" class="btn btn-default btn-xs this-delete"
                                            title="Удалить">
                                        <span class="glyphicon glyphicon-remove" ></span>
                                    </button>                                                            
                                </div>                                        
                           </th>
                       </tr>
                    <?php endforeach; ?>
                </table>
            <?php endforeach; ?>
        </div>

        <div id="section4">
            <h3>Мессенджеры</h3>
            <p>
                <button value="/contact/messenger-form/<?= $office->getLegalContact()->getId() ?>" class="btn btn-default btn-xs"
                        data-toggle="modal" data-target="#modal-dialog" title="Добавить мессенджер">
                    <span class="glyphicon glyphicon-plus" ></span>
                    мессенджер
                </button>                    
            </p>            
            <table class="table table-striped table-bordered">
                <?php if (count($office->getLegalContact()->getMessengers())):?>
                    <?php foreach ($office->getLegalContact()->getMessengers() as $messenger): ?>
                        <tr>
                            <td>
                                <?= $this->escapeHtml($messenger->getTypesAsString()); ?>
                            </td>
                            <td>
                                <div class="pull-left">
                                    <?= $this->escapeHtml($messenger->getIdent()); ?>
                                </div>                                        
                                <div class="pull-right">
                                    <button value="/contact/messenger-form/<?= $messenger->getContact()->getId() ?>?messenger=<?= $messenger->getId() ?>" class="btn btn-default btn-xs"
                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                        <span class="glyphicon glyphicon-edit" ></span>
                                    </button>                                                            
                                    <button value="/contact/delete-messenger-form/<?= $messenger->getId() ?>" class="btn btn-default btn-xs this-delete"
                                            title="Удалить">
                                        <span class="glyphicon glyphicon-remove" ></span>
                                    </button>                                                            
                                </div>                                        
                            </td>
                       </tr>
                    <?php endforeach; ?>   
                <?php endif;?>       
            </table>
        </div>

        <div id="section5">
            <h3>Адреса</h3>
            <p>
                <button value="/contact/address-form/<?= $office->getLegalContact()->getId() ?>" class="btn btn-default btn-xs"
                        data-toggle="modal" data-target="#modal-dialog" title="Добавить адрес">
                    <span class="glyphicon glyphicon-plus" ></span>
                    адрес
                </button>                    
            </p>            
            <table class="table table-striped table-bordered">
                <?php if (count($office->getLegalContact()->getAddresses())):?>
                    <?php foreach ($office->getLegalContact()->getAddresses() as $address): ?>
                        <tr>
                            <td>
                                <?= $this->escapeHtml($address->getName()); ?>
                            </td>
                            <td>
                                <div class="pull-left">
                                    <?= $this->escapeHtml($address->getAddress()); ?>
                                </div>                                        
                                <div class="pull-right">
                                    <button value="/contact/address-form/<?= $address->getContact()->getId() ?>?address=<?= $address->getId() ?>" class="btn btn-default btn-xs"
                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                        <span class="glyphicon glyphicon-edit" ></span>
                                    </button>                                                            
                                    <button value="/contact/delete-address-form/<?= $address->getId() ?>" class="btn btn-default btn-xs this-delete"
                                            title="Удалить">
                                        <span class="glyphicon glyphicon-remove" ></span>
                                    </button>                                                            
                                </div>                                        
                            </td>
                       </tr>
                    <?php endforeach; ?>   
                <?php endif;?>       
            </table>
        </div>
        <div id="section6">
            <h2>Юридические лица</h2>
            <?php foreach ($office->getLegalContacts() as $contact):?>
                <p>
                    <a class="btn btn-default btn-xs" href="<?= $this->url('legals', 
                                        ['action'=>'legal', 'id'=>$contact->getId()]); ?>">
                                    <span class="glyphicon glyphicon-piggy-bank" ></span> <?= (count($contact->getLegals())) ? 'Изменить':'Добавить'; ?>
                    </a>
                </p>
                <table class="table table-striped table-bordered">
                    <?php foreach ($contact->getLegals() as $legal): ?>
                        <tr>
                           <th class=""><?= $legal->getName() ?></th>
                           <th class=""><?= $legal->getInn() ?></th>
                           <th class=""><?= $legal->getKpp() ?></th>
                       </tr>
                    <?php endforeach; ?>
                </table>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-sm-3" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active"><a href="#section1">Офис</a></li>
            <li><a href="#section2">Контакты</a></li>
            <li><a href="#section3">Адреса</a></li>
            <li><a href="#section3">Юридические лица</a></li>
        </ul>
    </div>
</div>

<div class="modal fade" id="modal-dialog" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal-content">
        </div>
    </div>
</div>

<script>
    $('#modal-dialog').on('show.bs.modal', function (e) {        
        var url = e.relatedTarget.value;
        if (url){
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                   $('#modal-content').html(data);
                })
                .fail(function () {
                    alert("Ошибка открытия формы.");
                }); 
        }
    })    
        
    $('.this-delete').on('click', function(e) {
        var url = e.currentTarget.value;
        if (url){
            if (confirm('Удалить запись?')){
                $.ajax({
                    type: 'GET',
                    url: url,
                })
                    .done(function (data) {
                        if (data == 'ok'){
                            window.location.reload();
                        } else {
                            alert("Не удалось удалить!");
                        }    
                    })
                    .fail(function (e) {
                        alert("Не удалось удалить.");

                    });
            }        
        }        
    })    
    
</script>