<?php
$this->headTitle('Офис '.$office->getName());

$this->mainMenu()->setActiveItemId('offices');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Офисы'=>$this->url('offices'),
            $office->getName()=>$this->url('offices', ['action'=>'view', 'id'=>$office->getId()])
            ]);

$this->headScript()
            ->appendFile($this->basePath('js/jquery.mask.min.js'))
        ;      

$legalContact = $office->getLegalContact();

?>


<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="row">
    <div class="col-sm-9">
        <div class="panel panel-default" id="section1">
            <div class="panel-heading">
                <h2>Офис <?= $office->getName() ?></h2>                
            </div>
            <div class="panel-body">
                <div class="pull-left">
                    ID: <?= $this->escapeHtml($office->getId()) ?>, AplId: <?= $this->escapeHtml($office->getAplId()) ?><br/>
                    Наименование: <?= $this->escapeHtml($office->getName()) ?><br/>
                    Регион: <?= $this->escapeHtml($office->getRegion()->getFullName()) ?><br/>
                    Статус: <?= $this->escapeHtml($office->getStatusAsString()) ?><br/>
                </div>
                <div class="pull-right">
                    <button value="/offices/edit-form/<?= $office->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                        <span class="glyphicon glyphicon-edit" ></span>
                    </button>                                                    
                </div>
            </div>
        </div>

        <div class="panel panel-default" id="section2">
            <div class="panel-body">
                <div class="pull-left">
                    <div class="panel-title">Контактные телефоны</div>
                </div>
                <div class="pull-right">
                    <button value="/contact/phone-form/<?= $legalContact->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Добавить телефон">
                        <span class="glyphicon glyphicon-plus" ></span>
                    </button>                                        
                </div>
            </div>
            <div class="panel-body">
                <div class="panel panel-group">
                    <?php foreach ($legalContact->getPhones() as $phone): ?>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="pull-left">
                                    <?= $phone->getName()?> <span><?= $phone->getComment()?></span>
                                </div>
                                <div class="pull-right">
                                    <button value="/contact/phone-form/<?= $legalContact->getId() ?>?phone=<?= ($phone ? $phone->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                        <span class="glyphicon glyphicon-edit" ></span>
                                    </button>                                                            
                                    <button value="/contact/delete-phone-form/<?= $phone->getId() ?>" class="btn btn-default btn-xs this-delete"
                                            title="Удалить">
                                        <span class="glyphicon glyphicon-remove" ></span>
                                    </button>                                                            
                                </div>
                            </div>
                        </div>    
                    <?php endforeach; ?>
                </div>                    
            </div>
        </div>
            
        <div class="panel panel-default" id="section3">
            <div class="panel-body">
                <div class="pull-left">
                    <div class="panel-title">Электронная почта</div>
                </div>
                <div class="pull-right">
                    <button value="/contact/email-form/<?= $legalContact->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Добавить email">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>                                            
                </div>
            </div>
            <div class="panel-body">
                <div class="panel panel-group">
                    <?php foreach ($legalContact->getEmails() as $email): ?>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="pull-left">
                                    <?= $email->getName()?>
                                </div>
                                <div class="pull-right">
                                    <button value="/contact/email-form/<?= $legalContact->getId() ?>?email=<?= ($email ? $email->getId():'') ?>" class="btn btn-default btn-xs email-edit"
                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                        <span class="glyphicon glyphicon-edit" ></span>
                                    </button>                                                            
                                    <button value="/contact/delete-email-form/<?= $email->getId() ?>" class="btn btn-default btn-xs this-delete" title="Удалить">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </button>                                                            
                                </div>
                            </div>

                        </div>
                    <?php endforeach; ?>
                </div>                    
            </div>
        </div>
            
        <div class="panel panel-default" id="section4">
            <div class="panel-body">
                <div class="pull-left">
                    <div class="panel-title">Мессенджеры</div>
                </div>
                <div class="pull-right">
                    <button value="/contact/messenger-form/<?= $legalContact->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Добавить мессенджер">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>                                            
                </div>
            </div>
            <div class="panel-body">
                <div class="panel panel-group">
                    <?php foreach ($legalContact->getMessengers() as $messenger): ?>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="pull-left">
                                    <?= $this->escapeHtml($messenger->getTypesAsString()); ?>: <?= $this->escapeHtml($messenger->getIdent()); ?>
                                </div>
                                <div class="pull-right">
                                    <button value="/contact/messenger-form/<?= $messenger->getContact()->getId() ?>?messenger=<?= $messenger->getId() ?>" class="btn btn-default btn-xs"
                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                        <span class="glyphicon glyphicon-edit" ></span>
                                    </button>                                                            
                                    <button value="/contact/delete-messenger-form/<?= $messenger->getId() ?>" class="btn btn-default btn-xs this-delete"
                                            title="Удалить">
                                        <span class="glyphicon glyphicon-remove" ></span>
                                    </button>                                                            
                                </div>
                            </div>

                        </div>
                    <?php endforeach; ?>
                </div>                    
            </div>
        </div>
            
        <div class="panel panel-default" id="section5">
            <div class="panel-body">
                <div class="pull-left">
                    <div class="panel-title">Адреса</div>
                </div>
                <div class="pull-right">
                    <button value="/contact/address-form/<?= $legalContact->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Добавить адрес">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>                                            
                </div>
            </div>
            <div class="panel-body">
                <div class="panel panel-group">
                    <?php foreach ($legalContact->getAddresses() as $address): ?>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="pull-left">
                                    <?= $this->escapeHtml($address->getName()); ?>: <?= $this->escapeHtml($address->getAddress()); ?>
                                </div>
                                <div class="pull-right">
                                    <button value="/contact/address-form/<?= $address->getContact()->getId() ?>?address=<?= $address->getId() ?>" class="btn btn-default btn-xs"
                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                        <span class="glyphicon glyphicon-edit" ></span>
                                    </button>                                                            
                                    <button value="/contact/delete-address-form/<?= $address->getId() ?>" class="btn btn-default btn-xs this-delete"
                                            title="Удалить">
                                        <span class="glyphicon glyphicon-remove" ></span>
                                    </button>                                                            
                                </div>
                            </div>

                        </div>
                    <?php endforeach; ?>
                </div>                    
            </div>
        </div>

        <div class="panel panel-default" id="section6">
            <?php echo $this->partial('/company/legal/partial-view', ['legalContact' => $legalContact, 'notContract' => true]); ?>
        </div>
    </div>
    <div class="col-sm-3" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active"><a href="#section1">Офис</a></li>
            <li><a href="#section2">Контактные телефоны</a></li>
            <li><a href="#section3">Электронная почта</a></li>
            <li><a href="#section4">Мессенджеры</a></li>
            <li><a href="#section5">Адреса</a></li>
            <li><a href="#section6">Юридические лица</a></li>
        </ul>
    </div>
</div>

<div class="modal fade" id="modal-dialog" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal-content">
        </div>
    </div>
</div>

<script>
    $('#modal-dialog').on('show.bs.modal', function (e) {        
        var url = e.relatedTarget.value;
        if (url){
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                   $('#modal-content').html(data);
                })
                .fail(function () {
                    alert("Ошибка открытия формы.");
                }); 
        }
    })    
        
    $('.this-delete').on('click', function(e) {
        var url = e.currentTarget.value;
        if (url){
            if (confirm('Удалить запись?')){
                $.ajax({
                    type: 'GET',
                    url: url,
                })
                    .done(function (data) {
                        if (data == 'ok'){
                            window.location.reload();
                        } else {
                            alert("Не удалось удалить!");
                        }    
                    })
                    .fail(function (e) {
                        alert("Не удалось удалить.");

                    });
            }        
        }        
    })    
    
</script>