<?php
use Application\Entity\Order;
use Cash\Entity\CashDoc;
use Laminas\Json\Encoder;

if ($order){
    $docName = '№ '.$order->getDocNo().' от  '.date('d.m.Y', strtotime($order->getDocDate()));
}

$cashDocDisabled = (!empty($order)) ? '':'disabled';

?>

<div class="modal-header">
    <h5 class="modal-title" id="cashDocModalLabel">Оплаты по заказу <?= $docName?></h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="row">
    <div class="col-xs-12">
        <div id="cashdoctoolbar">
            <div class="form-inline" role="form">
                <button <?= $cashDocDisabled?> class="btn btn-info btn-sm cash-in-modal-show" type="button" 
                    modal-url="/till/edit-cash-in?order=<?= $order->getId()?>" title="Поступление в кассу">
                    <span class="glyphicon glyphicon-rub" aria-hidden="true"></span> +
                </button>                
                <button <?= $cashDocDisabled?> class="btn btn-info btn-sm cash-out-modal-show" type="button" 
                    modal-url="/till/edit-cash-out?order=<?= $order->getId()?>" title="Списание из кассы">
                    <span class="glyphicon glyphicon-rub" aria-hidden="true"></span> -
                </button>  
                
                <button <?= $cashDocDisabled?> class="btn btn-default btn-sm user-in-modal-show" type="button" 
                    modal-url="/accountant/edit-user-in/?order=<?= $order->getId()?>" title="Поступление в подотчет">
                    <span class="glyphicon glyphicon-ruble" aria-hidden="true"></span> +
                </button>                
                <button <?= $cashDocDisabled?> class="btn btn-default btn-sm user-out-modal-show" type="button" 
                    modal-url="/accountant/edit-user-out/?order=<?= $order->getId()?>"  title="Списание с подотчета">
                    <span class="glyphicon glyphicon-ruble" aria-hidden="true"></span> -
                </button>                
            </div>
        </div>
        <table id="cashdoctable" 
            data-toggle="cashdoctable" 
            data-url="/cash/order-content/<?= ($order) ? $order->getId():"" ?>"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#cashdoctoolbar"
            data-show-refresh="true"
            data-query-params="cashDocQueryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="cashDocResponseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="cashDocRowStyle"
            >
            <thead>
                <tr>
                    <th data-field="id" data-sortable="false" data-formatter="cashDocIdFormatter" data-width="150">Номер</th>
                    <th data-field="dateOper" data-sortable="true" data-formatter="cashDocDateFormatter" data-width="100">Дата</th>
                    <!--<th data-field="aplId" data-type="numeric" data-align="right">AplId</th>-->
                    <th data-field='kind' data-sortable="false" data-formatter="cashDocKindFormatter" data-width="150">Операция</th>
                    <th data-field='amount' data-sortable="false" data-type="numeric" data-align="right" data-formatter="cashDocAmountFormatter">Сумма</th>
                    <!--<th data-field='order.aplId' data-sortable="false" data-formatter="linkFormatter">Заказ</th>-->
                    <!--<th data-field='office.name' data-sortable="false">Склад</th>-->
                    <th data-field='comment' data-sortable="false">Примечание</th>
                    <th data-field="" data-formatter="cashDocActiveFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script>
    $( document ).ready(function() {        
        $cashdoctable = $('#cashdoctable').bootstrapTable();         
    });
    
    function cashRefreshTable(){
        $('#cashdoctable').bootstrapTable('refresh');
    }
    
    function cashDocRowStyle(row){
        var retired = 'cashdoctablerow';
        if (row.status === <?= CashDoc::STATUS_RETIRED ?>){
           retired += ' retired';
        }
        return {classes: retired};
    }

    function cashDocQueryParams(params) {
        $('#cashdoctoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#cashdoctable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#cashdoctable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }

    function cashDocIdFormatter(value, row){
        if (row.aplId > 0){
            return value + ' ('+row.aplId+')';
        }
        
        return value;
    }    
    
    function cashDocDateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }
    
    function cashDocKindFormatter(value){
        var result = <?= Encoder::encode(CashDoc::getKindList())?>;
        return result[value];
    }
    
    function cashDocAmountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    
    
    function cashDocActiveFormatter(value, row){
        
        var btn = '<button';
        btn += ' type="button"';

        var url = '/till/edit-cash-in/'+row.id;
        
        if (row.kind<10){
            btn += ' class="btn btn-default btn-xs cash-in-modal-show"';
        }    
        if (row.kind>10){
            url = '/till/edit-cash-out/'+row.id;
            btn += ' class="btn btn-default btn-xs cash-out-modal-show"';
        }    
        if (row.kind<10 && row.userId > 0){
            url = '/accountant/edit-user-in/'+row.id;
            btn += ' class="btn btn-default btn-xs user-in-modal-show"';
        }    
        if (row.kind>10 && row.userId > 0){
            url = '/accountant/edit-user-out/'+row.id;
            btn += ' class="btn btn-default btn-xs user-out-modal-show"';
        }    

        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';

        return btn;
    }    

    function cashDocResponseHandler(res) {
        return res;
    }     
</script>