<?php
$form = $this->form;

$form->get('mode')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('name')->setAttributes([
    'class'=>'form-control searchinput', 
    ]);

$form->get('phone1')->setAttributes([
    'class'=>'form-control phone', 
    'placeholder'=>'8 (000) 000-0000',
    'aria-describedby' => "basic-addon2",
    ]);

$form->get('phone2')->setAttributes([
    'class'=>'form-control phone', 
    'placeholder'=>'8 (000) 000-0000',
    'aria-describedby' => "basic-addon2",
    ]);

$form->get('vin')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('make')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('gds')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('info')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('order')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('manager')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('yocm')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('wheel')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('tm')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('ac')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('md')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('ed')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('ep')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'ring-submit']);

$form->prepare();

?>


    <?= $this->form()->openTag($form); ?>
            
        <div class="modal-header">
            <h5 class="modal-title">Звонок</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
            
        <div class="modal-body">
            <div class="row">
                <div class="col-xs-2">                        
                    <div class="form-group">
                        <?= $this->formLabel($form->get('phone1')); ?>
                        <?= $this->formElement($form->get('phone1')); ?>
                        <!--<span class="searchclear glyphicon glyphicon-remove-circle"></span>-->
                        <?= $this->formElementErrors($form->get('phone1')); ?> 
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('phone2')); ?>
                        <?= $this->formElement($form->get('phone2')); ?>
                        <!--<span class="searchclear glyphicon glyphicon-remove-circle"></span>-->
                        <?= $this->formElementErrors($form->get('phone2')); ?>                  
                    </div>
                </div>    
                <div class="col-xs-4">       
                    <div class="form-group">
                        <?= $this->formLabel($form->get('name')); ?>
                        <?= $this->formElement($form->get('name')); ?> 
                        <span class="searchclear glyphicon glyphicon-remove-circle"></span>
                        <?= $this->formElementErrors($form->get('name')); ?>                  
                    </div>    
                </div>    
                <div class="col-xs-2">                        
                </div>    
            </div>    
            <div class="row">
                <div class="col-xs-4">                        
                    <div class="form-group">
                        <?= $this->formLabel($form->get('make')); ?>
                        <?= $this->formElement($form->get('make')); ?>
                        <?= $this->formElementErrors($form->get('make')); ?>                  
                    </div>
                </div>    
            </div>    
            <div class="row">
                <div class="col-xs-4">                        
                    <div class="form-group">
                        <?= $this->formLabel($form->get('wheel')); ?>
                        <?= $this->formElement($form->get('wheel')); ?>
                        <?= $this->formElementErrors($form->get('wheel')); ?>                  
                    </div>
                </div>    
                <div class="col-xs-4">                        
                    <div class="form-group">
                        <?= $this->formLabel($form->get('tm')); ?>
                        <?= $this->formElement($form->get('tm')); ?>
                        <?= $this->formElementErrors($form->get('tm')); ?>                  
                    </div>
                </div>    
                <div class="col-xs-4">                        
                    <div class="form-group">
                        <?= $this->formLabel($form->get('ac')); ?>
                        <?= $this->formElement($form->get('ac')); ?>
                        <?= $this->formElementErrors($form->get('ac')); ?>                  
                    </div>
                </div>    
            </div>        
            <div class="row">
                <div class="col-xs-4">                        
                    <div class="form-group">
                        <?= $this->formLabel($form->get('md')); ?>
                        <?= $this->formElement($form->get('md')); ?>
                        <?= $this->formElementErrors($form->get('md')); ?>                  
                    </div>
                </div>    
                <div class="col-xs-4">                        
                    <div class="form-group">
                        <?= $this->formLabel($form->get('ed')); ?>
                        <?= $this->formElement($form->get('ed')); ?>
                        <?= $this->formElementErrors($form->get('ed')); ?>                  
                    </div>
                </div>    
                <div class="col-xs-4">                        
                    <div class="form-group">
                        <?= $this->formLabel($form->get('ep')); ?>
                        <?= $this->formElement($form->get('ep')); ?>
                        <?= $this->formElementErrors($form->get('ep')); ?>                  
                    </div>
                </div>    
            </div>        
            <div class="row">
                <div class="col-xs-12">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('comment')); ?>
                        <?= $this->formElement($form->get('comment')); ?>
                        <?= $this->formElementErrors($form->get('comment')); ?>                  
                    </div>                        
                </div>    

            </div>        

        </div>
   
                
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            <button type="button" class="btn btn-primary" id="ring-submit">Сохранить</button>
        </div>

        <?= $this->form()->closeTag(); ?>

<style>
.searchclear {
    position:absolute;
    right:20px;
    top:0;
    bottom:0;
    height:5px;
    margin:auto;
    font-size:14px;
    cursor:pointer;
    color:#ccc;
}    
</style>
            
<script>
    $(document).ready(function () {
        $(".searchinput").keyup(function () {
            $(this).next().toggle(Boolean($(this).val()));
        });
        $(".searchclear").toggle(Boolean($(".searchinput").val()));
        $(".searchclear").click(function () {
            $(this).prev().val('').focus();
            $(this).hide();
        });
    });
    
    $('.phone').mask('8 (000) 000-0000', {selectOnFocus: true});
    
    $('.phone').on('input', function(){
        var value = $( this ).val();
        if (value.length == 16){
            $.ajax({
                type: 'POST',
                url: '/ring/find-phone',
                data: {phone: value}
            })
                .done(function (data) {
                    if (data){
                        $('#name').val(data.name);
                        $('#name').next().toggle(Boolean($('#name').val()));
                    }    
                })
                .fail(function (e) {
                    console.log(e);
                });
        }        
    });

    $('#ring-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/ring/edit-form/<?= ($ring) ? $ring->getId():'' ?>',
            data: $('#ring-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
                    window.location.reload();
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");

            });
    })    
    
</script>