<?php
$form = $this->form;

$form->get('mode')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('helpGroup')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('name')->setAttributes([
    'class'=>'form-control searchinput', 
    ]);

$form->get('info')->setAttributes([
    'class'=>'form-control phone', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control phone', 
    ]);

$form->get('sort')->setAttributes([
    'class'=>'form-control phone', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'help-submit']);

$form->prepare();

?>


    <?= $this->form()->openTag($form); ?>
            
        <div class="modal-header">
            <h5 class="modal-title">Подсказка</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
            
        <div class="modal-body">
            <div class="row">
                <div class="col-xs-9">                        
                    <div class="form-group">
                        <?= $this->formLabel($form->get('name')); ?>
                        <?= $this->formElement($form->get('name')); ?>
                        <?= $this->formElementErrors($form->get('name')); ?> 
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('info')); ?>
                        <?= $this->formElement($form->get('info')); ?>
                        <?= $this->formElementErrors($form->get('info')); ?>                  
                    </div>                        
                </div>    
                <div class="col-xs-3">       
                    <div class="form-group">
                        <?= $this->formLabel($form->get('sort')); ?>
                        <?= $this->formElement($form->get('sort')); ?> 
                        <?= $this->formElementErrors($form->get('sort')); ?>                  
                    </div>    
                    <div class="form-group">
                        <?= $this->formLabel($form->get('status')); ?>
                        <?= $this->formElement($form->get('status')); ?> 
                        <?= $this->formElementErrors($form->get('status')); ?>                  
                    </div>    
                    <div class="form-group">
                        <?= $this->formLabel($form->get('mode')); ?>
                        <?= $this->formElement($form->get('mode')); ?> 
                        <?= $this->formElementErrors($form->get('mode')); ?>                  
                    </div>    
                    <div class="form-group">
                        <?= $this->formLabel($form->get('helpGroup')); ?>
                        <?= $this->formElement($form->get('helpGroup')); ?> 
                        <?= $this->formElementErrors($form->get('helpGroup')); ?>                  
                    </div>    
                </div>    
            </div>    
            <div class="row">
                <div class="col-xs-9">
                </div>    
            </div>    
        </div>
   
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            <button type="submit" class="btn btn-primary" id="help-submit">Сохранить</button>
        </div>

        <?= $this->form()->closeTag(); ?>

<style>
.searchclear {
    position:absolute;
    right:20px;
    top:0;
    bottom:0;
    height:5px;
    margin:auto;
    font-size:14px;
    cursor:pointer;
    color:#ccc;
}    
</style>
            
<script>
    function submitForm(){
        $.ajax({
            type: 'POST',
            url: '/ring/help-form/<?= ($help) ? $help->getId():null; ?>',
            data: $('#help-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#table').bootstrapTable('refresh');
                    $('#helpModal').modal('hide');
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");
            });
    }    
    
    $(document).ready(function () {
        $(".searchinput").keyup(function () {
            $(this).next().toggle(Boolean($(this).val()));
        });
        $(".searchclear").toggle(Boolean($(".searchinput").val()));
        $(".searchclear").click(function () {
            $(this).prev().val('').focus();
            $(this).hide();
        });
        
        helpGroups($("#helpGroup").val());
        
        var forms = $('#help-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('help-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });   
    });    
</script>