<?php
$this->headTitle('Вход');

$this->mainMenu()->setActiveItemId('login');

$form->get('ident')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email или телефон',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Password',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<div class="row">
    <div class="col-md-offset-4 col-md-3">
        <p class="text-center">
            <form class="form-signin" method="post">
                <h2 class="form-signin-heading">Вход</h2>
                <?php if ($isLoginError): ?>
                <div class="alert alert-warning" role="alert">
                    Неверный логин и / или пароль. 
                    <a href="<?= $this->url('reset-password') ?>">Забыли пароль?</a>
                </div>
                <?php endif; ?>
                <?= $this->formLabel($form->get('ident')); ?>
                <?= $this->formElement($form->get('ident')); ?>
                <?= $this->formLabel($form->get('password')); ?>
                <?= $this->formElement($form->get('password')); ?>
                <div class="checkbox">
                    <label>
                        <?= $this->formElement($form->get('remember_me')); ?> Запомнить
                    </label>
                </div>
                <?= $this->formElement($form->get('redirect_url')); ?>
                <?= $this->formElement($form->get('csrf')) ?>
                <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
            </form>
        </p>
    </div>
</div>