<?php
    $this->headTitle('Каталог');
    $this->mainMenu()->setActiveItemId('shop');
    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Каталог'=>$this->url('shop'),
                ]);
?>    

<form method="GET" action=""id="shop_index_form_search">
    <div class="container">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div id="imaginary_container"> 
                    <div class="input-group stylish-input-group" id="shop_index_form_search_name_div">
                        <input type="text" name="q" id="shop_index_form_search_name_q" class="form-control" placeholder="Поиск" value="<?= $search?>">
                        <span class="input-group-addon">
                            <? if ($search): ?>
                                <button onmousedown="$('#shop_index_form_search_name_q').val('');document.getElementById('shop_index_form_search').submit()">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </button>  
                           <? endif; ?>
                            <button type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>  
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Наименование</th>
        <th>Артикул</th>
        <th>Производитель</th>
        <th>Цена</th>
        <th>Количество</th>
        <th>Купить</th>
        <th></th>
    </tr>
    
    <?php foreach ($goods as $row): ?>
    <?php 
        $price = $this->goodsManager->getMaxPrice($row);
        $inCart = $this->shopManager->getGoodInCart($row->getId());
        $avialable = $price>0;
    ?>
    <tr>
        <td><?= $this->escapeHtml($row->getId()); ?></td>
        <td>
            <a href="<?= $this->url('goods', ['action'=>'view', 'id'=>$row->getId()]); ?>">
                <?= $this->escapeHtml($row->getName()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($row->getCode()); ?></td>        
        <td><?= $this->escapeHtml($row->getProducer()->getName()); ?></td>        
        <td><?= $price; ?></td>        
        <td>
            <input type="text" id="num<?= $row->getId()?>" value="1" class="form-control" <?= ($avialable) ? '':'disabled' ?>/>
        </td>
        <td>
            <button type="button" class="btn <?= ($inCart ? 'btn-success':'btn-default') ?> btn-default" aria-label="Left Align" id="shop_index_add_cart_<?= $row->getId()?>" 
                    onclick="addCart({
                                good: <?= $row->getId()?>, 
                                price: <?= $price; ?>
                    })"
                     <?= ($avialable) ? '':'disabled' ?>
             >
                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true">
                </span>
            </button>
        </td>
        <td>
<!--            <span class="<?= ($inCart ? 'badge':'') ?> btn-success" id="shop_index_add_cart_badge<?= $row->getId()?>">
                <?= ($inCart ? $inCart:'') ?>
            </span>-->
        </td>
    </tr>
        
    <?php endforeach; ?>   
    
</table>
<?= $this->paginationControl($goods,
            'Sliding',
            'application/partial/paginator', 
            ['route' => array('route' => 'shop', 'q' => $search)]); ?>


<script type="text/javascript">
    var addCart = function(data){
        data.num = $('#num'+data.good).val();
        $.post(
            '/shop/add-cart',
            data,
            addCartSuccess
        );
    };
    
    function addCartSuccess(data)
    {
        if (data.num){  
            $('#nav_cart_badge').html(data.num);
        }  
        if (data.good){
            $('#shop_index_add_cart_'+data.good).removeClass('btn-default');
            $('#shop_index_add_cart_'+data.good).addClass('btn-success');
        }
    }
</script>