<?php
    $this->headScript()->appendFile('/js/typeahead.js/typeahead.jquery.min.js', 'text/javascript');
?>    

<form method="GET" action=""id="shop_index_form_search">
    <div class="container">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div id="imaginary_container"> 
                    <div class="input-group stylish-input-group">
                        <input type="text" name="q" id="shop_index_form_search_name_q" class="form-control" placeholder="Поиск" value="<?= $search?>">
                        <span class="input-group-addon">
                            <? if ($search): ?>
                                <button onmousedown="$('#shop_index_form_search_name_q').val('');document.getElementById('shop_index_form_search').submit()">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </button>  
                           <? endif; ?>
                            <button type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>  
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <?php if ($currentClient): ?>
               <span class="label label-success">
                    Текущий покупатель: <?= $currentClient->getName(); ?>
               </span>    
            <?php else: ?>
               <span class="alert alert-warning">
                    Текущий клиент для работы в каталоге не установлен
               </span>    
            <?php endif; ?>    
        </div>    
    </div>
</div>    

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Наименование</th>
        <th>Артикул</th>
        <th>Производитель</th>
        <th>Цена</th>
        <th>Количество</th>
        <th>Купить</th>
    </tr>
    
    <?php foreach ($goods as $row): ?>
    <?php 
        $price = $this->goodsManager->getMaxPrice($row); 
        $avialable = $price>0;
    ?>
    <tr>
        <td><?= $this->escapeHtml($row->getId()); ?></td>
        <td>
            <a href="<?= $this->url('goods', ['action'=>'view', 'id'=>$row->getId()]); ?>">
                <?= $this->escapeHtml($row->getName()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($row->getCode()); ?></td>        
        <td><?= $this->escapeHtml($row->getProducer()->getName()); ?></td>        
        <td><?= $price; ?></td>        
        <td>
            <input type="text" id="num<?= $row->getId()?>" value="1" class="form-control" <?= ($avialable) ? '':'disabled' ?>/>
        </td>
        <td>
            <button type="button" class="btn btn-default" aria-label="Left Align" 
                    onclick="addCart({
                                good: <?= $row->getId()?>, 
                                price: <?= $price; ?>
                    })"
                     <?= ($avialable) ? '':'disabled' ?>
             >
                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
            </button>
        </td>            
    </tr>
        
    <?php endforeach; ?>   
    
</table>
<?= $this->paginationControl($goods,
            'Sliding',
            'application/partial/paginator', 
            ['route' => array('route' => 'shop', 'q' => $search)]); ?>


<script type="text/javascript">
    var addCart = function(data){
        data.num = $('#num'+data.good).val();
        $.post(
            '/shop/add-cart',
            data,
            addCartSuccess
        );
    };
    
    function addCartSuccess(data)
    {
      //alert(data);
    }
        
    $(document).ready(function() { 
        $('input.typehead').typeahead({
           name: 'search_assistent',
            remote: '<?= $this->url('shop', ['action'=>'search-assistant'], ['query' => ['q' => '']]); ?>%QUERY',
            limit : 10
        });
    });
</script>