<?php
    $this->headTitle('Каталог');
    $this->mainMenu()->setActiveItemId('shop');
    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Каталог'=>$this->url('shop'),
                ]);
    
$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
    
?>    

<table  data-pagination="true" data-search="true" data-toggle="table" data-url="/shop/shop-content">
    <thead>
        <tr>
             <th data-field="id" data-type="numeric">ID</th>
             <th data-field="name">Наименование</th>
             <th data-field="code">Артикул</th>
             <th data-field="producer" data-formatter="producerFormatter">Производитель</th>
             <th data-field="num" data-input="1"></th>
         </tr>                
    </thead>
</table>

<script type="text/javascript">
    function producerFormatter(value, row) {
        return value.name;
    }
    
    var addCart = function(data){
        data.num = $('#num'+data.good).val();
        $.post(
            '/shop/add-cart',
            data,
            addCartSuccess
        );
    };
    
    function addCartSuccess(data)
    {
        if (data.num){  
            $('#nav_cart_badge').html(data.num);
        }  
        if (data.good){
            $('#shop_index_add_cart_'+data.good).removeClass('btn-default');
            $('#shop_index_add_cart_'+data.good).addClass('btn-success');
        }
    }
</script>