<?php
$this->headTitle('Атрибуты машин');

$this->mainMenu()->setActiveItemId('make');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Машины'=>$this->url('make')
            ]);

$this->headLink()
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
   // ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css')        
        ;
$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.14.2/extensions/editable/bootstrap-table-editable.min.js')
            ;    

?>
<!--<button value="/make/make-form" class="btn btn-default btn-xs"
        data-toggle="modal" data-target="#modal-dialog" title="Добавить">
    <span class="glyphicon glyphicon-plus" ></span>
</button>           
-->
<h1>Атрибуты машин</h1>
<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
<!--            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>-->
        </div>
        <table id="table" 
            data-toggle="table" 
            data-id-field="id"
            data-url="/car/attribute-types-content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-editable-url="/my/editable/update/path"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                     <th data-field="name" data-sortable="true">Наименование</th>
                     <th data-field="title" data-sortable="true">Выводимое</th>
                     <th data-field="nameApl" data-editable="true" data-editable-emptytext="Custom empty text.">для АПЛ</th>             
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
        </div>
    </div>
</div>    

<script type="text/javascript">
    
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var $table = $('#table'),
        $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }

        
        return params;
    }
//    
//    function editableFormatter(value, row){
//        return [
//            '<a href="#" class="aplNameEdit" data-type="text" data-pk="1" data-name="firstname" data-url="post.php">' + value + '</a>'
//        ].join(''); 
//    }    
        
    function responseHandler(res) {
        return res;
    }    
</script>
