<?php
use Zp\Entity\Position;

$form = $this->form;

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('aplId')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('company')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('kind')->setAttributes([
    'class'=>'form-control', 
//    'disabled' => ($position) ? empty($position->getParentPosition()):true,
    ]);

$form->get('num')->setAttributes([
    'class'=>'form-control', 
    'disabled' => ($position) ? empty($position->getParentPosition()):true,
    ]);

$form->get('parentPosition')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'position-submit']);

$form->prepare();

?>


<?= $this->form()->openTag($form); ?>
            
<div class="modal-header">
    <h5 class="modal-title" id="stModalLabel">Штатная должность</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
            
<div class="modal-body">
    <div class="row">
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('aplId')); ?>
                <?= $this->formElement($form->get('aplId')); ?>
                <?= $this->formElementErrors($form->get('aplId')); ?>                  
            </div>
        </div>    
        <div class="col-xs-6">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('company')); ?>
                <?= $this->formElement($form->get('company')); ?>
                <?= $this->formElementErrors($form->get('company')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-8">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('kind')); ?>
                <?= $this->formElement($form->get('kind')); ?>
                <?= $this->formElementErrors($form->get('kind')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-8">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('parentPosition')); ?>
                <?= $this->formElement($form->get('parentPosition')); ?>
                <?= $this->formElementErrors($form->get('parentPosition')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('num')); ?>
                <?= $this->formElement($form->get('num')); ?>
                <?= $this->formElementErrors($form->get('num')); ?>                  
            </div>
        </div>    
    </div>        
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?= $this->formLabel($form->get('comment')); ?>
                <?= $this->formElement($form->get('comment')); ?>
                <?= $this->formElementErrors($form->get('comment')); ?>                  
            </div>                        
        </div>                                            
    </div>        

</div>

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary" id="position-submit">Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script>
    function submitForm(){
        var data = serializeForm('#position-form');
        $.ajax({
            type: 'POST',
            url: '/position/edit-form/<?= ($position) ? $position->getId():"" ?>?company='+$('#companySelectForm').val(),
            data: $.param(data)
        })
            .done(function (data) {
//                console.log(data);
                if (data == 'ok'){
                    $('#positionModal').modal('hide');
                    if ($('#table').length){
                        $('#table').bootstrapTable('refresh');
                    }    
                } else {
                    $('#positionModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };

    function positionList(){
        //alert(11);
        $.getJSON( '/position/select/?company='+$('#companySelectForm').val(), function( data ) {
            $('#positionSelectForm').empty();
            $('#positionSelectForm').append('<option>это группа</option>');
            $.each( data.rows, function( key, value ) {
                $('#positionSelectForm').append('<option value="' + key + '">' + value.name + '</option>');
            });
        });    
    }

    $( document ).ready(function() {
        
        $(document).on('change', '#companySelectForm', function (e) {
            positionList();
        });
        
        $(document).on('change', '#positionSelectForm', function (e) {
            $('#num').prop('disabled', !$.isNumeric($('#positionSelectForm').val()));
            $('#kind').prop('disabled', $.isNumeric($('#positionSelectForm').val()));
        });
        
        var forms = $('#position-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('position-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });        
    });        
</script>