<?php
use Application\Entity\Raw;

$this->headTitle('Прайсы загруженные');

$this->mainMenu()->setActiveItemId('raw');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Очередь'=>$this->url('price', ['action' => 'queue']),
            'Прайсы загруженные' => $this->url('raw'),
            ]);  
?>

<div class="row">
    <div class="col-md-9">
        
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select style="width: 200px" class="form-control" id='rawStatusSelect' name="rawStatusSelect">
                        <option>Все</option>
                        <?php foreach ($rawStatuses as $key => $value):?>
                        <option value="<?= $value['status']?>" <?= ($value['status'] == Raw::STATUS_PARSED) ? 'selected':'' ?>><?= $value['name']?></option>
                        <?php endforeach;?>
                    </select>
                    <select style="width: 200px" class="form-control" id='rawStageSelect' name="rawStageSelect">
                        <option selected>Все</option>
                        <?php foreach ($rawStages as $key => $value):?>
                            <option value="<?= $value['stage']?>"><?= $value['name']?></option>
                        <?php endforeach;?>
                    </select>
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/raw/content"
            data-cookie="true"
            data-cookie-id-table="rawSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric">ID</th>
                     <th data-field="supplier" data-formatter="supplierFormatter">Поставщик</th>
                     <th data-field="filename"  data-formatter="filenameFormatter">Файл</th>
                     <th data-field="rows">Строк</th>
                     <th data-field="status" data-formatter="statusExStageFormatter">Состояние</th>
                     <th data-field="dateCreated" data-formatter="dateCreatedFormatter">Дата</th>
                     <th data-field="" data-formatter="activeFormatter"></th>
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="pull-left">
                            Прайсы
                        </div>    
                        <div class="pull-right">     
<!--                            <button value="/raw/delete-old-raws" class="btn btn-default btn-xs refresh-button"
                                    title="Удаление старых прайсов">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>-->
                        </div>    
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left" id="statusCountName">
                            <?php foreach($rawStatuses as $rawStatus):?>
                                <?= $rawStatus['name']?><br/>                                
                            <?php endforeach;?>
                        </div>
                        <div class="pull-right text-right" id="statusCountCount">
                            <?php $totalRawStatusCount = 0?>
                            <?php foreach($rawStatuses as $rawStatus):?>
                                <?= $rawStatus['status_count']?><br/>                                
                                <?php $totalRawStatusCount += $rawStatus['status_count']?>
                            <?php endforeach;?>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-footer">
                        <div class="pull-left">
                            Всего:     
                        </div>
                        <div class="pull-right text-right" id="totalStatusCount">
                            <?= $totalRawStatusCount; ?>                        
                        </div>    
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Строки прайсов                       
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left" id="rowCountName">
                            <?php foreach($rawStatuses as $rawStatus):?>
                                <?php if ($rawStatus['row_count']): ?>
                                    <?= $rawStatus['name']?><br/>                                
                                <?php endif; ?>    
                            <?php endforeach;?>
                        </div>
                        <div class="pull-right text-right" id="rowCountCount">
                            <?php $totalRowStatusCount = 0?>
                            <?php foreach($rawStatuses as $rawStatus):?>
                                <?php if ($rawStatus['row_count']): ?>
                                    <?= $rawStatus['row_count']?><br/>                                
                                    <?php $totalRowStatusCount += $rawStatus['row_count']?>
                                <?php endif; ?>    
                            <?php endforeach;?>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-footer">
                        <div class="pull-left">
                            Всего:     
                        </div>
                        <div class="pull-right text-right" id="totalRowCount">
                            <?= $totalRowStatusCount ?>
                        </div>    
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Стадии разборки                       
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left" id="stageCountName">
                            <?php foreach($rawStages as $rawStage):?>
                                <?php if ($rawStage['row_count']): ?>
                                    <?= $rawStage['name']?><br/>                                
                                <?php endif; ?>    
                            <?php endforeach;?>
                        </div>
                        <div class="pull-right text-right" id="stageCountCount">
                            <?php $totalRowStageCount = 0?>
                            <?php foreach($rawStages as $rawStage):?>
                                <?php if ($rawStage['row_count']): ?>
                                    <?= $rawStage['row_count']?><br/>                                
                                    <?php $totalRowStageCount += $rawStage['row_count']?>
                                <?php endif; ?>    
                            <?php endforeach;?>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-footer">
                        <div class="pull-left">
                            Всего:     
                        </div>
                        <div class="pull-right text-right" id="totalStageCount">
                            <?= $totalRowStageCount ?>                                                   
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>

<script type="text/javascript">
    var $table = $('#table');
    
    $table.bootstrapTable({
        onLoadSuccess: function (data){
            statUpdate();
        }
    });    

    function stat(data){
        var names1 = ''; var names2 = ''; var values1 = ''; var values2 = '';
        var names3 = ''; var values3 = ''; var status3Count = 0;
        var totalStatus = 0; var totalRow = 0; var totalStage = 0;
        $.each(data['rawStatuses'], function( index, value ) {
            if (value['status_count'] > 0){
                names1 += value['name']+'<br/>';
                values1 += value['status_count'] + '<br/>';
                if (value['status'] == 3){
                    status3Count = Math.round(value['status_count']);
                }
            }    
            if (value['row_count'] > 0){
                names2 += value['name']+'<br/>';
                if (value['status'] == 7){
                    var textInfo = 'success';
                    if (Math.round(value['row_count']) > status3Count*8){
                        textInfo = 'warning';
                    }    
                    if (Math.round(value['row_count']) > status3Count*10){
                        textInfo = 'danger';
                    }    
                    values2 += '<span class=text-'+textInfo+'>'+ value['row_count'] +'</span><br/>';                    
                } else {
                    values2 += value['row_count'] + '<br/>';                    
                }
            }    
            totalStatus += Math.round(value['status_count']);
            totalRow += Math.round(value['row_count']);
        });
        $('#statusCountName').html(names1);
        $('#statusCountCount').html(values1);
        $('#totalStatusCount').html(totalStatus);
        $('#rowCountName').html(names2);
        $('#rowCountCount').html(values2);
        $('#totalRowCount').html(totalRow);

        $.each(data['rawStages'], function( index, value ) {
            if (value['row_count'] > 0){
                names3 += value['name']+'<br/>';
                values3 += value['row_count'] + '<br/>';
            }    
            totalStage += Math.round(value['row_count']);
        });
        $('#stageCountName').html(names3);
        $('#stageCountCount').html(values3);
        $('#totalStageCount').html(totalStage);
    }
    
    function statUpdate(){    
        $.ajax({
            url: '/raw/status-content',
            success: function (data) {
                stat(data);
            }
        });        
    }

    $(function () {
        $('#rawStatusSelect').change(function (){
            $table.bootstrapTable('selectPage', 1);
        });
        $('#rawStageSelect').change(function (){
            $table.bootstrapTable('selectPage', 1);
        });
    });
    
    function queryParams(params) {
        $('#toolbar').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }            
        params.status = $('#rawStatusSelect').val();
        params.stage = $('#rawStageSelect').val();
        return params;
    }
    function responseHandler(res) {
        return res;
    }
    
    function activeFormatter(value, row){
        var url = '/raw/delete-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }
    
    function supplierFormatter(value) {
        return '<a href="/supplier/view/'+value.id+'">'+value.name+'</a>';
    }
    
    function filenameFormatter(value, row) {
        return '<a href="/raw/view/'+row.id+'">'+value+'</a>';
    }
    
    function statusFormatter(value, row) {
        switch (value){
            case '2': return 'Удален'; 
            case '3': return 'Разобран'; 
            case '4': return 'Загружается'; 
            case '5': return 'Разбирается'; 
            case '6': return 'Не удалось загрузить<br/><small style="color:red">'+row.name+'</small>'; 
            case '7': return 'Устарел'; 
            default: return 'Новый';    
        }
    }
    
    function statusStageFormatter(value, row) {
        var status = statusFormatter(value, row);
        var stage = '';
        if (value == '3'){
            switch (row.parseStage){
                case '1': stage = 'Производители не разобраны'; break;
                case '2': stage =  'Производители разобраны'; break;
                case '3': stage =  'Артикулы разобраны'; break;
                case '4': stage =  'Номера разобраны'; break;
                case '5': stage =  'Наименования разобраны'; break;
                case '6': stage =  'Производители собраны'; break;
                case '7': stage =  'Товары собраны'; break;
                case '8': stage =  'Цены пересчитаны'; break;
                case '9': stage =  'Токены товаров разобраны'; break;
                case '10': stage =  'Группы наименований разобраны'; break;
                case '11': stage =  'Описания обновлены'; break;
                case '12': stage =  'Наименования обновлены'; break;
                default: stage =  'Неизвестно';                  
            }
        }    
        return (stage) ? stage:status;
    }
    
    function statusExStageFormatter(value, row) {
        var stage = statusStageFormatter(value, row);
        var statusEx = '';
        switch (row.statusEx){
            case '1': statusEx = '<br/> Новый'; break;
            case '2': statusEx =  '<br/> Готов к передаче'; break;
            case '3': statusEx =  '<br/> Передан'; break;
            case '4': statusEx =  '<br/> Готов к удалению'; break;
            case '5': statusEx =  '<br/> Удален'; break;
            default: statusEx =  '<br/> Неизвестно';                  
        }
        return stage;// + statusEx;
    }

    function dateCreatedFormatter(value, row) {
        return value;
    }
    
    var addCart = function(data){
        data.num = $('#num'+data.good).val();
        $.post(
            '/shop/add-cart',
            data,
            addCartSuccess
        );
    };
    
    function addCartSuccess(data)
    {
        if (data.num){  
            $('#nav_cart_badge').html(data.num);
        }  
        if (data.good){
            $('#shop_index_add_cart_'+data.good).removeClass('btn-default');
            $('#shop_index_add_cart_'+data.good).addClass('btn-success');
        }
    }
</script>
