<?php
$this->headTitle('Прайсы загруженные');

$this->mainMenu()->setActiveItemId('raw');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Очередь'=>$this->url('price', ['action' => 'queue']),
            'Прайсы загруженные' => $this->url('raw'),
            ]);  

$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    

?>

<div class="row">
    <div class="col-md-8">
        
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/raw/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric">ID</th>
                     <th data-field="supplier" data-formatter="supplierFormatter">Поставщик</th>
                     <th data-field="filename"  data-formatter="filenameFormatter">Файл</th>
                     <th data-field="rows">Строк</th>
                     <th data-field="status" data-formatter="statusStageFormatter">Состояние</th>
                     <th data-field="dateCreated" data-formatter="dateCreatedFormatter">Дата</th>
                     <th data-field="" data-formatter="activeFormatter"></th>
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-4" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Прайсы                       
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?php $totalRawStatusCount = 0?>
                            <?php foreach($rawStatuses as $rawStatus):?>
                                <?= $rawStatus['status_count']?>: <a href="<?= $this->url('raw', ['action' => 'index'], ['query' => ['status' => $rawStatus['status']]])?>"><?= $rawStatus['name']?></a><br/>                                
                                <?php $totalRawStatusCount += $rawStatus['status_count']?>
                            <?php endforeach;?>
                        </div>
                    </div>
                    <div class="panel-footer">
                        Всего: <?= $totalRawStatusCount; ?><br/>                        
                    </div>
                </div>
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Строки прайсов                       
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?php $totalStatusCount = 0?>
                            <?php foreach($statuses as $status):?>
                                <?= $status['status_count']?>: <?= $status['name']?><br/>                                
                                <?php $totalStatusCount += $status['status_count']?>
                            <?php endforeach;?>
                        </div>
                    </div>
                    <div class="panel-footer">
                        Всего: <?= $totalStatusCount ?><br/>                        
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams() {
        var params = {offset: 0, limit: 10};
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        return params;
    }
    function responseHandler(res) {
        return res;
    }
    
    function activeFormatter(value, row){
        var url = '/raw/delete-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }
    
    function supplierFormatter(value) {
        return '<a href="/supplier/view/'+value.id+'">'+value.name+'</a>';
    }
    
    function filenameFormatter(value, row) {
        return '<a href="/raw/view/'+row.id+'">'+value+'</a>';
    }
    
    function statusFormatter(value, row) {
        switch (value){
            case '2': return 'Удален'; 
            case '3': return 'Разобран'; 
            case '4': return 'Загружается'; 
            case '5': return 'Разбирается'; 
            case '6': return 'Не удалось загрузить<br/><small style="color:red">'+row.name+'</small>'; 
            default: return 'Новый';    
        }
    }
    
    function statusStageFormatter(value, row) {
        var status = statusFormatter(value, row);
        var stage = '';
        if (value == '3'){
            switch (row.parseStage){
                case '1': stage = '<br/> Производители не разобраны'; break;
                case '2': stage =  '<br/> Производители разобраны'; break;
                case '3': stage =  '<br/> Артикулы разобраны'; break;
                case '4': stage =  '<br/> Номера разобраны'; break;
                default: stage =  '<br/> Неизвестно';                  
            }
        }    
        return status+stage;
    }
    
    function dateCreatedFormatter(value, row) {
        return value;
    }
    
    var addCart = function(data){
        data.num = $('#num'+data.good).val();
        $.post(
            '/shop/add-cart',
            data,
            addCartSuccess
        );
    };
    
    function addCartSuccess(data)
    {
        if (data.num){  
            $('#nav_cart_badge').html(data.num);
        }  
        if (data.good){
            $('#shop_index_add_cart_'+data.good).removeClass('btn-default');
            $('#shop_index_add_cart_'+data.good).addClass('btn-success');
        }
    }
</script>
