<?php
$this->headTitle('Прайсы загруженные');

$this->mainMenu()->setActiveItemId('raw');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Очередь'=>$this->url('price', ['action' => 'queue']),
            'Прайсы загруженные' => $this->url('raw'),
            ]);  

?>

<div class="row">
    <div class="col-md-8">
        <table class="table table-striped">

           <tr>
                <th>ID</th>
                <th>Поставщик</th>
                <th>Файл</th>
                <th>Статус</th>
                <th>Дата</th>
                <th>Действие</th>
            </tr>

            <?php foreach ($raws as $row): ?>

            <tr>
                <td>
                        <?= $this->escapeHtml($row->getId()); ?>
                </td>
                <td>
                    <a href="<?= $this->url('supplier', ['action' => 'view', 'id' => $row->getSupplier()->getId()])?>">
                        <?= $this->escapeHtml($row->getSupplier()->getName()); ?>
                    </a>
                </td>
                <td>
                    <a href="<?= $this->url('raw', ['action'=>'view', 'id'=>$row->getId()]); ?>">            
                        <?= $this->escapeHtml($row->getBasename()); ?>
                    </a>    
                </td>
                <td><?= $this->escapeHtml($row->getStatusAsString()); ?></td>
                <td><?= $this->escapeHtml($row->getDateCreated()); ?></td>
                <td>
                    <button value="/raw/delete-form/<?= $row->getId() ?>" class="btn btn-danger btn-xs this-delete"
                            title="Удалить">
                        <span class="glyphicon glyphicon-remove" ></span>
                    </button>                                                           
                </td>    
            </tr>

            <?php endforeach; ?>   

        </table>
        <?= $this->paginationControl($raws,
                    'Sliding',
                    'application/partial/paginator', 
                    ['route' => array('route' => 'raw')]); ?>
        
    </div>
    <div class="col-md-4">
    </div>    
</div>


