<?php
$this->headTitle('Прайс '.$raw->getSupplier()->getName());

$this->mainMenu()->setActiveItemId('raw');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Прайсы'=>$this->url('raw'),
            $raw->getBasename() => $this->url('raw', ['action'=>'view', 'id' => $raw->getId()])
            ]);  

?>

<h1>
    <?= $this->escapeHtml($raw->getSupplier()->getName().' прайс '. $raw->getBasename()); ?>    
</h1>


<h3 class="contact-header">Данные из файла</h3>


<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Данные</th>
        <th>Действие</th>
    </tr>
    
    <?php foreach ($rawprice as $row): ?>
    
    <tr>
        <td>
            <a href="<?= $this->url('rawprice', ['action'=>'view', 'id'=>$row->getId()]); ?>">            
                <?= $this->escapeHtml($row->getId()); ?>
            </a>    
        </td>
        <td>
        <?php 
            $rawdates = $row->getRawdataAsArray();
            $i = 0;
        ?>
        <?php foreach ($rawdates as $rawdata): ?>
            <?php $i++ ?>
            <div>
                <b><?= $i?>:</b><?= $this->escapeHtml($rawdata); ?>
            </div>
        <?php endforeach; ?>    
        </td>    
        <td>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>
<?= $this->paginationControl($rawprice,
            'Sliding',
            'application/partial/paginator', 
            ['route' => array('route' => 'raw', 'action' => 'view', 'id' => $raw->getId())]); ?>
