<?php
$this->headTitle('Add User');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            'Add User'=>$this->url('users', ['action'=>'add'])
            ]);

$form->get('aplId')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ]);

$form->get('mailPassword')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('sign')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'John Doe'
    ]);

$form->get('birthday')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter password',
    ]);

$form->get('confirm_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Retype password',
    ]);

$form->get('roles')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('office')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h1>Add User</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('aplId')); ?>
            <?= $this->formElement($form->get('aplId')); ?>
            <?= $this->formElementErrors($form->get('aplId')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('birthday')); ?>
            <?= $this->formElement($form->get('birthday')); ?>
            <?= $this->formElementErrors($form->get('birthday')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('office')); ?>
            <?= $this->formElement($form->get('office')); ?>
            <?= $this->formElementErrors($form->get('office')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('roles')); ?>
            <?= $this->formElement($form->get('roles')); ?>
            <?= $this->formElementErrors($form->get('roles')); ?>                  
        </div>
        <?= $this->formElement($form->get('submit')); ?>
    </div>
    <div class="col-md-6">
        <div class="form-group form-inline">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                  

            <?= $this->formLabel($form->get('mailPassword')); ?>
            <?= $this->formElement($form->get('mailPassword')); ?>
            <?= $this->formElementErrors($form->get('mailPassword')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('sign')); ?>
            <?= $this->formElement($form->get('sign')); ?>
            <?= $this->formElementErrors($form->get('sign')); ?>                  
        </div>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

<script>
    $( document ).ready(function() {
        $('textarea[name="sign"]').summernote({
            lang: 'ru-RU', // default: 'en-US'
            height: 200
        });
        
    });
</script>