<?php
$this->headTitle('Edit User');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            'Edit User'=>$this->url('users', ['action'=>'edit', 'id'=>$user->getId()])
            ]);

$form->get('aplId')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ]);

$form->get('mailPassword')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('sign')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'John Doe'
    ]);

$form->get('birthday')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('zpRs')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('zpBik')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('inn')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('fio')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('roles')->setAttributes([
    'class'=>'form-control',
    'style' => 'height: 220px',
    ]);

$form->get('office')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Сохранить');

$form->prepare();
?>


<h1>Edit User <?= $this->escapeHtml($user->getEmail()) ?></h1>

<?= $this->form()->openTag($form); ?>

<div class="row">
    <div class="col-md-6">
        
        <div class="form-group">
            <?= $this->formLabel($form->get('aplId')); ?>
            <?= $this->formElement($form->get('aplId')); ?>
            <?= $this->formElementErrors($form->get('aplId')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('birthday')); ?>
            <?= $this->formElement($form->get('birthday')); ?>
            <?= $this->formElementErrors($form->get('birthday')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('office')); ?>
            <?= $this->formElement($form->get('office')); ?>
            <?= $this->formElementErrors($form->get('office')); ?>                  
        </div>
        
        <div class="form-group form-inline">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                  

            <?= $this->formLabel($form->get('mailPassword')); ?>
            <?= $this->formElementErrors($form->get('mailPassword')); ?>                  
            <div class="input-group">
                <?= $this->formElement($form->get('mailPassword')); ?>
                <span class="input-group-btn">
                    <button class="btn btn-default password-generator" type="button" data-toggle="tooltip" data-placement="top" title="Генератор пароля">
                        <span class="glyphicon glyphicon-qrcode"></span>
                    </button>
                </span>                                                            
            </div>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('sign')); ?>
            <?= $this->formElement($form->get('sign')); ?>
            <?= $this->formElementErrors($form->get('sign')); ?>                  
        </div>
        
    </div>    
    <div class="col-md-6">    
        <div class="form-group">
            <?= $this->formLabel($form->get('fio')); ?>
            <?= $this->formElement($form->get('fio')); ?>
            <?= $this->formElementErrors($form->get('fio')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('inn')); ?>
            <?= $this->formElement($form->get('inn')); ?>
            <?= $this->formElementErrors($form->get('inn')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('zpRs')); ?>
            <?= $this->formElement($form->get('zpRs')); ?>
            <?= $this->formElementErrors($form->get('zpRs')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('zpBik')); ?>
            <?= $this->formElement($form->get('zpBik')); ?>
            <?= $this->formElementErrors($form->get('zpBik')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('roles')); ?>
            <?= $this->formElement($form->get('roles')); ?>
            <?= $this->formElementErrors($form->get('roles')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
    </div>
    <div class="row">
        <div class="col-md-12">

        </div>    
    </div>    
</div>   
<?= $this->form()->closeTag(); ?>

<script>
    $( document ).ready(function() {
        $('textarea[name="sign"]').summernote({
            lang: 'ru-RU', // default: 'en-US'
            height: 200
        });
        
    });
    
    $('.password-generator').on('click', function() {
        $.ajax({
            type: 'GET',
            url: '/admin/password-generator/'
        })
            .done(function (data) {
                if (data){
                    $('input[name=mailPassword]').val(data['password']);
                }
            })
            .fail(function (e) {
                console.log(e);
            });    
    });    
    
</script>