<?php
use User\Entity\User;

$this->headTitle('Сотрудники');

$this->mainMenu()->setActiveItemId('users');
$this->mainMenu()->setActiveUrl($this->url('users'));

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Сотрудники'=>$this->url('users'),
            ]);

?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <a class="btn btn-default" type="button" href="<?= $this->url('users', ['action'=>'add']); ?>" target="_blank">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Добавить
                </a>                
                <div class="form-group">
                    <select id="officeSelect" style="width: 200px" class="form-control refresh-table" name="office">
                        <option>Все офисы</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="statusSelect" style="width: 200px" class="form-control refresh-table" name="status">
                        <option>Все</option>
                        <?php foreach (User::getStatusList() as $status=>$value):?>
                            <option value="<?= $status?>" <?= ($status == User::STATUS_ACTIVE) ? 'selected':'' ?>><?= $value?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/users/content"
            data-cookie="true"
            data-cookie-id-table="usersSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-unique-id="id"
            data-row-style="rowStyle"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true" data-formatter="idFormatter" data-width="80">Id</th>
                     <th data-field="dateCreated" data-sortable="true" data-formatter="dateFormatter" data-width="80">Дата</th>
                     <th data-field='fullName' data-sortable="true" data-formatter="linkFormatter">ФИО</th>
                     <th data-field='phones' data-sortable="false">Телефон</th>
                     <th data-field='email' data-sortable="false">Email</th>
                     <th data-field='officeName' data-sortable="false">Офис</th>
                     <th data-field='roles' data-sortable="false">Права</th>
                     <th data-field='statusAsString' data-sortable="false">Статус</th>
                     <th data-field="" data-formatter="activeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    var $table = $('#table');        
    var $ok = $('#ok');
    
    var curentRowIndex = -1;
    
    function setCurrentIndex(index){
        curentRowIndex = index;
    }

    function getCurrentIndex(){
        return curentRowIndex;
    }    
    
    function refreshTable(){
        $table.bootstrapTable('selectPage', 1);
    }
    
    $(function () {
        $('#ok').click(function () {
            refreshTable();
        });

        $(document).on('change', '.refresh-table', function (e) {
            refreshTable();
        });
        
    });
    
    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status == '<?= User::STATUS_RETIRED?>'){
           retired += ' retired-muted';
        }
        
        return {classes: retired};
    }
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
        
    function idFormatter(value, row){
        if (row.aplId > 0){
            return '<nobr>'+value+' ('+row.aplId+')</nobr>';
        }
        return value;
    }    

    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/users/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }
    
    function activeFormatter(value, row){
        var btn = '<nobr>';

        var url = '/users/edit/'+row.id;
        btn += '<a';
        btn += ' type="button"';
        btn += ' class="btn btn-info btn-xs"';
        btn += ' aria-label="Left Align"'; 
        btn += ' href="'+url+'" target="_blank" title="Изменить">';
        btn += '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>';
        btn += '</a>';

        var url = '/users/change-password/'+row.id;
        btn += ' <a';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs"';
        btn += ' aria-label="Left Align"'; 
        btn += ' href="'+url+'" target="_blank" title="Сменить пароль">';
        btn += '<span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>';
        btn += '</a>';

        var url = '/users/delete/'+row.id;
        btn += ' <button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>';
        btn += '</button>';
        
        btn += '</nobr>';
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }
    
    function changeStatus(userId, status){
        $.get( "/users/status/"+userId+'?status='+status, function(data){
            $table.bootstrapTable('updateByUniqueId', {id: userId, row: data});
        });        
    }
    
    var menu = new BootstrapMenu('.tablerow', {
        fetchElementData: function(rowElem) {
            setCurrentIndex($(rowElem).attr('data-index'));
            return $table.bootstrapTable('getData')[getCurrentIndex()];
        },
        actionsGroups: [
           ['statusActiv', 'statusRetired']
        ],      
        actions: {
            statusActiv: {
                name: 'Сделать активным',
                iconClass: 'glyphicon glyphicon-ok',
                onClick: function(row) {
                    changeStatus(row.id, <?= User::STATUS_ACTIVE?>);
                },
                isShown: function(row) {
                  return row.status == <?= User::STATUS_RETIRED?>;
                }
            }, 
            statusRetired: {
                name: 'Сделать не активным',
                iconClass: 'glyphicon glyphicon-remove',
//                classNames: 'bg-danger',
                onClick: function(row) {
                    changeStatus(row.id, <?= User::STATUS_RETIRED?>);
                },
                isShown: function(row) {
                  return row.status == <?= User::STATUS_ACTIVE?>;
                }
            }
        }
    });            
</script>
