<?php
$this->headTitle('Сотрудники');

$this->mainMenu()->setActiveItemId('users');
$this->mainMenu()->setActiveUrl('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            ]);
?>

<h1>Сотрудники</h1>

<p>
<a class="btn btn-default" href="
    <?= $this->url('users', ['action'=>'add']); ?>" target="_blank">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New User
</a>
</p>
<div class="row">
    <div class="col-md-12">
        <table id="table" 
            data-toggle="table" 
            data-url="/users/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true" data-formatter="idFormatter" data-width="80">Id</th>
                     <th data-field="dateCreated" data-sortable="true" data-formatter="dateFormatter" data-width="80">Дата</th>
                     <th data-field='fullName' data-sortable="true">ФИО</th>
                     <th data-field='phone' data-sortable="false">Телефон</th>
                     <th data-field='email' data-sortable="false">Email</th>
                     <th data-field='office.name' data-sortable="false">Офис</th>
                     <th data-field='role' data-sortable="false">Права</th>
                     <th data-field='statusAsString' data-sortable="false">Статус</th>
                     <th data-field="" data-formatter="activeFormatter"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>APL ID</th>
        <th>E-mail</th>
        <th>Full Name</th>
        <th>Role(s)</th>        
        <th>Офис</th>        
        <th>Date Created</th>
        <th>Status</th>        
        <th>Actions</th>        
    </tr>
    
    <?php foreach ($users as $user): ?>
    
    <tr>
        <td><?= $this->escapeHtml($user->getId()); ?></td>
        <td><?= $this->escapeHtml($user->getAplId()); ?></td>
        <td>
            <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                <?= $this->escapeHtml($user->getEmail()); ?>
            </a> 
        </td>
        <td>
            <?= $this->escapeHtml($user->getFullName()); ?> 
        </td>
        <td>
            <?= $this->escapeHtml($user->getRolesAsString()); ?> 
        </td>
        <td>
            <?php if ($user->getOffice()):?>
                <a href="<?= $this->url('offices', ['action'=>'view', 'id'=>$user->getOffice()->getId()]); ?>">
                    <?= $this->escapeHtml($user->getOffice()->getName()); ?>
                </a> 
            <?php endif;?>
        </td>
        <td><nobr><?= $this->escapeHtml($user->getDateCreated()); ?></nobr></td>        
        <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('users', 
                    ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
            <a class="btn btn-default" href="<?= $this->url('users',
                    ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> Change Password
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

<script type="text/javascript">
    var $table = $('#table');        
    var $ok = $('#ok');
    
    function refreshTable(){
        $table.bootstrapTable('selectPage', 1);
    }
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.status = $('#statusSelect').val();
        
        return params;
    }
        
    function idFormatter(value, row){
        if (row.aplId > 0){
            return '<nobr>'+value+' ('+row.aplId+')</nobr>';
        }
        return value;
    }    
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }
    
    function responseHandler(res) {
        return res;
    }    
</script>
