<?php
$this->headTitle('Спасибо');
?>

<div class="row">
<div class="col-md-offset-4 col-md-5">
<h1>Сброс пароля</h1>

<?php if ($id=='sent'): ?>
<p>
    На ваш адрес электронной почты была отправлена ссылка для сброса пароля.
</p>
<?php elseif ($id=='invalid-email'): ?>
<p>
    Нет такого пользователя с таким адресом электронной почты.
</p>
<?php elseif ($id=='set'): ?>
<p>
    Ваш новый пароль был успешно установлен.
</p>
<p>
    Вернуться на <a href="<?= $this->url('login'); ?>">страницу входа</a>.
</p>
<?php elseif ($id=='failed'): ?>

    Неверный ключ сброса или он может истек. Пожалуйста, вернитесь 
    <a href="<?= $this->url('reset-password') ?>">here</a> и попробуйте снова сбросить пароль.
</p>
<?php endif; ?>
</div>
</div>    