<?php
$this->headTitle('Сброс пароля');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email address'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
    ]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2>Сброс пароля</h2>

        <p>Введите свой адрес электронной почты ниже, чтобы сбросить пароль.</p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>                              

        <?= $this->formElement($form->get('captcha')); ?>
        <p class="hint">Введите буквы выше, как вы их видите.</p>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
