<?php
$this->headTitle('Сброс пароля');

$form->get('phone')->setAttributes([
    'class'=>'form-control', 
    'id' => 'reset_phone',
    'placeholder'=>'8 (000) 000-0000',
    ]);

$form->get('token')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Код из SMS'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
    ]);

$form->prepare();

$this->headScript()
            ->appendFile($this->basePath('js/jquery.mask.min.js'))
        ;

?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2>Сброс пароля</h2>
        <div class="alert alert-warning" role="alert"> 
            <a href="<?= $this->url('reset-password') ?>">Сброс пароля с помощью Email</a>
        </div>

        <p>Введите номер телефона и код из SMS, чтобы сбросить пароль.</p>

        <div class="input-group">
            <?= $this->formElement($form->get('phone')); ?>
            <?= $this->formElementErrors($form->get('phone')); ?>                              
            <div class="input-group-btn">
                <button class="btn btn-default" type="button" onclick="this.disabled=true; sms()">SMS</button>    
            </div>    
        </div>        

            <?= $this->formElement($form->get('token')); ?>
            <?= $this->formElementErrors($form->get('token')); ?>                              

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<script>
    $('#reset_phone').mask('8 (000) 000-0000', {selectOnFocus: false});

    var sms = function(){
        var data = {phone: $('#reset_phone').val()};
        $.post(
            '/sms-token',
            data,
            smsSuccess
        );
    };
    
    function smsSuccess(data)
    {
        alert(data.msg);
    }
    
</script>    
