<?php
$this->headTitle('View User');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
            ]);

$legalContact = $user->getLegalContact();
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View User <?= $this->escapeHtml($user->getEmail()) ?></h1>

<p>
    <a class="btn btn-default" href="<?= $this->url('users', 
            ['action'=>'edit', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Edit
    </a>
    <a class="btn btn-default" href="<?= $this->url('users',
            ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-asterisk"></span> Change Password
    </a>    
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Full Name:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
            <tr>
                <th>Основной офис</th>
                <td>
                    <a href="<?= $this->url('offices', ['action'=>'view', 'id'=>$user->getOffice()->getId()]); ?>">
                        <?= $this->escapeHtml($user->getOffice()->getName()); ?>
                    </a> 
                </td>
            </tr>
            <tr>
                <th>Roles:</th>
                <td><?= $this->escapeHtml($user->getRolesAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>

<div class="panel panel-success">
    <div class="panel-heading">Контакты</div>
    <div class="panel-body">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="pull-left">
                        <h3 class="panel-title">Телефон</h3>
                    </div>                                
                    <div class="pull-right">
                        <?php if ($legalContact):?>
                            <button value="/contact/phone-form/<?= $legalContact->getId() ?>" class="btn btn-default btn-xs"
                                    data-toggle="modal" data-target="#modal-dialog" title="Добавить телефон">
                                <span class="glyphicon glyphicon-plus" ></span>
                            </button>
                        <?php endif?>
                    </div>                                
                    <div class="clearfix"></div>
                </div>
                <?php foreach ($user->getContacts() as $contact): ?>
                    <?php foreach ($contact->getPhones() as $phone): ?>
                        <div class="panel-body">
                            <div class="pull-left"><?= $phone->getName()?> <span><?= $phone->getComment()?></span></div>
                            <div class="pull-right">
                                <button value="/contact/phone-form/<?= $contact->getId() ?>?phone=<?= ($phone ? $phone->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                        data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                    <span class="glyphicon glyphicon-edit" ></span>
                                </button>                                                            
                                <button value="/contact/delete-phone-form/<?= $phone->getId() ?>" class="btn btn-default btn-xs this-delete"
                                        title="Удалить">
                                    <span class="glyphicon glyphicon-remove" ></span>
                                </button>                                                            
                            </div>
                        </div>
                    <?php endforeach?>    
                <?php endforeach;?>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="pull-left">
                        <h3 class="panel-title">Почта</h3>
                    </div>                                
                    <div class="pull-right">
                        <?php if ($legalContact):?>
                            <button value="/contact/email-form/<?= $legalContact->getId() ?>" class="btn btn-default btn-xs"
                                    data-toggle="modal" data-target="#modal-dialog" title="Добавить email">
                                <span class="glyphicon glyphicon-plus" ></span>
                            </button>
                        <?php endif;?>
                    </div>                                
                    <div class="clearfix"></div>
                </div>
                <?php foreach ($user->getContacts() as $contact): ?>
                    <?php foreach ($contact->getEmails() as $email): ?>
                        <div class="panel-body">
                            <div class="pull-left"><?= $email->getName()?></div>
                            <div class="pull-right">
                                <button value="/contact/email-form/<?= $contact->getId() ?>?email=<?= ($email ? $email->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                        data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                    <span class="glyphicon glyphicon-edit" ></span>
                                </button>                                                            
                                <button value="/contact/delete-email-form/<?= $email->getId() ?>" class="btn btn-default btn-xs this-delete"
                                        title="Удалить">
                                    <span class="glyphicon glyphicon-remove" ></span>
                                </button>                                                            
                            </div>
                        </div>
                    <?php endforeach?>    
                <?php endforeach;?>
            </div>
        </div>
    </div>
