<?php

$form = $this->form;

$form->get('cost')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('quantity')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('amount')->setAttributes([
    'class'=>'form-control', 
    'data-inputmask' => "'alias': 'currency', 'min': 0, 'groupSeparator': ''"
    ]);

$form->get('price')->setAttributes([
    'class'=>'form-control', 
    'data-inputmask' => "'alias': 'currency', 'min': 0, 'groupSeparator': ''"
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'ptu-cost-submit']);

$form->prepare();

$docName = 'Новый';

?>
            
<?= $this->form()->openTag($form); ?>
            
<div class="modal-header">
    <h5 class="modal-title" id="ptuGoodModalLabel">Строка поступления услуг</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
            
<div class="modal-body">
    <div class="row">
        <div class="col-xs-12">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('comment')); ?>
                <?= $this->formElement($form->get('comment')); ?>
                <?= $this->formElementErrors($form->get('comment')); ?>                  
            </div>
        </div>    
    </div>
    <div class="row">
        <div class="col-xs-12">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('cost')); ?>
                <?= $this->formElement($form->get('cost')); ?>
                <?= $this->formElementErrors($form->get('cost')); ?>                  
            </div>
        </div>    
    </div>
    <div class="row">
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('quantity')); ?>
                <?= $this->formElement($form->get('quantity')); ?>
                <?= $this->formElementErrors($form->get('quantity')); ?>                  
            </div>
        </div>    
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('amount')); ?>
                <?= $this->formElement($form->get('amount')); ?>
                <?= $this->formElementErrors($form->get('amount')); ?>                  
            </div>
        </div>
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('price')); ?>
                <?= $this->formElement($form->get('price')); ?>
                <?= $this->formElementErrors($form->get('price')); ?>                  
            </div>
        </div>
    </div>    

    <?= $this->formElement($form->get('csrf')); ?>
</div>    
                
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="button" class="btn btn-primary" id="ptu-cost-submit">Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script  type="text/javascript">

    $('#ptu-cost-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/ptu/cost-edit-form/',
            data: $('#ptu-cost-form').serialize()
        })
            .done(function (answer) {
//                console.log(answer);
                if (answer.result == 'ok'){
                    var data = serializeForm('#ptu-cost-form');
                    var cost = {
                        id: answer.cost.id,
                        name: answer.cost.name
                    };
                    var row = {
                        cost: cost,
                        comment: data.comment,
                        amount: data.amount,
                        quantity: data.quantity,
                        price: Math.round(data.amount*100/data.quantity)/100
                    };

                    <?php if($rowNo): ?>
                        $('#ptucosttable').bootstrapTable('updateByUniqueId', {id: <?= $rowNo ?>, row: row});
                    <?php else:?>
                        var newRowNo = getNewTableUniqueId('ptucosttable', 'rowNo');
                        row.rowNo = newRowNo;
                        var rows = [];
                        rows.push(row);
                        $('#ptucosttable').bootstrapTable('prepend', rows);                        
                    <?php endif; ?>        
                    ptuUpdateTotal();    
                    
                    $('#ptuCostModal').modal('hide');
                } else {
                    $('#ptuCostModal .modal-content').html(answer);
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });
    });    
    
    $( document ).ready(function() {        
        $("#amount").inputmask();
        $("#price").inputmask();

        $("#price").on('input', function(){
//            var value = $(this).val();
//            $(this).val(value.replace(",","."));
            $("#amount").val(Math.round($(this).val()*$("#quantity").val()*100)/100);
        });
        
        $("#amount").on('input', function(){
//            var value = $(this).val();
//            $(this).val(parseFloat(value.replace(",",".").replace(/\s/g, '')));
            if ($("#quantity").val()){
                $("#price").val(Math.round($(this).val()*100/$("#quantity").val())/100);
            }    
        });
        
        $("#quantity").on('input', function(){
            if ($("#price").val()){
                $("#amount").val(Math.round($(this).val()*$("#price").val()*100)/100);
            } else {
                if ($("#amount").val()){
                    $("#price").val(Math.round($("#amount").val()*100/$(this).val())/100);
                }    
            }    
        });        
    });    
</script>