<?php

$form = $this->form;

$form->get('legal')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('office')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('company')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('supplier')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('contract')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('docDate')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('docNo')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'ptu-submit']);

$form->prepare();

$docName = 'Новый';
if ($ptu){
    $docName = '№ '.$ptu->getDocNo().' от  '.date('d.m.Y', strtotime($ptu->getDocDate()));
}

?>



            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title" id="ptuModalLabel">Поступление товаров <?= $docName?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('docNo')); ?>
                            <?= $this->formElement($form->get('docNo')); ?>
                            <?= $this->formElementErrors($form->get('docNo')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('office')); ?>
                            <?= $this->formElement($form->get('office')); ?>
                            <?= $this->formElementErrors($form->get('office')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('supplier')); ?>
                            <?= $this->formElement($form->get('supplier')); ?>
                            <?= $this->formElementErrors($form->get('supplier')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('status')); ?>
                            <?= $this->formElement($form->get('status')); ?>
                            <?= $this->formElementErrors($form->get('status')); ?>                  
                        </div>
                    </div>
                    <div class="col-xs-2 text-right">
                        <h1 class="display-4" id="ptuQuantity"></h1>
                    </div>    
                    <div class="col-xs-1 text-right">
                        <h1 class="display-4" id="ptuAmount"><?= ($ptu) ? round($ptu->getAmount(), 2):"" ?></h1>                        
                    </div>    
                </div>    
                <div class="row">
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('docDate')); ?>
                            <?= $this->formElement($form->get('docDate')); ?>
                            <?= $this->formElementErrors($form->get('docDate')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('company')); ?>
                            <?= $this->formElement($form->get('company')); ?>
                            <?= $this->formElementErrors($form->get('company')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('legal')); ?>
                            <?= $this->formElement($form->get('legal')); ?>
                            <?= $this->formElementErrors($form->get('legal')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-2">                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('contract')); ?>
                            <?= $this->formElement($form->get('contract')); ?>
                            <?= $this->formElementErrors($form->get('contract')); ?>                  
                        </div>
                    </div>    
                    <div class="col-xs-4 text-right">
                    </div>    
                </div>        
                <div class="row">
                    <div class="col-xs-12">
                        <div id="ptugoodtoolbar">
                            <div class="form-inline" role="form">
                                <button type="button" class="btn btn-default ptu-good-modal-show" modal-url="/ptu/good-edit-form">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                </button>
                            </div>
                        </div>
                        <table id="ptugoodtable" 
                            data-toggle="ptugoodtable" 
                            data-url="/ptu/good-content/<?= ($ptu) ? $ptu->getId():"" ?>"
                            data-side-pagination="client"
                            data-pagination="true"
                            data-page-size = "5"
                            data-page-list="[5, 10, 20, 50]"
                            data-toolbar="#ptugoodtoolbar"
                            data-show-refresh="true"
                            data-show-toggle="true"
                            data-query-params="ptugoodQueryParams"
                            data-response-handler="ptugoodResponseHandler"
                            >
                            <thead>
                                <tr>
                                     <th data-field="rowNo" data-type="numeric" data-align="right">N</th>
                                     <th data-field="good.code" data-type="numeric">Артикул</th>
                                     <th data-field="good.producer.name" data-type="numeric">Производитель</th>
                                     <th data-field="good.name" data-type="numeric">Наименование</th>
                                     <th data-field='amount' data-formatter="pgPriceFormatter" data-align="right">Цена</th>
                                     <th data-field='quantity' data-align="right">Количество</th>
                                     <th data-field='amount' data-align="right">Сумма</th>
                                     <th data-field="id" data-formatter="pgActiveFormatter"></th>
                                 </tr>                
                            </thead>
                        </table>
                    </div>
                </div>    
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('comment')); ?>
                            <?= $this->formElement($form->get('comment')); ?>
                            <?= $this->formElementErrors($form->get('comment')); ?>                  
                        </div>                        
                    </div>                                            
                </div>        




                        <?= $this->formElement($form->get('csrf')); ?>
                    </div>
                </div>
            </div>    
                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="ptu-submit">Сохранить</button>
            </div>
            
            <?= $this->form()->closeTag(); ?>
            
<script>
    $('#ptu-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/ptu/edit-form/<?= ($ptu) ? $ptu->getId():"" ?>',
            data: $('#ptu-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#ptu-modal').modal('hide');
                    window.location.reload();
                } else {
                    $('#ptu-modal-content').html(data);
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });
    });
    
    function contractList(){
        $.getJSON( '/contracts/select/?company='+$('#company').val()+'&legal='+$('#legal').val(), function( data ) {
            $('#contract').empty();
            $.each( data.rows, function( key, value ) {
                $('#contract').append('<option value="' + key + '">' + value.name + '</option>');
            });
        });    
    }
    
    $('#office').on('change', function(){
        $.getJSON( '/offices/legals/'+$('#office').val(), function( data ) {
            $('#company').empty();
            $.each( data.rows, function( key, value ) {
                $('#company').append('<option value="' + key + '">' + value.name + '</option>');
            });
            contractList();
        });    
    });
    
    $('#company').on('change', contractList());
    
    $('#supplier').on('change', function(){
        $.getJSON( '/supplier/legals/'+$('#supplier').val(), function( data ) {
            $('#legal').empty();
            $.each( data.rows, function( key, value ) {
                $('#legal').append('<option value="' + key + '">' + value.name + '</option>');
            });
            contractList();            
        });    
    });
    
    $('#legal').on('change', contractList());
    
    function ptuUpdateTotal(){
        var data = $('#ptugoodtable').bootstrapTable('getData');
        var amount = 0; var quantity = 0;
        $.each(data, function( index, value ) {
            amount += Math.round(value.amount*100)/100;
            quantity += Math.round(value.quantity*100)/100; 
        });
        $('#ptuAmount').html(Math.round(amount*100)/100);
        $('#ptuQuantity').html(Math.round(quantity*100)/100);
    }
    
    $(document).on('click', '.ptu-good-modal-show', function (e) {
     var url = $(e.currentTarget).attr('modal-url');
        showFormDialog({
            id: 'ptuGoodModal',
            url: url,
            zIndex: 9999
        });
    });
     
    $( document ).ready(function() {
        $('#ptugoodtable').bootstrapTable({
            onLoadSuccess: function(res){
                ptuUpdateTotal();
            }            
        });        
    });
    
    function ptuGoodRefreshTable(){
        $('#ptugoodtable').bootstrapTable('refresh');
    }
    
    function ptugoodQueryParams(params) {
        $('#ptugoodtoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#ptugoodtable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#ptugoodtable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    function pgActiveFormatter(value, row){
        var url = '/ptu/good-edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs ptu-good-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';

//        var url = '/ptu/delete-ptu/'+row.id;
//        btn += '<button';
//        btn += ' type="button"';
//        btn += ' class="btn btn-danger btn-xs this-delete"';
//        btn += ' aria-label="Left Align"'; 
//        btn += ' title="Удалить"'; 
//        btn += ' onclick="tableRowDelete(\''+url+'\')">';
//        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
//        btn += '</button>';
        return btn;
    }    
    
    function pgPriceFormatter(value, row){
        return Math.round(value*100/row.quantity)/100;
    }        
    
    function ptugoodResponseHandler(res) {
        return res;
    }     
</script>