<?php

$form = $this->form;

$form->get('legal')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('office')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('company')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('supplier')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('contract')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('docDate')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('docNo')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'ptu-submit']);

$form->prepare();

$docName = 'Новый';
if ($ptu){
    $docName = '№ '.$ptu->getDocNo().' от  '.date('d.m.Y', strtotime($ptu->getDocDate()));
}

?>


            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title" id="ptuModalLabel">Поступление товаров <?= $docName?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('office')); ?>
                            <?= $this->formElement($form->get('office')); ?>
                            <?= $this->formElementErrors($form->get('office')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('company')); ?>
                            <?= $this->formElement($form->get('company')); ?>
                            <?= $this->formElementErrors($form->get('company')); ?>                  
                        </div>
                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('supplier')); ?>
                            <?= $this->formElement($form->get('supplier')); ?>
                            <?= $this->formElementErrors($form->get('supplier')); ?>                  
                        </div>
                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('legal')); ?>
                            <?= $this->formElement($form->get('legal')); ?>
                            <?= $this->formElementErrors($form->get('legal')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('contract')); ?>
                            <?= $this->formElement($form->get('contract')); ?>
                            <?= $this->formElementErrors($form->get('contract')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('docDate')); ?>
                            <?= $this->formElement($form->get('docDate')); ?>
                            <?= $this->formElementErrors($form->get('docDate')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('docNo')); ?>
                            <?= $this->formElement($form->get('docNo')); ?>
                            <?= $this->formElementErrors($form->get('docNo')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('comment')); ?>
                            <?= $this->formElement($form->get('comment')); ?>
                            <?= $this->formElementErrors($form->get('comment')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('status')); ?>
                            <?= $this->formElement($form->get('status')); ?>
                            <?= $this->formElementErrors($form->get('status')); ?>                  
                        </div>

                        <?= $this->formElement($form->get('csrf')); ?>
                    </div>
                </div>
            </div>    
                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="ptu-submit">Сохранить</button>
            </div>
            
            <?= $this->form()->closeTag(); ?>
            
<script>
    $('#ptu-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/ptu/edit-form/<?= $ptu->getId() ?>',
            data: $('#ptu-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#ptu-modal').modal('hide');
                    window.location.reload();
                } else {
                    $('#ptu-modal-content').html(data);
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });
    });
    
    $('#office').on('change', function(){
        $.getJSON( '/offices/legals/'+$('#office').val(), function( data ) {
            $('#company').empty();
            $.each( data.rows, function( key, value ) {
                $('#company').append('<option value="' + key + '">' + value.name + '</option>');
            });
        });    
    });
    
    $('#supplier').on('change', function(){
        $.getJSON( '/supplier/legals/'+$('#supplier').val(), function( data ) {
            $('#legal').empty();
            $.each( data.rows, function( key, value ) {
                $('#legal').append('<option value="' + key + '">' + value.name + '</option>');
            });
        });    
    });
</script>