<?php

$form = $this->form;

$form->get('goodInputName')->setAttributes([
    'class'=>'form-control', 
    'disabled' => true,
    ]);

$form->get('code')->setAttributes([
    'class'=>'form-control', 
    'data-provide' => "typeahead",
    'autocomplete' => 'off',
    ]);

$form->get('quantity')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('amount')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('price')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('unit')->setAttributes([
    'class'=>'form-control', 
    'data-provide' => "typeahead",
//    'data-url' => '\ptu\autocompete-unit',
    'autocomplete' => 'off',
    ]);

$form->get('country')->setAttributes([
    'class'=>'form-control', 
    'data-provide' => "typeahead",
//    'data-url' => '\ptu\autocompete-country',
    'autocomplete' => 'off',
    ]);

$form->get('ntd')->setAttributes([
    'class'=>'form-control', 
    'data-provide' => "typeahead",
//    'data-url' => '\ptu\autocompete-ntd',
    'autocomplete' => 'off',
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'ptu-good-submit']);

$form->prepare();

$docName = 'Новый';

?>
            
<?= $this->form()->openTag($form); ?>
            
<div class="modal-header">
    <h5 class="modal-title" id="ptuGoodModalLabel">Строка поступления товаров</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
            
<div class="modal-body">
    <div class="row">
        <div class="col-xs-12">                        
            <div class="form-group">
<!--                            <?= $this->formLabel($form->get('goodInputName')); ?>
                <em>(артикул;производитель;наименование)</em>-->
                <?= $this->formElement($form->get('goodInputName')); ?>
                <?= $this->formElementErrors($form->get('goodInputName')); ?>                  
            </div>
        </div>    
    </div>
    <div class="row">
        <div class="col-xs-8">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('code')); ?>
                <div class="btn-group">
                    <?= $this->formElement($form->get('code')); ?>
                    <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                </div>
                <?= $this->formElementErrors($form->get('code')); ?>                  
            </div>
        </div>    
    </div>
    <div class="row">
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('quantity')); ?>
                <?= $this->formElement($form->get('quantity')); ?>
                <?= $this->formElementErrors($form->get('quantity')); ?>                  
            </div>
        </div>    
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('amount')); ?>
                <?= $this->formElement($form->get('amount')); ?>
                <?= $this->formElementErrors($form->get('amount')); ?>                  
            </div>
        </div>
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('price')); ?>
                <?= $this->formElement($form->get('price')); ?>
                <?= $this->formElementErrors($form->get('price')); ?>                  
            </div>
        </div>
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('unit')); ?>
                <?= $this->formElement($form->get('unit')); ?>
                <?= $this->formElementErrors($form->get('unit')); ?>                  
            </div>
        </div>
    </div>    
    <div class="row">
        <div class="col-xs-5">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('country')); ?>
                <?= $this->formElement($form->get('country')); ?>
                <?= $this->formElementErrors($form->get('country')); ?>                  
            </div>
        </div>    
        <div class="col-xs-7">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('ntd')); ?>
                <?= $this->formElement($form->get('ntd')); ?>
                <?= $this->formElementErrors($form->get('ntd')); ?>                  
            </div>
        </div>
    </div>    

    <?= $this->formElement($form->get('good')); ?>
    <?= $this->formElement($form->get('csrf')); ?>
</div>    
                
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="button" class="btn btn-primary" id="ptu-good-submit">Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script  type="text/javascript">
    /**
    * очистить поле
     */
    $(".inputclear").click(function(node){
        $("#code").val('');
        $("#good").val('');
        $("#goodInputName").val('');
    });    

    $('#ptu-good-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/ptu/good-edit-form/',
            data: $('#ptu-good-form').serialize()
        })
            .done(function (answer) {
//                console.log(answer);
                if (answer.result == 'ok'){
                    var data = serializeForm('#ptu-good-form');
                    var good = {
                        id: answer.good.id,
                        code: answer.good.code,
                        name: answer.good.name,
                        producer: {name: answer.good.producer},
                    }
                    var unit = {
                        name: data.unit
                    }
                    var country = {
                        name: data.country
                    }
                    var ntd = {
                        ntd: data.ntd
                    }
                    var row = {
                        good: good,
                        amount: data.amount,
                        quantity: data.quantity,
                        price: Math.round(data.amount*100/data.quantity)/100,
                        unit: unit,
                        country: country,
                        ntd: ntd
                    };

                    <?php if($rowNo): ?>
                        $('#ptugoodtable').bootstrapTable('updateByUniqueId', {id: <?= $rowNo ?>, row: row});
                    <?php else:?>
                        var newRowNo = getNewTableUniqueId('ptugoodtable', 'rowNo');
                        row.rowNo = newRowNo;
                        var rows = [];
                        rows.push(row);
                        $('#ptugoodtable').bootstrapTable('prepend', rows);                        
                    <?php endif; ?>        
                    ptuUpdateTotal();    
                    
                    $('#ptuGoodModal').modal('hide');
                } else {
                    $('#ptuGoodModal .modal-content').html(answer);
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });
    });    
    
    $( document ).ready(function() {
        $('#code').typeahead({
            source: function(query, process) {
                query = query.replace(/[^A-Za-z0-9]/g,"");
//                $('#code').val(query);
                return $.get("/ptu/autocomplete-good?q="+query, function (data) {
                    return process(data);
                });
            },
            items: 20,
            changeInputOnSelect: false,
            afterSelect: function(data) {
                $('#good').val(data.id);
                $('#code').val(data.code);
                $('#goodInputName').val(data.name);
            }
        });
        
        $('#unit').typeahead({
            source: function(query, process) {
                return $.get("/ptu/autocomplete-unit?q="+query, function (data) {
                    return process(data);
                });
            }
        });
        
        $('#country').typeahead({
            source: function(query, process) {
                return $.get("/ptu/autocomplete-country?q="+query, function (data) {
                    return process(data);
                });
            }
        });
        
        $('#ntd').typeahead({
            source: function(query, process) {
                return $.get("/ptu/autocomplete-ntd?q="+query, function (data) {
                    return process(data);
                });
            }
        });
        
        $("#code").on('input', function(){
            var value = $(this).val();
            $(this).val(value.replaceAll(/[^A-Za-z0-9]/g,""));
        });

        $("#price").on('input', function(){
            var value = $(this).val();
            $(this).val(value.replace(",","."));
            $("#amount").val(Math.round($(this).val()*$("#quantity").val()*100)/100);
        });
        
        $("#amount").on('input', function(){
            var value = $(this).val();
            $(this).val(parseFloat(value.replace(",",".").replace(/\s/g, '')));
            if ($("#quantity").val()){
                $("#price").val(Math.round($(this).val()*100/$("#quantity").val())/100);
            }    
        });
        
        $("#quantity").on('input', function(){
            if ($("#price").val()){
                $("#amount").val(Math.round($(this).val()*$("#price").val()*100)/100);
            } else {
                if ($("#amount").val()){
                    $("#price").val(Math.round($("#amount").val()*100/$(this).val())/100);
                }    
            }    
        });        
    });    
</script>