<?php
    $this->headTitle('Поступление товаров');

    $this->mainMenu()->setActiveItemId('supplier');

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Поступление товаров'=>$this->url('ptu'),
                ]);

    $this->headLink()
    //    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
        ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
            ;

    $this->headScript()
        ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
        ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
                ;    
?>


<h1>Поступление товаров</h1>

<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button class="btn btn-default" data-toggle="modal" data-target="#modal-dialog" value="/ptu/edit-form">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/ptu/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true" data-align="right">ID</th>
                     <th data-field="aplId" data-type="numeric"data-align="right">AplId</th>
                     <th data-field="docDate" data-sortable="true">Дата</th>
                     <th data-field="docNo" data-sortable="false">Номер</th>
                     <th data-field='amount' data-sortable="false" data-align="right">Сумма</th>
                     <th data-field='legal.name' data-sortable="false">Поставщик</th>
                     <th data-field='office.name' data-sortable="false">Склад</th>
                     <th data-field='comment' data-sortable="false">Примечание</th>
                     <th data-field='status' data-sortable="false">П</th>
                     <th data-field='statusDoc' data-sortable="false">Т</th>
                     <th data-field='statusEx' data-sortable="false">О</th>
                     <th data-field="" data-formatter="activeFormatter"></th>
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Обработка и обновления
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Импорт из АПЛ
                        </div>
                        <div class="pull-right">
                            <button value="/apl/unload-doc?doc=ptu" class="btn btn-default btn-xs refresh-table-button"
                                    title="Импорт одного поступления из АПЛ">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                            <button value="/apl/unload-docs?doc=ptu" class="btn btn-default btn-xs refresh-table-button"
                                    title="Импорт поступлений из АПЛ">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Перепровести все
                        </div>
                        <div class="pull-right">
                            <button value="/ptu/repost-all-ptu/" class="btn btn-default btn-xs refresh-table-button"
                                    title="Перепровести все ПТУ">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button> 
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table'),
        ok = $('#ok');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function activeFormatter(value, row){
        var url = '/ptu/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs"';
        btn += ' aria-label="Left Align"'; 
        btn += ' data-toggle="modal" data-target="#modal-dialog"'; 
        btn += ' value="'+url+'">';
        btn += '<span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>';
        btn += '</button>';

        var url = '/ptu/delete-ptu/'+row.id;
        btn += '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>

