<?php
    $this->headTitle('Поступление товаров');

    $this->mainMenu()->setActiveItemId('supplier');

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Поступление товаров'=>$this->url('ptu'),
                ]);


?>


<h1>Поступление товаров</h1>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
<!--                <button class="btn btn-default" data-toggle="modal" data-target="#modal-dialog" value="/ptu/edit-form">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>-->
                <button class="btn btn-default ptu-modal-show" type="button" modal-url="/ptu/edit-form">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
                <div class="form-group">
                    <input name="search" style="width: 150px" class="form-control" type="text" placeholder="Поиск">
                    <button id="ok" type="submit" class="btn btn-default">OK</button>
                </div>
                <div class="form-group">
                    <select id="supplierSelect" style="width: 250px" class="form-control">
                        <option selected>поставщик</option>
                        <?php foreach ($suppliers as $supplier):?>
                            <option value="<?= $supplier->getId()?>"><?= $supplier->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <select id="officeSelect" style="width: 100px" class="form-control">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <input id="monthSelect" class="form-control" type="month" placeholder="Период" value="<?= date('Y-m');?>">
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/ptu/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true" data-align="right">ID</th>
                     <th data-field="aplId" data-type="numeric"data-align="right">AplId</th>
                     <th data-field="docDate" data-sortable="true">Дата</th>
                     <th data-field="docNo" data-sortable="false">Номер</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-formatter="amountFormatter">Сумма</th>
                     <th data-field='legal.name' data-sortable="false">Поставщик</th>
                     <th data-field='contract.name' data-sortable="false">Договор</th>
                     <th data-field='office.name' data-sortable="false">Склад</th>
                     <th data-field='comment' data-sortable="false">Примечание</th>
                     <th data-field='status' data-sortable="false">П</th>
                     <th data-field='statusDoc' data-sortable="false">Т</th>
                     <th data-field='statusEx' data-sortable="false">О</th>
                     <th data-field="" data-formatter="activeFormatter"></th>
                     <th data-field="id" data-formatter="vtpFormatter"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table'),
        ok = $('#ok');
    
    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
        $(document).on('click', '.ptu-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'ptuModal',
                url: url,
                width: '1440px'
            });
        });  
        $(document).on('click', '.ptu-good-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            var uniqueId = $(e.currentTarget).attr('unique-id');
            if (uniqueId){
                var row = $('#ptugoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'ptuGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        $(document).on('click', '.vtp-index-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'vtpIndexModal',
                url: url,
                width: '1440px'
            });
        });  
        $(document).on('click', '.vtp-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'vtpModal',
                url: url,
                width: '1440px',
                zIndex: 9990
            });
        });  
        $(document).on('click', '.vtp-good-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            var uniqueId = $(e.currentTarget).attr('unique-id');
            if (uniqueId){
                var row = $('#vtpgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'vtpGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('change', '#supplierSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#officeSelect', function (e) {
            refreshTable();
        });
//        $(document).on('change', '#yearSelect', function (e) {
//            refreshTable();
//        });
        $(document).on('change', '#monthSelect', function (e) {
            refreshTable();
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.supplier = $('#supplierSelect').val();
        params.office = $('#officeSelect').val();
//        params.year = $('#yearSelect').val();
        params.month = $('#monthSelect').val();
        
        return params;
    }
    
    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function amountFormatter(value){
        return Math.round(value*100)/100;
    }    
    
    function activeFormatter(value, row){
        var url = '/ptu/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs ptu-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function vtpButtonClass(data){
        if (data.vtpCount){
            $('#vtpbtn'+data.id).removeClass('btn-default');
            $('#vtpbtn'+data.id).addClass('btn-info');
        }            
    }
    
    function vtpFormatter(value, row){
        $.get(
            '/ptu/vtp-count/'+value,
            null,
            vtpButtonClass                
        );

        var url = '/vtp/ptu-form/'+row.id;
        btn = '<button';
        btn += ' id="vtpbtn' + value + '"';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs vtp-index-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span aria-hidden="true">В</span>';
        btn += '</button>';
        return btn;
    }    

    function responseHandler(res) {
        return res;
    }    
</script>

