<?php
    use Stock\Entity\Ptu;
    use Company\Entity\Contract;
    use Laminas\Json\Encoder;

    $this->headTitle('Поступление товаров');

    $this->mainMenu()->setActiveItemId('raw');
    $this->mainMenu()->setActiveUrl($this->url('ptu'));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Поступление товаров'=>$this->url('ptu'),
                ]);


?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <button class="btn btn-default ptu-modal-show" type="button" modal-url="/ptu/edit-form">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </button>
                </div>    
                <div class="form-group">
                    <div class="btn-group">
                        <input id="searchinput" name="search" style="width: 150px" class="form-control enter-search" type="text" placeholder="Артикул">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>
                    <button id="ok" type="submit" class="btn btn-default" title="Поиск">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>    
                <div class="form-group">
                    <select id="supplierSelect" style="width: 250px" class="form-control">
                        <option selected>поставщик</option>
                        <?php foreach ($suppliers as $supplier):?>
                            <option value="<?= $supplier->getId()?>"><?= $supplier->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="officeSelect" style="width: 100px" class="form-control">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <input id="monthSelect" class="form-control" type="month" placeholder="Период" value="<?= date('Y-m');?>">
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/ptu/content"
            data-cookie="true"
            data-cookie-id-table="ptuSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-sort-name="docDate"
            data-sort-order="desc"            
            data-classes = "table table-bordered table-hover table-condensed"
            data-response-handler="responseHandler"
            data-row-style="rowStyle"
            data-show-columns="true"
            data-minimum-count-columns="3"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-formatter="idFormatter" data-align="right" data-width="120">Id</th>
                     <th data-field="docDate" data-sortable="true" data-formatter="dateFormatter" data-width="80">Дата</th>
                     <th data-field="docNo" data-sortable="false">Номер</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-formatter="amountFormatter">Сумма</th>
                     <th data-field='supplier.name' data-sortable="false" data-formatter="linkFormatter">Поставщик</th>
                     <th data-field='legal.name' data-sortable="false">ЮЛ</th>
                     <th data-field='contract.name' data-sortable="false" data-formatter="contractFormatter">Договор</th>
                     <th data-field='office.name' data-sortable="false">Офис</th>
                     <th data-field='comment' data-sortable="false">Примечание</th>
<!--                     <th data-field='status' data-sortable="false">П</th>
                     <th data-field='statusDoc' data-sortable="false">Т</th>
                     <th data-field='statusEx' data-sortable="false">О</th>-->
                     <th data-field="id2" data-formatter="activeFormatter" data-width="5"></th>
                     <th data-field="id3" data-formatter="vtpFormatter" data-width="5"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');
        
    function refreshTable(){
        $table.bootstrapTable('selectPage', 1);
//        $stable.bootstrapTable('refresh');
    }

    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.supplier = $('#supplierSelect').val();
        params.office = $('#officeSelect').val();
//        params.year = $('#yearSelect').val();
        params.month = $('#monthSelect').val();
        
        return params;
    }
    
    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status == '<?= Ptu::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        if (row.status == '<?= Ptu::STATUS_COMMISSION?>'){
           retired += ' warning';
        }
        
        return {classes: retired};
    }
    
    function idFormatter(value, row){
        if (row.aplId > 0){
            return '<nobr>'+value+' ('+row.aplId+')</nobr>';
        }
        return value;
    }    
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }
    
    function linkFormatter(value, row){
        return [
            '<nobr>',
            '<a href="#" class="btn btn-link btn-xs supplier-link" supplier-id="'+row.supplier.id+'" title="Перейти на сайт поставщика">',
            '<span class="glyphicon glyphicon-link"></span></a>',
            '<a href="/supplier/view/' + row.supplier.id + '" target="_blank">' + value + '</a>',
            '</nobr>'
        ].join(''); 
    }        
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    

    function contractFormatter(value, row){
        var date = new Date(row.contract.dateStart);
        var pays = <?= Encoder::encode(Contract::getPayList())?>;
        return pays[row.contract.pay]+' №'+row.contract.act+' от '+$.format.date(date, "dd.MM.yyyy");
    }
    
    function activeFormatter(value, row){
        var url = '/ptu/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs ptu-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function vtpFormatter(value, row){
        var info = $.parseJSON(row.info);
        var btnClass = 'btn-default';
        if (info){
            if (info.depend){
                if (info.depend.vtp){
                    if (info.depend.vtp.length > 0){
                        btnClass = 'btn-info';
                    }
                }    
            }    
        }    

        var url = '/vtp/ptu-form/'+row.id;
        btn = '<button';
        btn += ' id="vtpbtn' + row.id + '"';
        btn += ' type="button"';
        btn += ' class="btn '+btnClass+' btn-xs vtp-index-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span aria-hidden="true">В</span>';
        btn += '</button>';
        return btn;
    }    

    function responseHandler(res) {
        return res;
    }    
</script>

