<?php
use Application\Entity\MarketPriceSetting;

$form = $this->form;

$form->get('region')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('info')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('filename')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('format')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('goodSetting')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('imageCount')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('supplierSetting')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('producerSetting')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('groupSetting')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('tokenGroupSetting')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('minPrice')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('maxPrice')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('maxRowCount')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('blockRowCount')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('pricecol')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('movementLimit')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('nameSetting')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('restSetting')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('tdSetting')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('rates')->setAttributes([
    'class'=>'form-control',
    'style' => 'height: 330px',
    ]);

$form->get('supplier')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('shipping')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'market-submit']);

$form->prepare();

?>



            
        <?= $this->form()->openTag($form); ?>

        <div class="modal-header">
            <h5 class="modal-title" id="otModalLabel">Настройка прайса</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
            
        <div class="modal-body">
            <div class="row">
                <div class="col-lg-9">
                    <div class="row">
                        <div class="col-xs-3">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('name')); ?>
                                <?= $this->formElement($form->get('name')); ?>
                                <?= $this->formElementErrors($form->get('name')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-3">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('filename')); ?>
                                <?= $this->formElement($form->get('filename')); ?>
                                <?= $this->formElementErrors($form->get('filename')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('format')); ?>
                                <?= $this->formElement($form->get('format')); ?>
                                <?= $this->formElementErrors($form->get('format')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('region')); ?>
                                <?= $this->formElement($form->get('region')); ?>
                                <?= $this->formElementErrors($form->get('region')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('status')); ?>
                                <?= $this->formElement($form->get('status')); ?>
                                <?= $this->formElementErrors($form->get('status')); ?>                  
                            </div>
                        </div>
                    </div>    
                    <div class="row">
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('minPrice')); ?>
                                <?= $this->formElement($form->get('minPrice')); ?>
                                <?= $this->formElementErrors($form->get('minPrice')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('maxPrice')); ?>
                                <?= $this->formElement($form->get('maxPrice')); ?>
                                <?= $this->formElementErrors($form->get('maxPrice')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('imageCount')); ?>
                                <?= $this->formElement($form->get('imageCount')); ?>
                                <?= $this->formElementErrors($form->get('imageCount')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('goodSetting')); ?>
                                <?= $this->formElement($form->get('goodSetting')); ?>
                                <?= $this->formElementErrors($form->get('goodSetting')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('maxRowCount')); ?>
                                <?= $this->formElement($form->get('maxRowCount')); ?>
                                <?= $this->formElementErrors($form->get('maxRowCount')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('movementLimit')); ?>
                                <?= $this->formElement($form->get('movementLimit')); ?>
                                <?= $this->formElementErrors($form->get('movementLimit')); ?>                  
                            </div>
                        </div>    
                    </div>        
                    <div class="row">
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('pricecol')); ?>
                                <?= $this->formElement($form->get('pricecol')); ?>
                                <?= $this->formElementErrors($form->get('pricecol')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('tdSetting')); ?>
                                <?= $this->formElement($form->get('tdSetting')); ?>
                                <?= $this->formElementErrors($form->get('tdSetting')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('nameSetting')); ?>
                                <?= $this->formElement($form->get('nameSetting')); ?>
                                <?= $this->formElementErrors($form->get('nameSetting')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('supplier')); ?>
                                <?= $this->formElement($form->get('supplier')); ?>
                                <?= $this->formElementErrors($form->get('supplier')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('producerSetting')); ?>
                                <?= $this->formElement($form->get('producerSetting')); ?>
                                <?= $this->formElementErrors($form->get('producerSetting')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-2">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('groupSetting')); ?>
                                <?= $this->formElement($form->get('groupSetting')); ?>
                                <?= $this->formElementErrors($form->get('groupSetting')); ?>                  
                            </div>
                        </div>    
                    </div>        
                    <div class="row">
                        <div class="col-xs-3">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('tokenGroupSetting')); ?>
                                <?= $this->formElement($form->get('tokenGroupSetting')); ?>
                                <?= $this->formElementErrors($form->get('tokenGroupSetting')); ?>                  
                            </div>
                        </div>    
                        <div class="col-xs-9">                        
                            <div class="form-group">
                                <?= $this->formLabel($form->get('shipping')); ?>
                                <?= $this->formElement($form->get('shipping')); ?>
                                <?= $this->formElementErrors($form->get('shipping')); ?>                  
                            </div>
                        </div>    
                    </div>        
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <?= $this->formLabel($form->get('info')); ?>
                                <?= $this->formElement($form->get('info')); ?>
                                <?= $this->formElementErrors($form->get('info')); ?>                  
                            </div>                        
                        </div>                                            
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('rates')); ?>
                        <?= $this->formElement($form->get('rates')); ?>
                        <?= $this->formElementErrors($form->get('rates')); ?>                  
                    </div>
                </div>
            </div>
        </div>    
        <?= $this->formElement($form->get('supplierSetting')); ?>
        <?= $this->formElement($form->get('restSetting')); ?>
        <?= $this->formElement($form->get('blockRowCount')); ?>
                
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            <button type="submit" class="btn btn-primary" id="market-submit">Сохранить</button>
        </div>
        <?= $this->form()->closeTag(); ?>
            
<script>         
    function submitForm(){
        var data = serializeForm('#market-form');
         $('#market-submit').prop('disabled', true);
        //console.log(data);
        $.ajax({
            type: 'POST',
            url: '/market/edit-form/<?= ($market) ? $market->getId():"" ?>',
            data: $.param(data)
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#marketModal').modal('hide');
                    window.location.reload();
                } else {
                    $('#marketModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };
    
    function regionChange(){
        $.getJSON( '/market/region-shipping/'+$('#region').val(), function( data ) {
            $('#shipping').empty();
            $.each( data.rows, function( key, value ) {
                $('#shipping').append('<option value="' + key + '">' + value.name + '</option>');
            });
        });    
    }
    
    $('#region').on('change', function(){
        regionChange();
    });    
        
    $( document ).ready(function() {
        var forms = $('#market-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('market-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });
    });            
</script>