<?php
use Application\Entity\MarketPriceSetting;

$this->headTitle('Прайс листы для торговых площадок');

$this->mainMenu()->setActiveItemId('client');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Администрирование'=>$this->url('admin'),
            'Прайс листы для торговых площадок' => $this->url('market')
            ]);  

?>
<p>
    <button class="btn btn-default market-modal-show" type="button" modal-url="/market/edit-form">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"> Добавить</span>
    </button>                
    <button value="/ozon-zeroing" class="btn btn-default zeroing-ozon"
            title="Обновить остатки в Озоне">
        <span class="glyphicon glyphicon-remove-circle"> Обнулить OZON</span>
    </button> 
</p>

<table class="table table-striped">

   <tr>
        <th>Id</th>
        <th>Наименование</th>
        <th>Файл</th>        
        <th>Формат</th>
        <th>Регион</th>
        <th>Цены</th>
        <th>Статус</th>        
        <th>Строк</th>
        <th>Дата выгрузки</th>        
        <th></th>        
    </tr>
    
    <?php foreach ($markets as $market): ?>
    
        <tr>
            <td><?= $this->escapeHtml($market->getId()); ?></td>
            <td>
                <?= $this->escapeHtml($market->getName()); ?>
            </td>
            <td>
                <?= $this->escapeHtml($market->getFilename()); ?>
            </td>
            <td>
                <?= $this->escapeHtml($market->getFormatAsString()); ?>
            </td>
            <td>
                <?= $this->escapeHtml($market->getRegion()->getName()); ?>
            </td>
            <td>
                <?= $this->escapeHtml($market->getPricecolAsString()); ?>
                <span><?= $this->escapeHtml($market->getExtraMarginView());?></span>
            </td>
            <td>
                <?= $this->escapeHtml($market->getStatusAsString()); ?>
            </td>
            <td>
                <?= $this->escapeHtml($market->getRowUnload()); ?>
            </td>
            <td>
                <?= $this->escapeHtml($market->getDateUnload()); ?>
            </td>
            <td>
                <nobr>
                    <button class="btn btn-xs btn-info market-modal-show" 
                            type="button" modal-url="/market/edit-form/<?= $market->getId()?>"
                            title="Изменить">
                        <span class="glyphicon glyphicon-pencil" ></span>
                    </button>
                    <button class="btn btn-xs btn-info market-modal-show" 
                            type="button" modal-url="/market/edit-form/<?= $market->getId()?>?copy=1"
                            title="Копировать">
                        <span class="glyphicon glyphicon-duplicate" ></span>
                    </button>
                    <button class="btn btn-xs btn-danger this-delete" value="<?= $this->url('market', 
                            ['action'=>'delete', 'id'=>$market->getId()]); ?>">
                        <span class="glyphicon glyphicon-remove" ></span>
                    </button>
                </nobr>    
            </td>    
        </tr> 
        <tr>
            <td colspan="8">
                <small>
                    Наименования:  <?= $this->escapeHtml($market->getNameSettingAsString());?>; 
                    Картинки:  <?= $this->escapeHtml($market->getGoodSettingAsString());?>; 
                    Картинок:  <?= $this->escapeHtml($market->getImageCount());?>; 
                    Поставщик:  <?= $this->escapeHtml(($market->getSupplier()) ? $market->getSupplier()->getName():'Все');?>;
                    Доставка:  <?= $this->escapeHtml(($market->getShipping()) ? $market->getShipping()->getName():'Нет');?>;
                    Производители:  <?= $this->escapeHtml($market->getProducerSettingAsString());?>; 
                    Группы ТД:  <?= $this->escapeHtml($market->getGroupSettingAsString());?>; 
                    Группы наименований:  <?= $this->escapeHtml($market->getTokenGroupSettingAsString());?>; 
                    Текдок:  <?= $this->escapeHtml($market->getTdSettingAsString());?>; 
                    Расценки <?= $this->escapeHtml(mb_strtolower($market->getRateSettingAsString()));?>
                    <?php if($market->getRateSetting() != MarketPriceSetting::RATE_IGNORE):?>
                        : <?= $this->escapeHtml($market->getRatesAsString());?> 
                    <?php endif; ?>;    
                    Комплект:  <?= $this->escapeHtml($market->getConsiderSetAsString());?>; 
                    Цена минимальная:  <?= $this->escapeHtml($market->getMinPrice());?>; 
                    Цена максимальная:  <?= $this->escapeHtml($market->getMaxPrice());?>; 
                    Наценка дополнительная, %:  <?= $this->escapeHtml($market->getExtraMargin());?>; 
                    Строк в блоке:  <?= $this->escapeHtml($market->getMaxRowCount());?>; 
                    Количество блоков:  <?= $this->escapeHtml($market->getBlockRowCount());?>; 
                    Фильтр движений:  <?= $this->escapeHtml($market->getMovementLimit());?>;
                    Фильтр продаж: <i><?= $this->escapeHtml($market->getRetailLimit());?></i>;
                    Формат описания: <?= $this->escapeHtml($market->getDescriptionFormatAsString());?>;
                    Состав описания: <?= $this->escapeHtml($market->getDescriptionSetAsString());?>;
                    Фильтр слов: <i><?= $this->escapeHtml($market->getTokenFilter());?></i>;
                    Ozon: <?= $this->escapeHtml($market->getOzonUpdateAsString());?>;
                    Коментарий: <?= $this->escapeHtml($market->getInfo());?>
                </small>
            </td>
            <td>
                <?php if ($market->getDateUnload()):?>
                    <?php if ($market->getRowUnload()):?>
                        <button class="btn btn-default btn-xs links-btn" value="<?= $market->getId()?>" 
                                title="Ссылки для скачивания YML">
                            <span class="glyphicon glyphicon-link">Ссылки</span>
                        </button> 
                    <?php endif; ?>    
                    <a class="btn btn-default btn-xs" title="Скачать ZIP" href="<?= $this->url('market',
                            ['action'=>'download-price', 'id' => $market->getId()], ['query' => ['zip' => 1]]); ?>">
                        <span>скачать zip</span>
                    </a>
                <?php endif; ?>        
            </td>
            <td>
                <nobr>
                    <button value="/market/unload-market/<?= $market->getId()?>" class="btn btn-default btn-xs refresh-button"
                            title="Сформировать">
                        <span class="glyphicon glyphicon-play" ></span>
                    </button> 
                    <?php if ($market->getOzonUpdate() != MarketPriceSetting::OZON_IGNORE):?>
                        <button value="/market-place/ozon-update-market/<?= $market->getId()?>" class="btn btn-default btn-xs refresh-ozon"
                                title="Обновить цены и остатки в Озоне">OZON
                            <span class="glyphicon glyphicon-play" ></span>
                        </button> 
                    <?php endif; ?>
                </nobr>    
            </td>    
        </tr>
    <?php endforeach; ?>       
</table>

<script type="text/javascript">
    $(function () {
        $(document).on('click', '.market-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'marketModal',
                url: url,
                width: '1440px'
            });
        });          
        $(document).on('click', '.links-btn', function (e) {
            ymlLinks($(e.currentTarget).val());
        });
    });
    
    function copyToClipbpard(text) {
        var t = document.getElementById('t');
        t.innerHTML = text
        t.select();
        try {
            var successful = document.execCommand('copy');
            var msg = successful ? 'successfully' : 'unsuccessfully';
            console.log('text coppied ' + msg);
        } catch (err) {
            console.log('Unable to copy text');
        }
        t.innerHTML = '';
    }

    function ymlLinks(marketId){
        $.getJSON( '/market/yml-links/'+marketId, function( data ) {
            var result = '';
            $.each( data.links, function( key, value ) {
                result += '<p><span id=link'+key+'>'+value+'</span>';
                if (value.includes('http')){
                    result += '  <button class="btn btn-default btn-xs" onclick="copyToClipbpard(\''+value+'\')" title="Копировать в буфер"><span class="glyphicon glyphicon-copy"></span></button></p>';
                }    
            });                    
            result += '';
            bootbox.dialog({
                title: 'Ссылки на файлы с прайсами <textarea id=t style="width: 0px; height: 0px"></textarea>',
                message: result,
                buttons: {
                    ok: {
                        label: "OK",
                        className: 'btn-info'
                    }                    
                }
            }); 
        });    
    }
    
    $('.refresh-ozon').on('click', function(e) {
        var url = $(this).attr('value');
        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (obj) {
                    dialog.modal('hide');
                    var message = 'Обновлено!';
                    dialog = bootbox.dialog({
                        message: '<p><div><i class="fa fa-spin fa-spinner"></i>'+message+'</div><div>'+obj.prices+'</div><div>'+obj.stocks+'</div></p>',
                        closeButton: true
                    });
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    });     
    
    $('.zeroing-ozon').on('click', function(e) {
        var url = $(this).attr('value');
        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (obj) {
                    dialog.modal('hide');
                    var message = 'Обновлено!';
                    dialog = bootbox.alert('<p><div><i class="fa fa-spin fa-spinner"></i>'+message+'</div></p>');
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    });     

    $('.rate-select').on('click', function(e) {
        var url = e.currentTarget.value;
        bootbox.prompt({
            title: "Выбрать расценку",
            value: ['1', '3'],
            inputType: 'checkbox',
            inputOptions: [{
                text: 'Choice One',
                value: '1'
            },
            {
                text: 'Choice Two',
                value: '2'
            },
            {
                text: 'Choice Three',
                value: '3'
            }],
            callback: function (result) {
                console.log(result);
            }
        });
    });    
</script>