  <style>
   .layer {
        overflow: auto;  /*Добавляем полосы прокрутки*/ 
        width: 100%;  /*Ширина блока */
        height: 600px; /* Высота блока */
        /*padding: 5px;  Поля вокруг текста */
        border: solid 1px red;  /*Параметры рамки */
   } 
  </style>
<?php

$form = $this->form;

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'bill-setting-submit']);

$form->prepare();

?>

            
<?= $this->form()->openTag($form); ?>

<div class="modal-header">
    <h5 class="modal-title">Шаблон</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <div class="row">
        <div class="col-md-4">
            <div class="input-group">
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>                  
            </div>    
            <div class="input-group">
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>                  
            </div>    
            <div class="input-group">
                <?= $this->formLabel($form->get('description')); ?>
                <?= $this->formElement($form->get('description')); ?>
                <?= $this->formElementErrors($form->get('description')); ?>                  
            </div>    
        </div>        
        <div class="col-md-8">
            <div class="input-group">
                <div class="layer" id="sourceData">
                    <small><?= $idoc->getDescriptionAsHtmlTable()?></small>                    
                </div>
            </div>
        </div>
    </div>
</div>    

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="button" class="btn btn-primary" id="bill-setting-submit">Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script>
    $( document ).ready(function() {
        $('#sourceData').css('width', Math.round(window.screen.width/1.67));
    });
    
    $('#bill-setting-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/bills/bill-setting-form/<?= $idoc ?  $idoc->getId():""?>?template=<?= ($billSetting ? $billSetting->getId():"") ?>',
            data: $('#bill-setting-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
                    window.location.reload();
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");

            });
    });    
</script>