  <style>
   .layer {
        overflow: auto;  /*Добавляем полосы прокрутки*/ 
        width: 100%;  /*Ширина блока */
        /*height: 500px;  Высота блока */
        /*padding: 5px;  Поля вокруг текста*/ 
        border: solid 1px red;  /*Параметры рамки */
   } 
  </style>
<?php
use Application\Entity\BillSetting;

$form = $this->form;

$form->get('name')->setAttributes([
    'class'=>'form-control input-sm', 
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control input-sm', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control input-sm', 
    ]);

$form->get('ruleCell')->setAttributes([
    'class'=>'form-control input-sm', 
    ]);

$form->get('docNumCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('docNumRow')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('docDateCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('docDateRow')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('corNumCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('corNumRow')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('corDateCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('corDateRow')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('idNumCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('idNumRow')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('idDateCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('idDateRow')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('contractCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('contractRow')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('tagNoCashCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('tagNoCashRow')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('tagNoCashValue')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('initTabRow')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('articleCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('supplierIdCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('goodNameCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('producerCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('quantityCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('priceCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('amountCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('packageCodeCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('packcageCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('countryCodeCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('countryCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);

$form->get('ntdCol')->setAttributes([
    'class'=>'form-control input-sm input-num', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'bill-setting-submit']);

$form->prepare();

?>

            
<?= $this->form()->openTag($form); ?>

<div class="modal-header">
    <h5 class="modal-title">Шаблон для <?= $idoc->getSupplier()->getName()?> <?= $idoc->getName()?></h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <div class="row" style="padding: 5px;">
        <div class="col-md-3">
            <div id="dataLabel">
               
            </div>
        </div>
        <div class="col-md-1">
            <p class="pull-right">
                <button type="button" class="btn btn-action" title="Проверить" id="bill-setting-check">
                    <span class="glyphicon glyphicon-check"></span>
                </button>
                <button type="button" class="btn btn-action" title="Очистить" id="eraseBtn">
                    <span class="glyphicon glyphicon-erase"></span>
                </button>                
            </p>
        </div>
        <div class="col-md-1">
            <?= $this->formElement($form->get('status')); ?>
        </div>    
        <div class="col-md-1">
            <?= $this->formLabel($form->get('ruleCell')); ?>
        </div>    
        <div class="col-md-2">
            <?= $this->formElement($form->get('ruleCell')); ?>
        </div>    
        <div class="col-md-1">
            <?= $this->formElement($form->get('name')); ?>
        </div>    
        <div class="col-md-1">
            <?= $this->formLabel($form->get('description')); ?>
        </div>    
        <div class="col-md-2">
            <?= $this->formElement($form->get('description')); ?>
        </div>    
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="row">
                <div class="layer">
                    <table width="100%" class="table">
                        <tr>
                            <th></th>
                            <th>Строка</th>
                            <th>Колонка</th>
                            <th>Значение</th>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('docNumCol')); ?></td>
                            <td><?= $this->formElement($form->get('docNumRow')); ?></td>
                            <td><?= $this->formElement($form->get('docNumCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('docDateCol')); ?></td>
                            <td><?= $this->formElement($form->get('docDateRow')); ?></td>
                            <td><?= $this->formElement($form->get('docDateCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('corNumCol')); ?></td>
                            <td><?= $this->formElement($form->get('corNumRow')); ?></td>
                            <td><?= $this->formElement($form->get('corNumCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('corDateCol')); ?></td>
                            <td><?= $this->formElement($form->get('corDateRow')); ?></td>
                            <td><?= $this->formElement($form->get('corDateCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('idNumCol')); ?></td>
                            <td><?= $this->formElement($form->get('idNumRow')); ?></td>
                            <td><?= $this->formElement($form->get('idNumCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('idDateCol')); ?></td>
                            <td><?= $this->formElement($form->get('idDateRow')); ?></td>
                            <td><?= $this->formElement($form->get('idDateCol')); ?></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('contractCol')); ?></td>
                            <td><?= $this->formElement($form->get('contractRow')); ?></td>
                            <td><?= $this->formElement($form->get('contractCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('tagNoCashCol')); ?></td>
                            <td><?= $this->formElement($form->get('tagNoCashRow')); ?></td>
                            <td><?= $this->formElement($form->get('tagNoCashCol')); ?></td>
                            <td><?= $this->formElement($form->get('tagNoCashValue')); ?></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('initTabRow')); ?></td>
                            <td><?= $this->formElement($form->get('initTabRow')); ?></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('articleCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('articleCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('supplierIdCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('supplierIdCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('goodNameCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('goodNameCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('producerCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('producerCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('quantityCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('quantityCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('priceCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('priceCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('amountCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('amountCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('packageCodeCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('packageCodeCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('packcageCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('packcageCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('countryCodeCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('countryCodeCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('countryCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('countryCol')); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?= $this->formLabel($form->get('ntdCol')); ?></td>
                            <td></td>
                            <td><?= $this->formElement($form->get('ntdCol')); ?></td>
                            <td></td>
                        </tr>
                    </table>
                </div>    
            </div>
        </div>        
        <div class="col-md-8">
            <div class="input-group">
                <div class="layer" id="sourceData">
                    <?php if ($billSetting):?>
                        <small><?= $idoc->getDescriptionAsHtmlTable($billSetting->getRuleCellAsBool())?></small>
                    <?php else:?>
                        <small><?= $idoc->getDescriptionAsHtmlTable()?></small>
                    <?php endif;?>    
                </div>
            </div>
        </div>
    </div>
</div>    

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="button" class="btn btn-primary" id="bill-setting-submit">Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script>
    $( document ).ready(function() {
        $('#sourceData').css('width', Math.round(window.screen.width/1.58));
        $('.layer').css('height', Math.round(window.screen.height/1.9));

        $('.dataCell').on('click', function(e){
            var row = $(e.currentTarget).attr('data-row');
            var col = $(e.currentTarget).attr('data-col');
            var value = $(e.currentTarget).html();
            $('#dataLabel').html('строка: '+row+', колонка: '+col+', '+value);
        });
        $('#eraseBtn').on('click', function(e){
            $('.input-num').val(null);
        });
    });
    $('#bill-setting-check').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/bills/read-idoc/<?= $idoc ?  $idoc->getId():""?>',
            data: $('#bill-setting-form').serialize()
        })
            .done(function (data) {
                if (data.data){
    //                console.log(data.data.doc_no);
                    $('#dataLabel').html('№'+data.data.doc_no+' от '+data.data.doc_date+' на сумму '+data.data.total);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при проверке данных");

            });
    });    

    $('#ruleCell').on('change', function() {
        var ruleCell = 1;
        if ($('#ruleCell').val() == <?= BillSetting::RULE_CELL_VALUE?>){
            ruleCell = 0;
        }
        $.ajax({
            type: 'GET',
            url: '/bills/idoc-data/<?= $idoc ?  $idoc->getId():""?>?ruleCell='+ruleCell
        })
            .done(function (data) {
                if (data.data){
    //                console.log(data.data.doc_no);
                    $('#sourceData').html('<small>'+data.data+'</small>');
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при проверке данных");

            });
    });    
    
    $('#bill-setting-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/bills/bill-setting-form/<?= $idoc ?  $idoc->getId():""?>?template=<?= ($billSetting ? $billSetting->getId():"") ?>',
            data: $('#bill-setting-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#billSettingForm').modal('hide');
                    //window.location.reload();
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");

            });
    });    
</script>