<?php
use Application\Entity\Idoc;

$this->headTitle('Электронные накладные');

$this->mainMenu()->setActiveItemId('raw');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Поступления'=>$this->url('ptu'),
            'Электронные накладные'=>$this->url('bills'),
            ]);
?>

<h1>Электронные накладные</h1>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
<!--                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="">
                </div>-->
                <button id="byMail" type="button" class="btn btn-default" title="Проверить почту">
                    <span class="glyphicon glyphicon-envelope"></span>
                </button>
                <div class="form-group">
                    <select id="supplierSelect" style="width: 250px" class="form-control">
                        <option selected>поставщик</option>
                        <?php foreach ($suppliers as $supplier):?>
                            <option value="<?= $supplier->getId()?>"><?= $supplier->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="statusSelect" class="form-control">
                        <?php foreach (Idoc::getStatusList() as $key=>$value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                        <option>все</option>
                    </select>
                    
                </div>    
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/bills/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-width="50">ID</th>
                     <th data-field="dateCreated" data-width="100">Дата</th>
                     <th data-field="status" data-formatter="statusFormatter" data-width="20">C</th>
                     <th data-field="docKey" data-formatter="docFormatter" data-width="75">Документ</th>
                     <th data-field="supplier.name" data-formatter="supplierFormatter">Поставщик</th>
                     <th data-field="name">Файл</th>
                     <th data-field="id" data-formatter="activeFormatter" data-width="50"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table').bootstrapTable();
    var ok = $('#ok');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });

        $(document).on('change', '#supplierSelect', function (e) {
            refreshTable();
        });
        
        $(document).on('change', '#statusSelect', function (e) {
            refreshTable();
        });
        
        $(document).on('click', '.bill-setting-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            var urlQuery = '';
            showFormDialog({
                id: 'billSettingForm',
                url: url+urlQuery,
                width: window.screen.width-40
            });
        });  
        
        $(document).on('click', '.try-ptu', function (e) {
            var url = $(e.currentTarget).attr('url');
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    refreshTable();
                })
                .fail(function (e) {
                    console.log(e);
                    alert("Ошибка при создании ПТУ");

                });
        });            

        $(document).on('click', '#byMail', function (e) {
            var url = '/bills/bills-by-mail';
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    refreshTable();
                })
                .fail(function (e) {
                    console.log(e);
                    alert("Ошибка при проверке почты");

                });
        });            

        $(document).on('click', '.ptu-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'ptuModal',
                url: url,
                width: '1440px'
            });
        });  
        $(document).on('click', '.ptu-good-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            var uniqueId = $(e.currentTarget).attr('unique-id');
            if (uniqueId){
                var row = $('#ptugoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'ptuGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.supplier = $('#supplierSelect').val();
        params.status = $('#statusSelect').val();
        
        return params;
    }
    
    function docFormatter(value){
        if (!value){
            return;
        }
        var keys = value.split(':')
        var url = '/ptu/edit-form/'+keys[1];
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs ptu-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Просмотр ПТУ"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function supplierFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<a href="/supplier/view/' + row.supplier.id + '" target="_blank">' + value + '</a>'
        ].join(''); 
    }    
    
    function statusFormatter(value, row){
        if (value == <?= Idoc::STATUS_ACTIVE?>){
            return 'new';
        }
        if (value == <?= Idoc::STATUS_RETIRED?>){
            return 'ok';
        }
        return 'er';
    }    

    function activeFormatter(value, row){
        var url = '/bills/bill-setting-form/'+value;
        btn = '<button';
        btn += ' modal-url="'+url+'"';
        btn += ' class="btn btn-default btn-xs bill-setting-modal-show"';
//        btn += ' data-toggle="modal" data-target="#modal-dialog"'; 
        btn += ' title="Изменить">'; 
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        
        var url = '/bills/idoc-to-ptu/'+value;
        btn += ' <button';
        btn += ' url="'+url+'"';
        btn += ' class="btn btn-default btn-xs try-ptu"';
        btn += ' title="ПТУ">'; 
        btn += '<span class="glyphicon glyphicon-download" aria-hidden="true"></span>';
        btn += '</button>';

        var url = '/bills/delete-idoc/'+row.id;
        btn += ' <button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        
        return '<nobr>'+btn+'</nobr>';
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>


