<?php

$form = $this->form;

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Путь к файлу'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'id' => 'upload-bill-submit']);
$form->prepare();

?>

            <div class="modal-header">
                <h5 class="modal-title">Загрузить документ поставщика</h5>
                <p>
                    Выберете файл и нажмите <i>Загрузить</i>.
                </p>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">

            <div class="row">
                <div class="col-md-12">
                    <?= $this->form()->openTag($form); ?>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('name')); ?>
                        <?= $this->formElement($form->get('name')); ?>
                        <?= $this->formElementErrors($form->get('name')); ?>                  
                    </div>
                </div>    
            </div>   
                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="upload-bill-submit">Загрузить</button>
            </div>
            <?= $this->form()->closeTag(); ?>

<script type="text/javascript">
    $('#upload-bill-submit').on('click', function() {
        var dialog = bootbox.dialog({
            message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока идет загрузка ...</p>',
            closeButton: false
        });
        
        var file_data = $('#file').prop('files')[0];   
        var form_data = new FormData();                  
        form_data.append('name', file_data);

        $.ajax({
            type: 'POST',
            url: '/bills/upload-bill-form',
            contentType: false,
            processData: false,
            data: form_data
        })
            .done(function (data) {
                dialog.modal('hide');
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
                    //bootbox.alert("Файл успешно загружен.");
                    $('#billTable').bootstrapTable('refresh');
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function () {
                dialog.modal('hide');
                bootbox.alert("Произошла ошибка при выполнении операции.");
            });
    })    
</script>