<?php
    $this->headTitle('Банк');
    $this->mainMenu()->setActiveItemId('company');
    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Предприятие'=>$this->url('company'),
                'Банк'=>$this->url('bank', ['action' => 'statement']),
            ]);
    
$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
    
?>    
<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск по ИНН,Контрагенту,Назначению,Сумме">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/bank/statement-content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric">ID</th>
                     <th data-field="chargeDate" data-formatter="formatDate">Дата</th>
                     <th data-field="amount" data-formatter="amountIn" data-align='right'>Поступило</th>             
                     <th data-field="amount" data-formatter="amountOut" data-align='right'>Списано</th>             
                     <th data-field="purpose">Назначение платежа</th>
                     <th data-field="counterpartyName">Контрагент</th>
                     <th data-field="paymentNumber">Номер ПП</th>
                     <th data-field="paymentDate" data-formatter="formatDate">Дата ПП</th>
<!--                     <th data-field="bik">Счет</th>
                     <th data-field="account">Счет</th>-->
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Банковские счета
                    </div>
                    <? foreach($bankAccounts as $bankAccount): ?>
                        <div class="panel-body">                        
                            <div class="pull-left">
                                <?= $this->escapeHtml($bankAccount->getName());?><br/>
                                <?= $this->escapeHtml($bankAccount->getRs());?>
                            </div>
                            <div class="pull-right">
                                <button value="/legals/bank-account-form/<?= $bankAccount->getLegal()->getId() ?>?bankAccount=<?= $bankAccount->getId() ?>" class="btn btn-default btn-xs"
                                        data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                    <span class="glyphicon glyphicon-edit" ></span>
                                </button>                    
                               <button value="/legals/delete-bank-account-form/<?= $bankAccount->getId() ?>" class="btn btn-default btn-xs this-delete"
                                       title="Удалить">
                                   <span class="glyphicon glyphicon-remove" ></span>
                               </button>                                                           
                                <? if ($bankAccount->getApi() == $bankAccount::API_TOCHKA):?>
                                    <br/>
                                    <button value="/bank/tochka-statement-update/" class="btn btn-info btn-xs refresh-button"
                                            title="Обновить">
                                        <span class="glyphicon glyphicon-refresh" ></span>
                                    </button> 
                                    <a href="<?= $this->url('bankapi', ['action' => 'tochka-access']);?>" class="btn btn-info btn-xs"
                                            title="Доступ к Апи" target="_blank">
                                        <span class="glyphicon glyphicon-piggy-bank" ></span>
                                    </a> 
                                <? endif;?>
                            </div>
                        </div>
                    <? endforeach;?>
                </div>
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams() {
        var params = {offset: 0, limit: 10};
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        return params;
    }
    
    function responseHandler(res) {
        return res;
    }
    
    function formatDate(value){
        if (value){
            var res = value.split("-");
            return res[2]+'.'+res[1]+'.'+res[0];
        } else {
            return '';
        }    
    }
    
    
    function amountIn(value, row){
        if (value>0){            
            return numberFormat(value);
        } else
            return '';
    }

    function amountOut(value, row){
        if (value<0){
            return numberFormat(-value);
        } else
            return '';
    }
    
    
</script>