<?php
    $this->headTitle('Банк');
    $this->mainMenu()->setActiveItemId('company');
    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Предприятие'=>$this->url('company'),
                'Банк'=>$this->url('bank', ['action' => 'statement']),
            ]);
    
$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
    
?>    
<div class="row">
    <div class="col-md-9">
        <ul class="nav nav-tabs" id="featureTab" role="tablist">
            <li role="presentation"><a href="#statement" role="tab" id="statement-tab" data-toggle="tab" aria-controls="statement" aria-expanded="true">Выписка</a></li>
            <li role="presentation"><a href="#balance" role="tab" id="balance-tab" data-toggle="tab" aria-controls="balance" aria-expanded="true">Остатки</a></li>
            <li role="presentation"><a href="#acquiring" role="tab" id="acquiring-tab" data-toggle="tab" aria-controls="acquiring" aria-expanded="true">Эквайринг</a></li>
            <li role="presentation"><a href="#apl" role="tab" id="apl-tab" data-toggle="tab" aria-controls="apl" aria-expanded="true">Оплаты картой</a></li>
        </ul>
        <div class="tab-content" id="featureTabContent">
            <div class="tab-pane fade" role="tabpanel" id="statement" aria-labelledby="statement-tab">
                <div id="toolbar">
                    <div class="form-inline" role="form">
                        <div class="form-group">
                            <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск по ИНН,Контрагенту,Назначению,Сумме">
                        </div>
                        <button id="ok" type="submit" class="btn btn-default">OK</button>
                    </div>
                </div>
                <table id="table" 
                    data-toggle="table" 
                    data-url="/bank/statement-content"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#toolbar"
                    data-show-refresh="true"
                    data-show-toggle="true"
                    data-query-params="statementQueryParams"
                    data-response-handler="responseHandler"
                    >
                    <thead>
                        <tr>
                             <th data-field="id" data-formatter="avatar"></th>
                             <th data-field="chargeDate" data-formatter="formatDateId">Дата/ID</th>
                             <th data-field="amount" data-formatter="amountIn" data-align='right'>Поступило</th>             
                             <th data-field="amount" data-formatter="amountOut" data-align='right'>Списано</th>             
                             <th data-field="purpose">Назначение платежа</th>
                             <th data-field="counterpartyName" data-formatter="formatCounterparty">Контрагент</th>
                             <th data-field="paymentDate" data-formatter="formatDateNumber">Дата/Номер ПП</th>
        <!--                     <th data-field="bik">Счет</th>
                             <th data-field="account">Счет</th>-->
                         </tr>                
                    </thead>
                </table>                
            </div>            
            <div class="tab-pane fade" role="tabpanel" id="balance" aria-labelledby="balance-tab">
                <div id="toolbar_balance">
                </div>
                <table id="table_balance" 
                    data-toggle="table" 
                    data-url="/bank/balance-content"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#toolbar_balance"
                    data-show-refresh="true"
                    data-show-toggle="true"
                    data-query-params="balanceQueryParams"
                    data-response-handler="responseHandler"
                    >
                    <thead>
                        <tr>
                             <th data-field="id" data-formatter="avatar"></th>
                             <th data-field="account">Счет</th>
                             <th data-field="dateBalance" data-formatter="formatDate">Дата</th>
                             <th data-field="balance" data-formatter="amountIn" data-align='right'>Остаток на начало дня</th>             
                         </tr>                
                    </thead>
                </table>                
            </div>            
            <div class="tab-pane fade" role="tabpanel" id="acquiring" aria-labelledby="acquiring-tab">
                <div id="toolbar_acquiring">
                    <div class="form-inline" role="form">
                        <button value="/bank/load-statement-file/" class="btn btn-default refresh-table-button"
                                title="Загрузить данные банка">
                            <span class="glyphicon glyphicon-upload" ></span>
                        </button>                         
                        <button value="/bank/compress-acquiring/" class="btn btn-warning refresh-table-button"
                                title="Удалить отказы">
                            <span class="glyphicon glyphicon-remove-circle" ></span>
                        </button>                         
                        <button value="/bank/acquiring-intersect/" class="btn btn-default refresh-table-button"
                                title="Установить соответствия">
                            <span class="glyphicon glyphicon-check" ></span>
                        </button>                         
                        <div class="form-group">
                            <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск по номеру карты, rrn">
                        </div>
                        <button id="okAcquiring" type="submit" class="btn btn-default">OK</button>
                    </div>
                </div>
                <table id="table_acquiring" 
                    data-toggle="table" 
                    data-url="/bank/acquiring-content"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#toolbar_acquiring"
                    data-show-refresh="true"
                    data-show-toggle="true"
                    data-query-params="acquiringQueryParams"
                    data-response-handler="responseHandler"
                    >
                    <thead>
                        <tr>
                             <th data-field="id"></th>
                             <th data-field="transDate" data-formatter="transDateFormatter">Дата</th>
                             <th data-field="point">Точка</th>
                             <th data-field="cartType" data-formatter="cartFormatter">Карта</th>
                             <th data-field="acode">Код</th>
                             <th data-field="rrn">RRN</th>
                             <th data-field="output" data-formatter="amountIn" data-align='right'>Оплата</th>             
                             <th data-field="output" data-formatter="amountOut" data-align='right'>Возврат</th>             
                             <th data-field="status" data-formatter="statusFormatter"></th>             
                         </tr>                
                    </thead>
                </table>                
            </div>            
            <div class="tab-pane fade" role="tabpanel" id="apl" aria-labelledby="apl-tab">
                <div id="toolbar_apl">
                    <button value="/apl/update-acquiring/" class="btn btn-info refresh-table-button"
                            title="Загрузить данные АПЛ">
                        <span class="glyphicon glyphicon-upload" ></span>
                    </button>                         
                    <button value="/bank/compress-apl-payment/" class="btn btn-warning refresh-table-button"
                            title="Удалить отказы">
                        <span class="glyphicon glyphicon-remove-circle" ></span>
                    </button>                         
                    <button value="/bank/acquiring-intersect/" class="btn btn-default refresh-table-button"
                            title="Установить соответствия">
                        <span class="glyphicon glyphicon-check" ></span>
                    </button>                         
                </div>
                <table id="table_apl" 
                    data-toggle="table" 
                    data-url="/bank/apl-payment-content"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#toolbar_apl"
                    data-show-refresh="true"
                    data-show-toggle="true"
                    data-query-params="aplQueryParams"
                    data-response-handler="responseHandler"
                    >
                    <thead>
                        <tr>
                             <th data-field="id"></th>
                             <th data-field="aplPaymentId">Apl_Id</th>
                             <th data-field="aplPaymentDate">Дата</th>
                             <th data-field="aplPaymentSum" data-formatter="amountIn" data-align='right'>Оплата</th>             
                             <th data-field="aplPaymentSum" data-formatter="amountOut" data-align='right'>Возврат</th>             
                             <th data-field="aplPaymentType" data-formatter="orderFormatter">Заказ</th>             
                             <th data-field="status" data-formatter="aplStatusFormatter"></th>             
                         </tr>                
                    </thead>
                </table>                
            </div>            
        </div>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <?php foreach($bankAccounts as $bankAccount): ?>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <input type="checkbox" id="a<?= $bankAccount->getId() ?>" 
                                   onchange="refreshTable()" class="bankAccount" 
                                   value="<?= $bankAccount->getRs() ?>" 
                                   <?= ($bankAccount->getRs() == $account) ? 'checked':'' ?>>                                
                            <label class="" for="a<?= $bankAccount->getId() ?>">
                                <?= $this->escapeHtml($bankAccount->getName());?>                                                   
                            </label>
                        </div>
                        <div class="panel-body">
                            <div class="pull-left">
                                <img src="/bank/avatar-account/<?= $bankAccount->getRs()?>" width="24" height="24" style="border-radius: 100%"/>
                                <?= $numberFormatFilter->filter($currentBalances[$bankAccount->getRs()]);?>
                            </div>
                            <div class="pull-right">
                                <?php if ($bankAccount->getApi() == $bankAccount::API_TOCHKA):?>
                                        <button value="/bank/tochka-statement-update/" class="btn btn-info btn-xs refresh-table-button"
                                                title="Обновить">
                                            <span class="glyphicon glyphicon-refresh" ></span>
                                        </button> 
                                        <a href="<?= $this->url('bankapi', ['action' => 'tochka-access']);?>" class="btn btn-info btn-xs"
                                                title="Доступ к Апи" target="_blank">
                                            <span class="glyphicon glyphicon-piggy-bank" ></span>
                                        </a> 
                                <?php endif;?>                                    
                                <button value="/legals/bank-account-form/<?= $bankAccount->getLegal()->getId() ?>?bankAccount=<?= $bankAccount->getId() ?>" class="btn btn-default btn-xs"
                                        data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                    <span class="glyphicon glyphicon-edit" ></span>
                                </button>                                            
                            </div>
                        </div>
                    </div>    
                <? endforeach;?>                
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    $(window).on('load', function() {
        $('.nav-tabs a:first').tab('show');
    });
    
    $('#featureTab a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    });

    function refreshTable(){
        $('#table').bootstrapTable('refresh');
        $('#table_balance').bootstrapTable('refresh');
        $('#table_acquiring').bootstrapTable('refresh');
        $('#table_apl').bootstrapTable('refresh');
    }

    var table = $('#table'),
        ok = $('#ok'), okAcquiring = $('#okAcquiring');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
        okAcquiring.click(function () {
            $('#table_acquiring').bootstrapTable('refresh');
        });
    });
    
    function tabQueryParams(tab, params) {
        limit = $(tab + ' .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $(tab + ' li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        var rs = new Array();
        $('.bankAccount:checkbox:checked').each(function () {
            rs.push($(this).val());
        });
        
        if (rs.length){
            params.rs = rs;
        }
        
        return params;
        
    }
    
    function balanceQueryParams(params) {
        return tabQueryParams('#table_balance', params);
    }
    
    function statementQueryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        return tabQueryParams('#table', params);
    }

    function acquiringQueryParams(params) {
        $('#toolbar_acquiring').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        return tabQueryParams('#table_acquiring', params);
    }

    function aplQueryParams(params) {
        return tabQueryParams('#table_apl', params);
    }

    function responseHandler(res) {
        return res;
    }
    
    function avatar(value, row){
        return '<img src="/bank/avatar-account/'+row.account+'" width="24" height="24" style="border-radius: 100%"/>';
    }
    
    function transDateFormatter(value, row){
        return value+'<br/>'+row.operDate;
    }

    function cartFormatter(value, row){
        return value+'<br/>'+row.cart;
    }

    function orderFormatter(value, row){
        if (value == 'Orders'){
            return '<a href="https://autopartslist.ru/admin/orders/view/id/'+row.aplPaymentTypeId+'" target="_blank">'+row.aplPaymentTypeId+'<a/>';
        }
        if (value == 'Users'){
            return '<a href="https://autopartslist.ru/admin/users/users-orders/id/'+row.aplPaymentTypeId+'" target="_blank">'+row.aplPaymentTypeId+'<a/>';
        }
        
        return '';
    }
    
    function aplStatusFormatter(value, row){
        var url = '/bank/update-apl-payment-status/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Изменить статус"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\', \'table_apl\')">';
        btn += '<span class="glyphicon glyphicon-check" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function statusFormatter(value, row){
        var url = '/bank/update-acquiring-status/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Изменить статус"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\', \'table_acquiring\')">';
        btn += '<span class="glyphicon glyphicon-check" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    

    function formatDate(value){
        if (value){
            var res = value.split("-");
            return res[2]+'.'+res[1]+'.'+res[0];
        } else {
            return '';
        }    
    }
    
    function formatDateId(value, row){
        return formatDate(value) + '<br/>' + row.id;
    }
    
    function formatDateNumber(value, row){
        return formatDate(value) + '<br/>' + row.paymentNumber;
    }
    
    function formatCounterparty(value, row){
        var result = value;
        if (row.counterpartyInn){
            result += '<br/>' + row.counterpartyInn;
        }
        if (row.counterpartyKpp){
            result += '<br/>' + row.counterpartyKpp;
        }
        return result;
    }
    
    function amountIn(value, row){
        if (value>0){            
            return numberFormat(value);
        } else
            return '';
    }

    function amountOut(value, row){
        if (value<0){
            return numberFormat(-value);
        } else
            return '';
    }
    
    function responseHandler(res) {
        return res;
    }       
        
</script>