<?php

?>

            
<div class="modal-header">
    <h3 class="modal-title" id="comitentModalLabel"><?= $marketSaleReport->getDocPresent()?> на сумму <?= round($marketSaleReport->getDocAmount(), 2)?> руб.</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
            
<div class="modal-body">
    <div class="row">
        <div class="col-xs-12">
            <div id="msrgoodtoolbar">
            </div>
            <table id="msrgoodtable" 
                data-toggle="msrgoodtable" 
                data-url="/comitent/good-content/<?= $marketSaleReport->getId() ?>"
                data-side-pagination="client"
                data-pagination="true"
                data-cookie="true"
                data-cookie-id-table="msrGoodSaveId"
                data-cookie-expire="1m"
                data-page-size = "10"
                data-page-list="[5, 10, 20, 50]"
                data-toolbar="#msrgoodtoolbar"
                data-icon-size="sm"
                data-show-refresh="true"
                data-show-toggle="false"
                data-show-columns="true"
                data-query-params="msrgoodQueryParams"
                data-response-handler="msrgoodResponseHandler"
                data-unique-id = "id"
                data-row-style="takeStyle"
                data-filter-control="true"
                data-show-search-clear-button="true"
                data-show-footer="true"
                >
                <thead>
                    <tr>
                        <th data-field="rowNumber" data-type="numeric" data-align="right" data-width="20">N</th>
                        <th data-field="offerId" data-type="numeric" >Apl Id</th>
                        <th data-field="good.code" data-type="numeric" data-filter-control="select" data-formatter="goodFormatter">Артикул</th>
                        <th data-field="good.producer.name" data-type="numeric">Производитель</th>
                        <th data-field="productName" data-formatter="goodNameFormatter">Наименование</th>
                        <th data-field='priceSale' data-align="right" data-footer-formatter="totalFooterFormatter" data-formatter="amountFormatter">Цена</th>
                        <th data-field='saleQty' data-align="right" data-footer-formatter="footerFormatter">Количество</th>
                        <th data-field='returnQty' data-align="right" data-footer-formatter="footerFormatter">Возврат</th>
                        <th data-field='salePriceSeller' data-align="right" data-footer-formatter="saleFooterFormatter" data-formatter="saleFormatter">Сумма</th>
                        <th data-field='baseAmount' data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Закупка</th>
                        <th data-field="button" data-formatter="msrActiveFormatter" data-width="20"></th>
                     </tr>                
                </thead>
            </table>
        </div>
    </div>    
</div>
                
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
</div>

<script>    
    
    $( document ).ready(function() {
        
        $('#msrgoodtable').bootstrapTable({
            onLoadSuccess: function(res){
                //mspUpdateTotal();
            }            
        }); 
        
    });    
    
    function msrGoodRefreshTable(){
        $('#msrgoodtable').bootstrapTable('refresh');
    }
    
    function msrgoodQueryParams(params) {
        $('#msrgoodtoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#mspgoodtable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#mspgoodtable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function goodFormatter(value, row){
        if (row.good){
            var url = '/goods/view/'+row.good.id;
            btn = '<nobr><a';
            btn += ' href="'+url+'"';
            btn += ' class="btn btn-link btn-xs" target="_blank">';
            btn += '<span class="glyphicon glyphicon-link"></span>';
            btn += '</a>'+value+'</nobr>';
            return btn;
        }
        
        return;
    }    
    
    function goodNameFormatter(value, row){
        if (row.good){
            if (row.good.tokenGroup){
                return row.good.tokenGroup.name;
            }
        }    
        
        return value;
    }
    
    function amountFormatter(value, row){
        return (Math.round(value*100)/100).toFixed(2);
    }        

    function saleFormatter(value, row){
//        var price = value/row.saleQty;
        return (Math.round((value - row.returnPriceSeller)*100)/100).toFixed(2);
    }        
    
    function totalFooterFormatter() {
        return 'Итого:';
    }
    
    function footerFormatter(data){
        var field = this.field;
        return (data.map(function (row) {
            return +row[field];
        }).reduce(function (sum, i) {
            return (Math.round((sum + i)*100)/100);
        }, 0)).toFixed(2);
    }

    function saleFooterFormatter(data){
        var field = this.field;
        return (data.map(function (row) {
//            var price = row.salePriceSeller/row.saleQty;
            return +(row[field] - row.returnPriceSeller);
        }).reduce(function (sum, i) {
            return Math.round((sum + i)*100)/100;
        }, 0)).toFixed(2);
    }
    
    function msrActiveFormatter(value, row){
        var url = '/comitent/good-edit-form/';
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs msr-good-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' unique-id="'+row.id+'"';
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        
        return btn;
    }    
        
    function pgPriceFormatter(value, row){
        return Math.round(value*100/row.quantity)/100;
    }        
    
    function msrgoodResponseHandler(res) {
        return res;
    }     
</script>