<?php
    use ApiMarketPlace\Entity\MarketSaleReport;

    $this->headTitle('Отчеты торговых площадок');

    $this->mainMenu()->setActiveItemId('client');
    $this->mainMenu()->setActiveUrl($this->url('comitent'));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Отчеты торговых площадок'=>$this->url('comitent'),
                ]);


?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <button class="btn btn-default msr-modal-show" type="button" modal-url="/comitent/report-form" title="Добавить отчет">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </button>
                </div>    
<!--                <div class="form-group">
                    <div class="btn-group">
                        <input id="searchinput" name="search" style="width: 150px" class="form-control enter-search" type="text" placeholder="Артикул">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>
                    <button id="ok" type="submit" class="btn btn-default" title="Поиск">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>    -->
                <div class="form-group">
                    <select id="marketplaceSelect" style="width: 250px" class="form-control">
                        <option selected>торговая площадка</option>
                        <?php foreach ($marketplaces as $marketplace):?>
                            <option value="<?= $marketplace->getId()?>"><?= $marketplace->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <input id="monthSelect" class="form-control" type="month" placeholder="Период" value="">
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/comitent/content"
            data-cookie="true"
            data-cookie-id-table="comitentSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-sort-name="docDate"
            data-sort-order="desc"            
            data-classes = "table table-bordered table-hover table-condensed"
            data-response-handler="responseHandler"
            data-row-style="rowStyle"
            data-unique-id="id"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-align="right" data-width="20">Id</th>
                     <th data-field="docDate" data-sortable="true" data-formatter="dateFormatter" data-width="80">Дата</th>
                     <th data-field="num" data-sortable="false">Номер</th>
                     <th data-field='docAmount' data-sortable="false" data-align="right" data-formatter="amountFormatter">Реализовано</th>
                     <th data-field='baseAmount' data-sortable="false" data-align="right" data-formatter="amountFormatter">Закупка</th>
                     <th data-field='costAmount' data-sortable="false" data-align="right" data-formatter="amountFormatter">Расходы</th>
                     <th data-field='inAmount' data-sortable="false" data-align="right" data-formatter="inAmountFormatter">Прибыль</th>
                     <th data-field='marketplace.name' data-sortable="false" data-formatter="linkFormatter">Торговая площадка</th>
                     <th data-field="id2" data-formatter="activeFormatter" data-width="5"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');
    var curentRowIndex = -1;
    
    function setCurrentIndex(index){
        curentRowIndex = index;
    }

    function getCurrentIndex(){
        return curentRowIndex;
    }

    function refreshTable(){
        $table.bootstrapTable('selectPage', 1);
//        $stable.bootstrapTable('refresh');
    }

    $(function () {        
        $(document).on('change', '#marketplaceSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#monthSelect', function (e) {
            refreshTable();
        });
    });

    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.marketplace = $('#marketplaceSelect').val();
        params.month = $('#monthSelect').val();
        
        return params;
    }
    
    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status == '<?= MarketSaleReport::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        if (row.statusAccount == '<?= MarketSaleReport::STATUS_TAKE_NO?>'){
           retired += ' warning';
        }
        
        return {classes: retired};
    }
    
    function idFormatter(value, row){
        if (row.aplId > 0){
            return '<nobr>'+value+' ('+row.aplId+')</nobr>';
        }
        return value;
    }    
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }
    
    function linkFormatter(value, row){
        return [
            '<nobr>',
            '<a href="'+row.marketplace.site+'" class="btn btn-link btn-xs" target="_blank" title="Перейти на сайт ТП">',
            '<span class="glyphicon glyphicon-link"></span></a>',
            '<a href="/market-place/view/' + row.marketplace.id + '" target="_blank">' + value + '</a>',
            '</nobr>'
        ].join(''); 
    }        
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    

    function inAmountFormatter(value, row){
        return (Math.round((row.docAmount - row.baseAmount - row.costAmount)*100)/100).toFixed(2);
    }    
    
    function activeFormatter(value, row){
        var url = '/comitent/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs msr-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
    
    function changeStatus(mspId, status){
        $.get( "/comitent/status/"+mspId+'?status='+status, function(data){
            $table.bootstrapTable('updateByUniqueId', {id: mspId, row: data});
        });        
    }
    
    function repost(mspId){
        $.get( "/comitent/repost/"+mspId, function(data){
            $table.bootstrapTable('updateByUniqueId', {id: mspId, row: data});
        });        
    }
    
    var menu = new BootstrapMenu('.tablerow', {
        fetchElementData: function(rowElem) {
            setCurrentIndex($(rowElem).attr('data-index'));
            return $table.bootstrapTable('getData')[getCurrentIndex()];
        },
        actionsGroups: [
           ['statusActiv', 'statusRetired']
        ],      
        actions: {
            statusActiv: {
                name: 'Сделать активным',
                iconClass: 'glyphicon glyphicon-ok',
                onClick: function(row) {
                    changeStatus(row.id, <?= MarketSaleReport::STATUS_ACTIVE?>);
                },
                isShown: function(row) {
                  return row.status == <?= MarketSaleReport::STATUS_RETIRED?>;
                },
                isEnabled: function(row) {
                    return row.docDate > '<?= $allowDate?>';
                }                
            }, 
            statusRetired: {
                name: 'Сделать не активным',
                iconClass: 'glyphicon glyphicon-remove',
//                classNames: 'bg-danger',
                onClick: function(row) {
                    changeStatus(row.id, <?= MarketSaleReport::STATUS_RETIRED?>);
                },
                isShown: function(row) {
                  return row.status == <?= MarketSaleReport::STATUS_ACTIVE?>;
                },
                isEnabled: function(row) {
                    return row.docDate > '<?= $allowDate?>' || row.status != <?= MarketSaleReport::STATUS_ACTIVE?>;
                }                
            },
            repost: {
                name: 'Провести',
                iconClass: 'glyphicon glyphicon-refresh',
//                classNames: 'bg-danger',
                onClick: function(row) {
                    repost(row.id);
                },
                isShown: function(row) {
                  //return row.status == <?= MarketSaleReport::STATUS_ACTIVE?> && row.statusDoc == <?= MarketSaleReport::STATUS_DOC_NOT_RECD?>;
                },
                isEnabled: function(row) {
                    return row.docDate > '<?= $allowDate?>' && row.status == <?= MarketSaleReport::STATUS_ACTIVE?>;
                }                
            }
        }
    });        
</script>

