<?php
use Stock\Entity\Revise;

$form = $this->form;

$form->get('docDate')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('num')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('marketplace')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'compensation-submit']);

$form->prepare();

?>
<?= $this->form()->openTag($form); ?>

<div class="modal-header">
    <h5 class="modal-title" id="compensationModalLabel">Отчет о компенсациях</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <div class="row">
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('num')); ?>
                <?= $this->formElement($form->get('num')); ?>
                <?= $this->formElementErrors($form->get('num')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('docDate')); ?>
                <?= $this->formElement($form->get('docDate')); ?>
                <?= $this->formElementErrors($form->get('docDate')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('marketplace')); ?>
                <?= $this->formElement($form->get('marketplace')); ?>
                <?= $this->formElementErrors($form->get('marketplace')); ?>                  
            </div>
        </div>
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>                  
            </div>
        </div>    
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div id="msrgoodtoolbar">
                <div class="form-inline" role="form">
                    <button type="button" class="btn btn-default btn-sm report-good-modal-show" modal-url="/comitent/report-good-edit-form">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </button>
                </div>
            </div>
            <table id="msrgoodtable" 
                data-toggle="msrgoodtable" 
                data-url="/comitent/good-content/<?= ($report) ? $report->getId():'' ?>"
                data-side-pagination="client"
                data-pagination="true"
                data-cookie="true"
                data-cookie-id-table="msrGoodSaveId"
                data-cookie-expire="1m"
                data-page-size = "10"
                data-page-list="[5, 10, 20, 50]"
                data-toolbar="#msrgoodtoolbar"
                data-icon-size="sm"
                data-show-refresh="true"
                data-show-toggle="false"
                data-show-columns="true"
                data-query-params="msrgoodQueryParams"
                data-response-handler="msrgoodResponseHandler"
                data-unique-id = "rowNumber"
                data-row-style="takeStyle"
                data-show-footer="true"
                >
                <thead>
                    <tr>
                        <th data-field="rowNumber" data-type="numeric" data-align="right" data-width="20">N</th>
                        <th data-field="offerId" data-type="numeric" >Apl Id</th>
                        <th data-field="good.code" data-type="numeric" data-formatter="goodFormatter">Артикул</th>
                        <th data-field="good.producer.name" data-type="numeric">Производитель</th>
                        <th data-field="good.name" data-type="numeric">Наименование</th>
                        
                        <th data-field='priceSale' data-align="right" data-footer-formatter="totalFooterFormatter" data-formatter="amountFormatter">Цена</th>
                        <th data-field='saleQty' data-align="right" data-footer-formatter="footerFormatter">Количество</th>
                        <th data-field='returnQty' data-align="right" data-footer-formatter="footerFormatter">Возврат</th>
                        <th data-field='salePriceSeller' data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Сумма</th>
                        <th data-field='baseAmount' data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Закупка</th>
                        
                        <th data-field="rowNumber" data-formatter="msrcActiveFormatter" data-width="5"></th>
                         <th data-field="rowNumber" data-formatter="msrcRemoveFormatter" data-width="5"></th>
                     </tr>                
                </thead>
            </table>
        </div>
    </div>    
    <div class="row">    
        <div class="col-xs-12">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('comment')); ?>
                <?= $this->formElement($form->get('comment')); ?>
                <?= $this->formElementErrors($form->get('comment')); ?>                  
            </div>
        </div>    
    </div>    
</div>    

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary" id="compensation-submit">Сохранить</button>
</div>
<?= $this->form()->closeTag(); ?>
            
<script>             
    var report_total = 0;
    
    function getReportTotal(){
        return report_total;
    }
    
    function setReportTotal(reportTotal){
        report_total = reportTotal;
    }
    
    function submitForm(){
        var data = serializeForm('#market-sale-report-form');
        data['doc_amount'] = getReportTotal();
         $('#compensation-submit').prop('disabled', true);
        data.reportGood = getFormatedReportGood();
        $.ajax({
            type: 'POST',
            url: '/comitent/report-form/<?= ($report) ? $report->getId():"" ?>',
            data: $.param(data)
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#msrcModal').modal('hide');
                    if ($('#table')){
                        $('#table').bootstrapTable('refresh');
                    }    
                    if ($('#mutualtable')){
                        $('#mutualtable').bootstrapTable('refresh');
                    }    
                } else {
                    $('#msrcModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };
    
    function getFormatedReportGood(){
        var data = $('#msrgoodtable').bootstrapTable('getData');
        var result = [];
        $.each( data, function( index, row ) {
            var newRow = {
                good_id: row.good.id,
                saleQty: row.saleQty,
                salePriceSeller: row.salePriceSeller,
                priceSale: row.priceSale,
                rowNumber: row.rowNumber
            };
            result.push(newRow);
        });   
        return result;
    }
    
    //удаление строки из таблицы
    function removeTableRowByUniqueId(index){
        $('#msrgoodtable').bootstrapTable('removeByUniqueId', index);
    }
    
    
    $( document ).ready(function() {
        
        $('#msrgoodtable').bootstrapTable({
            onLoadSuccess: function(res){
                //mspUpdateTotal();
            }            
        }); 
        
    });    
    
    function msrGoodRefreshTable(){
        $('#msrgoodtable').bootstrapTable('refresh');
    }
    
    function msrgoodQueryParams(params) {
        $('#msrgoodtoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#msrgoodtable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#msrgoodtable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function goodFormatter(value, row){
        if (row.good){
            var url = '/goods/view/'+row.good.id;
            btn = '<nobr><a';
            btn += ' href="'+url+'"';
            btn += ' class="btn btn-link btn-xs" target="_blank">';
            btn += '<span class="glyphicon glyphicon-link"></span>';
            btn += '</a>'+value+'</nobr>';
            return btn;
        }
        
        return;
    }    
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }        
        
    function totalFooterFormatter() {
        return 'Итого:';
    }

    function footerFormatter(data){
        var field = this.field;
        return (data.map(function (row) {
            return +row[field];
        }).reduce(function (sum, i) {
            var total = sum + i;
            if (field == 'salePriceSeller'){
                setReportTotal(total);
            }
            return (Math.round((total)*100)/100);
        }, 0)).toFixed(2);
    }

    function msrcActiveFormatter(value, row){
        var url = '/comitent/report-good-edit-form/';
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs report-good-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' unique-id="'+value+'"';
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        
        return btn;
    }    
        
    function msrcRemoveFormatter(value, row){
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs table-row-remove"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="removeTableRowByUniqueId('+value+')">';
        btn += '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
        
    function msrgoodResponseHandler(res) {
        return res;
    }     

    $( document ).ready(function() {
                
        var forms = $('#market-sale-report-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('revise-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });
    });            
</script>