<?php
//var_dump($rowNo);

$form = $this->form;

$form->get('goodInputName')->setAttributes([
    'class'=>'form-control', 
    'disabled' => true,
    ]);

$form->get('code')->setAttributes([
    'class'=>'form-control', 
    'data-provide' => "typeahead",
    'autocomplete' => 'off',
    ]);

$form->get('aplId')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('good')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('saleQty')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('returnQty')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('saleAmount')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('retunAmount')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('priceSale')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'msr-good-submit']);

$form->prepare();

$docName = 'Новый';

?>
            
<?= $this->form()->openTag($form); ?>
            
<div class="modal-header">
    <h5 class="modal-title" id="msrcGoodModalLabel">Добавление товара в отчете по реализации</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
            
<div class="modal-body">
    <div class="row">
        <div class="col-xs-12">                        
            <div class="form-group">
<!--                            <?= $this->formLabel($form->get('goodInputName')); ?>
                <em>(артикул;производитель;наименование)</em>-->
                <?= $this->formElement($form->get('goodInputName')); ?>
                <?= $this->formElementErrors($form->get('goodInputName')); ?>                  
            </div>
        </div>    
    </div>
    <div class="row">
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('aplId')); ?>
                <div class="btn-group">
                    <?= $this->formElement($form->get('aplId')); ?>
                    <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                </div>
                <?= $this->formElementErrors($form->get('aplId')); ?>                  
            </div>
        </div>    
        <div class="col-xs-5">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('code')); ?>
                <div class="btn-group">
                    <?= $this->formElement($form->get('code')); ?>
                    <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                </div>
                <?= $this->formElementErrors($form->get('code')); ?>                  
            </div>
        </div>    
    </div>
    <div class="row">
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('saleQty')); ?>
                <?= $this->formElement($form->get('saleQty')); ?>
                <?= $this->formElementErrors($form->get('saleQty')); ?>                  
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('returnQty')); ?>
                <?= $this->formElement($form->get('returnQty')); ?>
                <?= $this->formElementErrors($form->get('returnQty')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('saleAmount')); ?>
                <?= $this->formElement($form->get('saleAmount')); ?>
                <?= $this->formElementErrors($form->get('saleAmount')); ?>                  
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('returnAmount')); ?>
                <?= $this->formElement($form->get('returnAmount')); ?>
                <?= $this->formElementErrors($form->get('returnAmount')); ?>                  
            </div>
        </div>
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('priceSale')); ?>
                <?= $this->formElement($form->get('priceSale')); ?>
                <?= $this->formElementErrors($form->get('priceSale')); ?>                  
            </div>
        </div>
    </div>    

    <?= $this->formElement($form->get('good')); ?>
    <?= $this->formElement($form->get('csrf')); ?>
</div>    
                
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="button" class="btn btn-primary" id="msrc-good-submit">Сохранить</button>
</div>
            
<?= $this->form()->closeTag(); ?>
            
<script  type="text/javascript">
    $('#msrc-good-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/comitent/report-good-edit-form/',
            data: $('#msr-good-form').serialize()
        })
            .done(function (answer) {
//                console.log(answer);
                if (answer.result == 'ok'){
                    var data = serializeForm('#msr-good-form');
                    var good = {
                        id: answer.good.id,
                        code: answer.good.code,
                        name: answer.good.name,
                        producer: {name: answer.good.producer}
                    };
                    var row = {
                        good: good,
                        offerId: answer.good.aplId,
                        saleAmount: data.saleAmount,
                        returnAmount: data.returnAmount,
                        saleQty: data.saleQty,
                        returnQty: data.returnQty,
                        priceSale: data.priceSale,
                        baseAmount: 0
                    };

                    <?php if($rowNo): ?>
                        $('#msrgoodtable').bootstrapTable('updateByUniqueId', {id: <?= $rowNo ?>, row: row});
                    <?php else:?>
                        var newRowNo = getNewTableUniqueId('msrgoodtable', 'rowNumber');
                        row.rowNumber = newRowNo;
                        var rows = [];
                        rows.push(row);
                        $('#msrgoodtable').bootstrapTable('prepend', rows);                        
                    <?php endif; ?>        
                    //ptuUpdateTotal();    
                    
                    $('#msrcGoodModal').modal('hide');
                } else {
                    $('#msrcGoodModal .modal-content').html(answer);
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });
    });    
    
    $( document ).ready(function() {
        $('#code').on('input', function(){
            $('#code').val($.trim($('#code').val()));
        });
        
        $('#code').typeahead({
            source: function(query, process) {
                return $.get("/ptu/autocomplete-good?q="+query, function (data) {
                    return process(data);
                });
            },
            changeInputOnSelect: false,
            afterSelect: function(data) {
                $('#good').val(data.id);
                $('#code').val(data.code);
                $('#aplId').val(data.aplId);
                $('#goodInputName').val(data.name);
            }
        });        
        
        $('#aplId').on('change', function(){
            $.get("/ptu/autocomplete-good?aplId="+$(this).val(), function (data){
                $('#good').val(data.id);
                $('#code').val(data.code);
                $('#aplId').val(data.aplId);
                $('#goodInputName').val(data.name);
            });        
        });

        $("#priceSale").on('input', function(){
            var value = $(this).val();
            $(this).val(value.replace(",","."));
        });
        
        $("#saleAmount").on('input', function(){
            var value = $(this).val();
            $(this).val(parseFloat(value.replace(",",".").replace(/\s/g, '')));
        });
        
        $("#returnAmount").on('input', function(){
            var value = $(this).val();
            $(this).val(parseFloat(value.replace(",",".").replace(/\s/g, '')));
        });
        
    });            
</script>