<?php
use Application\Entity\GenericGroup;

$this->headTitle('Группы товаров');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Группы'=>$this->url('group')
            ]);

?>
<div class="row">
    <div class="col-md-10">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/group/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                     <th data-field="tdId" data-sortable="true">TD</th>
                     <th data-field="aplId" data-sortable="true">АПЛ</th>
                     <th data-field="name" data-sortable="true" data-formatter="linkFormatter">Наименование</th>             
                     <th data-field="assemblyGroup" data-sortable="true">Группа сборки</th>             
                     <th data-field="masterName" data-sortable="true">Основная группа</th>             
                     <th data-field="usageName" data-sortable="true">Использование</th>             
                     <th data-field="carUpload" data-formatter="carUploadFormatter">
                         <span data-toggle="tooltip" data-original-title="Загружать машины из ТД">М</span>
                     </th>             
                     <th data-field="goodCount" data-sortable="true">Тов</th>             
                     <th data-field="movement" data-sortable="true">Движ</th>             
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-2" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Обновить и посчитать
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            ТекДок 
                        </div>
                        <div class="pull-right">
                            <button value="/ext/update-generic-group" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить группы из текдока">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
<!--                    <div class="panel-body">
                        <div class="pull-left">
                            Доступно<sup id='totalRow'></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/group/update-all-status" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить доступность">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>-->
                    <div class="panel-body">
                        <div class="pull-left">
                            Движения
                        </div>
                        <div class="pull-right">
                            <button value="/group/update-all-movement" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить движения">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                           АПЛ Ид
                        </div>
                        <div class="pull-right">
                            <button value="/group/update-apl-groups" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table').bootstrapTable({
        onLoadSuccess: function(res){
            $('#totalRow').html($('#table').bootstrapTable('getOptions').totalRows);
            $("[data-toggle='tooltip']").tooltip();
            $('.editableCheckBox').change(function() {
                $.ajax({
                    type: "POST",
                    url: $(this).attr('data-url'),
                    data: "pk="+$(this).attr('data-pk'),
                    success: function(msg){
//                      alert( "Прибыли данные: " + msg );
                    }
                });
            })        
        }
    });
    
    var ok = $('#ok');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }

        
        return params;
    }
    
    function linkFormatter(value, row){
        return [
            '<a href="/group/view/' + row.id + '" target="_blank">' + value + '</a>',
        ].join(''); 
    }    
    
    function carUploadFormatter(value, row){
        var checked = 'checked';
        if (value == <?= GenericGroup::CAR_RETIRED?>){
            checked = '';
        }
        return [
            '<input data-toggle="tooltip" class="editableCheckBox" \n\
                data-pk="'+row.id+'" data-url="/group/car-upload-edit" type="checkbox" '+checked+'/>'
        ].join(''); 
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>
