<?php
$this->headTitle('Группы товаров');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Группы'=>$this->url('group')
            ]);

$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
?>
<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/group/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                     <th data-field="tdId" data-sortable="true">TD</th>
                     <th data-field="aplId" data-sortable="true" data-formatter="aplFormatter">АПЛ</th>
                     <th data-field="name" data-sortable="true">Наименование</th>             
                     <th data-field="assemblyGroup" data-sortable="true">Группа сборки</th>             
                     <th data-field="masterName" data-sortable="true">Основная группа</th>             
                     <th data-field="usageName" data-sortable="true">Использование</th>             
                     <th data-field="goodCount" data-sortable="true">Товаров</th>             
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Обновить и посчитать
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            ТекДок 
                        </div>
                        <div class="pull-right">
                            <button value="/ext/update-generic-group" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить группы из текдока">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Доступно<sup id='totalRow'></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/group/update-all-status" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить доступность">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                           АПЛ Ид
                        </div>
                        <div class="pull-right">
                            <button value="/apl/update-make-apl-id" class="btn btn-info btn-xs refresh-table-button"
                                    title="Заполнить">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table').bootstrapTable({
        onLoadSuccess: function(res){
            $('#totalRow').html($('#table').bootstrapTable('getOptions').totalRows)
        }
    });
    
    var ok = $('#ok');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }

        
        return params;
    }
    
    function linkFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/make/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function aplFormatter(value, row){
        var url = '/group/update-group-apl/'+row.id;
        var btn = '<button';
        btn += ' value="'+url+'"';
        btn += ' class="btn btn-default btn-xs refresh-table-button"';
        btn += ' title="Обновить группу АПЛ">'; 
        btn += '<span class="glyphicon glyphicon-refresh"></span>';
        btn += '</button>';
        
        return btn+' '+value;
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>
