<?php
$this->headTitle($group->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Группы'=>$this->url('group'),
            $group->getName()=>$this->url('group', ['action'=>'view', 'id'=>$group->getId()])
            ]);

?>

<h1>
    <?= $group->getName();?>
    <sup>
        <?= $group->getTdId();?>
    </sup>
</h1>
<p>
    <?= $group->getStatusAsString();?>
</p>
<div class="row">
    <div class="col-md-9">

        <table class="table table-striped">
            <tr>
                <td colspan="3">            
                    <?php if ($prev):?>
                        <a href="/group/view/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getName()?></a>
                    <?php endif;?>            
                </td>
                <td colspan="3" align="right">
                    <?php if ($next):?>
                        <a href="/group/view/<?= $next[0]->getId()?>"><?= $next[0]->getName()?>&rarr;</a>
                    <?php endif;?>                            
                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Обновления и внешние данные
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            AplId: 
                                <?= $group->getAplId()?>
                        </div>
                        <div class="pull-right">
                            <button value="/apl/car-apl-id/<?= $group->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить АПЛ Ид">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Товары<sup><?= $group->getGoodCount()?></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/car/update-available/<?= $group->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить доступность">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.show-button').on('click', function(e) {
        var url = e.currentTarget.value;

        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    dialog = bootbox.dialog({
                        message: '<div><i class="fa fa-spin fa-spinner"></i>'+objectToHtml(data.message)+'</div>',
                        closeButton: true,
                        size: 'large'
                    });
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })        
</script>
