<?php
$this->headTitle($group->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Группы'=>$this->url('group'),
            $group->getName()=>$this->url('group', ['action'=>'view', 'id'=>$group->getId()])
            ]);

    $this->headLink()
    //    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
        ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
            ;

    $this->headScript()
        ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
        ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
?>

<h1>
    <?= $group->getName();?>
    <sup>
        <?= $group->getTdId();?>
    </sup>
</h1>
<p>
    <?= $group->getAssemblyGroup()?> 
    <?= $group->getMasterName()?> 
    <?= $group->getUsageName()?> 
</p>
<p>
    <?php if ($group->getTdId()):?>
        <?php foreach ($aplGroups as $aplGroup):?>
            <span><?= $aplGroup['groupApl']?></span> 
            <span>(<?= $aplGroup['goodCount']?>)</span>
        <?php endforeach;?> 
    <?php endif;?>        
</p>
<div class="row">
    <div class="col-md-9">
        <table class="table table-striped">
            <tr>
                <td colspan="3">            
                    <?php if ($prev):?>
                        <a href="/group/view/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getName()?></a>
                    <?php endif;?>            
                </td>
                <td colspan="3" align="right">
                    <?php if ($next):?>
                        <a href="/group/view/<?= $next[0]->getId()?>"><?= $next[0]->getName()?>&rarr;</a>
                    <?php endif;?>                            
                </td>
            </tr>
        </table>    
        <ul class="nav nav-tabs" id="featureTab" role="tablist">
            <li role="presentation"><a href="#goods" role="tab" id="goods-tab" data-toggle="tab" aria-controls="goods" aria-expanded="true">Товары</a></li>
            <li role="presentation"><a href="#tokenGroups" role="tab" id="token-group-tab" data-toggle="tab" aria-controls="tokenGroups" aria-expanded="true">Группы наименований</a></li>
        </ul>
        <div class="tab-content" id="featureTabContent">
            <div class="tab-pane fade" role="tabpanel" id="goods" aria-labelledby="goods-tab">
                <div id="goodsToolbar">
                    <div class="form-inline" role="form">
                        <div class="form-group">
                            <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                        </div>
                        <button id="goodsOk" type="submit" class="btn btn-default">OK</button>                        
                    </div>
                </div>
                <table id="goodsTable" 
                    data-toggle="table" 
                    data-url="/goods/content"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#goodsToolbar"
                    data-show-refresh="true"
                    data-show-toggle="true"
                    data-query-params="goodsQueryParams"
                    data-response-handler="responseHandler"
                    >
                    <thead>
                        <tr>
                             <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                             <th data-field="name" data-type="numeric" data-sortable="true" data-formatter="aplFormatter">Группа АПЛ</th>
                             <th data-field="code" data-formatter="linkFormatter" data-sortable="true">Артикул</th>
                             <th data-field="producer" data-formatter="producerFormatter">Производитель</th>             
                             <th data-field="" data-formatter="activeFormatter"></th>
                         </tr>                
                    </thead>
                </table>
            </div>
            <div class="tab-pane fade" role="tabpanel" id="tokenGroups" aria-labelledby="token-group-tab">
                <div id="tokenGroupToolbar">
                    <div class="form-inline" role="form">
                        <div class="form-group">
                            <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                        </div>
                        <button id="tokenGroupOk" type="submit" class="btn btn-default">OK</button>                        
                    </div>
                </div>
                <table id="tokenGroupTable" 
                    data-toggle="table" 
                    data-url="/group/token-group-content/<?= $group->getId()?>"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#tokenGroupToolbar"
                    data-show-refresh="true"
                    data-show-toggle="true"
                    data-query-params="tokenGroupQueryParams"
                    data-response-handler="responseHandler"
                    >
                    <thead>
                        <tr>
                             <th data-field="id" data-type="numeric" data-sortable="true">ID</th>
                             <th data-field="name" data-sortable="true">Наименование</th>
                             <th data-field="lemms" data-sortable="true">Леммы</th>
                         </tr>                
                    </thead>
                </table>
            </div>
        </div>    
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Обновления и внешние данные
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            AplId: 
                                <?= $group->getAplId()?>
                        </div>
                        <div class="pull-right">
                            <?php if ($group->getTdId()):?>
                                <button value="/group/update-group-apl/<?= $group->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                        title="Обновить АПЛ Ид">
                                    <span class="glyphicon glyphicon-refresh" ></span>
                                </button>
                            <?php endif;?>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Товары<sup><?= $group->getGoodCount()?></sup>
                        </div>
                        <div class="pull-right">
                            <button value="/group/update-good-count/<?= $group->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить количество товаров">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(window).on('load', function() {
        $('.nav-tabs a:first').tab('show');
    });
    
    $('#featureTab a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    })    

    function refreshTable(){
        $('#goods').bootstrapTable('refresh');
    }

    function refreshTokenGroupTable(){
        $('#tokenGroupTable').bootstrapTable('refresh');
    }

    var goodsTable = $('#goods'),
        goodsOk = $('#goodsOk'),
        tokenGroupTable = $('#tokenGroupTable'),
        tokenGroupOk = $('#tokenGroupOk');

    $(function () {
        goodsOk.click(function () {
            goodsTable.bootstrapTable('refresh');
        });
        tokenGroupOk.click(function () {
            tokenGroupTable.bootstrapTable('refresh');
        });
    });
    
    function tabQueryParams(tab, params) {
        $(tab +'Toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $(tab + ' .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $(tab + ' li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        params.group = <?= $group->getId();?>;
        
        return params;
    }
    
    function goodsQueryParams(params) {
        return tabQueryParams('#goods', params);
    }    

    function tokenGroupQueryParams(params) {
        return tabQueryParams('#tokenGroups', params);
    }    
    
    function linkFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/goods/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function aplFormatter(value, row){
        if (value != '0'){
            return [
                '<div class="pull-left">',
                '<a href="https://autopartslist.ru/goods/view/id/' + value + '" target="_blank">' + value + '</a>',
                '</div>'
            ].join(''); 
        } else {
            return '-';
        }    
    }    
    
    function producerFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + value.id + '" target="_blank">' + value.name + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function activeFormatter(value, row){
        var url = '/goods/delete-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>
