<script>
    function postMessagePartial(orderId, email){
        if (orderId){
            var url = '/post/post-form/';
            showFormDialog({
                id: 'postMessageModal',
                url: url+orderId+'?email='+email,
                zIndex: 9999,
                width: $(window).width()-150
            });
        };        
    }

    $(document).on('click', '.post-message-modal-show', function (e) {
        var orderId = $(this).attr('order-id');
        var email = $(this).attr('email');
        <?php if (!empty($idNode)):?>
            orderId = $('#<?= $idNode ?>').val();
        <?php endif; ?>    
        <?php if (!empty($emailNode)):?>
            email = $('#<?= $emailNode ?>').val();
        <?php endif; ?>    
            
        postMessagePartial(orderId, email);    
    });  
</script>