<?php

$form = $this->form;

$form->get('toEmail')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Кому',
    ]);

$form->get('fromEmail')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'От кого',
    ]);

$form->get('subject')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Тема',
    'value' => 'По заказу №'.$order->getAplId(),
    ]);

$form->get('showCode')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('bill')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('offer')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('copyMe')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('message')->setAttributes([
    'class'=>'form-control', 
    'rows' => 8
    ]);

$form->prepare();

?>

            
<?= $this->form()->openTag($form); ?>


<div class="modal-body">
    <div class="row">
        <div class="col-md-3">
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('toEmail')); ?>
                <?= $this->formElement($form->get('toEmail')); ?>
                <?= $this->formElementErrors($form->get('toEmail')); ?>                  
            </div>    
        </div>        
        <div class="col-md-3">
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('fromEmail')); ?>
                <?= $this->formElement($form->get('fromEmail')); ?>
                <?= $this->formElementErrors($form->get('fromEmail')); ?>                  
            </div>    
        </div>        
        <div class="col-md-1">
            <div class="form-group form-group-sm">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="copyMe"> Копию мне
                    </label>
                </div>
            </div>    
        </div>
        <div class="col-md-offset-2 col-md-3">
                <button type="button" class="btn btn-secondary clear-button">Очистить</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="post-submit">Отправить</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group form-group-sm">
                <?= $this->formElement($form->get('subject')); ?>
                <?= $this->formElementErrors($form->get('subject')); ?>                  
            </div>    
        </div>        
        <div class="col-md-3">
            <div class="form-group form-group-sm form-inline">
                <?//= $this->formLabel($form->get('bill')); ?>
                <?//= $this->formElement($form->get('bill')); ?>
                <?//= $this->formElementErrors($form->get('bill')); ?> 
                <?//= $this->formLabel($form->get('offer')); ?>
                <?//= $this->formElement($form->get('offer')); ?>
                <?//= $this->formElementErrors($form->get('offer')); ?>                  
                Вложить 
                <div class="checkbox">
                    <label>
                        Счет <input type="checkbox" name="bill">
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        КП <input type="checkbox" name="offer">
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        Артикул показывать <input type="checkbox" name="showCode">
                    </label>
                </div>
            </div>    
        </div>        
        <div class="col-md-2">
            <div class="form-group form-group-sm">
            </div>    
        </div>        
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group form-group-sm">
                <?= $this->formElement($form->get('message')); ?>
                <?= $this->formElementErrors($form->get('message')); ?>                  
            </div>    
        </div>        
    </div>
    <div class="row">
        <div class="col-xs-3">
            <div class="panel panel-default small">
                <div class="panel-heading">статусы заказов, информация</div>
                <div class="list-group">
                    <button type="button" class="list-group-item local-comment">№ запроса
                        <div class="text-hide">
                            Ваш запрос №<?= $order->getAplId()?>.
                                Для подтверждения заказа звоните по телефону <?= $order->getOffice()->getLegalContactPhones()?>.
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment">Заказ принят, на сборке
                        <div class="text-hide">
                            Ваш заказ №<?= $order->getAplId()?> на сумму <?= $order->getTotal()?> руб. принят.
                            <br/>Спасибо за заказ!
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment">Готов к отгр., ждет самовывоза
                        <div class="text-hide">
                            Ваш заказ №<?= $order->getAplId()?> готов к отгрузке и ожидает Вас по адресу:
                            <br/><?= $order->getOffice()->getLegalContactSmsAddress()?>,
                            <br/>тел.: <?= $order->getOffice()->getLegalContactPhones()?>
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment">№ заказа, адрес офиса
                        <div class="text-hide">
                            Ваш заказ №<?= $order->getAplId()?> на сумму <?= $order->getTotal()?> руб.
                            <br/><?= $order->getOffice()->getLegalContactSmsAddress()?>
                            <br/>тел.: <?= $order->getOffice()->getLegalContactPhones()?>
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment">На доставке
                        <div class="text-hide">
                            Ваш заказ №<?= $order->getAplId()?>. Дата доставки <?= date('d.m.y', strtotime($order->getDateShipment()))?>. Сумма к оплате <?= $order->getTotal()?> р.
                            <br/>Телефон водителя-экспедитора <?= $order->getSkiperPhone()?> <?= $order->getSkiperName()?>.
                            <br/>Спасибо за заказ!
                        </div>
                    </button>
                    <?php if ($order->getCourier()):?>
                        <button type="button" class="list-group-item local-comment">Отследить отправку СДЕК
                            <div class="text-hide">
                                Ваш заказ отправлен через ТК СДЕК. Отследить движение заказа Вы можете перейдя по ссылке <?= $order->getTrackLink()?>.
                                <br/>Спасибо за заказ! Ждем Вас снова!                       
                            </div>
                        </button>
                        <button type="button" class="list-group-item local-comment">Доставка ТК
                            <div class="text-hide">
                                Ваш заказ №<?= $order->getAplId()?> доставлен в транспортную компанию <?= $order->getCourierName()?>.
                                <br/>Номер накладной для отслеживания статуса груза: <?= $order->getTrackNumber()?>
                                <br/>Спасибо за заказ!
                            </div>
                        </button>
                    <?php endif;?>    
                    <?php if ($order->getContact()):?>
                        <button type="button" class="list-group-item local-comment">Логин, пароль
                            <div class="text-hide">
                                Данные для доступа в личный кабинет на сайте autopartslist.ru
                                <br/>Логин: <?= $order->getContact()->getPhone()->getName()?>
                                <br/>Пароль: 
                            </div>
                        </button>
                    <?php endif;?>    
                    <button type="button" class="list-group-item local-comment">Ответ по заказу или запросу
                        <div class="text-hide">
                            Ваш заказ №<?= $order->getAplId()?> поступил в обработку.
                            <br/>
                            <br/>В ближайшее время с Вами свяжется менеджер.
                            <br/>    
                            <br/><b>Внимание!</b> В связи с большим количеством заказов, возможны задержки с их обработкой. 
                            Если Вы желаете чтобы ваш заказ был обработан макимально оперативно, то рекомендуем позвонить нам 
                            и сообщить оператору присвоенный номер - <b><?= $order->getAplId()?></b>                        
                        </div>
                    </button>
                </div>
            </div>
        </div>        
        <div class="col-xs-3">
            <div class="panel panel-default small">
                <div class="panel-heading">оплаты через личный кабинет</div>
                <ul class="list-group">
                    <button type="button" class="list-group-item local-comment py-sm-0">Предоплата
                        <div class="text-hide">
                            Ваш заказ №<?= $order->getAplId()?> принят и ожидает предоплаты в размере <?= $order->getPrepay()?> руб.
                            <br/>Просмотреть содержимое заказа и оплатить его Вы можете в личном кабинете на сайте autopartslist.ru
                            <br/>Логин: <?= $order->getContact()->getPhone()->getName()?>
                            <br/>Пароль:                         
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment  py-sm-0">100% оплата
                        <div class="text-hide">
                            Ваш заказ №<?= $order->getAplId()?> принят и ожидает оплаты в размере <?= $order->getTotal()?> руб.
                            <br/>Просмотреть содержимое заказа и оплатить его Вы можете в личном кабинете на сайте autopartslist.ru
                            <br/>Логин: <?= $order->getContact()->getPhone()->getName()?>
                            <br/>Пароль:                         
                        </div>
                    </button>
                    <button type="button" class="list-group-item  py-sm-0 local-comment">Предоплата на СБ или ЛК
                        <div class="text-hide">
                            Ваш заказ №<?= $order->getAplId()?> принят и ожидает предоплаты в размере <?= $order->getPrepay()?> р.
                            <br/>
                            <br/><b>Варианты оплаты:</b>
                            <br/>1 - через личный кабинет на сайте autopartslist.ru
                            <br/>Логин: "<?= $order->getContact()->getPhone()->getName()?>"; пароль: 
                            <br/>
                            <br/>2 - на карту Сбербанка <?= $order->getOffice()->getSbCard()?>, получатель <?= $order->getOffice()->getSbOwner()?>
                            <br/>При оплате просьба в поле "Сообщение получателю" указать "<?= $order->getAplId()?>".
                            <br/>
                            <br/>Для идентификации платежа, после оплаты обязательно позвоните в офис по тел.: <?= $order->getOffice()->getLegalContactPhones()?> и сообщите об осуществлении платежа по заказу №<?= $order->getAplId()?>.
                        </div>
                    </button>
                    <button type="button" class="list-group-item  py-lg-0 local-comment">100% оплата СБ или ЛК
                        <div class="text-hide">
                            Ваш заказ №<?= $order->getAplId()?> принят и ожидает оплаты в размере <?= $order->getTotal()?> р.
                            <br/>
                            <br/><b>Варианты оплаты:</b>
                            <br/>1 - через личный кабинет на сайте autopartslist.ru
                            <br/>Логин: "<?= $order->getContact()->getPhone()->getName()?>"; пароль: 
                            <br/>
                            <br/>2 - на карту Сбербанка <?= $order->getOffice()->getSbCard()?>, получатель <?= $order->getOffice()->getSbOwner()?>
                            <br/>При оплате просьба в поле "Сообщение получателю" указать "<?= $order->getAplId()?>".
                            <br/>
                            <br/>Для идентификации платежа, после оплаты обязательно позвоните в офис по тел.: <?= $order->getOffice()->getLegalContactPhones()?> и сообщите об осуществлении платежа по заказу №<?= $order->getAplId()?>.
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment">100% оплата регионы
                        <div class="text-hide">
                            Для отправки заказа необходима 100% оплата за товар и услугу доставки до Транспортной Компании.
                            <br/>Услуги ТК оплачиваются Вами при получении заказа в офисе ТК в вашем городе.
                            <br/>
                            <br/>Ваш заказ №<?= $order->getAplId()?> принят и ожидает оплаты в размере <?= $order->getTotal()?> р. - с учетом нашей доставки (<?= $order->getShipmentTotal()?> р.) до ТК.
                            <br/>Просмотреть содержимое заказа и оплатить его Вы можете в личном кабинете на сайте autopartslist.ru
                            <br/>Логин: <?= $order->getContact()->getPhone()->getName()?>
                            <br/>Пароль: 
                        </div>
                    </button>
                </ul>
            </div>
        </div>        
        <div class="col-xs-3">
            <div class="panel panel-default small">
                <div class="panel-heading">оплаты картами</div>
                <ul class="list-group">
                    <button type="button" class="list-group-item local-comment-sb-prepay">Предоплата, ссылка на платежную форму
                        <div class="text-hide">
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment-sb-total">100% оплата, ссылка на платежную форму
                        <div class="text-hide">
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment-sb-total">100% оплата регионы, ссылка на платежную форму Сбер
                        <div class="text-hide">
                            <br/>Ваш заказ №<?= $order->getAplId()?> принят и ожидает оплаты в размере <?= $order->getTotal()?> Р - с учетом нашей доставки (<?= $order->getShipmentTotal()?> Р) до транспортной компании. Для отправки заказа необходима 100% оплата за товар и услугу доставки до транспортной компании. Услуги транспортной компании оплачиваются Вами при получении заказа в офисе транспортной компании в вашем городе.
                            <br/>Воспользуйтесь формой ниже для проведения платежа.   
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment">Предоплата на Сбер
                        <div class="text-hide">
                            Ваш заказ №<?= $order->getAplId()?> принят и ожидает предоплаты в размере <?= $order->getPrepay()?> р.
                            <br/>Номер карты Сбербанка <?= $order->getOffice()->getSbCard()?>, получатель <?= $order->getOffice()->getSbOwner()?>
                            <br/>При оплате просьба в поле "Сообщение получателю" указать "<?= $order->getAplId()?>".
                            <br/>Для идентификации платежа, после оплаты, обязательно позвоните в офис по тел.: <?= $order->getOffice()->getLegalContactPhones()?> и сообщите последние 4 цифры номера карты и имя отчество держателя карты.                        
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment">100% оплата на Сбер
                        <div class="text-hide">
                            Ваш заказ №<?= $order->getAplId()?> принят и ожидает оплаты в размере <?= $order->getTotal()?> р.
                            <br/>Номер карты Сбербанка <?= $order->getOffice()->getSbCard()?>, получатель <?= $order->getOffice()->getSbOwner()?>
                            <br/>При оплате просьба в поле "Сообщение получателю" указать "<?= $order->getAplId()?>".
                            <br/>Для идентификации платежа, после оплаты, обязательно позвоните в офис по тел.: <?= $order->getOffice()->getLegalContactPhones()?> и сообщите последние 4 цифры номера карты и имя отчество держателя карты.                        
                        </div>
                    </button>
                </ul>
            </div>
        </div>        
        <div class="col-xs-3">
            <div class="panel panel-default small">
                <div class="panel-heading">ошибки, отказы</div>
                <div class="list-group">
                    <button type="button" class="list-group-item local-comment">Ошибка телефона
                        <div class="text-hide">
                            Вами неверно указан номер телефона для связи: <?= $order->getContact()->getPhone()->getName()?>.
                            <br/>
                            <br/>Ваш запрос №<?= $order->getAplId()?>. Для подтверждения заказа звоните <?= $order->getOffice()->getLegalContactPhones()?>.
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment">Ошибка VIN
                        <div class="text-hide">
                            Указанный Вами VIN - код <?= $order->getContactCarVin()?> не пробивается.
                            <br/>
                            <br/>Просьба проверить VIN на наличие ошибок и в случае их обнаружения, прислать правильный!
                            <br/>
                            <br/>Информация о VIN - кодах:
                            <br/>
                            <br/>VIN может содержать только английские буквы и цифры в количестве 17 символов. Если автомобиль с правым рулем, то указывается FRAME - номер кузова - полностью.
                            <br/>
                            <br/>Для автомобилей следующих марок допускается указывать VIN не полностью:
                            <br/>- BMW - последние 7 символов
                            <br/>- PEUGEOT, CITROEN, DODGE, CHRYSLER, JEEP - последние 8 символов
                            <br/>
                            <br/>VIN код автомобильных марок KIA, HYUNDAI и собранных в Калининграде начинающийся с буквы X не подходит для подбора. Указываете заводской VIN - находится на свидетельстве регистрации ТС в поле "Особые отметки" и начинается с буквы K или U или Z. Запчасти на автомобили собранные на заводе ТАГАЗ подбираются ТОЛЬКО с указанием подробной информации об автомобиле!
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment">Пришлите VIN
                        <div class="text-hide">
                            Для проверки правильности подбора пришлите VIN-код автомобиля.   
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment">Нет в наличии
                        <div class="text-hide">
                            К сожалению, нужного Вам товара нет в наличии.
                        </div>
                    </button>
                    <button type="button" class="list-group-item local-comment">Авто помойка
                        <div class="text-hide">
                            К сожалению, в связи с отсутствием каталогов, подобрать запчасти на Ваш автомобиль не представляется возможным.
                        </div>
                    </button>
                </div>
            </div>
        </div>        
    </div>
</div>    

<?= $this->form()->closeTag(); ?>

<div class="text-hide" id="mail-welcome">
    Здравствуйте, <strong class="text-capitalize"><?= $order->getContact()->getName();?></strong>!
    <br/><br/>
</div>
<div class="text-hide" id="mail-info">
    Вы заказывали: <br/><?= $order->getInfo();?>
    <br/><br/>
</div>
            
<script>    
    var $bodyEditor = $('textarea[name="message"]');
    var $showCode = $('input[name="showCode"]');
    var $currentNode = null;
    
    $( document ).ready(function() {
        $bodyEditor.summernote({
            lang: 'ru-RU', // default: 'en-US'
            height: 200
        });
        
    });
    
    function renderBody(sberForm = '<br/><br/>'){
        let welcome = $('#mail-welcome').html();
        let info = $('#mail-info').html();
        let str = $currentNode.children('.text-hide').html();
        $.get('/post/order-body/<?= $order->getId()?>?showCode='+$showCode.prop('checked'), function( data ) {                
            $bodyEditor.summernote('code', welcome + info + data.body + '<br/><br/>' + $.trim(str) + sberForm + data.sign);
        });        
    }
    
    $showCode.on('click', function(){
        if ($currentNode){
            renderBody();
        }    
    });
        
    $('.local-comment').on('click', function() {
        $currentNode = $(this);
        renderBody();
    });
    
    $('.local-comment-sb-prepay').on('click', function() {
        let prepay = prompt("Сумма предоплаты", "<?= $order->getPrepay()?>");
        $currentNode = $(this);
        if (prepay !== null) {
            $.get('/post/sber-form/<?= $order->getId()?>?prepay='+prepay, function( data ) {
                renderBody(data);
            });
        }            
    });    
    
    $('.local-comment-sb-total').on('click', function() {
        $currentNode = $(this);
        $.get('/post/sber-form/<?= $order->getId()?>?prepay='+<?= $order->getTotal()?>, function( data ) {
            renderBody(data);
        });
    });    
    
    $('.clear-button').on('click', function() {
        $bodyEditor.summernote('code', '');
    });

    $('#post-submit').on('click', function() {
        $.post( "/post/send", $('#post-form').serialize())
          .done(function( data ) {
            $('#postMessageModal').modal('hide');
            alert(data.result);
//            console.log(data);
          })
        .fail(function(data) {
            alert( "Не ушло!" );
            console.log(data);
        });      
    });    
</script>