<script>
    $(document).on('click', '.post-message-modal-show', function (e) {
        var orderId = $(this).attr('order-id');
        var email = $(this).attr('email');
        <?php if ($idNode):?>
            orderId = $('#<?= $idNode ?>').val();
        <?php endif; ?>    
        <?php if ($emailNode):?>
            email = $('#<?= $emailNode ?>').val();
        <?php endif; ?>    
        if (orderId){
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'postMessageModal',
                url: url+orderId+'?email='+email,
                zIndex: 9999,
                width: $(window).width()-150
            });
        }    
    });  
</script>