<script>
$(document).on('click', '.post-message-modal-show', function (e) {
    let orderId = $('#<?= $idNode ?>').val();
    let email = $('#<?= $emailNode ?>').val();
    if (orderId){
        var url = $(e.currentTarget).attr('modal-url');
        showFormDialog({
            id: 'postMessageModal',
            url: url+orderId+'?email='+email,
            zIndex: 9999,
            width: $(window).width()-150
        });
    }    
});  

</script>