<?php
use Application\Entity\Client;
use Laminas\Json\Encoder;

$this->headTitle('Покупатели');

$this->mainMenu()->setActiveItemId('client');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Продажи'=>$this->url('order'),
            'Покупатели'=>$this->url('client'),
            ]);
?>
<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <div class='btn-group'>
                        <input name="search" style="width: 400px" class="form-control enter-search" type="text" placeholder="Поиск по заказу, инн, телефону, email, aplId">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>    
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
                <div class="form-group">
                    <select id="pricecolSelect" name="pricecol" style="width: 150px" class="form-control cookie-control">
                        <option selected>все цены</option>
                        <?php foreach (Client::getPricecolList() as $key=>$value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <button value="/client/update-balances/" class="btn btn-default refresh-table-button"
                        title="Пересчитать суммы долгов">
                    <span class="glyphicon glyphicon-rub" ></span>
                </button>                         
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/client/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-cookie="true"
            data-cookie-id-table="clientSaveId"
            data-cookie-expire="1m"
            data-classes = "table table-bordered table-hover table-condensed"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true" data-width="100">ID</th>
                     <th data-field="aplId" data-formatter="aplFormatter" data-type="numeric" data-width="100" data-sortable="true">AplId</th>
                     <th data-field="name" data-formatter="linkFormatter" data-sortable="true">Имя</th>
                     <th data-field="balance" data-sortable="true" data-align="right" data-width="150" data-formatter="amountFormatter">Долг</th>
                     <th data-field="pricecol" data-sortable="false" data-width="10" data-formatter="pricecolFormatter">Цены</th>
                     <th data-field="" data-width="5" data-formatter="activeFormatter" data-widtn="5"></th>
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Всего клиентов
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?= $total?>
                        </div>
                        <div class="pull-right">
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table').bootstrapTable({
        onLoadSuccess: function(res){
//            $('#totalRow').html($('#table').bootstrapTable('getOptions').totalRows);
            $("[data-toggle='tooltip']").tooltip();
            $('.editableCheckBox').change(function() {
                $.ajax({
                    type: "POST",
                    url: $(this).attr('data-url'),
                    data: "pk="+$(this).attr('data-pk'),
                    success: function(msg){
//                      alert( "Прибыли данные: " + msg );
                    }
                });
            })        
        }
    });

    $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            refreshTable();
        });

        $(".inputclear").click(function(){
            $(".enter-search").val('');
            refreshTable();
        });

        $(document).on('change', '#pricecolSelect', function (e) {
            refreshTable();
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/client/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function aplFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="https://autopartslist.ru/admin/users/users-view/id/' + value + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    
    
    function pricecolFormatter(value, row){
        var pricecols = <?= Encoder::encode(Client::getPricecolList())?>;
        return '<nobr>'+pricecols[value]+'</nobr>';
    }
    
    function activeFormatter(value, row){
        var url = '/client/delete-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function statusFormatter(value, row){
        var checked = 'checked';
        if (value == <?= Client::STATUS_RETIRED?>){
            checked = '';
        }
        return [
            '<input data-toggle="tooltip" class="editableCheckBox" \n\
                data-pk="'+row.id+'" data-url="/client/producer-status-edit" type="checkbox" '+checked+'/>'
        ].join(''); 
    }     
    
    function responseHandler(res) {
        return res;
    }    
</script>


