<?php
use Application\Entity\Client;
use Laminas\Json\Encoder;

$this->headTitle('Покупатели');

$this->mainMenu()->setActiveItemId('client');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Продажи'=>$this->url('order'),
            'Покупатели'=>$this->url('client'),
            ]);
?>
<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <div class='btn-group'>
                        <input name="search" style="width: 400px" class="form-control enter-search" type="text" onfocus="this.select();" placeholder="Поиск по заказу, инн, телефону, email, aplId">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>    
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
                <div class="form-group">
                    <select id="pricecolSelect" name="pricecol" style="width: 150px" class="form-control cookie-control">
                        <option selected>все цены</option>
                        <?php foreach (Client::getPricecolList() as $key=>$value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="legalSelect" name="legal" style="width: 150px" class="form-control cookie-control">
                        <option value="0" selected>все</option>
                        <option value="1">юр. лица</option>
                    </select>                    
                </div>    
                <button value="/client/update-balances/" class="btn btn-default refresh-table-button"
                        title="Пересчитать суммы долгов">
                    <span class="glyphicon glyphicon-rub" ></span>
                </button>                         
<!--                <button value="/revise/reset-client-balances?year=2020" class="btn btn-default refresh-table-button"
                        title="Обнулить старые долги">
                    <span class="glyphicon" ></span>0-2020
                </button>                         -->
                <button value="/contact/delete-empty-contacts/" class="btn btn-default refresh-table-button"
                        title="Очистить пустые контакты">
                    <span class="glyphicon glyphicon-trash" ></span>
                </button>                         
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/client/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-cookie="true"
            data-cookie-id-table="clientSaveId"
            data-cookie-expire="1m"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="rowStyle"
            data-show-footer="true"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true" data-width="100">ID</th>
                     <th data-field="aplId" data-formatter="aplFormatter" data-type="numeric" data-width="100" data-sortable="true">AplId</th>
                     <th data-field="name" data-formatter="linkFormatter" data-sortable="true">Имя</th>
                     <!--<th data-field="balance" data-sortable="true" data-align="right" data-width="150" data-formatter="amountFormatter">Долг</th>-->
                     <th data-field="balance" data-footer-formatter="footerCreditFormatter" data-formatter="creditFormatter" data-align="right" data-width="100" data-original-title="Мы должны" data-sortable="true">Мы должны</th>
                     <th data-field="balance" data-footer-formatter="footerDebitFormatter" data-formatter="debitFormatter" data-align="right" data-width="100" data-original-title="Нам должны" data-sortable="true">Нам должны</th>
                     <th data-field="balanceDate" data-sortable="true" data-align="center" data-width="100" data-formatter="dateFormatter">Дата долга</th>
                     <th data-field="pricecol" data-sortable="false" data-width="100" data-formatter="pricecolFormatter">Цены</th>
                     <!--<th data-field="" data-width="5" data-formatter="activeFormatter" data-widtn="5"></th>-->
                 </tr>                
            </thead>
        </table>
    </div>
<!--    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Всего клиентов
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?= $total?>
                        </div>
                        <div class="pull-right">
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>-->
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

//    var table = $('#table').bootstrapTable();

    $ok = $('#ok');

    function rowStyle(row){
        var retired = 'tablerow';
        
        return {classes: retired};
    }

    $(function () {
        $ok.click(function () {
            refreshTable();
        });

        $('#table').on('load-success.bs.table', function (e, res) {
//            $('#totalRow').html($('#table').bootstrapTable('getOptions').totalRows);
            tableRowClick();
            var inTotal = (res.balanceIn) ? res.balanceIn:0;
            var outTotal = (res.balanceOut) ? res.balanceOut:0;
            $('#inTotalFooter').html((Math.round(inTotal*100)/100).toFixed(2));
            $('#outTotalFooter').html((Math.round(outTotal*100)/100).toFixed(2));
        });        

        $(".inputclear").click(function(){
            $(".enter-search").val('');
            refreshTable();
        });

        $(document).on('change', '#pricecolSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#legalSelect', function (e) {
            refreshTable();
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        if (row.contacts){
            var names = [];
            $.each(row.contacts, function( index, contact ) {
                if (contact.legals){
                    $.each(contact.legals, function( index, legal ) {
                        names.push(legal.name); 
                    });
                }
            });            
            value = '<small><span class="muted">'+names.join('<br/>')+'</span><small>';
        };
        return [
            '<div class="pull-left">',
            '<a href="/client/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function aplFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="https://autopartslist.ru/admin/users/users-view/id/' + value + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    

    function contractsBalance(row){
        var result = 0;
        if (row.contacts){
            $.each(row.contacts, function( index, contact ) {
                if (contact.legals){
                    $.each(contact.legals, function( index, legal ) {
                        $.each(legal.contracts, function( index, contract ) {
                            result += contract.balance;
                        });
                    });
                }
            });            
        };
        
        return result;
    }
    
    function creditFormatter(value, row){
        var result = value;
        if ($('#legalSelect').val() === '1'){
            console.log(1);
            result = contractsBalance(row);
        }    
        if (result<0){
            return (-Math.round(result*100)/100).toFixed(2);
        }
        return '';
    }
    function debitFormatter(value, row){
        var result = value;
        if ($('#legalSelect').val() === '1'){
            console.log(1);
            result = contractsBalance(row);
        }    
        if (result>0){
            return (Math.round(result*100)/100).toFixed(2);
        }
        return '';
    }
    
    function footerDebitFormatter(data){
        return '<span id="inTotalFooter"></span>';
    }

    function footerCreditFormatter(data){
        return '<span id="outTotalFooter"></span>';
    }
    
    function dateFormatter(value, row){
        if (value){
            return '<nobr>'+$.format.date(value+' 00:00:00', "dd.MM.yy")+'</nobr>';        
        }
        
        return '';
    }
    
    function pricecolFormatter(value, row){
        var pricecols = <?= Encoder::encode(Client::getPricecolList())?>;
        return '<nobr>'+pricecols[value]+'</nobr>';
    }
    
    function activeFormatter(value, row){
        var url = '/client/delete-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function statusFormatter(value, row){
        var checked = 'checked';
        if (value == <?= Client::STATUS_RETIRED?>){
            checked = '';
        }
        return [
            '<input data-toggle="tooltip" class="editableCheckBox" \n\
                data-pk="'+row.id+'" data-url="/client/producer-status-edit" type="checkbox" '+checked+'/>'
        ].join(''); 
    }     
    
    function responseHandler(res) {
        return res;
    }    
</script>


