<?php
$this->headTitle('Покупатели');

$this->mainMenu()->setActiveItemId('client');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Управление покупателями'=>$this->url('client'),
            ]);
?>
<h1>Покупатели</h1>
<p>
    <a class="btn btn-default" href="
        <?= $this->url('client', ['action'=>'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Новый покупатель
    </a>      
    
    <?php if ($currentClient): ?>
       <span class="alert alert-success">
            Текущий клиент для работы в каталоге: <?= $currentClient->getName(); ?>
       </span>    
    <?php else: ?>
       <span class="alert alert-warning">
            Текущий клиент для работы в каталоге не установлен
       </span>    
    <?php endif; ?>    
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Наименование</th>
        <th>Статус</th>
        <th>Ответственный</th>
        <th>Действие</th>
    </tr>
    
    <?php foreach ($client as $row): ?>
    
    <tr>
        <td><?= $this->escapeHtml($row->getId()); ?></td>
        <td>
            <a href="<?= $this->url('client', ['action'=>'view', 'id'=>$row->getId()]); ?>">
                <?= $this->escapeHtml($row->getName()); ?>
            </a> 
        </td>
        <td>
            <?= $this->escapeHtml($row->getStatusAsString()); ?>
        </td>
        <td>
            <a href="<?= $this->url('members', ['action'=>'view', 'id'=>$row->getManager()->getId()]); ?>">
                <?= $this->escapeHtml($row->getManager()->getFullName()); ?>
            </a> 
        </td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('client', 
                    ['action'=>'edit', 'id'=>$row->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Изменить
            </a>
            <a class="btn btn-danger" href="<?= $this->url('client',
                    ['action'=>'delete', 'id'=>$row->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Удалить
            </a>
            <a class="btn btn-info" href="<?= $this->url('client',
                    ['action'=>'set-current-client', 'id'=>$row->getId()]); ?>">
                <span class="glyphicon glyphicon-set"></span> Текущий
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>
<?= $this->paginationControl($client,
            'Sliding',
            'application/partial/paginator', 
            ['route' => array('route' => 'client')]); ?>

