<?php
$this->headTitle($client->getName());

$this->mainMenu()->setActiveItemId('client');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Покупатели'=>$this->url('client'),
            $client->getName()=>$this->url('client', ['action'=>'view', 'id'=>$client->getId()])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$this->headTitle($client->getName());
        
$form = $this->form;

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Имя'
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Должность и т.п.'
    ]);

$form->get('phone')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Телефон'
    ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Пароль'
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>
    <?= $this->escapeHtml($client->getName()); ?>    
</h1>


<p>    
    <?= $this->escapeHtml($client->getStatusAsString()); ?>
</p>

<h3 class="contact-header">Контакты</h3>
<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Имя</th>
        <th>Телефон</th>
        <th>Описание</th>
        <th>Доступ</th>
        <th>Действие</th>
    </tr>
    
    <?php foreach ($client->getContacts() as $row): ?>
    
    <tr>
        <td><?= $this->escapeHtml($row->getId()); ?></td>
        <td>
                <?= $this->escapeHtml($row->getName()); ?>
        </td>
        <td><?= $this->escapeHtml($row->getPhonesAsString()); ?></td>
        <td>
                <?= $this->escapeHtml($row->getDescription()); ?>
        </td>
        <td>
                <?= ($row->getUser() ? 'есть':'нет') ?>
        </td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('contact', 
                    ['action'=>'edit', 'id'=>$row->getId()],['query' => ['client' => $client->getId()]]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Изменить
            </a>
            <a class="btn btn-danger" href="<?= $this->url('client',
                    ['action'=>'delete-contact', 'id'=>$row->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Удалить
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

<h3 class="contact-header">Добавить контакт</h3>

<div class="row">
    <div class="col-md-8">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('phone')); ?>
            <?= $this->formElement($form->get('phone')); ?>
            <?= $this->formElementErrors($form->get('phone')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>
