<?php
use Application\Entity\Order;
use Application\Entity\ContactCar;
use Laminas\Json\Encoder;
use Stock\Entity\Vt;
use Stock\Entity\Retail;
use Stock\Entity\Movement;
use Stock\Entity\Revise;
use Cash\Entity\CashDoc;

$this->headTitle(ucfirst($client->getName()));

$this->mainMenu()->setActiveItemId('client');

$this->mainMenu()->setActiveUrl('client');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Покупатели'=>$this->url('client'),
            $client->getName()=>$this->url('client', ['action'=>'view', 'id'=>$client->getId()]),
            ]);

$legalContact = $client->getLegalContact();

?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<!--<h1 style="text-transform: capitalize">
</h1>-->

<div class="row">
    <div class="col-md-12">
        <ul class="nav nav-tabs" id="featureTab" role="tablist">
            <li role="presentation"><a href="#contacts" role="tab" id="contact-tab" data-toggle="tab" aria-controls="contacts" aria-expanded="true"><span style="text-transform: capitalize"><?= $this->escapeHtml($client->getName()); ?></span> <span id="contactBadge" class="badge"></span></a></li>
            <li role="presentation"><a href="#orders" role="tab" id="order-tab" data-toggle="tab" aria-controls="orders" aria-expanded="true">Заказы <span id="orderBadge" class="badge"></span></a></li>
            <li role="presentation"><a href="#mutuals" role="tab" id="mutual-tab" data-toggle="tab" aria-controls="mutual" aria-expanded="true">Финансы <span id="mutualBadge" class="badge"></span></a></li>
            <li role="presentation"><a href="#vt" role="tab" id="vt-tab" data-toggle="tab" aria-controls="vt" aria-expanded="true">Возвраты <span id="vtBadge" class="badge"></span></a></li>
            <li role="presentation"><a href="#comiss" role="tab" id="comiss-tab" data-toggle="tab" aria-controls="comiss" aria-expanded="true">Комиссия <span id="comissBadge" class="badge"></span></a></li>
            <li role="presentation"><a href="#cars" role="tab" id="car-tab" data-toggle="tab" aria-controls="cars" aria-expanded="true">Машины <span id="carBadge" class="badge"></span></a></li>
            <li role="presentation"><a href="#comments" role="tab" id="comment-tab" data-toggle="tab" aria-controls="comment" aria-expanded="true">Комментарии <span id="commentBadge" class="badge"></span></a></li>
        </ul>        
    </div>
    <div class="tab-content" id="featureTabContent">
        <div class="tab-pane fade" role="tabpanel" id="contacts" aria-labelledby="contact-tab">
            <div class="clearfix"></div>
            <div class="panel panel-body">
                <div class="row">
                    <div class="col-md-3">
                        <table class="table table-bordered table-hover table-condensed">
                            <tr>
                                <td width="100%">
                                    <div class="pull-left">
                                        <?php if ($legalContact):?>
                                            <button value="/contact/phone-form/<?= $legalContact->getId() ?>" class="btn btn-default btn-xs"
                                                    data-toggle="modal" data-target="#modal-dialog" title="Добавить телефон">
                                                <span class="glyphicon glyphicon-phone-alt"></span> <span class="glyphicon glyphicon-plus"></span>
                                            </button>
                                        <?php endif; ?>                        
                                    </div>    
                                </td>
                            </tr>
                            <?php foreach ($client->getContacts() as $contact): ?>
                                <?php foreach ($contact->getPhones() as $phone): ?>
                                    <tr>
                                        <td>
                                            <div class="pull-left">
                                                <?= $phone->getName()?> <span><?= $phone->getComment()?></span>                                            
                                            </div>
                                            <div class="pull-right">
                                                <button value="/contact/phone-form/<?= $contact->getId() ?>?phone=<?= ($phone ? $phone->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                                        data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                                    <span class="glyphicon glyphicon-edit"></span>
                                                </button>                                                            
                                                <button value="/contact/delete-phone-form/<?= $phone->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                        title="Удалить">
                                                    <span class="glyphicon glyphicon-remove" ></span>
                                                </button>                                                           
                                            </div>    
                                        </td>
                                    </div>
                                <?php endforeach?>    
                            <?php endforeach;?>   
                        </table>
                    </div>
                    <div class="col-md-3">
                        <table class="table table-bordered table-hover table-condensed">
                            <tr>
                                <td width="1005">
                                    <div class="pull-left">
                                        <?php if ($legalContact):?>
                                            <button value="/contact/email-form/<?= $legalContact->getId() ?>" class="btn btn-default btn-xs"
                                                    data-toggle="modal" data-target="#modal-dialog" title="Добавить email">
                                                <span class="glyphicon glyphicon-envelope"></span> <span class="glyphicon glyphicon-plus" ></span>
                                            </button>                                        
                                        <?php endif; ?>
                                    </div>    
                                </td>
                            </tr>
                            <?php foreach ($client->getContacts() as $contact): ?>
                                <?php foreach ($contact->getEmails() as $email): ?>
                                    <tr>
                                        <td>
                                            <div class="pull-left">
                                                <?= $email->getName()?>
                                            </div>    
                                            <div class="pull-right">
                                                <button value="/contact/email-form/<?= $contact->getId() ?>?email=<?= ($email ? $email->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                                        data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                                    <span class="glyphicon glyphicon-edit" ></span>
                                                </button>                                                            
                                                <button value="/contact/delete-email-form/<?= $email->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                        title="Удалить">
                                                    <span class="glyphicon glyphicon-remove" ></span>
                                                </button>                                                           
                                            </div>    
                                        </td>
                                    </div>
                                <?php endforeach?>    
                            <?php endforeach;?>
                        </table>
                    </div>    
                    <div class="col-md-2">
                        <table class="table table-bordered table-hover table-condensed">
                            <tr>
                                <td width="100%">
                                    <div class="pull-left">
                                        <a href="https://autopartslist.ru/admin/users/users-view/id/<?= $client->getAplId()?>" target="_blank">АПЛ id: <?= $client->getAplId()?></a>                                    
                                    </div>
                                    <div class="pull-right">
                                        <button value="/client/apl-union/<?= $client->getId()?>" class="btn btn-warning btn-xs refresh-table-button"
                                                title="Объеденить по коду Апл">
                                            <span class="glyphicon glyphicon-refresh" ></span>
                                        </button>                                     
                                    </div>
                                </td>
                            </tr>
                        </table>    
                    </div>
                </div> 
            </div>
            <div class="row">        
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <?php foreach ($client->getContacts() as $contact):?>
                            <?php echo $this->partial('/company/legal/partial-view', ['legalContact' => $contact, 'client' => $client]); ?>
                        <?php endforeach;?>
                    </div>                        
                </div>
            </div>
        </div>    
        <div class="tab-pane fade" role="tabpanel" id="orders" aria-labelledby="order-tab">
            <div id="ordertoolbar">
                <div class="form-inline" role="form">
                    <div class="form-group">
                        <select id="clientOrderStatusSelect" style="width: 200px" class="form-control cookie-control" name="status">
                            <option>все</option>
                            <?php foreach (Order::getStatusList() as $key=>$value):?>
                                <option value="<?= $key?>"><?= $value?></option>
                            <?php endforeach;?>
                        </select>
                    </div>    
                </div>    
            </div>
            <table id="table" 
                data-toggle="table" 
                data-side-pagination="server"
                data-pagination="true" 
                data-url="/order/content"
                data-cookie="true"
                data-cookie-id-table="clientOrdersSaveId"
                data-cookie-expire="1m"
                data-page-list="[5, 10, 20, 50]"
                data-toolbar="#ordertoolbar"
                data-show-refresh="true"
                data-show-toggle="false"
                data-show-columns="false"
                data-query-params="orderQueryParams"
                data-sort-name="dateOper"
                data-sort-order="desc"            
                data-response-handler="responseHandler"
                data-classes = "table table-bordered table-hover table-condensed"
                data-row-style="rowStyle"
                data-unique-id="id"
                data-icon-size="sm"
                >
                <thead>
                    <tr>
                        <th data-field="dateOper" data-sortable="true" data-width="50" data-formatter="dateFormatter">Дата</th>
                        <th data-field="id" data-sortable="false" data-formatter="docFormatter" data-width="50">Номер</th>
                        <th data-field="office.name" data-sortable="false" data-width="50">Офис</th>
                        <th data-field="contact.name" data-sortable="false" data-formatter="clientFormatter">Покупатель</th>
                        <th data-field="info" data-sortable="false" data-formatter="infoFormatter">Что нужно</th>
                        <th data-field="contactCar.vin" data-sortable="false" data-formatter="carFormatter">Машина</th>
                        <th data-field="address" data-sortable="false" data-formatter="shippingFormatter">Доставка</th>
                        <th data-field="dependInfo" data-sortable="false" data-formatter="commentFormatter">Комментарий</th>
                        <th data-field='total' data-sortable="false" data-align="right" data-formatter="inFormatter" data-width="100">Сумма</th>
                        <th data-field='user.fullName' data-sortable="false" data-width="50">Отв.</th>
                     </tr>                
                </thead>
            </table>
        </div>    
        <div class="tab-pane fade" role="tabpanel" id="comments" aria-labelledby="comment-tab">
            <table id="commenttable" 
                data-toggle="table" 
                data-side-pagination="server"
                data-pagination="true" 
                data-url="/comments/content"
                data-cookie="true"
                data-cookie-id-table="clientCommentsSaveId"
                data-cookie-expire="1m"
                data-page-list="[5, 10, 20, 50]"
                data-toolbar="#commenttoolbar"
                data-show-refresh="true"
                data-show-toggle="false"
                data-show-columns="false"
                data-query-params="commentQueryParams"
                data-sort-name="id"
                data-sort-order="desc"            
                data-response-handler="responseHandler"
                data-classes = "table table-bordered table-hover table-condensed"
                data-unique-id="id"
                data-icon-size="sm"
                >
                <thead>
                    <tr>
                     <th data-field="id" data-type="numeric" data-width="75">ID</th>
                     <th data-field="dateCreated" data-width="50" data-formatter="dateFormatter">Дата</th>
                     <th data-field="order.id" data-formatter="docFormatter" data-width="100">Заказ</th>
                     <th data-field="comment" data-sortable="true" data-formatter="textFormatter">Комментарий</th>
                     <th data-field="user.fullName" data-width="100">Автор</th>
                     </tr>                
                </thead>
            </table>
        </div>    
        <div class="tab-pane fade" role="tabpanel" id="cars" aria-labelledby="car-tab">
            <div id="cartoolbar">
                <div class="form-inline" role="form">
                    <button value="/garage/edit-form/?contact=<?= $legalContact->getId()?>" class="btn btn-default btn-sm"
                            data-toggle="modal" data-target="#modal-dialog" <?= ($legalContact) ? '':'disabled'?> title="Добавить машину">
                        <span class="glyphicon glyphicon-plus" ></span>
                    </button>                                        
                </div>
            </div>
            <table id="cartable" 
                data-toggle="table" 
                data-side-pagination="server"
                data-pagination="true" 
                data-url="/garage/content"
                data-cookie="true"
                data-cookie-id-table="clientCarsSaveId"
                data-cookie-expire="1m"
                data-page-list="[5, 10, 20, 50]"
                data-toolbar="#cartoolbar"
                data-show-refresh="true"
                data-show-toggle="false"
                data-show-columns="false"
                data-query-params="carQueryParams"
                data-sort-name="id"
                data-sort-order="desc"            
                data-response-handler="responseHandler"
                data-classes = "table table-bordered table-hover table-condensed"
                data-unique-id="id"
                data-icon-size="sm"
                >
                <thead>
                    <tr>
                     <th data-field="id" data-type="numeric" data-width="5">ID</th>
                     <th data-field="vin" data-width="250" data-formatter="vinFormatter">VIN</th>
                     <th data-field="make" data-width="200" data-formatter="carFormatter">Машина</th>
                     <th data-field="yocm" data-width="10">Год</th>
                     <th data-field="wheel" data-width="10" data-formatter="wheelFormatter">Руль</th>
                     <th data-field="tm" data-width="10" data-formatter="tmFormatter">Коробка</th>
                     <th data-field="ac" data-width="10" data-formatter="acFormatter">Кондиционер</th>
                     <th data-field="md" data-width="10">Двигатель</th>
                     <th data-field="ed" data-width="10">Объем</th>
                     <th data-field="ep" data-width="10">Мощность</th>
                     <th data-field="comment">Комментарий</th>
                     <th data-field="id" data-formatter="carEditFormatter" data-width="5"></th>
                     </tr>                
                </thead>
            </table>
        </div>    
        <div class="tab-pane fade" role="tabpanel" id="vt" aria-labelledby="vt-tab">
            <table id="vttable" 
                data-toggle="table" 
                data-url="/vt/content/"
                data-side-pagination="server"
                data-pagination="true" 
                data-cookie="true"
                data-cookie-id-table="clientVtSaveId"
                data-cookie-expire="1m"
                data-page-list="[5, 10, 20, 50]"
                data-toolbar="#vttoolbar"
                data-show-refresh="true"
                data-show-toggle="false"
                data-query-params="vtQueryParams"
                data-sort-name="docDate"
                data-sort-order="desc"            
                data-response-handler="responseHandler"
                data-classes = "table table-bordered table-hover table-condensed"
                data-row-style="vtRowStyle"
            >
                <thead>
                    <tr>
                         <th data-field="id" data-sortable="false" data-formatter="idFormatter" data-width="120">Номер</th>
                         <th data-field="docDate" data-sortable="true" data-width="100" data-formatter="vtDateFormatter">Дата</th>
                         <th data-field='amount' data-sortable="false" data-type="numeric" data-align="right" data-formatter="inFormatter">Сумма</th>
                         <th data-field='order.id' data-sortable="false" data-formatter="docFormatter">Заказ</th>
                         <th data-field='office.name' data-sortable="false">Склад</th>
                         <th data-field='comment' data-sortable="false">Примечание</th>
                         <th data-field="" data-formatter="vtActiveFormatter" data-width="10"></th>
                     </tr>                
                </thead>
            </table>    
        </div>    
        <div class="tab-pane fade" role="tabpanel" id="mutuals" aria-labelledby="mutual-tab">
            <div id="mutualtoolbar">
                <div class="form-inline" role="form">
                    <button class="btn btn-default btn-sm revise-modal-show" type="button" modal-url="/revise/edit-form?client=<?= $client->getId()?>&kind=<?= Revise::KIND_REVISE_CLIENT?>">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </button>                
                </div>
            </div>
            <table id="mutualtable" 
                data-toggle="table" 
                data-side-pagination="server"
                data-pagination="true" 
                data-url="/client/retails/<?= $client->getId()?>"
                data-cookie="true"
                data-cookie-id-table="clientMutualsSaveId"
                data-cookie-expire="1m"
                data-page-list="[5, 10, 15, 20, 50]"
                data-toolbar="#mutualtoolbar"
                data-show-refresh="true"
                data-show-toggle="false"
                data-show-columns="false"
                data-query-params="mutualsQueryParams"
                data-sort-name="docStamp"
                data-sort-order="desc"            
                data-response-handler="responseHandler"
                data-classes = "table table-bordered table-hover table-condensed"
                data-unique-id="id"
                data-icon-size="sm"
                data-row-style="mutualRowStyle"
                data-undefined-text = ""
                >
                <thead>
                    <tr>
                        <th data-field="docStamp" data-width="80" data-sortable="true" data-formatter="docStampFormatter">Дата</th>
                        <th data-field="amount" data-type="numeric" data-align="right" data-width="30" data-formatter="inFormatter">Отгрузка</th>
                        <th data-field="amount" data-type="numeric" data-align="right" data-width="30" data-formatter="outFormatter">Оплата</th>
                        <th data-field="rest" data-type="numeric" data-align="right" data-formatter="restFormatter" data-width="30">Баланс</th>
                        <th data-field="docKey" data-formatter="docKeyFormatter">Документ</th>
                        <th data-field="contract.name">Договор</th>
                        <th data-field="office.name" data-width="50">Офис</th>
                        <th data-field="company.name" data-width="150">ЮЛ</th>
                    </tr>                
                </thead>
            </table>
        </div>    
        <div class="tab-pane fade" role="tabpanel" id="comiss" aria-labelledby="comiss-tab">
            <table id="comisstable" 
                data-toggle="table" 
                data-side-pagination="server"
                data-pagination="true" 
                data-url="/client/comiss/<?= $client->getId()?>"
                data-cookie="true"
                data-cookie-id-table="clientComissSaveId"
                data-cookie-expire="1m"
                data-page-list="[5, 10, 15, 20, 50]"
                data-toolbar="#comisstoolbar"
                data-show-refresh="true"
                data-show-toggle="false"
                data-show-columns="false"
                data-query-params="comissQueryParams"
                data-sort-name="dateOper"
                data-sort-order="desc"            
                data-response-handler="responseHandler"
                data-classes = "table table-bordered table-hover table-condensed"
                data-unique-id="id"
                data-icon-size="sm"
                data-row-style="comissRowStyle"
                >
                <thead>
                    <tr>
                        <th data-field="dateOper" rowspan="2" data-width="80" data-sortable="true" data-formatter="dateFormatter">Дата</th>
                        <th data-field="good.code" rowspan="2" data-formatter="goodFormatter" data-width="50">Артикул</th>
                        <th data-field="good.producer.name" rowspan="2" data-width="50">Производитель</th>
                        <th data-field="good.name" rowspan="2" data-formatter="goodNameFormatter">Наименование</th>
                        <th colspan="2">Поступило</th>
                        <th colspan="2">Списано</th>
                        <th colspan="2">Остаток</th>
                        <th data-field="docKey" rowspan="2" data-formatter="docKeyFormatter">Документ</th>
                        <th data-field="office.name" rowspan="2" data-width="50">Офис</th>
                        <th data-field="company.name" rowspan="2" data-width="150">ЮЛ</th>
                    </tr>                
                    <tr>
                        <th data-field="quantity" data-type="numeric" data-align="right" data-width="30" data-formatter="inQuantityFormatter">Количество</th>
                        <th data-field="amount" data-type="numeric" data-align="right" data-width="30" data-formatter="inFormatter">Сумма</th>
                        <th data-field="quantity" data-type="numeric" data-align="right" data-width="30" data-formatter="outQuantityFormatter">Количетсво</th>
                        <th data-field="amount" data-type="numeric" data-align="right" data-width="30" data-formatter="outFormatter">Сумма</th>
                        <th data-field="rest.quantity" data-type="numeric" data-align="right" data-formatter="restQuantityFormatter" data-width="30">Количетсво</th>
                        <th data-field="rest.amount" data-type="numeric" data-align="right" data-formatter="restFormatter" data-width="30">Сумма</th>
                    </tr>                
                </thead>
            </table>
        </div>    
    </div>
</div>

<?php echo $this->partial('/stock/index/stock-partial', []); ?>
<?php echo $this->partial('/application/order/comment-partial', []); ?>

<script type="text/javascript">
    var $table = $('#table').bootstrapTable();
    
    function setCookies(cookieKey){
        let expires = 30;
        $('.cookie-control').each(function () {
            Cookies.set(cookieKey+'_'+$(this).attr('id'), $(this).val(), { expires: expires});        
        });        
    }
    
    function getCookies(cookieKey){
        $('.cookie-control').each(function () {
            var cookieVal = Cookies.get(cookieKey+'_'+$(this).attr('id'));
            if (cookieVal !== undefined){
                $(this).val(cookieVal);                
            }
        });     
        var activeTab = Cookies.get('clientSaveId_tab');
        if (activeTab !== undefined){
            $('.nav-tabs #'+activeTab).tab('show');
        } else {
            $('.nav-tabs a:first').tab('show');
        }    
    }    

    $(window).on('load', function() {
        getCookies('clientSaveId');
        
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            Cookies.set('clientSaveId_tab', $(this).attr('id'), { expires: 30});
        });        

        $(document).on('change', '#clientOrderStatusSelect', function (e) {
            $('#table').bootstrapTable('refresh');
        });        
    });

    function orderQueryParams(params) {
        $('#ordertoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#ordertoolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        params.client = <?= $client->getId()?>;
        return params;
    }    

    function commentQueryParams(params) {
        $('#commenttoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#commettable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#commenttable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        params.client = <?= $client->getId()?>;
        return params;
    }    

    function carQueryParams(params) {
        $('#cartoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#cartable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#cartable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        params.client = <?= $client->getId()?>;
        return params;
    }    

    function vtQueryParams(params) {
        $('#vttoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#vttable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#vttable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        params.client = <?= $client->getId()?>;
        return params;
    }    

    function mutualsQueryParams(params) {
        $('#mutualtoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#mutualtable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#mutualtable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }    

    function comissQueryParams(params) {
        $('#comisstoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#comisstable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#comisstable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }    

    function rowStyle(row){
        var retired = 'tablerow';
        switch(row.status){
            case '<?= Order::STATUS_TAKE_NO?>': 
            case '<?= Vt::STATUS_TAKE_NO?>': 
                return {classes: 'warning '+retired};
            default: break;            
        }                
        switch(row.status){
            case '<?= Order::STATUS_SHIPPED?>': 
                        return {classes: 'success '+retired}; break;
            case '<?= Order::STATUS_DELIVERY?>': 
            case '<?= Vt::STATUS_COMMISSION?>': 
            case '<?= Vt::STATUS_DEFECT?>': 
            case '<?= Vt::STATUS_WAIT?>': 
                        return {classes: 'info '+retired}; break;
            case '<?= Order::STATUS_CONFIRMED?>': 
                        return {classes: retired, css: {"background-color": "linen"}}; break;
            case '<?= Order::STATUS_PROCESSED?>': 
                        return {classes: retired, css: {"background-color": "WhiteSmoke"}}; break;
            case '<?= Order::STATUS_CANCELED?>': 
            case '<?= Vt::STATUS_RETIRED?>': 
                        return {classes: 'retired '+retired}; break;
            default:break;     
        }
        
        return {classes: retired};
    }
    
    function vtRowStyle(row){
        var retired = 'default';
        switch(row.status){
            case '<?= Vt::STATUS_TAKE_NO?>': 
                return {classes: 'warning '+retired};
            case '<?= Vt::STATUS_COMMISSION?>': 
            case '<?= Vt::STATUS_DEFECT?>': 
            case '<?= Vt::STATUS_WAIT?>': 
                        return {classes: 'info '+retired}; break;
            case '<?= Vt::STATUS_RETIRED?>': 
                        return {classes: 'retired '+retired}; break;
            default:break;     
        }
        
        return {classes: retired};
    }

    function mutualRowStyle(row){
        var retired = 'default';
        switch(row.status){
            case '<?= Retail::STATUS_RETIRED?>': 
                        return {classes: 'retired '+retired}; break;
            default:break;     
        }
        
        return {classes: retired};
    }

    function comissRowStyle(row){
        var retired = 'default';
//        switch(row.status){
//            case '<?= Vt::STATUS_TAKE_NO?>': 
//                return {classes: 'warning '+retired};
//            default: break;            
//        }                
//        switch(row.status){
//            case '<?= Vt::STATUS_COMMISSION?>': 
//            case '<?= Vt::STATUS_DEFECT?>': 
//                        return {classes: 'info '+retired}; break;
//            case '<?= Vt::STATUS_RETIRED?>': 
//                        return {classes: 'retired '+retired}; break;
//            default:break;     
//        }
        
        return {classes: retired};
    }

    function idFormatter(value, row){
        if (row.aplId > 0){
            return value + ' ('+row.aplId+')';
        }        
        return value;
    }    
    
    function dateFormatter(value, row){
        return '<nobr>'+$.format.date(value, "dd.MM.yy")+'</nobr>';        
    }
        
    function vtDateFormatter(value){
        return dateFormatter(value + ' 00:00:00');        
    }

    function docStampFormatter(value, row){
        return dateFormatter(row.dateOper);        
    }

    function docFormatter(value, row){
        var orderId = value;
        var idAplId = value;
        if (row.aplId){
            idAplId += ' ('+row.aplId+')';
        }
        if (row.order){
            orderId = row.order.id;
            idAplId = row.order.id;
            if (row.order.aplId){
                idAplId += ' ('+row.order.aplId+')';
            }
        }
        return "<nobr><a href='#' class='order-view-show' modal-url='/order/view/"+orderId+"'>"+idAplId+"</a></nobr>";
    }
        
    function clientFormatter(value, row){
        var result = [];
        var name = (value) ? value:'Nan';
        if (row.legal){
            name = row.legal.name;
        }
        result.push('<a style="text-transform:capitalize" href="/contact/view/' + row.contact.id + '" target="_blank">' + name + '</a>');

        if (row.dependInfo){
            var depend = $.parseJSON(row.dependInfo);
            var phones = [];

            $.each(depend.phones, function( index, phone ) {
                phones.push('<a href="#" class="sms-message-modal-show" modal-url="/sms/sms-form/" phone="'+phone.name+'" order-id="'+row.id+'">'+phone.name.replace(/(\d{3})(\d{3})(\d{4})/, '$1 $2-$3')+'</a>');
                if (phones.length > 1){
                    return false;
                }
            });

            var emails = [];
            $.each(depend.emails, function( index, email ) {
                emails.push('<a href="#" class="post-message-modal-show" modal-url="/post/post-form/" email="'+email.name+'" order-id="'+row.id+'">'+email.name+'</a>');
                return false;
            });

            var marketplaceOrders = [];
            if (depend.marketplaceOrders){
                marketplaceOrders.push('<a href="#" class="marketplace-orders-modal-show" modal-url="/market-place/order-form/" order-id="'+row.id+'" title="Заказы в ТП">('+depend.marketplaceOrders.length+')</a>');
                $.each(depend.marketplaceOrders, function( index, marketplaceOrder ) {
                    marketplaceOrders.push(marketplaceOrder.marketplaceName+': '+marketplaceOrder.postingNumber);
                    if (marketplaceOrders.length > 2){
                        return false;
                    }
                });
            }    
            
            if (phones.length || emails.length || marketplaceOrders.length){
                if (phones.length){
                    result.push('<br/>');
                    result.push(phones.join('; '));
                }    
                if (emails.length){
                    result.push('<br/>');
                    result.push('<nobr>'+emails.join('; ')+'</nobr>');
                }    
                if (marketplaceOrders.length){
                    result.push('<br/>');
                    result.push('<nobr>'+marketplaceOrders.join(' ')+'</nobr>');
                }    
            }    
        }    
        return result.join(' '); 
    }

    function infoFormatter(value, row){
        return value;
    }
        
    function carFormatter(value, row){
        var result = [];
        var contactCar = row;
        if (row.contactCar){
            contactCar = row.contactCar;
        }
        if (contactCar){
            if (contactCar.car){
                result.push(contactCar.car.fullname);
            } else {    
                if (contactCar.make){
                    result.push(contactCar.make.name);
                }
                if (contactCar.model){
                    result.push(contactCar.model.name);
                }
            }    
        }
        return result.join(' ');
    }

    function shippingFormatter(value, row){
        var result = [];
        result.push(value);
        if (row.infoShipping){
            result.push(row.infoShipping);
        }
        if (row.shipmentTotal > 0){
            result.push(row.shipmentTotal);
        }
        if (row.skiper){
            result.push(row.skiper.fullName);
        }
        return result.join(' ');
    }

    function commentFormatter(value, row){
        var result = '';
        var commentLength = '0';
        if (value){
            var depend = $.parseJSON(value);
            var comments = depend.comments;
            if (comments.length){
                commentLength = comments.length;
                $.each(comments, function( index, comment ) {
                    result = comment.comment;
                });
            }    
        }    
        
        return [
//            '<a href="#" class="order-comment-modal-show" modal-url="/comments/edit-local-form/" order-id="'+row.id+'" title="Добавить комментарий">(+)</a>',
            '<a href="#" class="comments-modal-show" modal-url="/comments/order-form/" order-id="'+row.id+'" title="Комментарии">('+commentLength+')</a>',
            //'(' + value.length + ')',
            result
        ].join(' ');
    }

    function inFormatter(value, row){
        switch(row.docType){
            case '<?= Movement::DOC_VT?>':
                return Math.round(value*100)/100;
            case '<?= Movement::DOC_CASH?>':
                return;
            default:
                if (value>0){
                    return Math.round(value*100)/100;
                }
        }
        return;
    }    
    
    function outFormatter(value, row){
        switch(row.docType){
            case '<?= Movement::DOC_VT?>':
                return;
            case '<?= Movement::DOC_CASH?>':
                return -Math.round(value*100)/100;
            default:
                if (value<0){
                    return -Math.round(value*100)/100;
                }
        }
        return;
    }    

    function inQuantityFormatter(value){
        if (value>0){
            return Math.round(value*100)/100;
        }
        return;
    }    
    
    function outQuantityFormatter(value){
        if (value<0){
            return -Math.round(value*100)/100;
        }
        return;
    }    

    function restFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    

    function restQuantityFormatter(value){
        return Math.round(value*100)/100;
    }    

    function vinFormatter(value, row){
        var result = (value) ? value:'';
        if (row.vin2){
            result += ' (' + row.vin2 + ')';
        }
        return result.trim();
    }    
    
    function wheelFormatter(value){
        var result = <?= Encoder::encode(ContactCar::getWheelList())?>;
        return result[value];
    }

    function tmFormatter(value){
        var result = <?= Encoder::encode(ContactCar::getTmList())?>;
        return result[value];
    }

    function acFormatter(value){
        var result = <?= Encoder::encode(ContactCar::getAcList())?>;
        return result[value];
    }

    function textFormatter(value){
        return value;
    }

    function carEditFormatter(value, row){
        var url = '/garage/edit-form/'+value;
        btn = '<button';
        btn += ' value="'+url+'"';
        btn += ' class="btn btn-default btn-xs"';
        btn += ' data-toggle="modal" data-target="#modal-dialog"'; 
        btn += ' title="Изменить">'; 
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }        
    
    function vtActiveFormatter(value, row){
        var url = '/vt/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs vt-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';

        return btn;
    }        
    
    function goodFormatter(value, row){
        var url = '/goods/view/'+row.good.id;
        btn = '<nobr><a';
        btn += ' href="'+url+'"';
        btn += ' class="btn btn-link btn-xs" target="_blank">';
        btn += '<span class="glyphicon glyphicon-link"></span>';
        btn += '</a>'+value+'</nobr>';
        return btn;
    }    
      
    function goodNameFormatter(value, row){
        if (row.tokenGroup){
            return row.tokenGroup.name;
        }
        return value;
    }        
    
    function docKeyFormatter(value, row){
        let docType = row.docType;        
        let docId = row.docId;        
        switch(docType){
            case '<?= Movement::DOC_ORDER?>': 
                return "<a href='#' class='order-view-show' modal-url='/order/view/"+docId+"'>Заказ №"+docId+"</a>";
            case '<?= Movement::DOC_MSR?>': 
                return "<a href='#' class='msr-modal-show' modal-url='/comitent/edit-form/"+docId+"'>Отчет о продажах №"+docId+"</a>";
            case '<?= Movement::DOC_VT?>': 
                return "<a href='#' class='vt-modal-show' modal-url='/vt/edit-form/"+docId+"'>Возврат покупателя №"+docId+"</a>";
            case '<?= Movement::DOC_PTU?>': 
                return "<a href='#' class='ptu-modal-show' modal-url='/ptu/edit-form/"+docId+"'>Поступление №"+docId+"</a>";
            case '<?= Movement::DOC_OT?>': 
                return "<a href='#' class='ot-modal-show' modal-url='/ot/edit-form/"+docId+"'>Оприходование №"+docId+"</a>";
            case '<?= Movement::DOC_ST?>': 
                return "<a href='#' class='st-modal-show' modal-url='/st/edit-form/"+docId+"'>Списание №"+docId+"</a>";
            case '<?= Movement::DOC_VTP?>': 
                return "<a href='#' class='vtp-modal-show' modal-url='/vtp/edit-form/"+docId+"'>Возврат поставщику №"+docId+"</a>";
            case '<?= Movement::DOC_REVISE?>':
                if (row.reviseDoc){        
                    var comment = row.reviseDoc.comment;        
                    return "<a href='#' class='revise-modal-show' modal-url='/revise/edit-form/"+docId+"'>Корректировка №"+docId+"</a> <small class='text-muted'>"+comment+"</small>";
                } else {
                    return '!Документ не найден!';
                }    
            case '<?= Movement::DOC_CASH?>':
                var cashName = '';
                var result = '';
                var kindName = '';
                var kindNames = <?= CashDoc::getKindListAsJavascriptArray()?>;
                if (row.cashDoc){
                    if (row.cashDoc.cash){
                        kindName = kindNames[row.cashDoc.kind];
                        cashName = kindName +' '+ row.cashDoc.cash.name;
                        if (row.amount < 0){
                            result = "<a href='#' class='cash-in-modal-show' modal-url='/till/edit-cash-in/"+docId+"'>"+cashName+" №"+docId+"</a>";
                        } else {   
                            result = "<a href='#' class='cash-out-modal-show' modal-url='/till/edit-cash-out/"+docId+"'>"+cashName+" №"+docId+"</a>";
                        }    
                    }    
                    if (row.cashDoc.user){
                        cashName = kindName +' '+ row.cashDoc.user.fullName;
                        if (row.amount < 0){
                            result = "<a href='#' class='cash-in-modal-show' modal-url='/accountant/edit-user-in/"+docId+"'>"+cashName+" №"+docId+"</a>";
                        } else {    
                            result = "<a href='#' class='cash-out-modal-show' modal-url='/accountant/edit-user-out/"+docId+"'>"+cashName+" №"+docId+"</a>";
                        }    
                    } 
                    if (row.cashDoc.order){
                        var orderId = 'Z'+row.cashDoc.order.id;
                        if (row.cashDoc.order.aplId){
                            orderId = row.cashDoc.order.aplId;
                        }
                        result += " <a href='#' class='order-view-show' modal-url='/order/view/"+row.cashDoc.order.id+"'>Заказ №"+orderId+"</a>";
                    }
                    return result;
                }    
            default: return docId;            
        }
    }
    
    function responseHandler(res) {
        return res;
    }    

    function changeOrderStatus(orderId, status){
        $.get( "/order/status/"+orderId+'?status='+status, function(data){
//            refreshTable();
            $table.bootstrapTable('updateByUniqueId', {id: orderId, row: data});
        });        
    }

    var menu = new BootstrapMenu('.tablerow', {
        fetchElementData: function(rowElem) {
            var rowId = $(rowElem).attr('data-index');
            return $table.bootstrapTable('getData')[rowId];
        },
        actionsGroups: [
           ['addComment', 'comments', 'history'],
           ['addMarketplaceNumber', 'addLegal'],
           ['vt', 'cash']
        ],      
        actions: {
            statusNew: {
                name: 'Новый',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_NEW?>);
                },
                isShown: function(row) {
                  return row.status != '<?= Order::STATUS_NEW?>';
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            }, 
            statusProcessed: {
                name: 'Обработан',
                classNames: 'bg-default',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_PROCESSED?>);
                },
                isShown: function(row) {
                  return row.status != '<?= Order::STATUS_PROCESSED?>';
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            }, 
            statusConfirmed: {
                name: 'Подтвержден',
                classNames: 'bg-warning',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_CONFIRMED?>);
                },
                isShown: function(row) {
                  return row.status != '<?= Order::STATUS_CONFIRMED?>';
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            }, 
            statusDelivery: {
                name: 'На доставке',
//                iconClass: 'glyphicon glyphicon-ok',
                classNames: 'bg-info',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_DELIVERY?>);
                },
                isShown: function(row) {
                  return row.status != <?= Order::STATUS_DELIVERY?>;
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            }, 
            statusShipped: {
                name: 'Отгружен',
                classNames: 'bg-success',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_SHIPPED?>);
                },
                isShown: function(row) {
                  return row.status != <?= Order::STATUS_SHIPPED?>;
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            },
            statusCanceled: {
                name: 'Отменен',
                classNames: 'bg-default',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_CANCELED?>);
                },
                isShown: function(row) {
                  return row.status != <?= Order::STATUS_CANCELED?>;
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            },
            addComment: {
                name: 'Добавить комментарий',
                iconClass: 'glyphicon glyphicon-plus',
                onClick: function (row){
                    var url = '/comments/edit-local-form/'+row.id;
                    showFormDialog({
                        id: 'orderCommentModal',
                        url: url,
                        zIndex: 9999,
                        width: $(window).width()-150
                    });
                }
            },    
            comments: {
                name: 'Комментарии',
                iconClass: 'glyphicon glyphicon-list-alt',
                onClick: function (row){
                    var url = '/comments/order-form/'+row.id;
                    showFormDialog({
                        id: 'orderCommentsModal',
                        url: url,
                        zIndex: 8888
                    });
                }
            },    
            history: {
                name: 'История',
                iconClass: 'glyphicon glyphicon-list-alt',
//                classNames: 'bg-danger',
                onClick: function(row) {
                    $.ajax({
                        type: "GET",
                        url: "/log/history/"+row.id+"?docType=ord",
                        success: function (result) {
                            bootbox.alert({
                                size: "large",
                                message: result
                            });
                        }
                    });                    
                }
            },
            addMarketplaceNumber: {
                name: 'Номер заказа в ТП',
                iconClass: 'glyphicon glyphicon-plus',
                onClick: function (row){
                    var depend = $.parseJSON(row.dependInfo);
                    var dialogId = 'marketplaceOrderModal';
                    var url = '/market-place/marketplace-order-form?order='+row.id;
                    var zIndex = 9999;
                    if (depend.marketplaceOrders){
                        if (depend.marketplaceOrders.length){
                            var url = '/market-place/order-form/'+row.id;
                            var dialogId = 'marketplaceOrdersModal';
                            var zIndex = 8888;
                        }    
                    }
                    
                    showFormDialog({
                        id: dialogId,
                        url: url,
                        zIndex: zIndex
                    });
                }
            },    
            addLegal: {
                name: 'Юр. лицо',
                iconClass: 'glyphicon glyphicon-plus',
                onClick: function (row){
                    var url = '/order/order-legal-form/'+row.id;
                    showFormDialog({
                        id: 'orderLegalModal',
                        url: url,
                        width: '1000px',
                        zIndex: 9999
                    });    
                }
            },    
            vt: {
                name: 'Возврат',
                iconClass: 'glyphicon glyphicon-repeat',
                onClick: function (row){
                    var url = '/vt/order-form/'+row.id;
                    showFormDialog({
                        id: 'vtIndexModal',
                        url: url,
                        zIndex: 8888,
                        width: '1440px'
                    });
                },
                isEnabled: function(row) {
                    return row.status == <?= Order::STATUS_SHIPPED?>;
                }                
            },
            cash: {
                name: 'Оплата',
                iconClass: 'glyphicon glyphicon-rub',
                onClick: function (row){
                    var url = '/comments/order-form/'+row.id;
                    showFormDialog({
                        id: 'orderCommentsModal',
                        url: url,
                        zIndex: 8888
                    });
                }
            }
        }
    });    

</script>