<?php
    $this->headTitle('Подотчет');

    $this->mainMenu()->setActiveItemId('report');
    $this->mainMenu()->setActiveUrl($this->url('report', ['action' => 'accountant']));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Отчеты'=>$this->url('report'),
                ]);
    
    $this->headScript()
                ->prependFile('//cdn.plot.ly/plotly-2.12.1.min.js')
            ;

?>
<div class="row">
    <div class="col-md-6">
        <div id="tester"></div>
    </div>
    <div class="col-md-6">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select id="userSelect" name="user" style="width: 200px" class="form-control">
                        <option selected>Сотрудник</option>                        
                        <?php foreach ($users as $user):?>
                            <option value="<?= $user->getId()?>"><?= $user->getFullName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <select id="periodSelect" class="form-control" name="periodSelect">
<!--                        <option value="date">Дата</option>
                        <option value="week">Неделя</option>                        -->
                        <option value="month">Месяц</option>                        
                        <option value="number">Год</option>                        
                    </select>
                    <input name="dateStart" id="dateStart" style="width: 200px" class="form-control refresh-table" type="month" value="<?= date('Y-m')?>">
                    <select id="period" class="form-control" name="period">
                        <option value="day">По дням</option>                        -->
                        <option value="month">По месяцам</option>                        
                        <option value="year">По годам</option>                        
                    </select>
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/report/accountantContent"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-sort-name="period"
            data-sort-order="asc"            
            data-classes = "table table-bordered table-hover table-condensed"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="period" data-sortable="true" data-width="100">Период</th>
                     <th data-field='bSum' data-sortable="false" data-align="right" data-formatter="amountFormatter">Остаток на начало</th>
                     <th data-field='inSum' data-sortable="false" data-align="right" data-formatter="amountFormatter">Поступило</th>
                     <th data-field='outSum' data-sortable="false" data-align="right"  data-formatter="amountFormatter">Расход</th>
                     <th data-field='eSum' data-sortable="false" data-align="right"  data-formatter="endAmountFormatter">Остаток на конец</th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>

<script>
    var $table = $('#table').bootstrapTable({
        onLoadSuccess: function(data){
//            console.log(data);
            var bTotalNode = $table.find('th[data-field="bSum"]').find('.th-inner');
            bTotalNode.html('На начало '+data.bTotal.toFixed(2));
            bTotalNode.css('text-align','right');

            var inTotalNode = $table.find('th[data-field="inSum"]').find('.th-inner');
            inTotalNode.html('Поступило '+data.inTotal.toFixed(2));
            inTotalNode.css('text-align','right');

            var outTotalNode = $table.find('th[data-field="outSum"]').find('.th-inner');
            outTotalNode.html('Расход '+data.outTotal.toFixed(2));
            outTotalNode.css('text-align','right');

            var eTotalNode = $table.find('th[data-field="eSum"]').find('.th-inner');
            eTotalNode.html('На конец '+data.eTotal.toFixed(2));
            eTotalNode.css('text-align','right');
                
            var x = []; var y1 = []; var y2 = [];
            $.each(data.rows, function( index, value ) {
                    x.push(value.period);
                    y1.push(value.inSum);
                    y2.push(value.outSum);
                });
                plotly(x, y1);
            }                    
        }),
        $ok = $('#ok');

    function refreshTable(){
        $table.bootstrapTable('refresh');
    }
    
    function plotly(x, y){
	TESTER = document.getElementById('tester');
	Plotly.newPlot( TESTER, [{
            x: x,
            y: y,
            type: 'bar'
            }], 
            {
                margin: { t: 30 },
                title: 'Обороты за период'
            } 
        );        
    }
    
    $(function(){        
        $(document).on('change', '#officeSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#userSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#dateStart', function (e) {
            refreshTable();
        });        
        $(document).on('change', '#period', function (e) {
            refreshTable();
        });        
        $(document).on('change', '#periodSelect', function (e) {
            var periodSelectVal = $(this).val();
            $('#dateStart').attr('type', $(this).val());
            if (periodSelectVal == 'number'){
               $('#dateStart').val($.format.date(new Date(), "yyyy"));
               $('#dateStart').attr('min', 2012);
               $('#dateStart').attr('max', $.format.date(new Date(), "yyyy"));
            }
        });
    });

    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }        

    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }

    function endAmountFormatter(value, row){
        var bSum = Math.round((row.bSum || 0)*100)/100;
        var inSum = Math.round((row.inSum || 0)*100)/100;
        var outSum = Math.round((row.outSum || 0)*100)/100;
        return (bSum+inSum-outSum).toFixed(2);
    }

    function responseHandler(res) {
        return res;
    }    
</script>