<?php
    $this->headTitle('Отчеты');

    $this->mainMenu()->setActiveItemId('report');
    $this->mainMenu()->setActiveUrl($this->url('report'));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Отчеты'=>$this->url('report'),
                ]);
    
    $this->headScript()
                ->prependFile('//cdn.plot.ly/plotly-2.12.1.min.js')
            ;

?>
<div class="row">
    <div class="col-md-6">
        <div id="tester"></div>
    </div>
<!--</div>    
<div class="row">-->
    <div class="col-md-6">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select id="officeSelect" style="width: 100px" class="form-control">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="periodSelect" class="form-control" name="period">
                        <!--<option value="date">Дата</option>-->
                        <!--<option value="week">Неделя</option>-->                        
                        <option value="all">За все времена</option>                        
                        <option value="number">Год</option>                        
                        <option value="month" selected="">Месяц</option>                        
                    </select>
                    <input name="dateStart" id="dateStart" style="width: 200px" min="2024-01" class="form-control refresh-table" type="month" value="<?= date('Y-m')?>">
                </div>                
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/report/revenueByYears"
            data-side-pagination="client"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-sort-name="period"
            data-sort-order="asc"            
            data-classes = "table table-bordered table-hover table-condensed"
            data-response-handler="responseHandler"
            data-show-export="true"
            data-show-footer="true"
            >
            <thead>
                <tr>
                     <th data-field="period" data-align="right">Период</th>
                     <th data-field='revenue' data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="totalFormatter">Продажа</th>
                     <th data-field='purchase' data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="totalFormatter">Закупка</th>
                     <th data-field='income' data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="totalFormatter">Доход</th>
                     <!--<th data-field='quantity' data-sortable="false" data-align="right" data-formatter="totalFormatter">Товаров, шт</th>-->
                 </tr>                
            </thead>
        </table>
    </div>
</div>

<script>
    var $table = $('#table'),
        $ok = $('#ok');

    function refreshTable(){
        $table.bootstrapTable('refresh');
    }
    
    function plotly(x, y, layout){
	TESTER = document.getElementById('tester');
	Plotly.newPlot( TESTER, [{
            x: x,
            y: y,
            type: 'bar'
            }], 
            layout
        );        
    }
    
    $(function(){        
        $table.on('load-success.bs.table', function (e, data) {
            var x = []; var y = []; 
            var x1 = []; var y1 = []; 
            var x2 = []; var y2 = []; 
//            var x3 = []; var y3 = []; 
            var res = []; 
            var TESTER = document.getElementById('tester');
            $.each(data.rows, function( index, value ) {
                x.push(value.period);
                y.push(value.revenue);
                x1.push(value.period);
                y1.push(value.purchase);
                x2.push(value.period);
                y2.push(value.income);
//                x3.push(value.period);
//                y3.push(value.quantity);
            });
            
            res.push({x: x, y:y, type:"lines", name: 'Продажа'});
            res.push({x: x1, y:y1, type:"lines", name: 'Закупка'});
            res.push({x: x2, y:y2, type:"lines", name: 'Доход'});
//            res.push({x: x3, y:y3, type:"lines", name: 'Товаров, шт'});
            
            const layout = {title: "Обороты", type: 'bar'};
                
            Plotly.newPlot( TESTER, res, layout);        
        });  
        
        $(document).on('change', '#officeSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#dateStart', function (e) {
            refreshTable();
        });
//        $(document).on('change', '#monthSelect', function (e) {
//            refreshTable();
//        });        
        $(document).on('change', '#periodSelect', function (e) {
            var selectType = $(this).val();
            $('#dateStart').attr('type', selectType);
            switch(selectType){
                case 'number':
                    $('#dateStart').val(new Date().getFullYear());
                    //$('#dateStart').attr('min', 2024);
                    break;
                case 'month':    
                    //$('#dateStart').attr('min', '2024-01');
                    $('#dateStart').val($.format.date(new Date(), "yyyy-MM"));
                    break;
                case 'all':    
                    //$('#dateStart').attr('min', '2012-01');
                    $('#dateStart').val(null);
                    break;
                default:
                    $('#dateStart').attr('min', '2011-01-01');
                    $('#dateStart').val($.format.date(new Date(), "yyyy-MM-dd"));
            }
            refreshTable();
        });
    });

    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
//        params.office = $('#officeSelect').val();
//        params.month = $('#monthSelect').val();
        
        return params;
    }        

    function totalFormatter(value, row){
        return $.number(value, 0, ',', ' ' );
    }
    
    function footerFormatter(data){
        var field = this.field;
        return $.number((data.map(function (row) {
            return +row[field];
        }).reduce(function (sum, i) {
            return (Math.round((sum + i)*100)/100);
        }, 0)), 0, ',', ' ');
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>