<?php
    use Application\Entity\Client;
    use Laminas\Json\Encoder;

    $this->headTitle('Отчеты');

    $this->mainMenu()->setActiveItemId('report');
    $this->mainMenu()->setActiveUrl($this->url('report'));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Отчеты'=>$this->url('report'),
                ]);
    
    $this->headScript()
                ->prependFile('//cdn.plot.ly/plotly-2.12.1.min.js')
            ;

?>
<h2>Лучшие покупатели</h2>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar5">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select style="width: 100px" class="form-control officeSelect">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select class="form-control periodSelect" name="period">
                        <option value="all">За все времена</option>                        
                        <option value="number">Год</option>                        
                        <option value="month" selected="">Месяц</option>                        
                    </select>
                    <input name="dateStart" style="width: 200px" class="form-control dateStart" type="month" value="<?= date('Y-m')?>">
                </div>                
                <div class="form-group">
                    <select class="form-control newClient" name="newClient">
                        <option value="all">все клиенты</option>                        
                        <option value="1">новые клиенты</option>                        
                    </select>
                </div>                
            </div>
        </div>
        <table id="table5" 
            data-toggle="table" 
            data-url="/report/revenueByClient"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50, 100]"
            data-toolbar="#toolbar5"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams5"
            data-sort-name="income"
            data-sort-order="desc"            
            data-classes = "table table-bordered table-hover table-condensed"
            data-response-handler="responseHandler"
            data-show-export="true"
            data-show-footer="true"
            data-row-style="rowStyle5"
            >
            <thead>
                <tr>
                     <th data-field="clientName" data-formatter="clientFormatter">Покупатель</th>
                     <th data-field='dateOrder' data-sortable="true" data-footer-formatter="totalFooterFormatter" data-formatter="dateFormatter">Дата первого заказа</th>
                     <th data-field='orderCount' data-sortable="true" data-align="right" data-footer-formatter="serverFooterFormatter" data-formatter="totalFormatter">Заказов</th>
                     <th data-field='amount' data-sortable="true" data-align="right" data-footer-formatter="serverFooterFormatter" data-formatter="totalFormatter">Продажи, руб.</th>
                     <th data-field='margin' data-sortable="true" data-align="right" data-footer-formatter="serverFooterFormatter" data-formatter="totalFormatter">Маржа, %</th>
                     <th data-field='average' data-sortable="true" data-align="right" data-footer-formatter="serverFooterFormatter" data-formatter="totalFormatter">Средний чек, руб.</th>
                     <th data-field='income' data-sortable="true" data-align="right" data-footer-formatter="serverFooterFormatter" data-formatter="totalFormatter">Доход, руб.</th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>

<h2>Популярные товары</h2>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar3">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select style="width: 100px" class="form-control officeSelect">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select class="form-control periodSelect" name="period">
                        <option value="all">За все времена</option>                        
                        <option value="number">Год</option>                        
                        <option value="month" selected="">Месяц</option>                        
                    </select>
                    <input name="dateStart" style="width: 200px" class="form-control dateStart" type="month" value="<?= date('Y-m')?>">
                </div>                
            </div>
        </div>
        <table id="table3" 
            data-toggle="table" 
            data-url="/report/revenueByGoods"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50, 100]"
            data-toolbar="#toolbar3"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams3"
            data-sort-name="income"
            data-sort-order="desc"            
            data-classes = "table table-bordered table-hover table-condensed"
            data-response-handler="responseHandler"
            data-show-export="true"
            data-show-footer="true"
            >
            <thead>
                <tr>
                     <th data-field="code" data-footer-formatter="totalFooterFormatter" data-formatter="goodLinkFormatter">Товар</th>
                     <th data-field='quantity' data-sortable="true" data-align="right" data-footer-formatter="serverFooterFormatter" data-formatter="totalFormatter">Продажи, шт</th>
                     <th data-field='income' data-sortable="true" data-align="right" data-footer-formatter="serverFooterFormatter" data-formatter="totalFormatter">Доход, руб.</th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>

<h2>Популярные категории товаров</h2>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar4">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select style="width: 100px" class="form-control officeSelect">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select class="form-control periodSelect" name="period">
                        <option value="all">За все времена</option>                        
                        <option value="number">Год</option>                        
                        <option value="month" selected="">Месяц</option>                        
                    </select>
                    <input name="dateStart" style="width: 200px" class="form-control dateStart" type="month" value="<?= date('Y-m')?>">
                </div>                
            </div>
        </div>
        <table id="table4" 
            data-toggle="table" 
            data-url="/report/revenueByTokenGroup"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50, 100]"
            data-toolbar="#toolbar4"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams4"
            data-sort-name="income"
            data-sort-order="desc"            
            data-classes = "table table-bordered table-hover table-condensed"
            data-response-handler="responseHandler"
            data-show-export="true"
            data-show-footer="true"
            >
            <thead>
                <tr>
                     <th data-field="tgName" data-footer-formatter="totalFooterFormatter">Категория</th>
                     <th data-field='quantity' data-sortable="true" data-align="right" data-footer-formatter="serverFooterFormatter" data-formatter="totalFormatter">Продажи, шт</th>
                     <th data-field='income' data-sortable="true" data-align="right" data-footer-formatter="serverFooterFormatter" data-formatter="totalFormatter">Доход, руб.</th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>

<h2>Выручка за период</h2>
<div class="row">
    <div class="col-md-6">
        <div id="tester"></div>
    </div>
    <div class="col-md-6">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select style="width: 100px" class="form-control officeSelect">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select class="form-control periodSelect" name="period">
                        <option value="all">За все времена</option>                        
                        <option value="number">Год</option>                        
                        <option value="month" selected="">Месяц</option>                        
                    </select>
                    <input name="dateStart" style="width: 200px" class="form-control dateStart" type="month" value="<?= date('Y-m')?>">
                </div>                
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/report/revenueByYears"
            data-side-pagination="client"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams1"
            data-sort-name="period"
            data-sort-order="asc"            
            data-classes = "table table-bordered table-hover table-condensed"
            data-response-handler="responseHandler"
            data-show-export="true"
            data-show-footer="true"
            >
            <thead>
                <tr>
                     <th data-field="period" data-align="right" data-footer-formatter="totalFooterFormatter"><span class="periodName">День</span></th>
                     <th data-field='revenue' data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="totalFormatter">Продажа</th>
                     <th data-field='purchase' data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="totalFormatter">Закупка</th>
                     <th data-field='income' data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="totalFormatter">Доход</th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>

<h2>Заказы за период</h2>

<div class="row">
    <div class="col-md-6">
        <div id="tester2"></div>
    </div>
    <div class="col-md-6">
        <div id="toolbar2">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select style="width: 100px" class="form-control officeSelect">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select class="form-control periodSelect" name="period">
                        <option value="all">За все времена</option>                        
                        <option value="number">Год</option>                        
                        <option value="month" selected="">Месяц</option>                        
                    </select>
                    <input name="dateStart" style="width: 200px" class="form-control dateStart" type="month" value="<?= date('Y-m')?>">
                </div>                
            </div>
        </div>
        <table id="table2" 
            data-toggle="table" 
            data-url="/report/revenueByOrders"
            data-side-pagination="client"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar2"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams2"
            data-sort-name="period"
            data-sort-order="asc"            
            data-classes = "table table-bordered table-hover table-condensed"
            data-response-handler="responseHandler"
            data-show-export="true"
            data-show-footer="true"
            >
            <thead>
                <tr>
                    <th data-field="period" data-align="right" data-footer-formatter="totalFooterFormatter"><span class="periodName">День</span></th>
                     <th data-field='orderCount' data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="totalFormatter">Заказы</th>
                     <th data-field='newClient' data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="totalFormatter">Новые регистрации</th>
                     <th data-field='newOrder' data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="totalFormatter">Заказы новых клиентов</th>
                     <th data-field='vtCount' data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="totalFormatter">Возвраты</th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>

<script>
    var $table = $('#table'),
        $table2 = $('#table2'),
        $table3 = $('#table3'),
        $table4 = $('#table4'),
        $table5 = $('#table5'),
        $ok = $('#ok');
        $periodName = 'День';
        
    function setPeriodName(name){
        $periodName = name;
    }  
    
    function getPeriodName(){
        return $periodName;
    }

    function refreshTable(){
        $table.bootstrapTable('refresh');
        $table2.bootstrapTable('refresh');
        $table3.bootstrapTable('refresh');
        $table4.bootstrapTable('refresh');
        $table5.bootstrapTable('refresh');
    }
    
    $(function(){        
        $table.on('load-success.bs.table', function (e, data) {
            var x = []; var y = []; 
            var x1 = []; var y1 = []; 
            var x2 = []; var y2 = []; 
            var xTitle = getPeriodName();
            var res = []; 
            var TESTER = document.getElementById('tester');
            $.each(data.rows, function( index, value ) {
                x.push(value.period);
                y.push(value.revenue);
                x1.push(value.period);
                y1.push(value.purchase);
                x2.push(value.period);
                y2.push(value.income);
            });
            
            res.push({x: x, y:y, type:"lines", name: 'Продажа'});
            res.push({x: x1, y:y1, type:"lines", name: 'Закупка'});
            res.push({x: x2, y:y2, type:"lines", name: 'Доход'});
            
            const layout = {xaxis: {title: xTitle}, yaxis: {title: 'Сумма'}};
                
            Plotly.newPlot( TESTER, res, layout);        
        });  
        
        $table2.on('load-success.bs.table', function (e, data) {
            var x = []; var y = []; 
            var x1 = []; var y1 = []; 
            var x2 = []; var y2 = []; 
            var x3 = []; var y3 = []; 
            var xTitle = getPeriodName();
            var res = []; 
            var TESTER = document.getElementById('tester2');
            $.each(data.rows, function( index, value ) {
                x.push(value.period);
                y.push(value.orderCount);
                x1.push(value.period);
                y1.push(value.newClient);
                x2.push(value.period);
                y2.push(value.newOrder);
                x3.push(value.period);
                y3.push(value.vtCount);
            });
            
            res.push({x: x, y:y, type:"lines", name: 'Заказы'});
            res.push({x: x1, y:y1, type:"bar", name: 'Новые ркгистрации'});
            res.push({x: x2, y:y2, type:"bar", name: 'Заказы новых клиентов'});
            res.push({x: x3, y:y3, type:"lines", name: 'Возвраты'});
            
            const layout = {xaxis: {title: xTitle}, yaxis: {title: 'Количество'}};
                
            Plotly.newPlot( TESTER, res, layout);        
        });  
        
        $table3.on('load-success.bs.table', function (e, data) {
            $table3.find('.incomeFooter').text($.number(data.income,  0, ',', ' '));
            $table3.find('.quantityFooter').text($.number(data.quantity,  0, ',', ' '));
        });  
        
        $table4.on('load-success.bs.table', function (e, data) {
            $table4.find('.incomeFooter').text($.number(data.income,  0, ',', ' '));
            $table4.find('.quantityFooter').text($.number(data.quantity,  0, ',', ' '));
        });  
        
        $table5.on('load-success.bs.table', function (e, data) {
            $table5.find('.incomeFooter').text($.number(data.income,  0, ',', ' '));
            $table5.find('.amountFooter').text($.number(data.amount,  0, ',', ' '));
            $table5.find('.marginFooter').text($.number(data.margin,  0, ',', ' '));
            $table5.find('.averageFooter').text($.number(data.average,  0, ',', ' '));
            $table5.find('.orderCountFooter').text($.number(data.orderCount,  0, ',', ' '));
        });  
        
        $(document).on('change', '.officeSelect', function (e) {
            $('.officeSelect').val($(this).val());
            refreshTable();
        });
        
        $(document).on('change', '.dateStart', function (e) {
            $('.dateStart').val($(this).val());
            refreshTable();
        });

        $(document).on('change', '.newClient', function (e) {
            $table5.bootstrapTable('refresh');
        });

        $(document).on('change', '.periodSelect', function (e) {
            var selectType = $(this).val();
            $('.periodSelect').val($(this).val());
            $('.dateStart').attr('type', selectType);
            switch(selectType){
                case 'number':
                    $('.dateStart').val(new Date().getFullYear());
                    setPeriodName('Месяц');
                    break;
                case 'month':    
                    $('.dateStart').val($.format.date(new Date(), "yyyy-MM"));
                    setPeriodName('День');
                    break;
                case 'all':    
                    $('.dateStart').val(null);
                    setPeriodName('Год');
                    break;
                default:
                    $('.dateStart').attr('min', '2011-01-01');
                    $('.dateStart').val($.format.date(new Date(), "yyyy-MM-dd"));
                    setPeriodName('Год');
            }
            $('.periodName').text(getPeriodName());
            refreshTable();
        });
    });

    function rowStyle5(row){
        var retired = 'tablerow';
        if (row.newOrderFlag === 1){
            return {classes: 'success '+retired};
        }        
        return {classes: retired};
    }

    function queryParams(params, toolbar) {
        toolbar.find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        toolbar.find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        return params;
    }        

    function queryParams1(params){
        return queryParams(params, $('#toolbar'));
    }

    function queryParams2(params){
        return queryParams(params, $('#toolbar2'));
    }

    function queryParams3(params){
        return queryParams(params, $('#toolbar3'));
    }

    function queryParams4(params){
        return queryParams(params, $('#toolbar4'));
    }

    function queryParams5(params){
        return queryParams(params, $('#toolbar5'));
    }

    function dateFormatter(value, row){
        if (value){
            return '<nobr>'+$.format.date(value, "dd.MM.yy")+'</nobr>';        
        }
        
        return '';
    }

    function totalFooterFormatter() {
        return 'Итого:';
    }
    
    function totalFormatter(value, row){
        return $.number(value, 0, ',', ' ' );
    }
    
    function footerFormatter(data){
        var field = this.field;
        return $.number((data.map(function (row) {
            return +row[field];
        }).reduce(function (sum, i) {
            return (Math.round((sum + i)*100)/100);
        }, 0)), 0, ',', ' ');
    }    
    
    function serverFooterFormatter(data){
        return '<span class="'+this.field+'Footer"></span>';
    }
    
    function goodLinkFormatter(value, row){
        var url = '/goods/view/'+row.id;
        btn = '<a';
        btn += ' href="'+url+'"';
        btn += ' class="btn btn-link btn-xs" target="_blank">';
        btn += '<span class="glyphicon glyphicon-link"></span>';
        btn += '</a><b>'+value+'</b> '+row.name;
        return btn;
    }    
    
    function clientFormatter(value, row){
        var pricecols = <?= Encoder::encode(Client::getPricecolList())?>;
        var url = '/client/view/'+row.clientId;
        btn = '<a';
        btn += ' href="'+url+'"';
        btn += ' class="btn btn-link btn-xs" target="_blank">';
        btn += '<span class="glyphicon glyphicon-link"></span>';
        btn += '</a> '+row.clientName+' <small class="text-muted">'+pricecols[row.pricecol]+'</small>';
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
    
</script>