<?php
use Stock\Entity\Mark;

$this->headTitle('Коды маркировки');

$this->mainMenu()->setActiveItemId('stock');
$this->mainMenu()->setActiveUrl($this->url('mark'));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Маркировка'=>$this->url('mark')
            ]);

?>
<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">               
                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>                                               
                <div class="form-group">
                    <select class="form-control cookie-control" name="markStatus">
                        <option value="-2">все</option>
                        <?php foreach(Mark::getMarkStatusList() as $key=>$value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                    </select>  
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/mark/content"
            data-cookie="true"
            data-cookie-id-table="markSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-query-params="queryParams"
            data-sort-name="aplId"
            data-sort-order="desc"  
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed" 
            data-row-style="rowStyle"
            data-auto-refresh="true"            
            >
            <thead>
                <tr>
                     <th data-field="aplId" data-sortable="true" data-width="5">AId</th>
                     <th data-field="created" data-sortable="true" data-width="10" data-formatter="dateFormatter">Дата</th>             
                     <th data-field="order" data-sortable="false" data-width="10" data-formatter="orderFormatter">Заказ</th>             
                     <th data-field="good" data-sortable="false" data-width="20" data-formatter="linkFormatter">Артикул</th>             
                     <!--<th data-field="markGroup" data-sortable="false">Группа ЧЗ</th>-->             
                     <th data-field="mark" data-sortable="false">Код со сканера</th>
                     <th data-field="" data-formatter="activeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');

    
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }
    
    $(function () {
        

    });    
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }

        
        return params;
    }
    
    function rowStyle(row, index) {
        var retired = 'tablerow';
        if (row.mark === <?= Mark::MARK_ACTIVE?>){
            retired += ' success';
        }    
        return {classes: retired};    
    }    
    
    function dateFormatter(value, row){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }     
    
    function linkFormatter(value, row){
        return [
            '<nobr>',
            '<a href="/goods/view/' + row.id + '" class="btn btn-link btn-xs" title="Перейти на страницу товара" target="_blank">',
            '<span class="glyphicon glyphicon-link"></span></a>'+value,
            '</nobr>'
        ].join(''); 
    }    
    
    function orderFormatter(value, row){
        return [
            '<nobr>',
            "<a href='#' class='order-view-show' modal-url='/order/view/"+row.order.id+"'>" + row.order.aplId+"</a>",
            '</nobr>'
        ].join(''); 
    }    
    
  
    
    function activeFormatter(value, row){
//        var url = '/group-site/edit-form/'+row.id;
//        if (row.pid){
//            url = url + '?parent=' + row.pid;
//        }
//        btn = '<nobr><button';
//        btn += ' type="button"';
//        btn += ' class="btn btn-default btn-xs group-site-modal-show"';
//        btn += ' aria-label="Left Align"'; 
//        btn += ' modal-url="'+url+'">';
//        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
//        btn += '</button> ';
//
//        url = '/group-site/delete/'+row.id;
//        var disabled = (row.hasChild === ) ? 'disabled="true"':''; 
//        btn += '<button '+disabled;
//        btn += ' type="button" title="Удалить '+row.name+'"';
//        btn += ' class="btn btn-default btn-xs del-group-site"';
//        btn += ' aria-label="Left Align"'; 
//        btn += ' del-url="'+url+'" del-name="'+row.name+'">';
//        btn += '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>';
//        btn += '</button></nobr>';
//        
//        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>
