<?php
use Stock\Entity\Mark;

$this->headTitle('Коды маркировки');

$this->mainMenu()->setActiveItemId('stock');
$this->mainMenu()->setActiveUrl($this->url('mark'));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Маркировка'=>$this->url('mark')
            ]);

?>
<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">               
                <div class="form-group">
                    <div class="btn-group">
                        <input id="searchinput" name="search" style="width: 200px" class="form-control enter-search" onfocus="this.select();" type="text" placeholder="Поиск">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>                        
                    </div>
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>                                               
                <div class="form-group">
                    <select class="form-control cookie-control refresh-table" name="markStatus">
                        <option value="-2">все</option>
                        <?php foreach(Mark::getMarkStatusList() as $key=>$value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                    </select>  
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/mark/content"
            data-cookie="true"
            data-cookie-id-table="markSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-query-params="queryParams"
            data-unique-id="id"
            data-sort-name="aplId"
            data-sort-order="desc"  
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed" 
            data-row-style="rowStyle"
            data-auto-refresh="true"            
            >
            <thead>
                <tr>
                     <th data-field="aplId" data-sortable="true" data-width="5">AId</th>
                     <th data-field="created" data-sortable="true" data-width="10" data-formatter="dateFormatter">Дата</th>             
                     <th data-field="order" data-sortable="false" data-width="10" data-formatter="orderFormatter">Заказ</th>             
                     <th data-field="good" data-sortable="false" data-width="20" data-formatter="markLinkFormatter">Артикул</th>             
                     <!--<th data-field="markGroup" data-sortable="false">Группа ЧЗ</th>-->             
                     <th data-field="mark" data-sortable="false" data-formatter="markFormatter">КM</th>
                     <th data-field="mark" data-sortable="false">Код со сканера</th>
                     <th data-field="" data-formatter="markActiveFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');

    
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }
    
    function checkMarkStatus(row){
        $.get( "/mark/mark-status/"+row.id, function(data){
            $table.bootstrapTable('updateByUniqueId', {id: row.id, row: data});
        });        
    }    
    
    $(function () {
        $table.on('load-success.bs.table', function (e, res) {
            tableRowClick();  
        });        
        
        $(".inputclear").click(function(){
            $("#searchinput").val('');
            refreshTable();
        });
        
        $(document).on('change', '.refresh-table', function (e) {
            refreshTable();
        });  
                        
    });    
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }

        
        return params;
    }
    
    function rowStyle(row, index) {
        var retired = 'tablerow';
        if (row.mark === <?= Mark::MARK_ACTIVE?>){
            retired += ' success';
        }    
        return {classes: retired};    
    }    
    
    function dateFormatter(value, row){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }     
    
    function markLinkFormatter(value, row){
        return [
            '<nobr>',
            '<a href="/goods/view/' + row.good.id + '" class="btn btn-link btn-xs" title="Перейти на страницу товара" target="_blank">',
            '<span class="glyphicon glyphicon-link"></span></a>'+row.good.code,
            '</nobr>'
        ].join(''); 
    }    
    
    function orderFormatter(value, row){
        return [
            '<nobr>',
            "<a href='#' class='order-view-show' modal-url='/order/view/"+row.order.id+"'>" + row.order.aplId+"</a>",
            '</nobr>'
        ].join(''); 
    }    
    
    function markFormatter(value, row){
        return [
            '<nobr>',
            value.slice(0, 31),
            '</nobr>'
        ].join(''); 
    }    
    
      var menu = new BootstrapMenu('.tablerow', {
        fetchElementData: function(rowElem) {
            setCurrentIndex($(rowElem).attr('data-index'));
            return $table.bootstrapTable('getData')[getCurrentIndex()];
        },
        actionsGroups: [
//           ['statusActiv', 'statusRetired', 'repostEx'], ['history']
        ],      
        actions: {
            markStatus: {
                name: 'Проверить состояние кода',
                onClick: function(row) {
                    checkMarkStatus(row);
                },
                isEnabled: function(row) {
                    return true;
                }                
            } 
        }
    });    
    
    
    function responseHandler(res) {
        return res;
    }    
</script>
