<?php
use Stock\Entity\Mark;

$this->headTitle('Коды маркировки');

$this->mainMenu()->setActiveItemId('stock');
$this->mainMenu()->setActiveUrl($this->url('mark'));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Маркировка'=>$this->url('mark')
            ]);

?>
<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">               
                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>                                               
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/mark/content"
            data-cookie="true"
            data-cookie-id-table="markSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="false" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-query-params="queryParams"
            data-sort-name="aplId"
            data-sort-order="desc"  
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"           
            >
            <thead>
                <tr>
                     <th data-field="aplId" data-sortable="true" data-width="5">Apl Id</th>
                     <th data-field="created" data-sortable="true" data-width="10">Дата</th>             
                     <th data-field="order" data-sortable="false" data-width="10">Заказ</th>             
                     <th data-field="good" data-sortable="false" data-width="20">Артикул</th>             
                     <!--<th data-field="markGroup" data-sortable="false">Группа ЧЗ</th>-->             
                     <th data-field="mark" data-sortable="false">Код со сканера</th>
                     <th data-field="" data-formatter="activeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');

    
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }
    
    $(function () {
        

    });    
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }

        
        return params;
    }
    
    function nameFormatter(value, row){
//        var result = value;
//        if (row.level === 0){
//            result = '<strong>'+value+'</strong>';
//        }    
//        if (row.level === 2){
//            result = '<em>'+value+'</em>';
//        } 
//        
//        if (row.description){
//            result = result + ' <small style="color: #bde5a1">есть описание</small>';
//        }
//        
//        var disabled = (row.goodCount > 0 && row.hasChild === ) ? 'disabled="true"':''; 
//        var url = '/group-site/edit-form?parent='+row.id;
//        return [
//            '<button '+disabled+' type="button" class="btn btn-default btn-xs group-site-modal-show"',
//            ' aria-label="Left Align" modal-url="'+url+'" title="Добавить подгруппу">',
//            '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>',
//            '</button>',
//            ' ',
//            result
//        ].join(''); 
    }    
    
    function activeFormatter(value, row){
//        var url = '/group-site/edit-form/'+row.id;
//        if (row.pid){
//            url = url + '?parent=' + row.pid;
//        }
//        btn = '<nobr><button';
//        btn += ' type="button"';
//        btn += ' class="btn btn-default btn-xs group-site-modal-show"';
//        btn += ' aria-label="Left Align"'; 
//        btn += ' modal-url="'+url+'">';
//        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
//        btn += '</button> ';
//
//        url = '/group-site/delete/'+row.id;
//        var disabled = (row.hasChild === ) ? 'disabled="true"':''; 
//        btn += '<button '+disabled;
//        btn += ' type="button" title="Удалить '+row.name+'"';
//        btn += ' class="btn btn-default btn-xs del-group-site"';
//        btn += ' aria-label="Left Align"'; 
//        btn += ' del-url="'+url+'" del-name="'+row.name+'">';
//        btn += '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>';
//        btn += '</button></nobr>';
//        
//        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>
