<?php
use Stock\Entity\VtpGood;

$form = $this->form;

$form->get('legal_id')->setAttributes([
    'class'=>'form-control', 
    'disabled' => 'true',
    ]);

$form->get('office_id')->setAttributes([
    'class'=>'form-control', 
    'disabled' => 'true',
    ]);

$form->get('company')->setAttributes([
    'class'=>'form-control', 
    'disabled' => 'true',
    ]);

$form->get('supplier')->setAttributes([
    'class'=>'form-control', 
    'disabled' => 'true',
    ]);

$form->get('contract_id')->setAttributes([
    'class'=>'form-control', 
    'disabled' => 'true',
    ]);

$form->get('doc_date')->setAttributes([
    'class'=>'form-control', 
    'min' => date('Y-m-d', strtotime($allowDate.' + 1 day')),
    'disabled' => $disabled,
    ]);

$form->get('doc_no')->setAttributes([
    'class'=>'form-control', 
    'disabled' => 'true',
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('cause')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('statusDoc')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('ptu')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'vtp-submit']);

$form->prepare();

$docName = 'Новый';
$ptuDocName = '№ '.$ptu->getDocNo().' от  '.date('d.m.Y', strtotime($ptu->getDocDate()));
if ($vtp){
    $docName = '№ '.$vtp->getDocNo().' от  '.date('d.m.Y', strtotime($vtp->getDocDate()));
}

?>
<?= $this->form()->openTag($form); ?>

<div class="modal-header">
    <h5 class="modal-title" id="vtpModalLabel">Возврат товаров поставщику <?= $docName?> по ПТУ <?= $ptuDocName?></h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <div class="row">
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('office_id')); ?>
                <?= $this->formElement($form->get('office_id')); ?>
                <?= $this->formElementErrors($form->get('office_id')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('supplier')); ?>
                <?= $this->formElement($form->get('supplier')); ?>
                <?= $this->formElementErrors($form->get('supplier')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('statusDoc')); ?>
                <?= $this->formElement($form->get('statusDoc')); ?>
                <?= $this->formElementErrors($form->get('statusDoc')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>                  
            </div>
        </div>
        <div class="col-xs-2 text-right">
            <h1 class="display-4" id="vtpQuantity"></h1>
        </div>    
        <div class="col-xs-1 text-right">
            <h1 class="display-4" id="vtpAmount"><?= ($vtp) ? round($vtp->getAmount(), 2):"" ?></h1>                        
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('doc_date')); ?>
                <?= $this->formElement($form->get('doc_date')); ?>
                <?= $this->formElementErrors($form->get('doc_date')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('company')); ?>
                <?= $this->formElement($form->get('company')); ?>
                <?= $this->formElementErrors($form->get('company')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('legal_id')); ?>
                <?= $this->formElement($form->get('legal_id')); ?>
                <?= $this->formElementErrors($form->get('legal_id')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('contract_id')); ?>
                <?= $this->formElement($form->get('contract_id')); ?>
                <?= $this->formElementErrors($form->get('contract_id')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4 text-right">
        </div>    
    </div>        
    <div class="row">
        <div class="col-xs-4">
            <div class="form-group">
                <?= $this->formElement($form->get('ptu')); ?>
                <?= $this->formElementErrors($form->get('ptu')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-12">
            <div id="vtpgoodtoolbar">
                <div class="form-inline" role="form">
                    <button type="button" class="btn btn-default" onclick="vtpFill()">
                        <span aria-hidden="true">Заполнить из ПТУ</span>
                    </button>
                    <button id="remove-selected-button" class="btn btn-default" type="button" title="Удалить выделенное">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </button>                
                </div>    
            </div>
            <table id="vtpgoodtable" 
                data-toggle="vtpgoodtable" 
                data-url="/vtp/good-content/<?= ($vtp) ? $vtp->getId():"" ?>"
                data-side-pagination="client"
                data-pagination="true"
                data-page-size = "5"
                data-page-list="[5, 10, 20, 50]"
                data-toolbar="#vtpgoodtoolbar"
                data-show-refresh="true"
                data-show-toggle="false"
                data-query-params="vtpgoodQueryParams"
                data-response-handler="vtpgoodResponseHandler"
                data-unique-id = "rowNo"
                data-classes = "table table-bordered table-hover table-condensed"
                data-row-style="vtpTakeStyle"
                data-click-to-select="true"
                >
                <thead>
                    <tr>
                        <th data-checkbox="true"></th>
                        <th data-field="rowNo" data-type="numeric" data-align="right">N</th>
                        <th data-field="vtpg.good.code" data-formatter="goodFormatter">Артикул</th>
                        <th data-field="vtpg.good.producer.name">Производитель</th>
                        <th data-field="vtpg.good.name">Наименование</th>
                        <th data-field='price' data-type="numeric" data-always-use-formatter="true" data-editable="true" data-formatter="pgPriceFormatter" data-align="right">Цена</th>
                        <th data-field='quantity' data-type="numeric" data-editable="true" data-always-use-formatter="true" data-align="right">Количество</th>
                        <th data-field='amount' data-type="numeric" data-always-use-formatter="true" data-formatter="pgAmountFormatter" data-align="right">Сумма</th>
                        <th data-field="rowNo" data-formatter="pgActiveFormatter" data-width="10"></th>
                     </tr>                
                </thead>
            </table>
        </div>
    </div>    
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?= $this->formLabel($form->get('comment')); ?>
                <?= $this->formElement($form->get('comment')); ?>
                <?= $this->formElementErrors($form->get('comment')); ?>                  
            </div>                        
        </div>                                            
    </div>        
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?= $this->formLabel($form->get('cause')); ?>
                <?= $this->formElement($form->get('cause')); ?>
                <?= $this->formElementErrors($form->get('cause')); ?>                  
            </div>                        
        </div>                                            
    </div>        




            <?= $this->formElement($form->get('csrf')); ?>
        </div>
    </div>
</div>    

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary" id="vtp-submit" <?= $disabled ? 'disabled':''; ?>>Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script>
    function vtpUpdateTotal(){
        var data = $('#vtpgoodtable').bootstrapTable('getData');
        var amount = 0; var quantity = 0;
        $.each(data, function( index, value ) {
            let result = value.price.toString().replace(',', '.');
            amount += Math.round(result*value.quantity*100)/100;
            quantity += Math.round(value.quantity*100)/100; 
        });
        $('#vtpAmount').html(Math.round(amount*100)/100);
        $('#vtpQuantity').html(Math.round(quantity*100)/100);
    }
    
    function vtpFill(){
        $.ajax({
            type: 'GET',
            url: "/ptu/good-content/<?= ($ptu) ? $ptu->getId():"" ?>"
        })
            .done(function (data) {
                $('#vtpgoodtable').bootstrapTable('removeAll');
                var rows = [];
                $.each( data, function( index, row ) { 
                    var good = {
                        id: row.good.id,
                        code: row.good.code,
                        name: row.good.name,
                        producer: {name: row.good.producer.name}
                    };
                    var vtpg = {
                        good: good
                    };
                    var row = {
                        rowNo: index+1,
                        vtpg: vtpg,
                        amount: row.amount,
                        quantity: row.quantity,
                        price: Math.round(row.amount*100/row.quantity)/100
                    };

                    rows.push(row);
                });   
                $('#vtpgoodtable').bootstrapTable('append', rows);                        
                vtpUpdateTotal();
            })
            .fail(function () {
                alert("Ошибка при получении данных.");

            });            
    }
    
    function submitForm(){
        $('#vtp-submit').prop('disabled', true);
        var data = serializeForm('#vtp-form');
        data.vtpGood = getFormatedVtpGood();
        $.ajax({
            type: 'POST',
            url: '/vtp/edit-form/<?= ($vtp) ? $vtp->getId():"" ?>?ptu=<?= ($ptu) ? $ptu->getId():"" ?>',
            data: $.param(data)
        })
            .done(function (data) {
                $('#vtp-submit').prop('disabled', false);
                if (data == 'ok'){
                    $('#vtpModal').modal('hide');
                    $('#vtptable').bootstrapTable('refresh');
                } else {
                    $('#vtpModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");
                $('#vtp-submit').prop('disabled', false);
            });    
    };
    
    function getFormatedVtpGood(){
        var data = $('#vtpgoodtable').bootstrapTable('getData');
        var result = [];
        $.each( data, function( index, row ) {
            let rowPrice = row.price.toString().replace(',', '.');
            var newRow = {
                good_id: row.vtpg.good.id,
                quantity: row.quantity,
                amount: rowPrice*row.quantity,
            };
            result.push(newRow);
        });   
        return result;
    }
        
    //удаление строки из таблицы
    function removeTableRowByUniqueId(index){
        $('#vtpgoodtable').bootstrapTable('removeByUniqueId', index);
        vtpUpdateTotal();
    }
    
    $( document ).ready(function() {
        
        $('#remove-selected-button').click(function () {
            var ids = $.map($('#vtpgoodtable').bootstrapTable('getSelections'), function (row) {
              return row.rowNo;
            });
            $('#vtpgoodtable').bootstrapTable('remove', {
              field: 'rowNo',
              values: ids
            });
            vtpUpdateTotal();
        });        
        
        $('#vtpgoodtable').bootstrapTable({
            onLoadSuccess: function(res){
                vtpUpdateTotal();
            }            
        }); 
        var forms = $('#vtp-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('vtp-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });
    });    
    
    $(document).on('editable-save.bs.table', '#vtpgoodtable', function (e, field, row, old, $el) {
        vtpUpdateTotal();
    });        
    
    function vtpGoodRefreshTable(){
        $('#vtpgoodtable').bootstrapTable('refresh');
    }
    
    function vtpgoodQueryParams(params) {
        $('#vtpgoodtoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#vtpgoodtable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#vtpgoodtable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function vtpTakeStyle(row){
        var classes = 'default';
        if (row.vtpg.take === "<?= VtpGood::TAKE_NO?>"){
            classes = 'warning';
        }        
        return {classes: classes};
    }
    
    function pgActiveFormatter(value, row){
        var url = '/vtp/good-edit-form/';
        btn = '<button';
//        btn += ' type="button"';
//        btn += ' class="btn btn-default btn-xs vtp-good-modal-show"';
//        btn += ' aria-label="Left Align"'; 
//        btn += ' unique-id="'+value+'"';
//        btn += ' modal-url="'+url+'">';
//        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
//        btn += '</button>';
//
//        btn += ' <button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs table-row-remove"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="removeTableRowByUniqueId('+value+')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function goodFormatter(value, row){
        var url = '/goods/view/'+row.vtpg.good.id;
        btn = '<nobr><a';
        btn += ' href="'+url+'"';
        btn += ' class="btn btn-link btn-xs" target="_blank">';
        btn += '<span class="glyphicon glyphicon-link"></span>';
        btn += '</a>'+value + '</nobr>';
        return btn;
    }    
    
    function pgPriceFormatter(value, row){
//        console.log(value);
        let result = value.toString().replace(',', '.');
        return (Math.round(result*100)/100).toFixed(2);
    }        
        
    function pgAmountFormatter(value, row){
        let result = row.price.toString().replace(',', '.');
        return (Math.round(result*row.quantity*100)/100).toFixed(2);
    }        

    function vtpgoodResponseHandler(res) {
        return res;
    }     
</script>