<?php
    use Stock\Entity\Vtp;
    
    $this->headTitle('Возврат товаров поставщику');

    $this->mainMenu()->setActiveItemId('raw');
    $this->mainMenu()->setActiveUrl($this->url('vtp'));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Возврат товаров поставщику'=>$this->url('vtp'),
                ]);


?>


<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <div class="btn-group">
                        <input id="searchinput" name="search" style="width: 150px" class="form-control" type="text" placeholder="Артикул">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>
                    <button id="ok" type="submit" class="btn btn-default" title="Поиск">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
                <div class="form-group">
                    <select id="supplierSelect" style="width: 250px" class="form-control">
                        <option selected>поставщик</option>
                        <?php foreach ($suppliers as $supplier):?>
                            <option value="<?= $supplier->getId()?>"><?= $supplier->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <select id="officeSelect" style="width: 100px" class="form-control">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <input id="monthSelect" class="form-control" type="month" placeholder="Период" value="<?= date('Y-m');?>">
                </div>
                <div class="form-group">
                    <select id="statusDocSelect" style="width: 200px" class="form-control">
                        <option selected>статус возврата</option>
                        <?php foreach (Vtp::getStatusDocList() as $key=>$value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="statusSelect" style="width: 200px" class="form-control">
                        <option selected>статус документа</option>
                        <?php foreach (Vtp::getStatusList() as $key=>$value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
            </div>
        </div>
        <table id="vtptable" 
            data-toggle="table" 
            data-url="/vtp/content"
            data-cookie="true"
            data-cookie-id-table="vtpSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="rowStyle"
            >
            <thead>
                <tr>
                     <!--<th data-field="id" data-type="numeric" data-sortable="true" data-align="right">ID</th>-->
                     <th data-field="docDate" data-sortable="true">Дата</th>
                     <th data-field="ptu.docDate" data-sortable="false">Дата поступления</th>
                     <th data-field="id" data-sortable="false" data-formatter="docNumFormatter">Номер</th>
                     <!--<th data-field="aplId" data-type="numeric" data-align="right">AplId</th>-->
                     <th data-field='amount' data-sortable="true" data-align="right" data-formatter="amountFormatter">Сумма</th>
                     <th data-field='ptu.legal.name' data-sortable="false">Поставщик</th>
                     <!--<th data-field='ptu.contract.name' data-sortable="false">Договор</th>-->
                     <th data-field='ptu.office.name' data-sortable="false">Склад</th>
                     <th data-field='comment' data-sortable="false">Примечание</th>
<!--                     <th data-field='status' data-sortable="false">П</th>
                     <th data-field='statusDoc' data-sortable="false">Т</th>
                     <th data-field='statusEx' data-sortable="false">О</th>-->
                     <th data-field="id" data-formatter="printFormatter">Торг2</th>
                     <th data-field="id" data-formatter="updFormatter">УПД</th>
                     <th data-field="id" data-formatter="activeFormatter" data-align="center"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    var $table = $('#vtptable'),
       $ok = $('#ok');

    function refreshTable(){
        $table.bootstrapTable('refresh');
    }

    
    $(function () {
        $(document).on('change', '#statusDocSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#statusSelect', function (e) {
            refreshTable();
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#vtptable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#vtptable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.supplier = $('#supplierSelect').val();
        params.office = $('#officeSelect').val();
        params.month = $('#monthSelect').val();
        params.statusDoc = $('#statusDocSelect').val();
        params.status = $('#statusSelect').val();
        
        return params;
    }
    
    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status === '<?= Vtp::STATUS_RETIRED?>'){
           retired += ' retired';
           return {classes: retired};
        }
        if (row.statusAccount === '<?= Vtp::STATUS_TAKE_NO?>'){
           retired += ' warning';
           return {classes: retired};
        }
        if (row.statusAccount === '<?= Vtp::STATUS_TAKE_NO?>'){
           retired += ' warning';
           return {classes: retired};
        }
        switch(row.statusDoc){
            case '<?= Vtp::STATUS_DOC_NOT_RECD?>': 
                        return {classes: retired}; break;
            case '<?= Vtp::STATUS_DOC_RECD?>': 
                        return {classes: 'info '+retired}; break;
            case '<?= Vtp::STATUS_DOC_NOT_RECD?>': 
                        return {classes: 'success '+retired}; break;
                default:break;     
        }
        
        return {classes: retired};
    }
        
    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    

    function docNumFormatter(value, row){
        if (row.aplId > 0){
            return value+' ('+row.aplId+')';
        }
        return value;
    }    
    
    function activeFormatter(value, row){
        var url = '/vtp/edit-form/'+value;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs vtp-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';

        return btn;
    }    
    
    function printFormatter(value, row){

        var url = '/print/vtp-torg2/'+value;
        btn = '<a href="'+url+'" target="_blank">pdf</a>';
        url = '/print/vtp-torg2/'+value+'?ext=Xls';
        btn += ' <a href="'+url+'" target="_blank">xls</a>';
        return btn;
    }    
    
    function updFormatter(value, row){

        var url = '/print/vtp-upd/'+value;
        btn = '<a href="'+url+'" target="_blank">pdf</a>';
        url = '/print/vtp-upd/'+value+'?ext=Xls';
        btn += ' <a href="'+url+'" target="_blank">xls</a>';
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
    
    function changeStatus(vtpId, status){
        $.get( "/vtp/status/"+vtpId+'?status='+status, function(data){
            refreshTable();
        });        
    }

    function changeStatusDoc(vtpId, statusDoc){
        $.get( "/vtp/status-doc/"+vtpId+'?status='+statusDoc, function(data){
            refreshTable();
        });        
    }
    
    var menu = new BootstrapMenu('.tablerow', {
        fetchElementData: function(rowElem) {
            var rowId = $(rowElem).attr('data-index');
            return $table.bootstrapTable('getData')[rowId];
        },
        actionsGroups: [
           ['statusActiv', 'statusRetired']
        ],      
        actions: {
            statusDocNew: {
                name: 'Новый',
                onClick: function(row) {
                    changeStatusDoc(row.id, <?= Vtp::STATUS_DOC_NEW?>);
                },
                isShown: function(row) {
                  return row.statusDoc !== '<?= Vtp::STATUS_DOC_NEW?>';
                },
                isEnabled: function(row) {
                    return row.docDate > '<?= $allowDate?>';
                }                
            }, 
            statusDocRect: {
                name: 'Отправлен',
                classNames: 'bg-info',
                onClick: function(row) {
                    changeStatusDoc(row.id, <?= Vtp::STATUS_DOC_RECD?>);
                },
                isShown: function(row) {
                  return row.statusDoc != '<?= Vtp::STATUS_DOC_RECD?>';
                },
                isEnabled: function(row) {
                    return row.docDate > '<?= $allowDate?>';
                }                
            }, 
            statusDocNotRect: {
                name: 'Принят',
                iconClass: 'glyphicon glyphicon-ok',
                classNames: 'bg-success',
                onClick: function(row) {
                    changeStatusDoc(row.id, <?= Vtp::STATUS_DOC_NOT_RECD?>);
                },
                isShown: function(row) {
                  return row.statusDoc != '<?= Vtp::STATUS_DOC_NOT_RECD?>';
                },
                isEnabled: function(row) {
                    return row.docDate > '<?= $allowDate?>';
                }                
            }, 
            statusActiv: {
                name: 'Сделать активным',
                iconClass: 'glyphicon glyphicon-ok',
                onClick: function(row) {
                    changeStatus(row.id, <?= Vtp::STATUS_ACTIVE?>);
                },
                isShown: function(row) {
                  return row.status == <?= Vtp::STATUS_RETIRED?>;
                },
                isEnabled: function(row) {
                    return row.docDate > '<?= $allowDate?>';
                }                
            }, 
            statusRetired: {
                name: 'Сделать не активным',
                iconClass: 'glyphicon glyphicon-remove',
//                classNames: 'bg-danger',
                onClick: function(row) {
                    changeStatus(row.id, <?= Vtp::STATUS_RETIRED?>);
                },
                isShown: function(row) {
                  return row.status == <?= Vtp::STATUS_ACTIVE?>;
                },
                isEnabled: function(row) {
                    return row.docDate > '<?= $allowDate?>';
                }                
            }
        }
    });    
</script>

