<?= $this->doctype() ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('adminapl.ru')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= 
            $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/ajax-bootstrap-select.min.css'))

//                ->prependStylesheet('//cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css')  

                ->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')

//                ->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css') 

    //            ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css')
    //            ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css')
                ->prependStylesheet('//stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css', 
                        'screen',
                        true,
                        [
                            'rel' => 'stylesheet', 
                            'integrity' => 'sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ',
                            'crossorigin' => 'anonymous',
                        ]
                )
                ->prependStylesheet('//stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css', 
                        'screen',
                        true,
                        [
                            'rel' => 'stylesheet', 
                            'integrity' => 'sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu',
                            'crossorigin' => 'anonymous',
                        ]
                )
        
//                ->prependStylesheet('//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css', 
//                        'screen',
//                        true,
//                        [
//                            'rel' => 'stylesheet', 
//                            'integrity' => 'sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO',
//                            'crossorigin' => 'anonymous',
//                        ]
//                )        
                    
                ->prependStylesheet('//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css')
                ->prependStylesheet('//cdn.jsdelivr.net/npm/bootstrap-select@1.13.18/dist/css/bootstrap-select.min.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/ajax-bootstrap-select.ru-RU.min.js'))
            ->prependFile($this->basePath('js/ajax-bootstrap-select.min.js'))
            ->prependFile($this->basePath('js/control-modal.min.js'))
            ->prependFile($this->basePath('js/jquery.mask.min.js'))
        
            ->prependFile('//cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.7/dist/latest/bootstrap-autocomplete.min.js')
        
//            ->prependFile('//cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-ru_RU.min.js')
//            ->prependFile('//cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js')
        
//            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
//            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
            ->prependFile('//unpkg.com/bootstrap-table@1.19.1/src/locale/bootstrap-table-ru-RU.js')
            ->prependFile('//unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js')
        
            // bootstrap3!!
//            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js')
//      
//            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js')
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js')
        
//            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js')
            ->prependFile('//stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js', 'text/javascript', [
                'integrity' => 'sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd',
                'crossorigin' => 'anonymous',
            ])
        
            //bootstrap 4
//            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js', 'text/javascript', [
//                'integrity' => 'sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49',
//                'crossorigin' => 'anonymous',
//            ])        
//            ->prependFile('//stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js', 'text/javascript', [
//                'integrity' => 'sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy',
//                'crossorigin' => 'anonymous',
//            ])
        
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js')
//            ->prependFile('//code.jquery.com/ui/1.13.1/jquery-ui.js')
        ?>
    </head>
    <body>
        <div class="container">
            <div class="col-md-12">
                <?php
                    // Check if the activeMenuItemId passed to layout view model
                    // and if so, use it for setting active navbar item.
                    if (isset($activeMenuItemId)) {
                        $this->mainMenu()->setActiveItemId($activeMenuItemId);
                    }

                    // Render the navbar
                    echo $this->mainMenu()->render(); 
                ?>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->
                    <?= $this->pageBreadcrumbs()->render(); ?>
                </div>
            </div>                
            <div class="row">
                <?= $this->content ?>
                <hr>
                <footer>
                    <p>&copy; <?= date('Y') ?> adminapl.ru</p>
                </footer>
            </div>
        </div>
        
        <div class="modal fade" id="modal-dialog" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content" id="modal-content">
                </div>
            </div>
        </div>
    </body>
</html>

        
<?= $this->inlineScript() ?>
<script type="text/javascript">
    /*
    * проверка на авторизацию
    */

    var checkLogin = function(){
        $.ajax({
            type: 'POST',
            url: '/application/check-login'
        })
            .done(function (data) { 
                if (data){
                    if (data.response == 'ok' && !data.ident){
                        window.location.reload();
                    }
                }    
                setTimeout(checkLogin, 60000);
            })
            .fail(function (e) {
                console.log(e);
            });                
    }

    // вызов проверки на авторизацию
    //checkLogin();

    //сериализация формы
    function serializeForm(node)
    {
        var formdata = $(node).serializeArray();
        var result = {};
        $(formdata).each(function(index, obj){
            if (obj.name.indexOf('[]') > 0){
                if (Array.isArray(result[obj.name])){
                    result[obj.name].push(obj.value);
                } else {
                    result[obj.name] = [obj.value];
                }    
            } else {
                result[obj.name] = obj.value;
            }    
        });    
        //alert(result);
        return result;
    }

    //получить новый номер строки таблицы
    function getNewTableUniqueId(tableName, fieldName)
    {
        var data = $('#'+tableName).bootstrapTable('getData');
        var result = 0;
        $.each(data, function( index, value ) {
            if (value[fieldName] > result){
                result = value[fieldName];
            }
        });
        result++;
        return result;
    }

    function showFormDialog(params)
    {
        //https://itchief.ru/bootstrap/modal-dynamic-creation

        $.ajax({
            url: params.url,
        }).done(function(data) {
            var modalDialog = new ModalApp.ModalProcess({
                id: params.id,
            });
            modalDialog.init();

            $('#' + modalDialog.id + ' .modal-header').remove();
            $('#' + modalDialog.id + ' .modal-footer').remove();
            $('#' + modalDialog.id).modal({
                backdrop: 'static',
                keyboard: true
            });
            $('#' + modalDialog.id).attr('data-focus-on', "input:first");

            if (params.zIndex){
                $('#' + modalDialog.id).css('z-index', params.zIndex);                        
            }
            if (params.width){
                $('#' + modalDialog.id + ' .modal-dialog').css('width', params.width);                        
            }

            modalDialog.changeBody(data);

            modalDialog.showModal();

            $('#' + modalDialog.id).on('hidden.bs.modal', function (e) {
                modalDialog.changeBody('');
            });                                    
        });                                                
    }

    $('#modal-dialog').on('show.bs.modal', function (e) {        
        var url = e.relatedTarget.value;
        if (url){
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                   $('#modal-content').html(data);
                })
                .fail(function () {
                    alert("Ошибка открытия формы.");
                }); 
        }
    })    


    //удаление по классу
    $('.this-delete').on('click', function(e) {
        var url = e.currentTarget.value;
        if (url){
            if (confirm('Удалить запись?')){
                var dialog = bootbox.dialog({
                    message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                    closeButton: false
                });

                $.ajax({
                    type: 'GET',
                    url: url,
                })
                    .done(function (data) {
                        if (data == 'ok'){
                            bootbox.alert("Ок!");
                            window.location.reload();
                        } else {
                            alert("Не удалось удалить!");
                        }    
                    })
                    .fail(function (e) {
                        alert("Не удалось удалить.");

                    });
            }        
        }        
    })    

    /*
    *Удаление в bootstrap таблице
    *str url - ссылка на удаление строки таблицы
    */
    function tableRowDelete(url, table = 'table') {
        if (url){
            if (confirm('Удалить запись?')){
                var table = $('#'+table);
                var dialog = bootbox.dialog({
                    message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                    closeButton: false
                });

                $.ajax({
                    type: 'GET',
                    url: url,
                })
                    .done(function (data) {
                        if (data == 'ok'){
                            dialog.modal('hide');
                            table.bootstrapTable('refresh');
                        } else if (data == 'ok-reload'){
                            window.location.reload();
                        } else {
                            alert("Не удалось удалить!");
                        }    
                    })
                    .fail(function (e) {
                        alert("Не удалось удалить.");

                    });
            }        
        }        
    }   

    $('.refresh-button').on('click', function(e) {
        var url = e.currentTarget.value;

        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    if (data == 'ok'){
                        bootbox.alert("Ок!");
                        window.location.reload();
                    }    
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })    

    $('.refresh-table-button').on('click', function(e) {
        var url = e.currentTarget.value;
        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (obj) {
                    dialog.modal('hide');
//                            var data = jQuery.parseJSON(obj);
                    data = obj;
                    if (data.result == 'ok'){
                        //bootbox.alert("Ок!");
                        $('#table').bootstrapTable('refresh');
                    } else if (data.result == 'ok-reload'){
                        //bootbox.alert("Ок!");
                        window.location.reload();
                    } else {
                        dialog = bootbox.dialog({
                            message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>'+data.message+'</p>',
                            closeButton: true
                        });
                    }    
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })    

    //форматирование числа
    numberFormat = function(value){
        var res = parseFloat(value).toFixed(2);
        res = res.replace('.',',');
        return res.replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1&nbsp;")
    }

    /**
    * Объект или массив в html
     * @param Object|Array obj
     * @returns {String}
     *              */
    objectToHtml = function(obj){
        var result = '<div>';
        $.each( obj, function( key, value ) {
            if (jQuery.isPlainObject(value) || jQuery.isArray(value)){
                result = result + '<div>' + key + '</div>';
                result = result + objectToHtml(value);
            } else {
                result = result + '<div><span>' + key + '</span>: <span>' + value + '</span></div>';
            }    
        });

        result = result + '</div>';
        return result;
    }


</script>        
