<?= $this->doctype() ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('adminapl.ru')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= 
            $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))

                ->prependStylesheet('//cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css', 
                        'screen',
                        true,
                        [
                            'rel' => 'stylesheet', 
                        ]
                )

                ->prependStylesheet('//cdn.jsdelivr.net/npm/bootstrap-select@1.13.18/dist/css/bootstrap-select.min.css')

                ->prependStylesheet('//unpkg.com/bootstrap-table@1.20.2/dist/extensions/reorder-rows/bootstrap-table-reorder-rows.css', 
                        'screen',
                        true,
                        [
                            'rel' => 'stylesheet', 
                        ]
                )

                ->prependStylesheet('//cdn.jsdelivr.net/npm/x-editable@1.5.1/dist/bootstrap3-editable/css/bootstrap-editable.css', 
                        'screen',
                        true,
                        [
                            'rel' => 'stylesheet', 
                        ]
                )

                ->prependStylesheet('//unpkg.com/bootstrap-table@1.20.2/dist/bootstrap-table.min.css',
                        'screen',
                        true,
                        [
                            'rel' => 'stylesheet', 
                        ]
                )


                ->prependStylesheet('//stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css', 
                        'screen',
                        true,
                        [
                            'rel' => 'stylesheet', 
                            'integrity' => 'sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ',
                            'crossorigin' => 'anonymous',
                        ]
                )
                

                ->prependStylesheet('//stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css', 
                        'screen',
                        true,
                        [
                            'rel' => 'stylesheet', 
                            'integrity' => 'sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu',
                            'crossorigin' => 'anonymous',
                        ]
                )
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/control-modal.min.js'))
            ->prependFile($this->basePath('js/jquery.mask.min.js'))
            ->prependFile($this->basePath('js/bootstrap3-typeahead.min.js'))
            ->prependFile($this->basePath('js/BootstrapMenu.min.js'))
        
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/jquery-dateFormat/1.0/jquery.dateFormat.min.js')
            ->prependFile('//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js')

//            ->prependFile('//cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.7/dist/latest/bootstrap-autocomplete.min.js')
        
            ->prependFile('//cdn.jsdelivr.net/npm/summernote@0.8.18/lang/summernote-ru-RU.js')
            ->prependFile('//cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js')

            ->prependFile('//cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-ru_RU.min.js')
            ->prependFile('//cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js')
        
            ->prependFile('//unpkg.com/bootstrap-table@1.21.0/dist/extensions/reorder-rows/bootstrap-table-reorder-rows.min.js')
            ->prependFile('//cdn.jsdelivr.net/npm/x-editable@1.5.1/dist/bootstrap3-editable/js/bootstrap-editable.min.js')

            ->prependFile('//unpkg.com/bootstrap-table@1.21.0/dist/extensions/auto-refresh/bootstrap-table-auto-refresh.min.js')
            ->prependFile('//unpkg.com/bootstrap-table@1.21.0/dist/extensions/editable/bootstrap-table-editable.min.js')
            ->prependFile('//unpkg.com/bootstrap-table@1.21.0/dist/extensions/cookie/bootstrap-table-cookie.min.js')
            ->prependFile('//unpkg.com/bootstrap-table@1.21.0/src/locale/bootstrap-table-ru-RU.js')
            ->prependFile('//unpkg.com/bootstrap-table@1.21.0/dist/extensions/export/bootstrap-table-export.min.js')
            ->prependFile('//unpkg.com/bootstrap-table@1.21.0/dist/bootstrap-table.min.js')
            ->prependFile('//cdn.jsdelivr.net/npm/tablednd@1.0.5/dist/jquery.tablednd.min.js')
            ->prependFile('//cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.10.21/tableExport.min.js')
            ->prependFile('//cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.10.21/libs/jsPDF/jspdf.min.js')
//            ->prependFile('//cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.10.21/libs/jsPDF-AutoTable/jspdf.plugin.autotable.js')
        
            // bootstrap3!!
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js')
        
            ->prependFile('//stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js', 'text/javascript', [
                'integrity' => 'sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd',
                'crossorigin' => 'anonymous',
            ])
        
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js')

        ?>
    </head>
    <style>
    </style>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/"><strong>АдминАПЛ</strong><sup>.ru</sup></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
<!--              <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
              </ul>-->
                <form class="navbar-form navbar-right" action="/order/search" method="GET">
                    <input type="text" name="orderId" class="form-control" placeholder="№ заказа">
                    <button type="submit" class="btn btn-default" title="Перейти">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </form>
            </div>
          </div>
        </nav>        
        
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <?php
                        if (isset($activeMenuItemId)) {
                            $this->mainMenu()->setActiveItemId($activeMenuItemId);
                        }

                        echo $this->mainMenu()->render(); 
                    ?>
                </div>                
                
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

                    <!--<div class="row">
                        <div class="col-md-12">
                             Breadcrumbs 
                            <?php //echo $this->pageBreadcrumbs()->render(); ?>
                        </div>
                    </div>                -->

                    <?php echo $this->content ?>

                    <div class="modal fade" id="modal-dialog" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content" id="modal-content">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </body>
</html>

        
<?= $this->inlineScript() ?>
<script type="text/javascript">
    $('.phone').mask('8 (000) 000-0000', {selectOnFocus: true});    

    $('.nav-second').on('show.bs.collapse', function () {
        $('.nav-second.in').collapse('hide');
    });
    
    /*
    * проверка на авторизацию
    */

    var checkLogin = function(){
        $.ajax({
            type: 'POST',
            url: '/application/check-login'
        })
            .done(function (data) { 
                if (data){
                    if (data.response == 'ok' && !data.ident){
                        window.location.reload();
                    }
                }    
                setTimeout(checkLogin, 60000);
            })
            .fail(function (e) {
                console.log(e);
            });                
    };

    // вызов проверки на авторизацию
    //checkLogin();

    //сериализация формы
    function serializeForm(node)
    {
        var formdata = $(node).serializeArray();
        var result = {};
        $(formdata).each(function(index, obj){
            if (obj.name.indexOf('[]') > 0){
                if (Array.isArray(result[obj.name])){
                    result[obj.name].push(obj.value);
                } else {
                    result[obj.name] = [obj.value];
                }    
            } else {
                result[obj.name] = obj.value;
            }    
        });    
        //alert(result);
        return result;
    }

    //получить новый номер строки таблицы
    function getNewTableUniqueId(tableName, fieldName)
    {
        var data = $('#'+tableName).bootstrapTable('getData');
        var result = 0;
        $.each(data, function( index, value ) {
            if (value[fieldName] > result){
                result = value[fieldName];
            }
        });
        result++;
        return result;
    }

    /**
     * Открыть окно 
     * @param object params
     * @returns 
     */
    function showFormDialog(params)
    {
        //https://itchief.ru/bootstrap/modal-dynamic-creation

        $.ajax({
            url: params.url
        }).done(function(data) {
            var modalDialog = new ModalApp.ModalProcess({
                id: params.id
            });
            modalDialog.init();

//            modalDialog.changeTitle('');
//            modalDialog.changeBody('');
//            modalDialog.changeFooter('');
            $('#' + modalDialog.id + ' .modal-header').remove();
            $('#' + modalDialog.id + ' .modal-footer').remove();

            $('#' + modalDialog.id).modal({
                backdrop: 'static',
                keyboard: true
            });
            $('#' + modalDialog.id).attr('data-focus-on', "input:first");

            if (params.zIndex){
                $('#' + modalDialog.id).css('z-index', params.zIndex);                        
            }
            if (params.width){
                $('#' + modalDialog.id + ' .modal-dialog').css('width', params.width);                        
            }

            modalDialog.changeBody(data);

            modalDialog.showModal();

            $('#' + modalDialog.id).on('hidden.bs.modal', function (e) {
                modalDialog.changeBody('');
            });                                    
        });                                                
    }

    /**
     * Открыть окно лучше
     * @param object modalDialog
     * @param object params
     * @returns {undefined}
     */
    function dialogModalShow(modalDialog, params)
    {
        //https://itchief.ru/bootstrap/modal-dynamic-creation

        $.ajax({
            url: params.url
        }).done(function(data) {

            $('#' + modalDialog.id + ' .modal-header').remove();
            $('#' + modalDialog.id + ' .modal-footer').remove();

            $('#' + modalDialog.id).modal({
                backdrop: 'static',
                keyboard: true
            });
            $('#' + modalDialog.id).attr('data-focus-on', "input:first");

            if (params.zIndex){
                $('#' + modalDialog.id).css('z-index', params.zIndex);                        
            }
            if (params.width){
                $('#' + modalDialog.id + ' .modal-dialog').css('width', params.width);                        
            }

            modalDialog.changeBody(data);

            modalDialog.showModal();

            $('#' + modalDialog.id).on('hidden.bs.modal', function (e) {
                modalDialog.changeBody('');
            });                                    
        });                                                
    }

    $(document).ready(function(){
        $('button').on('click', function(){
            $('button').removeClass('marked');
            $(this).addClass('marked');
        });
        $(document).on('click', '.supplier-link', function (e) {
            let id = $(e.currentTarget).attr('supplier-id');
            $.get( "/supplier/site/"+id, function(data){
                if (data.url){
                    window.open(data.url, '_blank');
                } else {
                    bootbox.alert('Сайт не указан в карточке поставщика!');
                }
            });        
        });        
    });    

    $('#modal-dialog').on('show.bs.modal', function (e) {        
        var url = e.relatedTarget.value;
        if (url){
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                   $('#modal-content').html(data);
                })
                .fail(function () {
                    alert("Ошибка открытия формы.");
                }); 
        }
    });    


    //удаление по классу
    $('.this-delete').on('click', function(e) {
        var url = e.currentTarget.value;
        if (url){
            if (confirm('Удалить запись?')){
                var dialog = bootbox.dialog({
                    message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                    closeButton: false
                });

                $.ajax({
                    type: 'GET',
                    url: url
                })
                    .done(function (data) {
                        if (data == 'ok'){
                            bootbox.alert("Ок!");
                            window.location.reload();
                        } else {
                            alert("Не удалось удалить!");
                        }    
                    })
                    .fail(function (e) {
                        alert("Не удалось удалить.");

                    });
            }        
        }        
    });    

    /*
    *Удаление в bootstrap таблице
    *str url - ссылка на удаление строки таблицы
    */
    function tableRowDelete(url, table = '$table') {
        if (url){
            if (confirm('Удалить запись?')){
                var table = $('#'+table);
                var dialog = bootbox.dialog({
                    message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                    closeButton: false
                });

                $.ajax({
                    type: 'GET',
                    url: url
                })
                    .done(function (data) {
                        if (data == 'ok'){
                            dialog.modal('hide');
                            table.bootstrapTable('refresh');
                        } else if (data == 'ok-reload'){
                            window.location.reload();
                        } else {
                            alert("Не удалось удалить!");
                        }    
                    })
                    .fail(function (e) {
                        alert("Не удалось удалить.");

                    });
            }        
        }        
    }   

    $('.refresh-button').on('click', function(e) {
        var url = e.currentTarget.value;

        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    if (data == 'ok'){
                        bootbox.alert("Ок!");
                        window.location.reload();
                    }    
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    });    

    $('.refresh-table-button').on('click', function(e) {
        var url = e.currentTarget.value;
        var table = $(this).attr('data-table');
        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (obj) {
                    dialog.modal('hide');
//                            var data = jQuery.parseJSON(obj);
                    data = obj;
                    if (data.result == 'ok'){
                        if (table){
                            $('#'+table).bootstrapTable('refresh');
                        } else {
                            $('#table').bootstrapTable('refresh');
                        }    
                    } else if (data.result == 'ok-reload'){
                        //bootbox.alert("Ок!");
                        window.location.reload();
                    } else {
                        dialog = bootbox.dialog({
                            message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>'+data.message+'</p>',
                            closeButton: true
                        });
                    }    
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    }); 
    
    $('.enter-search').on('keypress', function(e){
        if (e.keyCode === 13) {
            refreshTable();
        }
    });
        
    //форматирование числа
    numberFormat = function(value){
        var res = parseFloat(value).toFixed(2);
        res = res.replace('.',',');
        return res.replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1&nbsp;");
    };

    /**
    * Объект или массив в html
     * @param Object|Array obj
     * @returns {String}
     *              
     */
    objectToHtml = function(obj){
        var result = '<div>';
        $.each( obj, function( key, value ) {
            if (jQuery.isPlainObject(value) || jQuery.isArray(value)){
                result = result + '<div>' + key + '</div>';
                result = result + objectToHtml(value);
            } else {
                result = result + '<div><span>' + key + '</span>: <span>' + value + '</span></div>';
            }    
        });

        result = result + '</div>';
        return result;
    };
    
    
    /**
    * Печать
     */
    prnt = function (url) {
        var iframe = this._printIframe;
        if (!this._printIframe) {
            iframe = this._printIframe = document.createElement('iframe');
            document.body.appendChild(iframe);

            iframe.style.display = 'none';
            iframe.onload = function() {
                setTimeout(function() {
                    iframe.focus();
                    iframe.contentWindow.print();
                }, 1);
            };
        }

        iframe.src = url;
    };

    /**
    * Пометка товара в документе

     * @param {type} row
     * 
     * */
    function takeStyle(row){
        var classes = 'default';
        if (row.take == '2'){
            classes = 'warning';
        }        
        return {classes: classes};
    }
    
</script>        
