<?php
    use Bank\Entity\Payment;

    $this->headTitle('Платежные поручения');

    $this->mainMenu()->setActiveItemId('company');
    $this->mainMenu()->setActiveUrl($this->url('payment'));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Предприятие'=>$this->url('company'),
                'Платежные поручения'=>$this->url('payment'),
                ]);


?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button class="btn btn-default payment-modal-show" type="button" modal-url="/payment/edit-form" title="Новая платежка">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
                <button class="btn btn-default suppliers-pay-modal-show" type="button" modal-url="/payment/suppliers-pay-form" title="Оплата поставщикам">
                    <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                </button>                
                <div class="form-group">
                    <div class="btn-group">
                        <input id="searchinput" name="search" style="width: 150px" class="form-control" type="text" placeholder="Поиск">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>
                    <button id="ok" type="submit" class="btn btn-default" title="Поиск">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>    
                <div class="form-group">
                    <input id="monthSelect" class="form-control" type="month" placeholder="Период" value="<?= date('Y-m');?>">
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/payment/content"
            data-cookie="true"
            data-cookie-id-table="paymentSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-sort-name="docDate"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="rowStyle"
            >
            <thead>
                <tr>
                     <th data-field="paymentDate" data-sortable="true" data-width="100">Дата</th>
                     <th data-field="id" data-sortable="false" data-type="numeric" data-align="right" data-width="50">Номер</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-formatter="amountFormatter">Сумма</th>
                     <th data-field='bankAccount.name' data-sortable="false">Банк</th>
                     <th data-field='counterpartyInn' data-sortable="false">Получатель ИНН</th>
                     <th data-field='counterpartyKpp' data-sortable="false">Получатель КПП</th>
                     <th data-field='counterpartyName' data-sortable="false">Получатель</th>
                     <th data-field='supplier.name' data-sortable="false">Поставщик</th>
                     <th data-field='purpose' data-sortable="false">назначение</th>
                     <th data-field='user.fullName' data-sortable="false">Автор</th>
                     <th data-field="" data-formatter="editFormatter" data-width="10"></th>
                     <th data-field="" data-formatter="sendFormatter" data-width="10"></th>
                     <th data-field="" data-formatter="removeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status === '<?= Payment::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        if (row.statusAccount === '<?= Payment::STATUS_ACTIVE?>'){
           retired += ' warning';
        }
        return {classes: retired};
    }

    var $table = $('#table'),
            $ok = $('#ok');
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }

    $(function () {
        $('select').change(function (){
            refreshTable();
        });
    });

    $(document).on('click', '.payment-modal-show', function (e) {
        var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'paymentModal',
                url: url,
                width: '1440px'
            });
    });  

    $(document).on('click', '.suppliers-pay-modal-show', function (e) {
        var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'suppliersPayModal',
                url: url,
                width: '1440px'
            });
    });  

    $(document).on('click', '.send-payment', function (e) {
        var dialog = bootbox.dialog({
            message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
            closeButton: false
        });
        var url = $(e.currentTarget).attr('modal-url');
        $.getJSON( url, function( data ) {
            refreshTable();
            dialog.modal('hide');
        });            
    });  
    
    $(document).on('click', '.status-payment', function (e) {
        var dialog = bootbox.dialog({
            message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
            closeButton: false
        });
        var url = $(e.currentTarget).attr('modal-url');
        $.getJSON( url, function( data ) {
            dialog.modal('hide');
            bootbox.dialog({
                message: (data.message) ? data.message:data.status,
                closeButton: true
            });
        });            
    });  

    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.month = $('#monthSelect').val();
        
        return params;
    }
        
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    
    
    function editFormatter(value, row){
        if (!row.requestId){
            var url = '/payment/edit-form/'+row.id;
            btn = '<button';
            btn += ' type="button"';
            btn += ' class="btn btn-default btn-xs payment-modal-show"';
            btn += ' aria-label="Left Align" title="Изменить"'; 
            btn += ' modal-url="'+url+'">';
            btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
            btn += '</button>';
            return btn;
        }    
    }    
    
    function sendFormatter(value, row){
        if (!row.requestId){
            var url = '/payment/send/'+row.id;
            btn = '<button';
            btn += ' type="button"';
            btn += ' class="btn btn-default btn-xs send-payment"';
            btn += ' aria-label="Left Align"'; 
            btn += ' modal-url="'+url+'" title="Отправить в банк">';
            btn += '<span class="glyphicon glyphicon-send" aria-hidden="true"></span>';
            btn += '</button>';
            return btn;
        } else {
            var url = '/payment/status/'+row.id;
            btn = '<button';
            btn += ' type="button"';
            btn += ' class="btn btn-default btn-xs status-payment"';
            btn += ' aria-label="Left Align"'; 
            btn += ' modal-url="'+url+'" title="Проверить статус платежа">';
            btn += '<span class="glyphicon glyphicon-check" aria-hidden="true"></span>';
            btn += '</button>';
            return btn;
        }    
    }    

    function removeFormatter(value, row){
        if (!row.requestId){
            var url = '/payment/delete/'+row.id;
            btn = ' <button';
            btn += ' type="button"';
            btn += ' class="btn btn-danger btn-xs this-delete"';
            btn += ' aria-label="Left Align"'; 
            btn += ' title="Удалить"'; 
            btn += ' onclick="tableRowDelete(\''+url+'\')">';
            btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
            btn += '</button>';
            return btn;
        }    
    }    

    function responseHandler(res) {
        return res;
    }    
</script>

