<?php
    use Bank\Entity\Payment;

    $this->headTitle('Платежные поручения');

    $this->mainMenu()->setActiveItemId('company');
    $this->mainMenu()->setActiveUrl($this->url('payment'));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Предприятие'=>$this->url('company'),
                'Платежные поручения'=>$this->url('payment'),
                ]);


?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button class="btn btn-default payment-modal-show" type="button" modal-url="/payment/edit-form" title="Новая платежка">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
                <button class="btn btn-default suppliers-pay-modal-show" type="button" modal-url="/payment/suppliers-pay-form" title="Оплата поставщикам">
                    <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                </button>                
<!--                <button class="btn btn-default payment-send-all" type="button" modal-url="/payment/send-all" title="Отправить все платежи">
                    <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
                </button>                -->
                <button class="btn btn-default payment-send-all" type="button" modal-url="/payment/send-all?version=2" title="Отправить все платежи">
                    <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
                </button>                
                <div class="form-group">
                    <div class="btn-group">
                        <input name="search" style="width: 150px" class="form-control enter-search" type="text" placeholder="Поиск">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>
                    <button id="ok" type="submit" class="btn btn-default" title="Поиск">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>    
                <div class="form-group">
                    <input name="month" class="form-control" type="month" placeholder="Период" value="<?= date('Y-m');?>">
                </div>
                <div class="form-group">
                    <select name="supplier" style="width: 200px" class="form-control">
                        <option selected>поставщик</option>
                        <?php foreach ($suppliers as $supplier):?>
                            <option value="<?= $supplier->getId()?>"><?= $supplier->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select name="status" style="width: 200px" class="form-control">
                        <option selected>статус</option>
                        <?php foreach (Payment::getStatusList() as $key => $value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select name="paymentType" style="width: 200px" class="form-control">
                        <option selected>тип платежа</option>
                        <?php foreach (Payment::getPaymentTypeList() as $key => $value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <input class="form-control status-total" style='width: 100px; direction: rtl' disabled value="0">
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/payment/content"
            data-cookie="true"
            data-cookie-id-table="paymentSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="rowStyle"
            >
            <thead>
                <tr>
                     <th data-field="paymentDate" data-sortable="true" data-width="100">Дата</th>
                     <th data-field="id" data-sortable="true" data-type="numeric" data-align="right" data-width="50">Номер</th>
                     <th data-field='amount' data-sortable="true" data-align="right" data-formatter="amountFormatter">Сумма</th>
                     <th data-field='bankAccount.bik' data-sortable="false" data-formatter="formatBank">Отправитель БИК/счет</th>
                     <th data-field='counterpartyBankBik' data-sortable="false" data-formatter="formatAccount">Получатель БИК/счет</th>
                     <th data-field='counterpartyName' data-sortable="false" data-formatter="formatCounterparty">Получатель</th>
                     <th data-field='purpose' data-sortable="false" data-formatter="purposeFormatter">Назначение</th>
                     <th data-field='user.fullName' data-sortable="false">Автор</th>
                     <th data-field="" data-formatter="editFormatter" data-width="10"></th>
                     <th data-field="" data-formatter="sendFormatter" data-width="10"></th>
                     <th data-field="" data-formatter="removeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status === '<?= Payment::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        if (row.status === '<?= Payment::STATUS_ERROR?>'){
           retired += ' warning';
        }
        if (row.status === '<?= Payment::STATUS_TRANSFER?>'){
           retired += ' info';
        }
        if (row.status === '<?= Payment::STATUS_SUCCESS?>'){
           retired += ' success';
        }
        return {classes: retired};
    }

    var $table = $('#table'),
            $ok = $('#ok');
    
    $table.bootstrapTable({
        onLoadSuccess: function(res){
            updateTotal();
        }            
    }); 
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }
    
    function updateTotal(){
        $.getJSON('/payment/status-total', function( data ) {
            $('.status-total').val(data['total']);
        });                    
    }    

    $(function () {
        $('input[name="month"]').change(function (){
            refreshTable();
        });
        $('select').change(function (){
            refreshTable();
        });
        $ok.click(function (){
            refreshTable();
        });
        $(".inputclear").click(function(){
            $('input[name="search"]').val('');
            refreshTable();
        });
    });

    $(document).on('click', '.payment-modal-show', function (e) {
        var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'paymentModal',
                url: url,
                width: '1440px'
            });
    });  

    $(document).on('click', '.suppliers-pay-modal-show', function (e) {
        var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'suppliersPayModal',
                url: url,
                width: '1440px'
            });
    });  

    $(document).on('click', '.send-payment', function (e) {
        var dialog = bootbox.dialog({
            message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
            closeButton: true
        });
        var url = $(e.currentTarget).attr('modal-url');
        $.getJSON( url, function( data ) {
            refreshTable();
            dialog.modal('hide');
        });            
    });  

    $(document).on('click', '.payment-send-all', function (e) {
        var dialog = bootbox.dialog({
            message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
            closeButton: true
        });
        var url = $(e.currentTarget).attr('modal-url');
        $.getJSON( url, function( data ) {
            refreshTable();
            dialog.modal('hide');
        });            
    });  
    
    $(document).on('click', '.status-payment', function (e) {
        var dialog = bootbox.dialog({
            message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
            closeButton: false
        });
        var url = $(e.currentTarget).attr('modal-url');
        $.ajax({
            url: url,
            dataType: 'json',
            success: function( data ) {
                var message = 'Ошибка создания платежа!';
                if (data.Data.status){
                    message = 'Платеж принят банком!';
                }
                if (data.message){
                    message += '<br/>'+data.message;
                }
                if (data.errors){
                    $.each(data.errors, function( index, value ) {
                        message += '<br/>'+value.message;                        
                    });                    
                }
                dialog.modal('hide');
                bootbox.dialog({
                    message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>'+message+'</p>',
                    closeButton: true
                });
                refreshTable();
            },
            error: function( data ) {
                dialog.modal('hide');
                bootbox.dialog({
                    message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Платеж не найден</p>',
                    closeButton: true
                });
            }
        });
    });  

    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
        
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    
    
    function formatBankAccount(value, row){
        var result = value;
        if (row.bankAccount.rs){
            result += '<br/>' + row.bankAccount.rs;
        }
        return result;
    }

    function formatAccount(value, row){
        var result = value;
        if (row.counterpartyAccountNumber){
            result += '<br/>' + row.counterpartyAccountNumber;
        }
        return result;
    }

    function formatCounterparty(value, row){
        var result = value;
        if (row.counterpartyInn){
            result += '<br/>' + row.counterpartyInn;
        }
        if (row.counterpartyKpp){
            result += '<br/>' + row.counterpartyKpp;
        }
        return result;
    }
    
    function purposeFormatter(value, row){
        if (row.statusMessage){
            return value + '<br/><div class="label label-danger">'+row.statusMessage+'</div>';
        }
        return value;
    }
    
    function editFormatter(value, row){
        var disabled = '';
        if (row.requestId){
            var url = '/payment/edit-form/'+row.id+'?copy=1';
            btn = '<button ' + disabled;
            btn += ' type="button"';
            btn += ' class="btn btn-default btn-xs payment-modal-show"';
            btn += ' aria-label="Left Align" title="Копировать"'; 
            btn += ' modal-url="'+url+'">';
            btn += '<span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span>';
            btn += '</button>';
            return btn;
        }
        var url = '/payment/edit-form/'+row.id;
        btn = '<button ' + disabled;
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs payment-modal-show"';
        btn += ' aria-label="Left Align" title="Изменить"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function sendFormatter(value, row){
        var disabled = '';
        if (row.status === '<?= Payment::STATUS_RETIRED?>'){
            disabled = 'disabled = "true"';
        }
        if (!row.requestId){
//            var url = '/payment/send/'+row.id;
//            btn = '<button ' + disabled;
//            btn += ' type="button"';
//            btn += ' class="btn btn-default btn-xs send-payment"';
//            btn += ' aria-label="Left Align"'; 
//            btn += ' modal-url="'+url+'" title="Отправить в банк">';
//            btn += '<span class="glyphicon glyphicon-send" aria-hidden="true"></span>';
//            btn += '</button>';
            //return btn;

            var url = '/payment/send/'+row.id+'?version=2';
            btn = ' <button ' + disabled;
            btn += ' type="button"';
            btn += ' class="btn btn-default btn-xs send-payment"';
            btn += ' aria-label="Left Align"'; 
            btn += ' modal-url="'+url+'" title="Отправить в банк">';
            btn += '<span class="glyphicon glyphicon-send" aria-hidden="true"></span>';
            btn += '</button>';
            
            return btn;
        } else {
//            var url = '/payment/status/'+row.id;
//            btn = '<button ' + disabled;
//            btn += ' type="button"';
//            btn += ' class="btn btn-default btn-xs status-payment"';
//            btn += ' aria-label="Left Align"'; 
//            btn += ' modal-url="'+url+'" title="Проверить статус платежа">';
//            btn += '<span class="glyphicon glyphicon-check" aria-hidden="true"></span>';
//            btn += '</button>';

            var url = '/payment/status/'+row.id+'?version=2';
            btn = ' <button ' + disabled;
            btn += ' type="button"';
            btn += ' class="btn btn-default btn-xs status-payment"';
            btn += ' aria-label="Left Align"'; 
            btn += ' modal-url="'+url+'" title="Проверить статус платежа">';
            btn += '<span class="glyphicon glyphicon-check" aria-hidden="true"></span>';
            btn += '</button>';

            return btn;
        }    
    }    

    function removeFormatter(value, row){
        var disabled = '';
        if (row.requestId){
            //disabled = 'disabled = "true"';
        }
        var url = '/payment/delete/'+row.id;
        btn = ' <button '+disabled;
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    

    function responseHandler(res) {
        return res;
    }    
</script>

