<?php if ($this->pageCount): ?>

<nav>
<ul class="pagination">

<?php
    $action = $id = $querystr = null; 
    if (array_key_exists('id', $this->route)){
        $id = $this->route['id'];
    }
    if (array_key_exists('action', $this->route)){
        $action = $this->route['action'];
    }
    
    
    if (array_key_exists('query', $this->route)){
        $routeQuery = $this->route['query'];
    } else {
        $routeQuery = [];
    }
    if (!array_key_exists('page', $routeQuery)){
        $routeQuery['page'] = 1;
    }    
?>    
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <?php $routeQuery['page'] = $this->previous;?>
    <li>
      <a href="<?= $this->url($this->route['route'], ['action' => $action, 'id' => $id], ['query'=> $routeQuery]); ?>" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>  
<?php else: ?>
    <li>
        <span aria-hidden="true">&laquo;</span>      
    </li>  
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <?php $routeQuery['page'] = $page;?>
  <?php if ($page != $this->current): ?>
    <li>
        <a href="<?= $this->url($this->route['route'], ['action' => $action, 'id' => $id], ['query'=>$routeQuery]); ?>"><?= $this->escapeHtml($page); ?></a>
    </li>    
  <?php else: ?>
    <li>
        <span aria-hidden="true"><b><?= $this->escapeHtml($page); ?></b></span> 
    </li>    
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
    <?php $routeQuery['page'] = $this->next;?>
    <li>
      <a href="<?= $this->url($this->route['route'], ['action' => $action, 'id' => $id], ['query'=> $routeQuery]); ?>" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>  
<?php else: ?>
    <li>
        <span aria-hidden="true">&raquo;</span>      
    </li> 
<?php endif; ?>
</ul>
</nav>
<?php endif; ?>
