<?php
use Application\Entity\GroupSite;

$this->headTitle('Категории товаров на сайте');

$this->mainMenu()->setActiveItemId('fasade');
$this->mainMenu()->setActiveUrl($this->url('group-site'));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Категории на сайте'=>$this->url('group-site')
            ]);

?>
<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button class="btn btn-default group-site-modal-show" type="button"
                        modal-url="/group-site/edit-form" title="Добавить группу верхнего уровня">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/group-site/content"
            data-cookie="true"
            data-cookie-id-table="groupSiteSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="false" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-query-params="queryParams"
            data-sort-name="code"
            data-sort-order="asc"  
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-tree-enable="true"
            data-id-field="id"
            data-parent-id-field="pid"
            data-tree-show-field = "name"
            data-tree-save-state = "true"
            data-tree-save-state-name = "groupSiteTreeGrid"
            data-show-columns="true"            
            >
            <thead>
                <tr>
                     <th data-field="code" data-sortable="true" data-width="100">Код</th>
                     <th data-field="name" data-sortable="false" data-formatter="nameFormatter">Наименование</th>             
                     <th data-field="sort" data-sortable="true" data-width="10">С</th>
                     <th data-field="level" data-sortable="true" data-width="10">У</th>
                     <th data-field="goodCount" data-sortable="true" data-width="10">Т</th>             
                     <th data-field="" data-formatter="activeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');
    
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }
    
    $(function () {
        $(document).on('click', '.group-site-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'groupSiteModal',
                url: url
                //width: '1440px'
            });
        });    
        
        $(document).on('click', '.del-group-site', function (e) {
            if (confirm('Удалить '+$(this).attr('del-name')+'?')){
                $.get( $(this).attr('del-url'), function(data){
                    $table.bootstrapTable('refresh', {silent: true});
                });        
            }    
        });
        
        $(document).on('post-body.bs.table', '#table', function (data) {
            var columns = $table.bootstrapTable('getOptions').columns;
            if (columns && columns[0][1].visible) {
                $table.treegrid({
                    treeColumn: 1,
                    onChange: function() {
                        $table.bootstrapTable('resetView');
                    }
                });
            };        
        });
    });    
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }

        
        return params;
    }
    
    function nameFormatter(value, row){
        var result = value;
        if (row.level === 0){
            result = '<strong>'+value+'</strong>';
        }    
        if (row.level === 2){
            result = '<em>'+value+'</em>';
        }    
        
        var url = '/group-site/edit-form?parent='+row.id;
        return [
            '<button type="button" class="btn btn-default btn-xs group-site-modal-show"',
            ' aria-label="Left Align" modal-url="'+url+'" title="Добавить подгруппу">',
            '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>',
            '</button>',
            ' ',
            result
        ].join(''); 
    }    
    
    function activeFormatter(value, row){
        var url = '/group-site/edit-form/'+row.id;
        btn = '<nobr><button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs group-site-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button> ';

        url = '/group-site/delete/'+row.id;
        var disabled = (row.goodCount !== 0) ? 'disabled="true"':''; 
        btn += '<button '+disabled;
        btn += ' type="button" title="Удалить '+row.name+'"';
        btn += ' class="btn btn-default btn-xs del-group-site"';
        btn += ' aria-label="Left Align"'; 
        btn += ' del-url="'+url+'" del-name="'+row.name+'">';
        btn += '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>';
        btn += '</button></nobr>';
        
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>
