<?php
$this->headTitle('Добавить поставщика');

$this->mainMenu()->setActiveItemId('supplier');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Поставщики'=>$this->url('supplier'),
            'Добавить поставщика'=>$this->url('supplier', ['action'=>'add'])
            ]);

$form = $this->form;
$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Наименование'
    ]);

$form->get('aplId')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Код АПЛ'
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Добавить нового поставщика</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('aplId')); ?>
            <?= $this->formElement($form->get('aplId')); ?>
            <?= $this->formElementErrors($form->get('aplId')); ?>                  
        </div>
                                                        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
                
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
