<?php

$form = $this->form;

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('emailPassword')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('appPassword')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('realSupplier')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'bill-getting-submit']);

$form->prepare();

?>


            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Настройка загрузки электронных накладных поставщика</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('name')); ?>
                            <?= $this->formElement($form->get('name')); ?>
                            <?= $this->formElementErrors($form->get('name')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('status')); ?>
                            <?= $this->formElement($form->get('status')); ?>
                            <?= $this->formElementErrors($form->get('status')); ?>                  
                        </div>                        

                        <div class="form-group">
                            <?= $this->formLabel($form->get('email')); ?>
                            <div class="input-group">
                                <?= $this->formElement($form->get('email')); ?>
                                <span class="input-group-btn">
                                    <a class="btn btn-default" type="button" title="Перейти на biz.mail.ru" href="https://biz.mail.ru/login/autopartslist.ru" target="_blank">
                                        <span class="glyphicon glyphicon-link"></span>
                                    </a>
                                </span>                                                            
                            </div>
                            <?= $this->formElementErrors($form->get('email')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('emailPassword')); ?>
                            <div class="input-group">
                                <?= $this->formElement($form->get('emailPassword')); ?>
                                <span class="input-group-btn">
                                    <button class="btn btn-default password-generator" type="button" data-toggle="tooltip" data-placement="top" title="Генератор пароля">
                                        <span class="glyphicon glyphicon-qrcode"></span>
                                    </button>
                                </span>                                                            
                            </div>
                            <?= $this->formElementErrors($form->get('emailPassword')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('appPassword')); ?>
                            <?= $this->formElement($form->get('appPassword')); ?>
                            <?= $this->formElementErrors($form->get('appPassword')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('realSupplier')); ?>
                            <?= $this->formElement($form->get('realSupplier')); ?>
                            <?= $this->formElementErrors($form->get('realSupplier')); ?>                  
                        </div>                        

                        <?= $this->formElement($form->get('csrf')); ?>
                    </div>        
                </div>
            </div>    
                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="bill-getting-submit">Сохранить</button>
            </div>
            
            <?= $this->form()->closeTag(); ?>
            
<script>
    $('#bill-getting-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/supplier/bill-getting-form/<?= $supplier->getId() ?>?billGetting=<?= ($billGetting ? $billGetting->getId():'') ?>',
            data: $('#bill-getting-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#bill-getting-modal').modal('hide');
                    window.location.reload();
                } else {
                    $('#bill-getting-modal-content').html(data);
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });
    });
    
    $('.password-generator').on('click', function() {
        $.ajax({
            type: 'GET',
            url: '/admin/password-generator/'
        })
            .done(function (data) {
                if (data){
                    $('input[name=emailPassword]').val(data['password']);
                }
            })
            .fail(function (e) {
                console.log(e);
            });    
    });    
    
</script>