<?php
$this->headTitle('Редактирование данных поставщика '.$supplier->getName());

$this->mainMenu()->setActiveItemId('supplier');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Управление поставщиками'=>$this->url('supplier'),
            'Редактирование данных поставщика'=>$this->url('supplier', ['action'=>'edit', 'id' => $supplier->getId()])
            ]);  

$form = $this->form;
$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Наименование'
    ]);

$form->get('address')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Адрес'
    ]);

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Наименование'
    ]);

$form->get('info')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Описание'
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Изменить поставщика</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('address')); ?>
            <?= $this->formElement($form->get('address')); ?>
            <?= $this->formElementErrors($form->get('address')); ?>                  
        </div>
                                
        <div class="form-group">
            <?= $this->formLabel($form->get('info')); ?>
            <?= $this->formElement($form->get('info')); ?>
            <?= $this->formElementErrors($form->get('info')); ?>                  
        </div>
                                
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
                
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
