<?php
$this->headTitle('Поставщики');

$this->mainMenu()->setActiveItemId('supplier');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Поставщики'=>$this->url('supplier'),
            ]);
?>

<p>
    <a class="btn btn-default" href="
        <?= $this->url('supplier', ['action'=>'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Новый поставщик
    </a>     
</p>

<div class="row">
    <div class="col-md-9">

        <table class="table table-striped">

           <tr>
                <th>ID</th>
                <th>Наименование</th>
                <th>Действие</th>
            </tr>

            <?php foreach ($supplier as $row): ?>

            <tr>
                <td><?= $this->escapeHtml($row->getId()); ?></td>
                <td>
                    <a href="<?= $this->url('supplier', ['action'=>'view', 'id'=>$row->getId()]); ?>">
                        <?= $this->escapeHtml($row->getName()); ?>
                    </a> 
                </td>
                <td>
                    <a class="btn btn-info" href="<?= $this->url('supplier', 
                            ['action'=>'edit', 'id'=>$row->getId()]); ?>">
                        <span class="glyphicon glyphicon-pencil" ></span> Изменить
                    </a>
                    <a class="btn btn-danger" href="<?= $this->url('supplier',
                            ['action'=>'delete', 'id'=>$row->getId()]); ?>">
                        <span class="glyphicon glyphicon-remove"></span> Удалить
                    </a>
                </td>    
            </tr>

            <?php endforeach; ?>   

        </table>
        <?= $this->paginationControl($supplier,
                    'Sliding',
                    'application/partial/paginator', 
                    ['route' => array('route' => 'supplier')]); ?>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Поставщики
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                        </div>
                    </div>
                </div>
            </div>                
        </div>
    </div>    
</div>

