<?php

$form = $this->form;

$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder' => 'Описание полей прайса '.$supplier->getName(),
    ]);

$form->get('article')->setAttributes([
    'class'=>'form-control', 
    'min' => 0,
    ]);

$form->get('iid')->setAttributes([
    'class'=>'form-control', 
    'min' => 0,
    ]);

$form->get('producer')->setAttributes([
    'class'=>'form-control', 
    'min' => 0,
    ]);

$form->get('title')->setAttributes([
    'class'=>'form-control', 
    'min' => 0,
    ]);

$form->get('price')->setAttributes([
    'class'=>'form-control', 
    'min' => 0,
    ]);

$form->get('rest')->setAttributes([
    'class'=>'form-control', 
    'min' => 0,
    ]);

$form->get('oem')->setAttributes([
    'class'=>'form-control', 
    'min' => 0,
    ]);

$form->get('vendor')->setAttributes([
    'class'=>'form-control', 
    'min' => 0,
    ]);

$form->get('lot')->setAttributes([
    'class'=>'form-control', 
    'min' => 0,
    ]);

$form->get('lot')->setAttributes([
    'class'=>'form-control', 
    'min' => 0,
    ]);

$form->get('unit')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('car')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('bar')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('currency')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('weight')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('country')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('type')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('markdown')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('sale')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('image')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'price-description-submit']);

$form->prepare();

?>
            
<?= $this->form()->openTag($form); ?>

            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Описание полей прайса</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('type')); ?>
                            <?= $this->formElement($form->get('type')); ?>
                            <?= $this->formElementErrors($form->get('type')); ?>                  
                        </div>
                    </div>
                </div>    
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('name')); ?>
                            <?= $this->formElement($form->get('name')); ?>
                            <?= $this->formElementErrors($form->get('name')); ?>                  
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('status')); ?>
                            <?= $this->formElement($form->get('status')); ?>
                            <?= $this->formElementErrors($form->get('status')); ?>                  
                        </div>
                    </div>
                </div>    

                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('article')); ?>
                            <?= $this->formElement($form->get('article')); ?>
                            <?= $this->formElementErrors($form->get('article')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('price')); ?>
                            <?= $this->formElement($form->get('price')); ?>
                            <?= $this->formElementErrors($form->get('price')); ?>                  
                        </div>                        
                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('oem')); ?>
                            <?= $this->formElement($form->get('oem')); ?>
                            <?= $this->formElementErrors($form->get('oem')); ?>                  
                        </div>                        
                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('car')); ?>
                            <?= $this->formElement($form->get('car')); ?>
                            <?= $this->formElementErrors($form->get('car')); ?>                  
                        </div>                        
                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('weight')); ?>
                            <?= $this->formElement($form->get('weight')); ?>
                            <?= $this->formElementErrors($form->get('weight')); ?>                  
                        </div>                        
                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('currency')); ?>
                            <?= $this->formElement($form->get('currency')); ?>
                            <?= $this->formElementErrors($form->get('currency')); ?>                  
                        </div>                        

                        <div class="form-group">
                            <?= $this->formLabel($form->get('markdown')); ?>
                            <?= $this->formElement($form->get('markdown')); ?>
                            <?= $this->formElementErrors($form->get('markdown')); ?>                  
                        </div>                        

                    </div>
                
                    <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('producer')); ?>
                            <?= $this->formElement($form->get('producer')); ?>
                            <?= $this->formElementErrors($form->get('producer')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('rest')); ?>
                            <?= $this->formElement($form->get('rest')); ?>
                            <?= $this->formElementErrors($form->get('rest')); ?>                  
                        </div>
                        
                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('vendor')); ?>
                            <?= $this->formElement($form->get('vendor')); ?>
                            <?= $this->formElementErrors($form->get('vendor')); ?>                  
                        </div>                        

                        <div class="form-group">
                            <?= $this->formLabel($form->get('comment')); ?>
                            <?= $this->formElement($form->get('comment')); ?>
                            <?= $this->formElementErrors($form->get('comment')); ?>                  
                        </div>                        

                        <div class="form-group">
                            <?= $this->formLabel($form->get('bar')); ?>
                            <?= $this->formElement($form->get('bar')); ?>
                            <?= $this->formElementErrors($form->get('bar')); ?>                  
                        </div>                        

                        <div class="form-group">
                            <?= $this->formLabel($form->get('image')); ?>
                            <?= $this->formElement($form->get('image')); ?>
                            <?= $this->formElementErrors($form->get('image')); ?>                  
                        </div>                        

                    </div>
                    
                    <div class="col-md-4">
                        
                        <div class="form-group">
                            <?= $this->formLabel($form->get('title')); ?>
                            <?= $this->formElement($form->get('title')); ?>
                            <?= $this->formElementErrors($form->get('title')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('iid')); ?>
                            <?= $this->formElement($form->get('iid')); ?>
                            <?= $this->formElementErrors($form->get('iid')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('lot')); ?>
                            <?= $this->formElement($form->get('lot')); ?>
                            <?= $this->formElementErrors($form->get('lot')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('unit')); ?>
                            <?= $this->formElement($form->get('unit')); ?>
                            <?= $this->formElementErrors($form->get('unit')); ?>                  
                        </div>                        

                        <div class="form-group">
                            <?= $this->formLabel($form->get('country')); ?>
                            <?= $this->formElement($form->get('country')); ?>
                            <?= $this->formElementErrors($form->get('country')); ?>                  
                        </div>                        

                        <div class="form-group">
                            <?= $this->formLabel($form->get('sale')); ?>
                            <?= $this->formElement($form->get('sale')); ?>
                            <?= $this->formElementErrors($form->get('sale')); ?>                  
                        </div>                        

                    </div>
                    
                </div>    
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary" id="price-description-submit">Сохранить</button>
                </div>

            </div>
`            

            <?= $this->form()->closeTag(); ?>
            
<script>
    $('#price-description-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/supplier/price-description-form/<?= $supplier->getId() ?>?priceDescription=<?= ($priceDescription ? $priceDescription->getId():'') ?>',
            data: $('#price-description-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#price-description-modal').modal('hide');
                    window.location.reload();
                } else {
                    $('#price-description-modal-content').html(data);
                }    
            })
            .fail(function () {
                bootbox.alert("Произошла ошибка при выполнении операции.");
            });
    })    
</script>