<?php
$this->headTitle($supplier->getName());

$this->mainMenu()->setActiveItemId('supplier');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Поставщики'=>$this->url('supplier'),
            $supplier->getName() => $this->url('supplier', ['action'=>'view', 'id' => $supplier->getId()])
            ]);  

$this->headScript()
            ->appendFile($this->basePath('js/jquery.mask.min.js'))
        ;

?>
<div class="row">
    <div class="col-sm-9">
        <div class="panel panel-default" id="section1">
            <div class="panel-heading">
                <h2><?= $supplier->getName() ?></h2>                
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <div class="pull-left">
                    ID: <?= $this->escapeHtml($supplier->getId()) ?>
                    AplId: <?= $this->escapeHtml($supplier->getAplId()) ?><br/>
                    Статус: <?= $this->escapeHtml($supplier->getStatusAsString()) ?>
                </div>
                <div class="pull-right">
                    <button value="/supplier/edit-form/<?= $supplier->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                        <span class="glyphicon glyphicon-edit" ></span>
                    </button>                                                    
                </div>
            </div>
        </div>

        <div class="panel panel-default" id="section2">
            <div class="panel-heading">
                <h3 class="panel-title pull-left">Как заказать?</h3>
                <div class="pull-right">
                    <button value="/supplier/request-setting-form/<?= $supplier->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Добавить">
                        <span class="glyphicon glyphicon-plus" ></span>
                    </button>                                                                        
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <?php if ($supplier->getRequestSettings()): ?>                    
                    <div class="panel-group">
                        <?php foreach ($supplier->getRequestSettings() as $requestSetting): ?>                
                            <div class="panel panel-info">
                                <div class="panel-body">
                                    <div class="pull-left">
                                        <?= $requestSetting->getName() ?><br/>
                                        Способ заказа: <span><?= $requestSetting->getModeAsString() ?></span><br/>
                                        <!--<span><?= $requestSetting->getStatusAsString() ?></span>-->
                                        <!--<br/>-->
                                        Сайт: <a href="<?= $requestSetting->getSiteNormalize()?>" target="block"><?= $requestSetting->getSite() ?></a>
                                        <br/>
                                        Логин: <?= $requestSetting->getLogin() ?><br/>
                                        Пароль: <?= $requestSetting->getPassword() ?><br/>
                                        <?= nl2br($requestSetting->getDescription()) ?>
                                    </div>        
                                    <div class="pull-right">                                
                                        <button value="/supplier/request-setting-form/<?= $supplier->getId() ?>?requestSetting=<?= $requestSetting->getId() ?>" class="btn btn-default btn-xs"
                                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                            <span class="glyphicon glyphicon-edit" ></span>
                                        </button>                                                    
                                        <button value="/supplier/delete-request-setting-form/<?= $requestSetting->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                title="Удалить">
                                            <span class="glyphicon glyphicon-remove" ></span>
                                        </button>                                                           
                                    </div>                                                                        
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <div class="panel panel-default" id="section3">
            <div class="panel-heading">
                <h3 class="panel-title pull-left">Контакты</h3>
                <div class="pull-right">
                    <button value="/supplier/manager-form/<?= $supplier->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Добавить">
                        <span class="glyphicon glyphicon-plus" ></span>
                    </button>                                                                        
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <?php if ($supplier->getOtherContacts()): ?>                    
                    <div class="panel-group">
                        <?php foreach ($supplier->getOtherContacts() as $manager):?>
                            <div class="panel panel-info">
                                <div class="panel-body">
                                    <div class="pull-left">
                                        <strong><?= $manager->getName() ?></strong>
                                        <div>
                                            <?= $manager->getDescription() ?>
                                            <!--<span><?= $manager->getStatusAsString() ?></span>-->
                                        </div>                                    
                                    </div>
                                    <div class="pull-right">                                
                                        <button value="/supplier/manager-form/<?= $supplier->getId() ?>?manager=<?= $manager->getId() ?>" class="btn btn-default btn-xs"
                                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                            <span class="glyphicon glyphicon-edit" ></span>
                                        </button>                                                    
                                        <button value="/supplier/delete-manager-form/<?= $manager->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                title="Удалить">
                                            <span class="glyphicon glyphicon-remove" ></span>
                                        </button>                                                           
                                    </div>                                                                        
                                </div>
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <div class="pull-left">
                                            <div class="panel-title">Контактные телефоны</div>
                                        </div>
                                        <div class="pull-right">
                                            <button value="/contact/phone-form/<?= $manager->getId() ?>" class="btn btn-default btn-xs"
                                                    data-toggle="modal" data-target="#modal-dialog" title="Добавить телефон">
                                                <span class="glyphicon glyphicon-plus" ></span>
                                            </button>                                        
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="panel-body">
                                        <div class="panel panel-group">
                                            <?php foreach ($manager->getPhones() as $phone): ?>
                                                <div class="panel panel-default">
                                                    <div class="panel-body">
                                                        <div class="pull-left">
                                                            <?= $phone->getName()?> <span><?= $phone->getComment()?></span>
                                                        </div>
                                                        <div class="pull-right">
                                                            <button value="/contact/phone-form/<?= $manager->getId() ?>?phone=<?= ($phone ? $phone->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                                                    data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                                                <span class="glyphicon glyphicon-edit" ></span>
                                                            </button>                                                            
                                                            <button value="/contact/delete-phone-form/<?= $phone->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                                    title="Удалить">
                                                                <span class="glyphicon glyphicon-remove" ></span>
                                                            </button>                                                            
                                                        </div>
                                                    </div>
                                                </div>    
                                            <?php endforeach; ?>
                                        </div>                    
                                    </div>
                                </div>    
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <div class="pull-left">
                                        <div class="panel-title">Электронная почта</div>
                                    </div>
                                    <div class="pull-right">
                                        <button value="/contact/email-form/<?= $manager->getId() ?>" class="btn btn-default btn-xs"
                                                data-toggle="modal" data-target="#modal-dialog" title="Добавить email">
                                            <span class="glyphicon glyphicon-plus" ></span>
                                        </button>                                        
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="panel-body">
                                    <div class="panel panel-group">
                                        <?php foreach ($manager->getEmails() as $email): ?>
                                            <div class="panel panel-default">
                                                <div class="panel-body">
                                                    <div class="pull-left">
                                                        <?= $email->getName()?>
                                                    </div>
                                                    <div class="pull-right">
                                                        <button value="/contact/email-form/<?= $manager->getId() ?>?email=<?= ($email ? $email->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                                            <span class="glyphicon glyphicon-edit" ></span>
                                                        </button>                                                            
                                                        <button value="/contact/delete-email-form/<?= $email->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                                title="Удалить">
                                                            <span class="glyphicon glyphicon-remove" ></span>
                                                        </button>                                                            
                                                    </div>
                                                </div>
                                            </div>    
                                        <?php endforeach; ?>
                                    </div>                    
                                </div>
                            </div>  
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <div class="pull-left">
                                        <div class="panel-title">Мессенджеры</div>
                                    </div>
                                    <div class="pull-right">
                                        <button value="/contact/messenger-form/<?= $manager->getId() ?>" class="btn btn-default btn-xs"
                                                data-toggle="modal" data-target="#modal-dialog" title="Добавить мессенджер">
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </button>                                            
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <div class="panel panel-group">
                                        <?php foreach ($manager->getMessengers() as $messenger): ?>
                                            <div class="panel panel-default">
                                                <div class="panel-body">
                                                    <div class="pull-left">
                                                        <?= $this->escapeHtml($messenger->getTypesAsString()); ?>: <?= $this->escapeHtml($messenger->getIdent()); ?>
                                                    </div>
                                                    <div class="pull-right">
                                                        <button value="/contact/messenger-form/<?= $messenger->getContact()->getId() ?>?messenger=<?= $messenger->getId() ?>" class="btn btn-default btn-xs"
                                                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                                            <span class="glyphicon glyphicon-edit" ></span>
                                                        </button>                                                            
                                                        <button value="/contact/delete-messenger-form/<?= $messenger->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                                title="Удалить">
                                                            <span class="glyphicon glyphicon-remove" ></span>
                                                        </button>                                                            
                                                    </div>
                                                </div>

                                            </div>
                                        <?php endforeach; ?>
                                    </div>                    
                                </div>
                            </div>                        
                        <?php endforeach; ?>            
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <div class="panel panel-default" id="section4">
            <?php echo $this->partial('/company/legal/partial-view', ['legalContact' => $legalContact]); ?>
        </div>    
    </div>
    <div class="col-sm-3" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active"><a href="#section1">Офис</a></li>
            <li><a href="#section2">Контактные телефоны</a></li>
            <li><a href="#section3">Электронная почта</a></li>
            <li><a href="#section4">Мессенджеры</a></li>
            <li><a href="#section5">Адреса</a></li>
            <li><a href="#section6">Юридические лица</a></li>
        </ul>
    </div>    
</div>    

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title pull-left">Получение прайса</h3>
                <button supplier-id="<?= $supplier->getId() ?>" class="btn btn-default pull-right" 
                        data-toggle="modal" data-target="#price-getting-modal" title="Добавить">
                    <span class="glyphicon glyphicon-plus" ></span>
                </button>
                <div class="clearfix"></div>
            </div>            
            <table class="table table-striped table-bordered">
                <?php if ($supplier->getPriceGettings()): ?>
                    <?php foreach ($supplier->getPriceGettings() as $priceGetting): ?>
                        <tr>
                            <td>
                                <?= $priceGetting->getName() ?>
                            </td>
                            <td align="right">
                                <button supplier-id="<?= $supplier->getId() ?>" value="<?= $priceGetting->getId() ?>" class="btn btn-default" 
                                        data-toggle="modal" data-target="#price-getting-modal" data-toggle="tooltip" title="Изменить">
                                    <span class="glyphicon glyphicon-pencil" ></span>
                                </button>
                                <a class="btn btn-danger" data-toggle="confirmation" data-title="Удалить?" title="Удалить" href="<?= $this->url('supplier',
                                        ['action'=>'delete-price-getting', 'id' => $priceGetting->getId()]); ?>">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </a>                           
                            </td>
                        </tr>
                        <tr>     
                            <th>Статус</th>
                            <td class=""><?= $priceGetting->getStatusAsString() ?></td>
                       </tr>
                        <tr>     
                            <th>Email</th>
                            <td class=""><?= $priceGetting->getEmail() ?></td>
                       </tr>
                        <tr>     
                            <th>Email пароль</th>
                            <td class=""><?= $priceGetting->getEmailPassword() ?></td>
                       </tr>
                        <tr>     
                            <th>Ftp</th>
                            <td class=""><?= $priceGetting->getFtp() ?></td>
                       </tr>
                        <tr>     
                            <th>Ftp логин</th>
                            <td class=""><?= $priceGetting->getFtpLogin() ?></td>
                       </tr>
                        <tr>     
                            <th>Ftp пароль</th>
                            <td class=""><?= $priceGetting->getFtpPassword() ?></td>
                       </tr>
                        <tr>     
                            <th>Ссылка на скачивание</th>
                            <td class=""><?= $priceGetting->getLink() ?></td>
                       </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </table>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title pull-left">Подвоз</h3>
                <button supplier-id="<?= $supplier->getId() ?>" class="btn btn-default pull-right" 
                        data-toggle="modal" data-target="#supply-setting-modal" title="Добавить">
                    <span class="glyphicon glyphicon-plus" ></span>
                </button>
                <div class="clearfix"></div>
            </div>            
            <table class="table table-striped table-bordered">
                <?php if ($supplier->getSupplySettings()): ?>                    
                    <?php foreach ($supplier->getSupplySettings() as $supplySetting): ?>
                        <tr>
                            <td colspan="2">
                                <div class="pull-left">
                                    <?= $supplySetting->getSupplyTimeSpan()?>
                                    <span><?= $supplySetting->getOffice()->getName() ?></span>
                                    Заказать до: <span><?= $supplySetting->getOrderBeforeHi()?></span>
                                    Подвоз часов: <span><?= $supplySetting->getSupplyTime()?></span>
                                    Подвоз в субботу <span><?= $supplySetting->getSupplySatAsString() ?></span>
                                    Статус: <span><?= $supplySetting->getStatusAsString() ?></span>
                                </div>        
                                <div class="pull-right">                                
                                    <button supplier-id="<?= $supplier->getId() ?>" value="<?= $supplySetting->getId() ?>" class="btn btn-default"
                                            data-toggle="modal" data-target="#supply-setting-modal" title="Изменить">
                                        <span class="glyphicon glyphicon-pencil" ></span>
                                    </button>                            
                                    <a class="btn btn-default" data-toggle="confirmation" data-title="Удалить?" title="Удалить" href="<?= $this->url('supplier',
                                            ['action'=>'delete-supply-setting', 'id' => $supplySetting->getId()]); ?>">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </a>
                                </div>    
                            </td>
                        </tr>
                        
                    <?php endforeach; ?>
                <?php endif; ?>
            </table>
        </div>
    </div>    

</div>
<div class="row">
        
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title pull-left">Получение электронных накладных</h3>
                <button supplier-id="<?= $supplier->getId() ?>" class="btn btn-default pull-right" 
                        data-toggle="modal" data-target="#bill-getting-modal" title="Добавить">
                    <span class="glyphicon glyphicon-plus" ></span>
                </button>
                <div class="clearfix"></div>
            </div>            
            <table class="table table-striped table-bordered">
                <?php if ($supplier->getBillGettings()): ?>                    
                    <?php foreach ($supplier->getBillGettings() as $billGetting): ?>
                        <tr>
                            <th class=""><?= $billGetting->getName() ?></th>
                            <td align="right">
                                <button supplier-id="<?= $supplier->getId() ?>" value="<?= $billGetting->getId() ?>" class="btn btn-default"
                                        data-toggle="modal" data-target="#bill-getting-modal" title="Изменить">
                                    <span class="glyphicon glyphicon-pencil" ></span>
                                </button>                            
                                <a class="btn btn-default" data-toggle="confirmation" data-title="Удалить?" title="Удалить" href="<?= $this->url('supplier',
                                        ['action'=>'delete-bill-getting', 'id' => $billGetting->getId()]); ?>">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </a>                           
                            </td>
                        </tr>
                        <tr>     
                            <th>Статус</th>
                            <td class=""><?= $billGetting->getStatusAsString() ?></td>
                       </tr>
                        <tr>     
                            <th>Email</th>
                            <td class=""><?= $billGetting->getEmail() ?></td>
                       </tr>
                        <tr>     
                            <th>Email пароль</th>
                            <td class=""><?= $billGetting->getEmailPassword() ?></td>
                       </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </table>
        </div>
    </div>    
                
                
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title pull-left">Прайсы</h3>
                <button supplier-id="<?= $supplier->getId() ?>" class="btn btn-default btn-xs pull-right" 
                        data-toggle="modal" data-target="#upload-price-modal" title="Загрузить">
                    <span class="glyphicon glyphicon-upload" ></span>
                </button>
                <div class="clearfix"></div>
            </div>            
            <table class="table table-striped table-bordered">
                <?php if ($supplier->getRaw()): ?>                    
                    <?php foreach ($supplier->getRaw() as $raw): ?>
                        <tr>
                            <th class=""><?= $raw->getBasename() ?></th>
                            <td align="right">
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </table>
        </div>
    </div>    
    
</div>


<div class="modal fade" id="modal-dialog" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal-content">
        </div>
    </div>
</div>

<script>
    $('#modal-dialog').on('show.bs.modal', function (e) {        
        var url = e.relatedTarget.value;
        if (url){
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                   $('#modal-content').html(data);
                })
                .fail(function () {
                    alert("Ошибка открытия формы.");
                }); 
        }
    })    
        
    $('.this-delete').on('click', function(e) {
        var url = e.currentTarget.value;
        if (url){
            if (confirm('Удалить запись?')){
                $.ajax({
                    type: 'GET',
                    url: url,
                })
                    .done(function (data) {
                        if (data == 'ok'){
                            window.location.reload();
                        } else {
                            alert("Не удалось удалить!");
                        }    
                    })
                    .fail(function (e) {
                        alert("Не удалось удалить.");

                    });
            }        
        }        
    })    
    
</script>