<?php
$this->headTitle('Просмотр данных поставщика '.$supplier->getName());

$this->mainMenu()->setActiveItemId('supplier');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Поставщики'=>$this->url('supplier'),
            'Просмотр данных поставщика'=>$this->url('supplier', ['action'=>'view', 'id' => $supplier->getId()])
            ]);  

?>

<h1>
    <?= $this->escapeHtml($supplier->getName()); ?> 
    <sup>
        Id: <?= $this->escapeHtml($supplier->getId()); ?>             
    </sup>
    <sup>
        <?php if ($supplier->getAplId()): ?>
            Код АПЛ: <?= $this->escapeHtml($supplier->getAplId()); ?>             
        <?php endif;?>
    </sup>
</h1>
<p>    
    <?= $this->escapeHtml($supplier->getStatusAsString()); ?>
</p>


<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="contact-header">Контактные лица
                </h4>
            </div>    
            <div class="panel-body">
                <?php foreach ($supplier->getContacts() as $contact):?>
                <?php endforeach; ?>            
            </div>        
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="contact-header">Юридические лица
                </h4>
            </div>    
            <div class="panel-body">
                <?php foreach ($supplier->getContacts() as $contact):?>
                        <a class="btn btn-default" href="<?= $this->url('legals', 
                                            ['action'=>'legal', 'id'=>$contact->getId()]); ?>">
                                        <span class="glyphicon glyphicon-pencil" ></span> <?= (count($contact->getLegals())) ? 'Изменить':'Добавить'; ?>
                        </a>
                    <table class="table table-striped table-bordered">
                        <?php foreach ($contact->getLegals() as $legal): ?>
                            <tr>
                               <th class=""><?= $legal->getName() ?></th>
                               <th class=""><?= $legal->getInn() ?></th>
                               <th class=""><?= $legal->getStatusAsString() ?></th>
                           </tr>
                        <?php endforeach; ?>
                    </table>
                <?php endforeach; ?>            
            </div>        
        </div>
    </div>
    <div class="col-md-4">

        <h4 class="contact-header">Настройки загрузки прайса</h4>
        <p>
        <a class="btn btn-default" href="
            <?= $this->url('pricesettings', ['action'=>'add'], ['query' => ['supplier' => $supplier->getId()]]); ?>">
            Добавить
        </a>
        </p>
        <table class="table table-striped">

           <tr>
                <th>ID</th>
                <th>Наименование</th>
                <th>Действие</th>
            </tr>

            <?php foreach ($supplier->getPricesettings() as $row): ?>

            <tr>
                <td><?= $this->escapeHtml($row->getId()); ?></td>
                <td>
                        <?= $this->escapeHtml($row->getName()); ?>
                </td>
                <td>
                    <a class="btn btn-info" href="<?= $this->url('pricesettings', 
                            ['action'=>'edit', 'id'=>$row->getId()]); ?>">
                        <span class="glyphicon glyphicon-pencil" ></span> Изменить
                    </a>
                    <a class="btn btn-danger" href="<?= $this->url('pricesettings',
                            ['action'=>'delete', 'id'=>$row->getId()]); ?>">
                        <span class="glyphicon glyphicon-remove"></span> Удалить
                    </a>
                </td>    
            </tr>

            <?php endforeach; ?>   

        </table>
    </div>
</div>   
 <div class="row">
   
            <div class="col-md-4">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Получение прайса</th>
                        <td align="right">
                            <button type="button" supplier-id="<?= $supplier->getId() ?>" class="btn btn-primary" data-toggle="modal" data-target="#price-getting-modal">
                                Добавить
                            </button>                                
                        </td>
                    </tr>    
                    
                    <?php foreach ($supplier->getPriceGettings() as $priceGetting): ?>
                        <tr>
                            <td colspan="2" align="right">
                                <button type="button" supplier-id="<?= $supplier->getId() ?>" value="<?= $priceGetting->getId() ?>" class="btn btn-primary" data-toggle="modal" data-target="#price-getting-modal">
                                    Изменить
                                </button>                            
                                <a class="btn btn-danger" href="<?= $this->url('supplier',
                                        ['action'=>'delete-price-getting', 'id' => $priceGetting->getId()]); ?>">
                                    <span class="glyphicon glyphicon-remove"></span> Удалить
                                </a>                           
                            </td>
                        </tr>
                        <tr>     
                            <td>Наименование</td>
                            <th class=""><?= $priceGetting->getName() ?></th>
                       </tr>
                        <tr>     
                            <td>Статус</td>
                            <th class=""><?= $priceGetting->getStatusAsString() ?></th>
                       </tr>
                        <tr>     
                            <td>Email</td>
                            <th class=""><?= $priceGetting->getEmail() ?></th>
                       </tr>
                        <tr>     
                            <td>Email пароль</td>
                            <th class=""><?= $priceGetting->getEmailPassword() ?></th>
                       </tr>
                        <tr>     
                            <td>Ftp</td>
                            <th class=""><?= $priceGetting->getFtp() ?></th>
                       </tr>
                        <tr>     
                            <td>Ftp логин</td>
                            <th class=""><?= $priceGetting->getFtpLogin() ?></th>
                       </tr>
                        <tr>     
                            <td>Ftp пароль</td>
                            <th class=""><?= $priceGetting->getFtpPassword() ?></th>
                       </tr>
                        <tr>     
                            <td>Ссылка на скачивание</td>
                            <th class=""><?= $priceGetting->getLink() ?></th>
                       </tr>
                    <?php endforeach; ?>
                </table>
            </div>    
    
            <div class="col-md-4">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Получение электронных накладных</th>
                        <td align="right">
                            <button type="button" supplier-id="<?= $supplier->getId() ?>" class="btn btn-primary" data-toggle="modal" data-target="#bill-getting-modal">
                                Добавить
                            </button>                                
                        </td>
                    </tr>    
                    
                    <?php foreach ($supplier->getBillGettings() as $billGetting): ?>
                        <tr>
                            <td colspan="2" align="right">
                                <button type="button" supplier-id="<?= $supplier->getId() ?>" value="<?= $billGetting->getId() ?>" class="btn btn-primary" data-toggle="modal" data-target="#bill-getting-modal">
                                    Изменить
                                </button>                            
                                <a class="btn btn-danger" href="<?= $this->url('supplier',
                                        ['action'=>'delete-bill-getting', 'id' => $billGetting->getId()]); ?>">
                                    <span class="glyphicon glyphicon-remove"></span> Удалить
                                </a>                           
                            </td>
                        </tr>
                        <tr>     
                            <td>Наименование</td>
                            <th class=""><?= $billGetting->getName() ?></th>
                       </tr>
                        <tr>     
                            <td>Статус</td>
                            <th class=""><?= $billGetting->getStatusAsString() ?></th>
                       </tr>
                        <tr>     
                            <td>Email</td>
                            <th class=""><?= $billGetting->getEmail() ?></th>
                       </tr>
                        <tr>     
                            <td>Email пароль</td>
                            <th class=""><?= $billGetting->getEmailPassword() ?></th>
                       </tr>
                    <?php endforeach; ?>
                </table>
            </div>    
</div>


<div class="modal fade" id="price-getting-modal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="price-getting-modal-content">
        </div>
    </div>
</div>

<div class="modal fade" id="bill-getting-modal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="bill-getting-modal-content">
        </div>
    </div>
</div>

<script>
    $('#price-getting-modal').on('show.bs.modal', function (e) {        
        var url = '/supplier/price-getting-form/';
        var supplier_id = $(e.relatedTarget).attr('supplier-id');
        if (supplier_id){
            url += supplier_id;
            
            var priceGetting = e.relatedTarget.value;
            if (priceGetting){
                url += '?priceGetting=' + priceGetting;
            }    
            
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                   $('#price-getting-modal-content').html(data);
                })
                .fail(function () {
                    alert("Ошибка открытия формы.");
                });    
            }
        })
        
    $('#bill-getting-modal').on('show.bs.modal', function (e) {        
        var url = '/supplier/bill-getting-form/';
        var supplier_id = $(e.relatedTarget).attr('supplier-id');
        if (supplier_id){
            url += supplier_id;
            
            var billGetting = e.relatedTarget.value;
            if (billGetting){
                url += '?billGetting=' + billGetting;
            }    
            
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                   $('#bill-getting-modal-content').html(data);
                })
                .fail(function () {
                    alert("Ошибка открытия формы.");
                });    
            }
        })
</script>

