<?php
$this->headTitle('Операторы ЭДО');

$this->mainMenu()->setActiveItemId('company');
$this->mainMenu()->setActiveUrl('legals', ['action' => 'edo-operators']);

?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button value="/legals/edo-operator-form" class="btn btn-default"
                        data-toggle="modal" data-target="#modal-dialog" title="Добавить">
                    <span class="glyphicon glyphicon-plus" ></span>
                </button>                                                                        
                <div class="form-group">
                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/legals/edo-operator-content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-sortable="true" data-width='10'>ID</th>
                     <th data-field="name" data-sortable="true">Наименование</th>           
                     <th data-field="inn" data-sortable="true">ИНН</th>           
                     <th data-field="code" data-sortable="true" data-width='20'>Код</th>
                     <th data-field="site" data-sortable="false">Сайт</th>           
                     <th data-field="id2" data-formatter="activeFormatter" data-width='5'></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var $table = $('#table'),
        $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }
        return params;
    }
        
    function linkFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/make/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    

    function activeFormatter(value, row){
        var url = '/legals/edo-operator-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs" data-toggle="modal" data-target="#modal-dialog"';
        btn += ' aria-label="Left Align"'; 
        btn += ' value="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
        
    function responseHandler(res) {
        return res;
    }    
</script>
