<?php

$form = $this->legalForm;

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('inn')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('kpp')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('ogrn')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('okpo')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('ogrn')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('head')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('chiefAccount')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('address')->setAttributes([
    'class'=>'form-control', 
    'style' => 'height: 182px',
    ]);

$form->get('info')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('dateStart')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить']);

$form->prepare();

?>


            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Организация</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('inn')); ?>
                            <div class="input-group">
                                <?= $this->formElement($form->get('inn')); ?>
                                <span class="input-group-btn">
                                    <button class="btn btn-default" id="inn-info" type="button" data-toggle="tooltip" data-placement="top" title="Найти и заполнить по ИНН">ИНН</button>
                                </span>                                                            
                            </div>    
                            <?= $this->formElementErrors($form->get('inn')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('name')); ?>
                            <?= $this->formElement($form->get('name')); ?>
                            <?= $this->formElementErrors($form->get('name')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('kpp')); ?>
                            <?= $this->formElement($form->get('kpp')); ?>
                            <?= $this->formElementErrors($form->get('kpp')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('ogrn')); ?>
                            <?= $this->formElement($form->get('ogrn')); ?>
                            <?= $this->formElementErrors($form->get('ogrn')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('okpo')); ?>
                            <?= $this->formElement($form->get('okpo')); ?>
                            <?= $this->formElementErrors($form->get('okpo')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('dateStart')); ?>
                            <?= $this->formElement($form->get('dateStart')); ?>
                            <?= $this->formElementErrors($form->get('dateStart')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('status')); ?>
                            <?= $this->formElement($form->get('status')); ?>
                            <?= $this->formElementErrors($form->get('status')); ?>                  
                        </div>
                    </div>                

                    <div class="col-md-6">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('address')); ?>
                            <?= $this->formElement($form->get('address')); ?>
                            <?= $this->formElementErrors($form->get('address')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('head')); ?>
                            <?= $this->formElement($form->get('head')); ?>
                            <?= $this->formElementErrors($form->get('head')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('chiefAccount')); ?>
                            <?= $this->formElement($form->get('chiefAccount')); ?>
                            <?= $this->formElementErrors($form->get('chiefAccount')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('info')); ?>
                            <?= $this->formElement($form->get('info')); ?>
                            <?= $this->formElementErrors($form->get('info')); ?>                  
                        </div>

                        <?= $this->formElement($form->get('csrf')); ?>

                    </div>
                </div>
            </div>    
                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="legal-submit">Сохранить</button>
            </div>
            
            <?= $this->form()->closeTag(); ?>
            
<script>
    var _dadata;
    
    function setDadata(data){
        _dadata = data;
    }
    function getDadata(){
        return _dadata;
    }
    
    var _inn = $('#inn').val();
    
    $('#legal-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/legals/form/<?= $contact->getId() ?>',
            data: $('#legal-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#legal-modal').modal('hide');
                    window.location.reload();
                } else {
                    $('#modal-dialog .modal-content').html(data);
                }    
            })
            .fail(function () {
                alert("Posting failed.");

            });
    })
    
    function fillFromData(index){
        var data = getDadata();
        if (data){
            var row = data[index];
            $('#inn').val(row.data.inn);
            $('#name').val(row.data.name.short_with_opf);
            $('#kpp').val(row.data.kpp);
            $('#ogrn').val(row.data.ogrn);
            $('#okpo').val(row.data.okpo);
            $('#address').val(row.data.address.unrestricted_value);
            if (row.data.management){
                $('#head').val(row.data.management.name);
            } else {
                $('#head').val('');
            }
        }    
        $('.bootbox.modal').modal('hide');
    }
    
    $('#inn-info').on('click', function() {        
        var inn = $('#inn').val();
        if (inn){
            $.ajax({
                type: 'GET',
                url: '/legals/inn-info/?inn='+inn,
            })
                .done(function (data) {
//                    console.log(data);
                    setDadata(data);
                    var message = '<table class="table table-striped">';
                    for (var i in data){
                        row = data[i];
                        message += '<tr>';
                        message += '<td>'+row.data.inn+'<br/>'+row.data.kpp+'</td>';
                        message += ' <td>'+row.data.name.short_with_opf+'</td>';
                        message += ' <td>'+row.data.address.unrestricted_value+'</td>';
                        message += ' <td><button onclick="fillFromData('+i+')">Выбрать</button></td>';
                        message += '</tr>';
                    }
                    message += '</table>';
                    bootbox.dialog({
                        title: "Выберете организацию",
                        message: message,
                        size: 'large',
                        buttons: {
                            cancel: {
                                label: 'Закрыть',
                                className: 'btn-default'
                            }
                        },                            
                    });
                })
                .fail(function (error) {
                    console.log(error);
                });
            }        
    })
    
</script>