<?php
$this->headTitle($parent['pageTitle']. ' - юридические лица');

$this->mainMenu()->setActiveItemId('');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            $parent['headTitle']=>$this->url($parent['route']),
            $parent['pageTitle']=>$this->url($parent['route'], ['action'=>'view', 'id'=>$parent['id']]),
            'Юридические лица' => $this->url('contact', ['action'=>'legal', 'id'=>$contact->getId()]),
            ]);

?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h2>Юридические лица</h2>
<p>
    <button type="button" value="/legals/form/<?= $contact->getId() ?>" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#modal-dialog">
      Добавить новое
    </button>    
</p>

<div class="row">
    <?php if (count($contact->getLegals())): ?>
        <div class="col-sm-9">
            <?php foreach ($contact->getLegals() as $legal): ?>    
                <div id="section<?= $legal->getId(); ?>">
                </div>
                <table class="table table-striped">
                    <tr>     
                        <th class=""><h3><?= $legal->getName() ?></h3></th>
                        <td align="right">
                        </td>
                   </tr>
                    <tr>     
                        <td colspan="2">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <div class="pull-left">
                                        ИНН/КПП: <?= $legal->getInn() ?>/<?= $legal->getKpp() ?><br/>
                                        ОГРН: <?= $legal->getOgrn() ?><br/>
                                        ОКПО: <?= $legal->getOkpo() ?><br/>
                                        Местонахождение: <?= $legal->getAddress() ?><br/>
                                        Руководитель: <?= $legal->getHead() ?><br/>
                                        Главный бухгалтер: <?= $legal->getChiefAccount() ?><br/>
                                        Дата начала деятельности: <?= date('d.m.Y', strtotime($legal->getDateStart())); ?><br/>
                                        Статус: <?= $legal->getStatusAsString() ?><br/>
                                        Дополнительная информация: <?= $legal->getInfo() ?><br/>                            
                                    </div>
                                    <div class="pull-right">
                                        <button value="/legals/form/<?= $contact->getId() ?>?legal=<?= $legal->getId() ?>" class="btn btn-default btn-xs"
                                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                            <span class="glyphicon glyphicon-edit" ></span>
                                        </button>                    
                                        <button value="/legals/delete-association-form/<?= $legal->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                title="Удалить">
                                            <span class="glyphicon glyphicon-remove" ></span>
                                        </button>                                                           
                                    </div>
                                </div>    
                            </div>
                        </td>
                   </tr>
                   <tr>
                       <th>
                           Банковские счета
                       </th>
                       <td align="right">
                            <button value="/legals/bank-account-form/<?= $legal->getId() ?>" class="btn btn-default btn-xs"
                                    data-toggle="modal" data-target="#modal-dialog" title="Добавить новый">
                                <span class="glyphicon glyphicon-plus" ></span>
                            </button>                    
                       </td>
                   </tr>
                   <tr>
                       <td colspan="2">
                            <?php foreach ($legal->getBankAccounts() as $bankAccount): ?>
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <div class="pull-left">
                                             Банк: <?= $bankAccount->getName().' '.$bankAccount->getCity() ?><br/>
                                             БИК: <?= $bankAccount->getBik()?><br/>
                                             Расчетный счет: <?= $bankAccount->getRs()?><br/>
                                             Корр. счет: <?= $bankAccount->getKs()?><br/>
                                             Статус: <?= $bankAccount->getStatusAsString()?><br/>                               
                                        </div>
                                         <div class="pull-right">
                                             <button value="/legals/bank-account-form/<?= $legal->getId() ?>?bankAccount=<?= $bankAccount->getId() ?>" class="btn btn-default btn-xs"
                                                     data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                                 <span class="glyphicon glyphicon-edit" ></span>
                                             </button>                    
                                            <button value="/legals/delete-bank-account-form/<?= $bankAccount->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                    title="Удалить">
                                                <span class="glyphicon glyphicon-remove" ></span>
                                            </button>                                                           
                                         </div>
                                    </div>    
                                 </div>
                            <?php endforeach; ?>
                        </td>
                   </tr>
                   <tr>
                       <th>
                           Договоры
                       </th>
                       <td align="right">
                            <button value="/legals/contract-form/<?= $legal->getId() ?>" class="btn btn-default btn-xs"
                                    data-toggle="modal" data-target="#modal-dialog" title="Добавить новый">
                                <span class="glyphicon glyphicon-plus" ></span>
                            </button>                    
                       </td>
                   </tr>
                   <tr>
                       <td colspan="2">
                            <?php foreach ($legal->getContracts() as $contract): ?>
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <div class="pull-left">
                                            Наименование: <?= $contract->getName() ?><br/>  
                                            № <?= $contract->getAct() ?> от <?= date('d.m.Y', strtotime($contract->getDateStart())) ?>
                                        </div>
                                        <div class="pull-right">
                                            <button value="/legals/contract-form/<?= $legal->getId() ?>?contract=<?= $contract->getId() ?>" class="btn btn-default btn-xs"
                                                    data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                                <span class="glyphicon glyphicon-edit" ></span>
                                            </button>                    
                                            <button value="/legals/delete-contract-form/<?= $contract->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                    title="Удалить">
                                                <span class="glyphicon glyphicon-remove" ></span>
                                            </button>                                                           
                                        </div>
                                   </div>     
                                </div>
                            <?php endforeach; ?>                           
                       </td>
                   </tr>
                </table>                
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if (count($contact->getLegals())): ?>
        <div class="col-sm-3" id="side-nav" >
            <ul class="nav nav-stacked nav-list affix">
                <?php foreach ($contact->getLegals() as $legal): ?>
                    <li class="active"><a href="#section<?= $legal->getId()?>"><?= $legal->getName()?>"</a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif;?>        
</div>    


<div class="modal fade" id="modal-dialog" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal-content">
        </div>
    </div>
</div>

<script>
    $('#modal-dialog').on('show.bs.modal', function (e) {        
        var url = e.relatedTarget.value;
        if (url){
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                   $('#modal-content').html(data);
                })
                .fail(function () {
                    alert("Ошибка открытия формы.");
                }); 
        }
    })    
        
    $('.this-delete').on('click', function(e) {
        var url = e.currentTarget.value;
        if (url){
            if (confirm('Удалить запись?')){
                $.ajax({
                    type: 'GET',
                    url: url,
                })
                    .done(function (data) {
                        if (data == 'ok'){
                            window.location.reload();
                        } else {
                            alert("Не удалось удалить!");
                        }    
                    })
                    .fail(function (e) {
                        alert("Не удалось удалить.");

                    });
            }        
        }        
    })        
</script>
    