<?php
$this->headTitle($parent['headTitle']);

$this->mainMenu()->setActiveItemId('');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            $parent['headTitle']=>$this->url($parent['route']),
            $parent['pageTitle']=>$this->url($parent['route'], ['action'=>'view', 'id'=>$parent['id']]),
            'Юридические лица' => $this->url('contact', ['action'=>'legal', 'id'=>$contact->getId()]),
            ]);

$form = $this->legalForm;

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('inn')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('kpp')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('ogrn')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('okpo')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('ogrn')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('head')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('chiefAccount')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('address')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('info')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('dateStart')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить']);

$form->prepare();

?>

<?= $this->headScript()
    ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js')
        ;
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h2>Юридические лица</h2>
<p>
    <button type="button" id="legal-dialog-new" class="btn btn-primary" data-toggle="modal" data-target="#legal-modal">
      Добавить
    </button>    
</p>

<?php if (count($contact->getLegals())): ?>
    <?php foreach ($contact->getLegals() as $legal): ?>
        <div class="row">
            <div class="col-md-6">
                <table class="table table-striped table-bordered">
                    <tr>
                        <td colspan="2" align="right">
                            <button type="button" id="legal-dialog-edit" value="<?= $legal->getId() ?>" class="btn btn-primary" data-toggle="modal" data-target="#legal-modal">
                              Изменить
                            </button>                            
                            <a class="btn btn-danger" href="<?= $this->url('legals',
                                    ['action'=>'delete-association', 'id' => $contact->getId()], ['query' => ['legal' => $legal->getId()]]); ?>">
                                <span class="glyphicon glyphicon-remove"></span> Удалить
                            </a>                           
                        </td>
                    </tr>
                    <tr>     
                        <td>Наименование</td>
                        <th class=""><?= $legal->getName() ?></th>
                   </tr>
                    <tr>     
                        <td>ИНН</td>
                        <th class=""><?= $legal->getInn() ?></th>
                   </tr>
                    <tr>     
                        <td>КПП</td>
                        <th class=""><?= $legal->getKpp() ?></th>
                   </tr>
                    <tr>     
                        <td>ОГРН</td>
                        <th class=""><?= $legal->getOgrn() ?></th>
                   </tr>
                    <tr>     
                        <td>ОКПО</td>
                        <th class=""><?= $legal->getOkpo() ?></th>
                   </tr>
                    <tr>     
                        <td>Местонахождение</td>
                        <th class=""><?= $legal->getAddress() ?></th>
                   </tr>
                    <tr>     
                        <td>Руководитель</td>
                        <th class=""><?= $legal->getHead() ?></th>
                   </tr>
                    <tr>     
                        <td>Главный бухгалтер</td>
                        <th class=""><?= $legal->getChiefAccount() ?></th>
                   </tr>
                    <tr>     
                        <td>Дата начала деятельности</td>
                        <th class=""><?= date('d.m.Y', strtotime($legal->getDateStart())); ?></th>
                   </tr>
                    <tr>     
                        <td>Статус</td>
                        <th class=""><?= $legal->getStatusAsString() ?></th>
                   </tr>
                    <tr>     
                        <td>Дополнительная информация</td>
                        <th class=""><?= $legal->getInfo() ?></th>
                   </tr>
                </table>
            </div>
        
            <div class="col-md-4">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Банковские счета</th>
                        <td align="right">
                            <button type="button" value="<?= $legal->getId() ?>" class="btn btn-primary" data-toggle="modal" data-target="#bank-account-modal">
                                Добавить
                            </button>                                
                        </td>
                    </tr>    
                    
                    <?php foreach ($legal->getBankAccounts() as $bankAccount): ?>
                        <tr>
                            <td colspan="2" align="right">
                                <button type="button" value="<?= $bankAccount->getId() ?>" class="btn btn-primary" data-toggle="modal" data-target="#bank-account-modal">
                                    Изменить
                                </button>                            
                                <a class="btn btn-danger" href="<?= $this->url('legals',
                                        ['action'=>'delete-bank-account', 'id' => $bankAccount->getId()]); ?>">
                                    <span class="glyphicon glyphicon-remove"></span> Удалить
                                </a>                           
                            </td>
                        </tr>
                        <tr>     
                            <td>Наименование</td>
                            <th class=""><?= $bankAccount->getName().' '.$bankAccount->getCity() ?></th>
                       </tr>
                        <tr>     
                            <td>БИК</td>
                            <th class=""><?= $bankAccount->getBik() ?></th>
                       </tr>
                        <tr>     
                            <td>Расчетный счет</td>
                            <th class=""><?= $bankAccount->getRs() ?></th>
                       </tr>
                        <tr>     
                            <td>Корр. счет</td>
                            <th class=""><?= $bankAccount->getKs() ?></th>
                       </tr>
                    <?php endforeach; ?>
                </table>
            </div>    
        <?php endforeach; ?>
    <?php endif;?>        
</div>

<div class="modal fade" id="legal-modal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="legal-modal-content">
        </div>
    </div>
</div>

<div class="modal fade" id="add-bank-account-modal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="add-bank-account-modal-content">
        </div>
    </div>
</div>

<div class="modal fade" id="edit-bank-account-modal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="edit-bank-account-modal-content">
        </div>
    </div>
</div>

<script>
    $('#legal-modal').on('show.bs.modal', function (e) {        
        var url = '/legals/form/<?= $contact->getId() ?>';
        var legal_id = e.relatedTarget.value;
        if (legal_id){
            url += '?legal='+legal_id;
        }
        $.ajax({
            type: 'GET',
            url: url
        })
            .done(function (data) {
               $('#legal-modal-content').html(data);
            })
            .fail(function () {
                alert("Ошибка открытия формы.");
            });    
    })    
    
    $('#add-bank-account-modal').on('show.bs.modal', function (e) {        
        var url = '/legals/add-bank-account-form/';
        var legal_id = e.relatedTarget.value;
        if (legal_id){
            url += legal_id;
            
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                   $('#add-bank-account-modal-content').html(data);
                })
                .fail(function () {
                    alert("Ошибка открытия формы.");
                });    
            }
        })    
</script>
    