<?php

$form = $this->form;

$form->get('address')->setAttributes([
    'class'=>'form-control', 
    'style' => 'height: 182px',
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('dateStart')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить']);

$form->prepare();

?>
            
<?= $this->form()->openTag($form); ?>
            
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Местонахождение <?= $legal->getName()?></h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
            
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <?= $this->formLabel($form->get('address')); ?>
                <?= $this->formElement($form->get('address')); ?>
                <?= $this->formElementErrors($form->get('address')); ?>                  
            </div>
            
            <?= $this->formElement($form->get('csrf')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('dateStart')); ?>
                <?= $this->formElement($form->get('dateStart')); ?>
                <?= $this->formElementErrors($form->get('dateStart')); ?>                  
            </div>
        </div>    
        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>                  
            </div>
        </div>                
    </div>
</div>    
                
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="button" class="btn btn-primary" id="location-submit">Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script>
    
    $('#location-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/legals/location-form/<?= $legal->getId() ?>?location=<?= ($location) ? $location->getId():'' ?>',
            data: $('#location-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
                    window.location.reload();
                } else {
                    $('#modal-dialog .modal-content').html(data);
                }    
            })
            .fail(function () {
                alert("Posting failed.");

            });
    });
        
</script>