<?php
    use Company\Entity\BankAccount;
    use Company\Entity\Contract;
    use Company\Entity\Legal;
?>

<div class="panel-heading">
    <div class="pull-left">
        <div class="panel-title"><a class="anchor" id="sectionLegal">Юридические лица</a></div>
    </div>
    <div class="pull-right">
        <button value="/legals/form/<?= $this->legalContact->getId() ?>" class="btn btn-default btn-xs"
                data-toggle="modal" data-target="#modal-dialog" title="Добавить юридическое лицо">
            <span class="glyphicon glyphicon-plus"></span>
        </button>                                            
    </div>
    <div class="clearfix"></div>
</div>
<div class="panel-body">
    <div class="panel panel-group">
        <?php foreach ($this->legalContact->getOrderLegals() as $legal): ?>
        <div class="panel panel-group">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="pull-left <?= ($legal->getStatus() == Legal::STATUS_RETIRED) ? 'retired':''?>">
                        <b><?= $legal->getName() ?></b><br/>
                        ИНН/КПП: <?= $legal->getInnKpp()?> <?= $legal->getOgrnPresent() ?> <?= $legal->getOkpoPresent() ?><br/>
                        Местонахождение: <?= $legal->getAddress() ?><br/>
                        Руководитель: <?= $legal->getHead() ?> <?= $legal->getChiefAccountPresent() ?><br/>
                        Дата начала деятельности: <?= date('d.m.Y', strtotime($legal->getDateStart())); ?><br/>
                        <?= $legal->getInfo() ?>                           
                    </div>
                    <div class="pull-right">
                        <button value="/legals/form/<?= $legalContact->getId() ?>?legal=<?= $legal->getId() ?>" class="btn btn-default btn-xs"
                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                            <span class="glyphicon glyphicon-edit" ></span>
                        </button>                    
                        <button value="/legals/delete-association-form/<?= $legal->getId() ?>?contact=<?= $this->legalContact->getId()?>" class="btn btn-default btn-xs this-delete"
                                title="Удалить">
                            <span class="glyphicon glyphicon-remove" ></span>
                        </button>                                                           
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="pull-left">
                        <i>Банковские счета <?= $legal->getName() ?></i>
                    </div>                                
                    <div class="pull-right">
                        <button value="/legals/bank-account-form/<?= $legal->getId() ?>" class="btn btn-default btn-xs"
                                data-toggle="modal" data-target="#modal-dialog" title="Добавить новый">
                            <span class="glyphicon glyphicon-plus" ></span>
                        </button>                                                        
                    </div>                                
                </div>
                <table class="table table-hover table-condensed">
                    <tr>
                        <th>Банк</th>
                        <th>БИК</th>
                        <th>Счет</th>
                        <th>Корр. счет</th>
                        <th>Дата</th>
                        <?php if ($legal->isOfficeLegal()):?>
                            <th>Api</th>
                            <th>Касса</th>
                        <?php endif;?>   
                        <th colspan="2"></th>
                    </tr>
                    <?php foreach ($legal->getOrderBankAccounts() as $bankAccount): ?>
                        <tr class="<?= ($bankAccount->getStatus() == BankAccount::STATUS_RETIRED) ? 'retired':''?>">
                           <td>
                               <?= $bankAccount->getNameWithCity() ?>
                           </td>
                           <td>
                               <?= $bankAccount->getBik()?>
                           </td>
                           <td>
                               <?= $bankAccount->getRs()?> <?= $bankAccount->getAccountTypeAsString()?>
                                <?php if ($legal->isOfficeLegal() && $bankAccount->getStatement() == $bankAccount::STATEMENT_ACTIVE):?>
                                   <a href="/bank/statement?account=<?= $this->escapeHtml($bankAccount->getRs());?>"
                                       title="Выписка по счету" target="_blank">
                                       <span class="glyphicon glyphicon-rub" ></span>
                                   </a>
                                <?php endif;?>   
                           </td>
                           <td>
                               <?= $bankAccount->getKs()?>
                           </td>
                           <td>
                               <?= date('d.m.Y', strtotime($bankAccount->getDateStart()))?>
                           </td>
                            <?php if ($legal->isOfficeLegal()):?>
                                <td><?= $bankAccount->getApiAsString()?></td>
                                <td><?= ($bankAccount->getCash()) ? $bankAccount->getCash()->getName():''?></td>
                            <?php endif;?>
                            <td width='2'>
                                <button value="/legals/bank-account-form/<?= $legal->getId() ?>?bankAccount=<?= $bankAccount->getId() ?>" class="btn btn-default btn-xs"
                                        data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                    <span class="glyphicon glyphicon-edit" ></span>
                                </button>                    
                            </td>
                            <td width='2'>
                                <button value="/legals/delete-bank-account-form/<?= $bankAccount->getId() ?>" class="btn btn-default btn-xs this-delete"
                                        title="Удалить">
                                    <span class="glyphicon glyphicon-remove" ></span>
                                </button>                                                           
                            </td>    
                       </tr>
                    <?php endforeach; ?>
                </table>
            </div>
            <?php if (!$this->notContract):?>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="pull-left">
                            <i>Договоры</i>
                        </div>                                
                        <div class="pull-right">
                            <button value="/legals/contract-form/<?= $legal->getId() ?>" class="btn btn-default btn-xs"
                                    data-toggle="modal" data-target="#modal-dialog" title="Добавить новый">
                                <span class="glyphicon glyphicon-plus" ></span>
                            </button>                    
                        </div>                                
                    </div>
                    <table class="table table-hover table-condensed">
                        <tr>
                            <th>Офис</th>
                            <th>Компания</th>
                            <th>№,дата</th>
                            <th>Наименование</th>
                            <th>Тип</th>
                            <th>Оплата</th>
                            <th>НДС</th>
                            <th colspan="3"></th>
                        </tr>
                        <?php foreach ($legal->getOrderContracts() as $contract): ?>
                        <tr class="<?= ($contract->getStatus() == Contract::STATUS_RETIRED) ? 'retired':''?>">
                                <td>
                                    <?= $contract->getOffice()->getName() ?>
                                </td>
                                <td>
                                    <?= $contract->getCompany()->getName() ?>
                                </td>
                                <td>
                                    <?= $contract->getAct() ?> от <?= date('d.m.Y', strtotime($contract->getDateStart())) ?>
                                </td>
                                <td>
                                    <?= $contract->getName() ?>
                                </td>
                                <td>
                                    <?= $contract->getKindAsString() ?>
                                </td>
                                <td>
                                    <?= $contract->getPayAsString() ?>
                                </td>
                                <td>
                                    <?= $contract->getNdsPercentAsString() ?>
                                </td>
                                <td width="2">
                                   <button value="/legals/contract-form/<?= $legal->getId() ?>?contract=<?= $contract->getId() ?>" class="btn btn-default btn-xs"
                                           data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                       <span class="glyphicon glyphicon-edit" ></span>
                                   </button>                                                        
                                </td>
                                <td width="2">
                                   <button value="/legals/delete-contract-form/<?= $contract->getId() ?>" class="btn btn-default btn-xs this-delete"
                                           title="Удалить">
                                       <span class="glyphicon glyphicon-remove" ></span>
                                   </button>                                     
                                </td>
                                <td width="2">
                                    <?php if ($this->supplier):?>
                                       <button value="/apl/update-supplier-legal/<?= $this->supplier->getId()?>?contract=<?= $contract->getId()?>" class="btn btn-info btn-xs refresh-button"
                                               title="Обновить юр.лицо в Апл">
                                           <span class="glyphicon glyphicon-export" ></span>
                                       </button>
                                    <?php endif;?> 
                                </td>    
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>                    
</div>
