<div class="panel-heading">
    <div class="pull-left">
        <div class="panel-title">Юридические лица</div>
    </div>
    <div class="pull-right">
        <button value="/legals/form/<?= $this->legalContact->getId() ?>" class="btn btn-default btn-xs"
                data-toggle="modal" data-target="#modal-dialog" title="Добавить юридическое лицо">
            <span class="glyphicon glyphicon-plus"></span>
        </button>                                            
    </div>
    <div class="clearfix"></div>
</div>
<div class="panel-body">
    <div class="panel panel-group">
        <?php foreach ($this->legalContact->getLegals() as $legal): ?>
        <div class="panel panel-group">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="pull-left">
                        <?= $legal->getName() ?><br/>
                        ИНН/КПП: <?= $legal->getInn() ?>/<?= $legal->getKpp() ?><br/>
                        ОГРН: <?= $legal->getOgrn() ?><br/>
                        ОКПО: <?= $legal->getOkpo() ?><br/>
                        Местонахождение: <?= $legal->getAddress() ?><br/>
                        Руководитель: <?= $legal->getHead() ?><br/>
                        Главный бухгалтер: <?= $legal->getChiefAccount() ?><br/>
                        Дата начала деятельности: <?= date('d.m.Y', strtotime($legal->getDateStart())); ?><br/>
                        Статус: <?= $legal->getStatusAsString() ?><br/>
                        Дополнительная информация: <?= $legal->getInfo() ?><br/>                            
                    </div>
                    <div class="pull-right">
                        <button value="/legals/form/<?= $legalContact->getId() ?>?legal=<?= $legal->getId() ?>" class="btn btn-default btn-xs"
                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                            <span class="glyphicon glyphicon-edit" ></span>
                        </button>                    
                        <button value="/legals/delete-association-form/<?= $legal->getId() ?>" class="btn btn-default btn-xs this-delete"
                                title="Удалить">
                            <span class="glyphicon glyphicon-remove" ></span>
                        </button>                                                           
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="pull-left">
                        Банковские счета <?= $legal->getName() ?>
                    </div>                                
                    <div class="pull-right">
                        <button value="/legals/bank-account-form/<?= $legal->getId() ?>" class="btn btn-default btn-xs"
                                data-toggle="modal" data-target="#modal-dialog" title="Добавить новый">
                            <span class="glyphicon glyphicon-plus" ></span>
                        </button>                                                        
                    </div>                                
                </div>
                 <?php foreach ($legal->getBankAccounts() as $bankAccount): ?>
                    <div class="panel-body">
                        <div class="pull-left">
                             Банк: <?= $bankAccount->getName().' '.$bankAccount->getCity() ?><br/>
                             БИК: <?= $bankAccount->getBik()?><br/>
                             Расчетный счет: <?= $bankAccount->getRs()?>
                             <?php if ($legal->isOfficeLegal() && $bankAccount->getStatement() == $bankAccount::STATEMENT_ACTIVE):?>
                                <a href="/bank/statement?account=<?= $this->escapeHtml($bankAccount->getRs());?>"
                                    title="Выписка по счету" target="_blank">
                                    <span class="glyphicon glyphicon-rub" ></span>
                                </a>
                             <?php endif;?>   
                             <br/>
                             Корр. счет: <?= $bankAccount->getKs()?><br/>
                             <?php if ($legal->isOfficeLegal()):?>
                                Api: <?= $bankAccount->getApiAsString()?><br/>
                             <?php endif;?>   
                             Статус: <?= $bankAccount->getStatusAsString()?><br/>                               
                        </div>
                         <div class="pull-right">
                             <button value="/legals/bank-account-form/<?= $legal->getId() ?>?bankAccount=<?= $bankAccount->getId() ?>" class="btn btn-default btn-xs"
                                     data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                 <span class="glyphicon glyphicon-edit" ></span>
                             </button>                    
                            <button value="/legals/delete-bank-account-form/<?= $bankAccount->getId() ?>" class="btn btn-default btn-xs this-delete"
                                    title="Удалить">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>                                                           
                         </div>
                    </div>    
                 <?php endforeach; ?>
            </div>
            <?php if (!$this->notContract):?>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="pull-left">
                            Договоры
                        </div>                                
                        <div class="pull-right">
                            <button value="/legals/contract-form/<?= $legal->getId() ?>" class="btn btn-default btn-xs"
                                    data-toggle="modal" data-target="#modal-dialog" title="Добавить новый">
                                <span class="glyphicon glyphicon-plus" ></span>
                            </button>                    
                        </div>                                
                    </div>
                     <?php foreach ($legal->getContracts() as $contract): ?>
                        <div class="panel-body">
                            <div class="pull-left">
                                Наименование: <?= $contract->getName() ?><br/>  
                                № <?= $contract->getAct() ?> от <?= date('d.m.Y', strtotime($contract->getDateStart())) ?>
                            </div>
                             <div class="pull-right">
                                <button value="/legals/contract-form/<?= $legal->getId() ?>?contract=<?= $contract->getId() ?>" class="btn btn-default btn-xs"
                                        data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                    <span class="glyphicon glyphicon-edit" ></span>
                                </button>                    
                                <button value="/legals/delete-contract-form/<?= $contract->getId() ?>" class="btn btn-default btn-xs this-delete"
                                        title="Удалить">
                                    <span class="glyphicon glyphicon-remove" ></span>
                                </button>                                                           
                             </div>
                        </div>    
                     <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>                    
</div>
