<script>
   //формы склада
   
    $(function () {
        $('#ok').click(function () {
            refreshTable();
        });
        
        $(".inputclear").click(function(){
            $(".enter-search").val('');
            refreshTable();
        });

        $(document).on('click', '.ot-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'otModal',
                url: url,
                width: '1440px'
            });
        });  

        $(document).on('click', '.ot-good-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            var uniqueId = $(this).attr('unique-id');
            if (uniqueId){
                var row = $('#otgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'otGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('click', '.ot-combined-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'otCombinedModal',
                url: url
//                width: '1440px'
            });
        });  
        
        $(document).on('click', '.pt-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'ptModal',
                url: url,
                width: '1440px'
            });
        });  
        
        $(document).on('click', '.pt-combined-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'ptCombinedModal',
                url: url,
                zIndex: 9999
//                width: '1440px'
            });
        });  
        
        $(document).on('click', '.pt-good-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            var uniqueId = $(this).attr('unique-id');
            if (uniqueId){
                var row = $('#ptgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'ptGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('click', '.ptu-modal-show', function (e) {
            var supplier = $('#supplierSelect').val();
            var url = $(this).attr('modal-url')+'?supplier='+supplier;
            showFormDialog({
                id: 'ptuModal',
                url: url,
                width: '1440px'
            });
        });  
        
        $(document).on('click', '.ptu-good-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            var uniqueId = $(this).attr('unique-id');
            if (uniqueId){
                var row = $('#ptugoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'ptuGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('click', '.vtp-index-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'vtpIndexModal',
                url: url,
                width: '1440px'
            });
        });  
        
        $(document).on('click', '.vtp-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'vtpModal',
                url: url,
                width: '1440px',
                zIndex: 9990
            });
        });  

        $(document).on('click', '.vtp-combined-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'vtpCombinedModal',
                url: url,
                width: '1440px'
            });
        });  

        $(document).on('click', '.vtp-good-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            var uniqueId = $(this).attr('unique-id');
            if (uniqueId){
                var row = $('#vtpgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'vtpGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('click', '.st-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'stModal',
                url: url,
                width: '1440px'
            });
        });  

        $(document).on('click', '.st-good-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            var uniqueId = $(this).attr('unique-id');
            if (uniqueId){
                var row = $('#stgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'stGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('click', '.st-combined-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'stCombinedModal',
                url: url
//                width: '1440px'
            });
        });  

        $(document).on('click', '.vt-index-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'vtIndexModal',
                url: url,
                width: '1440px'
            });
        });  

        $(document).on('click', '.vt-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'vtModal',
                url: url,
                width: '1440px',
                zIndex: 9990
            });
        });  

        $(document).on('click', '.vt-good-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            var uniqueId = $(this).attr('unique-id');
            if (uniqueId){
                var row = $('#vtgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'vtGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        var orderViewModal = new ModalApp.ModalProcess({
            id: 'orderViewModal'
        });
        orderViewModal.init();
                    
        $(document).on('click', '.order-view-show', function (e) {  
            e.preventDefault();
            var url = $(this).attr('modal-url');
            dialogModalShow(orderViewModal, {
                url: url,
                width: '1440px',
                zIndex: 5555
            });
        });  

        $(document).on('click', '.cash-in-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            var urlQuery = '?cash='+$('#cashSelect').val();
            showFormDialog({
                id: 'cashInModal',
                url: url+urlQuery,
                width: '1440px'
            });
        });  
        
        $(document).on('click', '.cash-out-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            var urlQuery = '?cash='+$('#cashSelect').val();
            showFormDialog({
                id: 'cashOutModal',
                url: url+urlQuery,
                width: '1440px'
            });
        });  
        
        $(document).on('click', '.user-in-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            var urlQuery = '?user='+$('#userSelect').val();
            showFormDialog({
                id: 'userInModal',
                url: url+urlQuery,
                width: '1440px'
            });
        });  
        
        $(document).on('click', '.user-out-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            var urlQuery = '?user='+$('#userSelect').val();
            showFormDialog({
                id: 'userOutModal',
                url: url+urlQuery,
                width: '1440px'
            });
        });  

        $(document).on('click', '.producer-union-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'producerUnionModal',
                url: url,
    //            width: '500px'
            });
        });  

        $(document).on('change', '#supplierSelect', function (e) {
            refreshTable();
        });        
        $(document).on('change', '#officeSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#monthSelect', function (e) {
            refreshTable();
        });
    });

</script>
