<script>
   //формы склада
   
    $(function () {
        $ok.click(function () {
            refreshTable();
        });
        
        $(".inputclear").click(function(){
            $("#searchinput").val('');
            refreshTable();
        });

        $(document).on('click', '.ot-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'otModal',
                url: url,
                width: '1440px'
            });
        });  

        $(document).on('click', '.ot-good-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            var uniqueId = $(e.currentTarget).attr('unique-id');
            if (uniqueId){
                var row = $('#otgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'otGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('click', '.pt-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'ptModal',
                url: url,
                width: '1440px'
            });
        });  
        
        $(document).on('click', '.pt-combined-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'ptCombinedModal',
                url: url,
                width: '1440px'
            });
        });  
        
        $(document).on('click', '.pt-good-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            var uniqueId = $(e.currentTarget).attr('unique-id');
            if (uniqueId){
                var row = $('#ptgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'ptGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('click', '.ptu-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'ptuModal',
                url: url,
                width: '1440px'
            });
        });  
        
        $(document).on('click', '.ptu-good-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            var uniqueId = $(e.currentTarget).attr('unique-id');
            if (uniqueId){
                var row = $('#ptugoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'ptuGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('click', '.vtp-index-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'vtpIndexModal',
                url: url,
                width: '1440px'
            });
        });  
        
        $(document).on('click', '.vtp-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'vtpModal',
                url: url,
                width: '1440px',
                zIndex: 9990
            });
        });  

        $(document).on('click', '.vtp-good-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            var uniqueId = $(e.currentTarget).attr('unique-id');
            if (uniqueId){
                var row = $('#vtpgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'vtpGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('click', '.st-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'stModal',
                url: url,
                width: '1440px'
            });
        });  

        $(document).on('click', '.st-good-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            var uniqueId = $(e.currentTarget).attr('unique-id');
            if (uniqueId){
                var row = $('#stgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'stGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('click', '.vt-index-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'vtIndexModal',
                url: url,
                width: '1440px'
            });
        });  

        $(document).on('click', '.vt-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'vtModal',
                url: url,
                width: '1440px',
                zIndex: 9990
            });
        });  

        $(document).on('click', '.vt-good-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            var uniqueId = $(e.currentTarget).attr('unique-id');
            if (uniqueId){
                var row = $('#vtgoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'vtGoodModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('change', '#supplierSelect', function (e) {
            refreshTable();
        });        
        $(document).on('change', '#officeSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#monthSelect', function (e) {
            refreshTable();
        });
    });

</script>
