<?php
    use Stock\Entity\Revise;
    
    $this->headTitle('Сверка долгов');    

    $this->mainMenu()->setActiveItemId('raw');
    if ($kind == Revise::KIND_REVISE_CLIENT){
        $this->mainMenu()->setActiveItemId('client');
    }

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Сверка долгов'=>$this->url('revision'),
                ]);
?>


<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button class="btn btn-default revise-modal-show" type="button" modal-url="/revise/edit-form?kind=<?= $kind?>">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
                <?php if ($kind == Revise::KIND_REVISE_CLIENT):?>
                    <div class="form-group">
                        <input name="search" style="width: 150px" class="form-control" type="text" placeholder="Поиск">
                        <button id="ok" type="submit" class="btn btn-default">OK</button>
                    </div>
                <?php endif; ?>                
                <?php if ($kind == Revise::KIND_REVISE_SUPPLIER):?>
                    <div class="form-group">
                        <select id="supplierSelect" style="width: 250px" class="form-control">
                            <option selected>поставщик</option>
                            <?php foreach ($suppliers as $supplier):?>
                                <option value="<?= $supplier->getId()?>"><?= $supplier->getName()?></option>
                            <?php endforeach;?>
                        </select>

                    </div>    
                <?php endif; ?>
                <div class="form-group">
                    <select id="officeSelect" style="width: 100px" class="form-control">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <input id="monthSelect" class="form-control" type="month" placeholder="Период" value="<?= date('Y-m');?>">
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/revise/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="docDate" data-sortable="true" data-formatter="dateFormatter" data-width="80">Дата</th>
                     <th data-field="id" data-type="numeric" data-sortable="true" data-align="right" data-formatter="idFormatter" data-width="80">Id</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-formatter="amountFormatter">Сумма</th>
                     <?php if ($kind == Revise::KIND_REVISE_SUPPLIER):?>
                        <th data-field='legal.name' data-sortable="false">Поставщик</th>
                        <th data-field='contract.name' data-sortable="false">Договор</th>
                     <?php endif;?>   
                     <?php if ($kind == Revise::KIND_REVISE_CLIENT):?>
                        <th data-field='contact.name' data-sortable="false">Покупатель</th>
                     <?php endif;?>   
                     <th data-field='office.name' data-sortable="false">Офис</th>
                     <th data-field='comment' data-sortable="false">Примечание</th>
                     <th data-field="" data-formatter="activeFormatter"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }

    $(function () {
        $ok.click(function () {
            refreshTable;
        });
        
        $(document).on('change', '#supplierSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#officeSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#monthSelect', function (e) {
            refreshTable();
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.supplier = $('#supplierSelect').val();
        params.office = $('#officeSelect').val();
        params.month = $('#monthSelect').val();
        params.kind = <?= $kind?>
        
        return params;
    }
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }
    
    function idFormatter(value, row){
        if (row.aplId){
            return '<nobr>' + value + ' (' + row.aplId + ')</nobr>';
        }
        return value;
    }    

    function amountFormatter(value){
        return Math.round(value*100)/100;
    }    
    
    function activeFormatter(value, row){
        var url = '/revise/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs revise-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>

