<?php
$this->headTitle('Зарплата');

$this->mainMenu()->setActiveItemId('report');
$this->mainMenu()->setActiveUrl($this->url('balance'));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Баланс' => $this->url('balance'),
            'Зарплата' => $this->url('balance', ['action' => 'zp'])
            ]);  

?>
<?= $this->pageBreadcrumbs()->render(); ?>
<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select id="periodSelect" class="form-control" name="period">
                        <option value="date">Дата</option>
                        <!--<option value="week">Неделя</option>-->                        
                        <option value="month" selected="">Месяц</option>                        
                        <option value="number">Год</option>                        
                    </select>
                    <input name="dateStart" id="dateStart" style="width: 200px" min="2024-01" class="form-control refresh-table" type="month" value="<?= date('Y-m')?>">
                </div>    
                <div class="form-group">
                    <select id="companySelect" name="company" style="width: 200px" class="form-control cookie-control">
                        <?php foreach ($companies as $value):?>
                            <option value="<?= $value->getId()?>"><?= $value->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
            </div>
        </div>    
        <table id="table" 
            data-toggle="table" 
            data-url="/balance/zp-content"
            data-side-pagination="server"
            data-pagination="false" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-show-footer="true"
            data-row-style="rowStyle"
            data-classes = "table table-bordered table-hover table-condensed"
            >
            <thead>
                <tr>
                     <th data-field="user.fullName" data-sortable="false" data-footer-formatter="totalFooterFormatter">Сотрудник</th>
                     <th data-field="start" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Долг на начало</th>
                     <th data-field="amountIn" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Начисленно</th>
                     <th data-field="amountOut" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">получено</th>
                     <th data-field="end" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Долг на конец</th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    var $table = $('#table');
        $ok = $('#ok');
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }
    

    $(function () {
        $ok.click(function () {
            refreshTable();
        });
        $table.on('load-success.bs.table', function (e, res) {
            tableRowClick();        
        });                
        $(document).on('change', '#companySelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#yearSelect', function (e) {
            refreshTable();
        });
        $(document).on('click', '.calculate-button', function (e) {
            var url = "/opu/calculate?year="+$('#yearSelect').val();
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: true
            });
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    refreshTable();
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });                
            });                
    });    
    
    function rowStyle(row){
        var retired = 'tablerow';
        
        return {classes: retired};
    }
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function totalFooterFormatter() {
        return 'Итого:';
    }
    
    function footerFormatter(data){
        var field = this.field;
        return $.number((data.map(function (row) {
            return +row[field];
        }).reduce(function (sum, i) {
            return (Math.round((sum + i)*100)/100);
        }, 0)), 2, ',', ' ');
    }        
    
    function amountFormatter(value){
        if (value > 0){
            return $.number(value, 2, ',', ' ' );
        }
        if (value < 0){
            return '<span style="color:red">'+$.number(value, 2, ',', ' ' )+'</span>';
        }
        
        return '';
    }    
        
    function amountTotalFormatter(value){
        if (value > 0){
            return '<b>'+$.number(value, 2, ',', ' ' )+'</b>';
        }
        if (value < 0){
            return '<b style="color:red">'+$.number(value, 2, ',', ' ' )+'</b>';
        }
        
        return '';
    }    
        
    function responseHandler(res) {
        return res;
    }    
</script>
