<?php
use Fin\Entity\FinOpu;

$this->headTitle('Продажи');

$this->mainMenu()->setActiveItemId('report');
$this->mainMenu()->setActiveUrl($this->url('opu'));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'ОПиУ' => $this->url('opu'),
            'Продажи' => $this->url('opu', ['action' => 'retail'])
            ]);  

?>
<?= $this->pageBreadcrumbs()->render(); ?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select id="yearSelect" class="form-control" name="year">
                        <?php foreach ($years as $year):?>
                            <option value="<?= $year?>"><?= $year?></option>
                        <?php endforeach; ?>    
                    </select>
                </div>
                <div class="form-group">
                    <select id="companySelect" name="company" style="width: 200px" class="form-control cookie-control">
                        <?php foreach ($companies as $value):?>
                            <option value="<?= $value->getId()?>"><?= $value->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="kindSelect" name="kind" style="width: 200px" class="form-control cookie-control">
                        <?php foreach (FinOpu::getRetailKindList() as $key => $value):?>
                            <option value="<?= $key?>"  <?= ($kind == $key) ? 'selected':'' ?>><?= $value?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
            </div>
        </div>    
        <table id="table" 
            data-toggle="table" 
            data-url="/opu/retail-content"
            data-side-pagination="server"
            data-pagination="false" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-show-footer="true"
            data-row-style="rowStyle"
            data-classes = "table table-bordered table-hover table-condensed"
            >
            <thead>
                <tr>
                     <th data-field="mark" data-sortable="false" data-footer-formatter="totalFooterFormatter" data-formatter="markFormatter">Сотрудник</th>
                     <th data-field="01" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Январь</th>
                     <th data-field="02" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Февраль</th>
                     <th data-field="03" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Март</th>
                     <th data-field="04" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Апрель</th>
                     <th data-field="05" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Май</th>
                     <th data-field="06" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Июнь</th>
                     <th data-field="07" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Июль</th>
                     <th data-field="08" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Август</th>
                     <th data-field="09" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Сентябрь</th>
                     <th data-field="10" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Октябрь</th>
                     <th data-field="11" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Ноябрь</th>
                     <th data-field="12" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Декабрь</th>
                     <th data-field="13" data-sortable="false" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountTotalFormatter">Итого</th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    var $table = $('#table');
        $ok = $('#ok');
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }
    

    $(function () {
        $ok.click(function () {
            refreshTable();
        });
        $table.on('load-success.bs.table', function (e, res) {
            tableRowClick();        
        });                
        $(document).on('change', '#companySelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#kindSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#yearSelect', function (e) {
            refreshTable();
        });
        $(document).on('click', '.calculate-button', function (e) {
            var url = "/opu/calculate?year="+$('#yearSelect').val();
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: true
            });
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    refreshTable();
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });                
            });                
    });    
    
    function rowStyle(row){
        var retired = 'tablerow';
        
        return {classes: retired};
    }
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function totalFooterFormatter() {
        return 'Итого:';
    }
    
    function footerFormatter(data){
        if ($('#kindSelect').val() !== 'marginRetail'){
            var field = this.field;
            return $.number((data.map(function (row) {
                return +row[field];
            }).reduce(function (sum, i) {
                return (Math.round((sum + i)*100)/100);
            }, 0)), 0, ',', ' ');
        }
        
        return '';
    }        
    
    function amountFormatter(value){
        if (value > 0){
            return $.number(value, 0, ',', ' ' );
        }
        if (value < 0){
            return '<span style="color:red">'+$.number(value, 0, ',', ' ' )+'</span>';
        }
        
        return '';
    }    
        
    function amountTotalFormatter(value){
        if (value > 0){
            return '<b>'+$.number(value, 0, ',', ' ' )+'</b>';
        }
        if (value < 0){
            return '<b style="color:red">'+$.number(value, 0, ',', ' ' )+'</b>';
        }
        
        return '';
    }    
    
    function markFormatter(value, row){
        return '<a href="/order/fin?user='+row.key+'" target="_blank">'+value+'</a>';
    }        
        
    function responseHandler(res) {
        return res;
    }    
</script>
