<?php
use Application\Entity\Client;

$this->headTitle('Комментарии');

$this->mainMenu()->setActiveItemId('client');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Продажи'=>$this->url('order'),
            'Комментарии'=>$this->url('comments'),
            ]);
?>

<h1>Коммментарии</h1>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск по телефону, email, aplId">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/comments/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric" data-width="75">ID</th>
                     <th data-field="aplId" data-type="numeric" data-width="75">AplId</th>
                     <th data-field="dateCreated" data-width="150">Дата</th>
                     <th data-field="order.id" data-formatter="orderFormatter" data-width="100">Заказ</th>
                     <th data-field="comment" data-sortable="true">Комментарий</th>
                     <th data-field="client.id" data-formatter="clientFormatter" data-width="100">Клиент</th>
                     <th data-field="user.fullName" data-width="100">Автор</th>
                     <th data-field="id" data-formatter="activeFormatter" data-width="50"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table').bootstrapTable();

    ok = $('#ok');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function orderFormatter(value){
        if (!value){
            value = '---';
        }
        return [
            '<a href="/order/view/' + value + '" target="_blank">' + value + '</a>'
        ].join(''); 
    }    
    
    function clientFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<a href="/client/view/' + value + '" target="_blank">' + row.client.name + '</a>'
        ].join(''); 
    }    
    
    function activeFormatter(value, row){
        var orderId = null;
        if (row.order){
            orderId = row.order.id;
        }
        var url = '/comments/edit-form/'+value+'?client='+row.client.id+'&order='+orderId;
        btn = '<button';
        btn += ' value="'+url+'"';
        btn += ' class="btn btn-default btn-xs"';
        btn += ' data-toggle="modal" data-target="#modal-dialog"'; 
        btn += ' title="Изменить">'; 
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>


