<div id="orderComments">
    <?php if ($comments):?>
        <ul class="list-unstyled">        
        <?php foreach ($comments as $comment):?>
            <li>
                <h6>
                    <small><?= $comment->getDateCreatedShort()?></small>
                    <small><?= ($comment->getUser()) ? $comment->getUser()->getFullName():'NaN'?></small>                                                                                
                    <?= $this->escapeHtml($comment->getComment())?>
                </h6>                                        
            </li>
        <?php endforeach;?>
        </ul>
    <?php endif; ?>
</div>