
<div class="modal-header">
    <a href="#" class="order-comment-modal-show" order-id="<?= $order->getId() ?>" modal-url="/comments/edit-local-form/">+ Добавить комментарий</a>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="row">
    <div class="col-xs-12">     
        <div class="form-group form-group-sm">
            <?php echo $this->partial('/application/comment/order-partial', ['comments' => $comments]); ?>
        </div>    
    </div>    
</div>    
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
</div>