<?php
use Zp\Entity\Personal;
use Zp\Entity\PersonalAccrual;
use Zp\Entity\PersonalMutual;
use Laminas\Json\Encoder;
use Stock\Entity\Movement;

?>
<div class="modal-header">
    <h5 class="modal-title">Расшифровка начисдений/удержаний/выплат ЗП</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="row">
    <div class="col-md-12">
        <div id="mutualToolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <select id="mutualPeriodSelect" class="form-control" name="period">
                        <option value="date" <?= ($period == 'date') ? 'selected':''?>>Дата</option>
                        <!--<option value="week">Неделя</option>-->                        
                        <option value="month" <?= ($period == 'month') ? 'selected':''?>>Месяц</option>                        
                        <option value="number" <?= ($period == 'number') ? 'selected':''?>>Год</option>                        
                    </select>
                    <input name="dateStart" id="mutualDateStart" style="width: 200px" class="form-control refresh-table" min="2024-01-01" type="<?= $period?>" value="<?= $dateStart?>">
                </div>
                <div class="form-group">
                    <select id="mutualCompanySelect" name="company" style="width: 200px" <?= ($rbacManager->isGranted(null, 'zp.manage')) ? '':'disabled' ?> class="form-control cookie-control">
                        <?php foreach ($companies as $value):?>
                            <option value="<?= $value->getId()?>" <?= ($companyId == $value->getId()) ? 'selected':''?>><?= $value->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="mutualUserSelect" name="user" style="width: 200px" <?= ($rbacManager->isGranted(null, 'zp.manage')) ? '':'disabled' ?> class="form-control cookie-control">
                        <?php foreach ($users as $value):?>
                            <option value="<?= $value->getId()?>" <?= ($userId == $value->getId()) ? 'selected':''?>><?= $value->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="mutualAccrualSelect" name="accrual" style="width: 200px" <?= ($rbacManager->isGranted(null, 'zp.manage')) ? '':'disabled' ?> class="form-control cookie-control">
                        <?php foreach ($accruals as $value):?>
                            <option value="<?= $value->getId()?>" <?= ($accrualId == $value->getId()) ? 'selected':''?>><?= $value->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
            </div>
        </div>    
        <table id="mutualtable" 
            data-toggle="mutualtable" 
            data-url="/zp/content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#mutualToolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="mutualQueryParams"
            data-response-handler="mutualResponseHandler"
            data-row-style="mutualRowStyle"
            data-classes = "table table-bordered table-hover table-condensed"
            data-cookie="false"
            data-cookie-id-table="zpMutualSaveId"
            data-cookie-expire="1m"            
            data-show-footer="true"
            data-sort-name="dateOper"
            data-sort-order="desc"
            >
            <thead>
                <tr>
                     <th data-field="id" data-sortable="true" data-align="right" data-width="10">Id</th>
                     <th data-field="dateOper" data-sortable="true" data-width="10" data-formatter="dateFormatter">Дата</th>
                     <th data-field="docId" data-sortable="false" data-formatter="docKeyFormatter">Документ</th>
                     <th data-field="accrual.name" data-sortable="false">Операция</th>
                     <th data-field="user.fullName" data-footer-formatter="totalFooterFormatter">Сотрудник</th>
                     <th data-field="amount" data-sortable="false" data-align="right" data-footer-formatter="amountTotalFormatter" data-formatter="amountFormatter">Сумма</th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<div class="modal-footer">
    <button type="button" class="btn btn-secondary zp-mutual-close" data-dismiss="modal">Закрыть</button>
</div>

<script type="text/javascript">
    var $mutualTable = $('#mutualtable');
            $ok = $('#ok');
    
    function mutualRefreshTable(){
        $mutualTable.bootstrapTable('refresh');
    }    

    $( document ).ready(function() {

        $ok.click(function () {
            mutualRefreshTable();
        });
        
        $mutualTable.bootstrapTable({
            onLoadSuccess: function(res){
                tableRowClick();   
                var totalAmount = 0;
                if (res.totalAmount){
                    totalAmount = Math.abs(res.totalAmount);
                }
                $('#amountTotalFooter').html($.number(totalAmount, 2, '.', '' ));
            }            
        });
        
//        $table.on('load-success.bs.table', function (e, res) {
//        });                
        $(document).on('change', '#mutualCompanySelect', function (e) {
            mutualRefreshTable();
        });
        $(document).on('change', '#mutualUserSelect', function (e) {
            mutualRefreshTable();
        });
        $(document).on('change', '#mutualAccrualSelect', function (e) {
            mutualRefreshTable();
        });
        $(document).on('change', '#mutualDateStart', function (e) {
            mutualRefreshTable();
        });
        
        $(document).on('click', '.zp-mutual-close', function (e) {            
        });
        
        $(document).on('change', '#mutualPeriodSelect', function (e) {
            var selectType = $(this).val();
            $('#mutualDateStart').attr('type', selectType);
            switch(selectType){
                case 'number':
                    $('#mutualDateStart').val(new Date().getFullYear());
                    $('#mutualDateStart').attr('min', 2012);
                    break;
                case 'month':    
//                    $('#dateStart').val($.format.date(new Date(), "yyyy-MM"));
//                    break;
                default:
                    $('#mutualDateStart').val($.format.date(new Date(), "yyyy-MM-dd"));
            }
        });
    });    
    
    function mutualRowStyle(row){
        var retired = 'tablerow';

        if (row.status === '<?= PersonalMutual::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        
        return {classes: retired};
    }
    
    function mutualQueryParams(params) {
        $('#mutualToolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#mutualToolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#mutualtable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#mutualtable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function totalFooterFormatter() {
        return 'Итого:';
    }
    
    function amountTotalFormatter(){
        return '<span id="amountTotalFooter"></span>';
    }        

    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }    
    
    function amountFormatter(value){
        return (Math.round(Math.abs(value)*100)/100).toFixed(2);
    }        
    
    function docKeyFormatter(value, row){
        let docType = row.docType;        
        let docId = row.docId;  
        var comment = '';
        switch(docType){
            case '<?= Movement::DOC_ZP?>': 
                return 'Начисление ЗП';
            case '<?= Movement::DOC_ORDER?>': 
                return "<a href='#' class='order-view-show' modal-url='/order/view/"+docId+"'>Заказ №Z"+docId+"</a>";
            case '<?= Movement::DOC_MSR?>': 
                comment = (row.marketSaleReport.comment) ? row.marketSaleReport.comment:'';        
                return "<a href='#' class='msr-modal-show' modal-url='/comitent/edit-form/"+docId+"'>Отчет о продажах №"+docId+"</a> <small class='text-muted'>"+comment+"</small>";
            case '<?= Movement::DOC_VT?>': 
                return "<a href='#' class='vt-modal-show' modal-url='/vt/edit-form/"+docId+"'>Возврат покупателя №"+docId+"</a>";
            case '<?= Movement::DOC_ST?>': 
                return "<a href='#' class='st-modal-show' modal-url='/st/edit-form/"+docId+"'>Списание №"+docId+"</a>";
            case '<?= Movement::DOC_CASH?>':
                return 'Выдача из кассы/подотчета';        
            default: return docId;            
        }
    }
    
    function mutualResponseHandler(res) {
        return res;
    }    
</script>