<?php
use Zp\Entity\PersonalMutual;
use Laminas\Json\Encoder;
use Zp\Entity\Personal;

$this->headTitle('Расчетный листок');

$this->mainMenu()->setActiveItemId('personalSettings');
$this->mainMenu()->setActiveUrl($this->url('payslip'));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Расчетный листок' => $this->url('payslip')
            ]);  

?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <button class="btn btn-default zp-modal-show" type="button" disabled modal-url="/zp/edit-form">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </button>
                </div>    
                <div class="form-group">
                    <select id="periodSelect" class="form-control" name="period">
                        <option value="date">Дата</option>
                        <!--<option value="week">Неделя</option>-->                        
                        <option value="month" selected="">Месяц</option>                        
                        <option value="number">Год</option>                        
                    </select>
                    <input name="dateStart" id="dateStart" style="width: 200px" min="2024-01" class="form-control refresh-table" type="month" value="<?= date('Y-m')?>">
                </div>
                <div class="form-group">
                    <select id="companySelect" name="company" style="width: 200px" class="form-control cookie-control">
                        <!--<option selected>все компании</option>-->
                        <?php foreach ($companies as $value):?>
                            <option value="<?= $value->getId()?>"><?= $value->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="userSelect" name="user" style="width: 200px" <?= ($rbacManager->isGranted(null, 'zp.manage')) ? '':'disabled' ?> value="<?= $currentUser->getId()?>" class="form-control cookie-control">
                        <option>все сотрудники</option>
                        <?php foreach ($users as $value):?>
                            <option value="<?= $value->getId()?>" <?= ($currentUser->getId() == $value->getId()) ? 'selected':'' ?>><?= $value->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="accrualSelect" name="accrual" style="width: 200px" class="form-control cookie-control">
                        <option>все начисления</option>
                        <?php foreach ($accruals as $value):?>
                            <option value="<?= $value->getId()?>"><?= $value->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <button value="/zp/user-report/" <?= ($rbacManager->isGranted(null, 'zp.manage')) ? '':'disabled' ?> class="btn btn-default user-report"
                        title="Сохранить в файл">
                    <span class="glyphicon glyphicon-save-file" ></span>
                </button>                         
            </div>
        </div>    
        <table id="table" 
            data-toggle="table" 
            data-url="/zp/payslip-content"
            data-side-pagination="client"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-row-style="rowStyle"
            data-classes = "table table-bordered table-hover table-condensed"
            data-cookie="true"
            data-cookie-id-table="zpPayslipSaveId"
            data-cookie-expire="1m"            
            data-show-footer="true"
            >
            <thead>
                <tr>
                     <th data-field="id" data-sortable="true" data-align="right" data-width="10">Id</th>
                     <th data-field="company.name" data-sortable="true" data-width="200">Организация</th>
                     <th data-field="user.fullName" data-sortable="true" data-width="200">Сотрудник</th>
                     <th data-field="accrual.name" data-footer-formatter="totalFooterFormatter" data-sortable="true">Вид начисления/удержания</th>
                     <th data-field="amountOut" data-sortable="false" data-width="250" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Начислено</th>
                     <th data-field="amountIn" data-sortable="false" data-width="250" data-align="right" data-footer-formatter="footerFormatter" data-formatter="amountFormatter">Удержано</th>
                     <th data-field="active" data-formatter="activeFormatter" data-width="5"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>  
<p></p>
<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <table width="100%" class="table table-bordered table-hover table-condensed">
            <tr>
                <td id="startBalanceLabel">
                   Долг на начало за предприятием  
                </td>
                <td align="right" width="250">
                    <strong><span id="startBalance"></span></strong>
                </td>
                <td align="right" width="5">
                </td>
            </tr>
            <tr>
                <td>
                   Начислено  
                </td>
                <td align="right">
                    <span class="" id="totalIn"></span>
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                   Удержано/получено  
                </td>
                <td align="right">
                    <span class="" id="totalOut"></span>
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td id="endBalanceLabel">
                   Долг на конец за предприятием  
                </td>
                <td align="right">
                    <strong><span class="h1" id="endBalance"></span></strong>
                </td>
                <td>
                </td>
            </tr>
        </table>             
    </div>
    <div class="col-md-3">
    </div>
</div>

<?php echo $this->partial('/zp/index/zp-partial', []); ?>
<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    var $table = $('#table');
        $ok = $('#ok');
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }
    
    function userReport(){ 
        bootbox.prompt({
            title: 'Сохранить отчет за месяц',
            inputType: 'date',
            value: new Date($('#dateStart').val()).toISOString().split('T')[0],        
            callback: function (result) {
//                console.log(result);                
                if (result){
                    var dialog = bootbox.dialog({
                        message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                        closeButton: true
                    });                    
                    $.getJSON('/zp/user-report?user='+$('#userSelect').val()+'&dateStart='+result, function( data ) {
                        dialog.modal('hide');
//                        $table.bootstrapTable('refresh', {silent:true});
                    });                    
                }    
            }
        });
        return;
    }    

    $(function () {
        $ok.click(function () {
            refreshTable();
        });
        
        //$('#userSelect').val(<?= $currentUser->getId()  ?>);
        
        $table.on('load-success.bs.table', function (e, res) {
            $('#startBalance').html($.number(res.startBalance, 0, ',', ' '));
            $('#startBalanceLabel').html('Долг за предприятием на начало месяца');
            if (Math.round(res.startBalance) < 0){
                $('#startBalanceLabel').html('Долг за сотрудником на начало месяца');
            }
            $('#endBalance').html($.number(res.endBalance, 0, ',', ' '));
            $('#endBalanceLabel').html('Долг за предприятием на конец месяца');
            $('#endBalance').addClass( "text-success");
            $('#endBalance').removeClass( "text-danger");
            if (Math.round(res.endBalance) < 0){
                $('#endBalanceLabel').html('Долг за сотрудником на конец месяца');
                $('#endBalance').removeClass( "text-success" );
                $('#endBalance').addClass( "text-danger" );
            }
            $('#totalIn').html($.number(res.totalIn, 0, ',', ' '));
            $('#totalOut').html($.number(res.totalOut, 0, ',', ' '));
        });                
        $(document).on('change', '#companySelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#userSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#accrualSelect', function (e) {
            refreshTable();
        });
        $(document).on('change', '#dateStart', function (e) {
            refreshTable();
        });
        $(document).on('click', '.user-report', function (e) {
            userReport();
        });
        $(document).on('change', '#periodSelect', function (e) {
            var selectType = $(this).val();
            $('#dateStart').attr('type', selectType);
            switch(selectType){
                case 'number':
                    $('#dateStart').val(new Date().getFullYear());
                    $('#dateStart').attr('min', 2024);
                    break;
                case 'month':    
                    $('#dateStart').attr('min', '2024-01');
                    $('#dateStart').val($.format.date(new Date(), "yyyy-MM"));
                    break;
                default:
                    $('#dateStart').attr('min', '2024-01-01');
                    $('#dateStart').val($.format.date(new Date(), "yyyy-MM-dd"));
            }
        });
    });    
    
    function rowStyle(row){
        var retired = 'tablerow';

        if (row.status === '<?= PersonalMutual::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        
        return {classes: retired};
    }
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }    
    
    function accrualFormatter(value, row){
        if (row.amount<0){
            return (-Math.round(row.amount*100)/100).toFixed(0);
        }
        
        return '';
    }        

    function amountFormatter(value, row){
//        var result = (Math.round(value*100)/100).toFixed(0);
        if (Math.round(value) !== 0){
            return $.number(value, 0, ',', ' ');
        }
        
        return '';
    }        
    
    function totalFooterFormatter() {
        return 'Итого:';
    }
    
    function footerFormatter(data){
        var field = this.field;
        return $.number((data.map(function (row) {
            return +row[field];
        }).reduce(function (sum, i) {
            return (Math.round((sum + i)*100)/100);
        }, 0)), 0, ',', ' ');
    }    
    
    function statusFormatter(value, row){
        var statuses = <?= Encoder::encode(Personal::getStatusList())?>;
        return statuses[value];
    }    
    
    function activeFormatter(value, row){        
        var url = '/zp/mutual?company='+row.company.id+'&user='+row.user.id+'&accrual='+row.accrual.id+'&period='+$('#periodSelect').val()+'&dateStart='+$('#dateStart').val();
        btn = '<button ';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs mutual-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
        
    function responseHandler(res) {
        return res;
    }    
</script>
