<script>
   //формы zp
   
    $(function () {
        $('#ok').click(function () {
            refreshTable();
        });
        
        $(".inputclear").click(function(){
            $(".enter-search").val('');
            refreshTable();
        });

        $(document).on('click', '.accrual-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'accrualModal',
                url: url
                //width: '1440px'
            });
        });  

        $(document).on('click', '.position-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            if ($("#companySelect").length){
                url += '?company='+$("#companySelect").val();
            }
            showFormDialog({
                id: 'positionModal',
                url: url
                //width: '1440px'
            });
        });  

        $(document).on('click', '.personal-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            if ($("#companySelect").length){
                url += '?company='+$("#companySelect").val();
            }
            if ($("#userSelect").length){
                url += '&user='+$("#userSelect").val();
            }
            showFormDialog({
                id: 'personalModal',
                url: url,
                width: '1000px'
            });
        });  

        $(document).on('click', '.personal-accrual-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            var uniqueId = $(this).attr('unique-id');
            if (uniqueId){
                var row = $('#accrualtable').bootstrapTable('getRowByUniqueId', uniqueId);
                url = url+'?'+$.param(row);
            }    
            showFormDialog({
                id: 'personalAccrualModal',
                url: url,
                zIndex: 9999
            });
        });  
        
        $(document).on('click', '.personal-revise-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            if ($("#companySelect").length){
                url += '?company='+$("#companySelect").val();
            }
            if ($("#userSelect").length){
                url += '&user='+$("#userSelect").val();
            }
            showFormDialog({
                id: 'personalReviseModal',
                url: url,
                width: '1000px'
            });
        });  
        
        $(document).on('click', '.mutual-modal-show', function (e) {
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'mutualModal',
                url: url,
                width: '1000px',
                zIndex: 5555
            });
        });  
        
    });
    
</script>
