<?php
$form = $this->form;

$form->get('office_id')->setAttributes([
    'class'=>'form-control', 
//    'disabled' => 'true',
    ]);

$form->get('doc_date')->setAttributes([
    'class'=>'form-control', 
    'min' => date('Y-m-d', strtotime($allowDate.' + 1 day')),
    ]);

$form->get('doc_no')->setAttributes([
    'class'=>'form-control', 
    'disabled' => 'true',
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'vt-submit']);

$form->prepare();

$docName = 'Новый';
$orderDocName = '№ '.$order->getIdLink().' от  '.date('d.m.Y', strtotime($order->getDateOper()));
if ($vt){
    $docName = '№ '.$vt->getId().' от  '.date('d.m.Y', strtotime($vt->getDocDate()));
}

?>

<?= $this->form()->openTag($form); ?>

<div class="modal-header">
    <h5 class="modal-title" id="vtModalLabel">Возврат товаров <?= $docName?> по заказу <?= $orderDocName?></h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <div class="row">
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('doc_date')); ?>
                <?= $this->formElement($form->get('doc_date')); ?>
                <?= $this->formElementErrors($form->get('doc_date')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('doc_no')); ?>
                <?= $this->formElement($form->get('doc_no')); ?>
                <?= $this->formElementErrors($form->get('doc_no')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('office_id')); ?>
                <?= $this->formElement($form->get('office_id')); ?>
                <?= $this->formElementErrors($form->get('office_id')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>                  
            </div>
        </div>
        <div class="col-xs-2 text-right">
            <h1 class="display-4" id="vtQuantity"></h1>
        </div>    
        <div class="col-xs-1 text-right">
            <h1 class="display-4" id="vtAmount"><?= ($vt) ? round($vt->getAmount(), 2):"" ?></h1>                        
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-12">
            <div id="vtgoodtoolbar">
                <div class="form-inline" role="form">
                    <button type="button" class="btn btn-default" onclick="vtFill()">
                        <span aria-hidden="true">Заполнить из заказа</span>
                    </button>
                    <button id="remove-selected-button" class="btn btn-default" type="button" title="Удалить выделенное">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </button>                
                    <button class="btn btn-default good-row-copy" type="button" title="Копировать выделенные строки">
                        <span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span>
                    </button>                
                </div>
            </div>    
            <table id="vtgoodtable" 
                data-toggle="vtgoodtable" 
                data-url="/vt/good-content/<?= ($vt) ? $vt->getId():"" ?>"
                data-side-pagination="client"
                data-pagination="true"
                data-cookie="true"
                data-cookie-id-table="vtGoodSave<?= $vt->getId()?>"
                data-cookie-expire="1m"
                data-page-size = "50"
                data-page-list="[5, 10, 20, 50]"
                data-toolbar="#vtgoodtoolbar"
                data-show-refresh="true"
                data-show-toggle="false"
                data-show-columns="true"
                data-query-params="vtgoodQueryParams"
                data-response-handler="vtgoodResponseHandler"
                data-unique-id = "rowNo"
                data-row-style="takeStyle"
                data-click-to-select="true"
                >
                <thead>
                    <tr>
                        <th data-checkbox="true"></th>
                        <th data-field="rowNo" data-type="numeric" data-align="right">N</th>
                        <th data-field="good.code" data-type="numeric" data-formatter="goodFormatter">Артикул</th>
                        <th data-field="good.producer.name" data-type="numeric">Производитель</th>
                        <th data-field="good.name" data-type="numeric">Наименование</th>
                        <th data-field='price' data-type="numeric" data-formatter="pgPriceFormatter" data-always-use-formatter="true" data-align="right" data-editable="true">Цена</th>
                        <th data-field='quantity' data-type="numeric" data-align="right" data-always-use-formatter="true" data-editable="true">Количество</th>
                        <th data-field='amount' data-type="numeric" data-formatter="pgAmountFormatter" data-always-use-formatter="true" data-align="right">Сумма</th>
                        <th data-field="baseKey" data-visible="false" data-editable="true" data-editable-type="select" data-editable-source="/vt/find-base/<?= $vt->getId()?>" data-width="10">Партия</th>
                        <th data-field="id" data-formatter="pgActiveFormatter" data-width="5"></th>
                    </tr>                
                </thead>
            </table>
        </div>
    </div>    
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?= $this->formLabel($form->get('comment')); ?>
                <?= $this->formElement($form->get('comment')); ?>
                <?= $this->formElementErrors($form->get('comment')); ?>                  
            </div>                        
        </div>                                            
    </div>        




            <?= $this->formElement($form->get('csrf')); ?>
        </div>
    </div>
</div>    

<div class="modal-footer">
    <button type="button" class="btn btn-secondary vt-close" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary" id="vt-submit">Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script>
    function vtUpdateTotal(){
        var data = $('#vtgoodtable').bootstrapTable('getData');
        var amount = 0; var quantity = 0;
        $.each(data, function( index, value ) {
            amount += Math.round(value.amount*100)/100;
            quantity += Math.round(value.quantity*100)/100; 
        });
        $('#vtAmount').html(Math.round(amount*100)/100);
        $('#vtQuantity').html(Math.round(quantity*100)/100);
    }
    
    function vtFill(){
        $.ajax({
            type: 'GET',
            url: "/order/good-content/<?= ($order) ? $order->getId():"" ?>"
        })
            .done(function (data) {
                $('#vtgoodtable').bootstrapTable('removeAll');
                var rows = [];
                $.each( data, function( index, row ) { 
                    var good = {
                        id: row.good.id,
                        code: row.good.code,
                        name: row.good.name,
                        producer: {name: row.good.producer.name}
                    };
                    var row = {
                        good: good,
                        amount: row.price*row.num,
                        quantity: row.num,
                        price: row.price,
                        rowNo: index+1
                    };

                    rows.push(row);
                });   
                $('#vtgoodtable').bootstrapTable('append', rows);                        
                vtUpdateTotal();
            })
            .fail(function () {
                alert("Ошибка при получении данных.");

            });            
    }
    
    function submitForm(){
        var data = serializeForm('#vt-form');
        data.vtGood = getFormatedVtGood();
        $.ajax({
            type: 'POST',
            url: '/vt/edit-form/<?= ($vt) ? $vt->getId():"" ?>?order=<?= ($order) ? $order->getId():"" ?>',
            data: $.param(data)
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#vtModal').modal('hide');
                    $('#vtgoodtable').bootstrapTable('destroy');
                    if ($('#movementTable').length){
                        $('#movementTable').bootstrapTable('refresh');
                    }    
                    if ($('#vttable').length){
                        $('#vttable').bootstrapTable('refresh');
                    }    
                } else {
                    $('#vtModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };
    
    function getFormatedVtGood(){
        var data = $('#vtgoodtable').bootstrapTable('getData');
        var result = [];
        $.each( data, function( index, row ) {
            var newRow = {
                good_id: row.good.id,
                quantity: row.quantity,
                amount: row.amount,
                baseKey: row.baseKey
            };
            result.push(newRow);
        });   
        return result;
    }
        
    //удаление строки из таблицы
    function removeTableRowByUniqueId(index){
        $('#vtgoodtable').bootstrapTable('removeByUniqueId', index);
        vtUpdateTotal();
    }
    
    $( document ).ready(function() {
        
        $('#remove-selected-button').click(function () {
            var ids = $.map($('#vtgoodtable').bootstrapTable('getSelections'), function (row) {
              return row.rowNo;
            });
            $('#vtgoodtable').bootstrapTable('remove', {
              field: 'rowNo',
              values: ids
            });
            vtUpdateTotal();
        });        

        $('#vtgoodtable').bootstrapTable({
            onLoadSuccess: function(res){
                vtUpdateTotal();
            }            
        }); 
        
        $(document).on('click', '.vt-close', function (e) {
            $('#vtgoodtable').bootstrapTable('destroy');
        });        
        
        $(document).on('click', '.good-row-copy', function (e) {
            var selections = $('#vtgoodtable').bootstrapTable('getSelections');
            if (selections.length){
                $.each( selections, function( index, row ) {
                    var newRowNo = getNewTableUniqueId('vtgoodtable', 'rowNo');
                    var newRow = {
                        good: row.good,
                        price: row.price,
                        quantity: row.quantity,
                        amount: row.amount,
                        rowNo: newRowNo
                    };
                    newRow.rowNo = newRowNo;
                    $('#vtgoodtable').bootstrapTable('insertRow', {index: 1, row: newRow});
                });  
                $('#vtgoodtable').bootstrapTable('uncheckAll');
                vtUpdateTotal();
            }    
        });      
        
        var forms = $('#vt-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('vt-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });
    });    
    
    $(document).on('editable-save.bs.table', '#vtgoodtable', function (e, field, row, rowIndex, old, $el) { 
        var amount = row.amount;
        if (field == 'price'){
            amount = row.price*row.quantity;
        }
        if (field == 'quantity'){
            var price = row.amount/old;
            amount = price*row.quantity;
        }
        $('#vtgoodtable').bootstrapTable('updateCellByUniqueId', {id: row.rowNo, field: 'amount', value: amount});            
        vtUpdateTotal();
    });        

    function vtGoodRefreshTable(){
        $('#vtgoodtable').bootstrapTable('refresh');
    }
    
    function vtgoodQueryParams(params) {
        $('#vtgoodtoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#vtgoodtable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#vtgoodtable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function goodFormatter(value, row){
        var url = '/goods/view/'+row.good.id;
        btn = '<nobr><a';
        btn += ' href="'+url+'"';
        btn += ' class="btn btn-link btn-xs" target="_blank">';
        btn += '<span class="glyphicon glyphicon-link"></span>';
        btn += '</a>'+value+'</nobr>';
        return btn;
    }    
    
    function nameFormatter(value, row){
        if (row.good.tokenGroup.name){
            return row.good.tokenGroup.name;
        }        
        return value;
    }    

    function pgActiveFormatter(value, row){
//        var url = '/vt/good-edit-form/';
//        btn = '<button';
//        btn += ' type="button"';
//        btn += ' class="btn btn-default btn-xs vt-good-modal-show"';
//        btn += ' aria-label="Left Align"'; 
//        btn += ' unique-id="'+value+'"';
//        btn += ' modal-url="'+url+'">';
//        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
//        btn += '</button>';

        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs table-row-remove"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="removeTableRowByUniqueId('+value+')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function pgPriceFormatter(value, row){
        var result = Math.round(row.amount*100/row.quantity)/100;
        if (value){
            result = value.toString().replace(',', '.');
        }    
        return (Math.round(result*100)/100).toFixed(0);
    }        
    
    function pgAmountFormatter(value, row){
        var result = value;
        if (row.price){
            var price = row.price.toString().replace(',', '.');
            result = (Math.round(price*row.quantity*100)/100).toFixed(0);
        }    
        return result;
    }        
    
    function vtgoodResponseHandler(res) {
        return res;
    }     
</script>