<?php
    use Stock\Entity\Vt;
    $this->headTitle('Возврат товаров');

    $this->mainMenu()->setActiveItemId('client');

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Возврат товаров'=>$this->url('vt'),
                ]);


?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <div class="btn-group">
                        <input id="searchinput" name="search" style="width: 150px" class="form-control enter-search" type="text" placeholder="Артикул">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>
                    <button id="ok" type="submit" class="btn btn-default" title="Поиск">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
                <div class="form-group">
                    <select id="officeSelect" style="width: 100px" class="form-control">
                        <option selected>офис</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>
                    
                </div>    
                <div class="form-group">
                    <input id="monthSelect" class="form-control" type="month" placeholder="Период" value="<?= date('Y-m');?>">
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/vt/content"
            data-cookie="true"
            data-cookie-id-table="vtSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-sort-name="docDate"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="rowStyle"
            >
            <thead>
                <tr>
                     <!--<th data-field="id" data-type="numeric" data-sortable="true" data-align="right">ID</th>-->
                     <th data-field="id" data-sortable="false" data-formatter="idFormatter" data-width="120">Номер</th>
                     <th data-field="docDate" data-sortable="true" data-formatter="dateFormatter" data-width="100">Дата</th>
                     <!--<th data-field="aplId" data-type="numeric" data-align="right">AplId</th>-->
                     <th data-field='amount' data-sortable="false" data-type="numeric" data-align="right" data-formatter="amountFormatter">Сумма</th>
                     <th data-field='order.aplId' data-sortable="false" data-formatter="linkFormatter">Заказ</th>
                     <th data-field='office.name' data-sortable="false">Склад</th>
                     <th data-field='comment' data-sortable="false">Примечание</th>
                     <th data-field="" data-formatter="activeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');
    
    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status === '<?= Vt::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        if (row.status === '<?= Vt::STATUS_COMMISSION?>'){
           retired += ' info';
        }
        if (row.status === '<?= Vt::STATUS_DEFECT?>'){
           retired += ' info';
        }
        if (row.status === '<?= Vt::STATUS_WAIT?>'){
           retired += ' info';
        }
        if (row.statusAccount === '<?= Vt::STATUS_TAKE_NO?>'){
           retired = ' warning';
        }
        
        return {classes: retired};
    }
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }
        
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.office = $('#officeSelect').val();
        params.month = $('#monthSelect').val();
        
        return params;
    }
    
    function idFormatter(value, row){
        if (row.aplId > 0){
            return value + ' ('+row.aplId+')';
        }
        
        return value;
    }    
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }

    
    function linkFormatter(value, row){
        if (!value){
            value = row.order.id;
        }
        return [
            '<div class="pull-left">',
            '<a href="/order/intro/' + row.order.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    
    
    function activeFormatter(value, row){
        var url = '/vt/edit-form/'+row.id;
        btn = '<nobr><button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs vt-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';

        var url = '/apl/send-vt/'+row.id;
        btn += ' <button';
        btn += ' type="button"';
        btn += ' class="btn btn-info btn-xs send-cash-doc"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>';
        btn += '</button></nobr>';

        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>

