<?php
use Stock\Entity\Vt;
use Application\Entity\Order;

if ($order){
    $docName = '№ '.$order->getDocNo().' от  '.date('d.m.Y', strtotime($order->getDocDate()));
}

$disabled = ($order->getStatus() == Order::STATUS_SHIPPED) ? '':'disabled';
?>

<div class="modal-header">
    <h5 class="modal-title" id="vtModalLabel">Возвраты по заказу <?= $docName?></h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="row">
    <div class="col-xs-12">
        <div id="vttoolbar">
            <div class="form-inline" role="form">
                <button <?= $disabled?> class="btn btn-default vt-modal-show" type="button" modal-url="/vt/edit-form?order=<?= $order->getId()?>">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
            </div>
        </div>
        <table id="vttable" 
            data-toggle="vttable" 
            data-url="/vt/content/<?= ($order) ? $order->getId():"" ?>"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#vttoolbar"
            data-show-refresh="true"
            data-query-params="vtQueryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="vtResponseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="rowStyle"
            >
            <thead>
                <tr>
                     <th data-field="id" data-sortable="false" data-formatter="idFormatter" data-width="100">Номер</th>
                     <th data-field="docDate" data-sortable="true" data-formatter="dateFormatter" data-width="100">Дата</th>
                     <!--<th data-field="aplId" data-type="numeric" data-align="right">AplId</th>-->
                     <th data-field='amount' data-sortable="false" data-type="numeric" data-align="right" data-formatter="amountFormatter">Сумма</th>
                     <th data-field='order.aplId' data-sortable="false" data-formatter="linkFormatter">Заказ</th>
                     <th data-field='office.name' data-sortable="false">Склад</th>
                     <th data-field='status' data-sortable="false" data-formatter="statusFormatter">Статус</th>
                     <th data-field='comment' data-sortable="false">Примечание</th>
                     <th data-field="" data-formatter="activeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script>
    $( document ).ready(function() {        
        $('#vttable').bootstrapTable({
            onLoadSuccess: function(res){
                
            }            
        });         
    });
    
    function vtRefreshTable(){
        $('#vttable').bootstrapTable('refresh');
    }
    
    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status == '<?= Vt::STATUS_RETIRED ?>'){
           retired += ' retired';
        }
        if (row.status == '<?= Vt::STATUS_COMMISSION ?>'){
           retired += ' info';
        }
        if (row.status == '<?= Vt::STATUS_DEFECT ?>'){
           retired += ' info';
        }
        
        return {classes: retired};
    }

    function vtQueryParams(params) {
        $('#vttoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#vttable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#vttable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }

    function idFormatter(value, row){
        if (row.aplId > 0){
            return value + ' ('+row.aplId+')';
        }
        
        return value;
    }    
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }
    
    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/order/intro/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    
    
    function statusFormatter(value){
        if (value == '<?= Vt::STATUS_COMMISSION?>'){
            return 'Коммисия';
        }
        if (value == '<?= Vt::STATUS_DEFECT?>'){
            return 'Брак';
        }
        return '';
    }

    function activeFormatter(value, row){
        var url = '/vt/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs vt-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';

        return btn;
    }    
    function vtResponseHandler(res) {
        return res;
    }     
</script>