<?php
$this->headTitle('Страна - ' . $country->getName());
//$this->mainMenu()->setActiveItemId('home');
//$this->pageBreadcrumbs()->setItems([
//            'Home'=>$this->url('home')
//            ]);
        
?>

<a href="
    <?= $this->url('rb', ['action'=>'country']); ?>">
    &lt;&lt; Назад в список стран
</a>

<h1>
    <?= $this->escapeHtml($country->getName()); ?>    
</h1>


<p>    
    <?= $this->escapeHtml($country->getFullName()); ?>
</p>

<p>    
    <?= $this->escapeHtml($country->getCode()); ?>
</p>

<p>    
    <?= $this->escapeHtml($country->getAlpha2()); ?>
</p>

<p>    
    <?= $this->escapeHtml($country->getAlpha3()); ?>
</p>