<h1>Справочники</h1>

<p>
<a class="btn btn-default" href="
    <?= $this->url('rb', ['action'=>'tax']); ?>">
    Налоги
</a>
<a class="btn btn-default" href="
    <?= $this->url('rb', ['action'=>'country']); ?>">
    Страны
</a>
<a class="btn btn-default" href="
    <?= $this->url('rb', ['action'=>'producer']); ?>">
    Производители
</a>
<a class="btn btn-default" href="
    <?= $this->url('currency', []); ?>">
    Валюты
</a>
</p>