<?php
$form = $this->form;
$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Наименование налога'
    ]);

$form->get('amount')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Размер в %',
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Добавить новый налог</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('amount')); ?>
            <?= $this->formElement($form->get('amount')); ?>
            <?= $this->formElementErrors($form->get('amount')); ?>                  
        </div>
                
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
