<?php

$form = $this->form;

$form->get('oeNumber')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('brandName')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'oem-submit']);

$form->prepare();

?>

            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title">Добавить оригинальный номер</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-10">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('oeNumber')); ?>
                            <?= $this->formElement($form->get('oeNumber')); ?>
                            <?= $this->formElementErrors($form->get('oeNumber')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('brandName')); ?>
                            <?= $this->formElement($form->get('brandName')); ?>
                            <?= $this->formElementErrors($form->get('brandName')); ?>                  
                        </div>

                    </div>        
                </div>
            </div>    
                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="oem-submit">Сохранить</button>
            </div>
                
            <?= $this->form()->closeTag(); ?>
            
<script>    
    $('#oem-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/oem/oem-form/<?= $good->getId() ?>?oem=<?= ($oem) ? $oem->getId():'';?>',
            data: $('#oem-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
                    window.location.reload();
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");

            });
    })    
</script>