<?php

$form = $this->form;

$form->get('oeNumber')->setAttributes([
    'class'=>'form-control', 
    'autofocus' => 'autofocus', // Добавляем фокус
    ]);

$form->get('brandName')->setAttributes([
    'class'=>'form-control',
    'onfocus' => "this.select();"
    ]);

$form->get('source')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('supplier')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'oem-submit']);

$form->prepare();

?>

            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title">Добавить оригинальный номер или номер поставщика</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-10">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('source')); ?>
                            <?= $this->formElement($form->get('source')); ?>
                            <?= $this->formElementErrors($form->get('source')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('supplier')); ?>
                            <?= $this->formElement($form->get('supplier')); ?>
                            <?= $this->formElementErrors($form->get('supplier')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('oeNumber')); ?>
                            <div>
                                <div class="btn-group" style="width: 100%">
                                    <?= $this->formElement($form->get('oeNumber')); ?>
                                    <span class="glyphicon glyphicon-remove-circle inputclear inputclear_oe_number"></span>
                                </div>                                    
                            </div>                            
                            <?= $this->formElementErrors($form->get('oeNumber')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('brandName')); ?>
                            <div>
                                <div class="btn-group" style="width: 100%">
                                    <?= $this->formElement($form->get('brandName')); ?>
                                    <span class="glyphicon glyphicon-remove-circle inputclear inputclear_brand_name"></span>
                                </div>                                    
                            </div>
                            <?= $this->formElementErrors($form->get('brandName')); ?>                  
                        </div>

                    </div>        
                </div>
            </div>    
                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="oem-submit">Сохранить</button>
            </div>
                
            <?= $this->form()->closeTag(); ?>
            
<script>    
    $(document).ready(function() {
        // Получаем значение из вашей функции
        var savedBrand = getOemBrandCookie(); 
        
        $('#oeNumber').focus();

        // Если значение есть, записываем его в поле
        if (savedBrand) {
            $('#brandName').val(savedBrand);
        }
                
        $(".inputclear_oe_number").click(function(){
            $("#oeNumber").val('');
        });        
        $(".inputclear_brand_name").click(function(){
            $("#brandName").val('');
        });        
    });
    
    $('#oem-submit').on('click', function() {
        
        var brandName = $('#brandName').val();
        setOemBrandCookie(brandName);
        
        $.ajax({
            type: 'POST',
            url: '/oem/oem-form/<?= $good->getId() ?>?oem=<?= ($oem) ? $oem->getId():'';?>',
            data: $('#oem-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
//                    window.location.reload();
                    if ( $( "#oemTable" ).length ) {
                        $('#oemTable').bootstrapTable('refresh');
                    } else {
                        $('#table').bootstrapTable('refresh');
                    }    
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");

            });
    })    
</script>