<?php
$this->headTitle('Оригинальные номера');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Оригинальные номера'=>$this->url('oem', ['action' => 'oem'])
            ]);

$this->headLink()
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
?>

<div class="row">
    <div class="col-md-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск по номеру (не менее 3-х символов)">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/oem/oem-content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric">ID</th>
                     <th data-field="oe" data-formatter="oemFormatter">Номер</th>
                     <th data-field="oeNumber">Полный номер</th>             
                     <th data-field="good" data-formatter="linkFormatter">Товар</th>            
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Всего номеров
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?= $total?>
                        </div>
                        <div class="pull-right">
                            <button value="/oem/delete-empty/" class="btn btn-warning btn-xs refresh-table-button"
                                    title="Удаление пустых">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var $table = $('#table'),
        $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function oemFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/oem/oem-view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function linkFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/goods/view/' + row.good.id + '" target="_blank">' + row.good.code + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function responseHandler(res) {
        return res;
    }    
</script>
