<?php
use Application\Entity\Oem;

$this->headTitle('Оригинальные номера');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Оригинальные номера'=>$this->url('oem', ['action' => 'oem'])
            ]); 
?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск по номеру (не менее 3-х символов)">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
                <select style="width: 200px" class="form-control" id='oemSourceSelect'>
                    <option value="null" selected>все источники</option>
                    <?php foreach (Oem::getSourceList() as $key => $value):?>
                        <option value="<?= $key?>"><?= $value?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/oem/oem-content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="oem.id" data-type="numeric">ID</th>
                     <th data-field="oem.oe">Номер</th>
                     <th data-field="oem.oeNumber">Полный номер</th>             
                     <th data-field="oem.brandName">Бренд</th>
                     <th data-field="goodId" data-formatter="linkFormatter">Товар</th>            
                     <th data-field="oem.intersectGoodId" data-formatter="intersectFormatter">Товар кросс</th>            
                    <th data-field="oem.source" data-formatter="sourceFormatter">Источник</th>
                    <th data-field="oem.status" data-formatter="statusFormatter">Статус</th>
                    <th data-field="oem.status" data-formatter="oemActiveFormatter"></th>
                 </tr>                
            </thead>
        </table>
    </div>
<!--    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Всего номеров
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            <?= $total?>
                        </div>
                        <div class="pull-right">
                            <button value="/goods/td-oem/" class="btn btn-info btn-xs refresh-button"
                                    title="Обновление OEM">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                            <button value="/oem/delete-empty/" class="btn btn-warning btn-xs refresh-button"
                                    title="Удаление пустых">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>-->
</div>    

<script type="text/javascript">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table'),
        ok = $('#ok');

    $(function () {
        ok.click(function () {
            table.bootstrapTable('refresh');
        });
        $('#oemSourceSelect').change(function (){
            $('#table').bootstrapTable('refresh');
        })
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    

        params.source = $('#oemSourceSelect').val();
        
        return params;
    }
    
    function oemFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/oem/oem-view/' + row.oem.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function linkFormatter(value, row){
        $.post(
            '/oem/display-good',
            {goodId: value},
            function(data){
                if (data.code){
                    $('#oem_good_'+row.oem.id).html(data.code);
                }            
            }
        );
        return [
            '<div class="pull-left">',
            '<a id="oem_good_'+row.oem.id+'" href="/goods/view/' + value + '" target="_blank"></a>',
            '</div>'
        ].join(''); 
    }    
    
    function intersectFormatter(value, row){
        if (value){
            $.post(
                '/oem/display-good',
                {goodId: value},
                function(data){
                    if (data.code){
                        $('#intersect_good_'+row.oem.id).html(data.code);
                    }            
                }
            );
            return [
                '<div class="pull-left">',
                '<a id="intersect_good_'+row.oem.id+'" href="/goods/view/' + value + '" target="_blank"></a>',
                '</div>'
            ].join(''); 
        }
        return '';
    }    
    
    function sourceFormatter(value){
        switch(value){
            <?php foreach ($oemSources as $key => $value):?>
                case "<?= $key?>": result="<?= $value?>"; break;      
            <?php endforeach;?>            
            default: result = 'Неизвестно'; break;
        }
        
        return result;
    }    
    
    function statusFormatter(value){
        switch(value){
            <?php foreach ($oemStatuses as $key => $value):?>
                case "<?= $key?>": result="<?= $value?>"; break;      
            <?php endforeach;?>            
            default: result = 'Неизвестно'; break;
        }
        
        return result;
    }        
    
    function oemActiveFormatter(value, row){
        if (value == 1){
            status = 2;
        } else {
            status = 1;
        }            
        var url = '/oem/oem-status-form/'+row.oem.id+'?status='+status;
        var btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Изменить доступность"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\', \'table\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        
        var editUrl = '/oem/oem-form/'+row.goodId+'?oem='+row.oem.id;
        var editBtn = '<button';
        if (row.oem.source != 3){
            editBtn += ' disabled="disabled"';
        }
        editBtn += ' type="button" data-toggle="modal" data-target="#modal-dialog"';
        editBtn += ' class="btn btn-default btn-xs"';
        editBtn += ' aria-label="Left Align"'; 
        editBtn += ' title="Изменить"'; 
        editBtn += ' value="'+editUrl+'">';
        editBtn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        editBtn += '</button>';
        return editBtn+' '+btn;
    }        
    
    function responseHandler(res) {
        return res;
    }    
</script>
