<?php
$this->headTitle('Налоги');

$this->mainMenu()->setActiveItemId('company');
$this->mainMenu()->setActiveUrl($this->url('tax'));
?>


<h1>Налог</h1>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
<a class="btn btn-default" href="<?= $this->url('tax', 
                    ['action'=>'edit', 'id'=>$tax->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Изменить
</a>
</p>
    
<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($tax->getId()) ?></th>
            </tr>
            <tr>
                <th>Наименование:</th>
                <td><?= $this->escapeHtml($tax->getName()) ?></th>
            </tr>
            <tr>
                <th>Размер:</th>
                <td><?= $this->escapeHtml($tax->getAmount()) ?></th>
            </tr>
            <tr>
                <th>Вид:</th>
                <td><?= $this->escapeHtml($tax->getKindAsString()) ?></th>
            </tr>
            <tr>
                <th>Дата:</th>
                <td><?= $this->escapeHtml($tax->getDateStart()) ?></th>
            </tr>
            <tr>
                <th>Статус:</th>
                <td><?= $this->escapeHtml($tax->getStatusAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>