<div class="jumbotron">
    <?php if($ok):?>
        <?= $this->partial('/bankapi/index/tochka-access-partial'); ?>
    <?php else: ?>
        <h1>Нет доступа!</h1>
        <p>Требуется пройти авторизацию</p>
        <p><a class="btn btn-primary btn-lg" href="<?= $this->url('bankapi', ['action' => 'tochka-auth'])?>" role="button">Авторизация</a>
        </p>        
    <?php endif; ?>    
</div>
