<?php if (isset($error)):?>
    <h1>В доступе отказано :(</h1>
    <p><?= $this->escapeHtml($error)?></p>
<?php else:?>
    <h1>Есть доступ!</h1>
    <p>Можно получать выписку, список счетов и делать платежки</p>
    <p>
        <a class="btn btn-primary btn-lg" href="<?= $this->url('bankapi', ['action' => 'tochka-statements'])?>" role="button">Получить выписку</a>
        <a class="btn btn-primary btn-lg" href="<?= $this->url('bankapi', ['action' => 'tochka-account-list'])?>" role="button">Список счетов</a>
    </p>
<?php endif;?>    
