<?php
use Zp\Entity\Personal;
use Zp\Entity\PersonalAccrual;
use Laminas\Json\Encoder;

$form = $this->form;

$form->get('docDate')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('docNum')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('company')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('amount')->setAttributes([
    'class'=>'form-control', 
    'data-inputmask' => "'alias': 'currency', 'groupSeparator': ''"
    ]);

$form->get('kind')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('user')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'personal-revise-submit']);

$form->prepare();

?>


<?= $this->form()->openTag($form); ?>
            
<div class="modal-header">
    <h5 class="modal-title" id="stModalLabel">Корректировка ЗП</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
            
<div class="modal-body">
    <div class="row">
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('docDate')); ?>
                <?= $this->formElement($form->get('docDate')); ?>
                <?= $this->formElementErrors($form->get('docDate')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('docNum')); ?>
                <?= $this->formElement($form->get('docNum')); ?>
                <?= $this->formElementErrors($form->get('docNum')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('company')); ?>
                <?= $this->formElement($form->get('company')); ?>
                <?= $this->formElementErrors($form->get('company')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('user')); ?>
                <?= $this->formElement($form->get('user')); ?>
                <?= $this->formElementErrors($form->get('user')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('kind')); ?>
                <?= $this->formElement($form->get('kind')); ?>
                <?= $this->formElementErrors($form->get('kind')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('amount')); ?>
                <?= $this->formElement($form->get('amount')); ?>
                <?= $this->formElementErrors($form->get('amount')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?= $this->formLabel($form->get('comment')); ?>
                <?= $this->formElement($form->get('comment')); ?>
                <?= $this->formElementErrors($form->get('comment')); ?>                  
            </div>                        
        </div>                                            
    </div>        

</div>

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary" id="personal-revise-submit">Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script>

    function submitForm(){
        var data = serializeForm('#personal-revise-form');
        $.ajax({
            type: 'POST',
            url: '/personal-revise/edit-form/<?= ($revise && !$copy) ? $revise->getId():"" ?>?company='+$('#companySelectForm').val()+'&user='+$('#userSelectForm').val(),
            data: $.param(data)
        })
            .done(function (data) {
//                console.log(data);
                if (data.result){
                    $('#personalReviseModal').modal('hide');
                    if ($('#table').length){
                        $('#table').bootstrapTable('refresh');
                    }    
                } else {
                    $('#personalReviseModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };
    
    $( document ).ready(function() {
        $("#amount").inputmask();
        
        var forms = $('#personal-revise-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('personal-revise-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });        
    });        
        
    function accrualResponseHandler(res) {
        return res;
    }         
</script>