<?php
use Zp\Entity\PersonalRevise;
use Zp\Entity\Accrual;
use Laminas\Json\Encoder;

$form = $this->form;

$form->get('docDate')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('docNum')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('company')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('amount')->setAttributes([
    'class'=>'form-control', 
    'data-inputmask' => "'alias': 'currency', 'groupSeparator': ''"
    ]);

$form->get('kind')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('user')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('vacationFrom')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('vacationTo')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('vacationPeriod')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('info')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'personal-revise-submit']);

$form->prepare();

?>


<?= $this->form()->openTag($form); ?>
            
<div class="modal-header">
    <h5 class="modal-title" id="stModalLabel">Корректировка ЗП</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
            
<div class="modal-body">
    <div class="row">
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('docDate')); ?>
                <?= $this->formElement($form->get('docDate')); ?>
                <?= $this->formElementErrors($form->get('docDate')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('docNum')); ?>
                <?= $this->formElement($form->get('docNum')); ?>
                <?= $this->formElementErrors($form->get('docNum')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('company')); ?>
                <?= $this->formElement($form->get('company')); ?>
                <?= $this->formElementErrors($form->get('company')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('user')); ?>
                <?= $this->formElement($form->get('user')); ?>
                <?= $this->formElementErrors($form->get('user')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('kind')); ?>
                <?= $this->formElement($form->get('kind')); ?>
                <?= $this->formElementErrors($form->get('kind')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('amount')); ?>
                <?= $this->formElement($form->get('amount')); ?>
                <?= $this->formElementErrors($form->get('amount')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row" id="vacation">
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('vacationFrom')); ?>
                <?= $this->formElement($form->get('vacationFrom')); ?>
                <?= $this->formElementErrors($form->get('vacationFrom')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('vacationTo')); ?>
                <?= $this->formElement($form->get('vacationTo')); ?>
                <?= $this->formElementErrors($form->get('vacationTo')); ?>                  
            </div>
        </div>    
        <div class="col-xs-4">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('vacationPeriod')); ?>
                <?= $this->formElement($form->get('vacationPeriod')); ?>
                <?= $this->formElementErrors($form->get('vacationPeriod')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?= $this->formLabel($form->get('comment')); ?>
                <?= $this->formElement($form->get('comment')); ?>
                <?= $this->formElementErrors($form->get('comment')); ?>                  
            </div>                        
        </div>                                            
    </div>        

</div>

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary" id="personal-revise-submit">Сохранить</button>
</div>

<?= $this->formElement($form->get('info')); ?>

<?= $this->form()->closeTag(); ?>
            
<script>

    function submitForm(){
        var data = serializeForm('#personal-revise-form');
        $.ajax({
            type: 'POST',
            url: '/personal-revise/edit-form/<?= ($revise && !$copy) ? $revise->getId():"" ?>?company='+$('#companySelectForm').val()+'&user='+$('#userSelectForm').val(),
            data: $.param(data)
        })
            .done(function (data) {
//                console.log(data);
                if (data.result){
                    $('#personalReviseModal').modal('hide');
                    if ($('#table').length){
                        $('#table').bootstrapTable('refresh');
                    }    
                } else {
                    $('#personalReviseModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };
    
    function showKind(){
        $('#vacation').hide();
        if ($("#kind").val() == <?= PersonalRevise::KIND_VACATION?>){
            $('#vacation').show();
            if ($('#info').val()){
                var info = JSON.parse($('#info').val());
                if (info){
                    if (info.vacation){
                        if (info.vacation.period){
                            $('#vacationPeriod').val(info.vacation.period);
                        }    
                    }    
                }    
            }
        }        
    }
    
    function vacation(){
        if ($('#companySelectForm').val() && $('#userSelectForm').val()){
            $.getJSON( '/personal-revise/vacation?company='+$('#companySelectForm').val()+'&user='+$('#userSelectForm').val()+'&from='+$('#vacationFrom').val()+'&to='+$('#vacationTo').val(), function( data ) {
                $('#vacationPeriod').val(data.period);
                $('#amount').val(data.amount);
                $('#info').val(JSON.stringify({vacation: data}));
            });                        
        }    
        return;
    }
    
    $( document ).ready(function() {
        
        showKind();
        
        $("#amount").inputmask();
        
        $('#kind').on('change', function(){
            showKind();
        });
        
        $('#vacationFrom').on('change', function(){
            if ($('#vacationFrom').val() > $('#vacationTo').val()){
                $('#vacationTo').val($('#vacationFrom').val());                
            }
            vacation();
        });
        
        $('#vacationTo').on('change', function(){
            if ($('#vacationFrom').val() > $('#vacationTo').val()){
                $('#vacationFrom').val($('#vacationTo').val());                
            }
            vacation();
        });
        
        $('#companySelectForm').on('change', function(){
            if ($("#kind").val() == <?= PersonalRevise::KIND_VACATION?>){
                vacation();
            }    
        });
        
        $('#userSelectForm').on('change', function(){
            if ($("#kind").val() == <?= PersonalRevise::KIND_VACATION?>){
                vacation();
            }    
        });
        
        var forms = $('#personal-revise-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('personal-revise-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });        
    });        
        
    function accrualResponseHandler(res) {
        return res;
    }         
</script>