<?php
use Zp\Entity\Accrual;

$form = $this->form;

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('aplId')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('basis')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('kind')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('payment')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'accrual-submit']);

$form->prepare();

?>


<?= $this->form()->openTag($form); ?>
            
<div class="modal-header">
    <h5 class="modal-title" id="stModalLabel">Вид начисления ЗП</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
            
<div class="modal-body">
    <div class="row">
        <div class="col-xs-12">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-6">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('payment')); ?>
                <?= $this->formElement($form->get('payment')); ?>
                <?= $this->formElementErrors($form->get('payment')); ?>                  
            </div>
        </div>    
        <div class="col-xs-6">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('basis')); ?>
                <?= $this->formElement($form->get('basis')); ?>
                <?= $this->formElementErrors($form->get('basis')); ?>                  
            </div>
        </div>    
    </div>        
    <div class="row">
        <div class="col-xs-6">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('kind')); ?>
                <?= $this->formElement($form->get('kind')); ?>
                <?= $this->formElementErrors($form->get('kind')); ?>                  
            </div>
        </div>    
        <div class="col-xs-3">
            
        </div>                        
        <div class="col-xs-3">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('aplId')); ?>
                <?= $this->formElement($form->get('aplId')); ?>
                <?= $this->formElementErrors($form->get('aplId')); ?>                  
            </div>
        </div>    
    </div>        
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?= $this->formLabel($form->get('comment')); ?>
                <?= $this->formElement($form->get('comment')); ?>
                <?= $this->formElementErrors($form->get('comment')); ?>                  
            </div>                        
        </div>                                            
    </div>        

</div>

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary" id="accrual-submit">Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script>
    function submitForm(){
        var data = serializeForm('#accrual-form');
        $.ajax({
            type: 'POST',
            url: '/accrual/edit-form/<?= ($accrual) ? $accrual->getId():"" ?>',
            data: $.param(data)
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#accrualModal').modal('hide');
                    if ($('#table').length){
                        $('#table').bootstrapTable('refresh');
                    }    
                } else {
                    $('#accrualModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };
    
    $( document ).ready(function() {
        
        var forms = $('#accrual-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('accrual-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });        
    });        
</script>