<?php
use Zp\Entity\Accrual;
use Laminas\Json\Encoder;

$this->headTitle('Виды начислений');

$this->mainMenu()->setActiveItemId('zp');
$this->mainMenu()->setActiveUrl($this->url('accrual'));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Виды начислений' => $this->url('accrual')
            ]);  

?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <button class="btn btn-default accrual-modal-show" type="button" modal-url="/accrual/edit-form">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </button>
                </div>    
            </div>
        </div>    
        <table id="table" 
            data-toggle="table" 
            data-url="/accrual/content"
            data-side-pagination="server"
            data-pagination="false" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-show-footer="false"
            data-row-style="rowStyle"
            data-classes = "table table-bordered table-hover table-condensed"
            >
            <thead>
                <tr>
                     <th data-field="id" data-sortable="true" data-align="right" data-width="10">Id</th>
                     <th data-field="aplId" data-sortable="false" data-align="right" data-width="10">Apl Id</th>
                     <th data-field="name" data-sortable="false" >Наименование</th>
                     <th data-field="basis" data-sortable="false" data-formatter="basisFormatter">База</th>
                     <th data-field="kind" data-sortable="false" data-formatter="kindFormatter">Способ расчета</th>
                     <th data-field="comment" data-sortable="false">Комментарий</th>
                     <th data-field="active" data-formatter="activeFormatter" data-width="5"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<?php echo $this->partial('/zp/index/zp-partial', []); ?>

<script type="text/javascript">
    var $table = $('#table');
        $ok = $('#ok');
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }
    

    $(function () {
        $ok.click(function () {
            refreshTable();
        });
        $table.on('load-success.bs.table', function (e, res) {
        });                
    });    
    
    function rowStyle(row){
        var retired = 'tablerow';

        if (row.status === '<?= Accrual::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        
        return {classes: retired};
    }
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function basisFormatter(value, row){
        var basises = <?= Encoder::encode(Accrual::getBasisList())?>;
        return basises[value];
    }    
    
    function kindFormatter(value, row){
        var basises = <?= Encoder::encode(Accrual::getKindList())?>;
        return basises[value];
    }    
    
    function activeFormatter(value, row){
        var url = '/accrual/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs accrual-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
        
    function responseHandler(res) {
        return res;
    }    
</script>
