<?php
$this->headTitle('Обучающая выборка для наименований товаров');

$this->mainMenu()->setActiveItemId('ml');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Машинное обучение'=>$this->url('ml'),
            'Обучающая выборка для наименований товаров'=>$this->url('ml', ['action'=>'ml-titles'])
            ]);

?>

<div class="row">
    <div class="col-md-9">

        <table class="table table-striped">
            <tr>
                <td colspan="5">
                    <?= $this->paginationControl($mlTitles,
                                'Sliding',
                                'application/partial/paginator', 
                                ['route' => array('route' => 'ml', 'action' => 'ml-titles')]); ?>

                </td>
            </tr>
            <?php foreach ($mlTitles as $mlTitle):?>
                <tr>
                    <td colspan="5">
                        <a href="<?= $this->url('rawprice', ['action' => 'view', 'id' => $mlTitle->getRawprice()->getId()])?>" target="_blank">
                            <small><?= $mlTitle->getRawprice()->getGoodname();?></small>
                        </a>
                    </td>
                </tr>
                <?php $tokens = $this->mlManager->rawpriceToMlTitle($mlTitle->getRawprice())?>
                <tr>
                    <?php foreach ($tokens as $token):?>
                        <td>
                            <?php if (is_array($token)):?>
                                <small><?= $token['bigram']->getBilemma()?></small>
                            <?php endif; ?>
                        </td>
                    <?php endforeach;?>
                </tr>
                <tr>
                    <?php foreach ($tokens as $token):?>
                        <td>
                            <?php if (is_array($token)):?>
                            <small><?= $token['pwt'] ?></small> 
                            <small><?= $token['token1']->getFrequency(); ?></small> 
                            <small><?= $token['token2']->getFrequency(); ?></small> 
                            <small><?= $token['bigram']->getFrequency(); ?></small>
                            <?php endif; ?>
                        </td>
                    <?php endforeach;?>
                </tr>
            <?php endforeach;?>        
            <tr>
                <td colspan="5">
                    <?= $this->paginationControl($mlTitles,
                                'Sliding',
                                'application/partial/paginator', 
                                ['route' => array('route' => 'ml', 'action' => 'ml-titles')]); ?>

                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                        </div>
                        <div class="pull-right">
                            <button value="/ml/fill-ml-titles" class="btn btn-info btn-xs refresh-button">
                                Обновить
                            </button> 
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                        </div>
                        <div class="pull-right">
                            <button value="/ml/ml-titles-to-csv" class="btn btn-info btn-xs refresh-button">
                                Выгрузить
                            </button> 
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                        </div>
                        <div class="pull-right">
<!--                            <button value="/ml/ml-title-predict" class="btn btn-info btn-xs refresh-button">
                                Обучить
                            </button> -->
                        </div>
                    </div>
                    <div class="panel-body">
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.statusMlTitle').on('change', function(e, node) {
        var url = "/ml/update-ml-title-status/";

        if (url){
            $.ajax({
                type: 'POST',
                url: url,
                data: {pk: e.target.name, value: e.target.value}
            })
                .done(function (data) {
                })
                .fail(function () {
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })            
</script>

