<?php
$this->headTitle('Обучающая выборка для наименований товаров');

$this->mainMenu()->setActiveItemId('ml');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Машинное обучение'=>$this->url('ml'),
            'Обучающая выборка для наименований товаров'=>$this->url('ml', ['action'=>'ml-titles'])
            ]);

?>

<div class="row">
    <div class="col-md-9">

        <table class="table table-striped">
            <tr>
                <td colspan="13">
                    <?= $this->paginationControl($mlTitles,
                                'Sliding',
                                'application/partial/paginator', 
                                ['route' => array('route' => 'ml', 'action' => 'ml-titles')]); ?>

                </td>
            </tr>
            <tr>
                <th>
                    Гр
                </th>
                <th>
                    RU
                </th>
                <th>
                    ru
                </th>
                <th>
                    ru1
                </th>
                <th>
                    ruA
                </th>
                <th>
                    EN
                </th>
                <th>
                    en
                </th>
                <th>
                    en1
                </th>
                <th>
                    enA
                </th>
                <th>
                    N
                </th>                    
                <th>
                    A
                </th>                    
                <th>
                    Наименование
                </th>           
                <th>
                    Оценка
                </th>                    
            </tr>
            <?php foreach ($mlTitles as $mlTitle):?>
                <tr>
                    <?php $frequencies = $this->mlManager->strMeanFrequency($mlTitle->getRawprice()->getTitle(), $mlTitle->getRawprice()->getArticle())?>
                    <td>
                        <?= $this->mlManager->tokenGroupMeanFrequency($mlTitle->getRawprice()->getGood()->getTokenGroup())?>
                    </td>
                    <td>
                        <?= $frequencies[\Application\Entity\Token::IS_DICT]?>
                    </td>
                    <td>
                        <?= $frequencies[\Application\Entity\Token::IS_RU]?>
                    </td>
                    <td>
                        <?= $frequencies[\Application\Entity\Token::IS_RU_1]?>
                    </td>
                    <td>
                        <?= $frequencies[\Application\Entity\Token::IS_RU_ABBR]?>
                    </td>
                    <td>
                        <?= $frequencies[\Application\Entity\Token::IS_EN_DICT]?>
                    </td>
                    <td>
                        <?= $frequencies[\Application\Entity\Token::IS_EN]?>
                    </td>
                    <td>
                        <?= $frequencies[\Application\Entity\Token::IS_EN_1]?>
                    </td>
                    <td>
                        <?= $frequencies[\Application\Entity\Token::IS_EN_ABBR]?>
                    </td>
                    <td>
                        <?= $frequencies[\Application\Entity\Token::IS_NUMERIC]?>
                    </td>
                    <td>
                        <?= $frequencies[\Application\Entity\Token::IS_ARTICLE]?>
                    </td>
                    <td>
                        <a href="<?= $this->url('rawprice', ['action' => 'view', 'id' => $mlTitle->getRawprice()->getId()])?>" target="_blank">
                            <small><?= $mlTitle->getRawprice()->getGoodname();?></small>
                        </a>
                    </td>
                    <td>
                        <input type="radio" name="status_<?= $mlTitle->getId()?>" value="<?= Application\Entity\MlTitle::STATUS_BAD?>"><?= Application\Entity\MlTitle::STATUS_BAD?><br>
                        <input type="radio" name="status_<?= $mlTitle->getId()?>" value="<?= Application\Entity\MlTitle::STATUS_MID?>"><?= Application\Entity\MlTitle::STATUS_MID?><br>
                        <input type="radio" name="status_<?= $mlTitle->getId()?>" value="<?= Application\Entity\MlTitle::STATUS_EX?>"><?= Application\Entity\MlTitle::STATUS_EX?><br>
                    </td>
                </tr>
            <?php endforeach;?>        
            <tr>
                <td colspan="13">
                    <?= $this->paginationControl($mlTitles,
                                'Sliding',
                                'application/partial/paginator', 
                                ['route' => array('route' => 'ml', 'action' => 'ml-titles')]); ?>

                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                        </div>
                        <div class="pull-right">
                            <button value="/ml/fill-ml-titles" class="btn btn-info btn-xs refresh-button">
                                Обновить
                            </button> 
                        </div>
                    </div>
                    <div class="panel-body">
                    </div>
                    <div class="panel-body">
                    </div>
                    <div class="panel-body">
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>

