<?php
$this->headTitle('Обучающая выборка для наименований товаров');

$this->mainMenu()->setActiveItemId('ml');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Машинное обучение'=>$this->url('ml'),
            'Обучающая выборка для наименований товаров'=>$this->url('ml', ['action'=>'ml-titles'])
            ]);

?>

<h1>
Обучающая выборка для наименований товаров
</h1>

<div class="row">
    <div class="col-md-9">

        <table class="table table-striped">
            <tr>
                <td colspan="6">
                    <?= $this->paginationControl($goods,
                                'Sliding',
                                'application/partial/paginator', 
                                ['route' => array('route' => 'ml', 'action' => 'ml-titles')]); ?>

                </td>
            </tr>
            <?php foreach ($goods as $good):?>
                <tr>
                    <td colspan="6">
                        <h3><?= $good->getCode()?> <?= $good->getProducer()->getName()?> </h3>
                        <div>
                            <small>
                                <?= $good->getTokenGroup()->getLemms()?>
                            </small>                            
                        </div>
                        <div>
                            <small>
                                <?= $good->getTokenGroup()->getName()?>
                            </small>                            
                        </div>
                    </td>
                </tr>
                <?php foreach ($good->getArticles() as $article):?>
                    <?php foreach ($article->getRawprice() as $rawprice):?>
                        <?php 
                            if ($rawprice->getStatus() != $rawprice::STATUS_PARSED) continue;
                        ?>
                        <tr style="font-size: <?= ($rawprice->getStatus() == $rawprice::STATUS_PARSED) ? "inherit":"xx-small"?>">
                            <td>
                                <a href="<?= $this->url('rawprice', ['action' => 'view', 'id' => $rawprice->getId()]);?>">
                                    <?= $rawprice->getGoodname();?>
                                </a>    
<!--                                <div>
                                    <?php $tokens = $mlManager->tokenize($rawprice->getGoodname()) ?>
                                    <?php foreach($tokens as $mlToken):?>
                                        <?php foreach ($mlToken as $value):?>
                                            <small>[<?= $value?>]</small>
                                        <?php endforeach;?>
                                        <br/>
                                    <?php endforeach;?>
                                </div>-->
                            </td>
                        </tr>
                    <?php endforeach;?>        
                <?php endforeach;?>        
            <?php endforeach;?>        
            <tr>
                <td colspan="6">
                    <?= $this->paginationControl($goods,
                                'Sliding',
                                'application/partial/paginator', 
                                ['route' => array('route' => 'ml', 'action' => 'ml-titles')]); ?>

                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                        </div>
                        <div class="pull-right">
                            <button value="/ml/fill-ml-titles" class="btn btn-info btn-xs refresh-button">
                                Обновить
                            </button> 
                        </div>
                    </div>
                    <div class="panel-body">
                    </div>
                    <div class="panel-body">
                    </div>
                    <div class="panel-body">
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>

