<?php
$this->headTitle('Строка '.$rawprice->getId().' '.$rawprice->getRaw()->getSupplier()->getName().' прайс '. $rawprice->getRaw()->getBasename());
  
$this->mainMenu()->setActiveItemId('raw');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Прайсы'=>$this->url('raw'),
            $rawprice->getRaw()->getBasename() => $this->url('raw', ['action'=>'view', 'id' => $rawprice->getRaw()->getId()]),
            'Строка прайса' => $this->url('rawprice', ['action'=>'view', 'id' => $rawprice->getId()]),
            ]);  

$this->headLink()
    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css')
        ;

$this->headScript()
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js')
    //->appendFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/i18n/defaults-*.min.js')
        ;
        
$form = $this->form;        
$form->prepare();        
?>

<h1>
    <?= $this->escapeHtml('Строка '.$rawprice->getId().' '.$rawprice->getRaw()->getSupplier()->getName().' прайс '. $rawprice->getRaw()->getBasename()); ?>    
</h1>


<div class="row">
    <div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Сопоставление данных из строки прайса</h3>
        </div>
        <div class="panel-body">
            <?= $this->form()->openTag($form); ?>
                
                <table class="table table-striped">
                    <tr>
                        <th colspan="2" width="50%"> Данные из строки прайса
                        <th colspan="2"width="50%"> Соответствие колонок
                    </tr>
                    <tr>
                        <th width="5%">Колонка</th>
                        <th width="45%">Значение</th>
                        <th width="25%">Соответствие</th>
                        <th width="25%"></th>
                    </tr>
                    <?php 
                        $rawdates = $rawprice->getRawdataAsArray();
                    ?>
                    <?php foreach ($rawdates as $col => $rawdata): ?>
                        <tr>
                            <td>
                                <?= $this->escapeHtml($col + 1); ?>
                            </td>
                            <td>
                                <?= $this->escapeHtml($rawdata); ?>
                            </td>
                            <td>
                                <?php echo $this->partial('application/supplier/price-setting-select', ['col' => $col + 1,'data' => $priceSetting->getField($col + 1), 'options'=>$priceSettingOptions]); ?>
                            </td>
                            <?php if ($col == 0):?>
                                <td rowspan="<?= count($rawdates)?>">
                                    <div id="price-setting-alert">
                                        
                                    </div>
                                </td>
                            <?php endif; ?>    
                        </tr>
                    <?php endforeach; ?>    

                    <tr>
                        <td></td>
                        <td></td>
                        <td>
                            <button type="button" class="btn btn-success refresh-button" id="price-setting-submit">
                               Сохранить
                            </button>                        
                        </td>
                        <td></td>
                    </tr>    
                </table>
            <?= $this->formElement($form->get('csrf')); ?>   
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>    
</div>

<a class="btn btn-default" href="
    <?= $this->url('rawprice', ['action'=>'parse', 'id' => $rawprice->getId()]); ?>">
    1.Парсить
</a>
<?php if ($rawprice->getProducer()): ?>
    <a class="btn btn-default" href="
        <?= $this->url('rawprice', ['action'=>'unknown-producer', 'id' => $rawprice->getId()]); ?>">
        2.Производитель
    </a>
    <?php if ($rawprice->getUnknownProducer() && $rawprice->getUnknownProducer()->getProducer() && $rawprice->getGoodname()): ?>
        <a class="btn btn-default" href="
            <?= $this->url('rawprice', ['action'=>'good', 'id' => $rawprice->getId()]); ?>">
            3.Товар
        </a>
    <? endif; ?>
    <?php if ($rawprice->getGood()): ?>
        <a class="btn btn-default" href="
            <?= $this->url('rawprice', ['action'=>'price', 'id' => $rawprice->getId()]); ?>">
            4.Цена
        </a>
    <? endif; ?>
<? endif; ?>
<h3 class="contact-header">Прочитанные данные</h3>
<table class="table table-striped">

   <tr>
        <th>Поле</th>
        <th>Значение</th>
    </tr>
    <tr>
        <td>
            Артикул
        </td>
        <td>
            <?= $this->escapeHtml($rawprice->getArticle()) ?>
        </td>
    <tr>
        <td>
            Производитель
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getProducer()) ?>
        </td>
    </tr>    
    <tr>
        <td>
            Наименование
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getGoodname()) ?>
        </td>
    </tr>
    <tr>
        <td>
            Цена
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getPrice()) ?>
        </td>
    </tr>
    <tr>
        <td>
            Остаток
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getRest()) ?>
        </td>
    </tr>
</table>

<script>
    $('#price-setting-submit').on('click', function(e){
        $('#price-setting-alert').html('');
       var  data = $('#price-setting-form').serialize();
        $.ajax({
            type: 'POST',
            url: '/supplier/price-setting-form/<?=$rawprice->getRaw()->getSupplier()->getId()?>?priceSetting=<?= ($priceSetting ? $priceSetting->getId():'') ?>',
            data: data
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#price-setting-alert').html('<div class="alert alert-success" role="alert">Ок!</div>');
                    //window.location.reload();
                } else {
                    if (jQuery.isPlainObject(data)){
                        $.each(data, function(key, value){
                            var msg = '<div class="alert alert-warning" role="alert"><strong>'+key+'</strong>';
                            $.each(value, function(err, errvalue){
                                msg +='<div>'+errvalue+'</div>'
                            });    
                            msg += '</div>';
                            $('#price-setting-alert').append(msg);
                        });
                    }
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });       
    });
</script>
    