<?php
$this->headTitle('Строка '.$rawprice->getId().' '.$rawprice->getRaw()->getSupplier()->getName().' прайс '. $rawprice->getRaw()->getFilename());
  
?>

<a href="
    <?= $this->url('raw', ['action' => 'view', 'id' => $rawprice->getRaw()->getId()]); ?>">
    &lt;&lt; Назад в <?= $rawprice->getRaw()->getFilename() ?>
</a>

<h1>
    <?= $this->escapeHtml('Строка '.$rawprice->getId().' '.$rawprice->getRaw()->getSupplier()->getName().' прайс '. $rawprice->getRaw()->getFilename()); ?>    
</h1>


<h3 class="contact-header">Данные из строки прайса</h3>
<p>
    <?php 
        $rawdates = $rawprice->getRawdataAsArray();
    ?>
    <ol>
        <?php foreach ($rawdates as $rawdata): ?>
            <li>
                <?= $this->escapeHtml($rawdata); ?>
            </li>
        <?php endforeach; ?>    
    </ol>
</p>

<a class="btn btn-default" href="
    <?= $this->url('rawprice', ['action'=>'parse', 'id' => $rawprice->getId()]); ?>">
    1.Парсить
</a>
<?php if ($rawprice->getProducer()): ?>
    <a class="btn btn-default" href="
        <?= $this->url('rawprice', ['action'=>'unknown-producer', 'id' => $rawprice->getId()]); ?>">
        2.Производитель
    </a>
    <?php if ($rawprice->getUnknownProducer() && $rawprice->getUnknownProducer()->getProducer() && $rawprice->getGoodname()): ?>
        <a class="btn btn-default" href="
            <?= $this->url('rawprice', ['action'=>'good', 'id' => $rawprice->getId()]); ?>">
            3.Товар
        </a>
    <? endif; ?>
<? endif; ?>
<h3 class="contact-header">Прочитанные данные</h3>
<table class="table table-striped">

   <tr>
        <th>Поле</th>
        <th>Значение</th>
    </tr>
    <tr>
        <td>
            Артикул
        </td>
        <td>
            <?= $this->escapeHtml($rawprice->getArticle()) ?>
        </td>
    <tr>
        <td>
            Производитель
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getProducer()) ?>
        </td>
    </tr>    
    <tr>
        <td>
            Наименование
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getGoodname()) ?>
        </td>
    </tr>
    <tr>
        <td>
            Цена
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getPrice()) ?>
        </td>
    </tr>
    <tr>
        <td>
            Остаток
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getRest()) ?>
        </td>
    </tr>
</table>
