<?php
$this->headTitle('Строка '.$rawprice->getId().' '.$rawprice->getRaw()->getSupplier()->getName().' прайс '. $rawprice->getRaw()->getBasename());
  
$this->mainMenu()->setActiveItemId('raw');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Прайсы'=>$this->url('raw'),
            $rawprice->getRaw()->getBasename() => $this->url('raw', ['action'=>'view', 'id' => $rawprice->getRaw()->getId()]),
            'Строка прайса' => $this->url('rawprice', ['action'=>'view', 'id' => $rawprice->getId()]),
            ]);  
        ;
        
?>

<h1>
    <?= $this->escapeHtml('Строка '.$rawprice->getId().' '.$rawprice->getRaw()->getSupplier()->getName().' прайс '. $rawprice->getRaw()->getBasename()); ?>    
</h1>


<div class="row">
    <div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Сопоставление данных из строки прайса</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped">
                <tr>
                    <th colspan="<?= count($rawprice->getRaw()->getSupplier()->getPriceDescriptions()) + 2;?>" width="50%"> 
                        <div class="pull-left">
                            Данные из строки прайса                            
                        </div>
                        <div class="pull-right">
                            <button value="/supplier/price-description-form/<?= $rawprice->getRaw()->getSupplier()->getId() ?>" class="btn btn-default btn-xs"
                                    data-toggle="modal" data-target="#modal-dialog" title="Добавить описание полей">
                                    Добавить описание полей
                                <span class="glyphicon glyphicon-plus" ></span>
                            </button>                                                                        
                        </div>                            
                    </th>    
                </tr>
                <tr>
                    <th width="5%">Колонка</th>
                    <th>Значение</th>
                    <?php foreach($rawprice->getRaw()->getSupplier()->getPriceDescriptions() as $priceDescription):?>
                        <th>
                            <div class="pull-left">
                                <?= $this->escapeHtml($priceDescription->getName());?>
                            </div>    
                            <button value="/supplier/price-description-form/<?= $priceDescription->getSupplier()->getId() ?>?priceDescription=<?= $priceDescription->getId() ?>" class="btn btn-default btn-xs"
                                    data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                <span class="glyphicon glyphicon-edit" ></span>
                            </button>                                                    
                            <button value="/supplier/delete-price-description-form/<?= $priceDescription->getId() ?>" class="btn btn-default btn-xs this-delete"
                                    title="Удалить">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </button>                                                                                                                                       
                        </th>
                    <?php endforeach;?>
                </tr>
                <?php 
                    $rawdates = $rawprice->getRawdataAsArray();
                ?>
                <?php foreach ($rawdates as $col => $rawdata): ?>
                    <tr>
                        <td>
                            <?= $this->escapeHtml($col + 1); ?>
                        </td>
                        <td>
                            <?= $this->escapeHtml($rawdata); ?>
                        </td>
                        <?php foreach($rawprice->getRaw()->getSupplier()->getPriceDescriptions() as $priceDescription):?>
                            <td>
                                <?= $this->escapeHtml($priceDescription->getFieldLabel($col + 1));?>
                            </td>
                        <?php endforeach;?>
                    </tr>
                <?php endforeach; ?>    

            </table>
        </div>
    </div>    
</div>    