<?php
$this->headTitle('Файлы с картинками к загрузке');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Товары'=>$this->url('goods'),
            'Очередь файлов с картинками' => $this->url('image')
            ]);  

?>

<h1>Очередь файлов с картинками</h1>
<div class="row">
    <div class="col-sm-9">
        <div class="panel-group">
            <?php if (count($files)): ?>
                <?php foreach($files as $fileInfo):?>
                    <?php if (file_exists($fileInfo->getPathname())):?>
                    <div class="thumbnail">
                        <?php if ($imageManager->isImageFile($fileInfo->getFileName())): ?>
                            <a href="<?= $imageManager->publicPath($fileInfo->getPathname()) ?>" target="_blank">
                                <img src="<?= $imageManager->publicPath($fileInfo->getPathname()) ?>" class="img-thumbnail" alt="<?= $fileInfo->getFileName() ?>">
                            </a>
                        <?php endif;?>
                        <div class="caption panel-body small">
                            <div class="pull-left">
                                <?= $fileInfo->getFileName() ?>
                            </div>
                            <div class="pull-right">
                                <?php if ($imageManager->isImageFile($fileInfo->getFileName())): ?>
                                    <button value="/image/upload-tmp-file/?file=<?= $fileInfo->getPathname() ?>" class="btn btn-default btn-xs refresh-button"
                                            title="Привязать картинку к товару">
                                        <span class="glyphicon glyphicon-import" ></span>
                                    </button>                             
                                <?php endif;?>
                                <?php if ($imageManager->isCompressFile($fileInfo->getPathName())): ?>
                                    <button value="/image/decompress-tmp-file/?file=<?= $fileInfo->getPathname() ?>" class="btn btn-default btn-xs refresh-button"
                                            title="Распаковать">
                                        <span class="glyphicon glyphicon-compressed" ></span>
                                    </button>                             
                                <?php endif;?>
                                <button value="/image/delete-tmp-file/?file=<?= $fileInfo->getPathname() ?>" class="btn btn-warning btn-xs this-delete"
                                        title="Удалить">
                                    <span class="glyphicon glyphicon-remove" ></span>
                                </button>                             
                            </div>                                                                            
                        </div>                    
                    </div>
                    <?php endif;?>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Загрузить
                    </div>
                    <div class="panel-body">
                        <button value="/image/check-mail" class="btn btn-default btn-xs refresh-button"
                                title="Проверить ящик для картинок">
                            <span class="glyphicon glyphicon-envelope" ></span>
                        </button>                             
                        <button value="/image/upload-tmp-image-form" class="btn btn-default btn-xs"
                                data-toggle="modal" data-target="#modal-dialog" title="Добавить картинку">
                            <span class="glyphicon glyphicon-export" ></span>
                        </button>                            
                        <button value="/image/upload-tmp-files" class="btn btn-default btn-xs refresh-button"
                                title="Привязать картинки к товарам">
                            <span class="glyphicon glyphicon-import" ></span>
                        </button>                             
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>