<?php
$this->headTitle('Файлы с картинками к загрузке');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Товары'=>$this->url('goods'),
            'Очередь файлов с картинками' => $this->url('image')
            ]);  

?>

<h1>Очередь файлов с картинками</h1>
<div class="row">
    <div class="col-sm-9">
        <div class="panel-group">
            <?php if (count($files)): ?>
                <?php foreach($files as $fileInfo):?>
                    <div class="thumbnail">                        
                        <a href="<?= $tmpDir.'/'.$fileInfo->getFileName() ?>" target="_blank">
                            <img src="<?= $tmpDir.'/'.$fileInfo->getFileName() ?>" class="img-thumbnail" alt="<?= $fileInfo->getFileName() ?>">
                        </a>    
                        <div class="caption panel-body small">
                            <div class="pull-left">
                                <?= $fileInfo->getFileName() ?>
                            </div>
                            <div class="pull-right">
                                <button value="/image/upload-tmp-file/?file=<?= $fileInfo->getFileName() ?>" class="btn btn-default btn-xs refresh-button"
                                        title="Привязать картинку к товару">
                                    <span class="glyphicon glyphicon-import" ></span>
                                </button>                             
                                <button value="/image/delete-tmp-file/?file=<?= $fileInfo->getFileName() ?>" class="btn btn-warning btn-xs this-delete"
                                        title="Удалить">
                                    <span class="glyphicon glyphicon-remove" ></span>
                                </button>                             
                            </div>                                                                            
                        </div>                    
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Загрузить
                    </div>
                    <div class="panel-body">
                        <button value="/image/check-mail" class="btn btn-info btn-xs refresh-button"
                                title="Проверить ящик для картинок">
                            <span class="glyphicon glyphicon-envelope" ></span>
                        </button>                             
                        <button value="/image/upload-tmp-files" class="btn btn-default btn-xs refresh-button"
                                title="Привязать картинки к товарам">
                            <span class="glyphicon glyphicon-import" ></span>
                        </button>                             
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>