<?php
$this->headTitle('Настройки доступа к Ai');

$this->mainMenu()->setActiveItemId('settings');
$this->mainMenu()->setActiveUrl($this->url('admin', ['action' => 'ai-settings']));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Настройки доступа к ИИ'=>$this->url('settings', ['action' => 'ai-settings']),
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$form = $this->form;

$form->get('gigachat_client_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('gigachat_client_secret')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('gigachat_score')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('deepseek_api_key')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<div class="row">
    <div class="col-xs-12">
        <button class="btn btn-default test-button" value="/ai/gigachat-models">
            <span class="glyphicon glyphicon-tag" ></span> Gigachat Models
        </button>                
        <button class="btn btn-default test-button" value="/ai/gigachat-test">
            <span class="glyphicon glyphicon-tag" ></span> Gigachat Test
        </button>                
        <button class="btn btn-default test-button" value="/ai/deepseek-test">
            <span class="glyphicon glyphicon-tag" ></span> Deepseek Test
        </button>                
    </div>
</div>

<h1>Настройки подключения к ИИ</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-5">
        
        <div class="form-group">
            <?= $this->formLabel($form->get('gigachat_client_id')); ?>
            <?= $this->formElement($form->get('gigachat_client_id')); ?>
            <?= $this->formElementErrors($form->get('gigachat_client_id')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('gigachat_client_secret')); ?>
            <?= $this->formElement($form->get('gigachat_client_secret')); ?>
            <?= $this->formElementErrors($form->get('gigachat_client_secret')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('gigachat_score')); ?>
            <?= $this->formElement($form->get('gigachat_score')); ?>
            <?= $this->formElementErrors($form->get('gigachat_score')); ?>                  
        </div>
                        
        <?= $this->formElement($form->get('submit')); ?>
    </div>   
    <div class="col-md-5">
        <div class="form-group">
            <?= $this->formLabel($form->get('deepseek_api_key')); ?>
            <?= $this->formElement($form->get('deepseek_api_key')); ?>
            <?= $this->formElementErrors($form->get('deepseek_api_key')); ?>                  
        </div>
    </div>
<!--    <div class="col-md-2" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active">
                <?= $this->formElement($form->get('submit')); ?>
            </li>
        </ul>
    </div>    -->
    
</div>   

<?= $this->form()->closeTag(); ?>

<script async="false">
    $('.test-button').on('click', function(e) {
        var url = $(this).attr('value');
//        console.log(url);
        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: true
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    console.log(data);
                    if (data){
                        var message = '';
                        if (data.result){
                            if (data.result.message){
                                message = data.result.message;
                            }
                        }
                        if (data.Data){
                            if (data.Data.webhooksList){
                                message = data.Data.webhooksList.join(', ');
                            }
                            if (data.Data.result){
                                message = data.Data.result;
                            }
                        }
                        bootbox.alert(message);
                    } else {
                        bootbox.alert("Не удалось отправить сообщение!");
                    }    
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    });
</script>