<?php
$form = $this->form;

$form->get('get_producer_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('get_good_id')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Настройки обмена с АПЛ</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">

<div class="row">
    <div class="col-md-12">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('get_producer_id')); ?>
            <?= $this->formElement($form->get('get_producer_id')); ?>
            <?= $this->formElementErrors($form->get('get_producer_id')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('get_good_id')); ?>
            <?= $this->formElement($form->get('get_good_id')); ?>
            <?= $this->formElementErrors($form->get('get_good_id')); ?>                  
        </div>
                        
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            <button type="button" class="btn btn-primary" id="apl-exchange-settings-submit">Загрузить</button>
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>    

<script type="text/javascript">
    $('#apl-exchange-settings-submit').on('click', function() {
        var dialog = bootbox.dialog({
            message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите ...</p>',
            closeButton: false
        });
        
        var file_data = $('#file').prop('files')[0];   
        var form_data = new FormData();                  
        form_data.append('name', file_data);

        $.ajax({
            type: 'POST',
            url: '/admin/apl-exchange-settings-form',
            contentType: false,
            processData: false,
            data: form_data
        })
            .done(function (data) {
                dialog.modal('hide');
                if (data == 'ok'){
                    window.location.reload();
                } else {
                }    
            })
            .fail(function () {
                dialog.modal('hide');
                bootbox.alert("Произошла ошибка при выполнении операции.");
            });
    })    
</script>