<?php
$this->headTitle('Настройки обмена с АПЛ');

$this->mainMenu()->setActiveItemId('');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Настройки обмена с АПЛ'=>$this->url('settings', ['action' => 'apl-exchange-settings']),
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$form = $this->form;

$form->get('apl_secret_key')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'пароль api АПЛ',
    ]);


$form->get('get_acquiring')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('get_producer_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('get_car_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('get_good_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('get_group_apl')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('rawprice')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('image')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('group')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('oem')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('attribute')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('car')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('good_name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('good_price')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Настройки обмена с АПЛ</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-5">
        
        <div class="form-group">
            <?= $this->formLabel($form->get('apl_secret_key')); ?>
            <?= $this->formElement($form->get('apl_secret_key')); ?>
            <?= $this->formElementErrors($form->get('apl_secret_key')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('get_acquiring')); ?>
            <?= $this->formElement($form->get('get_acquiring')); ?>
            <?= $this->formElementErrors($form->get('get_acquiring')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('get_producer_id')); ?>
            <?= $this->formElement($form->get('get_producer_id')); ?>
            <?= $this->formElementErrors($form->get('get_producer_id')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('get_good_id')); ?>
            <?= $this->formElement($form->get('get_good_id')); ?>
            <?= $this->formElementErrors($form->get('get_good_id')); ?>                  
        </div>
                        
<!--        <div class="form-group">
            <?= $this->formLabel($form->get('get_group_apl')); ?>
            <?= $this->formElement($form->get('get_group_apl')); ?>
            <?= $this->formElementErrors($form->get('get_group_apl')); ?>                  
        </div>-->
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('get_car_id')); ?>
            <?= $this->formElement($form->get('get_car_id')); ?>
            <?= $this->formElementErrors($form->get('get_car_id')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('rawprice')); ?>
            <?= $this->formElement($form->get('rawprice')); ?>
            <?= $this->formElementErrors($form->get('rawprice')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('oem')); ?>
            <?= $this->formElement($form->get('oem')); ?>
            <?= $this->formElementErrors($form->get('oem')); ?>                  
        </div>
    </div>   
    <div class="col-md-5">
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('image')); ?>
            <?= $this->formElement($form->get('image')); ?>
            <?= $this->formElementErrors($form->get('image')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('group')); ?>
            <?= $this->formElement($form->get('group')); ?>
            <?= $this->formElementErrors($form->get('group')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('car')); ?>
            <?= $this->formElement($form->get('car')); ?>
            <?= $this->formElementErrors($form->get('car')); ?>                  
        </div>
    
        <div class="form-group">
            <?= $this->formLabel($form->get('attribute')); ?>
            <?= $this->formElement($form->get('attribute')); ?>
            <?= $this->formElementErrors($form->get('attribute')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('good_name')); ?>
            <?= $this->formElement($form->get('good_name')); ?>
            <?= $this->formElementErrors($form->get('good_name')); ?>                  
        </div>
    
        <div class="form-group">
            <?= $this->formLabel($form->get('good_price')); ?>
            <?= $this->formElement($form->get('good_price')); ?>
            <?= $this->formElementErrors($form->get('good_price')); ?>                  
        </div>

    </div>
    <div class="col-md-2" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active">
                <?= $this->formElement($form->get('submit')); ?>
            </li>
            <li>
                <a href="javascript:void(0)" onclick="offSelect(2)" class=""
                        title="Отключить все">
                    Отключить все
                </a>
                <a href="javascript:void(0)" onclick="offSelect(1)" class=""
                        title="Отключить все">
                    Включить все
                </a>
            </li>
        </ul>
    </div>    
    
</div>   

<?= $this->form()->closeTag(); ?>
<script type="text/javascript">
    function offSelect(flag){
        $("select").each(function(){
            $(this).val(flag);
        })
    }            
</script>