<?php
$this->headTitle('Настройки обмена с банком');

$this->mainMenu()->setActiveItemId('settings');
$this->mainMenu()->setActiveUrl($this->url('settings', ['action' => 'bank-settings']));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Настройки обмена с банком'=>$this->url('settings', ['action' => 'bank-settings']),
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$form = $this->form;

$form->get('statement_by_api')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('statement_by_file')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('doc_by_api')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('statement_email')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('statement_email_password')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('statement_app_password')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Настройки обмена с банком</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-5">
        
        <div class="form-group">
            <?= $this->formLabel($form->get('statement_by_api')); ?>
            <?= $this->formElement($form->get('statement_by_api')); ?>
            <?= $this->formElementErrors($form->get('statement_by_api')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('statement_by_file')); ?>
            <?= $this->formElement($form->get('statement_by_file')); ?>
            <?= $this->formElementErrors($form->get('statement_by_file')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('doc_by_api')); ?>
            <?= $this->formElement($form->get('doc_by_api')); ?>
            <?= $this->formElementErrors($form->get('doc_by_api')); ?>                  
        </div>        

    </div>   
    <div class="col-md-5">
        <div class="form-group">
            <?= $this->formLabel($form->get('statement_email')); ?>
            <div class="input-group">
                <?= $this->formElement($form->get('statement_email')); ?>
                <span class="input-group-btn">
                    <a class="btn btn-default" type="button" title="Перейти на biz.mail.ru" href="https://biz.mail.ru/login/autopartslist.ru" target="_blank">
                        <span class="glyphicon glyphicon-link"></span>
                    </a>
                </span>                                                            
            </div>
            <?= $this->formElementErrors($form->get('statement_email')); ?>                  
        </div>        

        <div class="form-group">
            <?= $this->formLabel($form->get('statement_email_password')); ?>
            <?= $this->formElement($form->get('statement_email_password')); ?>
            <?= $this->formElementErrors($form->get('statement_email_password')); ?>                  
        </div>                

        <div class="form-group">
            <?= $this->formLabel($form->get('statement_app_password')); ?>
            <?= $this->formElement($form->get('statement_app_password')); ?>
            <?= $this->formElementErrors($form->get('statement_app_password')); ?>                  
        </div>                
    </div>
    <div class="col-md-2" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active">
                <?= $this->formElement($form->get('submit')); ?>
            </li>
        </ul>
    </div>    
    
</div>   

<?= $this->form()->closeTag(); ?>
