<?php
$this->headTitle('Настройки обмена с банком');

$this->mainMenu()->setActiveItemId('settings');
$this->mainMenu()->setActiveUrl($this->url('admin', ['action' => 'bank-settings']));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Настройки обмена с банком'=>$this->url('admin', ['action' => 'bank-settings']),
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$form = $this->form;

$form->get('statement_by_api')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('statement_by_file')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('doc_by_api')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('statement_email')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('statement_email_password')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('statement_app_password')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('payment_auto')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<div class="row">
    <div class="col-xs-12">
        <button class="btn btn-default test-button" value="/bankapi/sber-client-info">
            <span class="glyphicon glyphicon-pushpin" ></span>Тест Sber
        </button>                
    </div>
</div>

<h1>Настройки обмена с банком</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-5">
        
        <div class="form-group">
            <?= $this->formLabel($form->get('statement_by_api')); ?>
            <?= $this->formElement($form->get('statement_by_api')); ?>
            <?= $this->formElementErrors($form->get('statement_by_api')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('statement_by_file')); ?>
            <?= $this->formElement($form->get('statement_by_file')); ?>
            <?= $this->formElementErrors($form->get('statement_by_file')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('doc_by_api')); ?>
            <?= $this->formElement($form->get('doc_by_api')); ?>
            <?= $this->formElementErrors($form->get('doc_by_api')); ?>                  
        </div>        

        <div class="form-group">
            <?= $this->formLabel($form->get('payment_auto')); ?>
            <?= $this->formElement($form->get('payment_auto')); ?>
            <?= $this->formElementErrors($form->get('payment_auto')); ?>                  
        </div>        

    </div>   
    <div class="col-md-5">
        <div class="form-group">
            <?= $this->formLabel($form->get('statement_email')); ?>
            <div class="input-group">
                <?= $this->formElement($form->get('statement_email')); ?>
                <span class="input-group-btn">
                    <a class="btn btn-default" type="button" title="Перейти на biz.mail.ru" href="https://biz.mail.ru/login/autopartslist.ru" target="_blank">
                        <span class="glyphicon glyphicon-link"></span>
                    </a>
                </span>                                                            
            </div>
            <?= $this->formElementErrors($form->get('statement_email')); ?>                  
        </div>        

        <div class="form-group">
            <?= $this->formLabel($form->get('statement_email_password')); ?>
            <?= $this->formElement($form->get('statement_email_password')); ?>
            <?= $this->formElementErrors($form->get('statement_email_password')); ?>                  
        </div>                

        <div class="form-group">
            <?= $this->formLabel($form->get('statement_app_password')); ?>
            <?= $this->formElement($form->get('statement_app_password')); ?>
            <?= $this->formElementErrors($form->get('statement_app_password')); ?>                  
        </div>                
    </div>
    <div class="col-md-2" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active">
                <?= $this->formElement($form->get('submit')); ?>
            </li>
        </ul>
    </div>    
    
</div>   

<?= $this->form()->closeTag(); ?>

<script async="false">
    $('.test-button').on('click', function(e) {
        var url = e.currentTarget.value;
        
        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    if (data == 'ok'){
                        bootbox.alert("Успешно!");
                    } else {
                        bootbox.alert("Не удалось отправить сообщение!");
                    }    
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })
</script>