<?php
$this->headTitle('Администрирование');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Администрирование'=>$this->url('admin'),
                'phpinfo()' => $this->url('admin', ['action' => 'phpinfo']),
                ]);
  
?>

<?php echo 'Сервер: '.$_SERVER['SERVER_ADDR'];?><br/>
<?php phpinfo(); ?>
