<?php
$form = $this->form;

$form->get('receiving_mail')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('receiving_link')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('upload_raw')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('parse_raw')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('parse_producer')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('parse_article')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('parse_oem')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('parse_name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('assembly_producer')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('assembly_good')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('image_mail_box')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('image_mail_box_password')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('image_mail_box_check')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Настройки загрузки прайсов</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">

<div class="row">
    <div class="col-md-12">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('receiving_mail')); ?>
            <?= $this->formElement($form->get('receiving_mail')); ?>
            <?= $this->formElementErrors($form->get('receiving_mail')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('receiving_link')); ?>
            <?= $this->formElement($form->get('receiving_link')); ?>
            <?= $this->formElementErrors($form->get('receiving_link')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('upload_raw')); ?>
            <?= $this->formElement($form->get('upload_raw')); ?>
            <?= $this->formElementErrors($form->get('upload_raw')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('parse_raw')); ?>
            <?= $this->formElement($form->get('parse_raw')); ?>
            <?= $this->formElementErrors($form->get('parse_raw')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('parse_producer')); ?>
            <?= $this->formElement($form->get('parse_producer')); ?>
            <?= $this->formElementErrors($form->get('parse_producer')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('parse_article')); ?>
            <?= $this->formElement($form->get('parse_article')); ?>
            <?= $this->formElementErrors($form->get('parse_article')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('parse_oem')); ?>
            <?= $this->formElement($form->get('parse_oem')); ?>
            <?= $this->formElementErrors($form->get('parse_oem')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('parse_name')); ?>
            <?= $this->formElement($form->get('parse_name')); ?>
            <?= $this->formElementErrors($form->get('parse_name')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('assembly_producer')); ?>
            <?= $this->formElement($form->get('assembly_producer')); ?>
            <?= $this->formElementErrors($form->get('assembly_producer')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('assembly_good')); ?>
            <?= $this->formElement($form->get('assembly_good')); ?>
            <?= $this->formElementErrors($form->get('assembly_good')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('image_mail_box')); ?>
            <?= $this->formElement($form->get('image_mail_box')); ?>
            <?= $this->formElementErrors($form->get('image_mail_box')); ?>                  
        </div>                
        <div class="form-group">
            <?= $this->formLabel($form->get('image_mail_box_password')); ?>
            <?= $this->formElement($form->get('image_mail_box_password')); ?>
            <?= $this->formElementErrors($form->get('image_mail_box_password')); ?>                  
        </div>                
        <div class="form-group">
            <?= $this->formLabel($form->get('image_mail_box_check')); ?>
            <?= $this->formElement($form->get('image_mail_box_check')); ?>
            <?= $this->formElementErrors($form->get('image_mail_box_check')); ?>                  
        </div>                
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            <button type="button" class="btn btn-primary" id="price-settings-submit">Загрузить</button>
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>    

<script type="text/javascript">
    $('#price-settings-submit').on('click', function() {
        var dialog = bootbox.dialog({
            message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите ...</p>',
            closeButton: false
        });
        
        var file_data = $('#file').prop('files')[0];   
        var form_data = new FormData();                  
        form_data.append('name', file_data);

        $.ajax({
            type: 'POST',
            url: '/admin/price-settings-form/<?= $supplier->getId() ?>',
            contentType: false,
            processData: false,
            data: form_data
        })
            .done(function (data) {
                dialog.modal('hide');
                if (data == 'ok'){
                    $('#upload-price-modal').modal('hide');
                    window.location.reload();
                } else {
                    $('#upload-price-modal-content').html(data);
                }    
            })
            .fail(function () {
                dialog.modal('hide');
                bootbox.alert("Произошла ошибка при выполнении операции.");
            });
    })    
</script>