<?php
$this->headTitle('Настройки загрузки прайсов');

$this->mainMenu()->setActiveItemId('raw');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Настройки загрузки прайсов'=>$this->url('settings', ['action' => 'price-settings']),
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$form = $this->form;

$form->get('receiving_mail')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('receiving_link')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('upload_raw')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('uploading_raw')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('parse_raw')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('parse_producer')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('parse_article')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('parse_oem')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('parse_name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('assembly_producer')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('assembly_good')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('update_good_price')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('assembly_group_name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('good_token')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('image_mail_box')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('image_mail_box_password')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('image_mail_box_check')->setAttributes([
    'class'=>'form-control', 
    ]);
$form->get('cross_mail_box')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('cross_mail_box_password')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('cross_mail_box_check')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Настройки загрузки прайсов</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-3">
        
        <div class="form-group">
            <?= $this->formLabel($form->get('receiving_mail')); ?>
            <?= $this->formElement($form->get('receiving_mail')); ?>
            <?= $this->formElementErrors($form->get('receiving_mail')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('receiving_link')); ?>
            <?= $this->formElement($form->get('receiving_link')); ?>
            <?= $this->formElementErrors($form->get('receiving_link')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('upload_raw')); ?>
            <?= $this->formElement($form->get('upload_raw')); ?>
            <?= $this->formElementErrors($form->get('upload_raw')); ?>                  
        </div>        

        <div class="form-group">
            <?= $this->formLabel($form->get('uploading_raw')); ?>
            <?= $this->formElement($form->get('uploading_raw')); ?>
            <?= $this->formElementErrors($form->get('uploading_raw')); ?>                  
        </div>        

        <div class="form-group">
            <?= $this->formLabel($form->get('parse_raw')); ?>
            <?= $this->formElement($form->get('parse_raw')); ?>
            <?= $this->formElementErrors($form->get('parse_raw')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('parse_producer')); ?>
            <?= $this->formElement($form->get('parse_producer')); ?>
            <?= $this->formElementErrors($form->get('parse_producer')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('parse_article')); ?>
            <?= $this->formElement($form->get('parse_article')); ?>
            <?= $this->formElementErrors($form->get('parse_article')); ?>                  
        </div>  
    </div>
    <div class="col-md-3">    
        <div class="form-group">
            <?= $this->formLabel($form->get('parse_oem')); ?>
            <?= $this->formElement($form->get('parse_oem')); ?>
            <?= $this->formElementErrors($form->get('parse_oem')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('parse_name')); ?>
            <?= $this->formElement($form->get('parse_name')); ?>
            <?= $this->formElementErrors($form->get('parse_name')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('assembly_producer')); ?>
            <?= $this->formElement($form->get('assembly_producer')); ?>
            <?= $this->formElementErrors($form->get('assembly_producer')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('assembly_good')); ?>
            <?= $this->formElement($form->get('assembly_good')); ?>
            <?= $this->formElementErrors($form->get('assembly_good')); ?>                  
        </div>        

        <div class="form-group">
            <?= $this->formLabel($form->get('update_good_price')); ?>
            <?= $this->formElement($form->get('update_good_price')); ?>
            <?= $this->formElementErrors($form->get('update_good_price')); ?>                  
        </div>        
        <div class="form-group">
            <?= $this->formLabel($form->get('good_token')); ?>
            <?= $this->formElement($form->get('good_token')); ?>
            <?= $this->formElementErrors($form->get('good_token')); ?>                  
        </div>                
        <div class="form-group">
            <?= $this->formLabel($form->get('assembly_group_name')); ?>
            <?= $this->formElement($form->get('assembly_group_name')); ?>
            <?= $this->formElementErrors($form->get('assembly_group_name')); ?>                  
        </div>                
    </div>   
    <div class="col-md-3">
        <div class="form-group">
            <?= $this->formLabel($form->get('image_mail_box')); ?>
            <?= $this->formElement($form->get('image_mail_box')); ?>
            <?= $this->formElementErrors($form->get('image_mail_box')); ?>                  
        </div>                
        <div class="form-group">
            <?= $this->formLabel($form->get('image_mail_box_password')); ?>
            <?= $this->formElement($form->get('image_mail_box_password')); ?>
            <?= $this->formElementErrors($form->get('image_mail_box_password')); ?>                  
        </div>                
        <div class="form-group">
            <?= $this->formLabel($form->get('image_mail_box_check')); ?>
            <?= $this->formElement($form->get('image_mail_box_check')); ?>
            <?= $this->formElementErrors($form->get('image_mail_box_check')); ?>                  
        </div>                
        <div class="form-group">
            <?= $this->formLabel($form->get('cross_mail_box')); ?>
            <?= $this->formElement($form->get('cross_mail_box')); ?>
            <?= $this->formElementErrors($form->get('cross_mail_box')); ?>                  
        </div>                
        <div class="form-group">
            <?= $this->formLabel($form->get('cross_mail_box_password')); ?>
            <?= $this->formElement($form->get('cross_mail_box_password')); ?>
            <?= $this->formElementErrors($form->get('cross_mail_box_password')); ?>                  
        </div>                
        <div class="form-group">
            <?= $this->formLabel($form->get('cross_mail_box_check')); ?>
            <?= $this->formElement($form->get('cross_mail_box_check')); ?>
            <?= $this->formElementErrors($form->get('cross_mail_box_check')); ?>                  
        </div>                
    </div>
    <div class="col-sm-3" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active">
                <?= $this->formElement($form->get('submit')); ?>
            </li>
            <li>
<!--                <button value="/admin/off-price-setting-form?flag=1" class="btn btn-info btn-xs refresh-button"
                        title="Отключить все">
                    Отключить все
                </button>-->
                <a href="javascript:void(0)" onclick="offSelect(2)" class=""
                        title="Отключить все">
                    Отключить все
                </a>
                <a href="javascript:void(0)" onclick="offSelect(1)" class=""
                        title="Отключить все">
                    Включить все
                </a>
            </li>
        </ul>
    </div>    
    
</div>   

<?= $this->form()->closeTag(); ?>

<script type="text/javascript">
    function offSelect(flag){
        $("select").each(function(){
            $(this).val(flag);
        })
    }            
</script>