<?php
$this->headTitle('Настройки оплат по СБП');

$this->mainMenu()->setActiveItemId('settings');
$this->mainMenu()->setActiveUrl($this->url('settings', ['action' => 'sbp-settings']));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Настройки оплат по СБП'=>$this->url('settings', ['action' => 'sbp-settings']),
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$form = $this->form;

$form->get('account')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('legal_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('merchant_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Настройки оплат по СБП</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-5">
        
        <div class="form-group">
            <?= $this->formLabel($form->get('legal_id')); ?>
            <?= $this->formElement($form->get('legal_id')); ?>
            <?= $this->formElementErrors($form->get('legal_id')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('merchant_id')); ?>
            <?= $this->formElement($form->get('merchant_id')); ?>
            <?= $this->formElementErrors($form->get('merchant_id')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('account')); ?>
            <?= $this->formElement($form->get('account')); ?>
            <?= $this->formElementErrors($form->get('account')); ?>                  
        </div>
                        
    </div>   
    <div class="col-md-5">
    </div>
    <div class="col-md-2" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active">
                <?= $this->formElement($form->get('submit')); ?>
            </li>
        </ul>
    </div>    
    
</div>   

<?= $this->form()->closeTag(); ?>
