<?php
$this->headTitle('Настройки оплат по СБП');

$this->mainMenu()->setActiveItemId('settings');
$this->mainMenu()->setActiveUrl($this->url('settings', ['action' => 'sbp-settings']));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Настройки оплат по СБП'=>$this->url('settings', ['action' => 'sbp-settings']),
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$form = $this->form;

$form->get('account')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('legal_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('customer_code')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('merchant_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('qrcode_check')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<div class="row">
    <div class="col-xs-12">
        <button class="btn btn-default test-button" value="/sbp/legal-info">
            <span class="glyphicon glyphicon-refresh" ></span> Инфо
        </button>                
        <button class="btn btn-default test-button" value="/sbp/payment-statuses">
            <span class="glyphicon glyphicon-refresh" ></span> Статусы
        </button>                
        <button class="btn btn-default test-button" value="/bankapi/webhooks">
            <span class="glyphicon glyphicon-list" ></span> Вебхуки Точки
        </button>                
        <button class="btn btn-default test-button" value="/bankapi/create-webhook">
            <span class="glyphicon glyphicon-edit" ></span> Создать вебхуки Точки
        </button>                
    </div>
</div>

<h1>Настройки оплат по СБП</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-5">
        
        <div class="form-group">
            <?= $this->formLabel($form->get('legal_id')); ?>
            <?= $this->formElement($form->get('legal_id')); ?>
            <?= $this->formElementErrors($form->get('legal_id')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('customer_code')); ?>
            <?= $this->formElement($form->get('customer_code')); ?>
            <?= $this->formElementErrors($form->get('customer_code')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('merchant_id')); ?>
            <?= $this->formElement($form->get('merchant_id')); ?>
            <?= $this->formElementErrors($form->get('merchant_id')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('account')); ?>
            <?= $this->formElement($form->get('account')); ?>
            <?= $this->formElementErrors($form->get('account')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('qrcode_check')); ?>
            <?= $this->formElement($form->get('qrcode_check')); ?>
            <?= $this->formElementErrors($form->get('qrcode_check')); ?>                  
        </div>
                        
        <?= $this->formElement($form->get('submit')); ?>
    </div>   
    <div class="col-md-5">
    </div>
<!--    <div class="col-md-2" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active">
                <?= $this->formElement($form->get('submit')); ?>
            </li>
        </ul>
    </div>    -->
    
</div>   

<?= $this->form()->closeTag(); ?>

<script async="false">
    $('.test-button').on('click', function(e) {
        var url = e.currentTarget.value;
//        console.log(url);
        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    console.log(data);
                    if (data){
                        bootbox.alert("Успешно!");
                    } else {
                        bootbox.alert("Не удалось отправить сообщение!");
                    }    
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    });
</script>