<?php
$this->headTitle('Настройки');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Настройки'=>$this->url('settings'),
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$form = $this->form;

$form->get('apl_secret_key')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'пароль api АПЛ',
    ]);

$form->get('sms_ru_api_id')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'СМС.РУ api_id',
    ]);

$form->get('sms_ru_url')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'СМС.РУ url http://sms.ru/sms/send',
    ]);

$form->get('telegram_hook_url')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Телеграм hook url',
    ]);

$form->get('telegram_bot_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'имя бота',
    ]);

$form->get('telegram_api_key')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Телеграм api key',
    ]);

$form->get('telegram_admin_chat_id')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Чат администратора',
    ]);



//$form->get('tamtam_chat_id')->setAttributes([
//    'class'=>'form-control', 
//    'placeholder'=>'ТамТам chat_id',
//    ]);
//
//$form->get('tamtam_access_token')->setAttributes([
//    'class'=>'form-control', 
//    'placeholder'=>'ТамТам access token',
//    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Настройки</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('apl_secret_key')); ?>
            <?= $this->formElement($form->get('apl_secret_key')); ?>
            <?= $this->formElementErrors($form->get('apl_secret_key')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('sms_ru_url')); ?>
            <?= $this->formElement($form->get('sms_ru_url')); ?>
            <?= $this->formElementErrors($form->get('sms_ru_url')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('sms_ru_api_id')); ?>
            <?= $this->formElement($form->get('sms_ru_api_id')); ?>
            <?= $this->formElementErrors($form->get('sms_ru_api_id')); ?>                  
        </div>
                
        <div class="form-group">
            <button class="btn btn-default test-button" value="/admin/test-sms">
                <span class="glyphicon glyphicon-phone" ></span>Тестовая смс
            </button>
        </div>    

        <div class="form-group">
            <?= $this->formLabel($form->get('telegram_bot_name')); ?>
            <?= $this->formElement($form->get('telegram_bot_name')); ?>
            <?= $this->formElementErrors($form->get('telegram_bot_name')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('telegram_api_key')); ?>
            <?= $this->formElement($form->get('telegram_api_key')); ?>
            <?= $this->formElementErrors($form->get('telegram_api_key')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('telegram_hook_url')); ?>
            <?= $this->formElement($form->get('telegram_hook_url')); ?>
            <?= $this->formElementErrors($form->get('telegram_hook_url')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('telegram_admin_chat_id')); ?>
            <?= $this->formElement($form->get('telegram_admin_chat_id')); ?>
            <?= $this->formElementErrors($form->get('telegram_admin_chat_id')); ?>                  
        </div>

        <div class="form-group">
            <button class="btn btn-default test-button" value="/admin/test-telegram">
                <span class="glyphicon glyphicon-phone" ></span>Телеграм тест
            </button>
        </div>    
                
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>   
    <div class="col-md-4">
    </div>    
    
</div>   

<script async="true">
    $('.test-button').on('click', function(e) {
        var url = e.currentTarget.value;
        
        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    if (data == 'ok'){
                        bootbox.alert("Успешно!");
                    }    
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })
</script>