
<script>
    $(document).on('click', '.sms-message-modal-show', function (e) {
        var orderId = $(this).attr('order-id');
        var phone = $(this).attr('phone');
        <?php if ($idNode):?>
            orderId = $('#<?= $idNode ?>').val();
        <?php endif; ?>    
        <?php if ($phoneNode):?>
            phone = $('#<?= $phoneNode ?>').val();
        <?php endif; ?>    
        if (orderId){
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'smsMessageModal',
                url: url+orderId+'?phone='+phone,
                zIndex: 9999,
                width: $(window).width()-150
            });
        };
    });  
</script>