<?php
$this->headTitle('Настройки обмена по апи текдока');

$this->mainMenu()->setActiveItemId('settings');
$this->mainMenu()->setActiveUrl($this->url('settings', ['action' => 'td-exchange-settings']));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Настройки обмена по апи текдока'=>$this->url('settings', ['action' => 'td-exchange-settings']),
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$form = $this->form;

$form->get('update_car')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('update_image')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('update_description')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('update_group')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('update_oe')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Настройки обмена по апи текдока</h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-4">
        
        <div class="form-group">
            <?= $this->formLabel($form->get('update_oe')); ?>
            <?= $this->formElement($form->get('update_oe')); ?>
            <?= $this->formElementErrors($form->get('update_oe')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('update_group')); ?>
            <?= $this->formElement($form->get('update_group')); ?>
            <?= $this->formElementErrors($form->get('update_group')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('update_description')); ?>
            <?= $this->formElement($form->get('update_description')); ?>
            <?= $this->formElementErrors($form->get('update_description')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('update_car')); ?>
            <?= $this->formElement($form->get('update_car')); ?>
            <?= $this->formElementErrors($form->get('update_car')); ?>                  
        </div>
                        
        <div class="form-group">
            <?= $this->formLabel($form->get('update_image')); ?>
            <?= $this->formElement($form->get('update_image')); ?>
            <?= $this->formElementErrors($form->get('update_image')); ?>                  
        </div>
                        
    </div>   
    <div class="col-md-4">
        <div class="panel-group">
            <div class="panel panel-info">
                <div class="panel-heading">
                   Обновления из Текдок
                </div>
                <div class="panel-body">                        
                    <div class="pull-left">
                        Группы <span id="totalGroup" class="badge">0</span>
                    </div>
                    <div class="pull-right">
                        <button value="/goods/td-group/" class="btn btn-info btn-xs refresh-button"
                                title="Обновление Групп">
                            <span class="glyphicon glyphicon-refresh" ></span>
                        </button>                             
                        <button value="/goods/reset-td-group/" class="btn btn-warning btn-xs refresh-button"
                                title="Сбросить метку обновлений">
                            <span class="glyphicon glyphicon-refresh" ></span>
                        </button>                             
                    </div>
                </div>
                <div class="panel-body">                        
                    <div class="pull-left">
                        Описания <span id="totalDesc" class="badge">0</span>
                    </div>
                    <div class="pull-right">
                        <button value="/goods/td-description/" class="btn btn-info btn-xs refresh-button"
                                title="Обновление описаний">
                            <span class="glyphicon glyphicon-refresh" ></span>
                        </button>                             
                        <button value="/goods/reset-td-description/" class="btn btn-warning btn-xs refresh-button"
                                title="Сбросить метку обновлений">
                            <span class="glyphicon glyphicon-refresh" ></span>
                        </button>                             
                    </div>
                </div>
                <div class="panel-body">                        
                    <div class="pull-left">
                        Номера <span id="totalOem" class="badge">0</span>
                    </div>
                    <div class="pull-right">
                        <button value="/goods/td-oem/" class="btn btn-info btn-xs refresh-button"
                                title="Обновление OEM">
                            <span class="glyphicon glyphicon-refresh" ></span>
                        </button>                             
                        <button value="/goods/reset-td-oem/" class="btn btn-warning btn-xs refresh-button"
                                title="Сбросить метку обновлений">
                            <span class="glyphicon glyphicon-refresh" ></span>
                        </button>                             
                    </div>
                </div>
                <div class="panel-body">                        
                    <div class="pull-left">
                        Mашины <span id="totalCar" class="badge">0</span>
                    </div>
                    <div class="pull-right">
                        <button value="/goods/update-cars/" class="btn btn-info btn-xs refresh-table-button"
                                title="Обновление машин">
                            <span class="glyphicon glyphicon-refresh" ></span>
                        </button> 
                        <button value="/goods/reset-td-car/" class="btn btn-warning btn-xs refresh-button"
                                title="Сбросить метку обновлений">
                            <span class="glyphicon glyphicon-refresh" ></span>
                        </button>                             
                    </div>
                </div>
                <div class="panel-body">                        
                    <div class="pull-left">
                        Картинки <span id="totalImage" class="badge">0</span>
                    </div>
                    <div class="pull-right">
                        <a href="/image" class="btn btn-info btn-xs" target='_blank'
                                title="Картинки поставщиков">
                            <span class="glyphicon glyphicon-picture" ></span>
                        </a> 
                        <button value="/goods/td-image/" class="btn btn-info btn-xs refresh-table-button"
                                title="Обновление картинок">
                            <span class="glyphicon glyphicon-refresh" ></span>
                        </button> 
                        <button value="/goods/reset-td-image/" class="btn btn-warning btn-xs refresh-button"
                                title="Сбросить метку обновлений">
                            <span class="glyphicon glyphicon-refresh" ></span>
                        </button>                             
                    </div>
                </div>
            </div>                    
        </div>    
    </div>
<!--    <div class="col-md-2">
        
    </div>-->
    <div class="col-md-2" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active">
                <?= $this->formElement($form->get('submit')); ?>
            </li>
            <li>
                <a href="javascript:void(0)" onclick="offSelect(2)" class=""
                        title="Отключить все">
                    Отключить все
                </a>
                <a href="javascript:void(0)" onclick="offSelect(1)" class=""
                        title="Отключить все">
                    Включить все
                </a>
            </li>    
        </ul>
    </div>    
    
</div>   

<?= $this->form()->closeTag(); ?>

<script type="text/javascript">
    function offSelect(flag){
        $("select").each(function(){
            $(this).val(flag);
        });
    }       
    
    function totalFeatures(){
        $(".badge").each(function( index ) {
            var node = $(this).attr('id');
            $.getJSON('/goods/total-feature/?feature=' + node, function(data){
                $('#'+node).text(data['total']);
            });
        });        
    }

    $(window).on('load', function() {
        totalFeatures();
    });
    
</script>