<?php
$this->headTitle('Настройки');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Настройки'=>$this->url('settings'),
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$form = $this->form;


$form->get('telegram_hook_url')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Телеграм hook url',
    ]);

$form->get('telegram_bot_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'имя бота',
    ]);

$form->get('telegram_api_key')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Телеграм api key',
    ]);

$form->get('telegram_admin_chat_id')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Чат администратора',
    ]);

$form->get('telegram_proxy')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Использовать прокси',
    ]);

$form->get('auto_check_proxy')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Автопроверка прокси',
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<div class="row">
    <div class="col-xs-12">
        <button class="btn btn-default test-button" value="/admin/test-telegram">
            <span class="glyphicon glyphicon-phone" ></span>Тест
        </button>                
        <button class="btn btn-default test-button" value="/admin/test-postpone-telegram">
            <span class="glyphicon glyphicon-phone" ></span>Тест (отл)
        </button>                
        <button class="btn btn-default test-button refresh-table-button" value="/telegramm/check-proxy">
            <span class="glyphicon glyphicon-bell" ></span>Проверка прокси
        </button>                
    </div>
</div>

<h1>Настройки</h1>
<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-8">
        
        <div class="form-group">
            <?= $this->formLabel($form->get('telegram_bot_name')); ?>
            <?= $this->formElement($form->get('telegram_bot_name')); ?>
            <?= $this->formElementErrors($form->get('telegram_bot_name')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('telegram_api_key')); ?>
            <?= $this->formElement($form->get('telegram_api_key')); ?>
            <?= $this->formElementErrors($form->get('telegram_api_key')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('telegram_hook_url')); ?>
            <?= $this->formElement($form->get('telegram_hook_url')); ?>
            <?= $this->formElementErrors($form->get('telegram_hook_url')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('telegram_admin_chat_id')); ?>
            <?= $this->formElement($form->get('telegram_admin_chat_id')); ?>
            <?= $this->formElementErrors($form->get('telegram_admin_chat_id')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('telegram_proxy')); ?>
            <?= $this->formElement($form->get('telegram_proxy')); ?>
            <?= $this->formElementErrors($form->get('telegram_proxy')); ?>
            <span><?= $geoIpData['country'];?></span>
            <span><?= $geoIpData['regionName'];?></span>
            <span><?= $geoIpData['city'];?></span>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('auto_check_proxy')); ?>
            <?= $this->formElement($form->get('auto_check_proxy')); ?>
            <?= $this->formElementErrors($form->get('auto_check_proxy')); ?>                  
        </div>
    </div>   
    <div class="col-sm-3" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active">
                <?= $this->formElement($form->get('submit')); ?>
            </li>
        </ul>
    </div>    
    
</div>   

<?= $this->form()->closeTag(); ?>

<script async="false">
    $('.test-button').on('click', function(e) {
        var url = e.currentTarget.value;
        
        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    if (data == 'ok'){
                        bootbox.alert("Успешно!");
                    }    
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })
</script>