<?php
$this->headTitle('Настройки Zetasoft');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Настройки'=>$this->url('settings'),
            'Настройки Zetasoft'=>$this->url('admin', ['action' => 'zetasoft-settings']),
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<?php
$form = $this->form;


$form->get('host')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('login')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('api_key')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('md5_key')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('max_query')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>
<div class="row">
    <div class="col-xs-12">
        <button class="btn btn-default test-button" value="/ext/zetasoft?action=ping">
            <span class="glyphicon glyphicon-bell" ></span>Ping
        </button>                
<!--        <button class="btn btn-default test-button" value="/ext/zetasoft?action=token">
            <span class="glyphicon glyphicon-certificate" ></span>Токен
        </button>                -->
    </div>
</div>

<h1>Настройки Zetasoft</h1>
<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-4">
        
        <div class="form-group">
            <?= $this->formLabel($form->get('host')); ?>
            <?= $this->formElement($form->get('host')); ?>
            <?= $this->formElementErrors($form->get('host')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('login')); ?>
            <?= $this->formElement($form->get('login')); ?>
            <?= $this->formElementErrors($form->get('login')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('md5_key')); ?>
            <?= $this->formElement($form->get('md5_key')); ?>
            <?= $this->formElementErrors($form->get('md5_key')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('api_key')); ?>
            <?= $this->formElement($form->get('api_key')); ?>
            <?= $this->formElementErrors($form->get('api_key')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('max_query')); ?>
            <?= $this->formElement($form->get('max_query')); ?>
            <?= $this->formElementErrors($form->get('max_query')); ?>                  
        </div>
        
        <div  class="form-group">
            <?= $this->formElement($form->get('submit')); ?>            
        </div>
    </div>
    <div class="col-sm-3" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active">
            </li>
        </ul>
    </div>    
    
</div>   

<?= $this->form()->closeTag(); ?>

<script async="false">
    $('.test-button').on('click', function(e) {
        var url = e.currentTarget.value;
        
        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    if (data.message.pong){
                        bootbox.alert(data.message.pong);
                    } else if (data.message.status && data.message.title){
                        bootbox.alert(data.message.title+' ('+data.message.status+')');
                    } else {
                        bootbox.alert("Не удалось отправить сообщение!");
                    }    
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })
</script>