<?php
use Stock\Entity\Pt;

$form = $this->form;

$form->get('office_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('company')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('office2_id')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('company2')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('doc_date')->setAttributes([
    'class'=>'form-control', 
    'min' => date('Y-m-d', strtotime($allowDate.' + 1 day')),
    'disabled' => $disabled,
    ]);

$form->get('doc_no')->setAttributes([
    'class'=>'form-control', 
    'disabled' => true,
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('quantity')->setAttributes([
    'class'=>'form-control', 
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'pt-submit']);

$form->prepare();

?>
<?= $this->form()->openTag($form); ?>

<div class="modal-header">
    <h5 class="modal-title" id="ptModalLabel">Перемещение <b><?= $good->getCode()?> <?= $good->getProducer()->getName() ?> <?= $good->getNameShort() ?></b></h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <div class="row">
        <div class="col-xs-6">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('doc_date')); ?>
                <?= $this->formElement($form->get('doc_date')); ?>
                <?= $this->formElementErrors($form->get('doc_date')); ?>                  
            </div>
        </div>   
        <div class="col-xs-6">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('quantity')); ?>
                <?= $this->formElement($form->get('quantity')); ?>
                <?= $this->formElementErrors($form->get('quantity')); ?>                  
            </div>
        </div>   
    </div>    
    <div class="row">
        <div class="col-xs-6">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('office_id')); ?>
                <?= $this->formElement($form->get('office_id')); ?>
                <?= $this->formElementErrors($form->get('office_id')); ?>                  
            </div>
        </div>    
        <div class="col-xs-6">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('office2_id')); ?>
                <?= $this->formElement($form->get('office2_id')); ?>
                <?= $this->formElementErrors($form->get('office2_id')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-6">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('company')); ?>
                <?= $this->formElement($form->get('company')); ?>
                <?= $this->formElementErrors($form->get('company')); ?>                  
            </div>
        </div>    
        <div class="col-xs-6">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('company2')); ?>
                <?= $this->formElement($form->get('company2')); ?>
                <?= $this->formElementErrors($form->get('company2')); ?>                  
            </div>
        </div>    
    </div>        
    <?= $this->formElement($form->get('csrf')); ?>
</div>    

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary" id="pt-submit" <?= $disabled ? 'disabled':''; ?>>Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script>
    function refreshTable(){
        return;
    }

    function submitForm(){
        var data = serializeForm('#pt-form');
        $.ajax({
            type: 'POST',
            url: '/pt/combined-form/<?= $good->getId()?>',
            data: $.param(data)
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#ptCombinedModal').modal('hide');
                    if ($('#table').length){
                        $('#table').bootstrapTable('refresh');
                    }    
                    if ($('#movementTable').length){
                        $('#movementTable').bootstrapTable('refresh');
                    }    
                    if ($('#baseptutable').length){
                        $('#baseptutable').bootstrapTable('refresh');
                    }    
                } else {
                    $('#ptCombinedModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };
    
    $('#office').on('change', function(){
        $.getJSON( '/offices/legals/'+$('#office').val(), function( data ) {
            $('#company').empty();
            $.each( data.rows, function( key, value ) {
                $('#company').append('<option value="' + key + '">' + value.name + '</option>');
            });
        });    
    });
        
    $('#office2').on('change', function(){
        $.getJSON( '/offices/legals/'+$('#office2').val(), function( data ) {
            $('#company2').empty();
            $.each( data.rows, function( key, value ) {
                $('#company2').append('<option value="' + key + '">' + value.name + '</option>');
            });
        });    
    });
        
    $( document ).ready(function() {
                
        var forms = $('#pt-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('pt-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });        
    });        
</script>