<?php
    use Stock\Entity\Pt;

    $this->headTitle('Перемещение товаров');

    $this->mainMenu()->setActiveItemId('stock');
    $this->mainMenu()->setActiveUrl($this->url('pt'));

    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Склад'=>$this->url('stock'),
                'Перемещение товаров'=>$this->url('pt'),
                ]);


?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <button class="btn btn-default pt-modal-show" type="button" modal-url="/pt/edit-form">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>                
                <div class="form-group">
                    <div class="btn-group">
                        <input id="searchinput" name="search" style="width: 150px" class="form-control enter-search" type="text" placeholder="Артикул">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>
                    <button id="ok" type="submit" class="btn btn-default" title="Поиск">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>    
                <div class="form-group">
                    <select style="width: 200px" class="form-control" name="office">
                        <option selected>--все офисы--</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select style="width: 200px" class="form-control" name="company">
                        <option selected>--все юл--</option>
                        <?php foreach ($companies as $company):?>
                            <option value="<?= $company->getId()?>"><?= $company->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <input id="monthSelect" class="form-control" type="month" placeholder="Период" value="<?= date('Y-m');?>">
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/pt/content"
            data-cookie="true"
            data-cookie-id-table="ptSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-show-columns="true"
            data-query-params="queryParams"
            data-sort-name="docDate"
            data-unique-id="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="rowStyle"
            >
            <thead>
                <tr>
                     <th data-field="docDate" data-sortable="true" data-width="100">Дата</th>
                     <th data-field="id" data-sortable="false" data-type="numeric" data-formatter="idFormatter" data-width="80">Id</th>
                     <th data-field="docNo" data-sortable="false" data-width="5">Номер</th>
                     <th data-field='amount' data-sortable="false" data-align="right" data-formatter="amountFormatter">Сумма</th>
                     <th data-field='office.name' data-sortable="false">Отправитель</th>
                     <th data-field='company.name' data-sortable="false">Отправитель ЮЛ</th>
                     <th data-field='office2.name' data-sortable="false">Получатель</th>
                     <th data-field='company2.name' data-sortable="false">Получатель ЮЛ</th>
                     <th data-field='comment' data-sortable="false">Примечание</th>
                     <th data-field="" data-formatter="activeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">
    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status === '<?= Pt::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        if (row.statusAccount === '<?= Pt::STATUS_TAKE_NO?>'){
           retired += ' warning';
        }
        return {classes: retired};
    }

    var $table = $('#table'),
        $ok = $('#ok'),
        curentRowIndex = -1;
    
    function setCurrentIndex(index){
        curentRowIndex = index;
    }
    
    function getCurrentIndex(){
        return curentRowIndex;
    }
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }

    $(function () {
        $table.on('load-success.bs.table', function (e, res) {
            tableRowClick();        
        });

        $('select').change(function (){
            refreshTable();
        });
    });

    
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        $('#toolbar').find('select[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.month = $('#monthSelect').val();
        
        return params;
    }
    
    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function idFormatter(value, row){
        if (row.aplId){
            return '<nobr>' + value + ' (' + row.aplId + ')</nobr>';
        }
        return value;
    }    
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    
    
    function activeFormatter(value, row){
        var url = '/pt/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs pt-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
    
    function changeStatus(ptId, status){
        $.get( "/pt/status/"+ptId+'?status='+status, function(data){
            $table.bootstrapTable('updateByUniqueId', {id: ptId, row: data});
        });        
    }    
    
    function clearTake(ptId){
        $.get( "/pt/clear-take/"+ptId, function(data){
            $table.bootstrapTable('updateByUniqueId', {id: ptId, row: data});
        });        
    }    
    
    var menu = new BootstrapMenu('.tablerow', {
        fetchElementData: function(rowElem) {
            setCurrentIndex($(rowElem).attr('data-index'));
            return $table.bootstrapTable('getData')[getCurrentIndex()];
        },
        actionsGroups: [
           ['clearTake'], ['history']
        ],      
        actions: {
            statusActiv: {
                name: 'Сделать активным',
                iconClass: 'glyphicon glyphicon-ok',
                onClick: function(row) {
                    changeStatus(row.id, <?= Pt::STATUS_ACTIVE?>);
                },
                isShown: function(row) {
                  return row.status == <?= Pt::STATUS_RETIRED?>;
                },
                isEnabled: function(row) {
                    return row.docDate > '<?= $allowDate?>';
                }                
            }, 
            statusRetired: {
                name: 'Сделать не активным',
                iconClass: 'glyphicon glyphicon-remove',
//                classNames: 'bg-danger',
                onClick: function(row) {
                    changeStatus(row.id, <?= Pt::STATUS_RETIRED?>);
                },
                isShown: function(row) {
                  return row.status == <?= Pt::STATUS_ACTIVE?>;
                },
                isEnabled: function(row) {
                    return row.docDate > '<?= $allowDate?>' || row.status != <?= Pt::STATUS_ACTIVE ?>;
                }                
            },
            clearTake: {
                name: 'Удалить отсутствующие товары',
                iconClass: 'glyphicon glyphicon-trash',
                classNames: 'bg-warning',
                onClick: function(row) {
                    clearTake(row.id);
                },
                isShown: function(row) {
                    return true;
                },
                isEnabled: function(row) {
                    return row.status == <?= Pt::STATUS_ACTIVE?> && row.statusAccount == <?= Pt::STATUS_TAKE_NO ?>;
    //                return row.docDate > '<?= $allowDate?>';
                }                
            },
            history: {
                name: 'История',
                iconClass: 'glyphicon glyphicon-list-alt',
//                classNames: 'bg-danger',
                onClick: function(row) {
                    $.ajax({
                        type: "GET",
                        url: "/log/history/"+row.id+"?docType=pt",
                        success: function (result) {
                            bootbox.alert({
                                size: "large",
                                message: result
                            });
                        }
                    });                    
                }
            }
        }
    });    
    
</script>

