<?php

$form = $this->form;

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('code')->setAttributes([
    'class'=>'form-control', 
    'data-provide' => "typeahead",
    'autocomplete' => 'off',
    ]);

$form->get('producer')->setAttributes([
    'class'=>'form-control', 
    'data-provide' => "typeahead",
    'autocomplete' => 'off',
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'good-submit']);

$form->prepare();

$docName = 'Новый';

?>
            
<?= $this->form()->openTag($form); ?>

<div class="modal-header">
    <h5 class="modal-title" id="goodModalLabel">Новый товар</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <div class="row">
        <div class="col-xs-12">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('code')); ?>
                <?= $this->formElement($form->get('code')); ?>
                <?= $this->formElementErrors($form->get('code')); ?>                  
            </div>
        </div>    
    </div>
    <div class="row">
        <div class="col-xs-12">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('producer')); ?>
                <?= $this->formElement($form->get('producer')); ?>
                <?= $this->formElementErrors($form->get('producer')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-12">                        
            <div class="form-group">
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>                  
            </div>
        </div>    
    </div>

    <?= $this->formElement($form->get('csrf')); ?>
</div>    

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary" id="good-submit">Сохранить</button>
</div>

<?= $this->form()->closeTag(); ?>
            
<script  type="text/javascript">
    /**
    * очистить поле
     */
    function submitForm(){
        var data = serializeForm('#goods-form');
        $.ajax({
            type: 'POST',
            url: '/goods/edit-form/<?= ($good) ? $good->getId():"" ?>',
            data: $.param(data)
        })
            .done(function (data) {
                if (data){
                    $('#goodModal').modal('hide');
                    if ($('#table')){
                        $('#table').bootstrapTable('refresh');
                    }    
                    if (data.result.id){
//                        window.open('/goods/view/'+data.result.id, '_blank');
                        var a = document.createElement('a');
                        a.target="_blank";
                        a.href='/goods/view/'+data.result.id';
                        a.click();
                    }
                } else {
                    $('#goodModal .modal-content').html(data);                    
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };

    $( document ).ready(function() {

        $('#code').typeahead({
            source: function(query, process) {
                return $.get("/goods/autocomplete-good?q="+query, function (data) {
                    return process(data);
                });
            },
            changeInputOnSelect: true,
            afterSelect: function(data) {
                $('#name').val(data.nameShort);
                $('#code').val(data.code);
                $('#producer').val(data.producer);
            }
        });
        
        $('#producer').typeahead({
            source: function(query, process) {
                return $.get("/goods/autocomplete-producer?q="+query, function (data) {
                    return process(data);
                });
            },
            changeInputOnSelect: true,
        });

        var forms = $('#goods-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('good-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });
    });    
    
</script>