<?php
$this->headTitle('Товары');

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Товары'=>$this->url('goods')
            ]);

?>

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <button class="btn btn-default good-modal-show" type="button" 
                            modal-url="/goods/edit-form" 
                            data-toggle='tooltip' data-original-title="Добавить товар">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </button>
                </div>    
                <div class="form-group">
                    <div class="btn-group">
                        <input type="checkbox" class="checkbox" name="accurate" value=""
                               data-toggle='tooltip' data-original-title="Точный поиск"
                               onchange="value = (this.checked) ? 1:0"/>
                        <input id="searchinput" name="search" style="width: 400px" class="form-control" type="text" placeholder="Артикул">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>
                    <button id="ok" type="submit" class="btn btn-default" title="Поиск">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/goods/presence"
            data-cookie="true"
            data-cookie-id-table="goodsSaveId"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            >
            <thead>
                <tr>
                     <!--<th data-field="id" data-type="numeric" data-sortable="true" data-width="100">ID</th>-->
                     <th data-field="aplId" data-type="numeric" data-formatter="aplFormatter" data-sortable="true" data-width="100">AplId</th>
                     <th data-field="code" data-formatter="linkFormatter" data-sortable="true" data-width="100">Артикул</th>
                     <th data-field="producerName" data-formatter="producerFormatter">Производитель</th>             
                     <th data-field="name" >Наименование</th>             
                     <th data-field="rest" data-width="100" data-align="right">Остаток</th>             
                     <th data-field="officeName" >Офис</th>             
                     <!--<th data-field="" data-formatter="activeFormatter"></th>-->
                     <th data-field="statusRawpriceEx" data-formatter="statusExFormatter" data-cell-style="cellStatusExStyle"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<script type="text/javascript">
    $(function () {
        $("[data-toggle='tooltip']").tooltip();
    });

    $(document).on('click', '.good-modal-show', function (e) {
        var url = $(e.currentTarget).attr('modal-url');
        showFormDialog({
            id: 'goodModal',
            url: url,
//            width: '500px'
        });
    });  
    
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    var table = $('#table'),
        ok = $('#ok');

    $(function () {
        ok.click(function () {
            refreshTable();
        });
        $(".inputclear").click(function(){
            $("#searchinput").val('');
            refreshTable();
        });
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function linkFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/goods/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function aplFormatter(value, row){
        if (value != '0'){
            return [
                '<div class="pull-left">',
                '<a href="https://autopartslist.ru/goods/view/id/' + value + '" target="_blank">' + value + '</a>',
                '</div>'
            ].join(''); 
        } else {
            return '-';
        }    
    }    
    
    function producerFormatter(value, row){
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + row.producerId + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function activeFormatter(value, row){
        var url = '/goods/delete-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function statusExFormatter(value, row) {
        return '<span></span>' ;
    }  
    
    function cellStatusExStyle(value, row, index) {
        var classes = [
          'light',
          'success',
          'warning'
        ]
        return {
          classes: classes[value-1]
        }
    }        
    
    function responseHandler(res) {
        return res;
    }    
</script>
