<?php
    use Application\Entity\Oem;
    use Stock\Entity\Movement;
    use Application\Entity\Rawprice;
    use Stock\Entity\Reserve;
    use Application\Filter\GoodAvailable;
    use Application\Entity\Goods;
    use ApiMarketPlace\Entity\MarketSaleReport;
    use Fasade\Entity\GroupSite;
    
    $priceCols = $goodsManager->priceCols($goods);
    $retailCount = ($goods->getRetailCount()) ? $goods->getRetailCount():'';
    
    $this->headTitle($goods->getTitleShort());
    $this->mainMenu()->setActiveItemId('stock');
    $this->mainMenu()->setActiveUrl('goods');
    
    $availableFilter = new GoodAvailable($entityManager);
?>

<div class="row">
    <div class="col-md-3">
        <h3>
            <?= $goods->getCode()?>
            <?= $goods->getProducer()->getName()?>
            <sup style="font-size:50%;"><?= Goods::getAvailableHtmlList()[$availableFilter->filter($goods)]; ?></sup>
            <sup>
                <button class="btn btn-default btn-xs producer-union-modal-show" type="button" 
                        <?= ($rbacManager->isGranted(null, 'rb.manage')) ? '':'disabled' ?> 
                        modal-url="/admin/producer-union-form/<?= $goods->getProducer()->getId() ?>?good=<?= $goods->getId()?>" 
                        data-toggle='tooltip' data-original-title="Заменить производителя">
                    <span class="glyphicon glyphicon-transfer" aria-hidden="true"></span>
                </button>
            </sup>    
        </h3>
        <h5>
            Цена: <?= $goods->getPrice(); ?>
            <button value="/apl/good-apl-id/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                    title="Обновить в АПЛ">
                <span class="glyphicon glyphicon-export" ></span> Обновить в АПЛ
            </button>
            <?= $goods->getAplIdLinkId('Ссылка на АПЛ'); ?>
        </h5>
        <h3>
            <?= $goods->getNameShort() ?>
        </h3>
        <?php if ($goods->getDescription()): ?>
        
        <?php endif;?>                    
                
        <?php if(!count($images)):?>
            <div class="thumbnail">
                <img src="/img/no_img.jpg" class="img-thumbnail">
            </div>    
        <?php endif ?>
        <?php foreach($images as $image):?>
            <?php if ($image->getPublicPath()):?>
                <div class="thumbnail">
                    <?php if (file_exists($image->getPath())):?>
                        <?php if (mime_content_type($image->getPath()) == 'application/pdf'):?>
                            <a href="<?= $image->getPublicPath()?>" download>
                                <span class="glyphicon glyphicon-download"></span>
                                <?= $image->getName() ?>
                            </a>
                        <?php else:?>
                            <a href="<?= $image->getPublicPath() ?>" target="_blank">
                                <img src="<?= $image->getPublicPath() ?>" class="img-thumbnail" alt="<?= $image->getName() ?>">
                            </a>
                        <?php endif; ?>
                    <?php else:?>
                        <a href="<?= $image->getPublicPath() ?>" target="_blank">
                            <span class='glyphicon glyphicon-picture'><?= $image->getName() ?></span>
                        </a>    
                    <?php endif; ?>
                    <div class="caption panel-body small">
                        <div class="pull-left">
                            <span><?= $image->getStatusAsString();?></span> 
                            <span><?= $image->getSimilarAsString();?></span> 
                            <?php if (file_exists($image->getPath())):?>
                                <span><?= mime_content_type($image->getPath()) ?></span>
                            <?php endif; ?>
                        </div>
                        <div class="pull-right">                                    
                            <button value="/goods/delete-image/<?= $image->getId()?>" class="btn btn-default btn-xs this-delete"
                                    title="Удалить">
                                <span class="glyphicon glyphicon-trash" ></span>
                            </button>                             
                        </div>                                                                            
                    </div>
                </div>    
            <?php endif; ?>    
        <?php endforeach;?>
        <div class="thumbnail">
            <button value="/goods/upload-image-form/<?= $goods->getId() ?>" class="btn btn-default btn-xs"
                    data-toggle="modal" data-target="#modal-dialog" title="Добавить картинку">
                <span class="glyphicon glyphicon-plus" ></span>
            </button>                 
            <?php if(count($images)):?>
                <button value="/apl/ex-img/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-button"
                        title="Обновить в apl">
                    <span class="glyphicon glyphicon-export" ></span>
                </button>            
            <?php endif; ?>    
<!--                <button value="/goods/external-api-image/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                        title="Обновить картинку из TecDoc">
                    <span class="glyphicon glyphicon-refresh" ></span>
                </button>                             -->
        </div>
    </div>
    <div class="col-md-9">        
        <ul class="nav nav-tabs" id="featureTab" role="tablist">
            <li role="presentation"><a href="#movements" role="tab" id="home-tab" data-toggle="tab" aria-controls="movements" aria-expanded="true">Движения <span id="movementBadge" class="badge">0</span> <span class="badge badge-success" data-toggle="tooltip" title="Продаж"><?= $retailCount?></span></a></li>
            <li role="presentation"><a href="#price" role="tab" id="price-tab" data-toggle="tab" aria-controls="price" aria-expanded="true">Прайсы <span id="priceBadge" class="badge">0</span> <span id="priceAplBadge" class="badge badge-info" data-toggle="tooltip" title="Остаток в Апл"><?= ($isApl) ? $isApl->getRest():'' ?></span></a></li>
            <li role="presentation"><a href="#home" role="tab" id="home-tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Описание <span id="homeBadge" class="badge"><?= count($goods->getAttributeValues()); ?></span></a></li>
            <li role="presentation"><a href="#oem" role="tab" id="oem-tab" data-toggle="tab" aria-controls="oem" aria-expanded="true">Номера <span id="oemBadge" class="badge">0</span></a></li>
            <li role="presentation"><a href="#linked" role="tab" id="linked-tab" data-toggle="tab" aria-controls="linked" aria-expanded="true">Применимость <span id="linkedBadge" class="badge">0</span></a></li>
            <li role="presentation"><a href="#prices" role="tab" id="price-tab" data-toggle="tab" aria-controls="prices" aria-expanded="true">Цены <span id="pricesBadge" class="badge"><?= $goods->getFormatMeanPrice()?></span></a></li>
            <li role="presentation"><a href="#comitent" role="tab" id="comitent-tab" data-toggle="tab" aria-controls="comitent" aria-expanded="true">ТП <span id="comitentBadge" class="badge">0</span></a></li>
        </ul>

        <div class="tab-content" id="featureTabContent">
            <div class="tab-pane fade" role="tabpanel" id="home" aria-labelledby="home-tab">
                <table class="table table-bordered">
                    <tr>
                        <th colspan="3">Характеристики</th>
                    </tr>
                    <?php if (!$goods->getAttributeValues()->count()):?>
                        <tr><td colspan="3"><i>Нет характеристик</i></td></tr>
                    <?php endif;?>
                    <?php foreach ($goods->getAttributeValues() as $attributeValue):?>
                        <tr style="text-decoration: <?= $attributeValue->getAttribute()->getStatusDecorationAsString()?>">
                            <td align='right'>
                                <a href="#" 
                                   class="editable" data-type="text" 
                                   data-pk="<?= $attributeValue->getAttribute()->getId()?>" 
                                   data-name="name" 
                                   data-disabled="true"
                                   data-url="/goods/attribute-edit">
                                    <?= $attributeValue->getAttribute()->getName()?>
                                </a>
                            </td>
<!--                                        <td width="5">
                                <input type="checkbox" class="similarGoodCheckbox checkbox" 
                                       data-toggle='tooltip' data-original-title="Использовать в аналогичных товарах"
                                       value="<?= $attributeValue->getAttribute()->getId()?>" <?= $attributeValue->getAttribute()->getSimilarGoodAsHtml()?>/>
                            </td>
                            <td width="5">
                                <input type="checkbox" class="toBestNameCheckbox checkbox" 
                                       data-toggle='tooltip' data-original-title="Использовать в наименовании"
                                       value="<?= $attributeValue->getAttribute()->getId()?>" <?= $attributeValue->getAttribute()->getToBestNameAsHtml()?>/>
                            </td>-->
                            <td>
                                <?= $attributeValue->getAttributeValue()->getValue();?>
                            </td>
                            <td width="10">
                                <button value="/goods/delete-attribute/<?= $attributeValue->getAttribute()->getId()?>" type="button"
                                        class="btn btn-default btn-xs this-delete" title="Не показывать">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </button>
                            </td>
                        </tr>                                              
                    <?php endforeach;?>
                    <tr>
                        <th colspan="2">Категории</th>
                        <th width="10">
                            <button class="btn btn-default btn-xs include-in-category"
                                    title="Включить в категорию">
                                <span class="glyphicon glyphicon-plus"></span>
                            </button>                                
                        </th>
                    </tr>
                    <?php if (!$goods->getCategories()->count()):?>
                        <tr><td colspan="3"><i>Нет категорий</i></td></tr>
                    <?php endif;?>
                    <?php foreach ($goods->getCategories() as $groupSite):?>
                        <tr>
                            <td colspan="2"><?= $groupSite->getName() ?></td>
                            <td width="10">
                                <button class="btn btn-default btn-xs delete-from-category"
                                        value="<?= $groupSite->getId() ?>" title="Удалить из категории">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>                                
                            </td>
                        </tr>
                    <?php endforeach;?>
                    <tr>
                        <th colspan="3">Группа наименований</th>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <?php if ($goods->getTokenGroup()):?>
                                <a href="/name/view-token-group/<?= $goods->getTokenGroup()->getId() ?>" target="_blank"><?= $goods->getTokenGroup()->getName() ?? 'Нет наименования' ?></a>
                            <?php else:?>
                                <i>Нет группы наименования</i>
                            <?php endif?>  
                        </td>        
                    </tr>
                    <tr>
                        <th colspan="3">Наименование</th>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div style="width: 100%">
                                <a href="#" id="good-name-editable" class="editable" 
                                   data-type="text" 
                                   data-pk="<?= $goods->getId()?>" 
                                   data-name="name" 
                                   data-disabled="false"
                                   data-mode='inline'
                                   data-showbuttons = 'false'
                                   data-inputclass ='form-control'
                                   data-tpl="<input type='text' style='width: 1000px'>"
                                   data-clear="false"
                                   data-savenochange="true"
                                   data-url="/goods/name-edit">
                                        <?php if ($goods->getName()): ?>
                                            <?= $this->escapeHtml($goods->getName()); ?>
                                        <?php endif;?>
                                </a>                                
                            </div>
                        </td> 
                        <td>
                            <button class="btn btn-default btn-xs ai-naming"
                                    title="ИИ генерация">
                                <span class="glyphicon glyphicon-fire" ></span>
                            </button>
                        </td>
                    </tr> 
                    <tr>
                        <th colspan="3">Описания поставщиков</th>
                    </tr>
                    <?php foreach ($goods->articleTitles() as $articleTitle):?>
                        <tr>
                            <td colspan="2">
                                <?= $articleTitle?>
                            </td>
                            <td width="10">
                            </td>
                        </tr>                                              
                    <?php endforeach;?>
                    <tr>
                        <th colspan="2">Описание
                        </th>
                        <th width="10">
                            <button class="btn btn-default btn-xs save-description"
                                    title="Сохранить описание">
                                <span class="glyphicon glyphicon-floppy-save"></span>
                            </button>                                
                        </th
                    </tr>
                    <tr>
                        <td colspan="3">
                            <textarea rows="10" id="description" class="wysihtml5 form-control">
                                <?= $goods->getDescription()?>
                            </textarea>                        
                        </td>    
                    </tr>
                    <tr>
                        <th colspan="2">Токены</th>
                        <th width="10">
                            <button value="/goods/update-good-token/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                                    title="Обновить токены">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>
                        </th>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <?php foreach ($tokens as $token):?>
                                <span><?= $token->getLemma();?></span>
                            <?php endforeach;?>
                        </td> 
                    </tr>    
                </table>                    
            </div>
            <div class="tab-pane fade" role="tabpanel" id="oem" aria-labelledby="oem-tab">
                <div id="oemToolbar">
                    <div class="form-inline" role="form">
                        <button value="/oem/oem-form/<?= $goods->getId() ?>" type="button" class="btn btn-default" title="Добавить" data-toggle="modal" data-target="#modal-dialog">
                            <span class="glyphicon glyphicon-plus"></span>
                        </button>
                        <div class="form-group">
                            <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                        </div>
                        <button id="oemOk" type="submit" class="btn btn-default">OK</button>
                        <select style="width: 200px" class="form-control" id='oemSourceSelect'>
                            <option value="null" selected>все источники</option>
                            <?php foreach ($oemSources as $key => $value):?>
                                <option value="<?= $key?>" <?= ($key === Oem::SOURCE_EXT_SOURCE) ? 'selected':'' ?>><?= $value?></option>
                            <?php endforeach;?>
                        </select>
                        <button value="/goods/good-oem/<?= $goods->getId()?>" class="btn btn-default refresh-table-button"
                                title="Загрузить номера из ТекДока" data-table="oemTable">
                            <span class="glyphicon glyphicon-import" ></span>
                        </button>                             
                        <button value="/goods/good-oem-sup-cross/<?= $goods->getId()?>" class="btn btn-default refresh-table-button"
                                title="Обновить номера из прайсов и кроссов" data-table="oemTable">
                            <span class="glyphicon glyphicon-import" ></span>
                        </button>                             
                        <button value="/goods/good-oem-intersect/<?= $goods->getId()?>" class="btn btn-default refresh-table-button"
                                title="Обновить пересечения номеров" data-table="oemTable">
                            <span class="glyphicon glyphicon-import" ></span>
                        </button>                             
                        <button value="/apl/ex-oem/<?= $goods->getId()?>" class="btn btn-default refresh-table-button"
                                title="Обновить в АПЛ" data-table="oemTable">
                            <span class="glyphicon glyphicon-export" ></span>
                        </button>
                    </div>
                </div>
                <table id="oemTable" 
                    data-toggle="table" 
                    data-url="/goods/oem-content/<?= $goods->getId()?>"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-size="20"
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#oemToolbar"
                    data-show-refresh="true"
                    data-show-toggle="false"
                    data-query-params="oemQueryParams"
                    data-response-handler="responseHandler"
                    data-row-style="oeRowStyle"
                    data-classes = "table table-bordered table-hover table-condensed"
                    data-silent-sort ="true"
                    data-unique-id="id"
                    >
                    <thead>
                        <tr>
                             <!--<th data-field="id" data-type="numeric">Id</th>-->
                             <th data-field="oe">Код</th>
                             <th data-field="oeNumber" data-formatter="oeNumberFormatter">Номер</th>
                             <th data-field="brandName">Бренд</th>
                             <th data-field="source" data-formatter="sourceFormatter">Источник</th>
                             <th data-field="rating" data-width="10">Рейтинг</th>
                             <!--<th data-field="status" data-formatter="statusFormatter">Статус</th>-->
                             <th data-field="status" data-width="5" data-align="right" data-formatter="oemActiveFormatter"></th>
                        </tr>                
                    </thead>
                </table>
            </div>
            <div class="tab-pane fade" role="tabpanel" id="movements" aria-labelledby="movements-tab">
                <div id="movementToolbar">
                    <div class="form-inline" role="form">
                        <select id="officeSelect" style="width: 200px" class="form-control refresh-table" name="office">
                            <option>все</option>
                            <?php foreach ($offices as $office):?>
                                <option value="<?= $office->getId()?>" <?//= ($office->getId() == $currentUser->getOffice()->getId()) ? 'selected':''?>><?= $office->getName()?></option>
                            <?php endforeach;?>
                        </select>                    
<!--                        <div class="form-group">
                            <input id="monthSelect" class="form-control" type="month" placeholder="Период">
                        </div>-->
                        <div class="form-group">
                            <select id="periodSelect" class="form-control" name="period">
                                <option value="date">Дата</option>
                                <option value="week">Неделя</option>                        
                                <option value="month">Месяц</option>                        
                                <option value="number"  selected="true">Год</option>                        
                                <option value="all">за все время</option>                        
                            </select>
                            <input name="dateStart" id="dateStart" style="width: 200px" class="form-control" type="number" value="<?= date('Y')?>">
                        </div>
                        <button class="btn btn-default pt-combined-modal-show" 
                                type="button" 
                                title="Переместить" modal-url="/pt/combined-form/<?= $goods->getId()?>">
                            <span class="glyphicon glyphicon-transfer" aria-hidden="true"></span>
                        </button>                
                        <button class="btn btn-default vtp-modal-show" 
                                type="button" title="Возврат поставщику" <?= ($base) ? '':'disabled'?>                                
                                modal-url="/vtp/edit-form?good=<?= $goods->getId()?>">
                            <span class="glyphicon" aria-hidden="true"></span> В
                        </button>                
                        <button class="btn btn-default ot-modal-show" 
                                type="button" title="Оприходовать" 
                                modal-url="/ot/edit-form?good=<?= $goods->getId()?>">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </button>                
                        <button class="btn btn-default st-modal-show" 
                                type="button" title="Списать"
                                modal-url="/st/edit-form?good=<?= $goods->getId()?>">
                            <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                        </button>                
                    </div>
                </div>
                <table id="movementTable" 
                    data-toggle="table" 
                    data-url="/goods/movements/<?= $goods->getId()?>"
                    data-side-pagination="server"
                    data-cookie="false"
                    data-cookie-id-table="goodSaveId"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#movementToolbar"
                    data-show-refresh="true"
                    data-show-toggle="false"
                    data-sort-name="docStamp"
                    data-sort-order="asc"            
                    data-query-params="movementsQueryParams"
                    data-response-handler="responseHandler"
                    data-row-style="movementRowStyle"
                    data-classes = "table table-bordered table-hover table-condensed"
                    data-silent-sort ="true"
                    data-show-footer="true"
                    >
                    <thead>
                        <tr>
                             <!--<th data-field="docStamp" data-width="150">Дата</th>-->
                             <th data-field="dateOper" data-width="100" data-footer-formatter="footerTotalFormatter" data-sortable="true" data-formatter="dateFormatter">Дата</th>
                             <th data-field="quantity" data-type="numeric" data-footer-formatter="footerInFormatter" data-align="right" data-width="30" data-formatter="inFormatter">Приход</th>
                             <th data-field="quantity" data-type="numeric" data-footer-formatter="footerOutFormatter" data-align="right" data-width="30" data-formatter="outFormatter">Расход</th>
                             <th data-field="rest" data-type="numeric" data-footer-formatter="footerRestFormatter" data-align="right" data-width="30">Остаток</th>
                             <th data-field="docKey" data-formatter="movementFormatter">Документ</th>
                             <th data-field="baseKey" data-formatter="baseFormatter">Партия</th>
                             <th data-field="ptu.supplier.name" data-formatter="baseSupplierFormatter">Поставщик</th>
                             <th data-field="office.name" data-width="50">Офис</th>
                             <th data-field="company.name" data-width="150">ЮЛ</th>
                         </tr>                
                    </thead>
                </table>
                <div id="balanceToolbar">
                    <div class="form-inline" role="form">
                        <button class="btn btn-default" 
                                type="button" title="Обновить резервы" id="updateReserve"
                                url="/goods/update-reserve/<?= $goods->getId()?>">
                            <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                        </button>                
                    </div>
                </div>
                <table id="balanceTable" 
                    data-toggle="table" 
                    data-url ="/goods/balance/<?= $goods->getId()?>"
                    data-side-pagination="server"
                    data-cookie="false"
                    data-cookie-id-table="balanceSaveId"
                    data-pagination="false" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#balanceToolbar"
                    data-show-refresh="true"
                    data-show-toggle="false"
                    data-query-params="balanceQueryParams"
                    data-response-handler="responseHandler"
                    data-row-style="movementRowStyle"
                    data-classes = "table table-bordered table-hover table-condensed"
                    data-auto-refresh ="true"
                    data-auto-refresh-interval="60"
                    data-show-auto-refresh="false"
                    >
                    <thead>
                        <tr>
                             <th data-field="office">Офис</th>
                             <th data-field="rest"      data-type="numeric" data-width="20" data-align="right">Наличие</th>
                             <th data-field="reserve"   data-type="numeric" data-width="20" data-align="right" data-formatter="reserveFormatter">Резерв</th>
                             <th data-field="delivery"  data-type="numeric" data-width="20" data-align="right" data-formatter="deliveryFormatter">Доставка</th>
                             <th data-field="vozvrat"   data-type="numeric" data-width="20" data-align="right">Возврат</th>
                             <th data-field="available" data-type="numeric" data-width="20" data-align="right">Доступно</th>
                             <th data-field="foldName" data-formatter="foldCodeFormatter">Хранение</th>
                         </tr>                
                    </thead>
                </table>
            </div>
            <div class="tab-pane fade" role="tabpanel" id="comitent" aria-labelledby="comitent-tab">
                <div id="comitentToolbar">
                    <div class="form-inline" role="form">
                        <div class="form-group">
                            <select id="comitentPeriodSelect" class="form-control" name="period">
                                <option value="date">Дата</option>
                                <option value="week">Неделя</option>                        
                                <option value="month">Месяц</option>                        
                                <option value="number"  selected="true">Год</option>                        
                                <option value="all">за все время</option>                        
                            </select>
                            <input name="dateStart" id="comitentDateStart" style="width: 200px" class="form-control" type="number" value="<?= date('Y')?>">
                        </div>
                    </div>
                </div>
                <table id="comitentTable" 
                    data-toggle="table" 
                    data-url="/comitent/movements/<?= $goods->getId()?>"
                    data-side-pagination="server"
                    data-cookie="false"
                    data-cookie-id-table="comitentSaveId"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#comitentToolbar"
                    data-show-refresh="true"
                    data-show-toggle="false"
                    data-sort-name="docStamp"
                    data-sort-order="asc"            
                    data-query-params="comitentQueryParams"
                    data-response-handler="responseHandler"
                    data-row-style="comitentRowStyle"
                    data-classes = "table table-bordered table-hover table-condensed"
                    data-silent-sort ="true"
                    data-show-footer="true"
                    >
                    <thead>
                        <tr>
                             <!--<th data-field="docStamp" data-width="150">Дата</th>-->
                             <th data-field="dateOper" data-width="100" data-sortable="true" data-footer-formatter="footerTotalFormatter" data-formatter="dateFormatter">Дата</th>
                             <th data-field="quantity" data-type="numeric" data-align="right" data-width="30" data-footer-formatter="comitentInFormatter" data-formatter="inFormatter">Приход</th>
                             <th data-field="quantity" data-type="numeric" data-align="right" data-width="30" data-footer-formatter="comitentOutFormatter" data-formatter="outFormatter">Расход</th>
                             <th data-field="rest" data-type="numeric" data-footer-formatter="comitentRestFormatter" data-align="right" data-width="30">Остаток</th>
                             <th data-field="docKey" data-formatter="movementFormatter">Документ</th>
                             <th data-field="baseKey" data-formatter="baseFormatter">Партия</th>
                             <th data-field="legal.name">ТП</th>
                             <th data-field="company.name" data-width="150">ЮЛ</th>
                         </tr>                
                    </thead>
                </table>
                <div id="comitentBalanceToolbar">
                    <div class="form-inline" role="form">
                    </div>
                </div>
                <table id="comitentBalanceTable" 
                    data-toggle="table" 
                    data-url ="/comitent/balance/<?= $goods->getId()?>"
                    data-side-pagination="server"
                    data-cookie="false"
                    data-cookie-id-table="balanceSaveId"
                    data-pagination="false" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#comitentBalanceToolbar"
                    data-show-refresh="true"
                    data-show-toggle="false"
                    data-query-params="comitentBalanceQueryParams"
                    data-response-handler="responseHandler"
                    data-row-style="comitentRowStyle"
                    data-classes = "table table-bordered table-hover table-condensed"
                    data-auto-refresh ="true"
                    data-auto-refresh-interval="60"
                    data-show-auto-refresh="false"
                    >
                    <thead>
                        <tr>
                             <th data-field="legal">ТП</th>
                             <th data-field="rest"  data-type="numeric" data-width="20" data-align="right">Остаток</th>
                         </tr>                
                    </thead>
                </table>
            </div>
            <div class="tab-pane fade" role="tabpanel" id="linked" aria-labelledby="linked-tab">
                <div id="linkedToolbar">
                    <div class="form-inline" role="form">
                        <button class="btn btn-default" 
                                type="button" title="Обновить машины по номеру" id="updateCarByOem"
                                url="/car/update-good-car-by-oem/<?= $goods->getId()?>">
                            <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                        </button>                
                        <button class="btn btn-default" 
                                type="button" title="Удалить все машины" id="removeCars"
                                <?= ($goods->getCheckCar() === Goods::CHECK_CAR_OE) ? '':'disabled' ?>
                                url="/car/delete-good-cars/<?= $goods->getId()?>">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </button>                
                    </div>
                </div>            
                <table id="linkedTable" 
                    data-toggle="table" 
                    data-url="/goods/car-content/<?= $goods->getId()?>"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#linkedToolbar"
                    data-show-refresh="true"
                    data-show-toggle="false"
                    data-query-params="linkedQueryParams"
                    data-response-handler="responseHandler"
                    data-classes = "table table-bordered table-hover table-condensed"
                    data-silent-sort ="true"
                    >
                    <thead>
                        <tr>
<!--                                     <th data-field="id" data-sortable="true" data-type="numeric">ID</th>
                             <th data-field="tdId" data-sortable="true" data-type="numeric">TD</th>
                             <th data-field="aplId" data-sortable="true" data-type="numeric">APL</th>-->
                             <th data-field="fullName" data-sortable="true" data-formatter="carFormatter">Машина</th>
                             <th data-field="goodCount" data-sortable="true">Товаров</th>
                         </tr>                
                    </thead>
                </table>
            </div>
            <div class="tab-pane fade" role="tabpanel" id="price" aria-labelledby="price-tab">
                <div id="priceToolbar">
                    <div class="form-inline" role="form">
                        <select style="width: 200px" class="form-control" id='priceStatusSelect'>
                            <option>--все--</option>                            
                            <?php foreach ($priceStatuses as $key => $value):?>
                                <option value="<?= $key?>" <?= ($key == Rawprice::STATUS_PARSED) ? 'selected':'' ?>><?= $value?></option>
                            <?php endforeach;?>
                        </select>
                        <select class="form-control" id='supplierSelect'>
                            <option>--все поставщики--</option>                            
                            <?php foreach ($goodSuppliers as $row):?>
                                <option value="<?= $row['id']?>"><?= $row['name']?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                </div>
                <table id="priceTable" 
                    data-toggle="table" 
                    data-url="/goods/price-content/<?= $goods->getId()?>"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#priceToolbar"
                    data-show-refresh="true"
                    data-show-toggle="false"
                    data-query-params="priceQueryParams"
                    data-response-handler="responseHandler"
                    data-classes = "table table-bordered table-hover table-condensed"
                    data-silent-sort ="true"
                    >
                    <thead>
                        <tr>
                             <!--<th data-field="id" data-type="numeric">ID</th>-->
                             <th data-field="dateCreated" data-formatter="dateTimeFormatter">Дата</th>
                             <th data-field="supplier" data-formatter="baseSupplierFormatter">Поставщик</th>
                             <th data-field="goodname" >Описание</th>
                             <th data-field="rest" data-align='right'>Наличие</th>
                             <th data-field="price" data-formatter="priceFormatter" data-align='right'>Цена</th>
                             <th data-field="statusEx" data-formatter="statusExFormatter" data-cell-style="cellStatusExStyle"></th>
                         </tr>                
                    </thead>
                </table>
            </div>
            <div class="tab-pane fade" role="tabpanel" id="prices" aria-labelledby="prices-tab">
                <div id="optsToolbar">
                    <div class="form-inline" role="form">
                        <button value="/goods/update-prices/<?= $goods->getId()?>" data-table="optsTable" class="btn btn-default refresh-table-button" type="button"
                                title="Пересчитать">Пересчитать
                            <span class="glyphicon glyphicon-rub" ></span>
                        </button>                                 
                        <button value="/market-place/ozon-update-price/<?= $goods->getId()?>" class="btn btn-default refresh-ozon" type="button"
                                title="Обновить цену и остаток в OZON" <?= ($goods->getPrice()) ? '':'disabled'?>>OZON
                            <span class="glyphicon glyphicon-refresh"></span>
                        </button>                                                                 
                    </div>
                </div>
                <table id="optsTable" 
                    data-toggle="table" 
                    data-url="/goods/opts/<?= $goods->getId()?>"
                    data-side-pagination="server"
                    data-pagination="false" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#optsToolbar"
                    data-show-refresh="true"
                    data-show-toggle="false"
                    data-response-handler="responseHandler"
                    data-show-header="false"
                    data-classes = "table table-bordered table-hover"
                    data-silent-sort ="true"
                    >
                    <thead>
                        <tr>
                             <th data-field="name" data-width="30">Наименование</th>
                             <th data-field="percent" data-width="5">Процент</th>
                             <th data-field="value" data-width="30" data-align="right">Цена</th>
                         </tr>                
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>    

<?php echo $this->partial('/stock/index/stock-partial', []); ?>

<script type="text/javascript">    
    var $linkedTable = $('#linkedTable');    
    var $oemTable = $('#oemTable');
    var $priceTable = $('#priceTable');    
    var $movementTable = $('#movementTable');
    var $comitentTable = $('#comitentTable');
    var $balanceTable = $('#balanceTable');

    var $optsTable = $('#optsTable');

    $(function () {
        $(window).on('load', function() {
            <?php if (!empty($tab)):?>
                $('.nav-tabs #<?= $tab ?>').tab('show');
            <?php else: ?>    
                $('.nav-tabs a:first').tab('show');
            <?php endif; ?>  
                
            $('.editable').editable();
            $('.wysihtml5').wysihtml5({
                'toolbar': {'save': true},
                "events": {
                    "change": function() { 
//                            console.log("Blured");
                        $('.save-description').removeClass('btn-default');
                        $('.save-description').addClass('btn-warning');
                    }
                }
            });
        });
    
        $linkedTable.on('load-success.bs.table', function (e, res) {
            $('#linkedBadge').html($linkedTable.bootstrapTable('getOptions').totalRows);
        });        

        $oemTable.on('load-success.bs.table', function (e, res) {
            $('#oemBadge').html($oemTable.bootstrapTable('getOptions').totalRows);
        });        

        $priceTable.on('load-success.bs.table', function (e, res) {
            $('#priceBadge').html($priceTable.bootstrapTable('getOptions').totalRows);
        });        

        $movementTable.on('load-success.bs.table', function (e, res) {
            $('#movementBadge').html($movementTable.bootstrapTable('getOptions').totalRows);
            var inTotal = (res.totalIn) ? res.totalIn:0;
            var outTotal = (res.totalOut) ? res.totalOut:0;
            $('#inTotalFooter').html((Math.round(inTotal*100)/100).toFixed(0));
            $('#outTotalFooter').html((Math.round(outTotal*100)/100).toFixed(0));
        });        

        $comitentTable.on('load-success.bs.table', function (e, res) {
            $('#comitentBadge').html($comitentTable.bootstrapTable('getOptions').totalRows);
            var inTotal = (res.totalIn) ? res.totalIn:0;
            var outTotal = (res.totalOut) ? res.totalOut:0;
            $('#comitentInTotalFooter').html((Math.round(inTotal*100)/100).toFixed(0));
            $('#comitentOutTotalFooter').html((Math.round(outTotal*100)/100).toFixed(0));
        });        

        $optsTable.on('load-success.bs.table', function (e, res) {
            $('.editable').editable();
        });        

        $balanceTable.on('load-success.bs.table', function (e, res) {
            $('.fold').editable();
        });        

        $('#updateReserve').click(function (){
            var url = $(this).attr('url');
            if (url){
                $.get( url, function(data){
                    $balanceTable.bootstrapTable('refresh');
                });        
            }    
        })
                
        $('#updateCarByOem').click(function (){
            var url = $(this).attr('url');
            if (url){
                $.get( url, function(data){
                    $linkedTable.bootstrapTable('refresh');
                });        
            }    
        })
                
        $('#removeCars').click(function (){
            if (confirm('Удалить все машины товара?')){
                var url = $(this).attr('url');
                if (url){
                    $.get( url, function(data){
                        $linkedTable.bootstrapTable('refresh');
                    });        
                }    
            }    
        })
                
        $('.include-in-category').click(function (){
            $.getJSON( '/group-site/content?hasChild=<?= GroupSite::HAS_NO_CHILD?>&sort=code', function( data ) {
                var inputOptions = [{text: 'без категории', value: -1}];
                $.each(data.rows, function( index, value ) {
                    inputOptions.push({text: value.fullName, value: value.id});
                });
                bootbox.prompt({
                    title: 'Укажите категорию',
                    message: '<p>Выберете категорию для <b><?= htmlspecialchars($goods->getInputName())?></b>:</p>',
                    inputType: 'select',
                    value: getGroupSiteCookie(),        
                    inputOptions: inputOptions,
                    callback: function (result) {
    //                    console.log(result); return;               
                        if (result){
                            setGroupSiteCookie(result);
                            $.getJSON('/group-site/include-good-to-category/'+result+'?good=<?= $goods->getId()?>', function( data ) {
                                if (data == 'ok'){
                                    window.location.href = '/goods/view/<?= $goods->getId()?>?tab=home-tab';
                                }
                            });    
                        };    
                    }
                });
            }); 
            return;            
        });
        
        $('.ai-naming').click(function (){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: true
            });
            $.getJSON('/name/ai-naming/<?= $goods->getId()?>', function( data ) {
//                console.log(data.name);
                if (data.name){
                    $('#good-name-editable').editable('setValue', data.name);
                }
                if (data.description){
//                    $("#description").html(data.description);
                    $('#description').data("wysihtml5").editor.setValue(data.description);
                }
                dialog.modal('hide');
            });    
            return;            
        })
        
        $('.delete-from-category').click(function (){
            var categoryId = $(this).attr('value');
            if (categoryId){
                bootbox.confirm("Исключить из категории <?= htmlspecialchars($goods->getInputName())?>?", function(result){ 
                    if (result){                            
                        $.getJSON('/group-site/delete-good-from-category/'+categoryId+'?good=<?= $goods->getId()?>', function( data ) {
                            if (data == 'ok'){
                                window.location.href = '/goods/view/<?= $goods->getId()?>?tab=home-tab';
                            }
                        });    
                    }
                });
            }    
            return;            
        })
        
        $('.save-description').click(function (){
            $.post('/goods/description-edit', {name: 'description', pk: <?= $goods->getId()?>, value: $('#description').val()}, function( data ) {
                $('.save-description').addClass('btn-default');
                $('.save-description').removeClass('btn-warning');
            });    
            return;            
        })
        
        $('#priceStatusSelect').change(function (){
            $('#priceTable').bootstrapTable('refresh');
        })
        $('#supplierSelect').change(function (){
            $('#priceTable').bootstrapTable('refresh');
        })
        $('#oemSourceSelect').change(function (){
            $('#oemTable').bootstrapTable('refresh');
        })
        $('select[name="office"]').change(function (){
            $('.st-combined-modal-show').attr('modal-url', '/st/combined-form/<?= $goods->getId()?>?office='+$(this).val());
            $('#movementTable').bootstrapTable('refresh');
        })
        $('#monthSelect').change(function (){
            $('#movementTable').bootstrapTable('refresh', {silent: true});
        })
        $('#dateStart').change(function (){
            $movementTable.bootstrapTable('refresh', {silent: true});
        })
        $('#periodSelect').change(function (e) {
            $('#dateStart').attr('type', $(this).val());
            if ($(this).val() == 'number'){
                $('#dateStart').val('<?= date('Y')?>');
            }
            if ($(this).val() == 'all'){
                $('#dateStart').attr('type', 'number');
                $('#dateStart').val('');
            }
        });
        $('#comitentDateStart').change(function (){
            $comitentTable.bootstrapTable('refresh', {silent: true});
        })
        $('#comitentPeriodSelect').change(function (e) {
            $('#comitentDateStart').attr('type', $(this).val());
            if ($(this).val() == 'number'){
                $('#dateStart').val('<?= date('Y')?>');
            }
            if ($(this).val() == 'all'){
                $('#dateStart').attr('type', 'number');
                $('#dateStart').val('');
            }
        });
        $(document).on('click', '.reserve-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            $.ajax({
                url: url,
                success: function (data) {
                    var message = '<table width="100%"><tr><th>Документ</th><th>Резерв</th></tr>';
                    $.each(data, function( index, value ) {
    //                    console.log(value);
                        message += '<tr>';
                        message += '<td>'+value.link+'</td>';                        
                        message += '<td>'+value.rest+'</td>';                        
                        message += '</tr>';
                    });                    
                    message += '</table>';                                
                   bootbox.alert({
                        message: message,
                        size: 'small'
                    });
                }
            });
        });
        $('.refresh-ozon').on('click', function(e) {
            var url = e.currentTarget.value;
            if (url){
                var dialog = bootbox.dialog({
                    message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                    closeButton: false
                });

                $.ajax({
                    type: 'GET',
                    url: url
                })
                    .done(function (obj) {
                        dialog.modal('hide');
                        var messagePrice = 'Цена обновлена!';
                        var messageStock = 'Остаток обновлен!';
                        $.each(obj.price, function (key, product) {
                            if (product.updated == false){
                                messagePrice = 'Цена не обновлена<br/>';
                                $.each(product.errors, function (index, value) {
                                    messagePrice += value.message + '<br/>';
                                });
                            }    
                        });    
                        $.each(obj.stock, function (key, product) {
                            if (product.updated == false){
                                messageStock = 'Остаток не обновлен<br/>';
                                $.each(product.errors, function (index, value) {
                                    messageStock += value.message + '<br/>';
                                });
                            }    
                        });    
                        dialog = bootbox.dialog({
                            message: '<p><i class="fa fa-spin fa-spinner"></i>'+messagePrice+'</p><p><i class="fa fa-spin fa-spinner"></i>'+messageStock+'</p>',
                            closeButton: true
                        });
                    })
                    .fail(function () {
                        dialog.modal('hide');
                        bootbox.alert("Произошла ошибка при выполнении операции.");
                    });        
            }        
        }); 
    });

    function tabQueryParams(tab, params) {
        $(tab +'Toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $(tab + ' .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $(tab + ' li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function oemQueryParams(params) {
        params.source = $('#oemSourceSelect').val();
        return tabQueryParams('#oem', params);
    }
    
    function linkedQueryParams(params) {
        return tabQueryParams('#linked', params);
    }
    
    function movementsQueryParams(params) {
        params.office = $('select[name="office"]').val();
        params.month = $('#monthSelect').val();
        params.dateStart = $('#dateStart').val();
        params.period = $('#periodSelect').val();
        return tabQueryParams('#movements', params);
    }
    
    function comitentQueryParams(params) {
        params.month = $('#comitentMonthSelect').val();
        params.dateStart = $('#comitentDateStart').val();
        params.period = $('#comitentPeriodSelect').val();
        return tabQueryParams('#comitent', params);
    }
    
    function balanceQueryParams(params) {
        return tabQueryParams('#balance', params);
    }

    function comitentBalanceQueryParams(params) {
        return tabQueryParams('#comitentBalance', params);
    }

    function priceQueryParams(params) {
        params.status = $('#priceStatusSelect').val();
        params.supplier = $('#supplierSelect').val();
        return tabQueryParams('#price', params);
    }
    
    function responseHandler(res) {
        return res;
    }       
        
    function sourceFormatter(value){
        switch(value){
            <?php foreach ($oemSources as $key => $value):?>
                case <?= $key?>: result="<?= $value?>"; break;      
            <?php endforeach;?>            
            default: result = 'Неизвестно'; break;
        }        
        return result;
    }    
    
    function statusFormatter(value){
        switch(value){
            <?php foreach ($oemStatuses as $key => $value):?>
                case <?= $key?>: result="<?= $value?>"; break;      
            <?php endforeach;?>            
            default: result = 'Неизвестно'; break;
        }
        
        return result;
    }    
    
    function oeNumberFormatter(value, row){
        if (row.source == <?= Oem::SOURCE_INTERSECT?>){
            return '<a href="/goods/view/'+row.intersectGoodId+'" target="_blank">'+value+'</a>';
        } 
        if (row.source == <?= Oem::SOURCE_IID?>){
            return row.oe;
        } 
        return value;
    }
    
    function oeRowStyle(row, index) {
        if (row.status == <?= Oem::STATUS_RETIRED?>) {
            return {               
                classes: 'retired'
            };   
        }
        return {
          css: {
//            color: 'blue'
          }
        }; 
    }    

    function movementRowStyle(row, index) {
        if (row.status == <?= Movement::STATUS_RETIRED?>) {
            return {               
                classes: 'retired'
            };   
        }
        if (row.status == <?= Movement::STATUS_COMMISSION?>) {
            return {               
                classes: 'info'
            };   
        }
        return {
          css: {
//            color: 'blue'
          }
        };   
    }
    
    function comitentRowStyle(row, index) {
        if (row.status == <?= Movement::STATUS_RETIRED?>) {
            return {               
                classes: 'retired'
            };   
        }
        if (row.status == <?= Movement::STATUS_COMMISSION?>) {
            return {               
                classes: 'info'
            };   
        }
        return {
          css: {
//            color: 'blue'
          }
        };   
    }
    
    function footerTotalFormatter() {
        return 'Всего:';
    }
    
    function footerInFormatter(data){
        return '<span id="inTotalFooter"></span>';
    }

    function footerOutFormatter(data){
        return '<span id="outTotalFooter"></span>';
    }

    function footerRestFormatter(data){
        return '<span id="restTotalFooter"></span>';
    }
    
    function comitentInFormatter(data){
        return '<span id="comitentInTotalFooter"></span>';
    }

    function comitentOutFormatter(data){
        return '<span id="comitentOutTotalFooter"></span>';
    }

    function comitentRestFormatter(data){
        return '<span id="comitentRestTotalFooter"></span>';
    }
    
    function docFormatter(docType, docId, docKey, row){
        switch(docType){
            case <?= Movement::DOC_ORDER?>: 
//                        return "<a href='/order/intro/"+docId+"' target='_blank'>Заказ №"+docId+"</a>";
                        return "<a href='#' class='order-view-show' modal-url='/order/view/"+docId+"'>Заказ №"+docId+"</a>";
            case <?= Movement::DOC_VT?>: 
                        return "<a href='#' class='vt-modal-show' modal-url='/vt/edit-form/"+docId+"'>Возврат покупателя №"+docId+"</a>";
            case <?= Movement::DOC_PTU?>: 
                        return "<a href='#' class='ptu-modal-show' modal-url='/ptu/edit-form/"+docId+"'>Поступление №"+docId+"</a>";
            case <?= Movement::DOC_OT?>: 
                        return "<a href='#' class='ot-modal-show' modal-url='/ot/edit-form/"+docId+"'>Оприходование №"+docId+"</a>";
            case <?= Movement::DOC_PT?>: 
                        return "<a href='#' class='pt-modal-show' modal-url='/pt/edit-form/"+docId+"'>Перемещение №"+docId+"</a>";
            case <?= Movement::DOC_ST?>: 
                        return "<a href='#' class='st-modal-show' modal-url='/st/edit-form/"+docId+"'>Списание №"+docId+"</a>";
            case <?= Movement::DOC_VTP?>: 
                        return "<a href='#' class='vtp-modal-show' modal-url='/vtp/edit-form/"+docId+"'>Возврат поставщику №"+docId+"</a>";
            case <?= Movement::DOC_MSR?>: 
                    if (row.marketSaleReport.reportType === <?= MarketSaleReport::TYPE_REPORT?>){    
                        return "<a href='#' class='msrc-modal-show' modal-url='/comitent/edit-form/"+docId+"'>Отчет о реализации №"+docId+"</a>";
                    }    
                    if (row.marketSaleReport.reportType === <?= MarketSaleReport::TYPE_COMPENSATION?>){    
                        return "<a href='#' class='msrc-modal-show' modal-url='/comitent/report-form/"+docId+"'>Отчет о компенсациях №"+docId+"</a>";
                    }    
            default: return docKey;            
        }
    }
        
    function movementFormatter(value, row){
        return docFormatter(row.docType, row.docId, value, row);
    }
    
    function inFormatter(value){
        if (value > 0){
            return value
        }
        return '';
    }
    
    function outFormatter(value){
        if (value < 0){
            return -value
        }
        return '';
    }
    
    function reserveFormatter(value, row){
        if (value > '0'){
            return "<a href='#' class='reserve-show' modal-url='/goods/reserve-show/<?= $goods->getId()?>?status=<?= Reserve::STATUS_RESERVE?>'>"+value+"</a>";
        }
        return value;
    }
    
    function deliveryFormatter(value, row){
        if (value > '0'){
            return "<a href='#' class='reserve-show' modal-url='/goods/reserve-show/<?= $goods->getId()?>?status=<?= Reserve::STATUS_DELIVERY?>'>"+value+"</a>";
        }
        return value;
    }

    function baseFormatter(value, row){
        return docFormatter(row.baseType, row.baseId, value, row);
    }
    
    function baseSupplierFormatter(value, row){
        var supplierId = 0;
        if (row.supplierId){
            supplierId = row.supplierId;
        }
        if (row.ptu){
            supplierId = row.ptu.supplier.id;
        }
        if (value && supplierId){
//            return value.substr(0, 25);
            return [
                '<nobr>',
                '<a href="#" class="btn btn-link btn-xs supplier-link" supplier-id="'+supplierId+'" title="Перейти на сайт поставщика">',
                '<span class="glyphicon glyphicon-link"></span></a>',
                '<a href="/supplier/view/' + supplierId + '" target="_blank">' + value.substr(0, 25) + '</a>',
                '</nobr>'
            ].join(''); 
        }
        
        if (row.ot){
            if (row.ot.comiss){
                return (row.ot.comiss.name) ? row.ot.comiss.name:'Nan';
            }
        }
        if (row.vt){
            if (row.vt.order){
                return docFormatter('<?= Movement::DOC_ORDER?>', row.vt.order.id, '', row);
            }
        }
        return value;
    }
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(value, "dd.MM.yyyy");
    }

    function dateTimeFormatter(value){
        var date = new Date(value);
        return '<nobr>'+$.format.date(value, "dd.MM hh:mm")+'</nobr>';
    }

    function foldCodeFormatter(value, row){
        var disabled = (row.rest > 0) ? 'false':'true';
        if (row.rest>0){
            return [
                '<a href="#"',
                ' class="fold" data-type="select"',
                ' data-pk="<?= $goods->getId()?>"',
                ' data-value="'+row.foldCode+'"',
                ' data-disabled="'+disabled+'"',
                ' data-mode="inline"',
                ' data-showbuttons="false"',
                ' data-name="code"',
                ' data-source="/fold/folds?office='+row.officeId+'"',
                ' data-url="/fold/change-code?good=<?= $goods->getId()?>&office='+row.officeId+'&rest='+row.rest+'">',
                '</a>'
            ].join(''); 
        }
        
        return '';
    }    

    function oemActiveFormatter(value, row){
        if (value == 1){
            status = 2;
        } else {
            status = 1;
        }            
        var url = '/oem/oem-status-form/'+row.id+'?status='+status;
        var btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Изменить доступность"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\', \'oemTable\')">';
        btn += '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>';
        btn += '</button>';
        
        var editUrl = '/oem/oem-form/<?= $goods->getId() ?>?oem='+row.id;
        var editBtn = '<button';
        if (row.source != 3){
            editBtn += ' disabled="disabled"';
        }
        editBtn += ' type="button" data-toggle="modal" data-target="#modal-dialog"';
        editBtn += ' class="btn btn-default btn-xs"';
        editBtn += ' aria-label="Left Align"'; 
        editBtn += ' title="Изменить"'; 
        editBtn += ' value="'+editUrl+'">';
        editBtn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        editBtn += '</button>';
        return '<nobr>'+editBtn+' '+btn+'</nobr>';
    }    
    
    function carFormatter(value, row) {
        return value;
    }    
    
    function goodnameFormatter(value, row) {
        return '<a href="/rawprice/view/'+row.id+'" target="_blank">'+value+'</a>';
    }    
    
    function producerFormatter(value, row) {
        return '<a href="/producer/unknown-view/'+row.producerId+'" target="_blank">'+value+'</a>';
    }    
    
    function codeFormatter(value, row) {
        return '<a href="/producer/article-view/'+row.codeId+'" target="_blank">'+value+'</a> ' + producerFormatter(row.producer, row);
    }    
    
    function statusExFormatter(value, row) {
        return '<span></span>' ;
    }  
    
    function cellStatusExStyle(value, row, index) {
        var classes = [
          'light',
          'success',
          'warning'
        ]
        return {
          classes: classes[value-1]
        }
    }    
    
    function dateOperFormatter(value) {
        var dateOper = new Date(value);
        var dateOperStr = dateOper.getDate()+'-'+ (dateOper.getMonth()+1) + '-' + dateOper.getYear();
        return dateOperStr;
    }    
    
    function supplierFormatter(value, row) {
        var priceDate = new Date(row.dateCreated);
        var priceDateStr = priceDate.getDate()+'-'+ (priceDate.getMonth()+1) + ' ' + priceDate.getHours() + ':' + priceDate.getMinutes();
        return value + '<br/>' + priceDateStr ;
    }    

    function inSigma(data){
        if (data.inSigma == false){
            $('#rawprice'+data.id).css('color', 'red');
        }    
    }
    
    function priceFormatter(value, row){
        $.post(
            '/goods/in-sigma-content/<?= $goods->getId()?>?rawprice='+row.id,
            null,
            inSigma                
        );
        return [
            '<span id="rawprice'+row.id+'">'+Math.round(parseFloat(value.replace(/\s/g, '')))+'</span>',
        ].join(''); 
    }        
    
</script>
