<?php
$this->headTitle($goods->getCode().' '.$goods->getProducer()->getName().' '.$goods->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Товары'=>$this->url('goods'),
            $goods->getName()=>$this->url('goods', ['action'=>'view', 'id'=>$goods->getId()])
            ]);

?>

<style>
    .modal-body {
        height: 400px;
        overflow-y: scroll;
    }    
</style>

<h1>
    <?php if ($goods->getName()): ?>
        <?= $this->escapeHtml($goods->getName()); ?>
        <? if ($goods->getAplId()):?>
            <sup>
                <button value="/apl/update-good-name/<?= $goods->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                        title="Обновить наименование в АПЛ">
                    <span class="glyphicon glyphicon-refresh" ></span>
                </button>         
            </sup>
        <? endif;?>
    <? endif;?>
</h1>

<h3>
    <button value="/goods/update-bestname/<?= $goods->getId()?>" class="btn btn-info btn-xs refresh-table-button"
            title="Обновить наименование">
        <span class="glyphicon glyphicon-refresh" ></span>
    </button> 
    <span>
        <?= ($bestName) ? $bestName:'Нет наименования';?>
    </span>    
</h3>

<h5>
    <?php if ($goods->getTokenGroup()):?>
        <?= $goods->getTokenGroup()->getName();?>
    <?php else: ?>
        Группа наименований не назначена
    <?php endif?>
</h5>    
<h6>
    <button value="/name/goods-token-group/<?= $goods->getId()?>" class="btn btn-info btn-xs refresh-table-button"
            title="Присвоить группу наименований">
        <span class="glyphicon glyphicon-refresh" ></span>
    </button> 
    <?php if ($goods->getTokenGroup()):?>
        <span>
            <a href="/name/view-token-group/<?= $goods->getTokenGroup()->getId()?>" target="_blank">
                <?= $goods->getTokenGroup()->getTokenView();?>
            </a>
        </span>    
    <?php endif?>
</h6>

<div class="row">
    <div class="col-md-9">

        <table class="table table-striped">
            <tr>
                <td colspan="3">            
                    <?php if ($prev):?>
                        <a href="/goods/view/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getCode()?></a>
                    <?php endif;?>            
                </td>
                <td colspan="3" align="right">
                    <?php if ($next):?>
                        <a href="/goods/view/<?= $next[0]->getId()?>"><?= $next[0]->getCode()?>&rarr;</a>
                    <?php endif;?>                            
                </td>
            </tr>
            <tr>
                <th>

                </th>
                <th>
                    <?//= $randRawprices[0]->getUnknownProducer()->getName()?>
                </th>
                <td colspan="3" align="right">
                </td>
                <td align="right">
                </td>
            </tr>
            <?php $totalRawpriceCount = 0; ?>
            <?php foreach ($rawprices as $rawprice):?>
                <tr style="font-size: <?= ($rawprice->getStatus() == $rawprice::STATUS_PARSED) ? "inherit":"xx-small"?>">
                    <td>
                        <a href="<?= $this->url('producer', ['action' => 'article-view', 'id' => $rawprice->getCode()->getId()]);?>">
                            <?= $rawprice->getArticle();?>
                        </a> 
                        <div>
                            <?= $rawprice->getStatusAsString();?>
                        </div>
                    </td>
                    <td>
                        <div>
                            <a href="<?= $this->url('supplier', ['action' => 'view', 'id' => $rawprice->getRaw()->getSupplier()->getId()]);?>">
                                <?= $rawprice->getRaw()->getSupplier()->getName();?>
                            </a>                       
                        </div>
                        <div>
                            <a href="<?= $this->url('producer', ['action' => 'unknown-view', 'id' => $rawprice->getUnknownProducer()->getId()]);?>">
                                <?= $rawprice->getUnknownProducer()->getName();?>
                            </a>                       
                        </div>
                    </td>
                    <td>
                        <a href="<?= $this->url('rawprice', ['action' => 'view', 'id' => $rawprice->getId()]);?>">
                            <?= $rawprice->getGoodname();?>
                        </a>    
                        <?php $tokens = $rawprice->getTokens(); ?>
                        <?php if(count($tokens)):?>  
                            <div>    
                                <?php foreach($tokens as $token):?>
                                    <span style="font-size: xx-small; font-weight: <?= ($token->getStatus() == $token::IS_DICT) ? 'bold':'normal' ?>">
                                        <a href="/name/view-token/<?= $token->getId() ?>"><?= $token->getLemma() ?></a>
                                    </span>
                                <?php endforeach;?>
                            </div>        
                        <?php endif;?>                                                
                    </td>
                    <td>
                        <?php $oemIntersect = $articleManager->oemRawpricesIntersect($rawprices, $rawprice); ?>
                        <?php foreach($rawprice->getOemRaw() as $oemRaw): ?>
                            <a href="<?= $this->url('oem', ['action' => 'view-on-code'], ['query' => ['code' => $oemRaw->getCode()]]);?>">
                                <span style="font-size: xx-small; color: <?= (in_array($oemRaw->getCode(), $oemIntersect)) ? 'green':'inherit' ?>"><?= $oemRaw->getCode()?></span>
                            </a>    
                        <?php endforeach;?>
                    </td>
                    <td align="right">
                        <?= number_format($rawprice->getRealPrice(), 2, '.', '');?>
                    </td>
                    <td align="right">
                        <?= $rawprice->getRealRest();?>
                    </td>
                </tr>
            <?php endforeach;?>        
            <tr>
                <th colspan="4">
                    Всего
                </th>
                <td align="right">
                </td>
                <td align="right">
                    <b><?//= $totalRawpriceCount ?></b>
                </td>
            </tr>
        </table>
        <div>
            <?php foreach($images as $key => $imageFolder):?>
                <?php foreach ($imageFolder as $path): ?>
                    <img src="<?= $path ?>" alt="<?= $key ?>" height="100">
                <?php endforeach;?>            
            <?php endforeach;?>
        </div>
    </div>
    <div class="col-md-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <span>
                            <a href="/producer/article-view/?code=<?=$goods->getCode()?>">
                                <?= $goods->getCode();?>
                            </a>
                        </span>
                        <span>
                            <a href="/producer/view/<?=$goods->getProducer()->getId()?>">
                                <?= $goods->getProducer()->getName();?>
                            </a>
                        </span>    
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            AplId: 
                            <?php if ($goods->getAplId()): ?>
                            <a href="https://autopartslist.ru/goods/view/id/<?= $goods->getAplId() ?>" target="_blank">
                                    <?= $goods->getAplId()?>
                                </a>
                            <?php else: ?>
                                <?= $goods->getAplId()?>
                            <? endif; ?>    
                        </div>
                        <div class="pull-right">
                            <button value="/apl/good-apl-id/<?= $goods->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить АПЛ Ид">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            Поиск в TecDoc: 
                        </div>
                        <div class="pull-right">
                            <button value="/goods/external-api-search/<?= $goods->getId()?>" class="btn btn-info btn-xs show-button"
                                    title="Посик в TecDocId">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            TecDocId: 
                        </div>
                        <div class="pull-right">
                            <button value="/goods/external-api/<?= $goods->getId()?>" class="btn btn-info btn-xs show-button"
                                    title="Обновить TecDocId">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            TecDoc машины: 
                        </div>
                        <div class="pull-right">
                            <button value="/goods/external-api-car/<?= $goods->getId()?>" class="btn btn-info btn-xs show-button"
                                    title="Обновить TecDocId">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left">
                            TecDoc Картинка: 
                        </div>
                        <div class="pull-right">
                            <button value="/goods/external-api-image/<?= $goods->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                    title="Обновить картинку из TecDoc">
                                <span class="glyphicon glyphicon-refresh" ></span>
                            </button>                             
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('.show-button').on('click', function(e) {
        var url = e.currentTarget.value;

        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    dialog = bootbox.dialog({
                        message: '<div><i class="fa fa-spin fa-spinner"></i>'+objectToHtml(data.message)+'</div>',
                        closeButton: true,
                        size: 'large'
                    });
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })        
</script>
