<?php
use Application\Entity\Oem;

$this->headTitle($goods->getCode().' '.$goods->getProducer()->getName().' '.$goods->getName());

$this->mainMenu()->setActiveItemId('rb');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Товары'=>$this->url('goods'),
            $goods->getName()=>$this->url('goods', ['action'=>'view', 'id'=>$goods->getId()])
            ]);

$priceCols = $goodsManager->priceCols($goods);
?>

<style>
    .modal-body {
        height: 400px;
        overflow-y: scroll;
    }    
</style>


<div class="row">
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-12">
                <h3>
                    <button value="/goods/update-best-name/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                            title="Обновить наименование">
                        <span class="glyphicon glyphicon-refresh" ></span>
                    </button> 
                    <?php if ($goods->getName()): ?>
                        <?= $this->escapeHtml($goods->getName()); ?>
                    <?php endif;?>
                </h3>
                <h6>
                    <button value="/name/update-description/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                            title="Обновить описание">
                        <span class="glyphicon glyphicon-refresh" ></span>
                    </button> 
                    <?php if ($goods->getDescription()): ?>
                        <?= $this->escapeHtml($goods->getDescription()); ?>
                    <?php endif;?>                    
                </h6>
                <table class="table table-striped">
                    <tr>
                        <td colspan="3">            
                            <?php if ($prev):?>
                                <a href="/goods/view/<?= $prev[0]->getId()?>">&larr;<?= $prev[0]->getCode()?></a>
                            <?php endif;?>            
                        </td>
                        <td colspan="3" align="right">
                            <?php if ($next):?>
                                <a href="/goods/view/<?= $next[0]->getId()?>"><?= $next[0]->getCode()?>&rarr;</a>
                            <?php endif;?>                            
                        </td>
                    </tr>
                </table>                
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
<!--                <div class="thumbnail">
                    <div class="caption panel-body small">
                        <button value="/goods/upload-image-form/<?= $goods->getId() ?>" class="btn btn-info btn-xs"
                                data-toggle="modal" data-target="#modal-dialog" title="Добавить картинку">
                            <span class="glyphicon glyphicon-export" >Добавить картинку</span>
                        </button>                            
                    </div>                    
                </div>-->
                <?php foreach($images as $image):?>
                    <?php if ($image->getPublicPath()):?>
                        <div class="thumbnail">
                            <?php if (file_exists($image->getPath())):?>
                                <?php if (mime_content_type($image->getPath()) == 'application/pdf'):?>
                                    <a href="<?= $image->getPublicPath()?>" download>
                                        <span class="glyphicon glyphicon-download"></span>
                                        <?= $image->getName() ?>
                                    </a>
                                <?php else:?>
                                    <a href="<?= $image->getPublicPath() ?>" target="_blank">
                                        <img src="<?= $image->getPublicPath() ?>" class="img-thumbnail" alt="<?= $image->getName() ?>">
                                    </a>
                                <?php endif; ?>
                            <?php else:?>
                                <a href="<?= $image->getPublicPath() ?>" target="_blank">
                                    <span class='glyphicon glyphicon-picture'><?= $image->getName() ?></span>
                                </a>    
                            <?php endif; ?>
                            <div class="caption panel-body small">
                                <div class="pull-left">
                                    <span><?= $image->getStatusAsString();?></span> 
                                    <span><?= $image->getSimilarAsString();?></span> 
                                    <?php if (file_exists($image->getPath())):?>
                                        <span><?= mime_content_type($image->getPath()) ?></span>
                                    <?php endif; ?>
                                </div>
                                <div class="pull-right">                                    
                                    <button value="/goods/delete-image/<?= $image->getId()?>" class="btn btn-warning btn-xs this-delete"
                                            title="Удалить">
                                        <span class="glyphicon glyphicon-remove" ></span>
                                    </button>                             
                                </div>                                                                            
                            </div>
                        </div>    
                    <?php endif; ?>    
                <?php endforeach;?>
            </div>
            <div class="col-md-9">
                <ul class="nav nav-tabs" id="featureTab" role="tablist">
                    <li role="presentation"><a href="#price" role="tab" id="price-tab" data-toggle="tab" aria-controls="price" aria-expanded="true">Прайсы <span id="priceBadge" class="badge">0</span></a></li>
                    <li role="presentation"><a href="#home" role="tab" id="home-tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Описание <span id="homeBadge" class="badge"><?= count($goods->getAttributeValues()); ?></span></a></li>
                    <li role="presentation"><a href="#oem" role="tab" id="oem-tab" data-toggle="tab" aria-controls="oem" aria-expanded="true">Номера <span id="oemBadge" class="badge">0</span></a></li>
                    <li role="presentation"><a href="#linked" role="tab" id="linked-tab" data-toggle="tab" aria-controls="linked" aria-expanded="true">Применимость <span id="linkedBadge" class="badge">0</span></a></li>
                    <li role="presentation"><a href="#prices" role="tab" id="price-tab" data-toggle="tab" aria-controls="prices" aria-expanded="true">Цены <span id="pricesBadge" class="badge"><?= $goods->getFormatMeanPrice()?></span></a></li>
                </ul>

                <div class="tab-content" id="featureTabContent">
                    <div class="tab-pane fade" role="tabpanel" id="home" aria-labelledby="home-tab">
                        <table class="table table-bordered">
                            <p>
                                <?php foreach ($goods->getAttributeValues() as $attributeValue):?>
                                    <tr style="text-decoration: <?= $attributeValue->getAttribute()->getStatusDecorationAsString()?>">
                                        <td align='right'>
                                            <a href="#" 
                                               class="editable" data-type="text" 
                                               data-pk="<?= $attributeValue->getAttribute()->getId()?>" 
                                               data-name="name" 
                                               data-url="/goods/attribute-edit">
                                                <?= $attributeValue->getAttribute()->getName()?>
                                            </a>
                                        </td>
                                        <td width="5">
                                            <input type="checkbox" class="similarGoodCheckbox checkbox" 
                                                   data-toggle='tooltip' data-original-title="Использовать в аналогичных товарах"
                                                   value="<?= $attributeValue->getAttribute()->getId()?>" <?= $attributeValue->getAttribute()->getSimilarGoodAsHtml()?>/>
                                        </td>
                                        <td width="5">
                                            <input type="checkbox" class="toBestNameCheckbox checkbox" 
                                                   data-toggle='tooltip' data-original-title="Использовать в наименовании"
                                                   value="<?= $attributeValue->getAttribute()->getId()?>" <?= $attributeValue->getAttribute()->getToBestNameAsHtml()?>/>
                                        </td>
                                        <td>
                                            <?= $attributeValue->getAttributeValue()->getValue();?>
                                        </td>
                                        <td width="10">
                                            <button value="/goods/delete-attribute/<?= $attributeValue->getAttribute()->getId()?>" type="button"
                                                    class="btn btn-default btn-xs this-delete" title="Не показывать">
                                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                            </button>
                                        </td>
                                    </tr>                                              
                                <?php endforeach;?>
                            </p>
                        </table>                    
                        <table class="table table-bordered">
                            <p>
                                <?php foreach ($titleFeatures as $titleFeature):?>
                                    <tr>
                                        <td align='right' width="5">
                                            <?= $titleFeature['frequency']?>
                                        </td>
                                        <td colspan="3">
                                            <?= $titleFeature['title']?>
                                        </td>
                                        <td width="10">
                                            <?= $titleFeature['displayLemma']?>
                                        </td>
                                    </tr>                                              
                                <?php endforeach;?>
                            </p>
                        </table>                    
                    </div>
                    <div class="tab-pane fade" role="tabpanel" id="oem" aria-labelledby="oem-tab">
                        <div id="oemToolbar">
                            <div class="form-inline" role="form">
                                <button value="/oem/oem-form/<?= $goods->getId() ?>" type="button" class="btn btn-default" title="Добавить" data-toggle="modal" data-target="#modal-dialog">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                                <div class="form-group">
                                    <input name="search" style="width: 200px" class="form-control" type="text" placeholder="Поиск">
                                </div>
                                <button id="oemOk" type="submit" class="btn btn-default">OK</button>
                                <select style="width: 200px" class="form-control" id='oemSourceSelect'>
                                    <option value="null" selected>все источники</option>
                                    <?php foreach (Oem::getSourceList() as $key => $value):?>
                                        <option value="<?= $key?>"><?= $value?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </div>
                        <table id="oemTable" 
                            data-toggle="table" 
                            data-url="/goods/oem-content/<?= $goods->getId()?>"
                            data-side-pagination="server"
                            data-pagination="true" 
                            data-page-list="[5, 10, 20, 50]"
                            data-toolbar="#oemToolbar"
                            data-show-refresh="true"
                            data-show-toggle="true"
                            data-query-params="oemQueryParams"
                            data-response-handler="responseHandler"
                            >
                            <thead>
                                <tr>
                                     <th data-field="id" data-type="numeric">ID</th>
                                     <th data-field="oeNumber" data-formatter="oeNumberFormatter">Номер</th>
                                     <th data-field="brandName">Бренд</th>
                                     <th data-field="source" data-formatter="sourceFormatter">Источник</th>
                                     <!--<th data-field="status" data-formatter="statusFormatter">Статус</th>-->
                                     <th data-field="status" data-formatter="oemActiveFormatter"></th>
                                </tr>                
                            </thead>
                        </table>
                    </div>
                    <div class="tab-pane fade" role="tabpanel" id="linked" aria-labelledby="linked-tab">
                        <table id="linkedTable" 
                            data-toggle="table" 
                            data-url="/goods/car-content/<?= $goods->getId()?>"
                            data-side-pagination="server"
                            data-pagination="true" 
                            data-page-list="[5, 10, 20, 50]"
                            data-toolbar="#linkedToolbar"
                            data-show-refresh="true"
                            data-show-toggle="true"
                            data-query-params="linkedQueryParams"
                            data-response-handler="responseHandler"
                            >
                            <thead>
                                <tr>
                                     <th data-field="id" data-sortable="true" data-type="numeric">ID</th>
                                     <th data-field="tdId" data-sortable="true" data-type="numeric">TD</th>
                                     <th data-field="aplId" data-sortable="true" data-type="numeric">APL</th>
                                     <th data-field="fullName" data-sortable="true" data-formatter="carFormatter">Машина</th>
                                     <th data-field="goodCount" data-sortable="true">Товаров</th>
                                 </tr>                
                            </thead>
                        </table>
                    </div>
                    <div class="tab-pane fade" role="tabpanel" id="price" aria-labelledby="price-tab">
                        <div id="priceToolbar">
                            <div class="form-inline" role="form">
                                <select style="width: 200px" class="form-control" id='priceStatusSelect'>
                                    <?php foreach ($priceStatuses as $key => $value):?>
                                        <option value="<?= $key?>" <?= ($key == 2) ? 'selected':'' ?>><?= $value?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </div>
                        <table id="priceTable" 
                            data-toggle="table" 
                            data-url="/goods/price-content/<?= $goods->getId()?>"
                            data-side-pagination="server"
                            data-pagination="true" 
                            data-page-list="[5, 10, 20, 50]"
                            data-toolbar="#priceToolbar"
                            data-show-refresh="true"
                            data-show-toggle="true"
                            data-query-params="priceQueryParams"
                            data-response-handler="responseHandler"
                            >
                            <thead>
                                <tr>
                                     <!--<th data-field="id" data-type="numeric">ID</th>-->
                                     <th data-field="supplier" data-formatter="supplierFormatter">Поставщик</th>
                                     <th data-field="code" data-formatter="codeFormatter">Артикул</th>
                                     <th data-field="goodname" data-formatter="goodnameFormatter">Описание</th>
                                     <th data-field="rest" data-align='right'>Наличие</th>
                                     <th data-field="price" data-formatter="priceFormatter" data-align='right'>Цена</th>
                                     <th data-field="statusEx" data-formatter="statusExFormatter" data-cell-style="cellStatusExStyle"></th>
                                 </tr>                
                            </thead>
                        </table>
                    </div>
                    <div class="tab-pane fade" role="tabpanel" id="prices" aria-labelledby="prices-tab">
                        <p>
                            <div class="row">
                                <div class="col-md-10">
                                    <table class="table table-bordered">
                                        <tr>
                                            <td width='30%'>
                                                Минимальная закупка
                                            </td>
                                            <td width="5"></td>
                                            <td align='right'>
                                                <?= $goods->getFormatMinPrice()?>
                                            </td>
                                        </tr>                                              
                                        <tr>
                                            <td>
                                                Средняя закупка
                                            </td>
                                            <td></td>
                                            <td align='right'>
                                                <?= $goods->getFormatMeanPrice()?>
                                            </td>
                                        </tr>                                              
                                        <tr>
                                            <td>
                                                Фиксированная продажа
                                            </td>
                                            <td></td>
                                            <td align='right'>
                                                <a href="#" 
                                                   class="editable" data-type="text" 
                                                   data-pk="<?= $goods->getId()?>" 
                                                   data-name="fixPrice" 
                                                   data-url="/goods/update-fix-price">
                                                    <?= $goods->getFixPrice()?>
                                                </a>
                                            </td>
                                        </tr> 
                                        <?php if ($rate):?>
                                            <tr>
                                                <td>Расценка</td>
                                                <td></td>
                                                <td><a href="<?= $this->url('rate', ['action' => 'view', 'id' => $rate->getId()])?>" target="_blank"><?= $rate->getName()?></a></td>
                                            </tr>
                                        <?php endif; ?>    
                                        <tr>
                                            <td>
                                                Розница продажа
                                            </td>
                                            <td><?= round($priceCols[0]['percent'])?>%</td>
                                            <td align='right'>
                                                <?= $goods->getPrice()?>
                                            </td>
                                        </tr>                                              
                                        <tr>
                                            <td>
                                                VIP продажа
                                            </td>
                                            <td><?= round($priceCols[1]['percent'])?>%</td>
                                            <td align='right'>
                                                <?= $priceCols[1]['price']?>
                                            </td>
                                        </tr>                                              
                                        <tr>
                                            <td>
                                                ОПТ2 продажа
                                            </td>
                                            <td><?= round($priceCols[2]['percent'])?>%</td>
                                            <td align='right'>
                                                <?= $priceCols[2]['price']?>
                                            </td>
                                        </tr>                                              
                                        <tr>
                                            <td>
                                                ОПТ3 продажа
                                            </td>
                                            <td><?= round($priceCols[3]['percent'])?>%</td>
                                            <td align='right'>
                                                <?= $priceCols[3]['price']?>
                                            </td>
                                        </tr>                                              
                                        <tr>
                                            <td>
                                                ОПТ4 продажа
                                            </td>
                                            <td><?= round($priceCols[4]['percent'])?>%</td>
                                            <td align='right'>
                                                <?= $priceCols[4]['price']?>
                                            </td>
                                        </tr>                                              
                                        <tr>
                                            <td>
                                                ОПТ5 продажа
                                            </td>
                                            <td><?= round($priceCols[5]['percent'])?>%</td>
                                            <td align='right'>
                                                <?= $priceCols[5]['price']?>
                                            </td>
                                        </tr>                                              
                                    </table>                                                    
                                </div>
                                <div class="col-md-2">
                                    <button value="/goods/update-prices/<?= $goods->getId()?>" class="btn btn-info btn-xs refresh-table-button"
                                            title="Обновить">
                                        Обновить
                                        <span class="glyphicon glyphicon-refresh" ></span>
                                    </button>                                 
                                </div>
                            </div>                            
                        </p>
                    </div>
                </div>
            </div>    
        </div>
    </div>
    <div class="col-md-3" id="side-nav">
        <div class="nav nav-stacked nav-list affix">
            <div class="col-xs-12">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <span>
                                <a href="/producer/article-view/?code=<?=$goods->getCode()?>">
                                    <?= $goods->getCode();?>
                                </a>
                            </span>
                            <span>
                                <a href="/producer/view/<?=$goods->getProducer()->getId()?>">
                                    <?= $goods->getProducer()->getName();?>
                                </a>
                            </span>    
                        </div>
                        <div class="pull-right">
                            <a href="/goods/delete/<?= $goods->getId()?>" class="btn btn-danger btn-xs show-button"
                                    title="Удалить, если возможно">
                                <span class="glyphicon glyphicon-remove" ></span>
                            </a>                                                         
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <small>
                            <a href="<?= $this->url('group', ['action' => 'view', 'id' => $goods->getGenericGroup()->getId()])?>" target="_blank">
                                <?= $goods->getGenericGroup()->getName().' ('.$goods->getGenericGroup()->getTdId().')'?>
                                <?php if ($goods->getGenericGroup()->getAplId()):?>
                                    <?= '('.$goods->getGenericGroup()->getAplId().')';?>
                                <?php endif; ?>
                            </a>                                                    
                        </small>
                    </div>
                    <div class="panel-body">
                        <button value="/name/goods-token-group/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                                title="Присвоить группу наименований">
                            <span class="glyphicon glyphicon-refresh" ></span>
                        </button> 
                        <?php if ($goods->getTokenGroup()):?>
                            <small>
                                <?php if ($goods->getTokenGroup()):?>
                                    <a href="/name/view-token-group/<?= $goods->getTokenGroup()->getId()?>" target="_blank">
                                        <?= ($goods->getTokenGroup()->getName()) ? $goods->getTokenGroup()->getName():'---';?>
                                    </a>
                                <?php else: ?>
                                    Группа наименований не назначена
                                <?php endif?>
                            </small>    
                        <?php endif?>
                    </div>
                </div>    
            </div>
            <div class="col-xs-6">
                <div class="panel-group">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            Обновления из ТекДок
                        </div>
                        <div class="panel-body">
                            <div class="pull-left">
                                Поиск в TecDoc: 
                            </div>
                            <div class="pull-right">
                                <button value="/goods/external-api-search/<?= $goods->getId()?>" class="btn btn-info btn-xs show-button"
                                        title="Поиск в TecDocId">
                                    <span class="glyphicon glyphicon-refresh" ></span>
                                </button>                             
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="pull-left">
                                TecDocId: 
                            </div>
                            <div class="pull-right">
                                <button value="/goods/external-api/<?= $goods->getId()?>" class="btn btn-info btn-xs show-button"
                                        title="Обновить TecDocId">
                                    <span class="glyphicon glyphicon-refresh" ></span>
                                </button>                             
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="pull-left">
                                TecDoc группа: 
                            </div>
                            <div class="pull-right">
                                <button value="/goods/generic-group/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                                        title="Обновить группу">
                                    <span class="glyphicon glyphicon-refresh" ></span>
                                </button>                             
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="pull-left">
                                TecDoc описание: 
                            </div>
                            <div class="pull-right">
                                <button value="/goods/attribute/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                                        title="Обновить описание">
                                    <span class="glyphicon glyphicon-refresh" ></span>
                                </button>                             
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="pull-left">
                                <span class="<?= $goods->getStyleStatusOem()?>">
                                    TecDoc номера: 
                                </span> 
                            </div>
                            <div class="pull-right">
                                <button value="/goods/good-oem/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                                        title="Обновить номера">
                                    <span class="glyphicon glyphicon-refresh" ></span>
                                </button>                             
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="pull-left">
                                TecDoc машины: 
                            </div>
                            <div class="pull-right">
                                <button value="/goods/external-api-car/<?= $goods->getId()?>" class="btn btn-info btn-xs show-button"
                                        title="Обновить TecDocId">
                                    <span class="glyphicon glyphicon-refresh" ></span>
                                </button>                             
                                <button value="/goods/good-cars/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                                        title="Обновить машины">
                                    <span class="glyphicon glyphicon-refresh" ></span>
                                </button>                             
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="pull-left">
                                TecDoc Картинка: 
                            </div>
                            <div class="pull-right">
                                <button value="/goods/upload-image-form/<?= $goods->getId() ?>" class="btn btn-info btn-xs"
                                        data-toggle="modal" data-target="#modal-dialog" title="Добавить картинку">
                                    <span class="glyphicon glyphicon-export" ></span>
                                </button>                            
                                <button value="/goods/external-api-image/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                                        title="Обновить картинку из TecDoc">
                                    <span class="glyphicon glyphicon-refresh" ></span>
                                </button>                             
                            </div>
                        </div>
                    </div>    
                </div>                
            </div>
            <div class="col-xs-6">
                <div class="panel-group">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            Обновления в АПЛ
                        </div>
                        <div class="panel-body">
                            <div class="pull-left">
                                AplId: 
                                <?php if ($goods->getAplId()): ?>
                                    <a href="https://autopartslist.ru/goods/view/id/<?= $goods->getAplId() ?>" target="_blank">
                                        <?= $goods->getAplId()?>
                                    </a>
                                <?php else: ?>
                                    <?= $goods->getAplId()?>
                                <?php endif; ?>    
                            </div>
                            <div class="pull-right">
                                <button value="/apl/good-apl-id/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                                        title="Обновить АПЛ Ид">
                                    <span class="glyphicon glyphicon-refresh" ></span>
                                </button>
                            </div>    
                        </div>    
                        <?php if ($goods->getAplId()):?>
                            <div class="panel-body">
                                <div class="pull-left">
                                    Группа <?= $goods->getGroupAplAsString()?>
                                </div>
                                <div class="pull-right">                        
                                    <button value="/apl/group-apl-id/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-table-button"
                                            title="Получить группу">
                                        <span class="glyphicon glyphicon-refresh" ></span>
                                    </button>
                                    <button value="/apl/ex-group/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-button"
                                            title="Обмен групп">
                                        <span class="glyphicon glyphicon-export" ></span>
                                    </button>
                                </div>    
                            </div>
                            <div class="panel-body">
                                <div class="pull-left">
                                    Номера
                                </div>
                                <div class="pull-right">                        
                                    <button value="/apl/ex-oem/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-button"
                                            title="Обмен номеров">
                                        <span class="glyphicon glyphicon-export" ></span>
                                    </button>
                                </div>    
                            </div>
                            <div class="panel-body">
                                <div class="pull-left" class="<?= $goods->getStyleStatusRawpriceEx()?>">
                                    Картинки 
                                </div>
                                <div class="pull-right">                        
                                    <button value="/apl/ex-img/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-button"
                                            title="Обмен картинок">
                                        <span class="glyphicon glyphicon-export" ></span>
                                    </button>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="pull-left">
                                    Машины 
                                </div>
                                <div class="pull-right">                        
                                    <button value="/apl/ex-car/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-button"
                                            title="Обмен машин">
                                        <span class="glyphicon glyphicon-export" ></span>
                                    </button>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="pull-left">
                                    <span class="<?= $goods->getStyleStatusRawpriceEx()?>">
                                        Строки прайсов
                                    </span> 
                                </div>
                                <div class="pull-right">                                                
                                    <button value="/apl/ex-rawprice/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-button"
                                            title="Обмен строк прайсов">
                                        <span class="glyphicon glyphicon-export" ></span>
                                    </button>                             
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="pull-left">
                                    Описания 
                                </div>
                                <div class="pull-right">                                                
                                    <button value="/apl/ex-attr/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-button"
                                            title="Обмен описания">
                                        <span class="glyphicon glyphicon-export" ></span>
                                    </button>                             
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="pull-left">
                                    Наименование 
                                </div>
                                <div class="pull-right">                                                
                                    <button value="/apl/update-good-name/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-button"
                                            title="Обновить наименование">
                                        <span class="glyphicon glyphicon-export" ></span>
                                    </button>                             
                                </div>
                            </div>                        
                            <div class="panel-body">
                                <div class="pull-left">
                                    Цены 
                                </div>
                                <div class="pull-right">                                                
                                    <button value="/apl/update-good-price/<?= $goods->getId()?>" class="btn btn-default btn-xs refresh-button"
                                            title="Обновить цены">
                                        <span class="glyphicon glyphicon-export" ></span>
                                    </button>                             
                                </div>
                            </div>                        
                        <?php endif;?>
                    </div>    
                </div>                
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function () {
        $("[data-toggle='tooltip']").tooltip();
    });

    $(window).on('load', function() {
        $('.nav-tabs a:first').tab('show');
        $('.editable').editable();
    });
    
    $('#featureTab a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    })
    
    function refreshLinkedTable(){
        $('#linkedTable').bootstrapTable('refresh');
    }

    function refreshOemTable(){
        $('#oemTable').bootstrapTable('refresh');
    }

    function refreshPriceTable(){
        $('#priceTable').bootstrapTable('refresh');
    }

    var linkedTable = $('#linkedTable').bootstrapTable({
        onLoadSuccess: function(res){
            $('#linkedBadge').html($('#linkedTable').bootstrapTable('getOptions').totalRows)
        }
    });
    
    var oemTable = $('#oemTable').bootstrapTable({
        onLoadSuccess: function(res){
            $('#oemBadge').html($('#oemTable').bootstrapTable('getOptions').totalRows)
        }
    });

    var priceTable = $('#priceTable').bootstrapTable({
        onLoadSuccess: function(res){
            $('#priceBadge').html($('#priceTable').bootstrapTable('getOptions').totalRows)
        }
    });

    var oemOk = $('#oemOk');

    $(function () {
        oemOk.click(function () {
            oemTable.bootstrapTable('refresh');
        });
        $('#priceStatusSelect').change(function (){
            $('#priceTable').bootstrapTable('refresh');
        })
        $('#oemSourceSelect').change(function (){
            $('#oemTable').bootstrapTable('refresh');
        })
    });
    
    
    
    function tabQueryParams(tab, params) {
        $(tab +'Toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $(tab + ' .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $(tab + ' li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function oemQueryParams(params) {
        params.source = $('#oemSourceSelect').val();
        return tabQueryParams('#oem', params);
    }
    
    function linkedQueryParams(params) {
        return tabQueryParams('#linked', params);
    }
    
    function priceQueryParams(params) {
        params.status = $('#priceStatusSelect').val();
        return tabQueryParams('#price', params);
    }
    
    function responseHandler(res) {
        return res;
    }       
    
    function sourceFormatter(value){
        switch(value){
            <?php foreach ($oemSources as $key => $value):?>
                case "<?= $key?>": result="<?= $value?>"; break;      
            <?php endforeach;?>            
            default: result = 'Неизвестно'; break;
        }
        
        return result;
    }    
    
    function statusFormatter(value){
        switch(value){
            <?php foreach ($oemStatuses as $key => $value):?>
                case "<?= $key?>": result="<?= $value?>"; break;      
            <?php endforeach;?>            
            default: result = 'Неизвестно'; break;
        }
        
        return result;
    }    
    
    function oeNumberFormatter(value, row){
        if (row.source == <?= Oem::SOURCE_INTERSECT?>){
            return '<a href="/goods/view/'+row.intersectGoodId+'" target="_blank">'+value+'</a>'
        } 
        return value;
    }
    
    function oemActiveFormatter(value, row){
        if (value == 1){
            status = 2;
        } else {
            status = 1;
        }            
        var url = '/oem/oem-status-form/'+row.id+'?status='+status;
        var btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs this-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Изменить доступность"'; 
        btn += ' onclick="tableRowDelete(\''+url+'\', \'oemTable\')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        
        var editUrl = '/oem/oem-form/<?= $goods->getId() ?>?oem='+row.id;
        var editBtn = '<button';
        if (row.source != 3){
            editBtn += ' disabled="disabled"';
        }
        editBtn += ' type="button" data-toggle="modal" data-target="#modal-dialog"';
        editBtn += ' class="btn btn-default btn-xs"';
        editBtn += ' aria-label="Left Align"'; 
        editBtn += ' title="Изменить"'; 
        editBtn += ' value="'+editUrl+'">';
        editBtn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        editBtn += '</button>';
        return '<nobr>'+editBtn+' '+btn+'</nobr>';
    }    
    
    function carFormatter(value, row) {
        return '<a href="/car/view/'+row.id+'" target="_blank">'+value+'</a>';
    }    
    
    function goodnameFormatter(value, row) {
        return '<a href="/rawprice/view/'+row.id+'" target="_blank">'+value+'</a>';
    }    
    
    function producerFormatter(value, row) {
        return '<a href="/producer/unknown-view/'+row.producerId+'" target="_blank">'+value+'</a>';
    }    
    
    function codeFormatter(value, row) {
        return '<a href="/producer/article-view/'+row.codeId+'" target="_blank">'+value+'</a> ' + producerFormatter(row.producer, row);
    }    
    
    function statusExFormatter(value, row) {
        return '<span></span>' ;
    }  
    
    function cellStatusExStyle(value, row, index) {
        var classes = [
          'light',
          'success',
          'warning'
        ]
        return {
          classes: classes[value-1]
        }
    }    
    
    function supplierFormatter(value, row) {
        var priceDate = new Date(row.dateCreated);
        var priceDateStr = priceDate.getDate()+'-'+ (priceDate.getMonth()+1) + ' ' + priceDate.getHours() + ':' + priceDate.getMinutes();
        return '<a href="/supplier/view/'+row.supplierId+'" target="_blank">'+value+'</a>' + '<br/>' + priceDateStr ;
    }    
    
    function inSigma(data){
        if (data.inSigma == false){
            $('#rawprice'+data.id).css('color', 'red');
        }    
    }
    
    function priceFormatter(value, row){
        $.post(
            '/goods/in-sigma-content/<?= $goods->getId()?>?rawprice='+row.id,
            null,
            inSigma                
        );
        return [
            '<span id="rawprice'+row.id+'">'+Math.round(parseFloat(value.replace(/\s/g, '')))+'</span>',
        ].join(''); 
    }        
    
    $('.show-button').on('click', function(e) {
        var url = e.currentTarget.value;

        if (url){
            var dialog = bootbox.dialog({
                message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                closeButton: false
            });

            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                    dialog.modal('hide');
                    dialog = bootbox.dialog({
                        message: '<div><i class="fa fa-spin fa-spinner"></i>'+objectToHtml(data.message)+'</div>',
                        closeButton: true,
                        size: 'large'
                    });
                })
                .fail(function () {
                    dialog.modal('hide');
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })        

    $('.similarGoodCheckbox').on('change', function(e, node) {
        var url = "/goods/attribute-similar-good-edit";

        if (url){
            $.ajax({
                type: 'POST',
                url: url,
                data: {pk: e.target.value, value: e.target.checked}
            })
                .done(function (data) {
                })
                .fail(function () {
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })        
    
    $('.toBestNameCheckbox').on('change', function(e, node) {
        var url = "/goods/attribute-to-best-name";

        if (url){
            $.ajax({
                type: 'POST',
                url: url,
                data: {pk: e.target.value, value: e.target.checked}
            })
                .done(function (data) {
                })
                .fail(function () {
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })        
    
</script>
