<?php
$this->headTitle('Редактировать '.$courier->getName());

$this->mainMenu()->setActiveItemId('client');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Транспортные компании'=>$this->url('courier'),
            $courier->getName()=>$this->url('courier', ['action'=>'edit'])
            ]);

$form = $this->form;

$form->get('aplId')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Апл Id'
    ]);

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Наименование'
    ]);

$form->get('comment')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Описание'
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('site')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Сайт'
    ]);

$form->get('track')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Отслеживание'
    ]);

$form->get('calculator')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Калькулятор'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Изменить данные <?= $courier->getName()?></h1>

<p>
    Заполните форму и нажмите <i>Сохранить</i>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('aplId')); ?>
            <?= $this->formElement($form->get('aplId')); ?>
            <?= $this->formElementErrors($form->get('aplId')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('comment')); ?>
            <?= $this->formElement($form->get('comment')); ?>
            <?= $this->formElementErrors($form->get('comment')); ?>                  
        </div>                        
        <div class="form-group">
            <?= $this->formLabel($form->get('site')); ?>
            <?= $this->formElement($form->get('site')); ?>
            <?= $this->formElementErrors($form->get('site')); ?>                  
        </div>                        
        <div class="form-group">
            <?= $this->formLabel($form->get('track')); ?>
            <?= $this->formElement($form->get('track')); ?>
            <?= $this->formElementErrors($form->get('track')); ?>                  
        </div>                        
        <div class="form-group">
            <?= $this->formLabel($form->get('calculator')); ?>
            <?= $this->formElement($form->get('calculator')); ?>
            <?= $this->formElementErrors($form->get('calculator')); ?>                  
        </div>                        
                
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
