<?php
$this->headTitle($courier->getName());

$this->mainMenu()->setActiveItemId('client');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Транспортные компании'=>$this->url('courier'),
            $courier->getName()=>$this->url('courier', ['action'=>'view', 'id'=>$courier->getId()])
            ]);
?>


<h1><?=$courier->getName()?></h1>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
<a class="btn btn-default" href="<?= $this->url('courier', 
                    ['action'=>'edit', 'id'=>$courier->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Изменить
</a>
</p>
    
<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($courier->getId()) ?></th>
            </tr>
            <tr>
                <th>Апл Id</th>
                <td><?= $this->escapeHtml($courier->getAplId()) ?></th>
            </tr>
            <tr>
                <th>Статус:</th>
                <td><?= $this->escapeHtml($courier->getStatusAsString()) ?></th>
            </tr>
            <tr>
                <th>Описание:</th>
                <td><?= $this->escapeHtml($courier->getComment()) ?></th>
            </tr>
            <tr>
                <th>Сайт:</th>
                <td><?= $this->escapeHtml($courier->getSite()) ?></th>
            </tr>
            <tr>
                <th>Отслеживание:</th>
                <td><?= $this->escapeHtml($courier->getTrack()) ?></th>
            </tr>
            <tr>
                <th>Калькулятор:</th>
                <td><?= $this->escapeHtml($courier->getCalculator()) ?></th>
            </tr>
        </table>
    </div>
</div>