<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Добавить представителя</h3>
            </div>
            <div class="panel-body">
                <p>
                    <ol>
                        <li>
                            Перейти на страницу <a href="/members" target="_blank">пользователи</a>
                        </li>
                        <li>Нажать кнопку Добавить пользователя</li>
                        <li>Заполнить все поля и нажать кнопку Сохранить</li>
                        <li>Сообщить логин и пароль представителю</li>
                        <p><a class="btn btn-success pull-right" href="/members">Перейти в пользователи&raquo;</a></p>
                    </ol>
                </p>

            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Что-то еще</h3>
            </div>
            <div class="panel-body">
                <p>
                    
                </p>

                <p><a class="btn btn-success pull-right" href="#">Перейти &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Техподдержка</h3>
            </div>
            <div class="panel-body">
                <p>
                    
                </p>

                <p><a class="btn btn-success pull-right" href="#">Написать &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
