<div class="jumbotron">
    <h1>Приветствие <span class="zf-green">ОВОДЕНТ</span></h1>

    <p>
        
    </p>

    <p><a class="btn btn-success btn-lg" href="#">Перейти &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Что-то важное</h3>
            </div>
            <div class="panel-body">
                <p>
                   
                </p>

                <p><a class="btn btn-success pull-right" href="#">Перейти &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Что-то еще</h3>
            </div>
            <div class="panel-body">
                <p>
                    
                </p>

                <p><a class="btn btn-success pull-right" href="#">Перейти &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Техподдержка</h3>
            </div>
            <div class="panel-body">
                <p>
                    
                </p>

                <p><a class="btn btn-success pull-right" href="#">Написать &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
