<?php
$this->headTitle('Edit User');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Edit User'=>$this->url('application', ['action'=>'settings', 'id'=>$user->getId()])
            ]);

$form->get('aplId')->setAttributes([
    'class'=>'form-control',
    'readonly' => true, 
    ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ]);

$form->get('mailPassword')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('sign')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'John Doe'
    ]);

$form->get('birthday')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control',
    'disabled' => true,
    ]);

$form->get('roles')->setAttributes([
    'class'=>'form-control',
    'rows' => 20,
    'readonly' => true,
    ]);

$form->get('office')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Сохранить');

$form->prepare();
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>Edit User <?= $this->escapeHtml($user->getEmail()) ?></h1>
<p>
    <a class="btn btn-default" href="<?= $this->url('members',
            ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-asterisk"></span> Изменить пароль
    </a>        
</p>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('aplId')); ?>
            <?= $this->formElement($form->get('aplId')); ?>
            <?= $this->formElementErrors($form->get('aplId')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('birthday')); ?>
            <?= $this->formElement($form->get('birthday')); ?>
            <?= $this->formElementErrors($form->get('birthday')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('office')); ?>
            <?= $this->formElement($form->get('office')); ?>
            <?= $this->formElementErrors($form->get('office')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
    </div>
    <div class="col-md-6">
        
        <div class="form-group form-inline">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                  

            <?= $this->formLabel($form->get('mailPassword')); ?>
            <?= $this->formElementErrors($form->get('mailPassword')); ?>                  
            <div class="input-group">
                <?= $this->formElement($form->get('mailPassword')); ?>
                <span class="input-group-btn">
                    <button class="btn btn-default password-generator" type="button" data-toggle="tooltip" data-placement="top" title="Генератор пароля">
                        <span class="glyphicon glyphicon-qrcode"></span>
                    </button>
                </span>                                                            
            </div>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('sign')); ?>
            <?= $this->formElement($form->get('sign')); ?>
            <?= $this->formElementErrors($form->get('sign')); ?>                  
        </div>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

<script>
    $( document ).ready(function() {
        $('textarea[name="sign"]').summernote({
            lang: 'ru-RU', // default: 'en-US'
            height: 200
        });
        
    });
    
    $('.password-generator').on('click', function() {
        $.ajax({
            type: 'GET',
            url: '/admin/password-generator/'
        })
            .done(function (data) {
                if (data){
                    $('input[name=mailPassword]').val(data['password']);
                }
            })
            .fail(function (e) {
                console.log(e);
            });    
    });    
    
</script>