<?php
$this->headTitle('Settings');
$this->mainMenu()->setActiveItemId('settings');
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Settings'=>$this->url('application', ['action'=>'settings']),
            ]);
?>

<h2>Settings</h2>
<p>
    <a class="btn btn-default" href="<?= $this->url('users', 
            ['action'=>'edit', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Edit
    </a>
    <a class="btn btn-default" href="<?= $this->url('users',
            ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-asterisk"></span> Change Password
    </a>    
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></td>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></td>
            </tr>
            <tr>
                <th>Full Name:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></td>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></td>
            </tr>
        </table>
    </div>
</div>