<?php
    $this->headTitle('Расценка товаров');
    $this->mainMenu()->setActiveItemId('raw');
    
    $this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Расценка'=>$this->url('rate'),
            ]);
?>
<p>
<a class="btn btn-default" href="
    <?= $this->url('rate', ['action'=>'add-scale']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Новая шкала
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Наименование</th>
        <th>Действия</th>        
    </tr>
    
    <?php foreach ($scales as $scale): ?>
    
    <tr>
        <td><?= $this->escapeHtml($scale->getId()); ?></td>
        <td>
            <a href="<?= $this->url('rate', ['action'=>'view-scale', 'id'=>$scale->getId()]); ?>">
                <?= $this->escapeHtml($scale->getName()); ?>
            </a> 
        </td>
        <td>
            <nobr>
            <a class="btn btn-info" href="<?= $this->url('rate', 
                    ['action'=>'edit-scale', 'id'=>$scale->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Изменить
            </a>
            <a class="btn btn-danger" href="<?= $this->url('rate',
                    ['action'=>'delete-scale', 'id'=>$scale->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Удалить
            </a>
            </nobr>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>
