<?php
    $this->headTitle('Расценка товаров');
    $this->mainMenu()->setActiveItemId('raw');
    
    $this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Расценки'=>$this->url('rate'),
            ]);
?>
<p>
    <button onclick="ratePromptDialog('/rate/add')" 
            class="btn btn-default btn-xs" 
            title="Новая расценка">
        <span class="glyphicon glyphicon-plus"></span>
    </button> 
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Наименование</th>
        <th>Использовать</th>
        <th>Действия</th>        
    </tr>
    
    <?php foreach ($rates as $rate): ?>
    
    <tr>
        <td><?= $this->escapeHtml($rate->getId()); ?></td>
        <td>
            <a href="<?= $this->url('rate', ['action'=>'view', 'id'=>$rate->getId()]); ?>">
                <?= $this->escapeHtml($rate->getName()); ?>
            </a> 
        </td>
        <td>
            <input type="checkbox" class="rateStatusCheckbox" value="<?= $rate->getId()?>" <?= $rate->getStatusCheckbox()?>/>
        </td>
        <td>
            <nobr>
<!--            <a class="btn btn-info" href="<?= $this->url('rate', 
                    ['action'=>'edit', 'id'=>$rate->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Изменить
            </a>-->
            <a class="btn btn-danger" href="<?= $this->url('rate',
                    ['action'=>'delete', 'id'=>$rate->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Удалить
            </a>
            </nobr>
        </td>    
    </tr>
        
    <?php endforeach; ?>       
</table>
<a href="
    <?= $this->url('rate', ['action'=>'fix-price']); ?>">
    Фиксированные цены &gt;&gt;
</a>



<?= $this->partialLoop('\admin\log\partialLoop.phtml', $logs) ?>

<script type="text/javascript">
    
    
    /**
    * Промпт диалог
    *
    */
    function ratePromptDialog(url, initValue) {
        if (url){            
            var dialog = bootbox.prompt({ 
                size: "medium",
                value: initValue,
                title: 'Наименование расценки', 
                callback: function(result){
                    /* result = String containing user input if OK clicked or null if Cancel clicked */
                    if (result != null){
                        $.ajax({
                            type: 'GET',
                            url: url+'?prompt='+result,
                        })
                            .done(function (data) {
                                if (data == 'ok'){
                                    window.location.reload();
                                }    
                            })
                            .fail(function (e) {
                                bootbox.alert("Произошла ошибка при выполнении операции.");
                            });
                    }        
                }
            });
        }        
    }    
    
    $('.rateStatusCheckbox').on('change', function(e, node) {
        var url = "/rate/update-rate-status";

        if (url){
            $.ajax({
                type: 'POST',
                url: url,
                data: {pk: e.target.value, value: e.target.checked}
            })
                .done(function (data) {
                })
                .fail(function () {
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })        
    
</script>