<?php
    $this->headTitle('Расценка товаров');
    $this->mainMenu()->setActiveItemId('raw');
    
    $this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Расценки'=>$this->url('rate'),
            ]);
?>
<div class="row">
    <div class="col-md-9">
        <button class="btn btn-default" onclick="ratePromptDialog('/rate/add')" 
                title="Новая расценка">
            <span class="glyphicon glyphicon-plus"> Новая расценка</span>
        </button>         
    </div>
    <div class="col-md-3">
        <a href="
            <?= $this->url('rate', ['action'=>'fix-price']); ?>">
            <h4>Фиксированные цены &gt;&gt;</h4>
        </a>            
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">

           <tr>
                <th>ID</th>
                <th>Наименование</th>
                <th>Использовать</th>
                <th>Действия</th>        
            </tr>

            <?php foreach ($rates as $rate): ?>

            <tr>
                <td><?= $this->escapeHtml($rate->getId()); ?></td>
                <td>
                    <a href="<?= $this->url('rate', ['action'=>'view', 'id'=>$rate->getId()]); ?>">
                        <?= $this->escapeHtml($rate->getName()); ?>
                    </a> 
                </td>
                <td>
                    <input type="checkbox" class="rateStatusCheckbox" value="<?= $rate->getId()?>" <?= $rate->getStatusCheckbox()?>/>
                </td>
                <td>
                    <button class="btn btn-danger this-delete" onclick="tableRowDelete('/rate/delete-form/<?= $rate->getId() ?>')">
                        <span class="glyphicon glyphicon-remove"></span> Удалить
                    </button>
                </td>    
            </tr>

            <?php endforeach; ?>       
        </table>
    </div>    
</div>

<?= $this->partial('/Admin/log/partial.phtml', ['logs' => $logs, 'ident' => 'rate']) ?>        

<script type="text/javascript">
    
    
    /**
    * Промпт диалог
    *
    */
    function ratePromptDialog(url, initValue) {
        if (url){            
            var dialog = bootbox.prompt({ 
                size: "medium",
                value: initValue,
                title: 'Наименование расценки', 
                callback: function(result){
                    /* result = String containing user input if OK clicked or null if Cancel clicked */
                    if (result != null){
                        $.ajax({
                            type: 'GET',
                            url: url+'?prompt='+result,
                        })
                            .done(function (data) {
                                if (data == 'ok'){
                                    window.location.reload();
                                }    
                            })
                            .fail(function (e) {
                                bootbox.alert("Произошла ошибка при выполнении операции.");
                            });
                    }        
                }
            });
        }        
    }    
    
    $('.rateStatusCheckbox').on('change', function(e, node) {
        var url = "/rate/update-rate-status";

        if (url){
            $.ajax({
                type: 'POST',
                url: url,
                data: {pk: e.target.value, value: e.target.checked}
            })
                .done(function (data) {
                })
                .fail(function () {
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })        
    
</script>