<?php
use Application\Entity\ScaleTreshold;

$this->headTitle($rate->getName());
$this->mainMenu()->setActiveItemId('raw');
$this->pageBreadcrumbs()->setItems([
            'Home' => $this->url('home'),
            'Расценки' => $this->url('rate'),
            $rate->getName() => $this->url('rate', ['action' => 'view', 'id' => $rate->getId()]),
            ]);
        
$col = 1;
?>
<div class="row">
    <div class="col-md-9">
        <h1>
            <?= $this->escapeHtml($rate->getName()); ?>    
            <button onclick="ratePromptDialog('/rate/update-rate-name/<?= $rate->getId()?>', '<?= $this->escapeHtml($rate->getName()); ?>')" 
                    class="btn btn-default btn-xs" 
                    title="Изменить наименование расценки">
                <span class="glyphicon glyphicon-pencil" ></span>
            </button> 
        </h1>        
    </div>
    <div class="col-md-3">
        <a class="btn btn-info" href="<?= $this->url('rate',
                ['action'=>'update-rate-scale', 'id'=>$rate->getId()]); ?>">
            <span class="glyphicon glyphicon-refresh">Обновить шкалу</span> 
        </a>    
        <button class="btn btn-danger this-delete" onclick="tableRowDelete('/rate/delete-form/<?= $rate->getId() ?>')">
            <span class="glyphicon glyphicon-remove"></span> Удалить
        </button>                
    </div>
</div>    
<div class="row">
    <div class="col-md-2">
        <div class="pull-left">
            <input id="ck" type="checkbox" class="rateStatusCheckbox" value="<?= $rate->getId()?>" <?= $rate->getStatusCheckbox()?>/>
            <label for="ck">Использовать</label>
        </div>            
    </div>
    <div class="col-md-6">
        <?php if ($rate->getSupplier()):?>
            <a href="<?= $this->url('supplier', ['action' => 'view', 'id' => $rate->getSupplier()->getId()])?>">
                <?= $rate->getSupplier()->getName()?>                
            </a>
        <?php endif; ?>
        <?php if ($rate->getGenericGroup()):?>
            <a href="<?= $this->url('group', ['action' => 'view', 'id' => $rate->getGenericGroup()->getId()])?>">
                <?= $rate->getGenericGroup()->getName()?>
            </a>
        <?php endif; ?>
        <?php if ($rate->getTokenGroup()):?>
            <a href="<?= $this->url('name', ['action' => 'view-token-group', 'id' => $rate->getTokenGroup()->getId()])?>">
                <?= $rate->getTokenGroup()->getName()?>
            </a>
        <?php endif; ?>
        <?php if ($rate->getProducer()):?>
            <a href="<?= $this->url('producer', ['action' => 'view', 'id' => $rate->getProducer()->getId()])?>">
                <?= $rate->getProducer()->getName()?>
            </a>
        <?php endif; ?> 
    </div>
    <div class="col-md-4">
        Закупочные цены от <?= round($rate->getMinPrice())?> до <?= round($rate->getMaxPrice())?>.
    </div>    
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">
            <tr>
                <th rowspan="2"  align="center">
                    Порог
                </th>
                <th colspan="12"  align="center">
                    Цены и %% 
                    <a class="btn btn-warning" title="Уменьшить наценку на 10%"
                       href="<?= $this->url('rate',['action'=>'change-rate-scale', 'id'=>$rate->getId()], ['query' => ['plus' => -10]]); ?>">
                        <span class="glyphicon glyphicon-minus">10%</span> 
                    </a>    
                    <a class="btn btn-warning" title="Уменьшить наценку на 5%"
                       href="<?= $this->url('rate',['action'=>'change-rate-scale', 'id'=>$rate->getId()], ['query' => ['plus' => -5]]); ?>">
                        <span class="glyphicon glyphicon-minus">5%</span> 
                    </a>    
                    <a class="btn btn-warning" title="Уменьшить наценку на 1%"
                       href="<?= $this->url('rate',['action'=>'change-rate-scale', 'id'=>$rate->getId()], ['query' => ['plus' => -1]]); ?>">
                        <span class="glyphicon glyphicon-minus">1%</span> 
                    </a>    
                    <a class="btn btn-info" title="Сбросить изменения"
                       href="<?= $this->url('rate',['action'=>'change-rate-scale', 'id'=>$rate->getId()], ['query' => ['plus' => 0]]); ?>">
                        <span class="glyphicon glyphicon-refresh">0</span> 
                    </a>    
                    <a class="btn btn-warning" title="Увеличить наценку на 1%"
                       href="<?= $this->url('rate', ['action'=>'change-rate-scale', 'id'=>$rate->getId()], ['query' => ['plus' => 1]]); ?>">
                        <span class="glyphicon glyphicon-plus">1%</span> 
                    </a>    
                    <a class="btn btn-warning" title="Увеличить наценку на 5%"
                       href="<?= $this->url('rate', ['action'=>'change-rate-scale', 'id'=>$rate->getId()], ['query' => ['plus' => 5]]); ?>">
                        <span class="glyphicon glyphicon-plus">5%</span> 
                    </a>    
                    <a class="btn btn-warning" title="Увеличить наценку на 10%"
                       href="<?= $this->url('rate', ['action'=>'change-rate-scale', 'id'=>$rate->getId()], ['query' => ['plus' => 10]]); ?>">
                        <span class="glyphicon glyphicon-plus">10%</span> 
                    </a>    
                </th>
                <th rowspan="2"  align="center">
                    Округление
                </th>
            </tr>
            <tr>
                <th  align="center">
                    Розница
                </th>
                <th  align="center">
                    %
                </th>
                <?php while ($col <= ScaleTreshold::PRICE_COL_COUNT):?>
                    <th align="center">Опт <?= $col?></th>
                    <th align="center">%</th>
                    <?php $col++ ?>
                <?php endwhile;?>
            </tr>
            <?php foreach ($rate->getScale()->getTresholds() as $treshold):?>
                <tr>
                    <td align="right">
                        <?= round($treshold->getTreshold()) ?>
                    </td>
                    <td align="right">
                        <?= $treshold->getRetail() ?>
                    </td>
                    <td>
                        <?= round($treshold->getFormatRate()) ?>
                    </td>
                    <?php $priceCols = $treshold->getPriceCols(); $col = 1;?>
                    <?php while ($col <= ScaleTreshold::PRICE_COL_COUNT):?>
                        <td align="right"><?= $priceCols[$col]['price']?></td`>
                        <td align="center"><?= round($priceCols[$col]['percent'])?></td`>
                        <?php $col++ ?>
                    <?php endwhile;?>
                    <td>
                        <?= $treshold->getRounding() ?>
                    </td>
                </tr>
            <?php endforeach;?>
        </table>        
    </div>    
</div>

<?= $this->partial('\Admin\log\partial.phtml', ['logs' => $logs, 'ident' => 'rate', 'id' => $rate->getId()]) ?>        

<script type="text/javascript">
    /**
    * Промпт диалог
    *
    */
    function ratePromptDialog(url, initValue) {
        if (url){            
            bootbox.prompt({ 
                size: "medium",
                value: initValue,
                title: 'Наименование расценки', 
                callback: function(result){
                    /* result = String containing user input if OK clicked or null if Cancel clicked */
                    if (result != null){
                        $.ajax({
                            type: 'GET',
                            url: url+'?prompt='+result,
                        })
                            .done(function (data) {
                                if (data == 'ok'){
                                    window.location.reload();
                                }    
                            })
                            .fail(function (e) {
                                bootbox.alert("Произошла ошибка при выполнении операции.");
                            });
                    }        
                }
            });
        }        
    }    
    
    $('.rateStatusCheckbox').on('change', function(e, node) {
        var url = "/rate/update-rate-status";

        if (url){
            $.ajax({
                type: 'POST',
                url: url,
                data: {pk: e.target.value, value: e.target.checked}
            })
                .done(function (data) {
                })
                .fail(function () {
                    bootbox.alert("Произошла ошибка при выполнении операции.");
                });        
        }        
    })        
    
</script>