<?php

use Application\Entity\ScaleTreshold;

$this->headTitle($scale->getName());
$this->mainMenu()->setActiveItemId('raw');
$this->pageBreadcrumbs()->setItems([
            'Home' => $this->url('home'),
            'Расценка' => $this->url('rate'),
            $scale->getName() => $this->url('rate', ['action' => 'view-scale', 'id' => $scale->getId()]),
            ]);


$col = 1;
        
?>

<h1>
    <?= $this->escapeHtml($scale->getName()); ?>    
</h1>

<table class="table table-striped">
    <tr>
        <th rowspan="2"  align="center">
            Порог
        </th>
        <th colspan="12"  align="center">
            Цены и %% 
        </th>
        <th rowspan="2"  align="center">
            Округление
        </th>
    </tr>
    <tr>
        <th  align="center">
            Розница
        </th>
        <th  align="center">
            %
        </th>
        <?php while ($col <= ScaleTreshold::PRICE_COL_COUNT):?>
            <th align="center">Опт <?= $col?></th>
            <th align="center">%</th>
            <?php $col++ ?>
        <?php endwhile;?>
    </tr>
    <?php foreach ($scale->getTresholds() as $treshold):?>
        <tr>
            <td>
                <?= $treshold->getTreshold() ?>
            </td>
            <td align="right">
                <?= $treshold->getRetail() ?>
            </td>
            <td>
                <?= round($treshold->getFormatRate()) ?>
            </td>
            <?php $priceCols = $treshold->getPriceCols(); $col = 1;?>
            <?php while ($col <= ScaleTreshold::PRICE_COL_COUNT):?>
                <td align="right"><?= $priceCols[$col]['price']?></td`>
                <td align="center"><?= round($priceCols[$col]['percent'])?></td`>
                <?php $col++ ?>
            <?php endwhile;?>
            <td>
                <?= $treshold->getRounding() ?>
            </td>
        </tr>
    <?php endforeach;?>
</table>