
<script>
    $(document).on('click', '.comments-modal-show', function (e) {
        let orderId = $(this).attr('order-id');
        if (orderId){
            var url = $(this).attr('modal-url');
            showFormDialog({
                id: 'orderCommentsModal',
                url: url+orderId,
                zIndex: 8888
                //width: $(window).width()-250
            });
        };
    });  

    $(document).on('click', '.order-comment-modal-show', function (e) {
        var url = $(this).attr('modal-url');
        var orderId = $(this).attr('order-id');
        if (orderId){
            url += orderId;
        }
        showFormDialog({
            id: 'orderCommentModal',
            url: url,
            zIndex: 9999,
            width: $(window).width()-150
        });
    });  
</script>