<?php
    use Application\Entity\Oem;
?>
<table class="table table-striped table-condensed">

   <tr>
        <th>Номер</th>
        <th>Происзводитель</th>
        <th>Источник</th>
        <th></th>
    </tr>
    
    <?php foreach ($oems as $oem): ?>
    
        <tr <?= ($oem->getStatus() == Oem::STATUS_RETIRED) ? 'class="retired"':'' ?>>
            <td>
                <?= $oem->getOeNumber() ?>
            </td>
            <td>
                <?= $oem->getBrandName() ?>                
            </td>
            <td class="text-muted small">
                <?= $oem->getSourceAsString() ?>                                
            </td>
            <td>
            </td>
        </tr>
        
    <?php endforeach; ?>   
    
</table>
