<table class="table table-striped">

   <tr>
        <th>Цена</th>
        <th>Поставщик</th>
        <th>Наценка</th>
        <th>Маржа</th>
        <th>Наличие</th>
        <th>Мин.</th>
        <th>Дата прайса</th>
    </tr>
    
    <?php foreach ($goodSuppliers as $goodSupplier): ?>
    
        <tr>
            <td class="text-right">
                <?= round($goodSupplier->getPrice(), 0) ?>
            </td>
            <td>
                <?= $goodSupplier->getSupplier()->getName() ?>                
            </td>
            <td class="text-right">
                <?= $goodSupplier->getMarkup($goodSupplier->getGood()->getPrice()) ?>                                
            </td>
            <td class="text-right">
                <?= $goodSupplier->getMargin($goodSupplier->getGood()->getPrice()) ?>                                
            </td>
            <td class="text-right">
                <?= $goodSupplier->getRest() ?>
            </td>
            <td class="text-right">
                <?= $goodSupplier->getLot() ?>
            </td>
            <td>
                <?= $goodSupplier->getFormatUpdate(); ?>
            </td>
        </tr>
        
    <?php endforeach; ?>   
    
</table>
