<?php
use Application\Entity\Order;
use Application\Entity\Bid;

$this->headTitle('Заказы');
$this->mainMenu()->setActiveItemId('client');
$this->mainMenu()->setActiveUrl($this->url('order'));

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Заказы'=>$this->url('order'),
            ]);
?>    

<div class="row">
    <div class="col-md-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <a class="btn btn-default" type="button" href="<?= $this->url('order', ['action' => 'intro'])?>" tarhet="_blank">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </a>                
                <div class="form-group">
                    <div class="btn-group">
                        <input id="searchinput" name="search" style="width: 350px" class="form-control enter-search" type="text" placeholder="Артикул, VIN, телефон, email">
                        <span class="glyphicon glyphicon-remove-circle inputclear"></span>
                    </div>
                    <button id="ok" type="submit" class="btn btn-default" title="Поиск">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>    
                <div class="form-group">
                    <select id="officeSelect" style="width: 100px" class="form-control refresh-table cookie-control" name="officeId">
                        <option>все</option>
                        <?php foreach ($offices as $office):?>
                            <option value="<?= $office->getId()?>"><?= $office->getName()?></option>
                        <?php endforeach;?>
                    </select>                    
                </div>    
                <div class="form-group">
                    <select id="userSelect" style="width: 200px" class="form-control refresh-table cookie-control" name="userId">
                        <option>все</option>
                        <?php foreach ($users as $user):?>
                            <option value="<?= $user->getId()?>"><?= $user->getName()?></option>
                        <?php endforeach;?>
                    </select>
                </div>    
                <div class="form-group">
                    <select id="statusSelect" style="width: 200px" class="form-control refresh-table cookie-control" name="status">
                        <option>все</option>
                        <?php foreach (Order::getStatusList() as $key=>$value):?>
                            <option value="<?= $key?>"><?= $value?></option>
                        <?php endforeach;?>
                    </select>
                </div>    
<!--                <div class="form-group">
                    <input id="monthSelect" class="form-control" type="month" placeholder="Период" value="<?= date('Y-m');?>">
                </div>-->
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-cookie="true"
            data-cookie-id-table="orderSaveId"
            data-cookie-expire="1m"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="false"
            data-show-columns="true"
            data-query-params="queryParams"
            data-sort-name="dateOper"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="rowStyle"
            data-detail-view="true"
            data-detail-formatter="detailFormatter"
            >
            <thead>
                <tr>
                     <!--<th data-field="id" data-type="numeric" data-sortable="true" data-align="right">ID</th>-->
                     <th data-field="dateOper" data-sortable="true" data-width="50" data-formatter="dataFormatter">Дата</th>
                     <th data-field="id" data-sortable="false" data-width="50">Id</th>
                     <th data-field="aplId" data-sortable="false" data-width="50">Apl</th>
                     <th data-field="office.name" data-sortable="false" data-width="50">Офис</th>
                     <th data-field="contact.name" data-sortable="false" data-formatter="clientFormatter">Покупатель</th>
<!--                     <th data-field="contact.phones" data-sortable="false" data-formatter="phoneFormatter" data-width="50">Телефон</th>
                     <th data-field="contact.emails" data-sortable="false" data-formatter="emailFormatter" data-width="50">Почта</th>-->
                     <th data-field="info" data-sortable="false" data-formatter="infoFormatter">Что нужно</th>
                     <th data-field="contactCar.vin" data-sortable="false" data-formatter="carFormatter">Машина</th>
                     <th data-field="address" data-sortable="false" data-formatter="shippingFormatter">Доставка</th>
                     <th data-field="comments" data-sortable="false" data-formatter="commentFormatter">Комментарий</th>
                     <th data-field='total' data-sortable="false" data-align="right" data-formatter="inFormatter" data-width="100">Сумма</th>
                     <th data-field='user.fullName' data-sortable="false" data-width="50">Отв.</th>
                    <th data-field="id" data-formatter="activeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>  

<script type="text/javascript">
    var $table = $('#table').bootstrapTable({
        onLoadSuccess: function() {
            setCookies('orderSaveId');
        }, 
        onExpandRow: function (index, row, $detail) {
            $detail.html('Идет загрузка...');
            $.ajax({
                type: "GET",
                url: "/order/good-content/"+row.id,
                success: function (result) {
                    $detail.html('<table></table>').find('table').bootstrapTable({
                    classes: 'table table-bordered table-hover table-condensed', 
                    rowStyle: bidTakeStyle,
                    columns: [{
                        field: 'rowNo',
                        title: '№'
                    },{
                        field: 'good.code',
                        title: 'Артикул',
                        formatter: 'goodFormatter'                        
                    }, {
                        field: 'good.producer.name',
                        title: 'Производитель'
                    }, {
                        field: 'displayName',
                        title: 'Наименование'
                    }, {
                        field: 'num',
                        title: 'Количество',
                        width: 200,
                        align: 'right'
                    }, {
                        field: 'price',
                        title: 'Цена',
                        width: 200,
                        align: 'right'
                    }, {
                        field: 'amount',
                        title: 'Сумма',
                        width: 200,
                        align: 'right',
                        formatter: 'geAmountFormatter'
                    }],
                    data: result
                  });
                }
            });
        }
    });
    
    function setCookies(cookieKey){
        let expires = 30;
        $('.cookie-control').each(function () {
            Cookies.set(cookieKey+'_'+$(this).attr('id'), $(this).val(), { expires: expires});        
        });        
    }
    
    function getCookies(cookieKey){
        $('.cookie-control').each(function () {
            var cookieVal = Cookies.get(cookieKey+'_'+$(this).attr('id'));
            if (cookieVal !== undefined){
                $(this).val(cookieVal);                
            }
        });                        
        $table.bootstrapTable('refresh', {
            url: '/order/content'
        });
    }
    
    function refreshTable(){
        $table.bootstrapTable('refresh');
    }

    function officeChange(){
//        $.getJSON( '/accountant/office-cashes/'+$('#officeSelect').val(), function( data ) {
//            $('#userSelect').empty();
//            $.each( data.rows, function( key, value ) {
//                $('#userSelect').append('<option value="' + key + '">' + value.name + '</option>');
//            });            
//            refreshTable();
//        });    
    }

    $(function () {       
        getCookies('orderSaveId');
        
        $(".inputclear").click(function(){
            $("#searchinput").val('');
            refreshTable();
        });

        $(document).on('click', '.order-modal-show', function (e) {
            var url = $(e.currentTarget).attr('modal-url');
            showFormDialog({
                id: 'orderModal',
                url: url,
                width: $(window).width()-50
            });
        });  

        $('#ok').click(function () {
            refreshTable();
        });
        
        $(document).on('change', '.refresh-table', function (e) {
            refreshTable();
        });
        
        $(document).on('change', '#officeSelect', function (e) {
            officeChange();
        });
        
        $(document).on('change', '#userSelect', function (e) {
            $table.bootstrapTable('selectPage', 1);
        });        
    });
    
    function queryParams(params) {
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#table .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#table li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        params.office = $('#officeSelect').val();
        params.user = $('#userSelect').val();
        params.status = $('#statusSelect').val();
        return params;
    }

    function rowStyle(row){
        var retired = 'tablerow';
        if (row.status == '<?= Order::STATUS_CANCELED?>'){
           retired += ' retired';
        }
        switch(row.status){
            case '<?= Order::STATUS_SHIPPED?>': 
                        return {classes: 'success '+retired}; break;
            case '<?= Order::STATUS_DELIVERY?>': 
                        return {classes: 'info '+retired}; break;
            case '<?= Order::STATUS_CONFIRMED?>': 
                        return {classes: 'warning '+retired}; break;
                default:break;     
        }
        
        return {classes: retired};
    }
    
    function bidTakeStyle(row){
        var classes = 'default';
        if (row.take === "<?= Bid::TAKE_NO?>"){
            classes = 'warning';
        }        
        return {classes: classes};
    }    
    
    function goodFormatter(value, row){
        var url = '/goods/view/'+row.good.id;
        btn = '<nobr><a';
        btn += ' href="'+url+'"';
        btn += ' class="btn btn-link btn-xs" target="_blank">';
        btn += '<span class="glyphicon glyphicon-link"></span>';
        btn += '</a>'+value + '</nobr>';
        return btn;
    }    

    function geAmountFormatter(value, row){
        return (Math.round(row.price*row.num*100)/100).toFixed(0);
    }        
    
    function dataFormatter(value){
        return '<nobr>'+$.format.date(value, "dd.MM.yy")+'</nobr>';        
    }
    
    function clientFormatter(value, row){
        var result = [];
        var name = (value) ? value:'Nan';
        result.push('<a style="text-transform:capitalize" href="/contact/view/' + row.contact.id + '" target="_blank">' + name + '</a>');
        
        var phones = [];
        $.each(row.contact.phones, function( index, phone ) {
            phones.push(phone.name);
            if (phones.length > 1){
                return false;
            }
        });
        
        var emails = [];
        $.each(row.contact.emails, function( index, email ) {
            emails.push(email.name);
            return false;
        });
        if (phones.length || emails.length){
            result.push('<br/>');
            result.push(phones.join(';'));
            result.push('<nobr>'+emails.join(';')+'</nobr>');
        }    
        return result.join(' '); 
    }

    function infoFormatter(value, row){
        return value;
    }
    
    function carFormatter(value, row){
        var result = [];
        result.push(value);
        if (row.contactCar){
            if (row.contactCar.make){
                result.push(row.contactCar.make.name);
            }
        }
        return result.join(' ');
    }

    function shippingFormatter(value, row){
        var result = [];
        result.push(value);
        if (row.infoShipping){
            result.push(row.infoShipping);
        }
        if (row.shipmentTotal > 0){
            result.push(row.shipmentTotal);
        }
        if (row.skiper){
            result.push(row.skiper.fullName);
        }
        return result.join(' ');
    }

    function commentFormatter(value){
        var result = '';
        if (value.length){
            $.each(value, function( index, comment ) {
                result = comment.comment;
            });
            return [
                '(' + value.length + ')',
                result
            ].join(' ');
        }    
        return;    
    }

    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/producer/view/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function amountFormatter(value){
        return Math.round(value*100)/100;
    }
    
    function inFormatter(value){
        if (value>0){
            return Math.round(value*100)/100;
        }
        return;
    }    
    
    function outFormatter(value){
        if (value<0){
            return -Math.round(value*100)/100;
        }
        return;
    }    
        
    function activeFormatter(value, row){
        var url = '<?= $this->url('order', ['action' => 'intro'])?>/'+value;
        btn = '<a';
        btn += ' type="button"';
        btn += ' href="'+url+'"';
        btn += ' target="_blamk"';
        btn += ' class="btn btn-default btn-xs"';
        btn += ' aria-label="Left Align">'; 
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</a>';

        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }    
    
    function changeOrderStatus(orderId, status){
        $.get( "/order/status/"+orderId+'?status='+status, function(data){
            refreshTable();
        });        
    }

    var menu = new BootstrapMenu('.tablerow', {
        fetchElementData: function(rowElem) {
            var rowId = $(rowElem).attr('data-index');
            return $table.bootstrapTable('getData')[rowId];
        },
//        actionsGroups: [
//           ['statusActiv', 'statusRetired'],
//        ],      
        actions: {
            statusNew: {
                name: 'Новый',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_NEW?>);
                },
                isShown: function(row) {
                  return row.status != '<?= Order::STATUS_NEW?>';
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            }, 
            statusProcessed: {
                name: 'Обработан',
                classNames: 'bg-default',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_PROCESSED?>);
                },
                isShown: function(row) {
                  return row.status != '<?= Order::STATUS_PROCESSED?>';
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            }, 
            statusConfirmed: {
                name: 'Подтвержден',
                classNames: 'bg-warning',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_CONFIRMED?>);
                },
                isShown: function(row) {
                  return row.status != '<?= Order::STATUS_CONFIRMED?>';
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            }, 
            statusDelivery: {
                name: 'На доставке',
//                iconClass: 'glyphicon glyphicon-ok',
                classNames: 'bg-info',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_DELIVERY?>);
                },
                isShown: function(row) {
                  return row.status != <?= Order::STATUS_DELIVERY?>;
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            }, 
            statusShipped: {
                name: 'Отгружен',
                classNames: 'bg-success',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_SHIPPED?>);
                },
                isShown: function(row) {
                  return row.status != <?= Order::STATUS_SHIPPED?>;
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            },
            statusCanceled: {
                name: 'Отменен',
                classNames: 'bg-default',
                onClick: function(row) {
                    changeOrderStatus(row.id, <?= Order::STATUS_CANCELED?>);
                },
                isShown: function(row) {
                  return row.status != <?= Order::STATUS_CANCELED?>;
                },
                isEnabled: function(row) {
                    return row.dateOper > '<?= $allowDate?>';
                }                
            }
        }
    });    
    
</script>

