<?php
use Application\Entity\Order;
use Application\Entity\Shipping;

$this->headTitle(($orderId)?$orderId:'Новый');

$this->mainMenu()->setActiveItemId('client');
$this->mainMenu()->setActiveUrl($this->url('order'));


$form = $this->form;

$form->get('office')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Офис',
    ]);

$form->get('user')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Менеджер',
    ]);

$form->get('aplId')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Номер АПЛ',
    ]);

$form->get('skiper')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Водитель',
    ]);

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'style' => "text-transform:capitalize",
    'placeholder' => 'Имя',
    'required' => true,
    ]);

$form->get('phone')->setAttributes([
    'class'=>'form-control phone', 
    'placeholder' => 'Телефон',
    'required' => true,
    ]);

$form->get('phone2')->setAttributes([
    'class'=>'form-control phone', 
    'placeholder' => 'Телефон дополнительный',
    ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Email',
    ]);

$form->get('info')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Что нужно',
    'rows' => 4,
    ]);

$form->get('dateShipment')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Дата доставки/самовывоза',
    'title' => 'Дата доставки/самовывоза',
    'min' => ($orderId)? null:date('Y-m-d'),
    ]);

$form->get('timeShipment')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Время доставки/самовываза',
    'title' => 'Время доставки/самовывоза',
    ]);

$form->get('shipping')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Вариант доставки',
    ]);

$form->get('shipmentTotal')->setAttributes([
    'class'=>'form-control  select-on-focus', 
    'placeholder' => 'Стоимость доставки',
    ]);

$form->get('trackNumber')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Накладная ТК',
    ]);

$form->get('courier')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'ТК',
    ]);

$form->get('shipmentDistance')->setAttributes([
    'class'=>'form-control select-on-focus', 
    'placeholder' => 'КМ',
    ]);

$form->get('address')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Адрес доставки',
    'rows' => 1,
    ]);

$form->get('vin')->setAttributes([
    'class' => 'form-control', 
    'style' => "text-transform:uppercase",
    'placeholder' => 'VIN',
    ]);

$form->get('make')->setAttributes([
    'class'=>'form-control', 
    'style' => "text-transform:none",
    'data-provide' => "typeahead",
    'placeholder' => 'Марка машины',
    ]);

$form->get('makeComment')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Дополнительно о машине',
    ]);

$form->get('note')->setAttributes([
    'class'=>'form-control', 
    'placeholder' => 'Комментарий менеджера',
    ]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Сохранить', 'id' => 'order-submit']);

$form->prepare();

?>
            
<?= $this->form()->openTag($form); ?>
<div class="col-xs-9">
    <div class="row">
        <div class="col-xs-2">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('phone')); ?>
                <div class="input-group">
                    <?= $this->formElement($form->get('phone')); ?>
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-default btn-sm sms-message-modal-show" modal-url="/admin/sms-form/" title="Отправить сообщение">
                            <span class="glyphicon glyphicon-envelope"></span>
                        </button>
                    </span>    
                </div>    
                <?php echo $this->partial('/admin/index/sms-partial', ['phoneNode' => 'phone', 'idNode' => 'orderId']); ?>
                <?= $this->formElementErrors($form->get('phone')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('office')); ?>
                <?= $this->formElement($form->get('office')); ?>
                <?= $this->formElementErrors($form->get('office')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('user')); ?>
                <?= $this->formElement($form->get('user')); ?>
                <?= $this->formElementErrors($form->get('user')); ?>                  
            </div>
        </div>    
        <div class="col-xs-1">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('aplId')); ?>
                <?= $this->formElement($form->get('aplId')); ?>
                <?= $this->formElementErrors($form->get('aplId')); ?>                  
            </div>
        </div>    
    </div>    
    <div class="row">
        <div class="col-xs-3">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('vin')); ?>
                <div class="input-group">
                    <?= $this->formElement($form->get('vin')); ?>
                    <div class="input-group-addon" id="vinLength">0</div>
                </div>
                <?= $this->formElementErrors($form->get('vin')); ?>                  
            </div>
        </div>    
        <div class="col-xs-3">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('make')); ?>
                <?= $this->formElement($form->get('make')); ?>
                <?= $this->formElementErrors($form->get('make')); ?>                  
            </div>
        </div>                    
        <div class="col-xs-6">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('makeComment')); ?>
                <?= $this->formElement($form->get('makeComment')); ?>
                <?= $this->formElementErrors($form->get('makeComment')); ?>                  
            </div>
        </div>                            
    </div>
    <div class="row">
        <div class="col-xs-6">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('info')); ?>
                <?= $this->formElement($form->get('info')); ?>
                <?= $this->formElementErrors($form->get('info')); ?>                  
            </div>
        </div>                    
        <div class="col-xs-5">     
            <div class="form-group form-group-sm">
                <?php echo $this->partial('/application/comment/order-partial', ['comments' => $comments]); ?>
            </div>    
        </div>    
        <div class="col-xs-1 text-right">     
            <div class="form-group form-group-sm">
                <button type="button" class="btn btn-default btn-sm order-comment-modal-show" 
                        title="Добавить комментарий" modal-url="/comments/edit-local-form">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            </div>
        </div>    
    </div>        
    <div class="row">
        <div class="col-xs-12">
            <div id="ordergoodtoolbar">
                <div class="form-inline" role="form">
                    <div class="form-group form-group-sm">
                        <span class="label label-default" id="orderQuantity"></span>
                    </div>    
                    <div class="form-group form-group-sm">
                        <span class="label label-primary" id="shippingTotal"></span>
                    </div> +    
                    <div class="form-group form-group-sm">
                        <span class="label label-primary" id="bidTotal"></span>
                    </div> =   
                    <div class="form-group form-group-sm">
                        <span class="label label-primary" id="orderAmount"></span>                        
                    </div>    
                    <div class="form-group form-group-sm">
                        <button type="button" class="btn btn-default btn-sm order-good-modal-show" modal-url="/order/good-edit-form" title="Добавить товар">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </button>
                    </div>    
                </div>
            </div>
            <table id="ordergoodtable" 
                data-toggle="ordergoodtable" 
                data-url="/order/good-content/<?= ($orderId) ? $orderId:""?>"
                data-side-pagination="client"
                data-pagination="true"
                data-icon-size="sm"
                data-page-size = "100"
                data-page-list="[100, 200]"
                data-toolbar="#ordergoodtoolbar"
                data-toolbar-align="right"
                data-query-params="ordergoodQueryParams"
                data-response-handler="ordergoodResponseHandler"
                data-classes = "table table-bordered table-hover table-condensed"
                data-unique-id = "rowNo"                
                >
                <thead>
                    <tr>
                         <th data-field="rowNo" data-type="numeric" data-align="right" data-width="10">N</th>
                         <th data-field="good.code" data-width="150" data-formatter="goodFormatter">Артикул</th>
                         <th data-field="good.producer.name" data-type="numeric" data-width="100">Производитель</th>
                         <th data-field="displayName" data-formatter="geNameFormatter" data-editable="true">Наименование</th>
                         <th data-field='price' data-formatter="gePriceFormatter" data-editable="true" data-type="numeric" data-always-use-formatter="true" data-align="right" data-width="100">Цена</th>
                         <th data-field='num' data-align="right" data-editable="true" data-type="numeric" data-always-use-formatter="true" data-width="50">Количество</th>
                         <th data-field='amount' data-align="right" data-formatter="geAmountFormatter" data-always-use-formatter="true" data-type="numeric" data-width="100">Сумма</th>
                         <th data-field="rowNo" data-formatter="geActiveFormatter" data-width="10"></th>
                         <th data-field="rowNo" data-formatter="grActiveFormatter" data-width="10"></th>
                     </tr>                
                </thead>
            </table>
        </div>
    </div>    
    <hr/>
    <div class="row">
        <div class="col-xs-2">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('dateShipment')); ?>
                <?= $this->formElement($form->get('dateShipment')); ?>
                <?= $this->formElementErrors($form->get('dateShipment')); ?>                  
            </div>
        </div>
        <div class="col-xs-1">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('timeShipment')); ?>
                <?= $this->formElement($form->get('timeShipment')); ?>
                <?= $this->formElementErrors($form->get('timeShipment')); ?>                  
            </div>
        </div>
        <div class="col-xs-3">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('shipping')); ?>
                <?= $this->formElement($form->get('shipping')); ?>
                <?= $this->formElementErrors($form->get('shipping')); ?>                  
            </div>
        </div>
        <div class="col-xs-1">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('shipmentDistance')); ?>
                <?= $this->formElement($form->get('shipmentDistance')); ?>
                <?= $this->formElementErrors($form->get('shipmentDistance')); ?>                  
            </div>
        </div>
        <div class="col-xs-1">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('shipmentTotal')); ?>
                <?= $this->formElement($form->get('shipmentTotal')); ?>
                <?= $this->formElementErrors($form->get('shipmentTotal')); ?>                  
            </div>
        </div>
        <div class="col-xs-2">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('courier')); ?>
                <?= $this->formElement($form->get('courier')); ?>
                <?= $this->formElementErrors($form->get('courier')); ?>                  
            </div>
        </div>
        <div class="col-xs-2">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('trackNumber')); ?>
                <?= $this->formElement($form->get('trackNumber')); ?>
                <?= $this->formElementErrors($form->get('trackNumber')); ?>                  
            </div>
        </div>
    </div>        
    <div class="row">
        <div class="col-xs-8">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('address')); ?>
                <?= $this->formElement($form->get('address')); ?>
                <?= $this->formElementErrors($form->get('address')); ?>                  
            </div>
        </div>
        <div class="col-xs-2">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('phone2')); ?>
                <?= $this->formElement($form->get('phone2')); ?>
                <?= $this->formElementErrors($form->get('phone2')); ?>                  
            </div>
        </div>    
        <div class="col-xs-2">                        
            <div class="form-group form-group-sm">
                <?//= $this->formLabel($form->get('skiper')); ?>
                <?= $this->formElement($form->get('skiper')); ?>
                <?= $this->formElementErrors($form->get('skiper')); ?>                  
            </div>
        </div>    
    </div>        
</div>
<div class="col-xs-3">
    <button type="submit" class="btn btn-primary btn-sm" id="order-submit">Сохранить</button>    
    <button type="button" class="btn btn-secondary btn-sm" id="order-reset">Закрыть</button>
</div>

<?= $this->formElement($form->get('orderId')); ?>            
<?= $this->formElement($form->get('contact')); ?>            
<?= $this->formElement($form->get('rate')); ?>            
<?= $this->formElement($form->get('shipmentRate')); ?>            
<?= $this->formElement($form->get('shipmentRate1')); ?>            
<?= $this->formElement($form->get('shipmentRate2')); ?>            
<?= $this->formElement($form->get('shippingLimit1')); ?>            
<?= $this->formElement($form->get('shippingLimit2')); ?>            
<?= $this->formElement($form->get('rateDistance')); ?>            
<?//= $this->formElement($form->get('csrf')); ?>            
<?= $this->form()->closeTag(); ?>
            
<script>
    var table = $('#ordergoodtable');
    
    set_onbeforeunload = function(){
            return true;
    };
    
    $('.phone').mask('8 (000) 000-0000', {selectOnFocus: true});
    
    function setTextValue(node, value, clear = false)
    {
        if (!$(node).val()){
            $(node).val(value);
            if (clear){
                $(node).next().toggle(Boolean($(node).val()));
            }    
        }           
    }

    $('.phone').on('input', function(){
        var value = $( this ).val();
        if (value.length == 16){
            $.post('/ring/find-phone', {phone: value}, function (data) {
                if (data){
                    setTextValue('#contact', data.contact);
                    setTextValue('#name', data.name, true);
                    setTextValue('#email', data.email, true);
                    if (data.cars){
                        setTextValue('#make', data.cars[0].id);
                        setTextValue('#vin', data.cars[0].vin, true);
                        $("#vinLength").html($("#vin").val().length);
                        setTextValue('#make', data.cars[0].makeName, false);
                    }    
//                        $.each(data.cars, function( i, car ){
//                        });                    
                }    
            })
        }    
    });    
    
    $('#vin').on('input', function(){
        $("#vinLength").html($("#vin").val().length);
    });
    
    $('#make').typeahead({
        source: function(query, process) {
            return $.get("/make/autocomplete?q="+query, function (data) {
                return process(data);
            });
        },
        changeInputOnSelect: true,
    });
    
    $(document).on('click', '.order-good-modal-show', function (e) {
        var url = $(e.currentTarget).attr('modal-url');
        var uniqueId = $(e.currentTarget).attr('unique-id');
        if (uniqueId){
            var row = $('#ordergoodtable').bootstrapTable('getRowByUniqueId', uniqueId);
            url = url+'?'+$.param(row);
        }    
        showFormDialog({
            id: 'orderGoodModal',
            url: url,
            zIndex: 9999
        });
    });  
    
    function submitForm(){
        window.onbeforeunload = false;
        var data = serializeForm('#order-form');
        data.orderGood = getFormatedOrderGood();
        data.comments = getUnsavedOrderComments();
        $.ajax({
            type: 'POST',
            url: '/order/intro/'+$('#orderId').val(),
            data: $.param(data)
        })
            .done(function (data) {
                if (data.id){
                    document.title = data.id;
                    $('#orderId').val(data.id);
                    $('#aplId').val(data.aplId);
                    $('#contact').val(data.contact);
                    enableSms();
                }    
            })
            .fail(function () {
                alert("Ошибка при открытии формы.");

            });    
    };
    
    function getFormatedOrderGood(){
        var data = $('#ordergoodtable').bootstrapTable('getData');
        var result = [];
        $.each( data, function( index, row ) {
            var newRow = {
                good: row.good.id,
                displayName: row.displayName,
                num: row.num,
                price: row.price
            };
            result.push(newRow);
        });   
        return result;
    }

    function getUnsavedOrderComments(){
        var result = [];
        $(".new-manager-comment").each(function( index ) {
            if ($(this).text()){
                var newComment = {
                    comment: $(this).text(),
                };
                result.push(newComment);
            }
            $(this).removeClass('new-manager-comment');
        });        
        return result;
    }

    function bidTotal(){
        var amount = 0;
        var data = $('#ordergoodtable').bootstrapTable('getData');
        $.each(data, function( index, value ) {
            amount += Math.round(value.price*value.num*100)/100;
        });
        $('#bidTotal').html(amount);            
        return amount;
    }
    
    function shippingUpdate(){
        let rate = Number($('#rate').val());
        let shipmentRate = Number($('#shipmentRate').val());
        let shipmentRate1 = Number($('#shipmentRate1').val());
        let shipmentRate2 = Number($('#shipmentRate2').val());
        let shippingLimit1 = Number($('#shippingLimit1').val());
        let shippingLimit2 = Number($('#shippingLimit2').val());
        let rateDistance = Number($('#rateDistance').val());
        let distance = Number($('#shipmentDistance').val());
        let totalBid = bidTotal();
        if (rate != <?= Shipping::RATE_TK?>){
            if (shippingLimit1 > 0 && totalBid>=shippingLimit1){
                shipmentRate=shipmentRate1;
            }
            if (shippingLimit2 > 0 && totalBid>=shippingLimit2){
                shipmentRate=shipmentRate2;
            }
        }    
        $('#shipmentTotal').val(shipmentRate + rateDistance*distance);    
        $('#shippingTotal').html($('#shipmentTotal').val());    
        orderUpdateTotal();
    }
    
    function shippingParams(){
        $('#shipmentRate').val(0);
        $('#rateDistance').val(0);        
        $('#shipmentDistance').val(0);        
        $('#shipmentTotal').val(0);
        $('#shipmentRate1').val(0);        
        $('#shipmentRate2').val(0);        
        $('#shippingLimit1').val(0);        
        $('#shippingLimit2').val(0);        
        let shipping = $('#shipping').val();        
        $('#shipmentDistance').attr('disabled', true);
        $('#trackNumber').attr('disabled', true);
        $('#courier').attr('disabled', true);
        if (shipping > 0){
            $.get('/order/shipping/'+shipping, function(data){
                $('#rate').val(data.rate);
                switch(data.rate){
                    case '<?= Shipping::RATE_TK?>':
                        $('#trackNumber').attr('disabled', false);
                        $('#courier').attr('disabled', false);
                        break;
                    case '<?= Shipping::RATE_DISTANCE?>':
                        $('#shipmentDistance').attr('disabled', false);
                        $('#rateDistance').val(data.rateDistance);        
                    case '<?= Shipping::RATE_TRIP?>':
                        $('#shipmentRate1').val(data.rateTrip1);        
                        $('#shipmentRate2').val(data.rateTrip2);        
                        $('#shippingLimit1').val(data.shippingLimit1);        
                        $('#shippingLimit2').val(data.shippingLimit2);        
                    default:     
                        $('#shipmentRate').val(data.rateTrip); break;
                    };
                shippingUpdate();    
            });    
        }    
    }
    
    function shippingList(){
        //alert(11);
        $.getJSON( '/order/shippings/'+$('#office').val(), function( data ) {
            $('#shipping').empty();
            $.each( data.rows, function( key, value ) {
                $('#shipping').append('<option value="' + value.id + '">' + value.name + '</option>');
            });
            shippingParams();
        });    
    }

    function contractList(){
        //alert(11);
        $.getJSON( '/contracts/select/?company='+$('#company').val()+'&legal='+$('#legal').val(), function( data ) {
            $('#contract').empty();
            $.each( data.rows, function( key, value ) {
                $('#contract').append('<option value="' + key + '">' + value.name + '</option>');
            });
        });    
    }

    function enableSms(){
        let aplId = Number($('#aplId').val());
        $('.sms-message-modal-show').attr('disabled', !aplId);
    }
    
    $(document).on('editable-save.bs.table', '#ordergoodtable', function (e, field, row, old, $el) {
        shippingUpdate();
    });        
    
    $('#office').on('change', function(){
        shippingList();        
    });

    $('#shipping').on('change', function(){
        shippingParams();        
    });

    $('#shipmentDistance').on('change', function(){
        shippingUpdate();        
    });

    $('#shipmentTotal').on('change', function(){
        $('#shippingTotal').html($('#shipmentTotal').val());
        orderUpdateTotal();        
    });
    
    $('#plusGood').on('click', function(){
        insertGood();        
    });

    $('#company').on('change', function(){
        contractList();
    });    
    
    $('#legal').on('change', function(){
        contractList();
    });
    
    function orderUpdateTotal(){
        var amount = 0; var num = 0;
        let shipmentTotal = Number($('#shipmentTotal').val());
        var data = $('#ordergoodtable').bootstrapTable('getData');
        $.each(data, function( index, value ) {
            amount += Math.round(value.price*value.num*100)/100;
            num += Math.round(value.num*100)/100; 
        });
        $('#orderAmount').html((Math.round((amount + shipmentTotal)*100)/100).toFixed(0));
        $('#orderQuantity').html((Math.round(num*100)/100).toFixed(0));
    }
    
    //удаление строки из таблицы
    function removeTableRowByUniqueId(index){
        $('#ordergoodtable').bootstrapTable('removeByUniqueId', index);
        orderUpdateTotal();
    }
    
    $( document ).ready(function() {
        
	$(document).on('input', ':input', function() {
		window.onbeforeunload = set_onbeforeunload;
	});

        $('.select-on-focus').on('click', function () {
            if ($(this).val() == '0'){
                $(this).select();
            }
        });
        
        $('#ordergoodtable').bootstrapTable({
            onLoadSuccess: function(res){
                $('#shippingTotal').html($('#shipmentTotal').val());    
                bidTotal();
                orderUpdateTotal();
            }            
        }); 
        
        enableSms();
        
        <?php if (!$orderId): ?>
            shippingParams();    
        <?php endif; ?>    
        
        var forms = $('#order-form');
        
        forms.submit(function() {
            submitForm();
            return false;
        });
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('order-submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                submitForm();
            }, false);    
        });
    });    
    
    function orderGoodRefreshTable(){
        $('#ordergoodtable').bootstrapTable('refresh');
    }
    
    function ordergoodQueryParams(params) {
        $('#ordergoodtoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#ordergoodtable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#ordergoodtable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function goodFormatter(value, row){
        var url = '/goods/view/'+row.good.id;
        btn = '<nobr><a';
        btn += ' href="'+url+'"';
        btn += ' class="btn btn-link btn-xs" target="_blank">';
        btn += '<span class="glyphicon glyphicon-link"></span>';
        btn += '</a>'+value + '</nobr>';
        return btn;
    }    

    function geNameFormatter(value, row){
        if (value) return value;
        if (row.good.tokenGroup.name) return row.good.tokenGroup.name;        
        if (row.good.name) return row.good.name; 
        if (row.good.description)return row.good.description;
        return 'Нет названия';
    }    
    
    function geActiveFormatter(value, row){
        var url = '/order/good-edit-form/';
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs order-good-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' unique-id="'+value+'"';
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';

        return btn;
    }    
    function grActiveFormatter(value, row){
        let btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-danger btn-xs table-row-remove"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' onclick="removeTableRowByUniqueId('+value+')">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function gePriceFormatter(value){
        return (Math.round(value)).toFixed(0);
    }        

    function geAmountFormatter(value, row){
        return (Math.round(row.price*row.num*100)/100).toFixed(0);
    }        
    
    function ordergoodResponseHandler(res) {
        return res;
    }     
</script>