<?php
?>
<table class="table table-striped table-condensed">

   <tr>
        <th>Товар</th>
        <th>Количество</th>
        <th>Поставщик</th>
        <th>Заказно</th>
        <th>Получено</th>
    </tr>
    
    <?php foreach ($supplierOrders as $supplierOrder): ?>
    
        <tr>
            <td>
                <?= $supplierOrder->getGood()->getCode().' '.$supplierOrder->getGood()->getProducer()->getName() ?>
            </td>
            <td align="right">
                <?= $supplierOrder->getQuantity() ?>                
            </td>
            <td>
                <nobr>
                    <a href="#" class="btn btn-link btn-xs supplier-link" supplier-id="<?= $supplierOrder->getSupplier()->getId()?>" title="Перейти на сайт поставщика">
                        <span class="glyphicon glyphicon-link"></span>
                    </a>
                    <a href="/supplier/view/<?= $supplierOrder->getSupplier()->getId()?>" target="_blank"><?= $supplierOrder->getSupplier()->getName() ?></a>
                </nobr>
            </td>
            <td class="text-muted small">
                <?= $supplierOrder->getStatusOrderAsString() ?>
            </td>
            <td class="text-muted small">
                <?= $supplierOrder->getStatusAsString() ?>
            </td>
        </tr>
        
    <?php endforeach; ?>   
    
</table>
