<?php
use Application\Entity\Order;  
use Stock\Entity\Vt;
use Application\Entity\Bid;
use Laminas\Json\Encoder;

$vtDisabled = ($order->getStatus() == Order::STATUS_SHIPPED) ? '':'disabled';
?>
<div class="modal-header">
    <div class="row">
        <div class="col-md-6">
            <h5>
                <div><?= 'Заказ №'.$order->getDocNo().' от '. date('d.m.Y H:i:s', strtotime($order->getDocDate())); ?> 
                    <?= $order->getOffice()->getName()?>
                </div>
                <div>
                    <a href="/client/view/<?= $order->getContact()->getClient()->getId()?>" target="_blank">
                        <?= $this->escapeHtml(($order->getContact()->getName()) ? $order->getContact()->getName():'Nan'); ?>
                    </a>    
                </div>
                <div class="text-muted"><h6>
                    <a href="#" class="order-legal" modal-url="/order/order-legal-form/<?= $order->getId()?>">
                        <?= ($order->getLegal()) ? $order->getLegal()->getName():'+ ЮЛ'; ?>
                    </a></h6>    
                </div>
            </h5>
        </div>
        <div class="col-md-2">
            <h4>
                Доставка: 
                <b id="shipmentTotal"><?= $order->getShipmentTotal()?></b>                
            </h4>
        </div>    
        <div class="col-md-2">
            <h4>
                Товаров: 
                <b id="orderQuantity"></b>                
            </h4>
        </div>    
        <div class="col-md-2">
            <h4>
                Итого: 
                <b id="orderAmount"><?= $order->getTotal()?></b>                
            </h4>
        </div>    
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div id="ordergoodtoolbar">
            <div class="form-inline" role="form">
                <a href="/order/intro/<?= $order->getId()?>" class="btn btn-default btn-sm" type="button" title="Редактировать" target="_blank">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> <?= $order->getId()?>
                </a>                
                <a href="https://autopartslist.ru/admin/orders/view/id/<?= $order->getAplId()?>" 
                   class="btn btn-default btn-sm" type="button" title="АПЛ ссылка" target="_blank"
                   <?= ($order->getAplId()) ? '':'disabled' ?>>
                    <span class="glyphicon glyphicon-link" aria-hidden="true"></span> <?= $order->getAplId()?>
                </a>                
                <button class="btn btn-default btn-sm order-repost" type="button" title="Перепровести">
                    <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                </button>                
                <button class="btn btn-default btn-sm bid-row-copy" type="button" title="Копировать выделенные строки">
                    <span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span>
                </button>                
                <button type="button" class="btn btn-default btn-sm supplier-order">
                    <span class="glyphicon" aria-hidden="true">Заказано</span>
                </button>
            </div>
        </div>
        <table id="ordergoodtable" 
            data-toggle="ordergoodtable" 
            data-url="/order/good-content/<?= $order->getId()?>"
            data-side-pagination="client"
            data-pagination="true"
            data-cookie="true"
            data-cookie-id-table="orderViewSave<?= $order->getId()?>"
            data-cookie-expire="1m"
            data-show-refresh="true"
            data-icon-size="sm"
            data-page-size = "100"
            data-page-list="[100, 200]"
            data-toolbar="#ordergoodtoolbar"
            data-toolbar-align="left"
            data-show-columns="true"
            data-query-params="ordergoodQueryParams"
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-unique-id = "id"                
            data-click-to-select="true"
            data-id-field = "id"
            data-editable-url = "/order/bid-editable/"
            data-row-style="bidTakeStyle"
            >
            <thead>
                <tr>
                    <th data-checkbox="true"></th>
                    <th data-field="rowNo" data-type="numeric" data-align="right" data-width="10">N</th>
                    <th data-field="good.code" data-width="150" data-formatter="goodFormatter">Артикул</th>
                    <th data-field="good.producer.name" data-type="numeric" data-width="150">Производитель</th>
                    <th data-field="displayName" data-formatter="geNameFormatter" data-editable="true">Наименование</th>
                    <th data-field='price' data-formatter="gePriceFormatter" data-editable="true" data-type="numeric" data-align="right" data-width="100">Цена</th>
                    <th data-field='num' data-align="right" data-editable="true" data-type="numeric" data-width="50">Кол-во</th>
                    <th data-field='amount' data-align="right" data-formatter="geAmountFormatter" data-type="numeric" data-width="100">Сумма</th>
                    <th data-field="baseKey" data-visible="false" data-editable="true" data-editable-type="select" data-editable-source="/order/find-base/<?= $order->getId()?>" data-width="10">Партия</th>
                    <th data-field="active1" data-formatter="grActiveFormatter" data-width="10">Д</th>
                 </tr>                
            </thead>
        </table>        
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div id="vttoolbar">
            <div class="form-inline" role="form">
                <button <?= $vtDisabled?> class="btn btn-default btn-sm vt-modal-show" type="button" modal-url="/vt/edit-form?order=<?= $order->getId()?>">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Добавить возврат
                </button>                
            </div>
        </div>
        <table id="vttable" 
            data-toggle="vttable" 
            data-url="/vt/content/<?= ($order) ? $order->getId():"" ?>"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#vttoolbar"
            data-icon-size="sm"
            data-show-refresh="true"
            data-query-params="vtQueryParams"
            data-sort-name="id"
            data-sort-order="desc"            
            data-response-handler="responseHandler"
            data-classes = "table table-bordered table-hover table-condensed"
            data-row-style="vtRowStyle"
            >
            <thead>
                <tr>
                    <th data-field="id" data-sortable="false" data-formatter="idFormatter" data-width="100">Номер</th>
                    <th data-field="docDate" data-sortable="true" data-formatter="dateFormatter" data-width="100">Дата</th>
                    <!--<th data-field="aplId" data-type="numeric" data-align="right">AplId</th>-->
                    <th data-field='amount' data-sortable="false" data-type="numeric" data-align="right" data-formatter="amountFormatter">Сумма</th>
                    <th data-field='order.aplId' data-sortable="false" data-formatter="linkFormatter">Заказ</th>
                    <th data-field='office.name' data-sortable="false">Склад</th>
                    <th data-field='status' data-sortable="false" data-formatter="statusFormatter">Статус</th>
                    <th data-field='comment' data-sortable="false">Примечание</th>
                    <th data-field="" data-formatter="activeFormatter" data-width="10"></th>
                 </tr>                
            </thead>
        </table>
    </div>
</div>    

<div class="modal-footer">
    <button type="button" class="btn btn-secondary order-view-close" data-dismiss="modal">Закрыть</button>
</div>

<script>
    function orderUpdateTotal(){
        var amount = 0; var num = 0;
        let shipmentTotal = Number($('#shipmentTotal').val());
        var data = $('#ordergoodtable').bootstrapTable('getData');
        $.each(data, function( index, value ) {
            amount += Math.round(value.price*value.num*100)/100;
            num += Math.round(value.num*100)/100; 
        });
        $('#orderAmount').html((Math.round((amount + shipmentTotal)*100)/100).toFixed(0));
        $('#orderQuantity').html((Math.round(num*100)/100).toFixed(0));
    }
    
    function getBids(){
        var data = $('#ordergoodtable').bootstrapTable('getData');
        var result = [];
        $.each( data, function( index, row ) {
            var newRow = {
                good: row.good.id,
                displayName: row.displayName,
                num: row.num,
                price: row.price,
                oem: row.oem,
                baseKey: row.baseKey
            };
            result.push(newRow);
        });   
        return result;
    }
    
    function updateBids(orderId){
        var postData = {bids: getBids()};
        $.ajax({
            type: 'POST',
            url: '/order/update-bids/'+orderId,
            data: $.param(postData)
        })
            .done(function (data) {
                $('#ordergoodtable').bootstrapTable('refresh');
            })
            .fail(function (message) {
                alert(message);
            });        
    }
    
    //удаление строки из таблицы
    function removeTableRowByUniqueId(index){
        $('#ordergoodtable').bootstrapTable('removeByUniqueId', index);
        orderUpdateTotal();
    }
    
    function repostOrder(orderId){
        $.get( "/order/repost/"+orderId, function(data){
            $('#ordergoodtable').bootstrapTable('refresh');
        });        
    }
    
    $( document ).ready(function() {        
        $('#ordergoodtable').bootstrapTable({
            onLoadSuccess: function(res){
//                bidTotal();
                orderUpdateTotal();
            }            
        }); 
        
        $('#vttable').bootstrapTable({
            onLoadSuccess: function(res){
                
            }            
        });         
        
        $(document).on('editable-save.bs.table', '#ordergoodtable', function (e, field, row, old, $el) {
            orderUpdateTotal();
        });        
        
        $(document).on('click', '.order-view-close', function (e) {
            $('#ordergoodtable').bootstrapTable('destroy');
            $('#vttable').bootstrapTable('destroy');
            $('#ordergoodtoolbar').remove();
            $('#vttoolbar').remove();
//            $('#orderViewModal').modal('hide');
        });        

        $(document).on('click', '.order-repost', function (e) {
            repostOrder(<?= $order->getId()?>);
        });        
        
        $(document).on('click', '.bid-row-copy', function (e) {
            var selections = $('#ordergoodtable').bootstrapTable('getSelections');
            if (selections.length){
                $.each( selections, function( index, row ) {
                    $('#ordergoodtable').bootstrapTable('insertRow', {index: 1, row: row});
                });  
                $('#ordergoodtable').bootstrapTable('uncheckAll');
                updateBids(<?= $order->getId()?>);
            }    
        });      
        
        $(document).on('click', '.bid-row-delete', function (e) {
            var id = $(this).attr('value');
            if (id){
                var row = $('#ordergoodtable').bootstrapTable('getRowByUniqueId', id);
                if (confirm('Удалить '+row.good.code+'?')){
                    $('#ordergoodtable').bootstrapTable('removeByUniqueId', id);
                } 
            }
            updateBids(<?= $order->getId()?>);
        });        
        
        $(document).on('click', '.supplier-order', function (e) {
            $.get( '/order/supplier-orders/<?= $order->getId()?>', function( data ) {
                bootbox.dialog({
                    title: 'Заказано у поставщиков',
                    message: data,
                    size: 'large',
                    buttons: {
                        ok: {
                            label: "OK",
                            className: 'btn-info'
                        }                    
                    }
                }); 
            });    
        });            
    });    

    function ordergoodQueryParams(params) {
        $('#ordergoodtoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#ordergoodtable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#ordergoodtable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function vtQueryParams(params) {
        $('#vttoolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('#vttable .page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('#vttable li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        
        return params;
    }
    
    function bidTakeStyle(row){
        var classes = 'default';
        if (row.take === "<?= Bid::TAKE_NO?>"){
            classes = 'warning';
        }        
        return {classes: classes};
    }

    function vtRowStyle(row){
        var retired = 'tablerow';
        if (row.status === '<?= Vt::STATUS_RETIRED?>'){
           retired += ' retired';
        }
        if (row.status === '<?= Vt::STATUS_COMMISSION?>'){
           retired += ' info';
        }
        if (row.status === '<?= Vt::STATUS_DEFECT?>'){
           retired += ' info';
        }
        if (row.status === '<?= Vt::STATUS_WAIT?>'){
           retired += ' info';
        }
        if (row.statusAccount === '<?= Vt::STATUS_TAKE_NO?>'){
           retired = ' warning';
        }
        
        return {classes: retired};
    }

    function goodFormatter(value, row){
        var url = '/goods/view/'+row.good.id;
        btn = '<nobr><a';
        btn += ' href="'+url+'"';
        btn += ' class="btn btn-link btn-xs" target="_blank">';
        btn += '<span class="glyphicon glyphicon-link"></span>';
        btn += '</a>'+value + '</nobr>';
        return btn;
    }    

    function geNameFormatter(value, row){
        if (value) return value;
        if (row.good.tokenGroup){
            if (row.good.tokenGroup.name) return row.good.tokenGroup.name;        
        }    
        if (row.good.name) return row.good.name; 
        if (row.good.description)return row.good.description;
        return 'Нет названия';
    }    
        
    function grActiveFormatter(value, row){
        let btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs bid-row-delete"';
        btn += ' aria-label="Left Align"'; 
        btn += ' title="Удалить"'; 
        btn += ' value="'+row.id+'">';
        btn += '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }    
    
    function gePriceFormatter(value){
        return (Math.round(value)).toFixed(0);
    }        

    function geAmountFormatter(value, row){
        return (Math.round(row.price*row.num*100)/100).toFixed(0);
    }        
    
    function idFormatter(value, row){
        if (row.aplId > 0){
            return '<nobr>' + value + ' ('+row.aplId+')</nobr>';
        }
        
        return value;
    }    
    
    function dateFormatter(value){
        var date = new Date(value);
        return $.format.date(date, "dd.MM.yyyy");
    }
    
    function linkFormatter(value, row){
        if (!value){
            value = '---';
        }
        return [
            '<div class="pull-left">',
            '<a href="/order/intro/' + row.id + '" target="_blank">' + value + '</a>',
            '</div>'
        ].join(''); 
    }    
    
    function amountFormatter(value){
        return (Math.round(value*100)/100).toFixed(2);
    }    
    
    function statusFormatter(value){
        var result = <?= Encoder::encode(Vt::getStatusList())?>;
        return result[value];
    }

    function activeFormatter(value, row){
        var url = '/vt/edit-form/'+row.id;
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn btn-default btn-xs vt-modal-show"';
        btn += ' aria-label="Left Align"'; 
        btn += ' modal-url="'+url+'">';
        btn += '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>';
        btn += '</button>';

        return btn;
    }    
    
    function responseHandler(res) {
        return res;
    }         
</script>
